### ISSUE TITLE
Restore Tree state after reload

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10017]
Need an option to restore expanded state of tree nodes after data reload/ tab reopen.
[Forum post](https://forum.bryntum.com/viewtopic.php?p=154353#p154353)

Hi Team ,
I am trying to drag my subItem(child) , my endDate changes and automatically all my parent needs to be refresh . I am using  project.load() to update my activities (refersh).But my gantt view is getting collapsed.
 
```
 
  
   this._gantt.project.load()
 
 

```
what could be the alternative to update tasks without collapsing (refresh) maintaining the expanded view of tree.
In Below attachment Before I drag activity ebd date was  11 Julu , Once I drag it to 13 July . My tree got collapsed

**Comment by ghulamghousdev** [comment]
Another request here: https://forum.bryntum.com/viewtopic.php?p=154655#p154655
