### ISSUE TITLE
eventNonWorkingTime feature not working with manuallyScheduled

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10014]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=30398&p=154304#p154304)

"Hi Bryntum team,
I've come accross a problem since I updated Scheduler Pro from version 5.6.2 to version 6.0.4 (the problem is also on 6.0.5 version).
I use the eventNonWorkingTimeFeature and all my events have the manuallyScheduled prop set to true (I use  dependencies and have to update manually the dependent events), but the eventNonWorkingTime is not displayed on the events. When I set manuallyScheduled to false it works well.
The 2 options used to be compatible on version 5.6.2.
I could reproduce the problem on your example : https://bryntum.com/products/schedulerpro/examples/event-non-working-time/
I just added

```
eventRecord.manuallyScheduled = true
```
at the beginning of the eventRenderer (line 59)."

**Comment by ghulamghousdev** [comment]
Another report here: https://forum.bryntum.com/viewtopic.php?p=154799#p154799

**Comment by chuckn0rris** [comment]
Invalid, it's docs problem, here is the ticket https://github.com/bryntum/support/issues/10041
