### ISSUE TITLE
Collision-Detection for menu items is not working correctly

### ISSUE THREAD

**Issue by MPulxeR** [bryntum/support#10048]
Hi bryntum team,
we currently facing issues with the menu component on some edge cases ...

Demo:
I've tried to recreate the issue here: https://codepen.io/Martin-Szigas/pen/wvbyzgR

Screenshot:
![image](https://github.com/user-attachments/assets/b34d70b1-24cb-4153-b063-8be24cf413aa)

Issue:
The collision detection for menu component is in some cases not working properly. It does not detect properly that the menu size collides with the visible area of the browser. Sometimes the menu flips below a button ... sometimes its above. However in some cases, menu does not flip and collides with the outside area and displays a scrollbar ... despite there is enough free space on the flip direction available.

Expected behaviour is that the popup checks if there is a collision to the visible space, and checks if there is enough space on the flip direction ...
![image](https://i0.wp.com/css-tricks.com/wp-content/uploads/2014/11/disqus-detection1.gif)

Hope you can check and fix the issue.

Best regards,
Martin

**Comment by ExtAnimal** [comment]
This issue in the Codepen is that the `<body>` element is not sized which it would be in all well developed apps.

If you are creating a web [b]site[/b] which is a flowing document, the body will only be the height of the content.

In a _Single Page Application_, the body does not scroll. Rather it is a full sized viewport in which the individual widgets are all laid out and sized by the application's CSS rules.

As a basis, Single Page Applications need the following:

```
html,
body {
    height: 100dvh;
    overflow: clip;
}
body {
    display: flex;
    margin: 0;
    align-items: stretch;
}
```

<img width="1875" alt="Screenshot 2024-09-23 at 08 35 02" src="https://github.com/user-attachments/assets/94ac196e-c60f-44a6-a7b9-bdbb1717238f">
