### ISSUE TITLE
`resourceRecord` is not defined in `dragmoveend` event of `dayResource` view

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10070]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=30264&start=10)

https://bryntum.com/products/calendar/examples/date-resource/

in console
```
calendar.on('dragmoveend', ({ resourceRecord }) => { console.log(resourceRecord); })
```
drag and drop event from one resource to another. See resourceRecord has not been passed into handler.

**Comment by matsbryntse** [comment]
Test pushed to `10070-dayresource` branch
