### ISSUE TITLE
DOCS: Remove strings as a supported type startDate/endDate setters of the model

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1007]
https://www.bryntum.com/forum/viewtopic.php?p=73733#p73733

According to the [docs](https://www.bryntum.com/docs/scheduler/#Scheduler/model/EventModel#field-startDate) both string and date object are supported. Change docs to mention strings are only accepted during data loading/parsing

**Comment by isglass** [comment]
Scheduler accepts a string, seems fine there

**Comment by isglass** [comment]
Also works in Gantt & Scheduler Pro, closing ticket as not reproducible. Perhaps fixed by other changes on master
