### ISSUE TITLE
Error in currency format

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10084]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=30449&p=154688#p154688)

Hi!

I tried to test the currency formating in the sample https://www.bryntum.com/products/grid/examples/export/. But when I fill the format in the "Score" field with the template "$0.00", is throwed the error: "Currency code is required with currency style."

The declaration I'm used was:

```
{ text : 'Score', field : 'score', flex : 1, type : 'number', format: {template: "$0.00"} },
```

Note:

When using this:

```
 format : { template: '$0.99', style: 'currency' } 
```

It works without errors but when removing the style from format, errors are back. The style should be extracted from the currency.

the below should work: `{ text : 'Score', field : 'score', flex : 1, type : 'number', format : '$0.99' },`

**Comment by henriquewerlang** [comment]
Any milestone for this request?

**Comment by henriquewerlang** [comment]
This issue can be realted to this one #10234?
