### ISSUE TITLE
beforeRequest and afterRequest events missing in Calendar 6.1.0 version

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#10089]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=30486&p=154737#p154737)

Dear Bryntum,

Today, we updated the Bryntum Calendar. Unfortunately, we noticed that OnBeforeRequest and OnAfterRequest have been removed from EventStore and ResourceStore. We tried to find their replacements, but unfortunately, we couldn't. This is significant issue for us, as OnBeforeRequest ensures that the Event data is correctly send to backend, while OnAfterRequest checks whether the User still has the right access to make modifications on the backend. 

```
onBeforeRequest(event: any) {
    if (!(event.action === 'create' || event.action === 'update')) {
        return;
    }
    if (!event.body) {
        return;
    }
    const data = event.body.data[0];
    const resource = resourceStore.getById(data.resourceId);
    const entityType = resource.getData('entityType');
    if (data.busId != null && entityType === 'BUS') {
        const bus = busStore.getById(data.busId);
        data.name = bus.getData('licenseplate');
        return;
    }
},

```

```
const onAfterRequest = (event: any) => {
	const response = event.response;
	const body = event.json;
	if (!response.ok && response.status === 401) {
	    signOut();
	    return;
	}
	calendar.current?.instance.refresh();
	if (!body || !body.success) {
	    console.log('onAfterRequest', body);
	    return;
	}
};

```

Please support us in understanding how to implement these two functions in version 6.1.0 of the Calendar.

I really appreciate your answer.

Best Regards,
Adri

**Comment by emadellaloggia** [comment]
maybe this will help
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive
