### ISSUE TITLE
Bug MSP Export: task calendars not exported correctly

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#10090]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30484&p=154733#p154733)

Hi,
We encountered an issue while testing the MSP export feature. Upon importing the .xml file into Microsoft Project, we noticed that task calendars are not being applied.

![TaskCalendarMissing.png](https://forum.bryntum.com/download/file.php?id=30863)
![TaskCalendarMissing2.png](https://forum.bryntum.com/download/file.php?id=30864)

As shown in the attached images, the project calendars appear to be imported correctly, but they are not assigned to the tasks.
After investigating, we found that adjusting the UIDs in the .xml file resolves the problem, so the bug may be related to how these are handled.

We're using v.6.0.6 and this can also be tested in your example: https://bryntum.com/products/gantt/examples/msprojectexport/

Thank you for looking into this, 
Luca.
![TaskCalendarMissing.png](https://forum.bryntum.com/download/file.php?id=30863)
![TaskCalendarMissing2.png](https://forum.bryntum.com/download/file.php?id=30864)

**Comment by 102898Is** [comment]
try this
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)
