### ISSUE TITLE
Events flickering when updating events that uses JSX in eventRenderer

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10091]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27868&p=154745#p154745)

"Hi, 

We are experiencing issues with updating events on the board in combination with JSX elements. This issue can also be reproduced with the current demos on the website.
https://bryntum.com/products/schedulerpro/examples-scheduler/frameworks/react-vite/renderer-context/dist/
https://bryntum.com/products/scheduler/examples/frameworks/react-vite/bigdataset/dist/

We process a large number of updates per minute and notice a constant flickering on the screen. 

As soon as we switch to plain HTML, this no longer occurs. The same applies to your demos.

We use schedulerpro 6.0.6 and schedulerpro-react 6.0.6."

https://github.com/user-attachments/assets/7c58c231-ceb7-4f37-8ac9-6f81dda869c9

**Comment by chuckn0rris** [comment]
User confirmed the issue is persists in 6.1.0

**Comment by ylinssen** [comment]
@isglass Is there a binary available for the fix?
Thanks in advance.

**Comment by chuckn0rris** [comment]
It will be available tomorrow in Nightly Builds here https://customerzone.bryntum.com/
