### ISSUE TITLE
Configuring features using features in the config does not work anymore

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10114]
Setting features config on frameworks in the following manner no longer works resulting in breaking the clients apps who are using this convention.

```
features: {
    taskEdit: false
}
```

Below works as expected:

```
taskEditFeature: false
```

**Comment by isglass** [comment]
This was never meant to work, we do not promote it in framework docs or demos. And we have warned about using it since 2021. Will close issue
