### ISSUE TITLE
Live Demo in Menu Docs opens the menu at incorrect position with `autoShow: true`

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10133]
Probably need to add owner or something like that so the menu always opens anchored to the targeted button.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=30566&p=155161#p155161)

Hi!

In the sample in the documentation link Core.widget.MenuItem if is removed the "AutoShow" property the menu became visible in the left coner of the screen.

The default value can be changed to false?
![Screenshot_10.png](https://forum.bryntum.com/download/file.php?id=30996)

**Comment by matsbryntse** [comment]
Bad docs example code
