### ISSUE TITLE
Add hierarchy lines to tree group

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10142]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30576&p=155208#p155208)

"Hi guys,
[...]

Also, I am interested in modifying the table to show "hierarchy lines" (again, please see image). Is this at all possible?
"
![hierarchy-lines.png](https://forum.bryntum.com/download/file.php?id=31012)

**Comment by isglass** [comment]
Duplicate of https://github.com/bryntum/support/issues/2041
