### ISSUE TITLE
Vue examples with multiple widgets don't size them correctly

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10156]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=30602&p=155376#p155376)

Hi there 

We have a lot of resources on the vertical direction, and we're experiencing an issue, where the timeline does not scroll vertically when the cursor is close to the top or bottom edge. The horizontal edges works.

The drag-n-drop example demonstrates the issue.

https://bryntum.com/products/schedulerpro/examples/frameworks/vue-3-vite/drag-unplanned-tasks/dist/

NOTE: The vertical scroll does not work correctly. To first look seems like an css issue.

https://github.com/user-attachments/assets/0879ebbb-e2a4-4598-a484-6089bed15598

**Comment by ghulamghousdev** [comment]
This issue is not only for this demo but for all the demos that uses grid and scheduler in the same layout in vue-3-vite

**Comment by ExtAnimal** [comment]
Bad app. Overnesting and lack of CSS layout.
