### ISSUE TITLE
Multi-Task Copy & Paste

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#10162]
When copying & pasting multiple tasks to a new Gantt instance (new project) the task links are lost.  Can the task relationships be retained, as they are when copying & pasting in the same Gantt

**Comment by JockeLindberg** [comment]
Related to/same as https://github.com/bryntum/support/issues/8185

**Comment by JockeLindberg** [comment]
Closing this as a duplicate. Please track https://github.com/bryntum/support/issues/8185 instead
