### ISSUE TITLE
Crash on creating an event in Gantt+SchedulerPro demo with filter applied in gantt

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10187]
Forum Post: https://forum.bryntum.com/viewtopic.php?p=155684#p155684

Add this config to features in gantt:

```
features : {
        filterBar: {
          compactMode: true,
        },
    },
```

1. And now filter the tasks column with anything, and try to drag and create an event in the schedulerPro for any resource. You will see the crash.,
2. Creating event with double does not show any event in timeaxis region

https://github.com/user-attachments/assets/d9198e0f-3d25-4fc1-8d9c-eaddd63c17fb

**Comment by kansimies** [comment]
Could this issue be prioritized since it is a show stopper for us?

**Comment by matsbryntse** [comment]
test pushed to `10187-crash`
