### ISSUE TITLE
Duplicate conflict resolution pop-up showing up in Gantt+SchedulerPro example

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10223]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30758&p=156130#p156130)

Hi there,
If you try to raise a conflict in this example https://bryntum.com/products/gantt/examples/gantt-schedulerpro/ (for example set must start on constraint on a successor and then try to expand its predecessor) the conflict resolution pop-up appears twice. It looks like it's triggered for both Gantt and Scheduler.
Can I somehow disable this duplication via the configs?

**Comment by arcady-zherdev** [comment]
There is a config for that:
```javascript
new Gantt({
    // disable default scheduling resolution popup
    displaySchedulingIssueResolutionPopup : false
});
```
