### ISSUE TITLE
`resourceRecord` is undefined in DayResource View

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10232]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30787&p=156269#p156269)

According to the documentation, beforeDragCreateEnd should deliver resourceRecord if in a resource-type mode.  

Steps to repro:
Go to this example https://bryntum.com/products/calendar/examples/date-resource-non-consecutive-dates/ and add this code:
```
    onBeforeDragCreateEnd(e){
        console.log(e)
    },
```
and then try to create a record by dragging. resourceRecord will be undefined.

![Bildschirmfoto 2024-10-21 um 02.35.50.png](https://forum.bryntum.com/download/file.php?id=31276)

**Comment by willydee** [comment]
Related to https://github.com/bryntum/support/issues/10070

`resourceRecord` and `eventRecord.resourceId` are still referencing the previously assigned resource, not the one assigned during the drag operation.

Problem should be resolved in https://github.com/bryntum/bryntum-suite/pull/10336
