### ISSUE TITLE
Should be possible to change forceFit dynamically

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1023]
https://www.bryntum.com/forum/viewtopic.php?p=73881#p73881

forceFit is a public config. Need to add a corresponding property to Scheduler. Basically TimeAxisViewModel has a internal setter already, so this code works:
```
scheduler.timeAxisViewModel.forceFit = true
scheduler.timeAxisViewModel.forceFit = false
```

**Comment by matsbryntse** [comment]
https://bryntum.com/products/scheduler/docs/api/Scheduler/view/TimelineBase#property-forceFit
