### ISSUE TITLE
Gantt cells don't mark dirty after cell editing

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10240]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30664&p=156326#p156326)

Case 1 (not reproducible):

1. disable `silenceInitialCommit`, 
2. load Gantt project. 
Result:  See `gantt.project.changes` has changes but tasks not marked as dirty in the grid.

This case is not reproducible given that the Gantt has `showDirty` set to `true`.

Case 2:

1. Gantt has `showDirty` set to `true` and `silenceInitialCommit` as `false`.
2. Cell edit a task start date.

Result : the task cell is not marked as dirty

**Comment by Howard-Certinia** [comment]
Hi again,

This appears to be a broader issue than just "silenceInitialCommit". See attached video where I'm using the advanced demo to show that the first cell edit doesn't result in the dirty flag on the cell.

https://github.com/user-attachments/assets/1ecbfbc9-f73b-4577-b596-d4f1a25d69df

This is a serious problem for us. Any idea when it will be fixed?

**Comment by Howard-Certinia** [comment]
Further to this, we have seen similar behavior when the range store is updated. The Gantt chart doesn't update with the changes immediately but will do after further interaction, like scrolling away and back. Is there a general redraw issue in Gantt at the moment?

**Comment by taauntik** [comment]
Workaround
```javascript
    listeners : {
        finishCellEdit : ({ grid: gantt }) => {
            gantt.refreshRows();
        }
    }
```

**Comment by Howard-Certinia** [comment]
Thanks @taauntik. Presumably this will only work for cell edit changes. It won't work for the other issue listed, like initial commit or range store changes.
