### ISSUE TITLE
Task Board maxAvatars not working

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10243]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30816&p=156407#p156407)

"Hi,

We recently upgraded Task Board from 5.6.4 to 5.6.13. Since upgrading, the resource avatars have been acting a little strange. When a maxAvatar limit is used, sometimes an avatar is missing or another is duplicated in the overflow tooltip.

While trying to pin down the problem, we tried to run the config we currently use in the online example:

https://bryntum.com/products/taskboard/examples/basic/

```
resourceAvatars: {
    maxAvatars: 4
}

```

This config no longer seems to work. The maxAvatars documentation now indicates the following:

```
footerItems : {
    resources : {
        type       : 'resourceAvatars',
        maxAvatars : 5
    }
}

```

But the maxAvatars still doesn't work. In addition, the avatars are now duplicated!"

Live demo - https://codepen.io/marciogurka/pen/YzmrZBR

Using the snippet provided in the documentation doesn't work as expected.

**Comment by ghulamghousdev** [comment]
This is not a bug. maxAvatars config in the responsive cards takes precedence. So is the case here. Need to set maxAvatars in responsive cards to null to make sure that maxAvatars item in footerItems works correctly. This behaviour is mentioned here. https://bryntum.com/products/taskboard/docs/api/TaskBoard/view/item/ResourceAvatarsItem#config-maxAvatars. So it should be:

```
    cardSizes   : [],
    footerItems : {
        resourceAvatars : {
            type       : 'resourceAvatars',
            maxAvatars : 2
        }
    },
```
