### ISSUE TITLE
Icon for selected options in combo is not ignored by screen readers

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10257]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=30833&p=156492#p156492)

When using a combo column with multiselect, a checkmark icon appears next to each selected option. 

This icon is not ignored by the screen reader, causing it to generate a strange character. Is there a way to modify this icon to add an aria-hidden attribute? 

Attached is an example image using VoiceOver.

Thanks in advace!
![Screenshot 2024-10-23 at 17.20.48.png](https://forum.bryntum.com/download/file.php?id=31327)
![Screenshot 2024-10-23 at 17.21.05.png](https://forum.bryntum.com/download/file.php?id=31326)

**Comment by ExtAnimal** [comment]
`List.js` needs:

<img width="1512" alt="Screenshot 2024-10-23 at 17 58 22" src="https://github.com/user-attachments/assets/f61bc2c5-8f27-494a-8bcb-9919e2a0e1db">

`ResourceCombo.js` needs:

<img width="1414" alt="Screenshot 2024-10-23 at 17 59 12" src="https://github.com/user-attachments/assets/cd999a9a-934e-4a39-b6c9-f914a6ad2813">

`ResourceFilter.ja` needs:

<img width="1333" alt="Screenshot 2024-10-23 at 17 59 49" src="https://github.com/user-attachments/assets/e37bfb30-52ee-44a7-9d3f-5bf24dc72690">


It appears that `role="presentation"` does not hide pseudo elements from the screen reader, so the `inert` hammer is needed to remove that from the accessibility tree.

**Comment by chuckn0rris** [comment]
It will be fixed in bounds of https://github.com/bryntum/support/issues/9998
I will close this ticket as dupe, please use the link above to track the status.
