### ISSUE TITLE
Not all resources are being shown in the resourceAvatars for a task

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10250]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30816&p=156446#p156446)

Go to example: https://bryntum.com/products/taskboard/examples/basic/ and see for the `renew passport task`, resource `Kate` is not being shown in the resources shown and the tooltip. Open the taskEdit for it and see the `Kate` is there.

https://github.com/user-attachments/assets/c62d0013-e035-4e51-98c2-0b55f0089c1c

**Comment by Howard-Certinia** [comment]
Hi @ghulamghousdev, this has been ready for review for over a month at this point. Any idea when it will be closed and available for us?

**Comment by ghulamghousdev** [comment]
@Howard-Certinia Apologies for the delay. There were some concerns from the fellow team members on the approach. I'll fix it and fingers crossed and I am hopeful that it will be part of the next release.
