### ISSUE TITLE
Task segments should inherit the custom fields from task record

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10252]
[Forum Post](https://forum.bryntum.com/viewtopic.php?p=156452#p156452)

Go to gantt basic example: https://bryntum.com/products/gantt/examples/basic/, update the code with the below, split a task and you can see the task segment does not inherit the custom fields.

```

class Ne extends TaskModel {
    static fields = [
        { name : 'note', persist : true }
    ];
}

new Gantt({
    appendTo          : 'container',
    dependencyIdField : 'sequenceNumber',
    rowHeight         : 45,
    tickSize          : 45,
    barMargin         : 8,
    project           : {
        taskModelClass     : Ne,
        autoSetConstraints : true, // automatically introduce `startnoearlier` constraint if tasks do not use constraints, dependencies, or manuallyScheduled
        autoLoad           : true,
        transport          : {
            load : {
                url : '../_datasets/launch-saas.json'
            }
        }
    },

    columns : [
        { type : 'name', width : 250 },
        {
            field : 'note'
        }
    ],

    // Custom task content, display task name on child tasks
    taskRenderer({ taskRecord }) {
        if (taskRecord.isLeaf && !taskRecord.isMilestone) {
            return StringHelper.encodeHtml(taskRecord.name);
        }
    }
});
```

https://github.com/user-attachments/assets/6b3ffbb6-3706-428c-89a6-8eed64d65614

**Comment by canonic-epicure** [comment]
As it was discussed, the expectation that custom fields of the event should be available on its individual segments is not correct. Copying this data would introduce consistency issues - one would need to keep the data on segments synchronized with data on event. Also, task and its segments are different things. Segment just indicates the time interval, during which task can make progress. Task itself may contain various meta data.

As it was suggested by Ghulam on forum, user should just use `segmentRecord.task.customField` notation to access that data.
