### ISSUE TITLE
[React] `flushSync` was called from inside a lifecycle method runtime error

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#10260]
Runtime error appears from react demo running with app dev server.
Related to some code added to React wrapper.
Reproduces at `npm run start`
And most likely related to double rendering there on start

![image](https://github.com/user-attachments/assets/3839647f-1b4a-4f92-9cb9-7c8b2ea58765)

It can be seen in this branch `8804-thin-trial`
To reproduce run from root
`grunt clean build-thin`
Then build Grid react `basic-thin` demo and run with `npm run start` and check console

**Comment by jsakalos** [comment]
Let's investigate this approach: https://julesblom.com/writing/usesyncexternalstore

**Comment by jsakalos** [comment]
@SergeyMaltsev What about this ticket? It's been fixed at the first run of the app/wrapper so I think we could close it.

**Comment by jsakalos** [comment]
Fixed in this PR: https://github.com/bryntum/bryntum-suite/pull/10303
