### ISSUE TITLE
Define the GridSelectionMode type

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10278]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=30919&p=157013#p157013)

"Hi!

It is possible to define the type GridSelectionMode in the TS with all fields defined in the documentation?[Grid.view.mixin.GridSelection#typedef-GridSelectionMode](https://www.bryntum.com/products/grid/docs/api/Grid/view/mixin/GridSelection#typedef-GridSelectionMode)"

Currently, we have in our types
```
type GridSelectionMode = any
```

**Comment by SergeyMaltsev** [comment]
Wring changes which were not required.
