### ISSUE TITLE
Behavior difference new Gantt(...) config vs gantt.project in browser console

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10277]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30918&p=157010#p157010)

"Hello.

Using this demo, I am experiencing a difference in behavior via setting in the code vs setting via the console: https://bryntum.com/products/gantt/examples/advanced/

Scenario 1: use browser console to set these two settings -

```
gantt.project.hoursPerDay = 8
gantt.project.calendar = 'business'

```

Result: desire behavior is achieved - startdate of 2024/10/29 with duration of 1 day has enddate of 2024/10/29.

Scenario 2: instead of using the browser console, configure the example's code to have config with:

```
const gantt = new Gantt({
  ...
  project: {
    ...
    hoursPerDay: 8,
    calendar: 'business',
    ...
  }
  ...
})

```

Result: desired behavior is NOT consistent/achieved - startdate of 2024/10/29 with duration of 1 day has enddate of 2024/10/30.

Why does using the gantt.project via web browser console behave differently than using the Gantt({ project }) config?
"

**Comment by arcady-zherdev** [comment]
The `hoursPerDay` field value is provided in the demo dataset file (located in `examples/_datasets/launch-saas-advanced.json`)
```js
{
  "success" : true,
  "project" : {
    "calendar"     : "general",
    "startDate"    : "2019-01-14",
    "hoursPerDay"  : 24,
    "daysPerWeek"  : 5,
    "daysPerMonth" : 20
  },
  "calendars" : {
...
```
The dataset is loaded after the project gets created so value provided to constructor gets overridden.

**Comment by tyler-dot-earth** [comment]
@arcady-zherdev Would you mind verifying that setting `project.hoursPerDay` in the dataset properly handles the case I've described above? I have been unable to achieve similar results to the Bryntum demo in my own project.

**In the demo**, setting `gantt.project.hoursPerDay = 8` in the browser console on the Bryntum demo i get the desired behavior:
- 1 day duration starts and end same day (eg jan 1) :heavy_check_mark: 
- 2 day duration start and end different days (eg jan 1 & 2). :heavy_check_mark: 

**In my own project** with `project: { hoursPerDay: 8 }` in my dataset, i do NOT get the desired result:
 - 1 day duration does have start & end the same day (eg jan 1), so :heavy_check_mark: this is desired
 - yet 2 day duration still ends up being the same day (because 2x8 < 24 assumedly), so :x: this is **NOT** desired

Subset of data from my app below, but let me know if i've excluded something important:
```json
{
    "success": true,
    "project": {
        "calendar": "general",
        "hoursPerDay": 8,
        "daysPerWeek": 7,
        "daysPerMonth": 30,
        "startDate": "2022-02-01"
    },
    "tasks": {
        "rows": [
            {
                "cls": "",
                "effort": 8,
                "calendar": null,
                "duration": 2,
                "inactive": null,
                "segments": null,
                "baselines": [],
                "direction": null,
                "effortUnit": "hour",
                "parentIndex": 0,
                "unscheduled": false,
                "durationUnit": "day",
                "effortDriven": false,
                "constraintDate": "2024-10-31T07:00:00.000Z",
                "constraintType": "startnoearlierthan",
                "schedulingMode": "Normal",
                "delayFromParent": null,
                "manuallyScheduled": false,
                "confirmationStatus": null,
                "ignoreResourceCalendar": null,
                "projectConstraintResolution": "honor",
                "id": "cm2yyzt4f000bamo5inmd2a5f",
                "name": "New Task",
                "parentId": null,
                "startDate": "2024-11-01T00:00:00.000Z",
                "endDate": "2024-11-01T00:00:00.000Z",
                "confirmationReason": null,
                "description": "",
                "percentDone": "0",
                "children": []
            }
        ]
    },
    "dependencies": {
        "rows": []
    },
    "resources": {
        "rows": [
            {
                // user data omitted
            },
        ]
    },
    "assignments": {
        "rows": []
    },
    "calendars": {
        "rows": [
            {
                "id": "general",
                "name": "General",
                "intervals": [
                    {
                        "recurrentStartDate": "on Sat at 0:00",
                        "recurrentEndDate": "on Mon at 0:00",
                        "isWorking": false
                    }
                ],
                "ignoreTimeZone": true
            }
        ]
    }
}
```

Note that I'm not setting `hoursPerDay` anywhere else, only here.

**Comment by tyler-dot-earth** [comment]
@marciogurka @arcady-zherdev Have you had a chance to verify this behavior based on the dataset i provided above? This is fairly irritating pain for our users that I would like to be able to resolve as quickly as i can. Thank you!

**Comment by arcady-zherdev** [comment]
Hello @tyler-dot-earth 
The dataset looks fine and behaves as expected after loading it in the advanced demo:
![image](https://github.com/user-attachments/assets/8f84545a-afdf-4688-82a5-e7d5432e3fc5)
As you can see the task starts `2024-10-31T07:00:00.000` according to its constraint and finishes `16 hours` (2 days) later `2024-10-31T23:00:00.000`.
Best regards,
Arcady
