### ISSUE TITLE
Resize proxy has wrong color

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1028]
Always green, should use events color

Not really a styling issue, needs solving in code
<img width="1022" alt="Screenshot 2020-06-25 at 10 11 45" src="https://user-images.githubusercontent.com/5415653/85682177-52629f00-b6cc-11ea-97a5-3217cf109fe8.png">

**Comment by dongryphon** [comment]
I believe this was fixed in 1.0.0 in fact
