### ISSUE TITLE
Progress line is not fully printed

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#10283]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30943&p=157130#p157130)

Hello,

We are experiencing an issue with the timeline on the gantt section, where the progress line does not extend fully and stops prematurely at the last tasks. We managed to reproduce the same issue using your example https://bryntum.com/products/gantt/examples/print/, to which we added the following code snippet:

```
features: {
    progressLine: true
```

Additionally, we are have some issues with the display of colors in the time ranges of the gantt section; they are not rendering correctly.

Could you provide guidance on how to resolve this issue?

Thank you in advance for your help!

Sincerely,
Oskari

**Comment by palto** [comment]
Is the progress line fix being worked on? It seems like when using the Print functionality the progress line only draws on lines that are visible in the browser and stops drawing it on rest of the rows.

![image](https://github.com/user-attachments/assets/d99fcc86-d656-42c0-98b4-36eeafc77ad5)

![image](https://github.com/user-attachments/assets/6ee9f840-c2d0-429d-9fb6-7b2ab5dc08b0)
