### ISSUE TITLE
EventBuffer feature throws with fillTicks: true

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#10286]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30930&p=157206#p157206)

Hi,

I'm implementing "travel time" via EventBuffer, but I'm running into an issue when fillTicks: true:

![Schermafbeelding 2024-10-30 143658.png](https://forum.bryntum.com/download/file.php?id=31542)

Also attached is code based on this demo:
https://bryntum.com/products/schedulerpro/examples/drag-unplanned-tasks/

I'm not sure if these features just can't work together or if it's a bug. I'll leave that up to you 
![Schermafbeelding 2024-10-30 143658.png](https://forum.bryntum.com/download/file.php?id=31542)

To reproduce use this app.js [app.zip](https://github.com/user-attachments/files/17598494/app.zip) and set preamble time on visible event

**Comment by matsbryntse** [comment]
Dupe #9380
