### ISSUE TITLE
After adding a predecessor, other child tasks are not being shown in the predecessor column

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10291]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30966&p=157278#p157278)

Just use the below data in the advanced example:

[launch-saas-advanced.json](https://github.com/user-attachments/files/17615782/launch-saas-advanced.json)

https://github.com/user-attachments/assets/2e273960-9452-4278-b031-67976b6f9ee2

**Comment by taauntik** [comment]
User requested to share patch, please do if applicable
