### ISSUE TITLE
Safari: Drag create selects text in YearView

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1029]
See week numbers
<img width="1022" alt="Screenshot 2020-06-25 at 10 13 34" src="https://user-images.githubusercontent.com/5415653/85682453-9c4b8500-b6cc-11ea-9d12-0a48e9c2ea48.png">

**Comment by jsakalos** [comment]
All views are affected. See this ticket https://github.com/bryntum/support/issues/1441

**Comment by matsbryntse** [comment]
Not reproducible
