### ISSUE TITLE
EventMenu doesn't work on Android touch device

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#10300]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30984&p=157361#p157361)

When the Basic demo of the Bryntum scheduler is opened on an Android tablet and a long press is performed to open the context menu, the menu opens and then immediately closes. 

https://github.com/user-attachments/assets/e56c9d8f-d4eb-4fdb-8863-35ffc0d7597d

Since this is a basic operation, customers are experiencing issues following the upgrade to the latest Bryntum version. Please let us know if there is any workaround available until this issue is resolved.

**Comment by AamukthaAukunooru** [comment]
Hello @taauntik , @isglass 
Thank you for responding quickly to this issue. Since context menus and scheduling menus are fundamental operations, this is a priority issue for us. Could you please provide the release date for version 6.1.3?

**Comment by taauntik** [comment]
@AamukthaAukunooru We're hoping to have 6.1.3 out next week.
