### ISSUE TITLE
Error in Combo grouping after updating to 6.1.0

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10309]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=31012&p=157479#p157479)

"
I managed to reproduce the issue by modifying a little bit your example for grouped list:
[Core.widget.Combo](https://bryntum.com/products/scheduler/docs/api/Core/widget/Combo)

As you see on the print screen grouping is no longer working:
<img width="1774" alt="Screenshot 2024-11-06 at 17 05 07" src="https://github.com/user-attachments/assets/77416f1d-14c5-468a-851c-4e36432af94e">

Error happens because field string: '[_tpg_dept_value@OData.Community.Display.V1.FormattedValue](mailto:_tpg_dept_value@OData.Community.Display.V1.FormattedValue)' contains '.' character. This was working in older versions and this bug is introduced in the version 6.1.0

It would be very important for us if you could fix this because we are using this as a part of ResourcePicker where we override Ajax store to fetch the date from dataverse. There is no option for me to rename fields that are returned from the dataverse in the query.
"

Demo with the issue: https://codepen.io/marciogurka/pen/oNKaLyY

**Comment by isglass** [comment]
Will be fixed by https://github.com/bryntum/support/issues/10168
