### ISSUE TITLE
GroupBar crash if columnReorder is disabled

### ISSUE THREAD

**Issue by isglass** [bryntum/support#10318]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=31044&p=157635#p157635)

Hi,

I want to use the groupbar, but the user should not be able to reorder columns.
If you configure columnReorder: false in the grouping demo an error is raised: Cannot create property 'usingGroupBarWidget' on boolean 'false'.

BR, Rico

**Comment by matsbryntse** [comment]
ColumnReorder feature is required, try setting:
```
 subGridConfigs : {
                locked : {
                    sealedColumns: true
                }
            },
```
