### ISSUE TITLE
Cannot sign in to Bryntum calendar

### ISSUE THREAD

**Issue by Aphilile** [bryntum/support#10315]
C:\Users\aphil>npm login --registry=https://npm.bryntum.com/
npm notice Log in on https://npm.bryntum.com/
Username: aphililegwadiso..gmail.com
Password:

npm error code E403
npm error 403 403 Forbidden - PUT https://npm.bryntum.com/-/user/org.couchdb.user:aphililegwadiso..gmail.com -
npm error 403
npm error 403 --------------------------------------------------------
npm error 403                   BRYNTUM NPM REGISTRY
npm error 403 --------------------------------------------------------
npm error 403 Cannot authorize "aphililegwadiso..gmail.com"
npm error 403 Bryntum Customer Zone aphililegwadiso@gmail.com account is not found
npm error 403 For trial access use "trial" as password
npm error 403 --------------------------------------------------------
npm error 403   Npm server login guide: https://npm.bryntum.com/help
npm error 403   Get support at: https://forum.bryntum.com/
npm error 403 --------------------------------------------------------
npm error 403
npm error 403 In most cases, you or one of your dependencies are requesting
npm error 403 a package version that is forbidden by your security policy, or
npm error 403 on a server you do not have access to.
npm error A complete log of this run can be found in: C:\Users\aphil\AppData\Local\npm-cache\_logs\2024-11-07T19_26_33_131Z-debug-0.log getting this when try to sign in

**Comment by SergeyMaltsev** [comment]
Hi!

Please use email/password linked to your Customer Zone account as described here 
https://bryntum.com/products/calendar/docs/guide/Calendar/npm-repository#login
