### ISSUE TITLE
Scheduler is blank when resourceStore loaded when custom groupSortFn used

### ISSUE THREAD

**Issue by egorkel-altexsoft** [bryntum/support#10325]
### Problem
When I add [_sorters_](https://bryntum.com/products/schedulerpro/docs/api/Scheduler/data/ResourceStore#config-sorters) to the _resourceStore_ and [_groupSortFn_](https://bryntum.com/products/schedulerpro/docs/api/Grid/feature/Group#config-groupSortFn) to the _group feature_, the initial calendar view is broken until I scroll down and up.

[bryntum-scroll+sorters-issue.webm](https://github.com/user-attachments/assets/d67dd886-88ed-479a-8d1e-7294d743e0b1)

It looks like rows are rendered before actual sorting because the row order is broken

![image](https://github.com/user-attachments/assets/28d38635-0843-4bf4-a33d-4066838e1cd4)

**Environment**: angular 18 + scheduler pro 6.1.1
**Test repo**: https://github.com/egorkel-altexsoft/angular-bryntum-merge-cells-issue

**Comment by ExtAnimal** [comment]
OK, I cloned that repo.

In simple steps, how do I make it run?

**Comment by egorkel-altexsoft** [comment]
Have you tried the steps described in the readme? You need to put bryntum packages to the corresponding folder, npm install, and npm start
