### ISSUE TITLE
DayView (incl WeekView) event drag converts recurring events into "allDay" events

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#1034]
dblclick to create a new 1 hour long event. Make it recurring Daily. Click Save.

Ongoing occurrences in the week are rendered fine.

Drag the first one downwards.

No proxy drag appears.

Upon mouseup, and confirming in the dialog, the event is transferred into the "all day" row.

![convertstoallday](https://user-images.githubusercontent.com/200516/85687523-da46aa00-b6c8-11ea-8652-75303b29e441.gif)

**Comment by ExtAnimal** [comment]
It doesn't do this any more. It performs the operation, but invisibly. There's no dragged element.

**Comment by matsbryntse** [comment]
not repro
