### ISSUE TITLE
npm login flow is buggy 

### ISSUE THREAD

**Issue by sixhobbits** [bryntum/support#10343]
When logging into NPM from a mac, a loading spinner is seen. It's not obvious that the user is required to enter the password (`trial`) and their email address. When entering the email address, each letter is deleted as it is typed which makes it challenging to enter the correct email address.

![screenshot 2024-11-14 at 13 14 49](https://github.com/user-attachments/assets/2378122b-ec63-4ad7-8641-28da7f8d2711)

We have seen this on mac and windows.

**Comment by SergeyMaltsev** [comment]
Please follow this guide
https://bryntum.com/products/grid/docs/guide/Grid/npm-repository

**Comment by SergeyMaltsev** [comment]
FYI: https://github.com/npm/cli/issues/7583
