### ISSUE TITLE
Very slow drag drop interaction with 50k tasks in the bigdataset demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#10346]
http://lh/bryntum-suite/gantt/examples/bigdataset/

load tasks, do drag drop

**Comment by ExtAnimal** [comment]
It's the Dependencies feature going crazy:

![Screenshot 2024-11-14 at 16 22 44](https://github.com/user-attachments/assets/63ada4e3-6fbe-4c99-ad09-fa98782f545f)

In the example, just do `gantt.features.dependencies.disabled = true` and try the drag again.

**Comment by isglass** [comment]
A change done when Gantt started rendering unscheduled tasks overruled the DependencyGridCache and instead always considered all dependencies for drawing. So in this scenario, it iterated 50000 deps instead of <20 on each frame
