### ISSUE TITLE
Recurring TimeRanges broken

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1035]
http://lh/bryntum-suite/Scheduler/examples/recurringtimeranges/

Does not render correctly, only single instances and on wrong days
<img width="554" alt="Screenshot 2020-06-25 at 11 03 25" src="https://user-images.githubusercontent.com/5415653/85690093-842b3400-b6d3-11ea-85be-03ef4c91355d.png">

**Comment by ExtAnimal** [comment]
The "Coffee" event which is supposed to be promoted to being recurring is a simple TimeSpan instance, not an instance of a full `EventModel`, so can not be promoted.

Here is where it is being constructed:

![Screenshot 2020-06-25 at 11 19 34](https://user-images.githubusercontent.com/200516/85692762-91ddbb00-b6cd-11ea-96db-7a5ff051ef8a.png)

**Comment by ExtAnimal** [comment]
Looks like it's being overwritten during configuration.

The incoming config object is the right store, but the calculated `fullConfig` overrides it with a generated simple `Store` instance.

![Screenshot 2020-06-25 at 11 40 46](https://user-images.githubusercontent.com/200516/85695915-5f818d00-b6d0-11ea-9bac-b5acca46fc95.png)

**Comment by chuckn0rris** [comment]
Not reproducible in `release`
<img width="1381" alt="Screenshot 2020-07-13 at 12 57 20" src="https://user-images.githubusercontent.com/7203098/87295258-c0a9bd00-c526-11ea-9c48-91f3fa6d00bc.png">
