### ISSUE TITLE
Not possible to configure Gantt to use duration without rounding 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10359]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=31134&p=158288#p158288)

[decimalPrecision](https://bryntum.com/products/gantt/docs/api/Core/widget/DurationField#config-decimalPrecision) and [durationDisplayPrecision](https://bryntum.com/products/gantt/docs/api/Scheduler/view/Scheduler#config-durationDisplayPrecision) ignores by Gantt and rounds values, not possible to specify as example 3.0001

Try here 

```


const gantt = new Gantt({
    appendTo : 'container',

    dependencyIdField : 'wbsCode',
    durationDisplayPrecision : 4,

```

Change duration for task to "3.0001". Check Tooltip, re-open editor. See it totally ignored,

**Comment by matsbryntse** [comment]
Test pushed to `10359-duration`

**Comment by chuckn0rris** [comment]
Another [request](https://forum.bryntum.com/viewtopic.php?f=44&t=31239&p=158914#p158914)
