### ISSUE TITLE
Issue with expandAll, collapseAll, and toggleCollapse in SchedulerPro when Tree and LockRows features are enabled

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#10371]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=31164&p=158428#p158428)

To reproduce:
1. Go to any schedulerPro example online
2. And replace the code with the file below
3. This also doesn't apply any filters on resourceStore\
For Example:
```javascript
schedulerPro.project.resourceStore.filter(record => record.events.length > 0);
```
[app.module.js.zip](https://github.com/user-attachments/files/17826434/app.module.js.zip)

https://github.com/user-attachments/assets/2468eebb-d64d-4ed3-8d55-d51621a30895

--------------------------------------------------------------------------------------------------------------
Dear Bryntum Support Team,

I have encountered an issue in SchedulerPro related to the use of expandAll, collapseAll, and toggleCollapse methods. When both the Tree and LockRows features are enabled, these methods stop functioning as expected.

Here is a brief description of the setup:

Product: SchedulerPro
Features used: Tree and LockRows
Issue: Programmatic calls to expandAll, collapseAll, or toggleCollapse have no effect when these features are both active.
Expected behavior:
The methods should properly expand or collapse the tree nodes regardless of whether the LockRows feature is enabled.

Steps to reproduce:

Enable Tree and LockRows features in the SchedulerPro configuration.
Attempt to programmatically invoke expandAll, collapseAll, or toggleCollapse.
Please let me know if you require additional details, such as a code snippet or environment configuration, to reproduce the issue.

Looking forward to your assistance.

Best regards,

**Comment by ghulamghousdev** [comment]
It turns out we do not support lock rows feature with Tree yet. So this issue is invalid as it was never intended to work.
