### ISSUE TITLE
Not possible to resize a task when pinSuccessor enabled and Cmd pressed

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10375]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=31175&p=158495#p158495)

Hi Team,

I am trying to pin the successors on task resize in the examples here-
https://bryntum.com/products/gantt/examples/pin-successors/
I cannot seem to resize the tasks when I hold down the 'Cmd' key
Could you please guide me on this

**Comment by matsbryntse** [comment]
Dupe #10374
