### ISSUE TITLE
Safari: Icons missing in pro-constraints demo

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1038]
Safari:
<img width="351" alt="Screenshot 2020-06-25 at 11 17 04" src="https://user-images.githubusercontent.com/5415653/85692172-78407180-b6d5-11ea-83b9-c356ff1696a6.png">

Chrome:
<img width="238" alt="Screenshot 2020-06-25 at 11 17 43" src="https://user-images.githubusercontent.com/5415653/85692224-842c3380-b6d5-11ea-84da-2c0b84e1f714.png">

**Comment by matsbryntse** [comment]
Not reproducible
