### ISSUE TITLE
Event creation dialog closes without clicking on save with autoCreate gesture "click"

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10399]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=31227&p=158829#p158829)

If you use autoCreate and set gesture to "click", it’s possible to create an event skipping the event creation dialog by spam clicking.

How to reproduce:
Add to https://bryntum.com/products/calendar/examples/basic/

```
autoCreate: {gesture: “click”}
```

Position your mouse at a point in the calendar where clicking pops a dialog for an event starting at 5:15am. Proceed to click rapidly a few times. You’ll see a new event actually get added to the calendar without having to interact with the event dialog. This does not occur with gesture "dblclick"

Expected behavior is that no event gets added to the calendar without also going through the event editor dialog. Why does this matter? We rely on the user filling out some mandatory fields in the event dialog and this triggers backend sync errors because they never get the chance to.

https://github.com/user-attachments/assets/3f467640-f5fa-4981-adf1-fdcaf5c8fd5d

**Comment by ExtAnimal** [comment]
`Scheduler/view/EventEditor.js` needs:

```
    close() {
        if (this.isCancelingEdit) {
            return super.close(...arguments);
        }
        this.eventEditFeature.onCancelClick();
    }
```
