### ISSUE TITLE
Block escape key from propagating in cell editor

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#10397]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=31221&p=158808#p158808)

If a grid or other component is placed into a dialog modal it is expected escape would close the dialog. However, when editing a cell in a Bryntum component and pressing escape we would only expect the cell editor to close and a second escape to then close the dialog. However currently propagation is only stopped for keyboard shortcuts and doesn't include escape by default.

Expected bheaviour: When editing in the popup, upon pressing Escape should only close the cellEdit and modal should still remain open. And when end user again presses the Escape it should close the modal.

**Comment by ExtAnimal** [comment]
The fix is in here : https://codepen.io/Animal-Nige/pen/bGXoyjB?editors=0010
