### ISSUE TITLE
`EventSegments` feature need to add few properties as public

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10400]
`isEventSegment` used in our demo but it's private
We have `eventSegmentModelClass`, but it's private. Need to have public way to change the class.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=31213&p=158791#p158791)

Hi,

I’m using the Gantt React wrapper (TS).
Some of the Gantt tasks are split into segments, while others are not. 
I’m using the taskRenderer method for custom rendering.

I’m encountering an issue with identifying the correct taskRecord when using taskRenderer.
I reviewed the split-tasks example and found the isEventSegment property. However, this property is available in the EventSegmentModel type but not in the TaskModel type, so I had to manually add it to my custom TaskModel class.

Is there a way to determine if the taskRender type is TaskModel or EventSegmentModel?

Additionally, I need to conditionally render an icon on the last segment item. I found the segmentIndex property, but it seems like the EventSegmentModel type does not include it. Is it possible to create a custom class for the EventSegmentModel?

![Screenshot 2024-11-25 at 9.50.22.png](https://forum.bryntum.com/download/file.php?id=32078)
![Screenshot 2024-11-25 at 10.37.09.png](https://forum.bryntum.com/download/file.php?id=32079)

Thanks,
Edi
![Screenshot 2024-11-25 at 9.50.22.png](https://forum.bryntum.com/download/file.php?id=32078)
![Screenshot 2024-11-25 at 10.37.09.png](https://forum.bryntum.com/download/file.php?id=32079)

**Comment by arcady-zherdev** [comment]
Hello,

Regarding type checking as a workaround you can do:
```js
if (record instanceof TaskModel) {...}
```

We have auto-generated `is{ClassName}` property for each class but it's not reflected in TypeScript interfaces yet. We'll fix it in this ticket.

 Best regards,
 Arcady
