### ISSUE TITLE
Make beforeSave event async

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#10412]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=56&t=31260&p=159047#p159047)

Make this async -> https://bryntum.com/products/taskboard/docs/api/TaskBoard/widget/TaskEditor#event-beforeSave

**Comment by ExtAnimal** [comment]
The event doesn't appear to do anything:

![Screenshot 2024-11-28 at 13 43 02](https://github.com/user-attachments/assets/e3ba3beb-8556-46fc-8b4b-f7b5d761bcda)
