### ISSUE TITLE
Resizing event using left edge does not respect calendar

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1044]
Should not be possible to end up like this

<img width="562" alt="Screenshot 2020-06-25 at 11 46 52" src="https://user-images.githubusercontent.com/5415653/85696924-a4f68800-b6d9-11ea-96e0-57ed7da57004.png">

**Comment by fabiojpoli** [comment]
I was unable to reproduce that (resize the task to left) and when I try this error shows up on console:

> Uncaught (in promise) TypeError: dependencies?.scheduleDraw is not a function
>     at EventResize.finalize (ResizeBase.js:486)

**Comment by matsbryntse** [comment]
Not reproducible
