### ISSUE TITLE
`gantt-taskboard` demo code is not available in online Code Editor

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#10488]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=31431&p=160044#p160044)

Dear,

https://bryntum.com/products/gantt/examples/gantt-taskboard/

I am currently trying to look into and try out the code on my end, but I am encountering an issue that appears on your demo page.
![taskboardcode.png](https://forum.bryntum.com/download/file.php?id=32467)

**Comment by SergeyMaltsev** [comment]
Not reproducible in `6.3.0`
https://bryntum.com/products/gantt-next/examples/gantt-taskboard/
