### ISSUE TITLE
Allow timerange header content to have one tick-width

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10506]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=31433&p=160070#p160070)

As the user described in the post, he wants to use the time range header mark as the screenshot.

![timerangeexample](https://github.com/user-attachments/assets/d1d28f39-00f3-4801-a238-fc0c6836ed59)

![timerangeexample2](https://github.com/user-attachments/assets/42a0fa9d-17bc-4aee-b4dc-74daa44da2d8)

**Comment by matsbryntse** [comment]
Easy to solve with a little custom CSS

**Comment by Miedziaq** [comment]
> Easy to solve with a little custom CSS

really? how?

This labels is dynamically calculated by bryntum on the background, every reload, every move outside the screen, every preset change.

Even using listeners to DOM and changing this dynamically at every "RERENDER of label" it works ugly and not always perfect.
