### ISSUE TITLE
`TimeField` select wrong value for hour when used 24h format

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10515]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=31407&p=160130#p160130)

https://github.com/user-attachments/assets/9c36ad87-257d-4904-9ff0-eb6248675057

**Comment by ExtAnimal** [comment]
This was fixed by https://github.com/bryntum/bryntum-suite/pull/10301

Try it locally.

**Comment by chuckn0rris** [comment]
Confirmed, fixed in latest release. I will close this.
