### ISSUE TITLE
Make `showCheckAll` compatible for `lockRows`

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#10523]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=160232#p160232)

Hello,
Is it possible to use LockRows with a selectionMode ? Like with this config:

```
selectionMode : {
  showCheckAll : true
}
```

On this example, when I add this config, there is an error in devtools when I try to resize one of the column:

```
scheduler.module.js?479434:322 Uncaught TypeError: Cannot read properties of null (reading 'shouldSync')
```
(On my local instance it's even weirder as a new checkbox column would be created on the fly, check the video - it also happens when the scheduler is resized)

Another concern of mine, I don't know which fieldName I should use to make the locking function. I tried "selected" but it didn't work.

Thanks,

**Comment by matsbryntse** [comment]
not reproducible
