### ISSUE TITLE
enableCellContextMenu: false doesn't disable context menu in Gantt

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1056]
Gantt's grid ignores `enableCellContextMenu: false` for columns

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14436&p=73830)

**Comment by isglass** [comment]
Context menus has changed a lot on master, but problem might still be there

**Comment by pmiklashevich** [comment]
Works in master, fixed in release
