### ISSUE TITLE
Scheduler Pro Tree Events Not Updating

### ISSUE THREAD

**Issue by naten3** [bryntum/support#1058]
I'm setting scheduler events on the scheduler via the `events` property as opposed to through a crud manager, and they don't seem to get rerendered when I expand/collapse a tree row. They do get updated if I again set the events on the scheduler

In this image events are expected on the two recently-expanded rows below the visible event
![image](https://user-images.githubusercontent.com/5622781/85739772-b3877400-b6c6-11ea-9ffe-587b0a8a1029.png)

They get rendered if we update the events list
![image](https://user-images.githubusercontent.com/5622781/85739848-c437ea00-b6c6-11ea-8ada-a3502d9e5561.png)

They persist on row collapse
![image](https://user-images.githubusercontent.com/5622781/85739938-d4e86000-b6c6-11ea-9c2c-141a3222c210.png)

**Comment by matsbryntse** [comment]
Can you please provide your code snippets showing how you do it?

**Comment by naten3** [comment]
`import { Component, OnInit, ElementRef } from '@angular/core';
import { Scheduler } from 'bryntum-schedulerpro';
import flatten from 'lodash/flatten';
import * as moment from 'moment';
@Component({
  selector: 'schedule-page',
  templateUrl: './schedule-page.container.html',
  styleUrls: ['./schedule-page.container.scss'],
})
export class SchedulePageContainerComponent implements OnInit {
  schedulerEngine: Scheduler;

  constructor(private elementRef: ElementRef) {}

  ngOnInit(): void {
    const config = {
      // Render scheduler to components element
      appendTo: this.elementRef.nativeElement,

      // Listeners, will relay events
      listeners: {
        thisObj: this,
      },

      features: {},
    };

    this.schedulerEngine = new Scheduler({
      ...config,
      startDate: new Date(),
      endDate: moment().add(20, 'd').toDate(),
      features: {
        tree: true,
      },
      columns: [
        {
          type: 'tree',
          text: 'Name',
          width: 220,
          field: 'name',
        },
        {
          type: 'aggregate',
          text: 'Capacity',
          width: 90,
          field: 'capacity',
        },
      ],
    });
    this.schedulerEngine.minHeight = 500;

    const resources = new Array(5).fill(0).map((i, index) => ({
      id: index.toString(),
      name: index.toString(),
      type: 'sdfs',
      expanded: true,
      children: new Array(5).fill(0).map((i, i2) => ({
        id: `${index}-${i2}`,
        name: `${index}-${i2}`,
        type: 'fasf',
      })),
    }));

    const events = flatten(
      new Array(5).fill(0).map((x, i) =>
        new Array(5).fill(0).map((y, j) => ({
          id: `${i}-${j}`,
          name: `${i}-${j}`,
          resourceId: `${i}-${j}`,
          startDate: moment().toDate(),
          endDate: moment().add(100, 'd').toDate(),
        }))
      )
    );

    this.schedulerEngine.resources = resources;
    this.schedulerEngine.events = events;
  }
}
`
This one updates only when I resize the window
![image](https://user-images.githubusercontent.com/5622781/86844641-f73a9000-c06d-11ea-9e46-93286c620eff.png)
![image](https://user-images.githubusercontent.com/5622781/86844671-00c3f800-c06e-11ea-8afb-80889ea11815.png)

Please help since our design relies heavily on trees and this is blocking us from upgrading.

**Comment by matsbryntse** [comment]
Seems to work fine for me on our latest code, please try our nightly build and let us know your findings. Sample used:
```

/* eslint-disable no-unused-vars */
import '../_shared/shared.js'; // not required, our example styling etc.
import Toast from '../../lib/Core/widget/Toast.js';
import '../../lib/Grid/column/ActionColumn.js';
import '../../lib/Grid/feature/Stripe.js';
import '../../lib/Grid/feature/Tree.js';
import '../../lib/SchedulerPro/widget/CalendarField.js';
import '../../lib/Scheduler/column/ResourceInfoColumn.js';
import '../../lib/Scheduler/feature/ResourceTimeRanges.js';
import '../../lib/SchedulerPro/feature/PercentBar.js';
import '../../lib/SchedulerPro/column/ResourceCalendarColumn.js';
import '../../lib/SchedulerPro/feature/ResourceNonWorkingTime.js';
import '../../lib/Scheduler/feature/TimeRanges.js';
import DateHelper from '../../lib/Core/helper/DateHelper.js';
import WidgetHelper from '../../lib/Core/helper/WidgetHelper.js';
import SchedulerPro from '../../lib/SchedulerPro/view/SchedulerPro.js';
import ProjectModel from '../../lib/SchedulerPro/model/ProjectModel.js';

const schedulerPro = new SchedulerPro({
    project : {
    },

    resourceImagePath : '../_shared/images/users/',
    adopt             : 'container',
    eventStyle        : 'rounded',
    startDate         : new Date(),
    // Custom view preset, with more compact display of hours
    viewPreset        : {
        base      : 'hourAndDay',
        tickWidth : 35,
        headers   : [
            {
                unit       : 'day',
                dateFormat : 'ddd DD/MM' //Mon 01/10
            },
            {
                unit       : 'hour',
                dateFormat : 'H'
            }
        ]
    },

    features : {
        tree       : true,
        timeRanges : {
            narrowThreshold : 10,
            enableResizing  : true
        },
        resourceNonWorkingTime : true,
        cellEdit               : true,
        filter                 : true,
        regionResize           : true,
        dependencies           : true,
        dependencyEdit         : true,
        percentBar             : true,
        group                  : 'type',
        sort                   : 'name',
        eventTooltip           : {
            header : {
                title      : 'Information',
                titleAlign : 'start'
            },
            tools : [
                {
                    cls     : 'b-fa b-fa-trash',
                    handler : function() {
                        this.eventRecord.remove();
                        this.hide();
                    }
                },
                {
                    cls     : 'b-fa b-fa-edit',
                    handler : function() {
                        schedulerPro.editEvent(this.eventRecord);
                    }
                }
            ]
        }
    },

    columns : [
        {
            type       : 'tree',
            text       : 'Name',
            field      : 'name',
            width      : 220,
            validNames : null
        },
        {
            type  : 'resourceCalendar',
            text  : 'Shift',
            width : 120
        },
        {
            type    : 'action',
            text    : 'Actions',
            width   : 80,
            align   : 'center',
            actions : [{
                cls     : 'b-fa b-fa-fw b-fa-plus',
                tooltip : 'Add task',
                onClick : async({ record }) => {
                    await schedulerPro.project.addEvent({
                        name         : 'New task',
                        startDate    : schedulerPro.startDate,
                        duration     : 4,
                        durationUnit : 'h',
                        resourceId   : record.id
                    });

                    schedulerPro.editEvent(schedulerPro.eventStore.last);
                }
            }, {
                cls     : 'b-fa b-fa-fw b-fa-cog',
                tooltip : 'Settings',
                onClick : ({ record }) => Toast.show('TODO: Show a cool settings dialog')
            }, {
                cls     : 'b-fa b-fa-fw b-fa-copy',
                tooltip : 'Duplicate resource',
                onClick : ({ record }) => {
                    schedulerPro.resourceStore.add(record.copy({
                        name : record.name + ' (copy)'
                    }));
                }
            }]
        }
    ]
});

schedulerPro.resources = new Array(5).fill(0).map((i, index) => ({
    id       : index.toString(),
    name     : index.toString(),
    type     : 'sdfs',
    expanded : true,
    children : new Array(5).fill(0).map((i, i2) => ({
        id   : `${index}-${i2}`,
        name : `${index}-${i2}`,
        type : 'fasf'
    }))
})).flat();

schedulerPro.events =
    new Array(5).fill(0).map((x, i) =>
        new Array(5).fill(0).map((y, j) => ({
            id         : `${i}-${j}`,
            name       : `${i}-${j}`,
            resourceId : `${i}-${j}`,
            startDate  : new Date(),
            duration   : 5
        }))
    ).flat();

```

**Comment by naten3** [comment]
Looks like it's fixed in the nightly build for me too. Thanks!

**Comment by naten3** [comment]
It seems to be resolved in the nightly build. Thanks!

**Comment by naten3** [comment]
When can we expect the fix to be officially released?

**Comment by matsbryntse** [comment]
Full 4.0 GA targeted in 4w
