### ISSUE TITLE
Rejecting a change on dependency store causes multiple issues

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1061]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14461&p=73945)

Drop this in to a demo

```
    project.on({
      load: () => {
        project.dependencyStore.on({
          beforeUpdate: data => {
            return false
          }
        });
       } 
      })

```

Draw a dependency.

See that the dependency was not created as expected but the tasks were rescheduled as if it was. crudStoreHasChanges() will report that there are changes, it looks like a broken change set was inserted which causes issues saving as well.

It would be expected that returning false from beforeUpdate would result in nothing at all happening after the user draws a link.

**Comment by matsbryntse** [comment]
To block adding a dependency, you should listen for beforeAdd:
```

project.on({
    load : () => {
        project.dependencyStore.on({
            beforeAdd : data => {
                return false;
            }
        });
    }
});
```
