### ISSUE TITLE
Scheduler header bug after scrollLeft

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1065]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?p=73936#p73936)

1. open https://www.bryntum.com/examples/scheduler/configuration/
2. execute: scheduler.setViewPreset('day')
3. execute: scheduler.setViewPreset('weekAndDayLetter')
4. scroll to the left using `scheduler.scrollLeft = 0` and notice the header is rendered incorrect.
<img width="333" alt="Screenshot 2020-06-26 at 14 42 58" src="https://user-images.githubusercontent.com/7203098/85838800-eb241800-b7bb-11ea-852c-5d3039f39d10.png">

**Comment by matsbryntse** [comment]
not reproducible
