### ISSUE TITLE
Support showing tooltips for resource time ranges

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1069]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=14475
[and here](https://www.bryntum.com/forum/viewtopic.php?f=52&t=18374&p=90842#p90842)

**Timeranges:**
Scheduler/examples/timeranges/app.js
```
import Tooltip from '../../lib/Core/widget/Tooltip.js';

new Tooltip({
    forSelector : '.b-sch-timerange',
    getHtml     : ({ tip, element, activeTarget, event }) => {
        const
            timeRangeId = activeTarget.dataset.id,
            timeRangeRecord = scheduler.features.timeRanges.store.getById(timeRangeId);

        return timeRangeRecord.name;
    }
});
```
Works for header only:
<img width="653" alt="Снимок экрана 2020-06-26 в 20 11 45" src="https://user-images.githubusercontent.com/57486733/85883226-4f110580-b7e9-11ea-9c81-49caf1c2a3a8.png">
As a workaround user can override this style:
```
	<style>
		.b-sch-timerange.b-sch-range {
			pointer-events: all;
		}
	</style>
```

**Resource timeranges:**
Scheduler/examples/resourcetimeranges/app.js
```
import Tooltip from '../../lib/Core/widget/Tooltip.js';

new Tooltip({
    forSelector : '.b-sch-resourcetimerange',
    getHtml     : ({ tip, element, activeTarget, event }) => {
        const
            // TODO: update the way we set id to the element
            timeRangeId = activeTarget.dataset.eventId.split('-')[1],
            timeRangeRecord = scheduler.features.resourceTimeRanges.store.getById(timeRangeId);

        return timeRangeRecord.name;
    }
});
```
As a workaround user can override this style:
```
	<style>
		.b-sch-resourcetimerange {
			pointer-events: all;
		}
	</style>
```

**Comment by TanayBhalani** [comment]
Hi i am using bryntum scheduler as angular wrapper, can you suggest me how can i implement it in that?

**Comment by pmiklashevich** [comment]
@TanayBhalani please use our forum for such questions: https://www.bryntum.com/forum/
Please check out the guide: https://www.bryntum.com/docs/scheduler/#guides/integration/angular.md

**Comment by TanayBhalani** [comment]
> @TanayBhalani please use our forum for such questions: https://www.bryntum.com/forum/
> Please check out the guide: https://www.bryntum.com/docs/scheduler/#guides/integration/angular.md

Hi i have replied and updated the same on forum

**Comment by matsbryntse** [comment]
TimeRanges already has
```

/**
             * Template used to generate the tooltip contents when hovering a time range header element.
             * ```
             * const scheduler = new Scheduler({
             *   features : {
             *     timeRanges : {
             *       tooltipTemplate({ timeRange }) {
             *         return `${timeRange.name}`
             *       }
             *     }
             *   }
             * });
             * ```
             * @config {Function} tooltipTemplate
             * @param {Object} data Tooltip data
             * @param {Scheduler.model.TimeSpan} data.timeRange
             */
            tooltipTemplate : null,
```
