### ISSUE TITLE
Event tooltip should not react to mouse overs if editor is visible

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1071]
+ event tooltip should hide if editor is shown after double click

<img width="616" alt="Screenshot 2020-06-28 at 21 30 06" src="https://user-images.githubusercontent.com/218570/85956537-a7313e80-b986-11ea-988b-0b7cbabcdc65.png">

Reproduced in live demo online: https://www.bryntum.com/products/calendar/

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/1587
