### ISSUE TITLE
task.copy() copies original successors and predecessors

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1075]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14474&p=73993)

Hi!

I just started working on duplicating a task tree including its dependencies and something is a bit confusing. I was about to duplicate the dependencies (predecessors and successors) of the original task before adding the duplicated task to the taskStore, and I stumbled on already existing dependencies in the duplicate. Let me illustrate:

Start with the Basic Demo
Put the gantt instance on window: window.gantt = new Gantt(...
Delete the root task
Now in the console, add a new root task:
```
var rootTask = gantt.taskStore.rootNode.appendChild({ name : 'New task' })
```
Right click that new task, and add a new subtask
Then right that task, and add a new one below
Edit the two subtasks and add some duration
Then drag a dependency from the end of the first subtask to the start of the second
Now in the console, copy the root task:
```
var duplicate = rootTask.copy({deep: true})
```
BUG: Then look at duplicate.children[0].successors. There's one, and its fromTask and toTask properties are pointing to the original tasks!

**Comment by Jerther** [comment]
I'm the forum post OP. Just wanted to let you know that it's still happening in 4.1.5

**Comment by matsbryntse** [comment]
@Jerther Can you still reproduce in latest?

**Comment by Jerther** [comment]
@matsbryntse I think the `deep` argument of `copy()` is broken. `rootTask.copy({deep: true})` does not copy children :(

**Comment by Jerther** [comment]
@matsbryntse I confirm the problem still occurs on 5.5.4
