### ISSUE TITLE
Simplify framework installations

### ISSUE THREAD

**Issue by isglass** [bryntum/support#108]
Consolidate to a single local npm package per framework:

`build/angular`
`build/react`
`build/vue`

Should contain everything that is needed to make our demos run:

* bundles
* css
* wrappers
* images
* etc

So normally a user would only have to do `npm install scheduler/build/react`.

Also investigate: Bundles, css & wrappers (the super important stuff) could be in subfolders, allowing advanced users to only include that? `build/angular/base` or something. To allow:

`npm install scheduler/build/react/base`

**Comment by SergeyMaltsev** [comment]
All development is moved to https://github.com/bryntum/bryntum-suite/issues/545
