### ISSUE TITLE
Dependencies not redrawn after shiftNext call

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1080]
https://www.bryntum.com/examples/scheduler-pro/pro-grouping/

<img width="1227" alt="Screenshot 2020-06-29 at 10 57 30" src="https://user-images.githubusercontent.com/218570/85993979-6b828d00-b9f7-11ea-82ee-da4474224ce4.png">

**Comment by chuckn0rris** [comment]
Looks like it fixed now.

This is how it works in published version:
![scheduler-shift-pub](https://user-images.githubusercontent.com/7203098/87002586-b52f5c80-c1db-11ea-87ce-336dde21d30b.gif)

This is how it works in current master:
![scheduler-shift](https://user-images.githubusercontent.com/7203098/87002627-caa48680-c1db-11ea-98eb-05b794fc877a.gif)
