### ISSUE TITLE
New engine scheduling mode issues

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1085]
New engine incorrectly calculates duration, end date and effort in some cases.
Setup:
1. 8 hours project calendar
2. hoursPerDay: 8 set on project
3. single reource with 4 hours calendar
3. 6 tasks (2 per mode) each assigned single resource. 40h effort - 40h effort is set *before* assigning resource. no effort - no effort *before* assigning resource.

This is how MSProject calculates them
![image](https://user-images.githubusercontent.com/45400762/85997594-5c5d0880-ba12-11ea-9ffc-1a6ba668b9d4.png)

This is how new engine calculates them
![image](https://user-images.githubusercontent.com/45400762/85997236-f1133680-ba11-11ea-8a8f-a75bbeed4c61.png)

What's wrong:
1. FE (40h effort) - correct
2. FD (40h effort) - duration is 10 days, MSProject shows 9.5 (because work on last day is 4 hours which is exactly half)
3. FU (40h effort) - duration is 10 days (should be 5), effort is 80 hours (should be 40)
4. FE (no effort) - duration is 10 days (should be 5), effort is 80 hours (should be 40)
5. FD (no effort) - duration is 10 days (should be 5), effort is 40 hours (should be 20)
6. FU (no effort) - duration is 10 days (should be 5), effort is 80 hours (should be 40)

Notes:
1. it appears that for Fixed Units/Work modes duration is `effort / project hours per day` and end date is calculated by resource calendar availability
2. Fixed Duration on the other hand is set according to the project calendar, end date is calculated according to it. And effort is only amount working hours of the resource calendar in the given interval

Gantt data:
[launch-saas.zip](https://github.com/bryntum/support/files/4845042/launch-saas.zip)

MS Project file:
[Project1.zip](https://github.com/bryntum/support/files/4845047/Project1.zip)

**Comment by bmblb** [comment]
related forum post: https://www.bryntum.com/forum/viewtopic.php?f=9&t=13208&p=74078#p74078

**Comment by canonic-epicure** [comment]
Not clear, the MSProject file contains duration = 5 days for almost every task, however the "launch_saas" dataset contains duration = 10 days. 

Anyhow, this ticket seems to be way too old, closing as unactionable.
