### ISSUE TITLE
Sort triggered after column resize

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#1086]
Whenever i change the width of the fields on the Gantt it triggers the sort of that column messing up my Task order.  It is very frustrating!

Can you fix asap?
🙏

**Comment by matsbryntse** [comment]
Please provide more information: 

1. which Gantt version
2. browser
3. Touch enabled?

**Comment by MRC38** [comment]
1. The Gantt version I am using is 2.1.3
2. Browser is Chrome
3. Yes it is touch enabled but i am not using that feature generally

**Comment by matsbryntse** [comment]
Try using latest version, can you still reproduce?

**Comment by bmblb** [comment]
@MRC38 could you please try version 2.1.5 online here? https://www.bryntum.com/examples/gantt/advanced/
I am trying it on touch laptop, can dragdrop and resize columns without triggering sorting, using touchpad.

**Comment by MRC38** [comment]
Hi

I am afraid i still get the same issue even after installing the latest version.  See Loom video below

https://www.loom.com/share/31ae565e27cf4f29aedaea957149361a

**Comment by bmblb** [comment]
Can you reproduce this issue on our online demo? Or on advanced demo in your local distribution?

If it works online we would need a runnable test case to investigate this issue. If that's not possible, I could recommend to start disabling features/custom code to narrow down the problem.

Are you using any framework (react/angular/vue) there? If so, do you use our wrapper or did you make a custom one?

**Comment by matsbryntse** [comment]
Reproduced, drag Surname column to make it smaller.

https://bryntum.com/examples/grid/columns/

**Comment by matsbryntse** [comment]
@MRC38 Please try again in the next nightly build.

**Comment by MRC38** [comment]
When will the next nightly build be?

**Comment by bmblb** [comment]
Nightly builds appear in customer zone every day. Usually when we recommend to try next nightly build, it means the next morning one will be available.
