### ISSUE TITLE
Milestone task label overlaps dependency arrow

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1090]
<img width="158" alt="Screenshot 2020-06-29 at 19 55 05" src="https://user-images.githubusercontent.com/218570/86039236-757dad80-ba42-11ea-9842-f7134987bc77.png">

3em looks better
```
.b-sch-event-wrap .b-sch-label-left, .b-gantt-task-wrap .b-sch-label-left {
    position: absolute;
    align-self: self-start;
    transform: translate3d(calc(-100% - 3em), 0, 0);
    margin: 0;
}
```

**Comment by pmiklashevich** [comment]
Will be closed automatically
