### ISSUE TITLE
Store add/insert methods are documented as private

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1109]
Rebuild release docs and see that methods are private:
http://lh/bryntum-suite/gantt/docs/#Core/data/Store#function-add

Possibly more methods are affected across classes.

**Comment by chuckn0rris** [comment]
Try to follow the link above with hidden private methods. It will open the page on `add()` method in CRUD section.
<img width="1381" alt="Screenshot 2020-07-07 at 12 30 21" src="https://user-images.githubusercontent.com/7203098/86776373-f871ba00-c079-11ea-981a-13873e43ddf9.png">

Change docs settings to show private methods and reload the page. It will open the page on `add()` method from StoreStm section which is private. Try to find CRUD section. There is no `add()` method showed, as well as `insert()` and others which has same names with private methods that was showed up.
<img width="1381" alt="Screenshot 2020-07-07 at 12 30 31" src="https://user-images.githubusercontent.com/7203098/86776407-00c9f500-c07a-11ea-93b8-2eb9708f6708.png">
