### ISSUE TITLE
eventRenderer not applied to allDay events

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1123]
`eventRenderer : () => 'foo',`

<img width="547" alt="Screenshot 2020-07-03 at 15 59 57" src="https://user-images.githubusercontent.com/218570/86476149-45862100-bd46-11ea-92ed-459c4d2e105c.png">

Also implement ability to set 'cls', 'iconCls' + 'style' properties in the method. See tests/view/Rendering.t.js for expectations

**Comment by ExtAnimal** [comment]
I think it's just `DayView` not passing in on to its owned `CalendarRow` in its `onPaint` method.

Something like this is needed:

```
            me.allDayEvents = new CalendarRow({
                eventRenderer : me.eventRenderer,
                ...
```
