### ISSUE TITLE
Picker with multiple items breaks to new line too soon

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#114]
Input is on the new line although it seems like on the right there is enough space to type
![image](https://user-images.githubusercontent.com/45400762/71175870-9b4b1e00-2279-11ea-91d3-ca07dd03fa71.png)
Screenshot from Gantt export example

As I understand there is a an input field with a fixed width, and when that doesn't fit into the remaining space in the line it goes to the new line. What is the expected behavior @matsbryntse ?
Any thoughts @ExtAnimal @isglass ?

**Comment by dongryphon** [comment]
To address this, the `input` element will need to have its width adjusted as you type. Pretty easy. I'll grab it since the milestone is 3.0.1

**Comment by dongryphon** [comment]
https://github.com/bryntum/bryntum-suite/pull/393

**Comment by dongryphon** [comment]
Fixed by https://github.com/bryntum/bryntum-suite/pull/393 which dynamically sizes the `<input>` element based on the text inside.
