### ISSUE TITLE
taskEdit feature ignores width defined in editorConfig

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1140]
`TaskEditor` uses `width` from localization property called `editorWidth`. It allows us to define different width for every language to be able to fit label texts: 
```
LocaleManager.extendLocale('En', {
    SchedulerTaskEditor : {
        editorWidth : '50em'
    }
});
```

But if a user defined `width` property using `editorConfig`, that width should be used instead of default language dependent one.
Now it's just ignored.

Note: 
`TaskEditorBase` class has this hook that is cause of such behaviour:
```
    updateLocalization() {
        this.width = this.L('L{editorWidth}');
        super.updateLocalization(...arguments);
    }
```

**Comment by isglass** [comment]
Think this is already fixed, by other changes
