### ISSUE TITLE
Slow performance when loading big data set 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1144]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=14539&p=74247)

Load attached data into pro grouping demo.

[BigdataSet (1).json.zip](https://github.com/bryntum/support/files/4887506/BigdataSet.1.json.zip)

**Comment by pmiklashevich** [comment]
I have no initial numbers, but I set 3 months timeline and log the load time. It takes 5-6 secs to load data. Scrolling in both directions smooth, editing works fast with no visual lags. Though first Cancel editing or first task Delete operation takes a bit longer than I would expect. For example first delete takes 1sec when all next operations take 100ms.
<img width="264" alt="Снимок экрана 2020-09-23 в 18 41 12" src="https://user-images.githubusercontent.com/57486733/94035968-75384880-fdcc-11ea-965a-a284a391db77.png">

SchedulerPro/examples/grouping/app.js

```
const schedulerPro = new SchedulerPro({
    project : {
        autoLoad  : true,
        transport : {
            load : {
                url : './data/data.json'
            }
        },
        eventStore : {
            listeners : {
                beforeRemove() {
                    console.time('Delete task');
                },
                remove() {
                    console.timeEnd('Delete task');
                }
            }
        },
        listeners : {
            beforeLoad() {
                console.time('Load time');
            },
            load() {
                console.timeEnd('Load time');
            }
        }
    },

    resourceImagePath : '../_shared/images/users/',
    adopt             : 'container',
    eventStyle        : 'rounded',
    // Show 3 months
    startDate         : '2020-04-13',
    endDate           : '2020-07-13',
```
