### ISSUE TITLE
Project Start field highlighted as invalid while page is loading

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#115]
Bug or correct behavior? 

https://bryntum.com/examples/gantt/advanced/

**Comment by isglass** [comment]
Probably flagged as required, but has no value until project is propagated. Perhaps easiest to not make it required and instead check on change. Or have some config that says `requiredLater` :)

**Comment by dongryphon** [comment]
https://github.com/bryntum/bryntum-suite/pull/372
