### ISSUE TITLE
Occurrence not promoted to exception / updated after drag 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1153]
http://lh/bryntum-new/calendar/examples/basic/

Create new task and drag it upwards.

![recurr](https://user-images.githubusercontent.com/218570/86932766-13a3fe80-c13a-11ea-90f1-dee498525c5e.gif)

**Comment by dongryphon** [comment]
This issue was caused by calling `eventRecord.setStartDate(date)` instead of something like this:
```
    eventRecord.set({
        startDate : date,
        endDate : DateHelper.add(date, eventRecord.duration, eventRecord.durationUnit)
    });
```
I don't understand the difference here, but I've changed the code to use `set()` instead of `setStartDate()`
