### ISSUE TITLE
MonthView to have an `autoRowHeight` config

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#1157]
Probably coupled with a `maxRowHeight` config to prevent cells getting out of hand.

To allow rows to grow to accommodate all the events in the most populous cell in the row.

**Comment by javascript-programming** [comment]
Feedback from client
- possibility to expand the row when clicking the + sign. 
- expand multiple rows for print

**Comment by ExtAnimal** [comment]
Related to https://github.com/bryntum/support/issues/1142
