### ISSUE TITLE
Weeknumbers should be more distinguishable from date numbers

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/support#1164]
In the monthview a weeknumber is shown next to a date number (when weekno option is on), this can be confusing. 

Weeknumbers or its column should be more distinguishable

See outlook. 
![Screenshot 2020-07-10 at 09 44 02](https://user-images.githubusercontent.com/25703411/87161084-4679fe00-c2c4-11ea-95c1-3ddff2355709.png)

**Comment by ExtAnimal** [comment]
We should implement a `weekRenderer` which will only be enabled if 'showWeekCell` is true.

`showWeekCell` will be a new config. There is currently `showWeekNumber` but it's been overloaded to show/hide the week *cell*.

When this is unwound, a `weekRenderer` can be implemented to produce content for the week cell.

It's up to user CSS to style that such as rotating the text direction.

**Comment by ExtAnimal** [comment]
This was already available, it's now in an example. Closing ticket
