### ISSUE TITLE
Expand row config option in monthview 

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/support#1165]
![Screenshot 2020-07-10 at 16 28 47](https://user-images.githubusercontent.com/25703411/87165461-7a582200-c2ca-11ea-876a-2ec1a4deb93f.png)

When clicking the plus sign there should be a config for expanding the row instead of showing the items in a popup. In case of printing the calendar those items should be optional be visible

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/2268
