### ISSUE TITLE
Resize cursor stuck after clicking event resize handle

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1175]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=14618)

Hi,
I think EventResize has an issue.

If you click (and hold) on the edge of an event and you drag it to change the time range it works. But if you just do left click with the mouse on the edge (right or left, and just a click instead of holding down) of the event, the mouse cursor remains "resize" mode and there's no way to turn it off, neither by clicking on another event nor by clicking any key on the keyboard.

By inspecting the css, there's the following class that isn't removed:

You can see this behaviour in your own demo. Scheduler.feature.EventResize

**Comment by bmblb** [comment]
Problem still exists in docs and online demos e.g. this one: https://www.bryntum.com/examples/scheduler/fillticks/
