### ISSUE TITLE
Setting `field:'duration'` on Gantt columns breaks the column editor

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1179]
This is a bug that has nothing to do with Angular. The Gantt DurationColumn internally binds to `field:'fullDuration'` and when the user overrides it with his own `field:'duration'` it breaks. The expected behavior should probably be to ignore the `field` config option (and remove it from the documentation) or to warn user that he must actually bind to composite of duration and unit.

The steps to reproduce are on this video:
![gantt-duration](https://user-images.githubusercontent.com/204844/87393598-b501d900-c5ae-11ea-9b15-5ed6c0045eb5.gif)

---
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=14631&p=74512)

Hi

We have observed the following behaviour with gantt v2.1.5:

To reproduce, navigate to the angular spa page containing the gantt code in the code harness (see below) that loads a stubbed gantt project response we have provided for you.  Then go into the duration cell for task 1 and update the value (eg from 3 days to 5 days), then press tab.  NOTE: this happens whether you enter just 5 or whether you type 5d.  The task bar extends well past the new duration, the end date is set to null.  Click on Add Task button on top left and you can see some logging messages in the devtools console that confirm the task duration field gets set to 5 daysday (yes the unit is duplicated) - see messages logged to devtools console confirming this.  

I have referenced a heavily distilled version of our Angular 9 codebase and a stubbed express.js API to illustrate this problem.  See ```
src/app/work-item/schedule/schedule/schedule.component.ts
``` for the pertinent bryntum gantt code.

To start the stubbed API: ```
cd bryntum-gantt-mock-api; npm install; node index.js
```
To start the Angular front end: ```
cd ../spa; rm -rf node_modules; npm install; ng serve
```
Navigate to http://localhost:4200/work-item/W-1/schedule

Access code here: https://www.dropbox.com/s/s0wjc8a6pd6s7pz/bryntum-gantt-duration-tab-issue.zip?dl=0

Please could you confirm if this is a bug?

Thanks

Ben

**Comment by matsbryntse** [comment]
Added docs to clarify
