### ISSUE TITLE
Localization and class name collisions

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1184]
h1. problem
In the combined gantt + scheduler modules bundle multiple name collisions occur which leads to:

*locales are not picked up by classes*

1. gantt and scheduler export classes with equal name e.g. EventEdit
2. when *gantt.module.js* bundle is assembled, those two get into source (Gantt/widget/EventEditor is imported directly in webpack.entry.js, Scheduler/view/EventEditor is imported indirectly, by EventEdit feature)  
3. name collision occurs, rollup renames gantt class to EventEditor$1
4. when EventEditor is instantiated, it looks for locale using name. Name is *EventEditor$1* and locale is bound to *EventEditor*
5. same doesn't occur in *umd* bundle, because imported classes are all wrapped into closures (that still leaves possible locale collision)

*classes are renamed in the bundles, but it is not always clear how*

1. Scheduler/feature/EventEdit is exported as EventEdit, Gantt/feature/EventEdit is exported as GanttEventEdit
2. but at the same time Scheduler/model/ResourceModel --> SchedulerResourceModel and Gantt/model/ResourceModel --> ResourceModel (mirrored naming convention)

Problem has two parts:
1. how to consistently export colliding classes from scheduler and gantt?
2. how to localize them?

h1. Possible solutions
*Exporting classes*
1. Export classes from bundles in namespaces, smth like <pre><code>export default { gantt : { Gantt, EventEditor, ...}, scheduler : { Scheduler, EventEditor, ...} }</code></pre>
2. Rename all (or just conflicting?) classes in Gantt package, like <pre><code>EventEditor -> GanttEventEdtior, ResourceModel -> GanttResourceModel, etc.</code></pre>
3. (Figure out more)

*Localizing classes*
After brief problem analysis it becomes clear, that class localization should be:
1. unique (to avoid accidental conflicts between gantt, scheduler, grid and common locales
2. unambiguous (locale should match specific class regargdless of import means: source, module or umd bundle)

Making them unambiguous is bit problematic, class exists in 3 contexts: source, module bundle, umd bundle.
When we assemble umd bundle we process source code to persist original class names in $name property. This technique could be improved to also include namespace. I assume same could be achieved for module bundle with rollup. When locale is picked in the runtime, $name would be referred and unique locale picked up. Unfortunately, I don't see how that could work in sources context - nothing is generated, only identifier we could possibly have is class name.
From the source context perspective, only identifier accessible is class name. This suggests class name should include namespace by default, either in class name, or in special property to keep class name simple. Given this is only valuable for localization, property sounds better than renaming classes.

From https://app.assembla.com/spaces/bryntum/tickets/8034-localization-and-class-name-collisions/details#

**Comment by isglass** [comment]
This is not an issue when using thin bundles / thin npm packages, or sources. Closing
