### ISSUE TITLE
Docs: wrong links to our demos

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1186]
https://www.bryntum.com/forum/viewtopic.php?p=74593#p74593

https://www.bryntum.com/docs/scheduler/#Grid/feature/Search
"Search example" link follows to Search demo in Scheduler that does not exist (404).

Search Gantt/lib for "examples/"

We use relative paths `<a href="../examples/search" target="_blank">Search example</a>.`
Need to process them correctly in docs builder

Also change `[TimeAxis](https://bryntum.com/examples/scheduler/timeaxis/)` to relative version.

Links to images used in docs have to be fixed too. Otherwise Scheduler class opened in Gantt demo shows Gantt's charts
<img width="1651" alt="Снимок экрана 2020-07-15 в 11 07 25" src="https://user-images.githubusercontent.com/57486733/87521333-e9e45d80-c68c-11ea-96a8-0d95652e492a.png">

**Comment by matsbryntse** [comment]
Fixed
