### ISSUE TITLE
Implement TaskTimeRanges feature

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1190]
Similar to ResourceTimeRanges to highlight a part of timeline for a specific task.
Requested here: https://www.bryntum.com/forum/viewtopic.php?p=74610#p74610

**Comment by arcady-zherdev** [comment]
In Ext Scheduler/Gantt we have a common base class `RowZones` IIRC ..we could have it in a similar way here.

**Comment by fabiojpoli** [comment]
Similar feature request: https://www.bryntum.com/forum/viewtopic.php?f=52&t=14829

**Comment by matsbryntse** [comment]
https://bryntum.com/products/gantt/examples/calendars/
