### ISSUE TITLE
EventEditor should not show delete button in readOnlyMode

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/support#1193]
```
  eventEdit : {
            readOnly: true,
            items : {
                roomSelector : {
                    name  : 'room',
                    type  : 'roomSelector',
                    label : 'Room',
```

![Screenshot 2020-07-15 at 17 30 10](https://user-images.githubusercontent.com/25703411/87564777-16b26800-c6c1-11ea-9fd2-55409c985a39.png)

and in case it is readOnly, it should not be clickable

Then second issue on showDeleteButton: false should not throw an error. 
```
 eventEdit : {
            showDeleteButton: false,
            items : {
```

![Screenshot 2020-07-15 at 17 33 27](https://user-images.githubusercontent.com/25703411/87565053-6db83d00-c6c1-11ea-9afb-47ee6b91dd57.png)

All reproducible on http://lh/bryntum-suite/Calendar/examples/eventedit/

**Comment by ExtAnimal** [comment]
Fixed
