### ISSUE TITLE
When Event Store is chained dragging events duplicate elements on the screen

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1194]
https://www.bryntum.com/forum/viewtopic.php?p=74636#p74636

http://lh/bryntum-suite/scheduler/examples/basic/
`store = scheduler.eventStore.makeChained()`
Drag an event
<img width="2048" alt="Снимок экрана 2020-07-15 в 18 45 31" src="https://user-images.githubusercontent.com/57486733/87566802-2be0c400-c6cc-11ea-90e0-5a4ac5e39b27.png">

**Comment by matsbryntse** [comment]
Not reproducible
