### ISSUE TITLE
Vertical bold tick line is missing when show only working time and Sunday is filtered out

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1199]
https://www.bryntum.com/forum/viewtopic.php?p=74626#p74626

http://lh/bryntum-suite/scheduler/examples/basic/
```
let scheduler = new Scheduler({
    workingTime : {
        fromDay : 1,
        toDay   : 6
    },
    startDate        : new Date(2017, 0, 1),
    endDate          : new Date(2017, 0, 20),
    viewPreset       : 'weekAndDay',
```
Bold line between weeks is missing:
<img width="1197" alt="Снимок экрана 2020-07-16 в 20 44 13" src="https://user-images.githubusercontent.com/57486733/87704821-9dd90c00-c7a5-11ea-9114-363d34cf6383.png">

And with workingTime commented out the line is present:
<img width="1196" alt="Снимок экрана 2020-07-16 в 20 44 02" src="https://user-images.githubusercontent.com/57486733/87704761-8a2da580-c7a5-11ea-8856-938e557c6ae5.png">

**Comment by isglass** [comment]
By default, no minor line is added when there is a major, based on the dates. In filtered scenarios the end date for the major will no longer match that of the minor, even though they have the same coord. So they overlap. No point in fixing that in code, will just get complicated.

`z-index : 1` on the major lines will fix it.
