### ISSUE TITLE
Vertical mode misses 'renderTimeSpan' method 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#120]
Vertical mode misses 'renderTimeSpan' method so below code in EventDrag will crash if multi dragging and one event ends up outside rendered viewport:

```
// It's selected but unrendered. This happens when multi-selected events are dragged such
            // that on drop, they are outside of the timeline or the rendered block, and become unrendered.
            // Users will expect the event to be "there" so we have to bring it into existence
            // just for the drag.
            if (!eventBarEl) {
                const rd = scheduler.generateTplData(r, r.resource, { timeAxis : true, viewport : true });

                rd.top = rd.row ? (rd.top + rd.row.top) : scheduler.getResourceEventBox(r, r.resource, true).top;
                eventBarEl = scheduler.currentOrientation.renderTimeSpan(rd, {}, null, true);

                // Make it be reused after drag
                scheduler.currentOrientation.availableDivs.add(eventBarEl);
                eventBarEl = eventBarEl.innerElement;
            }
```
```

EventDrag.js:686 Uncaught TypeError: scheduler.currentOrientation.renderTimeSpan is not a function
    at EventDrag.js:686
    at Array.forEach (<anonymous>)
    at EventDrag.setupProductDragData (EventDrag.js:668)
    at EventDrag.getDragData (DragBase.js:635)
    at EventDrag.getDragData (EventDrag.js:710)
    at EventDrag.onDragStart (DragBase.js:189)
    at EventDrag.onDragStart (EventDrag.js:263)
    at DragHelper.trigger (Events.js:828)
    at DragHelper.callPreventable (Events.js:670)
    at DragHelper.internalMove (DragHelper.js:515)
```

**Comment by pmiklashevich** [comment]
Please add steps to reproduce the failure

**Comment by matsbryntse** [comment]
Read the sources to see the exact conditions when this method is called

**Comment by abhisrinu** [comment]
Why is this removed a high-priority?
What is the plan on this? We are not able to use the scheduler in the vertical mode because of this.

Abhi

**Comment by matsbryntse** [comment]
We're lacking a test case and a way to reproduce it, as well as noone else has reported it. Are you able to provide us a simple test case?

**Comment by nagasain** [comment]
In one of the demos, [https://www.bryntum.com/examples/scheduler/resourcetimeranges/](timeranges) modify the code, change the below properties of scheduler
`mode:'vertical',
startDate      : new Date(2019, 0, 1, 6),
endDate        : new Date(2019, 0, 7, 20),`
Now, drag any event to other dates, works for once, from next drag you can see the error in the console, and event drag doesn't work, it freezes.

**Comment by matsbryntse** [comment]
Still cannot reproduce it, please do it again online with this URL:  https://www.bryntum.com/examples/scheduler/resourcetimeranges/?video=1

**Comment by nagasain** [comment]
[VerticalModeError.zip](https://github.com/bryntum/support/files/4368805/VerticalModeError.zip)
Please look at the screen recording of the demo with replication.

**Comment by matsbryntse** [comment]
We've now reproduced it, thanks

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/918
