### ISSUE TITLE
Event is gone if reassign it to another resource in multiassign demo

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1200]
https://www.bryntum.com/forum/viewtopic.php?p=74670#p74670
http://lh/bryntum-suite/scheduler/examples/multiassign/

Edit a task
Open resources picker
Uncheck current, check another
Save
See event is gone
**Bug happens in release. Works in Master!**

https://www.bryntum.com/forum/download/file.php?id=10810

**Comment by matsbryntse** [comment]
Fixed in master already
