### ISSUE TITLE
Dropdown autocomplete in Gantt TaskEditor

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1217]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14694&p=74733)

Hello,

is there a way to filter items by autocomplete in the main dropdowns of the Gantt?
I mean autocomplete for: Successors, Predecessors and Resources combos in the Task editor.

Or, is there a sample code to implement it?

If not, please, consider it as a feature request.

Thank you a lot.

**Comment by matsbryntse** [comment]
Implemented
