### ISSUE TITLE
ComboBox list should be anchored to top/bottom sides only

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1218]
Go to https://bryntum.com/examples/gantt/advanced/
make screen smallish
Type 'eff' into add new column header:

<img width="382" alt="Screenshot 2020-07-21 at 09 37 59" src="https://user-images.githubusercontent.com/218570/88026270-e8f07780-cb35-11ea-9459-f80c2d713859.png">

**Comment by bmblb** [comment]
From one point it looks perfectly in touch with popup logic: if there's no space below - try to appear somewhere else. Do you mean combo list should always be to the bottom?
![image](https://user-images.githubusercontent.com/45400762/91193863-49a83c80-e700-11ea-8db3-fc38eb48f335.png)

**Comment by matsbryntse** [comment]
There's plenty of space below. A combo box should dock its list top or bottom.
