### ISSUE TITLE
Showing async tooltips is broken

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#122]
Forum: https://www.bryntum.com/forum/viewtopic.php?f=51&t=12955
(https://www.bryntum.com/forum/viewtopic.php?f=44&t=12373#p65238 ex. https://app.assembla.com/spaces/bryntum/tickets/9355)

Grid/examples/tooltip/app.js
```
const tooltip = new Tooltip({
    listeners : {
        beforeShow : ({ source : tip }) => {
            tip.html = false;
        }
    },
```
fails with an exception:
```
Uncaught (in promise) TypeError: Cannot read property 'targetHidden' of undefined
    at Tooltip.realign (Tooltip.js:642)
    at Tooltip.set html (Widget.js:1346)
    at Tooltip.set html [as html] (Tooltip.js:730)
    at Tooltip.beforeShow (app.js:28)
    at Tooltip.trigger (Events.js:828)
    at Widget.js:2100
    at new Promise (<anonymous>)
    at Tooltip.show (Widget.js:2084)
    at Tooltip.show (Tooltip.js:578)
    at Tooltip.showBy (Widget.js:2191)
```

Our API is broken: https://www.bryntum.com/docs/scheduler/#Core/widget/Tooltip

> Showing async content
> To create async tooltip and show loadingMsg, set html to false
> 
> Ensure that the activeTarget is the same when the data arrives.
> 

```
new Tooltip({
    listeners : {
        beforeShow : ({ source : tip }) => {
            const showingFor = tip.activeTarget;

            tip.html = false;
            AjaxHelper.get('someurl').then(response => {
                // Still visible for the same triggering element by the time the data arrives...
                if (tip.isVisible && tip.activeTarget === showingFor) {
                    tip.html = 'Done!';
                }
            });
        }
    }
});
```

**Comment by pmiklashevich** [comment]
Commented by @isglass 
Crash easily fix by checking for existence of `spec` in Tooltip.realign().
But that does still not make the tooltip work with async content. Problem with that is that TooltipBase uses getHtml. It should probably be changed to use `beforeShow` listener also, or rewritten a bit to respect the existence of a beforeShow listener

**Comment by ExtAnimal** [comment]
There never was any async ability. We need a proper async API.

```
const result = me.getHTML({...});

if (result instanceof Promise) {
    result.then(content => {
        me.html = content;
        // postprocessing
    });
    return; //Postprocesing has to wait until content arrives from the Promise
}
else {
    me.html = result;
}
```

And that should not be in `align`. It should kick off on activate, when the show countdown is started to make it a little more likely that it will be able to show content on time.

**Comment by pmiklashevich** [comment]
> There never was any async ability. We need a proper async API.
> 
> ```
> const result = me.getHTML({...});
> 
> if (result instanceof Promise) {
>     result.then(content => {
>         me.html = content;
>         // postprocessing
>     });
>     return; //Postprocesing has to wait until content arrives from the Promise
> }
> else {
>     me.html = result;
> }
> ```
> 
> And that should not be in `align`. It should kick off on activate, when the show countdown is started to make it a little more likely that it will be able to show content on time.

It sounds like a feature request. I fixed the regression https://github.com/bryntum/bryntum-suite/pull/329 and created a separate ticket to provide async capability: https://github.com/bryntum/bryntum-suite/issues/330
