### ISSUE TITLE
Scheduler time axis is empty after switching between schedulers

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1220]
Scheduler/examples/angular/advanced demo
Open http://localhost:4200/#/scheduler1
Zoom in first scheduler
Open second scheduler
Go back to the first one
See no content in normal grid

<img width="1265" alt="Screenshot 2020-07-21 at 19 20 25" src="https://user-images.githubusercontent.com/218570/88086194-3e08a980-cb87-11ea-944d-89b88dc627fc.png">

This is a demo issue related to the https://angular.io/api/router/RouteReuseStrategy implementation. See Scheduler/examples/angular/advanced/src/app/router/my-reuse-strategy.ts.
If you open Scheduler/examples/angular/advanced/src/app/app.module.ts and comment out
`{ provide: RouteReuseStrategy, useClass:MyReuseStrategy },`
It will work. Though everything will be reset to the initial value.
In Angular when you leave a route, the component represented by the route is destroyed. And when you come to the route the component is created from scratch. To do not loose the state, RouteReuseStrategy is used. It's needed to do not destroy the component. Instead Angular removes it from DOM and keeps somewhere in memory. When we navigate back to the component it restores the component from the memory and inserts it to the DOM. But the scroll position is reset and the content of the normal grid is not visible. Interesting thing is that you search for let's say 'b-sch-event' in the dev console, it finds all elements. And when you click enter and reach to the elements, all missing DOM is appeared on the screen. The same happens if you just start scrolling.

**Comment by isglass** [comment]
If there are hooks for when it stores/restores I guess we could store scroll position and restore it + refresh later. 
Or try an mimick this outside of Angular and come up with some way of detecting being ripped out of DOM and added back...

**Comment by bmblb** [comment]
Scheduler *has to* save and restore state when going through the router, because DOM element cannot store own left scroll. So every change related to scroll (which zoom is) would be lost on navigation.
