### ISSUE TITLE
Week numbers are off by 1 for 2020

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1225]
The week numbers are off - w1 should start on Dec 30 2019 but it starts on Jan 5 2020 in our demo and w53 starts on Jan 3 2021.

<img width="1576" alt="Screen Shot 2020-07-22 at 10 36 28" src="https://user-images.githubusercontent.com/204844/88155216-173e8780-cc08-11ea-8ef5-e54d5b7b4f08.png">

[Forum post](https://bryntum.com/forum/viewtopic.php?f=51&t=14738&p=74884#p74884)

Example:

https://www.bryntum.com/examples/scheduler/workingtime/

Issue:
When viewing the end of this year (2020) in week view, for some reason - the week numbers are either off, or some calculation is happening incorrectly - as the end of December showing Week 52 (as it should), but then the first week of Jan 2021 is showing as week 53 of the previous year (when Week 52 actually should go into Jan, but only for two days) Week 1 of 2021 should start on Jan 03, but in the Scheduler, Week 1 doesn't seem to start until Jan 10, which is not accurate as far as the calendar is concerned.

Steps to repeat:

Load the example above
Open the code panel and change the week dates to something reasonable for 2020 / 2021 ```
...
                    {
                        value      : 'week',
                        text       : 'Week',
                        startDate  : new Date(2020, 1, 1),
                        endDate    : new Date(2021, 1, 16),

```
Scroll right to see that 03 Jan is listed as W53 of 2020 (which shouldn't exist)

**Comment by ExtAnimal** [comment]
I think the customer is incorrect. 2020 has a week 53.
