### ISSUE TITLE
Export to MSP

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1250]
Ping @arcady-zherdev for instructions

https://products.aspose.com/tasks/java
http://www.mpxj.org/

**Comment by arcady-zherdev** [comment]
`<Task>` node sub-tags mappings:

- "Manual" - `manuallyScheduled` field value
- "Work" - `effort` & `effortUnit` fields combined value
- "Type" - is calculated based on `schedulingMode` field and equals to:
0 if schedulingMode == `FixedUnits`
1 if schedulingMode == `FixedDuration`
2 if schedulingMode == `FixedWork`
we have one more schedulingMode == `Normal` which doesn't exist in MSP ..let's use 1 for it so far
- "Summary" - "1" for parent tasks (tasks having `isLeaf` === false) and zero for other tasks,
- "Milestone" - can be mapped to task `milestone` (which is private for some reason but I guess it's ok to use it)
- "Rollup" - `rollup` field
- "CalendarUID" this one should be mapped to the task `calendarId`

these 3 should be probably mapped to `startDate`, `endDate` and `duration` for `manuallyScheduled` tasks (but need to check that in MS Project):
```
// "ManualStart": "2020-08-10T08:00:00",
// "ManualFinish": "2020-08-10T17:00:00",
// "ManualDuration": "PT8H0M0S",
```

**Comment by arcady-zherdev** [comment]
a task dependencies should be represented this way as far as I see:
```xml
			<PredecessorLink>
				<PredecessorUID>1</PredecessorUID>
				<Type>1</Type>
				<CrossProject>0</CrossProject>
				<LinkLag>0</LinkLag>
				<LagFormat>7</LagFormat>
			</PredecessorLink>
```

**Comment by arcady-zherdev** [comment]
`LinkLag` above is seems calculated as `dependency.lag`
```js
project.convertDuration(dependency.lag, dependency.lagUnit, 'minute') * 10
```

**Comment by arcady-zherdev** [comment]
`Task` `DurationFormat` should be mapped to `task.durationUnit` 
```
3 | m (minutes)
4 | em (elapsed minutes)
5 | h (hours)
6 | eh (elapsed hours)
7 | d (days)
8 | ed (elapsed days)
9 | w (weeks)
10 | ew (elapsed weeks)
11 | mo (months)
12 | emo (elapsed months)
19 | % (percent)
20 | e% (elapsed percent)
21 | Null
35 | m? (estimated minutes)
36 | em? (estimated elapsed minutes)
37 | h? (estimated hours)
38 | eh? (estimated elapsed hours)
39 | d? (estimated days)
40 | ed? (estimated elapsed days)
41 | w? (estimated weeks)
42 | ew? (estimated elapsed weeks)
43 | mo? (estimated months)
44 | emo? (estimated elapsed months)
51 | %? (estimated percent)
52 | e%? (estimated elapsed percent)
53 | Null
```
)elapsed units are not supported yet so should map to corresponding not elapsed unit

**Comment by arcady-zherdev** [comment]
`Task` `WorkFormat` should be mapped to `task.effortUnit`

**Comment by arcady-zherdev** [comment]
Let's use more complex logic for `Type`:
```js
if (task.isleaf) {
    switch (task.schedulingMode) {
        // let's map "Normal" to "Fixed Units" (which is default type in MS Project)
        case 'Normal':
        case 'FixedUnits':
            return 0;
        case 'FixedDuration':
            return 1;
        case 'FixedWork':
            return 2;
    }
}
// in MS Project all summary tasks have "Fixed Duration" type
else {
    return 1;
}
```

**Comment by arcady-zherdev** [comment]
Another mapping for `Task` - `EffortDriven` (1/0) to `task.effortDriven` boolean
