### ISSUE TITLE
No message when Indent/Outdent not working

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1251]
http://lh/bryntum-new/gantt/examples/gantt-schedulerpro/
Try indenting "Run tests" task
Nothing happens

**Comment by pmiklashevich** [comment]
Reproduced in Advanced demo in master.
In release it shows
<img width="1138" alt="Снимок экрана 2020-07-28 в 15 11 50" src="https://user-images.githubusercontent.com/57486733/88663853-e0271500-d0e4-11ea-93d5-2150e084f800.png">
 error toast:
