### ISSUE TITLE
Event editor should update fields visibility accoriding to picked event type

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1257]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=54&t=14791

When event type is changed in the editor, fields are not updated. This works in scheduler event editor.

**Comment by dongryphon** [comment]
This feels more like a bug, but just a quibble

**Comment by dongryphon** [comment]
Looks like the docs were wrong:
```javascript
    eventEdit : {
        items : {
            eventTypeField : {   // not "eventType"
                name : 'eventType',   // must match Model class field
            }
        }
    }
```

Also the model class must declare the `eventType` field:

```javascript
    class MyModel extends EventModel {
        static get fields() {
            return [
                { name : 'eventType' }
            ];
        }
    }
```

**Comment by dongryphon** [comment]
User reported that the above worked for him
