### ISSUE TITLE
Scheduler freezes after drag drop with many events

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1260]
https://www.bryntum.com/examples/scheduler/bigdataset/

Put 10k resources
drag an event
The drag drop is instant, some post processing makes browser freeze

**Comment by pmiklashevich** [comment]
When you drag a task dependency feature calculates the cache for the first time. 
Scheduler/lib/Scheduler/feature/Dependencies.js
```
    get dependencyGridCache() {
        const me = this;

        if (!me._dependencyGridCache) {
            me._dependencyGridCache = {};

            console.log('Generating cache for ' + me.dependencyStore.count + ' dependencies');
            console.time('Generate dependency cache');
            me.dependencyStore.forEach(dependency => {
                return me.addToGridCache(dependency);
            });
            console.timeEnd('Generate dependency cache');
        }

        return me._dependencyGridCache;
    }
```
Open http://lh/master/bryntum-suite/scheduler/examples/bigdataset/ and run in console
```
scheduler.features.dependencies.dependencyGridCache
```

Generating cache for 4000 dependencies
Generate dependency cache: 1026ms - timer ended

Generating cache for 20000 dependencies
Generate dependency cache: 20735ms - timer ended

Generating cache for 40000
Generate dependency cache: 79865ms - timer ended

addToGridCache => getDependencyBounds => which calls `getBox` 2 times:
```
            startRectangle = me.getBox(dependency, true, assignmentData),
            endRectangle   = me.getBox(dependency, false, assignmentData);
```
getBox => HorizontalRendering.getResourceEventBox => RowManager.getRecordCoords => getRecordCoordsByIndex = calculateTop

```
            top                   = me.allHeightsKnown
                // All heights are known (all rows visited or fixed row height), get actual top coord
                ? me.calculateTop(recordIndex)
                // Otherwise estimate
                : Math.floor(calculateFrom.y + calculateFrom.index * height),
```

So we loop through our rows and for each row RowManager.calculateTop loops from first to current row. Which is too expensive.
```
        // When not using fixed row height, we make an educated guess at the top. The more rows have been visited, the
        // more correct the guess is (fully correct if all rows visited)
        for (let i = 0; i < index; i++) {
            const record = store.getAt(i);
            top += this.getOffsetHeight(record);
        }
```

1. Need to improve RowManager.calculateTop performance.
2. Need to improve Dependencies.isDependencyVisible, so when the feature is disabled the cache is not recalculated. Need to add tests for enabling/disabling the feature and make sure cache is recalculated when the feature gets enabled.
For example:
```
    isDependencyVisible(dependency, assignmentData = null) {
        const me = this;

        // Lines cannot be visible if the feature is disabled
        if (me.disabled) {
            return false;
        }
```
