### ISSUE TITLE
Gantt+Scheduler demo: First scheduler resource row animates into view

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1266]
![Jul-30-2020 21-43-51](https://user-images.githubusercontent.com/218570/88967239-cdac0780-d2ad-11ea-9243-d83d7d6fe4a6.gif)
http://lh/bryntum-new/gantt/examples/gantt-schedulerpro/

**Comment by isglass** [comment]
Asked @matsbryntse if this really is undesired, if so we have to block rendering of grid rows until projects initial commit is complete
