### ISSUE TITLE
Events disappear after reapply zoom and filter in Non-Working Time demo

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1269]
Reproducible in this example:
[https://www.bryntum.com/examples/scheduler-pro/non-working-time/](https://www.bryntum.com/examples/scheduler-pro/non-working-time/)

Steps: 
1 - zoom in the axis using mouse wheel or your touchpad.
2 - apply filter with the button on the top panel
3 - zoom out using mouse wheel or your touchpad.
4- disable filter by click the button on the top panel.

Result: no events showed until you scroll time axis. Sometimes, depends on initial position of the axis you may see some of events, but they will blinking (show/hide) while scrolling.

Here is a video:
[pro-filter-reapply.mov.zip](https://github.com/bryntum/support/files/5006253/pro-filter-reapply.mov.zip)

**Comment by matsbryntse** [comment]
Not reproducible
