### ISSUE TITLE
Translation missing when load fails

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1276]
https://www.bryntum.com/examples/calendar/basic/
change url to something nonexisting
<img width="1608" alt="Screenshot 2020-08-01 at 12 26 43" src="https://user-images.githubusercontent.com/218570/89099824-5af87480-d3f2-11ea-91e7-62100bf5c7ad.png">

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/2102
