### ISSUE TITLE
tickWidth on responsiveLevels doesn't work

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1295]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=14841)

Steps to reproduce:

1. Go to https://bryntum.com/examples/scheduler/basic/
2. Open the code editor and change `tickWidth` value from 250 to 500.

Bug: There is no change on width of the ticks
Expected: The ticks must change width to 500
 
![Screen Shot 2020-08-04 at 14 00 31](https://user-images.githubusercontent.com/663908/89328136-e8d69880-d65a-11ea-83be-ccd413810c3c.png)

**Comment by isglass** [comment]
Might be because we renamed to `tickSize` back when we introduced vertical mode
