### ISSUE TITLE
Search feature renders incorrect result if content is not html encoded

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1300]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=14854)

Steps to reproduce:
1 - Open the [grid search example](https://www.bryntum.com/examples/grid/search/)
2 - On column First name, add this configs:

```
...
htmlEncode: false,
renderer: ({ value }) => `<span><a href="https://google.com/${value}" target="_blank">${value}</a></span>`
...
```

3 - On the top, type "Don" on search box;
4 - The grid filter and show the First names with link correctly [PASS]
5 - Now, on the search box type "Jan"
6 - The grid filter and show the First names but the links for Jane has a broken HTML tag [FAIL]:
![Screen Shot 2020-08-05 at 13 59 03](https://user-images.githubusercontent.com/663908/89447377-de340600-d723-11ea-8c06-aa4857d3c15a.png)

Expected: Render only the correct tags "span" and "a" with the correct url:
![Screen Shot 2020-08-05 at 14 02 36](https://user-images.githubusercontent.com/663908/89447701-6ca88780-d724-11ea-8908-e0f838a7d76e.png)

Test result:
![Screen Shot 2020-08-05 at 13 53 26](https://user-images.githubusercontent.com/663908/89446845-12f38d80-d723-11ea-93c8-a857ff7906d8.png)

**Comment by artigat1** [comment]
Is there any update on when this may be fixed? It's been causing the problem on our production site since Aug and still no fix.

**Comment by artigat1** [comment]
This keeps getting pushed from milestone to milestone. It was reported in Aug and still not fixed. This is affecting our product and users. Is there a realistic date when this might finally be looked at?

**Comment by jsakalos** [comment]
Can be reproduced in version 4.3.2

**Comment by matsbryntse** [comment]
Not reproducible
