### ISSUE TITLE
Store sorting improvements

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1303]
Old suggested approach replaced with:

- [x] Sort feature listens for `beforeSort` and applies any sorting fns defined on columns there. Removing the need for the store knowing about the fns, they will automatically be applied when sorting programmatically.

- [x] StoreSort docs for `sorters` should have wording updated. "Default sorters" -> "Initial sorters"

# Background from forum:

Sorting looks not consistent now. 
We have 2 ways to add custom sorters: 
1. using `sortable` prop for `columns[]`
2. using `sorters[]` for `store`

But, if we defined both, after first loading it will use #2 function, when we click on grid header, it will use #1 function, if we call `store.sort('name')`, no one will be used.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=14789)

Hello i try to sort ascending by default my header ? 

When i use a custom sort. I try to sort the scheduler ascending by default. But it's not work :/
I use this line for sort by default

```
this.scheduler.resourceStore.sort('name', true);
```

**Comment by isglass** [comment]
Configure sort feature with `prioritizeColumns` to make store use filter fn defined on a column.
