### ISSUE TITLE
Localization for topDateFormat doesn't apply in dayAndWeek mode

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1307]
It is possible to localize `topDateFormat` in `hourAndDay` preset mode, but it doesn't work in `dayAndWeek`/`weekAndDay` mode.
Easy to reproduce using https://bryntum.com/examples/scheduler/localization/ example.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=14871&p=75431)

Hi,
I'm trying to edit the format of dayAndWeek and weekAndDay. 
I created the file "scheduler.locale.It" with translations and this is the object with PresetManager: 

```
PresetManager: {
            minuteAndHour: { topDateFormat: "ddd MM/DD, hA" },
            hourAndDay: { topDateFormat: "ddd MM/DD" },
            monthAndYear: { topDateFormat: "YYYY" },
            weekDateAndMonth: { topDateFormat: "MMM YYYY" },
            dayAndMonth: { topDateFormat: "MMM YYYY" },
            dayAndWeek: {
              topDateFormat: "MMM YYYY",
            },
            weekAndDay: {
              displayDateFormat: "hh:mm A",
              topDateFormat: "MMM YYYY",
            },
            weekAndMonth: {
              topDateFormat: "MMMM YYYY",
            },
          }
```

but it doesn't format the top date correctly, because I'm trying to format "MMM YYYY" instead of "YYYY MMM dd"

**Comment by fabiojpoli** [comment]
Pushed on branch the tests for the issue and the solution for `dayAndWeek ` view preset.

For `weekAndDay ` viewPreset to translate the top header date format, have to define `middleDateFormat` property with the date format.

But as `middleDateFormat` is a confuse name to format the top header date was discussed with @ExtAnimal that there is needed a refactor to translate the headers.

Here is the context:
ViewPreset class has this code:
```
case 2:
                if (this.mainHeaderLevel === 0) {
                    result.middle = headers[0];
                    result.bottom = headers[1];
                }
                else {
                    result.top = headers[0];
                    result.middle = headers[1];
                }
                break;
```

on PresetManager class the viewPreset weekAndDay has  mainHeaderLevel : 0
means it wont have the top header property… but  when I change the locale to format the top header of the scheduler I have to do this:
```
weekAndDay : {
                    middleDateFormat : 'YYYY MMM DD'
                }
```

Here are the @ExtAnimal suggestions:
> Really it should be header0DateFormat etc
> or dateFormat[0] etc
> Or somethig which just coirresponds how the header array is
> I suppose singe the localization key can be anything, dateFormat[0], 1, 2 etc could woerk
> 
> I'm not sure whether thoe localizatuion properties existed when I refactored ViewPresets to use an aray of headers
> 
> I suspect not\And that the legacy configs were used to create those localization properties
> 
> that's all done using legacy header idea
> It should be just 0, 1, 2
> 
> And the localization props should change

@isglass please let me know your suggestions to refactor would have a big affect for users to translate viewPresets including our examples and maybe some guides. Thank you!
