### ISSUE TITLE
taskStore.move doesn't properly reflect changes on gantt

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1309]
Open gantt basic example and run in the console:

```
gantt.taskStore.move(
	gantt.taskStore.getById(3),
	gantt.taskStore.getById(1)
)
```
this will lead to incorrect displacement of objects for timeaxis. Reproduced in latest master and in released version.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=14887&p=75494)

> Hi,
> When using method move from taskStore on tasks, there is weird behaviour happening on the gantt. It looks like the change is somewhat reflected, but the tasks are incorrectly redrawed.

**Comment by matsbryntse** [comment]
Not reproducible
