### ISSUE TITLE
Grouping feature throws in Scheduler Pro Resource Histogram demo

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1313]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=51&t=14892&p=75520

To reproduce on pro react demo, add this config:
```
// react/javascript/resource-histogram/src/components/config.js
features: { group : 'city' },
// or
// groupFeature: { field : 'city' }
```

Throws error after short timeout:
```
Unhandled Rejection (Error): Unknown identifier ClassDefEx-group-header-Rome.$.assigned
throwUnknownIdentifier
```

**Comment by jsakalos** [comment]
Actually, this is not only problem of the React demo but also of vanilla demo. See the video:
![pro-grouping](https://user-images.githubusercontent.com/204844/89985537-82193680-dc7b-11ea-868e-cf6ea749ca58.gif)

**Comment by mmelcot** [comment]
Hi, I am the guy who raised the issue on Bryntum forum.

What I noticed is that the vanilla 'grouping' demos work correctly, but the React ones can't display groups at all, although using exactly the same Scheduler config and data.

So I believe there are two different issues: https://github.com/bryntum/support/issues/1313#issuecomment-672667324 and this one.

**Comment by bmblb** [comment]
@mmelcot could you please provide more info? I've tried scheduler and scheduler pro react demos with enabled grouping and couldn't reproduce any more issues.

**Comment by serbs** [comment]
Got the same issue. Appeared that Grouping and Tree features are not working together. Makes sense.
