### ISSUE TITLE
Implement demos with VUE 3 support

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1315]
Requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=14894&p=75522

**Comment by isglass** [comment]
Vue 3 is not yet release IIRC, but when it is we should for sure upgrade demos to it

**Comment by jsakalos** [comment]
I’ve been in Vue 3 world recently and here are my findings and recommendations that could interest you:

Vue 3 is not an incremental update but they bring new way how to write Vue applications, although the old way still works. The core of the new way is new “composition API”, while the old one is referred to as “options API”. Options API uses options of components to configure them, composition API uses `setup()` method where the component is configured - this is similar to React hooks.

There is also a new way how to create an app and a couple of renamed lifetime hooks. The one that most concerns us is `beforeDestroy` used in our wrappers to cleanup that has been renamed to `beforeUnmount` which de-facto breaks our wrappers in Vue 3.

Therefore:
1. We need Vue 3 specific wrappers (while keeping the existing ones for backward compatibility) written preferably with composition API
2. We need new Vue 3 demos that would use the composition API. I recommend to leave the existing demo untouched but to create new 3 versions. For example if we have `drag-from-grid` demo, I’d rather create a copy of it upgrade the copy to Vue 3 to have `drag-from-grid-3` demo. This way our users can compare. 
3. I recommend to upgrade (with copy) one basic, simple demo and one of more advanced demos at the beginning. New demos should be created with Vue 3.
4. We need to distinguish Vue 2 and 3 in the Integration guide
