### ISSUE TITLE
Provide precision config to be used when calculating floating numbers for model fields

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1320]
Required in the PM tool.

Recommended precision could be 7-8. Can be null by default to avoid rounding. Should be public, so users can configure it.

Usecase:
When engine calculates task fields, for example duration, the value could be a float number. In case it has 3 decimal numbers and DB is configured to 2 decimal numbers, the value will be rounded on the server. For example calculated value is 25.875. Then on sync it will be rounded to 25.88. Next time the data is loaded it will be automatically recalculated to 25.875 and become modified. So if will be sent to server with next sync request. And that will end up in infinite loop. Increasing precision in DB is not enough because value is not limited manually. It's limited to JavaScript number. To avoid rounding on server all floating numbers should be configured with a precision. Then it's possible to configure DB with the same precision and rounding will never happen on the server.

**Comment by isglass** [comment]
This is probably easily solved after @dongryphon's PR on fields is merged
