### ISSUE TITLE
Setting new data while store is filtered breaks rendering

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1332]
Open grid/examples/filtering/
Filter age column to equal 14
In console replace the dataset
`grid.store.data = [{ age : 15 }, {age : 14}]`

No rows shown

<img width="705" alt="Screenshot 2020-08-13 at 16 48 48" src="https://user-images.githubusercontent.com/218570/90149564-ea077400-dd84-11ea-989b-4d9773fb2ae0.png">

**Comment by isglass** [comment]
Data level issue, store ends up empty

**Comment by isglass** [comment]
Seems to work as it should?
