### ISSUE TITLE
Live example not loading data

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1336]
https://www.bryntum.com/docs/scheduler-pro/

<img width="1172" alt="Screenshot 2020-08-13 at 17 17 16" src="https://user-images.githubusercontent.com/218570/90155759-fb07b380-dd8b-11ea-9440-293f272cfc50.png">

**Comment by bmblb** [comment]
data.json is missing on the server. works fine in local release. @SergeyMaltsev please take over

**Comment by bmblb** [comment]
Fixed online and in sources. Not mentioned in changelog, closing right away.

**Comment by arcady-zherdev** [comment]
Closed before release since the docs were hot-patched online and the issue was actually related to online version of the docs only.
