### ISSUE TITLE
Poor performance of summary feature on big datasets

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1338]
Scheduler Summary should use HorizontalTimeAxis for rendering to have virtualization.

Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=14907

Steps to reproduce on bigdataset demo:
1. add summary feature:
```
summary : {
            renderer({ events }) {
                return `<label>${events.length ?? ''}</label>`;
            }
        }
```
2. run demo, generate 50 events per row. with profiler it takes >1 minute to finish the task

**Comment by bmblb** [comment]
Summary feature doesn't support virtual rendering, calculating summaries for the whole time span. Need to implement same approach as with time header.

**Comment by chuckn0rris** [comment]
Duplicated with https://github.com/bryntum/support/issues/2977
