### ISSUE TITLE
Histogram with group feature

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#1341]
Feature request for histogram with grouping

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14920)

Hi,

I'm grouping the histogram grid on a resource property:
```
features    : {
        group   : 'trade'
    }
```

But when that's active, the maximum effort is not rendered correctly/completely. It's rendered for only 1 resource:
![Bryntum Gantt - 012.png](https://www.bryntum.com/forum/download/file.php?id=10942)

Could you have a look at that? Thank you.

**Comment by pmiklashevich** [comment]
ResourceHistogram works when grouping is enabled

SchedulerPro/examples/resourcehistogram/app.js
```
const histogram = window.histogram = new ResourceHistogram({
    features : {
        group : 'city'
    },
```
<img width="1988" alt="Снимок экрана 2021-01-25 в 18 29 34" src="https://user-images.githubusercontent.com/57486733/105726620-4decb600-5f3b-11eb-81df-0518eadead14.png">
