### ISSUE TITLE
Translation missing in bigdataset demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1347]
<img width="309" alt="Screenshot 2020-08-19 at 09 26 52" src="https://user-images.githubusercontent.com/218570/90605270-645d4b80-e1fe-11ea-8c0c-1ea8d246a31a.png">

Should throw exception for non-found translations

**Comment by SergeyMaltsev** [comment]
This phrase comes from
SchedulingEngine/lib/Engine/quark/model/scheduler_basic/SchedulerBasicProjectMixin.ts:445
```
replica.onPropagationProgressNotification({ total : 0, remaining : 0, phase : 'storePopulation' })
```

- It is not covered with tests while it has no localization tests for Engine
- If it should be localizaed we expect L{storePopulation} to throw error
- Engine should be able to consume Bryntum localization from upper project
