### ISSUE TITLE
Not possible to type into field with text selected

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1349]
Open http://lh/bryntum-new/gantt/examples/bigdataset/
Change to 10k tasks
Select text in the input field (10000) and type 5 - no reaction

**Comment by bmblb** [comment]
Problem is number field not allowing to type new value which violates _min_ constraint, when text is selected. So far it only allows to type invalid value to empty field.
Another problem is that current Siesta version cannot test this. We need to emulate key event when field has selection. But instead siesta deliberately clears selected value first. Discussed with @canonic-epicure , decided to skip test.
