### ISSUE TITLE
Excel export turns numbers into text

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1350]
Which makes it harder to summarise etc in Excel. Should respect column (or perhaps field) type

**Comment by isglass** [comment]
This is a bug with the excel lib we are using: https://github.com/egeriis/zipcelx/issues/63

**Comment by bmblb** [comment]
Entire year has passed since issue was created. We could try to make a PR, but repo feels abandoned. Maybe we should make our own small library to generate Excel-compliant XML

**Comment by fabiojpoli** [comment]
After removed the code commented previously the number values was converted correctly and no error on Excel for Mac, or latest Excel for windows (tested by Max) for examples/exporttoexcel.
