### ISSUE TITLE
Show group summary in group header for collapsed groups

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1355]
To have the information always visible, without the clutter of always showing the group footer
- [ ] Grid support
- [ ] Scheduler support (see https://bryntum.com/examples/scheduler-for-extjs/kitchensink/#examples/grouping)

**Comment by isglass** [comment]
Makes for a nice look, but probably needs to be sponsored, not requested before. @matsbryntse?

**Comment by isglass** [comment]
Requested here too https://www.bryntum.com/forum/viewtopic.php?f=44&t=15700&p=78534

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/2387
