### ISSUE TITLE
Radio button + radio group widgets

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1357]
Add new widget
+ Radio Group widget ( Yes / No type UI)

https://www.bryntum.com/forum/viewtopic.php?f=52&t=16010&p=79794
https://www.bryntum.com/forum/viewtopic.php?f=44&t=18944&p=93653#p93653

**Comment by jsakalos** [comment]
Also requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=20063
