### ISSUE TITLE
Dragging multiple events with `unified drag` config shows visible lag in the beginning

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1361]
To reproduce on dragselection demo select 3 events, enable unified drag, start dragging. You'll notice significant delay with a laggy animations in Firefox 79. A little bit better in chrome
![drag](https://user-images.githubusercontent.com/45400762/90731888-f6cf1f00-e2d2-11ea-9175-549f9fc36441.gif)

**Comment by matsbryntse** [comment]
Dupe #627
