### ISSUE TITLE
Column header doesn't show grouping icon

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1363]
Steps to reproduce on dragselection demo:
1. Open context menu on Name column, group in any direction. Notice the icon, see how it changes when clicking header
2. Now sort column using context menu. Icon is changed. 
![icon](https://user-images.githubusercontent.com/45400762/90732437-c340c480-e2d3-11ea-9563-4195f8838e38.gif)

**Comment by matsbryntse** [comment]
not reproducible
