### ISSUE TITLE
Drag drop of multiple selected events in vertical mode does not work

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#137]
Open https://www.bryntum.com/examples/scheduler/dragselection/

https://www.bryntum.com/forum/viewtopic.php?f=44&t=13025&p=68023#p68023

Select a few events, drag events to the right. 
Note weird effects
Drop, not wrong placement

<img width="551" alt="Screenshot 2019-12-30 at 21 23 21" src="https://user-images.githubusercontent.com/218570/71599312-a855f000-2b4a-11ea-94c9-34f22e1e70fc.png">

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/427
