### ISSUE TITLE
Drag create breaks leaving visible proxy

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1376]
Steps to reproduce on timeaxis demo:
1. start dragcreate, don't close editor
2. start another drag create, drag pointer by a minumum width to see drag proxy, release pointer -> proxy is there, new drag create wouldn't start
![dragcreate](https://user-images.githubusercontent.com/45400762/90749313-f8511500-e2db-11ea-8f2e-e4bd7df654c6.gif)

**Comment by isglass** [comment]
Reproduces by only performing step 2
