### ISSUE TITLE
Grouping and sorting is available in predecessors grid header context menu, but features don't work

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1377]
Reproducible on basic demo. Start editing `Run tests` task, go to predecessors tab, try to sort/group. Header is updated, but grid content is not. Need to either fix grid or disable header menu

- [x] Disable grouping
- [x] Disable sorting on type column
- [x] Fix sorting on lag column

**Comment by isglass** [comment]
Grid has those features by default, needs to be based on GridBase or disable the features
