### ISSUE TITLE
eventStore.getEvents could go into infinite loop if recurrence feature is enabled

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1396]
To reproduce on recurrence demo call this in console:
```
scheduler.eventStore.getEvents({ resourceRecord : scheduler.resourceStore.first })
```
Pause in a second or two, see browser is constantly generating occurrences.

1. It is not stated in the docs, that start/end are required with recurrence
2. leaving option to go infinite loop that easy is no good

Probably if start/end are omitted, recurrence mixin should only generate few occurrences. 1 maybe?

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/1903
