### ISSUE TITLE
Card layout change animation

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1413]
Calendar view switch animation is not really a _smooth view transition_. When switching from hour to week view you can see day view is animated to the right, hovering side bar and when it moved to the left most position - it disappears immediately. It is odd because:
1. view goes to a position where it doesn't belong - it hovers the side bar
2. view position is animated but disappearance is instant
![calendar animation](https://user-images.githubusercontent.com/45400762/91313571-352a7980-e7be-11ea-8bf0-9c0f497def97.gif)

I'd say when switching view, old one should get _under_ the side bar. And, by analogy, it should not appear at the top of the side bar when it becomes active. That'd be ideal

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/1933
