### ISSUE TITLE
Allow only 0 or 100 % progress on Milestones

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#1415]
Progress on a Milestone should either be 0% or 100%.  Bryntum allows any figure to be added.  Have you considered this as an issue?

Also the progress line seems to ignore milestones, so it is not possible to assess progress visually on milestones

**Comment by isglass** [comment]
Compare with MSP

**Comment by matsbryntse** [comment]
MSP allows any value
<img width="1094" alt="Screenshot 2020-11-01 at 20 23 23" src="https://user-images.githubusercontent.com/218570/97812216-1ba32380-1c80-11eb-8738-1d613859e729.png">

**Comment by matsbryntse** [comment]
Progress line issue https://github.com/bryntum/support/issues/3264

**Comment by matsbryntse** [comment]
Easily solved in app code by setting https://bryntum.com/products/scheduler/docs/api/Core/widget/NumberField#config-step to 100
