### ISSUE TITLE
Calendar. Cannot read property 'widgetMap' of undefined on event create

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#1426]
http://lh/bryntum-suite/Calendar/examples/eventedit/

Open demo and try to dragcreate Event.

```
EventEdit.js:201 Uncaught (in promise) TypeError: Cannot read property 'widgetMap' of undefined
    at EventEdit.internalShowEditor (EventEdit.js:201)
    at EventEdit.doEditEvent (EventEdit.js:145)
```

**Comment by dongryphon** [comment]
I am not seeing this locally. Can you retry and if you do make it happen, maybe provide more specifics on what your drag operation looked like? From where to where did you drag, for example. Also, if you break on error in the debugger, can you post a screen shot of the stack and current scope?
