### ISSUE TITLE
CSS styling collisions for few products on one page

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#1430]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=15099)

Check how styles are applied for a few components like Grid/Calendar/Scheduler/etc... on one WEB page when importing few css files one by one? 
If it possible to use it without collisions?

**Comment by isglass** [comment]
Will be fixed by #3276

**Comment by isglass** [comment]
Thin css bundles are now available both on npm and in the download, closing this ticket
