### ISSUE TITLE
Recurring events don't render on load

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#1431]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15062)

1. Open recurrence Scheduler demo 
2. Add this to app.js
```
WidgetHelper.append([
    {
        type : 'button',
        cls  : 'b-orange b-raised',
        text : 'Reload',
        onClick() {
            scheduler.crudManager.load();
        }
    }
], { insertFirst : document.getElementById('tools') || document.body });
```
3. Load demo, click Reload button twice.

Recurring events disappear.
![RecurringLoad](https://user-images.githubusercontent.com/57486330/91713149-0a1f9b80-ebab-11ea-9de8-09ea4a2d5b8c.gif)

**Comment by ExtAnimal** [comment]
If this is from a pre 4.0.0 version of Scheduler, and cannot be reproduced on 4.0.0 then this ticket should be closed. Recurring events were completely refactored for 4.0.0

**Comment by ExtAnimal** [comment]
A bug does manifest in 4.0.0

`Scheduler.data.mixin.RecurringTimeSpansMixin` needs this to fix it:

```
    set data(data) {
        // All cached occurrences are now invalid with a new dataset
        this.globalOccurrences.clear();
        super.data = data;
    }
```
