### ISSUE TITLE
Events could be added to read only calendar through UI

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1437]
To reproduce dblclick day number in calendar preview:
![image](https://user-images.githubusercontent.com/45400762/92082970-f7d17780-edcd-11ea-9f9a-4e40a92c5645.png)

**Comment by dongryphon** [comment]
I tried adding `calendar.readOnly = true` to the unit tests but it does not exhibit this issue. Where did you see this?

**Comment by bmblb** [comment]
Cannot reproduce
