### ISSUE TITLE
Card layout animation is not triggered when switching active view fast

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1438]
http://lh/bryntum-suite/calendar/examples/basic/
pick new mode and then immediately pick another, while animation still in progress. you'll notice first active view was sliding into visible area and 2nd just got displayed immediately
![card](https://user-images.githubusercontent.com/45400762/92083588-ef2d7100-edce-11ea-9f05-212467a0dced.gif)

**Comment by ExtAnimal** [comment]
I can reproduce no fault with card switching.
