### ISSUE TITLE
New event is visually moved after drag create

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1440]
http://lh/bryntum-suite/calendar/examples/basic/
After drag create event is resized by ~2px and moved 1px below original position. Position should be exact from the beginning.
![new event](https://user-images.githubusercontent.com/45400762/92084405-0325a280-edd0-11ea-9656-94b79ea0b143.gif)

**Comment by isglass** [comment]
@dongryphon Intentional to set apart from existing events?

**Comment by dongryphon** [comment]
Looks like the "layout" done for the drag create indicator is slightly off. Probably missing a CSS class or something. It was not intentional. I don't hate it though :)

**Comment by ExtAnimal** [comment]
This seems fixed too

**Comment by matsbryntse** [comment]
No repro
