### ISSUE TITLE
`+n more` label style is inconsistent

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1445]
Sometimes when clicking it font becomes bold, sometimes not
![styling1](https://user-images.githubusercontent.com/45400762/92088076-138c4c00-edd5-11ea-9066-dd3b8a40a421.gif)

**Comment by fabiojpoli** [comment]
Unable to replicate on Chrome(Mac), @bmblb please test again to confirm. Thanks.

**Comment by ExtAnimal** [comment]
It has a "focused" rendition (the left cell below), and a "hovered" rendition (the right cell below)

This works as expected.

![Screenshot 2021-01-12 at 14 53 35](https://user-images.githubusercontent.com/200516/104323036-9341ca00-54dd-11eb-83da-d0f51b99b772.png)
