### ISSUE TITLE
Event editor does not appear when adding event to agenda

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1450]
Related issue: https://github.com/bryntum/support/issues/1444
![add](https://user-images.githubusercontent.com/45400762/92090751-7d5a2500-edd8-11ea-9cc2-c77dedc3cee4.gif)

**Comment by dongryphon** [comment]
Seems to be fixed:

![dblclick-create-agenda-view](https://user-images.githubusercontent.com/722969/97121878-876d1580-16ef-11eb-9138-3d37a18f7f59.gif)
