### ISSUE TITLE
Rows are hightlighted inconsistently in agenda view

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1453]
http://lh/bryntum-suite/calendar/examples/basic/
1. switch to agenda view, hover pointer over first day in agenda - it get a bg color. hover next day - it doesn't get bg color.
2. click event in first day, see bg color removed from the day. move pointer inside the event element to the circte - see bg color gets appended when pointer is still over the event
![bg](https://user-images.githubusercontent.com/45400762/92093721-556cc080-eddc-11ea-811e-2c1c51811e8d.gif)

3, when day in agenda is selected highlighting is also different. when click event and then hovering row you might observe slightest bg color change
![bg(1)](https://user-images.githubusercontent.com/45400762/92094159-cf9d4500-eddc-11ea-91b5-3b7370813731.gif)

4. hovering date puts a bg color to it, but there is no action associated with the day. what is the point of highlighting it then?
![bg(2)](https://user-images.githubusercontent.com/45400762/92094409-15f2a400-eddd-11ea-8282-f4d18aa8ee3c.gif)

**Comment by isglass** [comment]
All 4 issues fixed along the way, closing
