### ISSUE TITLE
Active view is incorrect when double clicking day in year view

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1457]
http://lh/bryntum-suite/calendar/examples/basic/
Could be FF specific.
Go to year view, dblclick any day. View is changed but button group still shows year as active. Try a few times.
![bug(5)](https://user-images.githubusercontent.com/45400762/92095424-543c9300-edde-11ea-9d17-5ec0aafb66bd.gif)

**Comment by dongryphon** [comment]
I cannot reproduce this anymore on Chrome or FF. @bmblb can you give it a try? I'd say maybe it is Mac specific except you are on Windows, right?

**Comment by bmblb** [comment]
Cannot reproduce
