### ISSUE TITLE
Tooltip jumps trying to follow by the TimeRange element

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1458]
http://lh/master/bryntum-suite/scheduler/examples/timeranges/

![Запись активности на экране 2020-09-03 в 12 09 13](https://user-images.githubusercontent.com/57486733/92095975-0a07e180-eddf-11ea-9492-06d93cb74a28.gif)

**Comment by ExtAnimal** [comment]
Since `html` became a configurable config, it only realigns when the html **changes**, not whenever it's attempted to be set. Somehow it needs to align whenever the html setter is called.

**Comment by ExtAnimal** [comment]
The fix in Tooltip.js is to always realign on set of html:

![Screenshot 2020-09-03 at 11 34 43](https://user-images.githubusercontent.com/200516/92098421-18e79780-edd1-11ea-92ee-947ef8020e0a.png)
