### ISSUE TITLE
Pressing ESC when dragcreating leaves drag proxy

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1459]
http://lh/bryntum-suite/calendar/examples/basic/
Start dragcreate, press ESC at any point. Proxy is not cleared, events cannot be dragdropped.
![bug](https://user-images.githubusercontent.com/45400762/92097202-79ca9c00-ede0-11ea-92ab-422976f2e0b8.gif)

**Comment by dongryphon** [comment]
It throws an error. Should be easy fix. I created a failing test case on my branch and will get the fix in tomorrow. This problem will present in all drag modes, so it will need a bunch of test cases to cover them.
