### ISSUE TITLE
Calendar CTRL key behavior on Mac

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1460]
While drag-creating an event in calendar the tooltip suggests that holding CTRL key creates a recurring event. That does not happen when pressing CRTL during dragging.

When pressing and holding CTRL before D&D system context menu appears and continue dragging leads to an error (2nd part of the video).

![calendar-ctrl](https://user-images.githubusercontent.com/204844/92097927-ea6dba80-edd8-11ea-9a09-eae07bdae6ad.gif)

**Comment by ExtAnimal** [comment]
This is working as designed. Dragging into another column implies also occurring on
 that day, and a rectangular range is selected.

![Screenshot 2020-09-03 at 11 39 49](https://user-images.githubusercontent.com/200516/92098944-cce92280-edd1-11ea-98da-a1438474057e.png)

**Comment by jsakalos** [comment]
Pressing and holding CTRL *before* the drag first displays the system context menu and, while keeping CTRL pressed, when insisting on dragging the error appears (2nd part of the video).

**Comment by pmiklashevich** [comment]
> Pressing and holding CTRL _before_ the drag first displays the system context menu and, while keeping CTRL pressed, when insisting on dragging the error appears (2nd part of the video).

@jsakalos whenever CTRL is mentioned it means CMD in MacOS.

**Comment by dongryphon** [comment]
It is also true that Cmd and Ctrl are swapped on the Mac. We should probably tweak the text from "CTRL to ..." to "CTRL or CMD to ..." or something.

**Comment by dongryphon** [comment]
The tooltip during drag create has been removed, so the Cmd/Ctrl text is no longer an issue. The behavior for recurrence is as Nige described: only if you cross into adjacent days for a COUNT recurrence. The tooltip owner has been resolved by above PR, but I cannot test on a Mac to see if the Ctrl key + context menu error is resolved.

**Comment by dongryphon** [comment]
Give or take the Mac-specific error that may be fixed, I believe we can close this one.
