### ISSUE TITLE
Cells are not aligned in first row in predecessors/successors grid

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1463]
http://lh/bryntum-suite/gantt/examples/aggregation-column/

FF only

![image](https://user-images.githubusercontent.com/45400762/92100122-10e52300-ede4-11ea-9ba8-c8660d982872.png)

looks fine in advanced demo where content is overflowing vertically

![image](https://user-images.githubusercontent.com/45400762/92100363-64577100-ede4-11ea-8213-6fdb388c1548.png)

**Comment by matsbryntse** [comment]
not reproducible
