### ISSUE TITLE
Enabling Snap changes schedule zone width on wide screen

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1469]
http://lh/master/bryntum-suite/scheduler/examples/timeresolution/

Make sure your screen is wide. Click on the Snap checkbox. See the columns move a bit.
![Запись активности на экране 2020-09-03 в 13 50 11](https://user-images.githubusercontent.com/57486733/92106188-b00e1880-edec-11ea-9e5d-811ca5e30d42.gif)

**Comment by isglass** [comment]
Expected to fit full half hours with whole pixels
