### ISSUE TITLE
Improve support for async tooltips

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#148]
https://www.bryntum.com/forum/viewtopic.php?f=51&t=12455

Show off async content in http://lh/bryntum-suite/scheduler/examples/tooltips/

- [x] Update demo with tabpanels, add new async scheduler tab
- [x] Discard loading promises that belong to previous irrelevant targets
- [x] Core Tooltip tests + inc 404 on tooltip load, show error
- [x] Async Grid Cell Tooltip tests
- [x] Async Scheduler Event Tip tests
- [x] async docs core
- [x] async docs grid
- [x] async docs scheduler
- [x] async tooltips demo in Grid docs
- [x] async tooltips demo in Scheduler docs
- [x] add docs for params of getHtml
- [x] Test for showAsyncMessage
- [x] Write a What's new section for Grid
- [x] Write a What's new section for Scheduler
- [x] Update legacy docs in Tooltips for asyncness
- [x] Assert returning false still works
- [x] changelog
- [x] Add bryntum.deprecate for code returning `false` to warn users of deprecation
- [x] Add test confirming deprecation warning
- [x] rename params of getHtml
- [x] Repaint line during dependency drag create + test

**Comment by pmiklashevich** [comment]
The bug is solved here: https://github.com/bryntum/support/issues/122
This is a public version of the feature request described here: https://github.com/bryntum/bryntum-suite/issues/330
