### ISSUE TITLE
Recurring events repeats endless after delete one of occurrences

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1481]
Reproduced in master and release.
1. Open [https://www.bryntum.com/examples/examples-scheduler/recurrence/](https://www.bryntum.com/examples/examples-scheduler/recurrence/)
2. Add new event and set it to repeat daily, end repeat after 5 times.
3. Delete the first occurrence (not origin) of this event using "Delete all future events" button.
4. Occurrences for this event will be rendered endless instead of remove all future events.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=15188&p=76423)

Also existed in Calendar:
https://www.bryntum.com/forum/viewtopic.php?f=54&t=18835&p=93159#p93159

1. Create new event, repeat every day, ends after 2 times repeat.
2. Delete second occurence as "this and all future events"

Actual:
The original event will be repeated endless every day.

Expected:
The original event should be the only existed without occurrences.

**Comment by arcady-zherdev** [comment]
Cannot reproduce this now. It was probably fixed due to changes made for #3456
