### ISSUE TITLE
Show a tooltip when drag an event from the grid to scheduler

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1482]
Extend our example to have a tooltip on drag an event from the grid to the scheduler with start/end time info, like it shows up on drag from scheduler to scheduler or inside the scheduler.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15175&p=76399)

Hi support,
Is it possible to display start time (e.g: 10:11 AM) to drop zone when drag event from grid to scheduler so we could know the exact start time of the event before drop (when we drag the event around this time will also change depend on the zone we would like to drop)?

**Comment by SyCuongVM2** [comment]
Dear support,
This feature has been implemented yet or not?

**Comment by bmblb** [comment]
@SyCuongVM2 when we implement a feature we first put `resolved` label and then close issue when feature is released. So no, not implemented yet.

**Comment by fabiojpoli** [comment]
Feature in progress. Tests ready and work in progress in branch 1482.
