### ISSUE TITLE
Step triggers not horizontally centered

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1484]
<img width="161" alt="Screenshot 2020-09-07 at 12 01 22" src="https://user-images.githubusercontent.com/218570/92385595-7736b200-f112-11ea-950a-6b88b2b55528.png">

**Comment by isglass** [comment]
Step triggers has 0.8em padding, date trigger has 0.5em

Also need to adjust inputs vertical centering:

<img width="1076" alt="Screenshot 2020-09-10 at 13 42 40" src="https://user-images.githubusercontent.com/5415653/92725104-e5c27c80-f36b-11ea-954c-bb376ab10369.png">

**Comment by ExtAnimal** [comment]
It's all centered vertically. It has

```
.b-field-inner {
    display: flex;
    flex: 1 1 100%;
    align-items: center;
```

It's just that due to inherited styling, the icons themselves adopt a height in which their glyph is not centered.

The `.b-numberfield .b-fieldtrigger, .b-textfield .b-fieldtrigger` rule needs `line-height : 0`
