### ISSUE TITLE
Add new 'dataready' event on Store

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1486]
'dataset' is not useful since the introduction of engine to scheduler since end dates aren't available until project has calculated them async.

In this simple example event has no `endDateMS` which is needed in various APIs of ours
```
 onStoreChange(event) {
        switch (event.action) {
            case 'add':
            case 'dataset':
                event.records.forEach(event => {
                    const { lat, long } = event;

                    if (lat && long && this.timeAxis.isTimeSpanInAxis(event)) {
                        this.addMarker(event);
                    }
                });
                break;
```

This works as a workaround, but could / should we hide this in our internals pre-firing store events to make lives easier for our customers? Downsides?
```
async onStoreChange(event) {
        // TODO remove
        await event.source.project.commitAsync();

  
```

**Comment by canonic-epicure** [comment]
Shouldn't the store just fire the `change/update` events and rendering should account for possibly missing data?
