### ISSUE TITLE
Dependency lines are not removed when regenerating dataset

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1487]
Reproducible on scheduler bigdataset demo. Enable dependencies, generate 10 resources (ignore exception it is fixed in #1462 )
![dependencies_bug](https://user-images.githubusercontent.com/45400762/92447232-a6572d00-f1bf-11ea-8b5f-396e341d3831.gif)

**Comment by ExtAnimal** [comment]
Duplicate. changing the store in the Scheduler does not change the stores that Features have cashed.

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/support/issues/1447

**Comment by isglass** [comment]
Cause was tracking of drawn deps lost when project wasn't ready on draw
