### ISSUE TITLE
Copy / Cut / Paste event API + context menu entries

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1489]
Make possible copy/cut and paste events using keyboard ctrl c/x + ctrl v

Also add option Copy, Cut and Paste options on context menu.

[Forum Post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15196)

**Comment by zhouhu** [comment]
This is one of the most required features from our endusers, are there any estimation on the delivery date of this feature? Thank you.
