### ISSUE TITLE
Gantt ASP.NET demo issues

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1495]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=52&t=15217&p=76526

1. project includes missing files (advances.css etc)
2. js app is not built on start
3. npm packages missing because of linked package, need to add this to webpack:
```
module.exports = [
    {
        entry : {
            cruddemo : path.join(__dirname, 'app.js')
        },
        resolve: {
            symlinks: false
        },
```

Check other (not core) demos too

**Comment by isglass** [comment]
Demos updated recently for another ticket
