### ISSUE TITLE
Event added using Plus button on the TopBar loses some data

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1497]
1. Open https://bryntum.com/examples/scheduler/eventeditor/
2. Add event using "plus" button on the TopBar, fill in all fields.
3. Double-click to open EventEditor for just added event.
See that "Appointment" field has no value.

Reproduced in master/release as well. Please check Vue/React examples too, all that has "Plus" button on TopBar to add event.
Please add tests.

Please, post a workaround for user if you find it during investigation to unblock him asap.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15223&p=76575)

**Comment by matsbryntse** [comment]
Issue is that wrong model is used in the button add method, should use model from eventStore
