### ISSUE TITLE
Basic React+TypeScript demo throws an error on launch

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1498]
Goto examples/react/typescript/basic demo, run
```
npm i
npm run start
```

App won't start:
<img width="1228" alt="Screenshot 2020-09-10 at 12 54 00" src="https://user-images.githubusercontent.com/7203098/92692202-a09b4c00-f365-11ea-98e3-fa787048eefe.png">

Reproduces in scheduler-3.1.9 and in `master`. `release` branch having issues too:
 
<img width="1228" alt="Screenshot 2020-09-10 at 13 03 36" src="https://user-images.githubusercontent.com/7203098/92692469-0be51e00-f366-11ea-93a7-e35f8685b9fc.png">

**Comment by chuckn0rris** [comment]
@jsakalos Do we still need to do something with that now?

**Comment by SergeyMaltsev** [comment]
Not reproducible in 4.1.4.
