### ISSUE TITLE
Clear filter doesn't reset list when using group

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1502]
Steps to reproduce:
- Open demo: https://www.bryntum.com/examples/examples-scheduler/react/javascript/filtering/
- Right button click on Staff column and click on Grouping Ascending on menu context
- Collapse all groups
- Type "Dave" on filter for column Staff
- Click on "x" to clear the filter
- The filter is still applied, only Dave is on the list

[Forum post](https://bryntum.com/forum/viewtopic.php?f=44&t=15241)

**Comment by matsbryntse** [comment]
Not reproducible?

**Comment by fabiojpoli** [comment]
Still reproducible: 
![Nov-02-2020 06-21-14](https://user-images.githubusercontent.com/663908/97862660-b842e100-1cd3-11eb-8561-1748b034afab.gif)

**Comment by pmiklashevich** [comment]
Reproduced here: http://lh/bryntum-suite/scheduler/examples/filtering/
Based on the steps the issue is identical to the #1596
