### ISSUE TITLE
Sub-events disappear when you drag-resize events in Nested events demo in simple Scheduler

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1518]
https://www.bryntum.com/examples/scheduler/nestedevents/
![Запись активности на экране 2020-09-14 в 18 26 24](https://user-images.githubusercontent.com/57486733/93105750-1c73fc00-f6b8-11ea-9917-b2d3faacdbdd.gif)

Also there is a UI regression in master, so when you drag resize an event, it's body is colored and it's not possible to see sub-events.
![Запись активности на экране 2020-09-14 в 18 34 52](https://user-images.githubusercontent.com/57486733/93106655-3d891c80-f6b9-11ea-925e-61a22c93e311.gif)

Also sub-events should not keep time when you drag-resize by the left handler to the left. It should keep relative position to the beginning of main event.
![Запись активности на экране 2020-09-14 в 18 38 38](https://user-images.githubusercontent.com/57486733/93106993-aff9fc80-f6b9-11ea-8f21-3324441296b7.gif)

Content overflows if resizing to make event smaller.

**Comment by bmblb** [comment]
Also note event color changing when resizing start. Try left edge too. Sub events should remain in place, if possible
