### ISSUE TITLE
Task Editor fields should not marked invalid at initial show

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1529]
<img width="455" alt="Screenshot 2020-09-17 at 09 05 18" src="https://user-images.githubusercontent.com/218570/93431777-eb1c4b80-f8c4-11ea-979f-7cb9b3dc1311.png">

Click New event button at http://lh/bryntum-new/schedulerpro/examples/maps/

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/2353
