### ISSUE TITLE
Paths disappearing on scroll

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1543]
The paths lines are disappearing after drag critical paths and scroll to right.

How to reproduce:
- Run http://lh/master/bryntum-suite/Gantt/examples/php/
- Click on top bar button "Critical Paths" to activate it
- Drag task "Install apache" to Feb 3rd
- Scroll horizontally to right to the end
- Result:
![Screen Shot 2020-09-18 at 10 32 58](https://user-images.githubusercontent.com/663908/93610223-cd211a80-f99a-11ea-876c-059bf1d5e4fa.png)
- Scroll to left and paths are visible again

**Comment by isglass** [comment]
Affects all dependencies, very critical

**Comment by isglass** [comment]
My previous comment was wrong, only happens with critical paths active

**Comment by isglass** [comment]
Caused by deps being sorted, need @arcady-zherdev to figure out why

**Comment by isglass** [comment]
Turns out if was a mistake in the sorting PR, fixed
