### ISSUE TITLE
Mini demo in example browser fails to load for classic themes in IE11

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#1545]
### Steps to reproduce

- Open Grid demo browser in IE11. (https://www.bryntum.com/examples/grid/)
- Select Classic-dark theme 
- Reload page

Console error arpears
```
Grid element not sized correctly, please check your CSS styles and review how you size the widget
```

![image](https://user-images.githubusercontent.com/57486330/93764996-fad5c000-fc35-11ea-88d6-077f6caa30bb.png)

**Comment by isglass** [comment]
Works fine for me, perhaps fixed by something else

**Comment by pmiklashevich** [comment]
Checked on the latest master. I see BG color is dark, but rows are missing. When I click on the grid the rows become visible. 
<img width="1332" alt="Снимок экрана 2020-10-07 в 10 42 17" src="https://user-images.githubusercontent.com/57486733/95301962-f93d0680-0889-11eb-9803-bcff01f98eca.png">
