### ISSUE TITLE
Previous value shown on drop event

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1547]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15327)

Steps to reproduce:
1 - On Scheduler/examples/vue/javascript/simple/src/components/schedulerConfig.js change the scheduler config to:
```
export default {
    ...
    listeners : {
        afterEventDrop : ({ eventRecords }) => {
            eventRecords[0].resourceName = eventRecords[0].resource.name;
        }
    },
    columns : [
        { text : 'Name', field : 'name', width : 130 }
    ]
}
```

2 - On Scheduler/examples/vue/javascript/simple/src/App.vue attribute the config:
```
<scheduler
    ...
    :eventRenderer    = "schedulerConfig.eventRenderer"
    :listeners        = "schedulerConfig.listeners"
></scheduler>
```
3 - Run the example and drag event to a different resource:
![Sep-21-2020 08-23-52](https://user-images.githubusercontent.com/663908/93768207-0c43ab80-fbe7-11ea-8bf9-87390b22b7c4.gif)

Looks like the record parameter refers to a previous record dropped instead of the current.

It works fine on https://www.bryntum.com/examples/scheduler/basic/ . Please check for all frameworks to confirm that works as expected.

**Comment by matsbryntse** [comment]
Doubt this is a bug, likely user error - not adding the field to their model

**Comment by chuckn0rris** [comment]
We should use `context.newResource.name` instead.

**Comment by chuckn0rris** [comment]
Further investigation showed up that the problem was in the next: 
`eventRenderer` called before the `afterEventDrop`. In case `resourceName` is not model's field, the UI will not reflect to the change that happed after rendering. If we add this field into the model (as it should be), the UI will reflect and update properly. I close this ticket as **won't fix**.
