### ISSUE TITLE
Wrong date format for AM / PM in DateField

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1555]
Open http://lh/bryntum-new/schedulerpro/examples/maps/
double click any task.
Note the leading 0 in the event start/end time fields.

<img width="231" alt="Screenshot 2020-09-22 at 16 23 14" src="https://user-images.githubusercontent.com/218570/93895316-fbcb2800-fcef-11ea-85ea-1b9c83ca455f.png">

**Comment by fabiojpoli** [comment]
Fix also for calendar:
![Screen Shot 2020-09-24 at 07 04 01](https://user-images.githubusercontent.com/663908/94137834-15c25300-fe35-11ea-89e4-21d100fb84d1.png)
