### ISSUE TITLE
Implement task splitting

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#1557]
Implement task splitting similar to what we have in Ext Gantt

Forum posts:
https://www.bryntum.com/forum/viewtopic.php?f=52&t=13676
https://www.bryntum.com/forum/viewtopic.php?f=52&t=15345

**Comment by c0dification** [comment]
Hi. Is there a timeline for porting this feature to Bryntum Gantt?

**Comment by matsbryntse** [comment]
Already supported!
