### ISSUE TITLE
scrollToNow() results in wrong timeline headers

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1564]
Confirmed. It is broken both in 3.1.9 and Scheduler Pro beta 2.

To reproduce:

<img width="1083" alt="Screen Shot 2020-09-23 at 16 46 56" src="https://user-images.githubusercontent.com/204844/94030665-6185e580-fdbe-11ea-98b6-82318d41f9bb.png">

---

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15361&p=77211#p77211)

We are using scroll to now function:  this.$refs.scheduler.schedulerInstance.scrollToNow({block: 'center'})
and we see the following.
![Untitled.png](https://www.bryntum.com/forum/download/file.php?id=11274)

our code for view Preset is:
```
 viewPreset : {
                base         : 'minuteAndHour'
            },

```
Expectation is the headers don't change.

We were able to reproduce similar issue (change of headers) in vuestic JS example by changing its viewPreset to above code and calling scroll to now in console.

Can you please let us know how to scroll to current time without changing the headers?

**Comment by matsbryntse** [comment]
progress pushed to 1564-scrollToNow
