### ISSUE TITLE
Tasks disappear after drag drop

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1565]
open basic calendar demo
drag team scrum to Monday
bunch of tasks disappear

**Comment by dongryphon** [comment]
I definitely saw this happen when reported, but I cannot reproduce it now. Maybe some bug in master that caused it has been fixed. There were no changes in the drag feature in the past couple weeks at least so the regression must have come from outside changes in the first place.

When I first tested it, after the events disappeared, I navigated between different weeks to force a dip back into the store to refresh the view. That did not cause the events to reappear, so there must have been some underlying data affected. Perhaps changes in the event stores / projects were the underlying cause.

**Comment by dongryphon** [comment]
@matsbryntse are you able to reproduce this with latest `master` branch?

**Comment by matsbryntse** [comment]
Can no longer repro, just add a test asserting the same amount of visible elements after the drop as before, something simple

**Comment by dongryphon** [comment]
https://github.com/bryntum/bryntum-suite/pull/2109/files
