### ISSUE TITLE
Time axis header too wide if workingTime is set at runtime

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1572]
If `workingTime` is set at runtime the time axis gets too wide showing the empty space. To reproduce use `examples-scheduler/drag-onto-tasks` demo with the following modification:
```
const workingTime = {
    fromHour : 8,
    toHour   : 19
}
const schedule = new Schedule({
    ref            : 'schedule',
    appendTo       : 'bodycontainer',
    startDate      : new Date(2017, 11, 1, 8),
    endDate        : new Date(2017, 11, 2, 18),
    equipmentStore : equipmentStore,
    crudManager    : {
        autoLoad   : true,
        eventStore : {
            modelClass : Task
        },
        transport : {
            load : {
                url : 'data/data.json'
            }
        }
    },
    // workingTime : workingTime
});

schedule.workingTime = workingTime;
```
The resulting screenshot (after horizontal scroll):
<img width="1088" alt="Screen Shot 2020-09-24 at 11 20 13" src="https://user-images.githubusercontent.com/204844/94126560-0c96ad80-fe58-11ea-9558-777093c008e0.png">

If `workingTime` is set as config option then it works correctly. (Maybe the setter needs a fix)

---

Reported on Forum (question 4): https://www.bryntum.com/forum/viewtopic.php?f=44&t=15303&start=10

**Comment by matsbryntse** [comment]
Not reproducible
