### ISSUE TITLE
Recurring events disappear after load

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1573]
Might be related to this issue: https://github.com/bryntum/support/issues/1570

To reproduce just open `exporttoics` demo in scheduler. Dragcreate event and see recurring events popping up
![bug(6)](https://user-images.githubusercontent.com/45400762/94152065-d5d68c80-fe83-11ea-804c-26cafa3e41ab.gif)

**Comment by matsbryntse** [comment]
not reproducible
