### ISSUE TITLE
SchedulerPro syncing without action on Ext JS

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1586]
[Forum topic](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15387)

If change the scheduler to autoSync: true, the request is sent to server without any action by user on launch of the application.

Steps to reproduce:
1 - Change the project to autoSync on SchedulerPro/examples/extjsmodern/App/view/Main.js:
```
...
project : {
    ...
    autoSync: true,
    transport : {
        ...
        sync: {
            url: './data/save.json',
        }
    },
   ...
```
2 - Load the app: http://lh/master/bryntum-suite/SchedulerPro/examples/extjsmodern/
3 - The POST request is send as soon the app is loaded:
![Screen Shot 2020-09-25 at 13 11 23](https://user-images.githubusercontent.com/663908/94296352-b3e71380-ff30-11ea-9d86-6bc2dd0bc679.png)

Please, also check on Scheduler project.

**Comment by isglass** [comment]
Might be related to https://github.com/bryntum/bryntum-suite/pull/1884

**Comment by fabiojpoli** [comment]
@isglass tested and working now.
