### ISSUE TITLE
Add getRowHeight to Angular wrapper

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1587]
[Forum Post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=15375)

Add possibility to define `getRowHeight` as scheduler config using Angular changing its wrapper.

Suggestion: https://www.bryntum.com/forum/viewtopic.php?p=77384#p77384

**Comment by pmiklashevich** [comment]
Just fix with no changelog and close the ticket. See "Adding properties which are not supported by default" https://www.bryntum.com/docs/scheduler/#guides/integration/angular.md
