### ISSUE TITLE
Collapsed groups disappear when using filterBar

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1596]
https://www.bryntum.com/forum/viewtopic.php?p=76628#p76628
https://www.bryntum.com/forum/viewtopic.php?p=77491#p77491
https://www.bryntum.com/forum/viewtopic.php?p=81637#p81637
https://www.bryntum.com/forum/viewtopic.php?f=51&t=16805&p=83595#p83595

In the following example,
https://www.bryntum.com/examples/grid/groupsummary/, add

```
filterBar: true
```

Do the following  steps:
1. Close some groups
2. Write something in search filed
3. Clear it from search filed by clicking backspace
Now the group which was closed disappears

Reproduced in master, release and on bryntum.com

**Comment by fabiojpoli** [comment]
Maybe related: https://github.com/bryntum/support/issues/1502

**Comment by pmiklashevich** [comment]
Pushed test to "1596-collapsed-group-lost"

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/371
