### ISSUE TITLE
Zoom In/Zoom Out works incorrect if tick size specified

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1601]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15412&p=77479)

Add the next config to the Scheduler example:

```
scheduler.viewPreset = {
    base: 'dayAndWeek',
    tickWidth: 16,

    headers: [
        {
            unit: 'week',
            dateFormat: 'MMM YYYY',
        },
        {
            unit: 'day',
            dateFormat: 'D',
        }
    ]
};
```

Call `scheduler.zoomIn()` and then `scheduler.zoomOut()`. 
The view will not back to the original state.

Try to comment `tickWidth: 16,` line and repeat. All works well.

Reproduced in master and release.

**Comment by ExtAnimal** [comment]
We need to ensure that the `PresetManager` (which is a `PresetStore`) sorts itself when you change anything like that.

It holds the presets in order of how wide it renders events. See the sorter definition in `PresetStore`.

`PresetStore` needs an `onModelChange` implementation which calls `this.sort()` before calling super to handle dynamic mutation of presets.

`PresetStore` also needs an `onDataChange` implementation which also calls `this.sort()` before calling super. This handles keeping newly added preset in order

**Comment by schTi** [comment]
Unfortunately I am also facing this issue, as I have a lot custom tick sizes defined for my presets.  I would appreciate, if you could tackle this in one of the next releases

**Comment by matsbryntse** [comment]
@schTi Could you please re-test in latest 6.0+ code, is everything for you?
