### ISSUE TITLE
Improve splitter behavior on touch devices with pointers

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1605]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=51&t=15439

On a touch device with pointer (eg windows 10 laptop with touch display), when hovering pointer over splitter arrows for collapse/expand do not appear. And arrows appear only on pointerdown

**Comment by zamber** [comment]
Hi, will this ever get back on the roadmap or is it fixed in another issue? This should also affect the mouse mode on iPads. We still have a ticket in our Jira for removing the workaround.

**Comment by bmblb** [comment]
There were some changes to splitter behavior few months ago, can you still see the problem in the latest release?

**Comment by JockeLindberg** [comment]
@zamber Have been investigating this issue and I cannot reproduce it on a Windows laptop with touch display using this example https://bryntum.com/examples/grid/multiregion/. Are you able to reproduce it in one of our online examples?

**Comment by bmblb** [comment]
Not reproducible
