### ISSUE TITLE
Calendar CSS issues.

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1609]
- [x] Original event should fade out a bit
- [x] Pointer should be hand
- [x] Should be on top

<img width="1024" alt="Screenshot 2020-10-06 at 09 13 36" src="https://user-images.githubusercontent.com/5415653/95170260-71d19380-07b4-11eb-8ce6-3f0ceb9a0960.png">

**Comment by ExtAnimal** [comment]
Also, height/width mismatch in MonthView's day number blob. It should be circular.

![Screenshot 2020-10-06 at 09 34 28](https://user-images.githubusercontent.com/200516/95172108-c245f280-07ae-11eb-938f-b28546135add.png)

**Comment by ExtAnimal** [comment]
Overflow popup behind events.

![Screenshot 2020-10-06 at 12 51 40](https://user-images.githubusercontent.com/200516/95192567-51accf00-07ca-11eb-8564-9f712526ac5c.png)

**Comment by ExtAnimal** [comment]
The issue of typing into the filter expanding the Sidebar... The field just needs configuring with `width : 0`

![Screenshot 2020-10-06 at 12 53 59](https://user-images.githubusercontent.com/200516/95192802-a05a6900-07ca-11eb-8c7e-5a31f71cdde6.png)

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/2283
