### ISSUE TITLE
Example landing page gets refreshed twice

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#1614]
It seems that examples landing page gets refreshed twice in Firefox.
Steps:

1. open any demo ..this for example: https://www.bryntum.com/examples/scheduler/animations/
2. click the demo title to jump back examples landing page

Result: the landing pages refreshes twice and the browser console shows that it was requested twice.

I had dark theme enabled.

**Comment by isglass** [comment]
I see the same/similar in Safari
