### ISSUE TITLE
Filtering by Name is broken in Grid filtering demo 

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#1623]
Chrome/FF/IE
https://www.bryntum.com/examples/grid/filterbar/
Can't filter by `Ja` or `Jan` or `Jane`  etc. word. 
Rows are empty.
![image](https://user-images.githubusercontent.com/57486330/95177162-b0307800-07df-11eb-899b-4cda049157ac.png)

**Comment by matsbryntse** [comment]
Working as designed
