### ISSUE TITLE
Calendar React Filtering demo styling

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1629]
Filter and find fields should have white text and icons.

<img width="1047" alt="Screen Shot 2020-10-06 at 11 02 10" src="https://user-images.githubusercontent.com/204844/95181498-ab5dcb00-07c3-11eb-9120-7c1a292ca93c.png">

**Comment by isglass** [comment]
looks like `b-bright` cls is missing from those fields

**Comment by jsakalos** [comment]
Resolved as a part of another issue. Filtering fields moved to toolbar, theme selector has white labels.
