### ISSUE TITLE
Should not be possible to set negative number for resources in big dataset demo

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1636]
https://www.bryntum.com/examples/scheduler-pro/bigdataset
Type in 0
Click arrow down trigger
<img width="684" alt="Снимок экрана 2020-10-06 в 14 57 31" src="https://user-images.githubusercontent.com/57486733/95198720-567e7c80-07e4-11eb-84d3-537f5e8f4966.png">

**Comment by isglass** [comment]
Just needs a min
