### ISSUE TITLE
Gantt throws an exception on invalid dependency loading

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#1640]
Gantt throws an exception on invalid dependency loading.

Steps to reproduce:
```js
            import Gantt from './lib/Gantt/view/Gantt.js';

            const gantt = new Gantt({
                appendTo: document.body,
                features: {
                    dependencies: true,
                },
                project : {
                    tasksData : [
                        {
                            'id': 1,
                            'startDate': '2019-09-18',
                            'endDate': '2019-09-22',
                            'expanded': true,
                            'children': [
                                {
                                    'id': 2,
                                    'startDate': '2019-09-18',
                                    'endDate': '2019-09-19'
                                }
                            ]
                        }
                    ],

                    dependenciesData : [
                        {
                            'id': 1,
                            'fromEvent': 1,
                            'toEvent': 2,
                        }
                    ]
                }
            });
```

**Comment by arcady-zherdev** [comment]
It was decided to make the following changes as a quick solution:

1. Add new way of cycle handling that will ignore them ..to be able to still load the data in the Engine graph. That mode will be used by default for data loading.
2. Cycle exceptions will use new message format. A message will consist of two parts. Its 1st part is more user friendly and less tech detailed. It will enumerate events that build the cycle (should give user a direction where to start looking for the root cause). And 2nd part will basically show the old message - list of involved engine identifiers (useful for more hardcore developers that adjust engine). For example:
```
Computation cycle:
events: 
#event2 => #event1 => #event2

identifiers: 
SchedulerProEventEx-event2.$.earlyStartDateConstraintIntervals
SchedulerProEventEx-event2.$.earlyEndDateRaw
SchedulerProEventEx-event1.$.earlyStartDateConstraintIntervals
SchedulerProEventEx-event1.$.earlyEndDateRaw
SchedulerProEventEx-event2.$.earlyStartDateConstraintIntervals
```

**Comment by Qwertie-** [comment]
> Add new way of cycle handling that will ignore them ..to be able to still load the data in the Engine graph. That mode will be used by default for data loading.

Is there a config option or something which can be set to restore the behavior? I was previously listening for the exception for my own solution which now can't detect the cycle event.
