### ISSUE TITLE
Number field not editable in big dataset demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1644]
http://lh/bryntum-new/gantt/examples/bigdataset/
click Custom button
Try to type into Tasks number field, not possible

NumberField should **NOT** block numbers typed into it. It should let you type any number you want, and use its validity to signal to user about its current state.

Big data set demo needs its own test as it is a very important demo

**Comment by dongryphon** [comment]
I'm doing the following and it appears to work:

![number-field-typing](https://user-images.githubusercontent.com/722969/95331968-5cba3a80-0870-11eb-80a0-e8b8f98439dd.gif)

Is there something else I should try?

**Comment by dongryphon** [comment]
I see now - typing is limited to 4 digits or so.
