### ISSUE TITLE
Error on project.setCalendar method call

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1646]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=15488)

Steps to replicate:
1 - Import `import { CalendarModel } from 'bryntum-gantt';` and change method `handleShowRollups` on Gantt/examples/vue/javascript/rollups/src/components/gantt/Gantt.vue to:
```
handleShowRollups({ checked }) {
    const calendar = new CalendarModel({
        id: 'calendar',
        name: 'calendar',
        hoursPerDay: 9,
        intervals: [
        {
            isWorking: false,
            recurrentEndDate: 'on Mon at 0:00',
            recurrentStartDate: 'on Sat at 0:00'
        },
        {
            'recurrentStartDate': 'every weekday at 17:00',
            'recurrentEndDate': 'every weekday at 8:00',
            'isWorking': false
        }
        ]
    })
    this.$refs.gantt.ganttEngine.project.setCalendar(calendar).then((response) => {
        console.log(response)
    })
    // this.$refs.gantt.ganttInstance.features.rollups.disabled = !checked;
}
```
2 - Uncheck rollup top/right checkbox
3 - console return error bellow:
![Screen Shot 2020-10-07 at 15 12 31](https://user-images.githubusercontent.com/663908/95376776-95c5cf80-08af-11eb-81eb-4e85e7faf0ce.png)

**Comment by arcady-zherdev** [comment]
The provided code snippet misses adding the new calendar to calendar manager store:
```js
// registering new calendar in the calendar manager
this.ganttEngine.project.calendarManagerStore.add(calendar);
```

**Comment by arcady-zherdev** [comment]
Actually we could add such records to calendar manager store automatically. Will implement this logic as part of this ticket.
