### ISSUE TITLE
Race condition in task editor

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1653]
To reproduce:
1. slow down tab by 6x (performance -> settings)
![image](https://user-images.githubusercontent.com/45400762/95584890-1408aa00-0a47-11eb-9ab7-f0e62ac6e5d1.png)
2. open gantt advanced demo
3. start editing any task
4. when editor is opened type ESC to close it and immediately dblclick on task to start editing again
5. you will see editor appears with values and shortly values are cleared and task editor becomes invalid and impossible to close/cancel
![task editor bug(1)](https://user-images.githubusercontent.com/45400762/95585573-0a337680-0a48-11eb-9fe6-c1ce5451a273.gif)

**Comment by isglass** [comment]
Should probably block editing again until first edit is fully cancelled

**Comment by fabiojpoli** [comment]
Unable to reproduce. @bmblb could you please test if this error still is happening? Thanks
