### ISSUE TITLE
TaskEditor demo does not remove warning icon after update 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1659]
Open http://lh/bryntum-new/schedulerpro/examples/taskeditor/
drag top left event bar to the right, causing overlap icon to appear in rows below
Drag task back to original position
Note the overlap icons still present, should not be

**Comment by isglass** [comment]
defaultRenderer uses DomSync, custom renderer does not. Since DomSync does not compare to DOM, it cannot know about this. Could probably be solved somehow but demo should use dom config instead to work properly. Replace html string with this and it is fixed:

```
return {
                        tag       : 'i',
                        className : 'b-fa b-fa-exclamation-triangle',
                        style     : 'color : red',
                        dataset   : {
                            btip : 'Overlap!'
                        }
                    };
```

Needs test coverage also
