### ISSUE TITLE
Icon padding missing before filter icon in dependency field in material theme 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1661]
<img width="311" alt="Screenshot 2020-10-11 at 13 49 03" src="https://user-images.githubusercontent.com/218570/95677851-c916a000-0bc8-11eb-9ee2-d6e103fbaef3.png">

**Comment by isglass** [comment]
Check if it is a generic problem affecting all fields with a start trigger

**Comment by matsbryntse** [comment]
All fields
<img width="228" alt="Screenshot 2020-10-11 at 21 55 41" src="https://user-images.githubusercontent.com/218570/95688728-8676b700-0c0c-11eb-8ca2-5d61adc16bcc.png">

**Comment by isglass** [comment]
The version of material we follow is supposed to not have padding, looks correct in demo browser. Should be fixed "in place" where needed
