### ISSUE TITLE
Changing rowHeight and barMargin breaks the layout

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1667]
http://lh/master/bryntum-suite/scheduler/examples/rowheight/
1. Drag Resource Margin to 20
2. Drag Bar Margin to 25
3. Drag Row Height to 20
See Bar Margin to set to 5 now (MAX value). That is configured in the demo.
But the lines are misaligned
<img width="1206" alt="Снимок экрана 2020-10-12 в 12 26 54" src="https://user-images.githubusercontent.com/57486733/95731393-26bdf180-0c88-11eb-96ec-5e3e1f601cd7.png">

Might be related: https://www.bryntum.com/forum/viewtopic.php?p=77944#p77944

**Comment by isglass** [comment]
A resourceMargin larger than half rowHeight leads to negative event height. I think we should:

* Prevent setting it to more than half rowHeight in the demo
* Prevent event heights < 1px in rendering
