### ISSUE TITLE
Partner splitter misalign on quick drag

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1673]
Open http://lh/bryntum-suite/Gantt/examples/gantt-schedulerpro/.

Drag top splitter quickly to the left:

<img width="1192" alt="Screenshot 2020-10-13 at 11 32 42" src="https://user-images.githubusercontent.com/5415653/95843300-d3ab7380-0d47-11eb-8ea3-59a261ef8358.png">

**Comment by matsbryntse** [comment]
Not reproducible
