### ISSUE TITLE
Implement React component for the Timeline widget

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1674]
Need to show this timeline http://lh/bryntum-suite/schedulerpro/examples/timeline/ in a react demo

Note, using BryntumWidget React component doesn't work for the Timeline. I propose to create a separate React component instead of embedding the timeline into the BryntumWidget wrapper.

**Comment by jsakalos** [comment]
What about other frameworks? I think we should have the wrapper for all of them.

**Comment by pmiklashevich** [comment]
>I think we should have the wrapper for all of them.
I have no objections

**Comment by isglass** [comment]
Part of wrapper generator task

**Comment by matsbryntse** [comment]
Handled in the wrapper generation ticket
