### ISSUE TITLE
Gantt + scheduler + calendar should all link to grid in their upgrade guide intros

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1677]
> Deprecation warning: You are using a deprecated API which will change in v5.0.0. TaskContextMenu feature is deprecated, in favor of TaskMenu feature. Please see https://bryntum.com/docs/gantt/#guides/upgrades/4.0.0.md for more information.

upgrade guide doesn't even have word menu in it anywhere.
ideally that warning should include the link to the guide itself, please open ticket for that

**Comment by isglass** [comment]
Found the info in older upgrade guide, it was supposed to be released earlier. Dont think it was, so moving
