### ISSUE TITLE
Broken Vue CDN demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#168]
Test coverage required

https://www.bryntum.com/examples/scheduler/vue/javascript/cdn/

https://www.bryntum.com/forum/viewtopic.php?f=44&t=13054

![image](https://user-images.githubusercontent.com/218570/71770963-1546fc80-2f34-11ea-9d20-43bfc1d828cb.png)

**Comment by jsakalos** [comment]
The demo works locally. It seems that `resources/app.css` and probably also other files are not copied to their expected locations. Please verify the server deployment process.

**Comment by jsakalos** [comment]
I have locally resolved the Vue CDN demo problem. I was a problem with axios that was also loaded from CDN, a weird message of XSS scripting error. It may be that their CDN server was attacked. I have removed the dependency on axios and the demo now uses fetch API. Works beautifully.

**Comment by jsakalos** [comment]
Finally I've decided for IE compatible fix and that was to change `axios` CDN url to always pull version `0.18.1`

**Comment by SergeyMaltsev** [comment]
Fixed online CDN demos.
Online issues were due to fail in release scripts. Fixed.
