### ISSUE TITLE
Loading big dataset to UMD application takes 4 times longer than to ES6 and MODULE applications

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1681]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=15164
https://www.bryntum.com/forum/viewtopic.php?f=52&t=15767

React/Angular does its own impact to the build because it also transpiles sources similar to UMD level

To reproduce:
Open BigDataset demo in SchedulerPro

Generate next dataset:
1 resource
4000 events
No dependencies

```
scheduler.widgetMap.dependenciesButton.hidden =
scheduler.widgetMap.resourceCountField.hidden =
scheduler.widgetMap.eventCountField.hidden = false;
scheduler.widgetMap.eventCountField.max = 4000;
scheduler.widgetMap.dependenciesButton.toggle();
//then
scheduler.widgetMap.resourceCountField.value = 1
//then
scheduler.widgetMap.eventCountField.value = 4000
```

http://lh/bryntum-suite/schedulerpro/examples/bigdataset/
=> data: 4734.62109375 ms

http://lh/bryntum-suite/schedulerpro/examples/bigdataset/index.module.html
=> data: 4538.0419921875 ms

http://lh/bryntum-suite/schedulerpro/examples/bigdataset/index.umd.html
=> data: 19992.302734375 ms

**Comment by chuckn0rris** [comment]
<img width="884" alt="Screenshot 2020-10-26 at 18 11 40" src="https://user-images.githubusercontent.com/7203098/97170945-c914c380-17b6-11eb-8191-9fe017bbede3.png">
<img width="884" alt="Screenshot 2020-10-26 at 18 10 24" src="https://user-images.githubusercontent.com/7203098/97170960-cdd97780-17b6-11eb-8b12-28cc86d6349c.png">

**Comment by chuckn0rris** [comment]
Test case may be found in this branch `1681-performance-data-set-react`

**Comment by jsakalos** [comment]
I have analyzed the problem and it seems that it has nothing to do with React. When the code is transpiled and/or minified its performance is degraded 10x. 

I have prepared two test cases; one uses our not-minified `schedulerpro.module.js` and another uses `schedulerpro.umd.js`. With these two cases we still have 2 ways of running them: development server with `npm start` and the production version with `npm run build`. The summary is:

Build | Time | Note
-- | -- | --
Module `npm start` | ~2800ms | Uses not-minified sources.
Module `npm run build` | ~21000ms | Uses React-minified sources.
UMD `npm start` | ~20000ms | Uses Bryntum-transpiled UMD
UMD `npm run build` | ~20000ms | Uses Bryntum-transpiled and React-minified UMD

Only not-minified and not-transpiled sources give the expected performance but when they are transpiled and/or minified, by our build process or by React, the performance is degraded.

Here is the screenshot of Chrome performance analysis:
<img width="1179" alt="Screen Shot 2020-10-28 at 09 34 03" src="https://user-images.githubusercontent.com/204844/97412362-c377c480-1901-11eb-9915-53fc85190248.png">

The apparent culprit is `addIdentifier` method (Chronograph).

**Comment by jsakalos** [comment]
The showcase is attached. To use it:

1. unzip to `examples/frameworks/react/javascript` directory. This will create two subdirectories `resource-histogram-umd` and `resource-histogram-module`
2. there's `npm` subdirectory in both directories. Run:
```
cd resource-histogram-umd/npm/react/schedulerpro
npm i npm
npm run build
cd ../../../../resource-histogram-module/npm/react/schedulerpro
npm i
npm run build
```
This builds the wrappers.

3. Run
```
npm i
npm run build # production
npm start # development server
```
in any of the new directories.

Note: The best for debugging is development server in `resource-histogram-umd` because it shows the issue but it doesn't mangle the names. The above screenshot is taken from there.

[showcase.zip](https://github.com/bryntum/support/files/5450629/showcase.zip)

**Comment by jsakalos** [comment]
Attempts to change the `browserlist` configuration for React scripts in `package.json` did not help. Even the following configuration had no effect:
```
  "browserslist": {
    "production": [
      "last 1 chrome version"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }

```

**Comment by canonic-epicure** [comment]
We checked with Saki and found that generators are transpiled in the build JS output. This explains performance drop down, as transpiled generators performs much worse than native. Since generators are supported in all modern browsers, except the IE, there's no need to transpile them for modern builds. Generators transpilation also increases the bundle size significantly.

The strange thing is that generators are transpiled even for "last 1 chrome version" case as mentioned in the previous comment. This seems to be a bug in the react tools.

**Comment by chuckn0rris** [comment]
Same has been found for Angular app. I reproduced speed up if I used `module.js` import instead of 'umd' as @jsakalos  mentioned. 
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15755&p=78789)

**Comment by chuckn0rris** [comment]
ES6 generators may be used with all browsers except IE11 
https://caniuse.com/es6-generators
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator

We have a module.js bundle with not transpiled generators and `babeljs` may be reconfigured to avoid generators transpilation for prod build of a framework:
```
{
   "presets": [[ "env", { "exclude": ["transform-regenerator"] } ]]
}
```
This is a way to fix this problem for the environment which is not support IE11. 
Should be discussed with @SergeyMaltsev

**Comment by SergeyMaltsev** [comment]
Proposed solution.

Tweak react-sripts to not transpile generators. 

- run `npm i`
- copy `node_modules/babel-preset-react-app` to `babel-preset-react-app-bry` at the same level as the project
- edit file `../babel-preset-react-app-bry/dependencies.js` to comment all plugins at the end of file:
```
    plugins: [
      // Disabled as it's handled automatically by preset-env, and `selectiveLoose` isn't
      // yet merged into babel: https://github.com/babel/babel/pull/9486
      // Related: https://github.com/facebook/create-react-app/pull/8215
      // [
      //   require('@babel/plugin-transform-destructuring').default,
      //   {
      //     // Use loose mode for performance:
      //     // https://github.com/facebook/create-react-app/issues/5602
      //     loose: false,
      //     selectiveLoose: [
      //       'useState',
      //       'useEffect',
      //       'useContext',
      //       'useReducer',
      //       'useCallback',
      //       'useMemo',
      //       'useRef',
      //       'useImperativeHandle',
      //       'useLayoutEffect',
      //       'useDebugValue',
      //     ],
      //   },
      // ],
      // Polyfills the runtime needed for async/await, generators, and friends
      // https://babeljs.io/docs/en/babel-plugin-transform-runtime
      // [
      //   require('@babel/plugin-transform-runtime').default,
      //   {
      //     corejs: false,
      //     helpers: areHelpersEnabled,
      //     // By default, babel assumes babel/runtime version 7.0.0-beta.0,
      //     // explicitly resolving to match the provided helper functions.
      //     // https://github.com/babel/babel/issues/10261
      //     version: require('@babel/runtime/package.json').version,
      //     regenerator: true,
      //     // https://babeljs.io/docs/en/babel-plugin-transform-runtime#useesmodules
      //     // We should turn this on once the lowest version of Node LTS
      //     // supports ES Modules.
      //     useESModules: isEnvDevelopment || isEnvProduction,
      //     // Undocumented option that lets us encapsulate our runtime, ensuring
      //     // the correct version is used
      //     // https://github.com/babel/babel/blob/090c364a90fe73d36a30707fc612ce037bdbbb24/packages/babel-plugin-transform-runtime/src/index.js#L35-L42
      //     absoluteRuntime: absoluteRuntimePath,
      //   },
      // ],
    ].filter(Boolean),

```
- add `"babel-preset-react-app": "file:../babel-preset-react-app-bry"` to `package.json`, `devDependencies` section.
or install it with this command from app's root
```
npm i --save-dev ../babel-preset-react-app-bry
```


- change `browserlist` in `package.json` to show:
```
  "browserslist": {
    "production": [
      "last 1 chrome version"
    ],

```
- remove `node_modules` and `package-lock.json` and run
```
npm i
npm run build
```
