### ISSUE TITLE
Task Editor always resets time part of start/end dates

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#1685]
It seems impossible to control start/end dates time info. Even if we provide a time-including `format` the time portion is anyway got reset to the earliest time allowed by the project calendar.
Problems here are:

1. why the project calendar? a task might use its own calendar + resource ones.
2. if user switches to a format showing time it's expected to enter time part so we need to respect user input.

`DateField` has `keepTime` config which sounds close to the subject yet it still doesn't support keeping user entered value.
And that config is ignored by `StartDateField`, `EndDateField` classes.

Mentioned here: https://www.bryntum.com/forum/viewtopic.php?p=81394#p81394

**Comment by pmiklashevich** [comment]
DateTimeField:
```
    features : {
        taskEdit : {
            items : {
                generalTab : {
                    items : {
                        startDate : {
                            type : 'datetimefield',
                            flex : '1 0 100%',
                            cls  : ''
                        },
                        endDate : {
                            type : 'datetimefield',
                            flex : '1 0 100%',
                            cls  : ''
                        },
```
<img width="609" alt="Снимок экрана 2021-01-11 в 15 21 14" src="https://user-images.githubusercontent.com/57486733/104181925-aa6eb200-5420-11eb-9d78-06e4167a279c.png">
