### ISSUE TITLE
Event elements assigned to different resources interfere to drag them when allowOverlap is false

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1699]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=15605

http://lh/bryntum-suite/schedulerpro/examples/percent-done/
```
const scheduler = new SchedulerPro({
    allowOverlap : false,
```
Drag "Batch 2" event assigned to Mike few hours ahead. See the drag is reverted.
Works in Multi Assignment demo in simple Scheduler

**Comment by matsbryntse** [comment]
Not reproducible
