### ISSUE TITLE
New vertical mode: Resources grouped by date range on X axis, Hours on Y axis

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1704]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15618&p=78198)

![image](https://user-images.githubusercontent.com/218570/96411929-92084600-11e9-11eb-9a8d-cd0f4fb0d245.png)

**Comment by ExtAnimal** [comment]
This can use a similar approach as suggested for https://github.com/bryntum/bryntum-suite/issues/2140.

A cache of configurable `Scheduler`s (these look like they are configured to be vertical), each one configured to encapsulate a different day.

They are arranged in a `flex-flow : row nowrap` container.

Obviously, instantiating dozens of child `Scheduler`s would be a perf hit, so the range of dates would have to be kept limited.

**Comment by matsbryntse** [comment]
Supported in Calendar: https://bryntum.com/products/calendar/examples/date-resource/
