### ISSUE TITLE
Repurpose `store.data` to return something meaningful

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1714]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=15634&p=78256)

See comment below by @isglass on what it should actually do.

- [x] #5499
- [x] Change it to return current state as raw objects in 6.0.0

**Comment by chuckn0rris** [comment]
Still reproducible https://www.bryntum.com/forum/viewtopic.php?p=112630#p112630

**Comment by dvakatsiienko** [comment]
Confirming, still happens for very basic `EventStore` with about ~16 events of data.
It needs to be fixed since `EventStore.data` access is a very basic and much required operation of data access.

**Comment by isglass** [comment]
`store.data` returns the original array of data object that the store was loaded with. There was a path where it was not previously set, which should be fixed already IIRC (not released)

But, the actual original array of data objects is not updated by the store on record manipulation, so its existence is questionable and very likely not what you want to use anyway.

You should probably be using `store.toJSON()` or `store.records.map(r => r.xxx)`, where xxx could be for example `data` or `modificationData`. 

I will change this ticket to be about repurposing what `get store.data` means, but that will be a breaking change so can't happen before 6.0.

**Comment by ExtAnimal** [comment]
The raw data element of the incoming data array is used as the `data` property of the record.

<img width="524" alt="Screenshot 2022-10-30 at 16 59 12" src="https://user-images.githubusercontent.com/200516/198888608-7651c3bb-de9d-42ba-a812-b024f322dacd.png">

So the raw data block should work to mutate and feed back through if you are using `syncDataOnLoad`

**Comment by dvakatsiienko** [comment]
When `Bryntum v6` is planned to be released?

**Comment by matsbryntse** [comment]
Early 2024! (Sorry for the late reply)
