### ISSUE TITLE
After calling zoomToFit, horizontal scroll is wrongly positioned

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1715]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=15635&p=78257)

When using gantt.zoomToFit(), scheduler displays correct tasks, but horizontal scroll is at wrong position:
![Screenshot 2020-10-19 at 22.35.51.png](https://www.bryntum.com/forum/download/file.php?id=11501)
it should be:
![Screenshot 2020-10-19 at 22.35.59.png](https://www.bryntum.com/forum/download/file.php?id=11502)
To test visit https://www.bryntum.com/examples/gantt/basic/ and type in the console:
```
gantt.zoomToFit()
```
and then try to move the scroll with cursor.

**Comment by fabiojpoli** [comment]
@chuckn0rris , looks like it is working now, please test and close if fixed. Thanks
