### ISSUE TITLE
No scrollbar if all data filtered

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1719]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=15641&p=78276)

**Steps to reproduce:**
1. open https://www.bryntum.com/examples/grid/groupedheaders/
2. enable `filterBar` feature
3. expand columns to see horizontal scrollbar
4. type in filter to remove all data from the grid, ("AAAAAAAA" as example)

**Current result:**
Horizontal scrollbar is disappeared and header is not scrollable if your cursor in not over it but over the grid body.
**Expected result:**
Should be possible to scroll and scrollbar should be there.

**Comment by fabiojpoli** [comment]
The problem happens only when one column is locked AND another column has children (grouped header).
