### ISSUE TITLE
Successor incorrectly updated after changing task end date

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#173]
http://lh/bryntum-suite/gantt/examples/localization/

https://www.bryntum.com/forum/viewtopic.php?f=52&t=13029

1/ Go to: https://www.bryntum.com/examples/gantt/localization/
2/ Increment "Finish" date of task "Run tests" using cell editing

Using resize works fine.

![image](https://user-images.githubusercontent.com/218570/71803248-8d124580-3060-11ea-8118-956e39cbb451.png)

Also test adding a dependency between two new tasks:
```

const project = window.project = new ProjectModel({
    startDate : '2019-10-10',
    tasksData : [
        { id : 1, name : 'Task 1', startDate : '2019-10-12', endDate : '2019-10-13' },
        { id : 2, name : 'Task 2', startDate : '2019-10-12', endDate : '2019-10-13' },
        { id : 3, name : 'Task 3', startDate : '2019-10-12', duration : 1 },
        { id : 4, name : 'Task 4', startDate : '2019-10-12', duration : 1 }
    ]
});

const gantt = new Gantt({
    appendTo : 'container',

    project : project,

    startDate : '2019-10-10',
    endDate   : '2019-10-14',

    columns : [
        { type : 'name', field : 'name', width : 150 },
        { type : 'date', text : 'Start',  field : 'startDate', width : 100, format : 'YYYY-MM-DD' },
        { type : 'date', text : 'End',  field : 'endDateDate', width : 100, format : 'YYYY-MM-DD' },
        { type : 'duration', field : 'duration', width : 100 },
        { type : 'constrainttype', width : 100 }
    ]
});
```

https://app.assembla.com/spaces/cHlz5-LZyr4kUleJe5cbCb/tickets/9358/details

**Comment by pmiklashevich** [comment]
That's a bug in Scheduling Engine. Pushed test to `173-scheduling-successors` branch and reassigned to @SamuraiJack

**Comment by SamuraiJack** [comment]
Fixed now, @pmiklashevich please verify and handle it from this point.
