### ISSUE TITLE
Drag proxy is not visible when drag creating new task

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1733]
Reproducible here: https://www.bryntum.com/examples/gantt/advanced/
1. add empty task 
```
gantt.taskStore.rootNode.appendChild({ name : 'foo' })
```
2. try to dragcreate the bar - tooltip is misplaced as well as drag proxy

**Comment by matsbryntse** [comment]
https://github.com/bryntum/support/issues/164 Dupe
