### ISSUE TITLE
Rounded eventStyle forces color

### ISSUE THREAD

**Issue by romainhk** [bryntum/support#1739]
The title of rounded events introduced on 4.0, have a forced color to green.

The problem come from `.b-sch-event-wrap.b-sch-style-rounded .b-sch-event:not(.b-milestone)` that force the use of the color `#2c9f31` instead of using inherited one (in scheduler.material.css file).

**Comment by matsbryntse** [comment]
Please provide a test case, can you see this online somewhere?

**Comment by romainhk** [comment]
Sure ! Using "getting start" example, I just added `eventStyle: 'rounded',` in `app.js`.
Before: event labels are white ; after, labels became green or orange (and are not quite readable anymore on blue events :).

![image](https://user-images.githubusercontent.com/295389/97415309-536b3d80-1905-11eb-8cdb-7af1e6942f7a.png)

[green_color_bug.zip](https://github.com/bryntum/support/files/5450745/green_color_bug.zip)

**Comment by matsbryntse** [comment]
Confirmed, thanks!

**Comment by matsbryntse** [comment]
Our 'rounded' style is a predefined style which includes background color and text color settings. Much easier for you to use our plain / none style and apply the color / rounding you want
