### ISSUE TITLE
Modifying assigned resources of Recurring events does not update UI

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1741]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15676&p=78440)

https://www.bryntum.com/forum/viewtopic.php?f=54&t=16150&p=80425

Hello, there is a bug when adding multiple resources to existing recurring events. 

Steps to reproduce: 

in the recurring events example: https://www.bryntum.com/examples/examples-scheduler/recurrence/

double click the event for Jong on 2/10/2018 to open the event editor 
in the Resource drop down, add Lee to the event
select "All future events" in the dialog box 

At this point, nothing happens, but I would expect Lee to be added as a resource to all of these recurring events from Feb 10 onward. Can you please take a look?

Thanks a lot.

**Comment by ExtAnimal** [comment]
Very strange that it's only for assignment.

If you edit any other property, like change the name, and click "All future events", it correctly creates a new start on that date with the new property. So updating the assignments seems like it takes place too early *before* the confirmation dialog.

Changing the name for all future events works: ![Screenshot 2020-12-10 at 14 05 59](https://user-images.githubusercontent.com/200516/101776183-75e99c80-3ae8-11eb-8cac-fb4a808694fa.png)

**Comment by ExtAnimal** [comment]
There is still a bug. The change to resource assigned is applied to the *original* base recurring event when you choose "All future occurrences".

And the new recurring base (which is the base for all the future occurrences) still has the hold resource.

It's the opposite way round than it should be.
