### ISSUE TITLE
Group renderer for timeaxis column duplicates content on group collapse

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1751]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15691&p=78508)

Trying to render text on the group header row on the time axis column seems to be glitchy after you collapse and expand a group. See picture below.
![bug.png](https://www.bryntum.com/forum/download/file.php?id=11552)
Here I collapsed Amsterdam and expanded it again afterwards. Notice the "Test123" is still  floating where Nijmegen used to be.

Code:
```
const scheduler = new bryntum.scheduler.Scheduler({
    appendTo: 'scheduler',
    columns: [ 
        { 
            text: 'Name', 
            field: 'name'
        },
        { 
            text: 'Location', 
            field: 'location',
        },
    ],
    resources: [
        {
            id: 1,
            name: 'Test1',
            location: 'Nijmegen'
        },
        {
            id: 2,
            name: 'Test2',
            location: 'Nijmegen'
        },
        {
            id: 3,
            name: 'Test3',
            location: 'Nijmegen'
        },
        {
            id: 4,
            name: 'Test4',
            location: 'Amsterdam'
        },
        {
            id: 5,
            name: 'Test5',
            location: 'Amsterdam'
        }
    ],
    features : {
        group : {
            field : 'location',
            renderer : ({ isFirstColumn, column, count, groupRowFor, record }) => {
                if(isFirstColumn) {
                    return `${groupRowFor} (${count})`;
                }
                else if (column instanceof bryntum.scheduler.TimeAxisColumn) {
                    return 'Test123'
                }
                else {
                    return '';
                }
            }
        },
    }
});

```

**Comment by egorkel-altexsoft** [comment]
I faced the same issue. You can reproduce it on your example https://www.bryntum.com/products/scheduler/examples/grouping
1) Hide the resource panel using splitter
2) Collapse and expand the top group
3) You will see the phantom header of the bottom group
![image](https://user-images.githubusercontent.com/95917278/218151565-d437fece-a037-4d83-b998-701c538fccf5.png)

Also, when the resource panel is hidden vertical alignment of the group headers is broken.

Could you please fix it or suggest a workaround for now?
