### ISSUE TITLE
Grouping breaks after collapsing / expanding group

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1757]
Needs 2 groups to exist to be reproducible
Go to forum prio list
collapse top group
expand it 

<img width="480" alt="Screenshot 2020-10-27 at 20 10 46" src="https://user-images.githubusercontent.com/218570/97350032-845d5b00-1890-11eb-99e0-af6c1d585b24.png">

**Comment by bmblb** [comment]
Duplicate of this issue: https://github.com/bryntum/support/issues/2135
Closing
