### ISSUE TITLE
Excel exporter demo doesn't really customize exported columns

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1763]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=15712&p=78617

To reproduce try to change columns configuration in `exporttoexcel` demo in scheduler.
What works is this:
```
scheduler.features.excelExporter.export({
    filename       : 'Bar',
    exporterConfig : {
        columns      : [{ text : 'Foo', field : 'name' }],
        eventColumns : [
            { text : 'Task', field : 'name', width : 200 }
        ]
    }
});
```

Need to update all Excel exporter demos. Docs do show correct config options.

**Comment by fabiojpoli** [comment]
@isglass , is not good we also move this class out of experimental folder?

**Comment by fabiojpoli** [comment]
There are 2 more problems:
- only if resourceColumns is defined, group header shown on excel
- columns width config doesn't work on excel
