### ISSUE TITLE
Revise the frameworks wrappers documentation to include all configs and features

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1769]
There is the missing `taskEditFeature` in Vue integration demo, but all products and all frameworks would deserve the revision. Ideally, we would have a template and the config/feature list would be automatically generated from sources.

Requested here: [Forum post](https://www.bryntum.com/forum/viewtopic.php?p=78665#p78665)

**Comment by matsbryntse** [comment]
Will be fixed in https://github.com/bryntum/support/issues/1808
