### ISSUE TITLE
Filter popup closes when field trigger is clicked

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1774]
To reproduce on advanced demo:
1. click filter icon on percend done column
2. click trigger in any field
3. popup closes
![filterpopup](https://user-images.githubusercontent.com/45400762/97729080-5cb20100-1ae3-11eb-8a4f-79e18a515b45.gif)

**Comment by fabiojpoli** [comment]
Was identified the problem with number field, flag changeOnSpin and created separated issue for it: https://github.com/bryntum/support/issues/1811

For the current issue, was discussed with @isglass and @ExtAnimal  a better UX for the number filter, when close the popup and when keep it open. Was decided to close the popup only when click out of the popup fields. Meaning, if user click on spins, press enter, or press to clean value on field ("x" icon) the popup must remain open.

**Comment by bmblb** [comment]
@fabiojpoli @ExtAnimal I doubt Enter press should keep filter popup open. how would you close popup with keyboard then? Esc will clear the value.

**Comment by isglass** [comment]
After trying I agree with max, should close on enter
