### ISSUE TITLE
WBS number should be a real field and not depend on store sort, filter, etc

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1788]
Steps to reproduce on [advanced demo](https://www.bryntum.com/examples/gantt/advanced/):

1. Apply filter `run` to name column, see WBS is different for tasks, it should remain intact
![image](https://user-images.githubusercontent.com/45400762/97900668-0a274d80-1d4c-11eb-99b8-c002e128d840.png)
![image](https://user-images.githubusercontent.com/45400762/97900728-24f9c200-1d4c-11eb-84ae-e42d456c48f5.png)

**Comment by ExtAnimal** [comment]
Well, it should depend on the real, underlying structure of the tree, not what gets setup by the flowing in and out of the store by filtering.

So `Model.getIndexPath` should be

```
    get indexPath() {
        const indices = [];

        for (let task = this; task && !task.isRoot; task = task.parent) {
            const { parent } = task;

            // Find our index in the original, unfiltered children list
            indices.unshift(parent ? (parent.unfilteredChildren || parent.children).indexOf(task) + 1 : 1);
        }

        return indices;
    }
```

**Comment by ExtAnimal** [comment]
And `StoreSort.performSort` should work similar to filtering.

There should be a `visibleChildren` property getter. Normally it will return the `children` property.

But when sorted, it returns the sorted children. And when filtered, it returns the filtered children. When filtered and sorted, likewise, it returns the children that the UI is going to get.

`children` should never be modified. It's the underlying data structure. So it will always be valid to find the index of a child in the original data structure using `getIndexPath` as above.

**Comment by bmblb** [comment]
WBS code is not updated automatically on task changes position in tree (or gets removed). Because it is unclear how it is expected to behave on sorted/filtered dataset.
Just like in MS Project. Note 1.1.2 is removed and 1.1.5 is a child of 1.2
![image](https://user-images.githubusercontent.com/45400762/99229350-f2959d80-27fe-11eb-9c23-fcdaaab12b9b.png)
