### ISSUE TITLE
Exception on a scheduling conflict

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#1802]
Reported  here: https://www.bryntum.com/forum/viewtopic.php?f=52&t=15762&p=78824

Steps to reproduce:

1. open advanced demo
2. ```js
    gantt.taskStore.removeAll()
    gantt.project.commitAsync().then(() => {
        const [t1, t2] = gantt.taskStore.add([{ id : 1, duration : 1 }, { id : 2, duration : 1, constraintType : 'muststarton', constraintDate : gantt.project.startDate }])
        gantt.dependencyStore.add({ from : t1, to : t2 })
    })
    ```

**Comment by arcady-zherdev** [comment]
The original issue seems resolved by now the conflict popup shows up.
But if one clicks `Cancel` button in the popup there is another exception `Uncaught (in promise) Error: Unknown identifier TaskEx-1.$.assigned`.

**Comment by canonic-epicure** [comment]
PR: https://github.com/bryntum/bryntum-suite/pull/5985
