### ISSUE TITLE
Scroll paging (load while scrolling)

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1804]
Load more resources as you scroll down in the grid 
https://www.bryntum.com/forum/viewtopic.php?f=51&t=14647&p=74578&hilit=infinite#p74578
https://www.bryntum.com/forum/viewtopic.php?f=52&t=17744&p=87859#p87859
https://www.bryntum.com/forum/viewtopic.php?f=51&t=18916&p=93534#p93534
https://www.bryntum.com/forum/viewtopic.php?f=51&t=19030&p=94085#p94085
https://forum.bryntum.com/viewtopic.php?p=130624#p130624

**Comment by dongryphon** [comment]
What about Gantt and Scheduler?

**Comment by chuckn0rris** [comment]
One more request for the Scheduler: [Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=16575&p=82471#p82471)

**Comment by marciogurka** [comment]
[+1](https://www.bryntum.com/forum/viewtopic.php?p=112616#p112616) for this one

**Comment by ExtAnimal** [comment]
Work on loading an AjaxStore on demand was begun here: https://github.com/bryntum/bryntum-suite/pull/4423

For Schedulers it's not the same. The Grid store is the resources, that will work as you scroll down.

But with the event store, that will be another part altogether. It will have to make specially formatted server requests to load events for a visible range of resources by collecting all the IDs of the visible rows and requesting to get all the events for those resources.

**Comment by OrlandoMR** [comment]
Any update?

**Comment by AjaxSolutions** [comment]
It is Q4.  Any update? Thx.

**Comment by JockeLindberg** [comment]
Grid support is finished, but not released. Currently finishing Scheduler support. The plan is for this to be released in 6.0. But depending on when that is, we might release Grid support earlier.

**Comment by JockeLindberg** [comment]
Moved https://www.bryntum.com/forum/viewtopic.php?f=51&t=20194&p=101659#p101659 into https://github.com/bryntum/support/issues/8001
