### ISSUE TITLE
Generate wrappers in an automated way

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1808]
- [x] Vue
- [x] Angular
- [x] React
- [x] Each wrapper should have documentation which include all configs and features (currently manually listed in https://bryntum.com/docs/scheduler/#guides/integration/react.md). Guide should refer to the new ReactWrapper 
- [x] Each framework should have a top level folder in the docs tree holding its docs. Use framework icon on them
- [x] `features` can't be a part of Config. We have `*Feature` names for this

**Comment by chuckn0rris** [comment]
Please check if it works and close https://github.com/bryntum/support/issues/2391 after merge
