### ISSUE TITLE
Events multi drag&drop via schedulers works incorrect

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1821]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=15789&p=78944)

Open https://www.bryntum.com/examples/scheduler/drag-between-schedulers/
Select few events from different resources and drop them in the same scheduler. They will be splitted by resources accordingly. All works correct.
Try the same but drop them on another scheduler. They will be attached to the same resource and all `startDate`s will be set to the same value. 

Should be handled same as on drop inside a scheduler.

**Comment by isglass** [comment]
That is by design, we cannot assume that resources in the target scheduler are in the same order as in the source scheduler and so on. So not a bug, but could be a feature request to have the behaviour configurable

**Comment by isglass** [comment]
After discussing with @matsbryntse, decided we want to support both behaviours, keeping their "order" by default. Lets introduce a config for cross scheduler dragging, perhaps:

`unifiedCrossSchedulerDrag : true/fale`

That matches the `unifiedDrag` config, but would only be applied when dragging to another scheduler

**Comment by isglass** [comment]
Lets make it respect `unifiedDrag` config in all scenarios
