### ISSUE TITLE
Create React 17 demos

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1823]
Use Create new React 17.x and react-scripts 4.x in all products.

Requested here:
https://www.bryntum.com/forum/viewtopic.php?p=78915#p78915
https://www.bryntum.com/forum/viewtopic.php?p=79890#p79890

Note, updating Calendar/examples/frameworks/react/javascript/filtering to react 17 has an issue
```
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1"
  },
```
npm i && npm run start
```
Failed to compile.

./src/App.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/App.scss)
Module not found: You attempted to import ../../../../../../build/calendar.material.css which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
```

As a workaround go to Calendar/build and run `npm pack .`. This will create Calendar/build/bryntum-calendar-4.0.3.tgz.
Update package.json to use it
```
  "dependencies": {
    "bryntum-calendar": "file:../../../../../build/bryntum-calendar-4.0.3.tgz",
```
This will create a copy of the package instead of a symlink.
The same is true for demo scss. Just comment it out meanwhile.
Calendar/examples/frameworks/react/javascript/filtering/src/App.scss
```
@import "~bryntum-calendar/calendar.material.css";
//@import "~@bryntum/demo-resources/scss/example.scss";
```

**Comment by pmiklashevich** [comment]
What's new in react17: https://ru.reactjs.org/blog/2020/08/10/react-v17-rc.html

**Comment by isglass** [comment]
@pmiklashevich @jsakalos I dont think we need to update all demos, good to keep demos on older versions too since not all clients will be switching to React 17. Assigning Saki, the two of you can discuss approach and let me know what is decided

**Comment by pmiklashevich** [comment]
@isglass We can create subfolders with react16 and react17. At the end React devs insist on upgrading to v17. As far as I got it from the article at least.

**Comment by bmblb** [comment]
@pmiklashevich is this the same problem here: https://github.com/bryntum/support/issues/1314#issuecomment-672569186 ?

**Comment by jsakalos** [comment]
> @pmiklashevich @jsakalos I dont think we need to update all demos, good to keep demos on older versions too since not all clients will be switching to React 17. Assigning Saki, the two of you can discuss approach and let me know what is decided

I also think that we only need new demos, not to update all. I prefer to create new demos after 4.1.0 when we switch to NPM.

**Comment by pmiklashevich** [comment]
Agree that having new demos is better. Updated the title and description.

**Comment by pmiklashevich** [comment]
> @pmiklashevich is this the same problem here: [#1314 (comment)](https://github.com/bryntum/support/issues/1314#issuecomment-672569186) ?

No, I don't think so. The symptoms are similar, but the root cause if this one is that React17 does not allow scss imports from the outside of the src folder using relative path.
