### ISSUE TITLE
Make individual records not editable

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1828]
https://www.bryntum.com/forum/viewtopic.php?f=1&t=15814&p=78996

For now to make one record read-only, need to prevent all features like cellEdit, drag, resize etc manually. Need to add a readOnly field to GridRowModel, convert GridRowModel into a mixin, mix up to ResourceModel and TaskModel (for now TaskModel does not extend GridRowModel). All feature should respect the readOnly value and prevent editing automatically.

**Comment by matsbryntse** [comment]
Dupe: https://github.com/bryntum/support/issues/665
