### ISSUE TITLE
Store behavior when last sorter is removed

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1833]
Assume this workflow:
1. grid is loaded, records are shown in some order which is not defined by any field
2. grid is sorted by field (order changes)
3. sorter is removed from the store (order doesn't change)

Arguably when last sorter is removed, grid should return to oiginal order on step 1. From the data level perspective, we could use index field (or analog) storing initial order of records. We don't need this order to be declared by special field, we would imply there's an order in the incoming data set.
This behavior could be switched by a config option.

I recall Ext grid behaves the same way as our grid, but some people (including me) would expect initial order to be restored.

**Comment by bmblb** [comment]
@isglass @matsbryntse @ExtAnimal @dongryphon thoughts?

**Comment by ghulamghousdev** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=140994#p140994) for this.

**Comment by matsbryntse** [comment]
Easy enough for the user to implement using our APIs by adding a sorter defining how the initial data was sorted.
