### ISSUE TITLE
Combo's picker loses anchoring after typing

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1836]
<img width="265" alt="Screenshot 2020-11-08 at 16 45 29" src="https://user-images.githubusercontent.com/218570/98469767-daf85c80-21e1-11eb-8352-50644aa9d22b.png">

http://lh/components-release/grid/docs/#Core/widget/Combo
Type into a combo box with no space available under it, forcing picker to go above combo filed

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/2412
