### ISSUE TITLE
Check dispatcher consistency

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#1839]
Reported here: https://bryntum.com/forum/viewtopic.php?f=52&t=15818

Steps:

1. unpack json file from [launch-saas.zip](https://github.com/bryntum/support/files/5509524/launch-saas.zip) to the Gantt/examples/_datasets
2. open advanced demo
3. open task editor for `Setup web server` click `Cancel`

Result: the task duration got recalculated

**Comment by crossleyjuan** [comment]
Not only it gets recalculated, but wrongly calculated, when loading the project the summaries gets calculated based on the children, which is ok, but when pressing the cancel (even if it's triggering the recalc) the logic uses the calculateEndDate which will compute the end date not using the children, which leads to a wrong calculation.

**Comment by arcady-zherdev** [comment]
The issue is no longer reproducible in Gantt v6.0.2. Looks like it's fixed while working on some other ticket.
