### ISSUE TITLE
Change renderer column keeping default renderer

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1844]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=15816)

Using for instance the duration column, is not possible create an additional renderer (like change style based on value) but keeping the duration format.

Steps to reproduce:
- Edit this demo: https://www.bryntum.com/examples/gantt/aggregation-column/
- Change the duration column adding this renderer different renderer to change the style:
```
renderer: ({ cellElement, record, value }) => {
    if (value.magnitude=== 2) {
        cellElement.style.color = 'blue';
        cellElement.style.fontWeight= 'bold';
    }
    
    return value.magnitude;
}
```

It return the value but doen't keep the format (like "2 days").

**Comment by matsbryntse** [comment]
Use See https://bryntum.com/products/grid/docs/api/Grid/column/Column#config-afterRenderCell
