### ISSUE TITLE
Create a Calendar demo with multi-assigned events

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1851]
The filtering by calendar (team, room, resource) should honor multi-assignment

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=15848&p=79142#p79142)

Hello, 

is assigning multiple resources to the same event supported in Calendar (like it is in Scheduler)? When I try to implement it, an event is only rendered for the "first" resource -- for example, if I assign resources "John," "Jane," and "Jim" to event "Weekly Meeting," "Weekly Meeting" is only rendered on the calendar for "John." I would expect three rectangles for "Weekly Meeting" for John, Jane, and Jim to render -- please let me know if this is not supported functionality. 

Thanks for your assistance!

**Comment by ExtAnimal** [comment]
A Calendar has a different view of events that a Scheduler.

In the Calendar's view there is only one event: "The" event, and there will only be one block for it in a calendar view.

But there has been some interest in a new "Resource View" mode which has an initial design but has not yet been roadmapped:

![Screenshot 2020-10-02 at 14 21 53](https://user-images.githubusercontent.com/200516/98808015-73295800-2413-11eb-9c20-170ee5fcd7bc.png)

**Comment by matsbryntse** [comment]
We have a 'multiassign' demo now
