### ISSUE TITLE
suspendAutoSync method for CrudManager

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1853]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=15853)

Replace the implementation bellow with a new suspendAutoSync method for CrudManager
```
// Suspend AjaxStore auto committing for the duration of the edit.
me.schedulerAutoCommit = taskStore.autoCommit;
taskStore.autoCommit   = false;
// Suspend Project auto syncing for the duration of the edit.
me.schedulerAutoSync       = scheduler.project.autoSync;
scheduler.project.autoSync = false;
```

**Comment by isglass** [comment]
We have `suspendCrudAutoSync()` and `resumeCrudAutoSync()`, but they are private. Discuss with @arcady-zherdev about making them public
