### ISSUE TITLE
[REACT] Very low performance of React cell renderers

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1869]
The performance is indeed low. It is caused by create/delete cycle of portals (state uses Set()). The idea is to reuse portals (state should use Map()), key portals by record.id and column.id. The portal would be re-used, not deleted.

We need to think of leaks too so that some (lazy?) cleaning mechanism would be employed.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=15868&p=79231#p79231)

Hello,

After implementing React cell renderers I noticed serious performance drop. See test case attached. Reproduction steps:
	1) yarn && yarn start
	2) Don't open Chrome devtools! With open Chrome devtools browser window may deadly freeze, so better try it first without active devtools. 
	3) Expand few tasks to get more rows visible and scroll back and forth, you will experience heavy UI freezes.

Despite the problems with devtools I managed to use React profiler and made a screenshot. After one single task expanded (with just few sub tasks) BryntumGantt component rendered 192 times (see screenshot attached). This seems to be the root of the issue.

In production build things become a little better, but freezes are still very perceptible. And devtools still makes dead freeze.

Please, help.

**Comment by sebastian-schlecht** [comment]
We can reproduce this. This is a potential blocker for us.

**Comment by jsakalos** [comment]
@sebastian-schlecht the issue has been resolved, however, it has not been merge yet. It is slated for 4.0.4 release.

**Comment by sebastian-schlecht** [comment]
> @sebastian-schlecht the issue has been resolved, however, it has not been merge yet. It is slated for 4.0.4 release.

Thanks for letting us know! Happy to hear that. Do you have an ETA for when this lands in the customer area?

**Comment by jsakalos** [comment]
It should be in nightly builds in a couple of days.
