### ISSUE TITLE
Virtual event rendering derenders too eagerly

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#1873]
It derenders an event as soon as its layout's `right` edge goes out of the viewport. Some events have content that overflows that, such as milestones. Maybe use some kind of margin?

This also includes the Labels feature when there's a right aligned label (which we don't have an example of and therefore this hasn't been seen).

![mb](https://user-images.githubusercontent.com/200516/99079763-4bbfc000-25b8-11eb-8118-4e2a5ecf59ea.gif)

**Comment by isglass** [comment]
A margin of perhaps 100px should fix most cases, if anyone has longer labels than that I suppose we could make it configurable

**Comment by matsbryntse** [comment]
Labels case:
![scroll](https://user-images.githubusercontent.com/218570/102720868-44967b00-42f7-11eb-9216-baae66c056fc.gif)
