### ISSUE TITLE
WBS column filter returns no results when you type visible WBS value

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1885]
After #1788 is merged filter behavior has changed. To reproduce on advanced demo try to type visible WBS code to filter field - no results returned. Now clear filter and filter vial WBS cell context menu, see why filter using dots doesn't work:
![image](https://user-images.githubusercontent.com/45400762/99231547-d21b1280-2801-11eb-924b-3757369ad534.png)

UPD: Ensure column filter correctly works after passing through State API. e.g.
1. filter column
2. save state
3. reset filter
4. apply state -> result should be same as on step 1

Also need to make sure sorting works properly (like it does now):
```
// correct
1.1.1
1.1.2
...
1.1.10

// incorrect
1.1.1
1.1.10
1.1.2
```

**Comment by isglass** [comment]
Probably needs a `filterable` implementation, since it holds indices and not the actual string.
Or a more generic way, filtering by data fields print value

**Comment by bmblb** [comment]
There's a wbsIndex which is an array serialized to string like `[1,1,5]` and `wbsCode` which has string `1.1.5`. filterable could use wbsCode field for filtering

**Comment by bmblb** [comment]
It feels like this should work like fullDuration column: it uses a special field, which returns instance of Duration, which itself defines `toString` which is conveniently used in filters, and `valueOf` which is used in sorters. it works seamlessly with state. @dongryphon
