### ISSUE TITLE
Revise column state attributes

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1896]
Consider following usecase.

1. There's an app like this which saves its state:
```
import 'MyFilterField.js';

grid = new Grid({
  columns: [
    { type : 'mycolumn', filterable : { filterField : { type : 'myfilterfield' } } }
  ]
});

// load state if exists
const state = JSON.parse(localStorage.getItem('foo'));
if (state) { grid.state = state; }

// save state to localStorage
localStorage.setItem('foo', JSON.stringify(grid.state));
```

2. Now inspect local storage and see column has `filterable` with field type.
3. Let's say app changed and we no longer import `MyFilterField`:
```
grid = new Grid({
  columns : [
    { type : 'mycolumn' }
  ]
})
```
4. now when we load the app we get an exception, because column is trying to instantiate a widget which doesn't exist

To do:
1. filterable should not be part of state, it cannot be modified in UI
2. filters are saved in the store state, column has nothing to do with them

**Comment by isglass** [comment]
Agree, does not make sense to store filterable in state. Please also remove `text` while at it

Handled in Column.getState()
