### ISSUE TITLE
Tooltip does not hide on hover target change if hideOnDelegateChange enabled

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1910]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=15919&p=79442)

1. Open any of scheduler's examples, disable `eventTooltip` and `scheduleTooltip` feature if it's required.
2. Import `Tooltip`:
```
import('../../lib/Core/widget/Tooltip.js').then(m => window.Tooltip = m.default)
```
3. Define this function
```
window.commonTooltip = function(selector, message) {
    new Tooltip({
        forSelector          : selector,
        hideOnDelegateChange : true,
        showOnHover          : true,
        anchorToTarget       : false,
        hideDelay            : 50,
        html                 : 'hello'
    });
};
```
4. Run example, in console call the next to add tooltips to grid cell and to event bars:
```
commonTooltip('.b-sch-event, .b-sch-event *', 'Event tooltip');
commonTooltip('.b-grid-cell, .b-grid-cell *', 'Cell toolltip');
```

5. Hover on grid cell, wait until a tooltip will be shown. Move a mouse pointer to the event bar.
Grid cell tooltip will stay visible. But should disappear after hideDelay timeout.

![tooltip_stays](https://user-images.githubusercontent.com/7203098/99638915-2aa41700-2a71-11eb-9e24-976d88926c2c.gif)

**Comment by ExtAnimal** [comment]
It is still over the cell.

The event is in a cell, so it is over both targets.

**Comment by ExtAnimal** [comment]
If they really need this maybe something like

```
commonTooltip('.b-sch-event-wrap, .b-sch-event-wrap *');
commonTooltip('.b-grid-row :not(.b-sch-event-wrap), .b-grid-row :not(.b-sch-event-wrap) *');
```

But these are the `eventTooltip` and `scheduleTooltip` features.

**Comment by pmiklashevich** [comment]
Not a bug
