### ISSUE TITLE
Selected constraint is not set to task when blurring the field

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1918]
Steps to reproduce on advanced demo https://www.bryntum.com/examples/gantt/advanced/ :
(execute steps only with a pointer)
1. scroll to constraint type column, start editing constraint for any `Configure firewall`
2. pick constraint `Must start on` (or any other)
3. click on the next cell in the same row - field closes, constraint is not set
4. do steps 1-2 again, but now click on the bottom row - field closes, constraint is set.

**Comment by matsbryntse** [comment]
Same issue as https://github.com/bryntum/support/issues/1920 ?

**Comment by matsbryntse** [comment]
Dupe
