### ISSUE TITLE
Add support for adding 0-duration event

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1948]
Render as some configured min-height.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=15968&p=79627#p79627)

How do I configure my Calendar to show events with the start data and end date equals?

For example:

Start Date: 11/26 at 9:00 AM
End Date: 11/26 at 9:00 AM

![calendar.png](https://www.bryntum.com/forum/download/file.php?id=11839)
![calendar.png](https://www.bryntum.com/forum/download/file.php?id=11839)

**Comment by gabiamante** [comment]
Hi, any news on this new feature?

**Comment by gabiamante** [comment]
Hello, any news on the new feature?

**Comment by ExtAnimal** [comment]
It is *possible* to create such events already, by just using the same time as start and end. It obviously just renders a zero height event block:

![Screenshot 2021-01-12 at 12 38 00](https://user-images.githubusercontent.com/200516/104309806-a303e300-54ca-11eb-94c3-3ec532fa0ddf.png)

And the only way to access that is by keyboard accessibility: Tabbing onto it, then invoking the editor using ENTER. You cannot click it.

We could update the layout class for DayView to show a minimum height, but that could be misleading - if it shows for example a 15 minute block height, it gives the impression to a user that there's 15 minutes of unavailable time.

We should survey customer requirements as to a desirable outcome for very short duration events. For example, at standard hourHeight setting of 42, a five minute event would be 3.5 pixels tall which would still be extremely difficult to hover or click on.

So this needs solving for the general case of very short duration events.

**Comment by gabiamante** [comment]
Okay, thank you for the information.

**Comment by jgavric** [comment]
Would it be possible to have somthing similiar to the Microsoft Outlook calendar in case of short event durations?
E.g. to have two separate boxes which represent an event (first for duration ,second for content).

![example](https://user-images.githubusercontent.com/9656068/198548686-8ac24ab4-7048-4412-b061-ed39ab2a5183.png)
