### ISSUE TITLE
When constrainDragToTimeline is false the dragging outside a scheduler should be invalid

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#1953]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=15976

Scheduler/examples/drag-between-schedulers/index.html
```
	<style>
		#container {
			margin-left : 200px;
		}
	</style>
```
Scheduler/examples/drag-between-schedulers/app.js
```
    startDate  : new Date(2017, 11, 30, 6),
    endDate    : new Date(2018, 0, 2, 20),
    listeners : {
        afterEventDrop({ valid }) {
            console.log(valid); // returns true, expect false
        }
    },
```
Scroll to the right. Drag a task to the left outside of the scheduler1. Drop it. Expect action to be invalid and the event returns to its original place. Instead it's moved to a new place on the timeline behind the resource cells.
![2020-11-24-200603](https://user-images.githubusercontent.com/57486733/100129740-faa2ac80-2e92-11eb-8d25-19fe6735605f.gif)

**Comment by matsbryntse** [comment]
Fixed as part of https://github.com/bryntum/support/issues/1954
