### ISSUE TITLE
Add docs to describe how to define weekend days

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1969]
https://www.bryntum.com/forum/viewtopic.php?f=52&t=15997&p=79744

In Ext Gantt we had:
```
WeekendFirstDay     : 6,
WeekendSecondDay    : 0,

```
TimeAxisViewModel.js
```
if (me.calendar && me.calendar.isWeekend(start)) {
                        cellData.headerCellCls += ' b-sch-dayheadercell-nonworking’;
                    }

```5:28
This is the only reference to isWeekend - stale API that’s no longer in use?

**Comment by arcady-zherdev** [comment]
Calendars do not need those settings anymore. Weekend days are defined w/ intervals as any other non-working periods.
And the code w/ `isWeekend` call is probably copypasted from Ext world as-is.

**Comment by pmiklashevich** [comment]
SchedulerPro/Gantt weekends are configurable and it's described in corresponding guides. Scheduler weekends are not configurable. Ticket: #2309
