### ISSUE TITLE
Infinite requests if wrong response received

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1970]
Modify advanced app.js:
```
project : {
        // Let the Project know we want to use our own Task model with custom fields / methods
        taskModelClass : Task,
        autoSync : true,
        transport      : {
            load : {
                url : '../_datasets/launch-saas.json'
            },
            sync : {
                url : '../_datasets/launch-saas.json'
            }
        },
        autoLoad : true,

        // The State TrackingManager which the UndoRedo widget in the toolbar uses
        stm      : {
            autoRecord : true
        }
    },
```

**Comment by arcady-zherdev** [comment]
This case actually continues #1881
In that ticket we decided that if server-side response includes corresponding table section (`tasks` for example) we use it (BW compatible mode). And in this case we response `tasks` but it doesn't confirm the modified task persisting.
So we end up having the same dirty records after sync() cal completion.

The solution could be merging of requested and responded records arrays. Then we always commit modified records.
