### ISSUE TITLE
Create angular gantt-schedulerpro demo

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#1981]
Requested here: https://www.bryntum.com/forum/viewtopic.php?p=79797#p79797

Do it with wrappers and import both Gantt and Scheduler from Gantt bundle. Do not include both scheduler and gantt bundles in one app.

**Comment by JockeLindberg** [comment]
https://bryntum.com/products/gantt/examples/frameworks/angular/gantt-schedulerpro/dist/gantt-schedulerpro/
