### ISSUE TITLE
Not possible to enter 00:00 into time field

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2]
* Open http://lh/bryntum-suite/grid/examples/columntypes/
* Edit time field in app.js to be 
<pre><code>        { text : 'Time', field : 'time', flex : 1, type : 'time', format : 'HH:mm' },

</code></pre>

* enter time 00:00 in time cell editor => invalid
* 00:01 works

**Comment by SergeyMaltsev** [comment]
Reported here
https://www.bryntum.com/forum/viewtopic.php?f=51&t=12627
