### ISSUE TITLE
Vertical mode support for PDF export

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2007]
Requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=16054&p=79972
https://bryntum.com/forum/viewtopic.php?f=51&t=16896&p=84057#p84057
https://www.bryntum.com/forum/viewtopic.php?f=51&t=21501&p=106365#p106365

**Comment by pmiklashevych** [comment]
Hello Max! How is it going with the ticket? Any thoughts on when it might be rolled out?

**Comment by bmblb** [comment]
Hello. Goes well, but slower than I anticipated. So I paused it while I'm doing another batch of work related to the live updates support. Hopefully this one can get resolved in April/May.

**Comment by pmiklashevych** [comment]
Got it, thanks!
