### ISSUE TITLE
Checkbox should support value attribute

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2016]
Forum: https://www.bryntum.com/forum/viewtopic.php?f=54&t=16065

According to our docs we support [value](https://www.bryntum.com/docs/calendar/#Core/widget/Checkbox#config-value) attribute. But in fact we override it with the "checked" value. Need to support native [value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value) attribute behaviour.

```
import Checkbox from '../../lib/Core/widget/Checkbox.js';

const checkbox = new Checkbox({
    appendTo : 'container',
    value    : 'test', // set the value here
    text     : 'Test Abc',
    checked  : true
});

console.log(checkbox.checked, checkbox.value);
// Expect: true, test
// Got: true, true

console.log(document.querySelector('input[name*=b-checkbox]:checked').value);
// Expect: test
// Got nothing, value attribute is not set
```

**Comment by isglass** [comment]
We have configurable `checkedValue` & `uncheckedValue` since 2022
