### ISSUE TITLE
Columns sub-menu does not scroll for many columns

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#202]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=43&t=13123#p68400

It jumps back to the top on any attempts to scroll with trackpad. Clicking on the scrollbar has no effect.
![column-combo-scrolling](https://user-images.githubusercontent.com/204844/72450604-f3166f80-37ba-11ea-9732-2ebc150c325c.gif)

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/615
