### ISSUE TITLE
Calendar should not sync to the store when create a new event before the event is saved in Event Editor

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2023]
Forum:
https://www.bryntum.com/forum/viewtopic.php?f=54&t=16077
https://www.bryntum.com/forum/viewtopic.php?p=82578#p82578

Calendar/examples/basic/app.js
```
    crudManager : {
        transport : {
            load : {
                url : 'data/data.json'
            },
            sync : {
                url : 'test'
            }
        },
        autoLoad : true,
        autoSync : true
    },
```
http://lh/bryntum-suite/calendar/examples/basic/
Drag create. See request is sent

**Comment by ExtAnimal** [comment]
The drag create should not remove its drop indicator at the end *if* there's an edit feature available, but leave it for the upcoming edit to point to, and somehow allow outside code to clean up the drop indicator.

this would be better than our scheme right now of adding the event and setting an `editingNewlyAddedEvent` flag to mean the edit feature should *remove* it on Cancel press.

@dongryphon would best know where the difficulties are here.
