### ISSUE TITLE
Events stay selected after other events selection if they are not in the viewport

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#203]
Open http://lh/bryntum-suite/scheduler/examples/timeresolution/
select an event that's far away from others
scroll to other events, select
scroll back to original selected event - it still has selected styling

Video: https://www.loom.com/share/b3dc7cc71e964313b284fcec74eda04f

**Comment by tsygantsev** [comment]
And there is a related issue (I guess). The event doesn't get selected If it is out of the viewport and you try to select it through API
