### ISSUE TITLE
Support for tree lines

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2041]
![image](https://user-images.githubusercontent.com/218570/101143847-c6a85380-3617-11eb-9d31-2622ec7f574e.png)

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?f=52&t=24269&p=120179#p120179

**Comment by isglass** [comment]
https://forum.bryntum.com/viewtopic.php?f=52&t=30576&p=155208#p155208

**Comment by matsbryntse** [comment]
Resolved in https://github.com/bryntum/support/issues/10334
