### ISSUE TITLE
TimeAxis header updates incorrect on workingTime change

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2053]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=16115&p=80271

Make sure the browser width is not too big, for example 800px
Apply the next changes on basic example:

```
    startDate  : new Date(2017, 0, 1, 6),
    endDate    : new Date(2017, 0, 7, 20),
    ......
    workingTime: {
        fromHour : 0,
        toHour   : 24
    }
```
Run in console:
```
scheduler.workingTime = {				
     fromHour : 8,
     toHour   : 20
}
```
See that the header updated incorrect. This problem disappears after scroll.
![timeaxis-header](https://user-images.githubusercontent.com/7203098/101467065-cf34bd00-397c-11eb-80c5-60c769c42f89.gif)

**Comment by pmiklashevich** [comment]
Make sure the browser width is wide enough, for example 2048px
http://lh/bryntum-suite/scheduler/examples/workingtime/
Switch to "Days"
See the unwanted space:
<img width="2047" alt="Снимок экрана 2020-12-12 в 13 26 32" src="https://user-images.githubusercontent.com/57486733/101981456-03aac080-3c7e-11eb-8711-431b208ff0b6.png">

**Comment by pmiklashevich** [comment]
Related tickets:
https://github.com/bryntum/support/issues/1572
https://github.com/bryntum/support/issues/315

**Comment by matsbryntse** [comment]
Not reproducible
