### ISSUE TITLE
Using adopt blows away inline style / class names

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2059]
Would be more intuitive to respect any inline styling provided by implementer in the root node.

```
 new Grid({
        adopt : 'foo'
})
```

No style seen after rendering
`<div id="foo" style="width:500px"></div>`

**Comment by ExtAnimal** [comment]
We have very well documented configs.

```
new Grid({
    width : 500,
    adopt : 'foo'
})
```

**Comment by matsbryntse** [comment]
JS configs should trump HTML styles, but this doesn't exclude option pure HTML sizing styles
