### ISSUE TITLE
Impossible to map task field to non-existent field

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2062]
Usecase: user wants to provide percent done calculated on the backend and not use percentDone calculation by the project. User knows field could have data mapping, so he points project field `percentDone` to random field - `_percentDone` and defines field which will be mapped to `percentDone` in the incoming dataset:
```
static get fields() {
    return [
        { name : 'percentDone', dataSource : '_percentDone' },
        { name : 'myPercentDone', dataSource : 'percentDone' }
    ];
}
```

Problem: if mapped field (`_percentDone`) does not exist in the incoming dataset, model would fallback to default `percentDone` value. Then two model fields would map to a single property in the dataset, which has undesired implications.

Suggestion: field should use strictly the configured field even if it doesn't exist

Note: other fields likely have same problem, need to test them too

**Comment by canonic-epicure** [comment]
They should override the `calculatePercentDone` method as:
```ts
        * calculatePercentDone () : ChronoIterator<number> {
                return yield ProposedOrPrevious
        }
```

It will be always returning the user-provided value (behave like regular Model field)
