### ISSUE TITLE
Disabling event edit does not work with SchedulerPro

### ISSUE THREAD

**Issue by ivnbogdan** [bryntum/support#2064]
Setting the `eventEdit` feature to false does not disable the double click event popup widow.

This incorrectly displays the editor when double clicking an event
```
new SchedulerPro({ ... 
  features: {
    eventEdit: false
  }
}
```

This works correctly in regular (not-pro) Scheduler 
```
new Scheduler({ ... 
  features: {
    eventEdit: false
  }
}
```

**Comment by matsbryntse** [comment]
For SchedulerPro, the feature is called taskEdit, please see https://bryntum.com/docs/scheduler-pro/#SchedulerPro/feature/TaskEdit
