### ISSUE TITLE
Vertical Scheduler does not update view when undoing actions

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2067]
https://www.bryntum.com/forum/viewtopic.php?p=80383#p80383

Scheduler/examples/undoredo/app.js
```
new Scheduler({
    appendTo  : 'container',
    minHeight : '20em',

    features : {
        tree         : false,
        regionResize : true,
        dependencies : false
    },
    mode : 'vertical',
```
http://lh/bryntum-suite/scheduler/examples/undoredo/
Drag a task. Click Undo button. See the task position is not reverted.
Drag another task. See the first task position is updated.

**Comment by fdaugs** [comment]
@pmiklashevich Any updates on this? This bug prevents me from updating to >4.0.3. 4.0.4 includes a fix I need, but also broke the undo functionality.
