### ISSUE TITLE
Setting task editor tab config to true hides the tab

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2068]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=16140

SchedulerPro/examples/taskeditor/app.js
```
    features : {
        taskEdit : {
            items : {
                generalTab : true // expect 
            }
        }
    },
```
http://lh/bryntum-suite/schedulerpro/examples/taskeditor/
`true` - hides the tab => bug; expect tab to be shown with default configs
`{}` - shows the tab => corrext
`false` - hides the tab => correct

**Comment by matsbryntse** [comment]
Incorrect description, closed and opened as https://github.com/bryntum/support/issues/2069
