### ISSUE TITLE
wbsIndex field removed by mistake

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2070]
Related issue: #1885 
Removed in PR: https://github.com/bryntum/bryntum-suite/pull/2472/files#r539438504

This is public API, it cannot be removed in patch release. Should go through deprecation phase first.

**Comment by dongryphon** [comment]
I didn't realize the `wbsIndex` field was part of a release; I thought it was found insufficient due to inability to filter by it. Let's chat tomorrow
