### ISSUE TITLE
CellEdit#addNewAtEnd not respected

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2087]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=16162&p=80488)

Hi all,

Migrating from Gantt v2.1.9 to v4. 
I discovered that hitting the "enter" key after in the make changes in the name column will auto focus to the next row's name cell. If the user happens to be on the last row, then hitting enter will create a new row/task. Is there a way to prevent this behavior?

**Comment by bdow** [comment]
Thanks @matsbryntse!!!
