### ISSUE TITLE
Block indent/outdent option for tasks when this operation is invalid

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2096]
Reproducible on advanced demo, try to outdent `install apache` task. It will just back and forth, because outdent operation is invalid - task will have outgoing dependency to one of its future children.

Solutions:
1. block option if outdent/indent is not possible
2. remove conflicting dependency (potentially harmful)

**Comment by matsbryntse** [comment]
Works as intended, cycle popup is shown
