### ISSUE TITLE
"Core" code not isomorphic

### ISSUE THREAD

**Issue by canonic-epicure** [bryntum/support#2104]
Rahulranjan reports some of the core code is not isomorphic (again): https://www.bryntum.com/forum/viewtopic.php?p=80612#p80612

"Again", because it was made isomorphic some time ago and seems regressed since.

**Comment by bmblb** [comment]
@SergeyMaltsev we need to setup TC to run engine tests using node, like this:
```
node SchedulingEngine/tests/index.js
```

One note though: siesta uses `esm` package to load modules and that one does not support optional chaining which we use a lot. @canonic-epicure suggested a change to `siesta/package.json` to fix that:
```diff
-    "esm": "^3.2.25",
+    "esm": "git://github.com/jsg2021/esm.git",
```

**Comment by SergeyMaltsev** [comment]
@bmblb IIRC optional chaining supported starting with NodeJS 13 (or stable 14) which is not used yet. We use Node JS 12.
First we have to upgrade to NodeJS 14 which  is definitely not compatible with several frameworks demos (I've checked this already).

**Comment by bmblb** [comment]
@SergeyMaltsev node upgrade is required too, but that's not enough. updating esm is mandatory
