### ISSUE TITLE
Update of recurring event creates another repeat of event

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2108]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=16150&p=80425)

1. Open https://www.bryntum.com/examples/scheduler/recurrence/
2. Create a new recurring event, repeats every week, stops after 3 times.
3. Edit second repeat of event, extend it for 1 more day, save and apply to all future events.

Another repeat of the event will be created (so, 4 in total, but should be 3)

**Comment by arcady-zherdev** [comment]
When an occurrence is saved it becomes a "real" recurring event w/ the same recurrence rule.
So it starts a new recurrence having 3 items in it. Need to change its stop condition when it gets saved.
