### ISSUE TITLE
Undo/redo popup titles are not localized

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2118]
https://bryntum.com/examples/gantt/advanced/

<img width="1139" alt="Снимок экрана 2020-12-16 в 13 21 23" src="https://user-images.githubusercontent.com/57486733/102336060-bbeba800-3fa1-11eb-9cea-4195a5dea508.png">

**Comment by pmiklashevich** [comment]
Should critical path button add an action of "Expand all" to the history?

**Comment by isglass** [comment]
@pmiklashevich I was not aware we could undo/redo expanding nodes, seems strange
