### ISSUE TITLE
Recurrence edit confirmation should not be displayed when drag creating a recurring event

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2125]
https://www.bryntum.com/forum/viewtopic.php?p=80748#p80748

http://lh/bryntum-suite/calendar/examples/basic/
[beforeEventAdd](https://www.bryntum.com/docs/calendar/#Calendar/feature/EventEdit#event-beforeEventAdd) & [beforeEventSave](https://www.bryntum.com/docs/calendar/#Calendar/feature/EventEdit#event-beforeEventSave) docs
```
calendar.on({
    beforeEventSave() { console.log('beforeEventSave') },
    beforeEventAdd() { console.log('beforeEventAdd') }
})
```

Create a few new events holding CMD on Mac or CTRL on Windows. Save it.
See the recurrence confirmation dialog appears => bug, should not be needed since it's a new event.
beforeEventSave is not fired => bug, ticket here: https://github.com/bryntum/support/issues/2123
beforeEventAdd is not fired => bug, happens due to adding new events to store on drop (by design though).
See how `editingNewlyAddedEvent` concept can be applied to prevent confirmation dialog to appear.

**Comment by pmiklashevich** [comment]
This ticket might be related: https://github.com/bryntum/support/issues/2023
Following the conversation there, maybe we will stop adding the newly created records to the store before they are saved.

**Comment by pmiklashevich** [comment]
Minor UI issues reported separately: https://github.com/bryntum/support/issues/2124
