### ISSUE TITLE
Grid - Template columns not rendering properly after grouping the grid

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2135]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=16235&p=80872)

Hi.

We have encountered an issue where template columns are not rendering correctly after a grouping operation has been performed on the grid.

We can replicate this behaviour using this online example and Google Chrome - https://www.bryntum.com/examples/grid/columntypes/.

Notice how the Link column is a Template column, and how a link is rendered for every row
Group the Date Column Ascending and the scroll up and down the grid
Notice that some rows no longer render a link in the Link column.

Thanks.
![Screenshot 2020-12-18 at 12.24.08.png](https://www.bryntum.com/forum/download/file.php?id=12065)

**Comment by bmblb** [comment]
Some rows still do not render properly as seen in this recording:
https://app.therootcause.io/#bryntum/bryntum-grid/feedback/64a5d7a4bd512352588624ee26230cbdab71ae96
