### ISSUE TITLE
ResourceHistogram is not refreshed after inline data reset and load again

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2138]
https://www.bryntum.com/forum/viewtopic.php?p=80871#p80871

http://lh/bryntum-suite/gantt/examples/resourcehistogram/
Gantt/examples/resourcehistogram/app.js

```
const project = window.project = new ProjectModel({
    startDate : '2019-01-16',
    endDate   : '2019-02-13'
});

const gantt = new Gantt({...})
new Splitter({...});

const histogram = window.histogram = new ResourceHistogram({
    appendTo    : 'container',
    project,
    hideHeaders : true,
    partner     : gantt,
    rowHeight   : 50,
    showBarTip  : true,
    columns     : [
        { field : 'name', flex : 1 },
        { field : 'calendar', flex : 1 }
    ],
    tbar : {
        cls    : 'histogram-toolbar',
        height : '3em',
        items  : [
            {
                type     : 'button',
                ref      : 'reloadButton',
                text     : 'Reset',
                onAction : 'up.onResetButton'
            },
            {
                type     : 'button',
                ref      : 'loadButton',
                text     : 'Load',
                onAction : 'up.onLoadButton'
            }
        ]
    },
    onResetButton() {
        gantt.project.taskStore.removeAll();
        gantt.project.assignmentStore.removeAll();
        gantt.project.resourceStore.removeAll();
    },
    onLoadButton() {
        project.loadInlineData({
            calendarsData : [{
                id           : 'general',
                name         : 'General calendar',
                hoursPerDay  : 24,
                daysPerWeek  : 5,
                daysPerMonth : 20,
                intervals    : [{
                    recurrentStartDate : 'on Sat at 0:00',
                    recurrentEndDate   : 'on Mon at 0:00',
                    isWorking          : false
                }]
            }],
            eventsData : [{
                id        : 1,
                name      : 'Task',
                startDate : '2020-12-13T23:00:00.000Z',
                endDate   : '2020-12-18T23:00:00.000Z'
            }],
            resourcesData : [{
                id       : 1,
                name     : 'Resource',
                calendar : 'general'
            }],
            assignmentsData : [
                { id : 1, event : 1, resource : 1 }
            ],
            dependenciesData : []
        });
    }
});
```

Click load button. See the data is loaded. ResouceHistogram shows calendar name in the column and resource allocation chart.
<img width="837" alt="Снимок экрана 2020-12-18 в 20 52 11" src="https://user-images.githubusercontent.com/57486733/102645522-a4fcaf80-4173-11eb-855c-acc5740bdb6f.png">

Click reset button to remove all records from stores.
Click load button again to restore data.
See Gantt is correct. Task is assigned to the resource. ResouceHistogram shows the record, but calendar column shows ID instead, and resource allocation chart is missing.
<img width="840" alt="Снимок экрана 2020-12-18 в 20 52 23" src="https://user-images.githubusercontent.com/57486733/102645635-d1183080-4173-11eb-8c22-01d6e49eaf1e.png">

When refresh rows manually it updates the column info but the chart is still missing
`histogram.refreshRows()`
Calendar name is shown

**Comment by pmiklashevich** [comment]
In 4.1.0 the same sequence leads to runtime error after data is loaded the second time:
```
Identifier.js:128 Uncaught (in promise) Error: Unknown identifier [object Object]
    at throwUnknownIdentifier (Identifier.js:128)
    at EngineTransaction.addEdge (Transaction.js:397)
    at EngineTransaction.onReadIdentifier (Transaction.js:440)
    at EngineTransaction.calculateTransitionsStackGen (Transaction.js:556)
    at calculateTransitionsStackGen.next (<anonymous>)
    at EngineTransaction.calculateTransitions (Transaction.js:477)
    at calculateTransitions.next (<anonymous>)
    at runGeneratorAsyncWithEffect (Calculation.js:102)
    at Transaction.js:366
```

**Comment by VictorAITERA** [comment]
I get the same error when I reload a second time my bryntum gantt :
`TypeError: Cannot read properties of undefined (reading 'getEvents')
    at HorizontalRendering.layoutResourceEvents (gantt.umd.js:210048)
    at HorizontalRendering.renderer (gantt.umd.js:210259)
    at HorizontalRendering.refreshEventsForResource (gantt.umd.js:210209)
    at gantt.umd.js:209637
    at Array.forEach (<anonymous>)
    at HorizontalRendering.updateFromHorizontalScroll (gantt.umd.js:209637)
    at ResourceHistogram.onSchedulerHorizontalScroll (gantt.umd.js:199235)
    at ResourceHistogram.<anonymous> (gantt.umd.js:199253)
    at ResourceHistogram.trigger (gantt.umd.js:50955)
    at TimeAxisSubGrid.onInternalResize (gantt.umd.js:150948)`
    
    Has :
    "@bryntum/gantt": "^4.3.2",
    "@bryntum/gantt-react": "^4.3.2",
