### ISSUE TITLE
Should be possible to render Grid inside another Grid or Tree grid

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2139]
Requested here: https://www.bryntum.com/forum/viewtopic.php?p=80890#p80890
Example of nested grids:
![Nested Grid Example](https://user-images.githubusercontent.com/57486733/102650004-3b809f00-417b-11eb-82a0-91b53119be15.png)

**Comment by pmiklashevich** [comment]
Tried to render grid in widget column. Got error when click on it
<img width="2048" alt="Снимок экрана 2020-12-18 в 21 46 32" src="https://user-images.githubusercontent.com/57486733/102650297-ba75d780-417b-11eb-91f3-87693b2ef0e3.png">
