### ISSUE TITLE
enableProgressNotifications should be documented

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2146]
Used in our demos.
https://www.bryntum.com/forum/viewtopic.php?f=52&t=16243&p=80917#p80917

**Comment by pmiklashevich** [comment]
@matsbryntse Here is the Engine docs:
https://www.bryntum.com/docs/gantt/engine/classes/_lib_engine_quark_model_scheduler_basic_schedulerbasicprojectmixin_.schedulerbasicprojectmixin.html#enableprogressnotifications
It is placed in SchedulerBasicProjectMixin. So I assume it should work for simple scheduler which uses project, SchedulerPro, and Gantt. So the candidate for the docs is Scheduler/lib/Scheduler/model/mixin/ProjectModelMixin.js class. But we have to have tests coverage for all products.

Docs:
```
    /**
     * Set to `true` to enable the calculation progress notifications.
     * @name enableProgressNotifications
     * @config {Boolean}
     * @category Engine
     */
    /**
     * Enables/disables the calculation progress notifications.
     * @name enableProgressNotifications
     * @member {Boolean}
     * @category Engine
     */
```
