### ISSUE TITLE
Respect event labels during event layout

### ISSUE THREAD

**Issue by isglass** [bryntum/support#2147]
Currently they are always overlapped by other events, add a config + logic to include their width when laying the events out

- [x] Add `labelLayoutMode` to Labels features, with same options as `milestoneLayoutMode`
- [x] - default/none
- [x] - estimate
- [x] - measure
- [x] Add `labelCharWidth` config
- [x] Add to labels demo
- [x] Tests

**Comment by peterwake** [comment]
This is a great development, thanks for doing it. Is there a demo page where we can see this?
