### ISSUE TITLE
Implement resourceTimeRangeRenderer

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2173]
Should be possible to customize the text and print out duration, for example.

Similar to eventRenderer need to implement resourceTimeRangeRenderer for `eventRecord.isResourceTimeRange === true`. See SchedulerEventRendering.generateRenderData.

Requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=16265

**Comment by matsbryntse** [comment]
Supported now
