### ISSUE TITLE
Adding non-working interval dynamically does not recalculate tasks

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2176]
https://www.bryntum.com/forum/viewtopic.php?p=81083#p81083

https://www.bryntum.com/docs/scheduler-pro/#SchedulerPro/model/CalendarModel#function-addInterval

SchedulerPro/examples/non-working-time/app.js
```
    startDate         : '2020-03-22',
    endDate           : '2020-03-28',
....
    viewPreset : 'weekAndDayLetter',
```

SchedulerPro/examples/non-working-time/data/data.json
```
{
    "success"     : true,
    "project"     : {
        "calendar" : "weekends"
    },
    "calendars": {
        "rows": [
            {
                "id": "weekends",
                "name": "Weekends",
                "intervals": [
                    {
                        "recurrentStartDate": "on Sat at 0:00",
                        "recurrentEndDate": "on Mon at 0:00",
                        "isWorking": false
                    },
                    {
                        "startDate" : "2020-03-25",
                        "endDate"   : "2020-03-26",
                        "isWorking" : false
                    }
                ]
            }
        ]
    },
```
Works:
<img width="1049" alt="Снимок экрана 2020-12-28 в 15 00 19" src="https://user-images.githubusercontent.com/57486733/103213002-6e662800-491d-11eb-8523-54fa201f008e.png">

SchedulerPro/examples/non-working-time/data/data.json
```
{
    "success"     : true,
    "project"     : {
        "calendar" : "weekends"
    },
    "calendars": {
        "rows": [
            {
                "id": "weekends",
                "name": "Weekends",
                "intervals": [
                    {
                        "recurrentStartDate": "on Sat at 0:00",
                        "recurrentEndDate": "on Mon at 0:00",
                        "isWorking": false
                    }
                ]
            }
        ]
    },
```
RELOAD THE PAGE

<img width="1051" alt="Снимок экрана 2020-12-28 в 15 01 39" src="https://user-images.githubusercontent.com/57486733/103213064-9a81a900-491d-11eb-899c-718f6b9b0e28.png">

Now add the interval dynamically in console:
```
scheduler.project.calendarManagerStore.first.addInterval({
    "startDate" : "2020-03-25",
    "endDate"   : "2020-03-26",
    "isWorking" : false
})
```
<img width="1488" alt="Снимок экрана 2020-12-28 в 15 02 33" src="https://user-images.githubusercontent.com/57486733/103213104-bdac5880-491d-11eb-8a32-8d285450ddd6.png">

See events are not rescheduled. `scheduler.project.commitAsync()` does not help.
Dragging events from working days to the second half of the Wednesday is not allowed => correct
Dragging events from working days to the first half of the Wednesday is allowed => bug
<img width="1052" alt="Снимок экрана 2020-12-28 в 15 03 04" src="https://user-images.githubusercontent.com/57486733/103213249-298ec100-491e-11eb-956a-6bbc5b4f332b.png">

**Comment by taauntik** [comment]
An user reported [here](https://forum.bryntum.com/viewtopic.php?f=51&t=23234&p=114908#p114908) too

**Comment by chuckn0rris** [comment]
Another request [here](https://forum.bryntum.com/viewtopic.php?p=115072#p115072)

**Comment by schTi** [comment]
@canonic-epicure Here again the reproduction steps for this, as it seems to work for when the added interval overlaps the event model, but not when it overlaps only the dependency lag, which itself should also influence the event model.

1. Let's assume we have event A and event B, both with a duration of 2, and there is a dependency between them from the end of A to the start of B. Also, this dependency has a lag of 1 (unit is hours here).

![Screenshot 2022-12-09 at 16 28 27](https://user-images.githubusercontent.com/49444254/208696021-facf6146-9830-4fb8-85ac-5f708bf1a091.png)

2. Now, we also use a calendar to specify the working times of the events. For this calendar, we have a non-working time interval that is exactly the time span that is currently the gap between A and B. Thus, B needs to be rescheduled to start one hour later to satisfy the lag definition. The events will now look like this:

![Screenshot 2022-12-09 at 16 39 50](https://user-images.githubusercontent.com/49444254/208696074-5b051bd6-7393-47ee-88fd-5ff9147f7965.png)

3. **Here is the thing:** When the interval was added during the initial load, this rescheduling happens perfectly, and the events end up in the correct state. BUT: When we modify the calendar later on, no rescheduling happens, A and B just reside in the same position as they were in 1.

To update the calendar, I am using the addIntervals method. Below is the code for this example, which is adapted from one of the SchedulerPro examples, you can plug it into the examples (added comments to test the cases).

```ts
import { SchedulerPro } from '../../build/schedulerpro.module.js';
import shared from '../_shared/shared.module.js';

// region Data

const resources = [{ id: 'r1', name: 'Mike' }];
const events = [
  {
    id: 1,
    resourceId: 'r1',
    startDate: new Date(2017, 0, 1, 10),
    endDate: new Date(2017, 0, 1, 12),
    name: 'A',
    iconCls: 'b-fa b-fa-mouse-pointer',
    calendar: 'start',
  },
  {
    id: 2,
    resourceId: 'r1',
    startDate: new Date(2017, 0, 1, 13),
    endDate: new Date(2017, 0, 1, 15),
    name: 'B',
    iconCls: 'b-fa b-fa-arrows-alt',
    calendar: 'start',
  },
];

const dependencies = [
  {
    id: 't',
    from: 1,
    to: 2,
    lag: 60,
    lagUnit: 'm',
  },
];

const interval = {
  isWorking: false,
  startDate: new Date(2017, 0, 1, 12),
  endDate: new Date(2017, 0, 1, 13),
};

const calendars = [
  {
    id: 'start',
    // Case 1: When directly adding the interval, rescheduling works.
    // Comment out to test case 2.
    intervals: [
      interval
    ],
    unspecifiedTimeIsWorking: true,
  },
];

// endregion

const scheduler = new SchedulerPro({
  appendTo: 'container',
  resources,
  events,
  dependencies,
  calendars,
  features: {
    dependencies: true,
    dependencyEdit: true,
  },
  startDate: new Date(2017, 0, 1, 6),
  endDate: new Date(2017, 0, 1, 20),
  viewPreset: 'hourAndDay',
  rowHeight: 50,
  barMargin: 5,
  multiEventSelect: true,
  columns: [{ text: 'Name', field: 'name', width: 130 }],
});

setTimeout(() => {
  // Case 2: When adding the interval later, the rescheduling does not work.
  // Comment out to test case 1.
  scheduler.calendars[0].addIntervals([interval]);
  console.log(scheduler.calendars[0].intervals);
}, 2000);

```

**Comment by canonic-epicure** [comment]
Thanks for the reproducing steps, we'll be looking into this soon.

**Comment by canonic-epicure** [comment]
Reproduced, checking.
