### ISSUE TITLE
Resource non working time rendering is broken when fillTicks enabled in weekAndDayLetter view

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2179]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=16278

http://lh/bryntum-suite/schedulerpro/examples/resource-non-working-time/
`scheduler.zoomOut(5)`
<img width="1121" alt="Снимок экрана 2020-12-29 в 13 06 24" src="https://user-images.githubusercontent.com/57486733/103276161-ddec1e00-49d6-11eb-9f57-00e70ae411be.png">
`scheduler.fillTicks = true`
<img width="1121" alt="Снимок экрана 2020-12-29 в 13 06 39" src="https://user-images.githubusercontent.com/57486733/103276194-f1978480-49d6-11eb-8b60-23cbbb521f95.png">
Events take all tick width but all timeline is non working time now

**Comment by matsbryntse** [comment]
Not reproducible in latest release
