### ISSUE TITLE
Make Core.util.drag.DragContext public

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2181]
DragContext is mentioned in many places in Calendar.feature.CalendarDrag docs. Drag and drop, drag resize, and drag create is based on Draggable/Droppable and it uses DragContext to pass context to the handlers.

It's used in events:
- dragCreateEnd
- dragMoveEnd
- dragResizeEnd

And it's used in validators:
- validateCreateFn
- validateMoveFn
- validateResizeFn

For example [validateMoveFn](https://www.bryntum.com/docs/calendar/#Calendar/feature/CalendarDrag#config-validateMoveFn) mentions [get](https://www.bryntum.com/docs/calendar/#Core/util/drag/DragContext#function-get) function of the DragContext
<img width="840" alt="Снимок экрана 2020-12-29 в 14 29 46" src="https://user-images.githubusercontent.com/57486733/103280801-57d5d480-49e2-11eb-9b18-8143851560c3.png">

Mentioned here: https://www.bryntum.com/forum/viewtopic.php?f=54&t=16279
Use case is when you need to extract the event being moved to find out its original start/end dates:
```
    features : {
        drag : {
            async validateMoveFn({ drag }) {
                const record = await drag.get('eventRecord');
                console.log(record.startDate);
            }
        },
```

**Comment by pmiklashevich** [comment]
@dongryphon @ExtAnimal please comment on this. Is it a good idea to make it public? Otherwise we will have to replace Core.util.drag.DragContext with Object and declare another approach to extract the context data.

**Comment by ExtAnimal** [comment]
Probably the original record should be added as a public property in the event object. Maybe `draggedEventRecord`, or `sourceEventRecord`?

That would be easier than asking them to peek inside the context.

**Comment by dongryphon** [comment]
In the context of the `validateMoveFn` there is already a separate `eventRecord`, but the `drag` object is possibly going to be needed in other cases. In the calendar drag example we use it to determine the drop target view.

I think it got labeled `@internal` because that is the status of `Draggable` and `Droppable`. I don't see any issue making `DragContext` public but probably worth a review of its members to make sure we don't flip too many things public with the class.

**Comment by pmiklashevich** [comment]
@dongryphon I compared the eventRecord provided as a param with the one extracted from the context. The difference is that the eventRecord in the params has its dates already updated, where the extracted from context record has original dates. And the user wants to compare the diff between old and new dates to decide on the validation.

**Comment by dongryphon** [comment]
Duplicates https://github.com/bryntum/support/issues/3503 which is linked to a forum post, so I'm marking this one as the dupe
