### ISSUE TITLE
Setting panel title does not update tab strip item

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2194]
<img width="394" alt="Screenshot 2021-01-04 at 21 13 40" src="https://user-images.githubusercontent.com/218570/103575256-ba8f0a80-4ed1-11eb-91dc-38fddb979de2.png">

**Comment by dongryphon** [comment]
This is probably already fixed on my tabpanel branch https://github.com/bryntum/bryntum-suite/pull/2732
