### ISSUE TITLE
EventDrag feature. Upon drop of events, the sticky feature needs to update its layouts.

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#2218]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=16347

Solution is for the following to be called after the drop processing has completed.

```
scheduler.trigger('horizontalscroll');
```

This will cause the sticky feature (if present) to sync any event bar layouts with the scroll position.

**Comment by ExtAnimal** [comment]
This works in `EventDrag.js`

![Screenshot 2021-01-11 at 16 59 11](https://user-images.githubusercontent.com/200516/104205124-f40dcb80-5425-11eb-8b47-1a0cd8f3005f.png)

**Comment by matsbryntse** [comment]
Sticky now native
