### ISSUE TITLE
Scheduler Pro - Dependencies

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#2222]
On the Dependency view for resources on Scheduler Pro there is an issue with the correct dates translating to the Gantt when a task is shifted which has no resource assigned to it.  The relationship links ignore that task on Scheduler Pro, whilst the Gantt does not, so later tasks have different dates between the 2 products. How can I resolve this issue?

See Loom below;

https://www.loom.com/share/4030c8bc7daf4f0a9ee31bfdf3e0e35f

https://www.loom.com/share/30ad23047c7b4a99b22c86a627180fd2

**Comment by MRC38** [comment]
Have you looked at this?

**Comment by matsbryntse** [comment]
You'll get faster responses in our forums as we don't monitor GitHub for new external issues. We'll look at this shortly.

**Comment by arcady-zherdev** [comment]
I watched the videos yet unfortunately couldn't get the problem. Are the videos supposed to have sound recorded? I don't hear anything.

Could you reproduce the problem on our demos or provide a test case showing the issue?

**Comment by matsbryntse** [comment]
@MRC38 Any more info on how to reproduce?

**Comment by matsbryntse** [comment]
Lacking info, closing
