### ISSUE TITLE
Browser Issue - Chrome

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#2224]
I am using Chrome on Windows 10 and the page slider on the Gantt and Scheduler Prodoes does strange things when the page first loads, see video below.  As soon as I touch the slider the chart jumps back a number of months and i then have to go looking for the tasks.  Have you seen this issue and have a fix?

https://www.loom.com/share/bc27c0560e534af997afcb0a347d3f04

**Comment by MRC38** [comment]
Have you looked at this?

**Comment by matsbryntse** [comment]
Impossible to say just by looking at the video. Could you please try to reproduce this based on our basic samples to boil it down a bit?

**Comment by matsbryntse** [comment]
Any update?

**Comment by MRC38** [comment]
Hi Mats.

This seems to have been resolved with the recent update.
Thank you
