### ISSUE TITLE
Weird behavior for async beforeeventdropfinalize

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#2239]
Confirmed, it looks like a bug.

![drag-bug](https://user-images.githubusercontent.com/204844/104461151-3adafd00-55af-11eb-9dde-4341e8f47219.gif)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=16368&p=81487#p81487)

In order to reproduce the bug you can start from this demo https://www.bryntum.com/examples/scheduler/eventmenu/
adding the following listener

```
listeners : {
        beforeeventdropfinalize(event) {
            console.log(event.context);
            console.log(event.context.valid);
            event.context.async = true;
            setTimeout(() => {
                event.context.finalize(true);
            }, 100);
        }
    }

```

If you drag an event keeping the same timing and without going into another resource area the event won't go back to it's previous position.
The problem is also visible in a multi row condition, when you try to rearrange events, and steps are the same.
We tried logging the context and we have seen that the problem arises when timeDiff is 0 and hence valid is false.
Here attached you can find 2 pictures of the ending condition.
![Schermata 2021-01-13 alle 12.34.13.png](https://www.bryntum.com/forum/download/file.php?id=12179)
![Schermata 2021-01-13 alle 12.32.43.png](https://www.bryntum.com/forum/download/file.php?id=12178)

**Comment by matsbryntse** [comment]
Cannot reproduce, please try again on latest and let us know?
