### ISSUE TITLE
MSP importer returns success response with java exception as data

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2249]
https://www.bryntum.com/forum/viewtopic.php?p=81599#p81599

Reproduced online and locally:
http://dev.bryntum.com/examples/gantt-vanilla/examples/msprojectimport/index.html
http://lh/bryntum-suite/gantt/examples/msprojectimport/

Load the file 
[Gantt.Test.zip](https://github.com/bryntum/support/files/5830088/Gantt.Test.zip)

See server response:
```
{
    "success": true,
    "data": There was an exception raised during the operation. Exception message: java.lang.NullPointerException: Null key.
}
```

**Comment by crossleyjuan** [comment]
Just to understand the current status, is this resolved and will be delivered in the next release? we tried to save it in a different formats (project versions) but the error is still the same, any feedback about this please?

Thanks,

**Comment by pmiklashevich** [comment]
@crossleyjuan It will be a part of the 4.1.0 release. And you can see the fix in nightly builds, for example "gantt-2021-01-22-next" file. Feel free to download it from customer zone.
