### ISSUE TITLE
Should render tasks before engine is done with initial propagation

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2251]
In the standard case, incoming data is likely correct and engine propagation will result in a no-op. We should paint if we have startDate, endDate / duration all available in the incoming dataset. 

Progress on branch `gantt-render-early`.

TODO GANTT
- [x] Project start/end parsing
- [x] Readonly until calculated
- [x] Buckets/references
- [x] Try large dataset with crudmanager
- [x] Docs
- [x] Changelog
- [x] Whats new
- [x] Upgrade guide
- [x] Tests
- [x] Schedule on reload using CrudManager

TODO PRO

- [x] Readonly until calculated
- [x] Add / remove indices from Pro at runtime depending on delaying state
- [x] Progressbar
- [x] Docs
- [x] Changelog
- [x] Whats new
- [x] Upgrade guide
- [x] Tests

**Comment by canonic-epicure** [comment]
Some partial propagation still needs to be done as we need the references information (for dependencies). Also, if column with computed information (like early start date) is visible it also needs to be computed.

So need to construct the graph partially, for missing values.

**Comment by canonic-epicure** [comment]
Also, the full propagation needs to be done after the partial one, to construct the data dependencies in graph.

**Comment by isglass** [comment]
Progress on branch `gantt-render-early`
