### ISSUE TITLE
Dragged task hangs on drop position when drag and drop is finalized in `beforeEventDropFinalize` handler

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2258]
https://www.bryntum.com/forum/viewtopic.php?p=81662#p81662

https://www.bryntum.com/examples/scheduler/layouts/
Run in console:
```
bryntum.query('scheduler').on('beforeEventDropFinalize', ({ context }) => {
    console.log('finalized');
    context.finalize(true);
})
```
Drag Meeting 3 a bit to the top. Drop it onto Meeting 2. See it stays there.
<img width="1008" alt="Снимок экрана 2021-01-19 в 20 45 05" src="https://user-images.githubusercontent.com/57486733/105073247-dc72ba80-5a97-11eb-91fd-54cf4bd45f2a.png">

Same reproduced locally in module bundle
http://lh/bryntum-suite/scheduler/examples/layouts/index.module.html

In ES6 reproducible too, but not every drop hangs

**Comment by RhavoX** [comment]
I belive it might be related to event state changes during drag. I have noticed that when something changes data on the event (like the color) during drag it causes weird behavior.
