### ISSUE TITLE
`RowReorder` feature: Not possible to drop a row as a child of an empty parent node

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#227]
https://www.bryntum.com/forum/viewtopic.php?f=51&t=13191

![MoveRow](https://user-images.githubusercontent.com/218570/73072280-16c17000-3eb5-11ea-86fc-ee1f3151d999.gif)

**Comment by bmblb** [comment]
Also here: https://www.bryntum.com/forum/viewtopic.php?f=43&t=19851&p=98484#p98484
