### ISSUE TITLE
iPad: Vertical scroll not working

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#228]
Just 1 scroll gesture works. Try in scheduler big data set demo

https://www.bryntum.com/forum/viewtopic.php?f=44&t=13189

**Comment by abhisrinu** [comment]
Hi, @matsbryntse  
This bug is important for us to roll out the complete scheduler and is stopping us from adopting this.
Can we please prioritize this?

Abhi

**Comment by matsbryntse** [comment]
It's prioritized already as you can see, it's marked as high prio and part of the next patch release.

**Comment by jsakalos** [comment]
This can be related: https://github.com/bryntum/support/issues/263

I was able to get the following mess on iPad with the scrolling alone:

![494ED0AE-866F-4C3B-9E53-06F1F0E7A31D_1_105_c](https://user-images.githubusercontent.com/204844/74150270-d3cc0000-4c09-11ea-8234-9d66aa53b54d.jpeg)
