### ISSUE TITLE
Gantt should support disabling the calculation engine 

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2284]
To be strictly a tool for visualisation incoming data (clients may have their own backend calculation engine).

Requested here:
https://www.bryntum.com/forum/viewtopic.php?p=81889#p81889
https://www.bryntum.com/forum/viewtopic.php?p=87929#p87929

Should be possible to set project in visualization mode. In this mode data can be loaded as is. Project should be "dumb". No calculation should be performed by the Engine. All data modification is user's responsibility.

**Comment by ergagandeep** [comment]
@pmiklashevich Can you please when you build that for us? So we can start using the bryntum?

**Comment by matsbryntse** [comment]
We'll try to address this in the coming 2-3 patch releases

**Comment by vimalraj-a** [comment]
@arcady-zherdev and @pmiklashevich Can we expect this will be closed in couple of months?

FYI, We are waiting for this feature

**Comment by arcady-zherdev** [comment]
There is some progress on this ticket but it's far from completion.
I'll review the changes and try to give you here more details.

**Comment by yk92** [comment]
Can you please provide an update on when this is likely to be delivered. We really need this to be able to leverage your library.

**Comment by arcady-zherdev** [comment]
Realistically this won't be released in August considering the change state. So the closest possible ETA is September if nothing more critical pops up.

**Comment by yk92** [comment]
@arcady-zherdev Appreciate the reply. When will you guys know for sure if the September ETA will really happen?

**Comment by yk92** [comment]
@arcady-zherdev Do you guys have an ETA on when this feature will be delivered? any help would be greatly appreciated. Thanks!

**Comment by arcady-zherdev** [comment]
Sorry for not replying ..I've missed that completely somehow. We are still planning to release this feature in September.

**Comment by arcady-zherdev** [comment]
FYI we've added a new `setCalculations` method to `ProjectModel` class that allows to override fields calculation dynamically.
There is a new demo called `static` in the Gantt. It uses the method for loading "dirty" data as-is w/o recalculation.
The changes will be introduced in the next release so stay tuned.
