### ISSUE TITLE
React Components not being rendered within Scheduler cells when columns are sorted

### ISSUE THREAD

**Issue by ben-carmichael-dentsu** [bryntum/support#2285]
**Steps to reproduce:**

1. Open [React Simple Demo](https://www.bryntum.com/examples/scheduler/react/javascript/simple/build/index.html)
2. Sort any column
3. Notice React JSX and React Component cell content not being rendered

From my local testing of the Scheduler examples it seems this issue was introduced in version 4.0.4

OS: MacOS 10.15.7
Browser: Chrome Version 88

![image](https://user-images.githubusercontent.com/67103712/105819918-c2ae0780-5fb0-11eb-80c5-f550d7c42538.png)

**Comment by pmiklashevich** [comment]
Confirm the bug. The widget is there but it is set to display none. The problem is in the React Wrapper (releaseReactCell).
