### ISSUE TITLE
Add support for filtering a range for number / date column

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2289]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=16471&p=81924#p81924)

When you tab out of the field (less than or greater than) it removes the value from the other field 
e.g. in the age column https://www.bryntum.com/examples/grid/filtering/

So I can't put in a range of 30-50 ?

Its also a little confusing not putting in the smaller number first.

**Comment by jsakalos** [comment]
Also requested [here](https://www.bryntum.com/forum/viewtopic.php?p=91772#p91772) to include Date+Time range field/filtering support

**Comment by chuckn0rris** [comment]
Another request [here](https://www.bryntum.com/forum/viewtopic.php?f=43&t=20741&p=102845#p102845)

**Comment by taauntik** [comment]
Here is [another one](https://forum.bryntum.com/viewtopic.php?f=44&t=23020&p=113824#p113824)

**Comment by matsbryntse** [comment]
Supported now! https://www.bryntum.com/examples/grid/filtering/
