### ISSUE TITLE
Exception if unspecifiedTimeIsWorking set to false

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2291]
Reproducible in Gantt advanced example.

Set `"unspecifiedTimeIsWorking": false` for calendars in mock data (launch-saas.json). Reload the page.

An error occurred
```
Identifier.js:128 Uncaught (in promise) Error: Unknown identifier TaskEx-1000.$.assigned
    at throwUnknownIdentifier (Identifier.js:128)
    at EngineTransaction.get (Transaction.js:133)
    at EngineReplica.get (Graph.js:360)
    at TemplateClass.getFromGraph (ModelFieldAtom.js:56)
    at TaskEx.get (Entity.js:151)
    at TaskEx.get assignments (BaseHasAssignmentsMixin.js:16)
    at TaskEx.get assignments [as assignments] (TaskModel.js:782)
    at ResourceAssignmentColumn.getRawValue (Column.js:947)
    at Row.renderCell (Row.js:670)
    at Row.render (Row.js:567)
```

**Comment by bdow** [comment]
FWIW I am getting this same error when the `onLoad` response is immediately available. Bryntum Gantt v4.0.8. If I force it to sleep/wait for ~1 second before returning the `onLoad` response then I am able to have the data properly load. Thanks for looking into this, excited to see it resolved - currently blocks us from adopting v4.

**Comment by arcady-zherdev** [comment]
The ticket looks wrong to me. One cannot simply change [unspecifiedTimeIsWorking](https://bryntum.com/docs/gantt/#SchedulerPro/model/CalendarModel#field-unspecifiedTimeIsWorking)
without reviewing calendar intervals definition.
You either set all timeaxis as *working* by default and then your calendar specifies *non-working intervals* or vice-versa make all
timeaxis as *non-working* and the specify *working intervals*. Those configuration parameters should be done in sync.

The calendars used by the advanced demo  provide *non working intervals* and expect all rest periods to be working. So they require
[unspecifiedTimeIsWorking](https://bryntum.com/docs/gantt/#SchedulerPro/model/CalendarModel#field-unspecifiedTimeIsWorking) to be `true`.

```json
  "calendars" : {
    "rows" : [
      {
        "id"        : "general",
        "name"      : "General",
        "intervals" : [
          {
            "recurrentStartDate" : "on Sat at 0:00",
            "recurrentEndDate"   : "on Mon at 0:00",
            "isWorking"          : false
          }
        ],
        "expanded" : true,
        "children" : [
          {
            "id"           : "business",
            "name"         : "Business",
            "intervals"    : [
              {
                "recurrentStartDate" : "every weekday at 12:00",
                "recurrentEndDate"   : "every weekday at 13:00",
                "isWorking"          : false
              },
              {
                "recurrentStartDate" : "every weekday at 17:00",
                "recurrentEndDate"   : "every weekday at 08:00",
                "isWorking"          : false
              }
            ]
          },
          {
            "id"           : "night",
            "name"         : "Night shift",
            "intervals"    : [
              {
                "recurrentStartDate" : "every weekday at 6:00",
                "recurrentEndDate"   : "every weekday at 22:00",
                "isWorking"          : false
              }
            ]
          }
        ]
      }
    ]
  },
```

As I already wrote in the above snippet of the advanced demo dataset all intervals have [isWorking](https://bryntum.com/docs/gantt/#Gantt/model/CalendarIntervalModel#field-isWorking)  `false`.
And if you set [unspecifiedTimeIsWorking](https://bryntum.com/docs/gantt/#SchedulerPro/model/CalendarModel#field-unspecifiedTimeIsWorking) to `false` all the unspecified periods will also
be treated as non-working which makes the calendar 100% non-working ..which makes scheduling impossible. 

The engine actually rejects propagation is such cases:

```js
const result = await project.commitAsync()
if (result.rejectedWith) console.log(result.rejectedWith)
```
