### ISSUE TITLE
Number column does not accept key typed if it cell has same value

### ISSUE THREAD

**Issue by CarlosOsorioFF** [bryntum/support#2295]
I detected a weird behaviour when working with numeric columns and I'm not sure if this is the expected one. Steps to recreate:
1. Click on a numeric cell and press a number, for example 3.
2. Press Enter for finishing the editing.
3. Click again on the same numeric cell to edit it again.
4. Press 3 several times.
5. You only have one 3 number in the cell.

**Comment by matsbryntse** [comment]
Confirmed
