### ISSUE TITLE
Resizing to 0 width moves event slightly to the left

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#230]
Weird visual artefact when resizing right edge of event and go to 0 width.

Caused by padding-left:
```
.b-sch-event {
    display: flex;
    align-items: center;
    justify-content: flex-start;
    cursor: pointer;
    -moz-user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
    user-select: none;
    overflow: hidden;
    white-space: nowrap;
    flex: 1;
    width: 100%;
    text-align: left;
    padding-left: 0.75em;
```

**Comment by dongryphon** [comment]
Is simply setting `min-width: 0.75em` an acceptable solution?

**Comment by bmblb** [comment]
with `align-items: center` style set on event wrapper element resize doesn't move event anywhere but it is still impossible to resize it below left padding value.
do we want to allow that?

**Comment by isglass** [comment]
`min-width` is not acceptable, we need to be able to display narrow events. I propose `text-indent` instead of that padding

**Comment by pmiklashevich** [comment]
"text-indent" doesn't work good in case user applies a custom eventBodyTemplate and puts block elements in it

**Comment by isglass** [comment]
Events event structure was refactored on master, this no longer reproduces
