### ISSUE TITLE
Setting data to store.data property should add records similar store.add

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2301]
https://www.bryntum.com/forum/viewtopic.php?p=82001#p82001

Grid/examples/basic/app.js

```
import AjaxStore from '../../lib/Core/data/AjaxStore.js';
import GridRowModel from '../../lib/Grid/data/GridRowModel.js';

new Grid({
......
    store : new AjaxStore({
        modelClass : GridRowModel,
        createUrl  : 'test',
        data       : DataGenerator.generateData(50)
    })
});
```

http://lh/bryntum-suite/grid/examples/basic/

In console:

```
grid.store.data = []
grid.store.data = [{ name : 'Foo' }]
console.log(grid.store.added.count) // 0
grid.store.commit()
```
**See no requests sent**

```
grid.store.add([{ name : 'Foo2' }])
console.log(grid.store.added.count) // 1
grid.store.commit()
```
See only Foo2 is sent

**Comment by pmiklashevich** [comment]
The problem is the root cause of the: https://github.com/bryntum/support/issues/1968 (replaced `store.data` with `store.add` and `treeStore.data` with `treeStore.rootNode.appendChild` in importer).

**Comment by isglass** [comment]
Discussed with @arcady-zherdev, he will use another approach
