### ISSUE TITLE
Support eventColor in RGB format

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2314]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=16514&p=82150#p82150)

Hello friends,

I am having a little problem because in the data I have eventColor which accepts the rgb color code, but when running the project, the color of the task is in default color. Is there a way to get to the rgb color code or not.
![color2.png](https://www.bryntum.com/forum/download/file.php?id=12314)
![color1.png](https://www.bryntum.com/forum/download/file.php?id=12313)

**Comment by ExtAnimal** [comment]
Very simple addition:

`CalendarMixin`

```
if (color.startsWith('#')) {
```

Should be

```
if (color.startsWith('#') || color.startsWith('rgb`)) {
```
