### ISSUE TITLE
Time axis misrendered if changing scheduler element size

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2338]
https://www.bryntum.com/forum/viewtopic.php?f=51&t=15829&p=82405&hilit=2338#p82405

https://bryntum.com/examples/scheduler/partners/

in console:
`scheduler.element.style.width = '400px'`

Then scroll full right, and back to 0 horizontally.

<img width="418" alt="Screenshot 2021-02-04 at 13 52 43" src="https://user-images.githubusercontent.com/218570/106895273-4aea8600-66f0-11eb-8875-7e12f39867df.png">

**Comment by pmiklashevich** [comment]
Pushed test to `2338-update-header-from-horizontal-scroll`

**Comment by pmiklashevich** [comment]
Created a separate ticket for quick window expanding: https://github.com/bryntum/support/issues/2414
