### ISSUE TITLE
scrollToDate call increases date range period

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2365]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=16573&p=82595#p82595)

1. Open basic example
2. Check how many columns (hours) has been shown in visible date range (ex. 14)
3. run in console `scheduler.scrollToDate(new Date())`
4. check #2 again, it will be +1 (ex. 15)

Should be the same amount.

**Comment by isglass** [comment]
Not sure this is a bug, needs verifying. If you request it to scroll to a date not in range it will extend the range, that is the indented behaviour
