### ISSUE TITLE
Some cyclic dependencies for Successors incorrectly validated by TaskEditor

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2373]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=16630&p=82708#p82708)

Using the Basic Demo: https://www.bryntum.com/examples/gantt/basic/
Open the Edit Task modal for "Contact Designers"
In the Successors tab, add a new row and select "Configure ports". Click enter, note that the name column becomes blank. There are no errors.
Hit save.
Reopen the Task Edit modal
See that there is a `undefined` instead of the name.

**Comment by chuckn0rris** [comment]
Related with https://github.com/bryntum/support/issues/2342
Should be fixed after that one.

**Comment by fabiojpoli** [comment]
The problem is gone after fixed #2342, but there is another problem:
After run this issue description steps, close the form, when reopen, the valid successor "Create short list..." is gone from successors grid.
