### ISSUE TITLE
Add time ranges support to Calendar

### ISSUE THREAD

**Issue by isglass** [bryntum/support#2389]
To enable shading blocks of time, underneath the events

**Comment by chuckn0rris** [comment]
Requested here https://www.bryntum.com/forum/viewtopic.php?f=54&t=22040&p=109018#p109018

**Comment by jonek** [comment]
I submitted the request in the forum.

Our requirement is this:
- we know the availability for each resource on each day
- per default, grey out the whole day if there are no availabilities for any resource on that day
- exclude any time intervals from the grey mask (i.e. render interval as white/default background) in the day columns of the 'day', 'week', and 'resource' views, where a resource is available for that interval
- in views that combine availabilities for multiple resources (multiple resources are active in the resource filter), exclude any interval from the grey mask if that interval is available in any resource

Currently, only everything before the `start` and after the `end` of the [coreHours](https://bryntum.com/docs/calendar/api/Calendar/widget/DayView#config-coreHours) is marked grey and it the same `coreHours` interval is used for each day and each resource.

We could compute the combined availabilities for multiple resources ourselves.

**Comment by matsbryntse** [comment]
Supported in v5.3 https://bryntum.com/products/calendar-next/examples/timeranges/
