### ISSUE TITLE
New event changes color after mouse up

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2398]
Should use same background color for create proxy as the default calendar/resource
![color](https://user-images.githubusercontent.com/218570/108253182-c9680e80-7159-11eb-9fb7-94ce499c13ee.gif)

**Comment by fabiojpoli** [comment]
related: https://github.com/bryntum/support/issues/2340

**Comment by ExtAnimal** [comment]
It gets the [default resource](https://www.bryntum.com/docs/calendar/#Calendar/view/Calendar#property-defaultCalendar) allocated to it upon addition into the Store!

Which in the examples' data is "Bryntum Team", which has t is data: `{id: "bryntum", name: "Bryntum team", eventColor: "blue"}`. So it becomes blue.

**Comment by ExtAnimal** [comment]
Will be fixed when the PR for this is merged: https://github.com/bryntum/support/issues/2353

A View's `defaultCalendar` is taken into account when creating the drag proxy.
