### ISSUE TITLE
sync triggered after loading initial data

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2399]
http://lh/bryntum-suite/calendar/examples/basic/

Change demo app.js to:
```
crudManager : {
        transport : {
            load : {
                url : 'data/data.json'
            },
            sync : {
                url : 'data/sync.json'
            }
        },
        autoLoad : true,
        autoSync : true
    },
```
<img width="470" alt="Screenshot 2021-02-17 at 19 56 57" src="https://user-images.githubusercontent.com/218570/108253650-527f4580-715a-11eb-9713-b6026df51c60.png">

**Comment by isglass** [comment]
This is caused by Calendars project defaulting to not silence initial commit, because doing so breaks tests with the new faster approach in engine. Need to remove that setting again and solve by redrawing on initial project refresh/dataready or similar
