### ISSUE TITLE
Filter feature doesn't work correctly when filterFn is specified

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2421]
Steps to reproduce on advanced demo:
1. change duration column definition to this:
```
{
            type       : 'duration',
            filterable : {
                filterField : { type : 'durationfield' },
                filterFn    : ({ record, value, operator }) => {
                    console.log(operator);

                    switch (operator) {
                        case '<': return record.fullDuration < value;
                        case '>': return record.fullDuration > value;
                        case '=': return record.fullDuration.valueOf() === value.valueOf();
                    }
                }
            }
        }
```
2. run demo, right click duration cell of a leaf task, pick `more than` option
3. now click another cell and pick `less than` you'll see previous filter is applied with new value because filterFn is provided with first operator

**Comment by fabiojpoli** [comment]
Unable to reproduce. After applied second filter it applies correctly removing the previous filter.

**Comment by bmblb** [comment]
Not reproducible on latest release code
