### ISSUE TITLE
Demo styling issues

### ISSUE THREAD

**Issue by isglass** [bryntum/support#2437]
http://lh/bryntum-suite/SchedulerPro/examples/drag-from-grid/

Text should go below name

<img width="1168" alt="Screenshot 2021-02-24 at 09 45 56" src="https://user-images.githubusercontent.com/5415653/108973804-13cf1b00-7685-11eb-904b-0b65bef80e11.png">

http://lh/bryntum-suite/SchedulerPro/examples/drag-from-grid/
http://lh/bryntum-suite/SchedulerPro/examples/drag-batches/

Should not select text when dragging event in Safari

<img width="329" alt="Screenshot 2021-02-24 at 09 48 20" src="https://user-images.githubusercontent.com/5415653/108974176-804a1a00-7685-11eb-9e6e-4f8552ca37cb.png">

http://lh/bryntum-suite/SchedulerPro/examples/maps/

Maps demo toolbar issues

<img width="1425" alt="Screenshot 2021-02-24 at 10 03 16" src="https://user-images.githubusercontent.com/5415653/108976174-8ccf7200-7687-11eb-8121-c20542566580.png">

http://lh/bryntum-suite/SchedulerPro/examples/taskeditor/

Labels/fields not aligned

<img width="537" alt="Screenshot 2021-02-24 at 10 12 03" src="https://user-images.githubusercontent.com/5415653/108977332-b937be00-7688-11eb-9cd5-9fa4dec5c45d.png">

**Comment by bmblb** [comment]
`font size` text color is indistinguishable 
![image](https://user-images.githubusercontent.com/45400762/108978400-98786400-769a-11eb-9ed3-24c3b8d2509b.png)

**Comment by jsakalos** [comment]
Commit button too narrow for text. Demo: http://localhost/bryntum-suite/Grid/examples/transaction/
<img width="734" alt="Screen Shot 2021-02-24 at 10 36 31" src="https://user-images.githubusercontent.com/204844/108980843-69f38c80-768c-11eb-9f6c-34e600cdc431.png">

**Comment by isglass** [comment]
http://lh/bryntum-suite/Scheduler/examples/vertical/

<img width="1255" alt="Screenshot 2021-02-24 at 10 38 47" src="https://user-images.githubusercontent.com/5415653/108980875-74158b00-768c-11eb-9941-e826bc7e0e75.png">

**Comment by isglass** [comment]
http://lh/bryntum-suite/Scheduler/examples/rough/

Unintended green line above events

<img width="1076" alt="Screenshot 2021-02-24 at 10 43 41" src="https://user-images.githubusercontent.com/5415653/108981564-22213500-768d-11eb-8fec-b54cdd0b03c1.png">
