### ISSUE TITLE
Grid transaction demo: Combo is always disabled

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#2451]
Tested in FF 86@Mac OS Catalina,

<img width="734" alt="Screen Shot 2021-02-24 at 10 36 31" src="https://user-images.githubusercontent.com/204844/108981925-86dc8f80-768d-11eb-9cc1-64f596de23e9.png">

**Comment by ExtAnimal** [comment]
The Scheduler `UndoRedo` widget needs to be hoisted into Core.

It then needs to be able to seek a host in one of two ways. Either by finding an ancestor which is a `ProjectConsumer` (like a Scheduler or Gantt), or just finding an ancestor with a Store which has STM enabled.

Then we only ever have to get this correct once: In the `UndoRedo` widget

**Comment by ExtAnimal** [comment]
It doesn't work online either. Here I started the recorder, then deleted all records and added a new one. Still "No transactions":

![Screenshot 2021-02-24 at 10 55 27](https://user-images.githubusercontent.com/200516/108983119-6e1cab80-7686-11eb-8c34-6661005e3c49.png)

**Comment by canonic-epicure** [comment]
In the screenshot above  probably a "Stop" button haven't been pressed, thats why no transaction is created (its still in progress)

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/5d5d906a-3eb2-48df-a3f0-fe885e7a4801

**Comment by canonic-epicure** [comment]
Does not seem to be reproducible anymore.
