### ISSUE TITLE
Click on the sort icon in the header of ListView demo is ignored

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2455]
http://lh/bryntum-suite/calendar/examples/listview/
Sorting from context menu works.
<img width="1116" alt="Снимок экрана 2021-02-24 в 13 54 35" src="https://user-images.githubusercontent.com/57486733/108990768-5b1ad300-76a8-11eb-8f49-0ce269fa6a03.png">

**Comment by pmiklashevich** [comment]
Works good in similar view (Week grid) here: http://lh/bryntum-suite/calendar/examples/custom-rendering/

**Comment by ExtAnimal** [comment]
Closing as same issue as https://github.com/bryntum/support/issues/2454
