### ISSUE TITLE
Calendar + Scheduler demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2458]
- [x] Needs license info tooltip similar to https://www.bryntum.com/examples/scheduler/dragfromgrid/
- [ ] Import scheduler from online scheduler bundle
- [x] Time shown in scheduler events should not use ellipsis

<img width="347" alt="Screenshot 2021-02-24 at 16 03 14" src="https://user-images.githubusercontent.com/218570/109020015-d9cc3c00-76b9-11eb-9571-27df0baba417.png">

**Comment by dongryphon** [comment]
I'm not sure how to do the import from the online scheduler. The other two are addressed on the PR.
