### ISSUE TITLE
Support for drop down with grouped list

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2459]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=16734&p=83319#p83319)
https://www.bryntum.com/forum/viewtopic.php?f=51&t=17453&p=86600#p86600

Hello 

I need to implement the select list in the combo with two or multiple indentations levels.
I have followed the documentation for the select list from the below link.

Core.widget.Combo

But there is nothing mention for the multiple indentation level select list.

Want to make the list like this: https://prnt.sc/105ieti

Thanks
![image](https://user-images.githubusercontent.com/218570/109019028-e734f680-76b8-11eb-9f3a-043c7d6fadb9.png)

**Comment by ExtAnimal** [comment]
Probably the easiest way to enable this would be to allow the Combo to use a themed Grid as its picker with a simple config setting.

Probably a slim subclass of Grid, `PickerGrid` could be created which offers the services and API that the Combo uses.

then configuring the combo

```
{
    picker : {
        type : 'pickergrid'
    }
}
```

would work.

It would have `hideHeaders : true` by default and have its own `pickergrid.scss` file to make it look good. But it could perform the same function. 

Essentially its function is to select one or more records (putting that selection into a `Collection` which acts as the `valueCollection` for the Combo). It should fit in well.

This could then be used when a combo has a very large dataset. Such as in our API docs where the combo has a detectable lag.

**Comment by matsbryntse** [comment]
For multiple level grouping, Combo would need to be a PickerField + TreeGrid, see https://github.com/bryntum/support/issues/1298
