### ISSUE TITLE
WBS Number should update when outdenting task

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2464]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=16749&p=83389#p83389)

Hello,

When outdenting a task out of a summary task, the task goes out of the summary, but the WBS number is not updated.

For example, when outdenting the task 'Run tests' in https://www.bryntum.com/examples/gantt/advanced/, the WBS Number is 1.1.5. It should change to 1.2 and similarly the tasks below 'Run tests' must follow.

**Comment by jsakalos** [comment]
It does not revert on undo: https://www.bryntum.com/forum/viewtopic.php?f=52&t=16749&p=97078#p97078

![wbs-undo](https://user-images.githubusercontent.com/204844/143443014-8479ec13-6235-4bc8-9669-d771b9c0f5c6.gif)

**Comment by dongryphon** [comment]
I would classify this as a different bug (different steps to reproduce) but not a critical concern on that point. We'll need to get a new milestone assigned as well.
