### ISSUE TITLE
Normal grid cannot be expanded after restoring its collapsed state

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2478]
Steps to reproduce on advanced demo:
1. save state:
```
localStorage.setItem('state', JSON.stringify(gantt.state))
```
2. reload the page and load state:
```
gantt.state = JSON.parse(localStorage.getItem('state'))
```
3. see splitter has only `collapse` button and it is not resiable either
![image](https://user-images.githubusercontent.com/45400762/109680111-3b464c00-7b8d-11eb-857f-a15f1b43667f.png)

**Comment by bmblb** [comment]
Seems to be a regression after: #1857

**Comment by fabiojpoli** [comment]
> Seems to be a regression after: #1857

Reverting it doesn't fix the problem, so is not a regression.
