### ISSUE TITLE
TaskEditor should know when it edits a newly created task

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2487]
https://www.bryntum.com/forum/viewtopic.php?p=83712#p83712

Should be possible to display different tabs depending on the task: if it is new or not

One of the solutions is to pass `isEditingNewRecord` flag to `beforeTaskEdit` and `beforeTaskEditShow` events

**Comment by matsbryntse** [comment]
You can now use https://bryntum.com/docs/scheduler/api/Core/data/Model#property-isCreating to know when a record is being created.
