### ISSUE TITLE
Resizing events in scheduler broken when snapping is activated

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2507]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=16883&p=83931#p83931)

We want to report an issue regarding the resizing the events in the Bryntum scheduler. The issue is reproducible when the event is outside view and the snapping is activated.
The problem is that the event doesn't snap to the mouse position while dragging. 

We have recorded a gif with this issue using your Time resolution demo (https://www.bryntum.com/examples/scheduler/timeresolution/).

![bVsKee2ZRe.gif](https://www.bryntum.com/forum/download/file.php?id=12676)
![bVsKee2ZRe.gif](https://www.bryntum.com/forum/download/file.php?id=12676)

**Comment by ExtAnimal** [comment]
Fixed by https://github.com/bryntum/bryntum-suite/pull/3153
