### ISSUE TITLE
loadInlineData doesn't apply resourceTimeRanges data

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2516]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=16899&p=84006#p84006)

`scheduler.loadInlineData()` ignores `resourceTimeRanges`

**Comment by isglass** [comment]
By design it only applies data to the stores used by the engine, but agree it should handle resourceTimeRanges and timeRanges.

**Comment by matsbryntse** [comment]
Should be implemented already, please comment if still reproducible in latest version
