### ISSUE TITLE
Histogram summary should respect resource store filter

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2524]
https://www.bryntum.com/forum/viewtopic.php?p=84191#p84191

Scheduler/examples/histogramsummary/app.js
```
import '../../lib/Grid/feature/FilterBar.js';
new Scheduler({
    features   : {
        filterBar : true,
```

http://lh/bryntum-suite/scheduler/examples/histogramsummary/
Type something to the column input to filter resources. See summary bars do not exclude events assigned to filtered out resources from the result.
<img width="1094" alt="Снимок экрана 2021-03-18 в 14 21 23" src="https://user-images.githubusercontent.com/57486733/111618286-3cb27e00-87f5-11eb-82a5-e7ecc52dd3bf.png">

**Comment by matsbryntse** [comment]
Works fine for me
