### ISSUE TITLE
React JSX Column renderer buggy in grouping grid.

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#2531]
The issue is present in both 4.0.8 and 4.1.0-beta-2. Expanding and collapsing groups and deleting records need the logic to take existing HTML of portals and save them before grid rendering destroys them.

**Comment by bmblb** [comment]
I can see similiar issue when I sort react grid (react/javascript/performance-test): 
![image](https://user-images.githubusercontent.com/45400762/112142945-41f23d00-8be8-11eb-9da6-08aa45bc3d16.png)
