### ISSUE TITLE
Replace events data while filter applied caused a bug

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2540]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=16965&p=84357#p84357)

1. Open basic example
2. Save all events to some variable and change it a bit. in console:
```
evts = scheduler.events.map(e=>e.data);
evts.pop();
```
3. Apply filter using header context menu.
4. Set events to the scheduler:
```
scheduler.events = evts;
```
5. Clear filter

See that no extra data has been shown after filter removed, but it should.

**Comment by matsbryntse** [comment]
Not reproducible
