### ISSUE TITLE
Installation fails with newer npm version

### ISSUE THREAD

**Issue by isglass** [bryntum/support#2544]
I am using 7.5.3. They have changed how dependencies are installed, making it fail.

Can circumvent with `npm install --legacy-peer-deps`, but should not need to

**Comment by bmblb** [comment]
Does that have same cause as this one? https://github.com/bryntum/support/issues/2392

**Comment by SergeyMaltsev** [comment]
> Does that have same cause as this one? #2392

@bmblb no. This is different issue.
