### ISSUE TITLE
Resource histogram bars not redrawn on zoom in Angular/React/Vue

### ISSUE THREAD

**Issue by isglass** [bryntum/support#2545]
Works on vanilla demo, not in angulars resource-histogram demo

<img width="1300" alt="Screenshot 2021-03-23 at 10 51 56" src="https://user-images.githubusercontent.com/5415653/112127487-c7b0c100-8bc5-11eb-812a-52cb6428ae6b.png">

**Comment by bmblb** [comment]
Dupe of #2557
