### ISSUE TITLE
List is not updated when record id is modified

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2556]
Test case to reproduce on a grid basic demo (add to app.js):
```
const store = window.store = new Store({
    data : [
        { text : 'foo' },
        { text : 'bar' }
    ]
});

new List({
    appendTo : 'container',
    store
});

store.first.id = 1;
store.first.text = 'baz';

store.last.text = 'fizz';
```

expected : list having items baz and fizz
got : list having items foo and fizz

**Comment by isglass** [comment]
Probably list should always redraw on store changes?

**Comment by ExtAnimal** [comment]
> Probably list should always redraw on store changes?

It does. Of course.

It's just if the id is the change, the find of the DOM item to update fails because the id used is not present  in the DOM.

It just needs 

```
// If the id was the change, use the old value
refreshId = event.changed.id ? event.changes.id.oldValue : event.record.id

this.refreshItem(refreshId);
```

**Comment by fabiojpoli** [comment]
> > Probably list should always redraw on store changes?
> 
> It does. Of course.
> 
> It's just if the id is the change, the find of the DOM item to update fails because the id used is not present in the DOM.
> 
> It just needs
> 
> ```
> // If the id was the change, use the old value
> refreshId = event.changes.id ? event.changes.id.oldValue : event.record.id
> 
> this.refreshItem(refreshId);
> ```

This won't work because `refreshItem` get the index to sync the dom with `this.store.indexOf(record)` which will look to index 1 because our new id is 1, what is wrong record to work.
