### ISSUE TITLE
Runtime exception when calling drawDependency of Dependency feature

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2568]
https://www.bryntum.com/forum/viewtopic.php?p=84545#p84545

http://lh/bryntum-suite/scheduler/examples/dependencies/
Run:
`scheduler.features.dependencies.drawDependency(scheduler.dependencyStore.first)`
See error in console:
```
Dependencies.js:1097 Uncaught TypeError: Cannot read property 'from' of null
    at Dependencies.getDependencyBounds (Dependencies.js:1097)
    at Dependencies.drawDependency (Dependencies.js:1717)
    at <anonymous>:1:33
```
Looks like third argument (assignmentData) is required.

Think of making drawDependency private.

**Comment by isglass** [comment]
Was fixed as part of Dependency feature refactoring in 5.1
