### ISSUE TITLE
Grid scroll not working after store.add when store is filtered

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#2569]
Steps to reproduce:
1 - Open: https://www.bryntum.com/examples/grid/filtering/
2 - run: `grid.store.add({name: 'Peter'})`

Impossible to scroll down to see the last record added to grid.

**Comment by isglass** [comment]
The record does not match the filter, so it is filtered out. And thus cannot be scrolled to

**Comment by fabiojpoli** [comment]
After add the record the scroll stucks:

https://user-images.githubusercontent.com/663908/112485108-f0b18d00-8d50-11eb-83f8-bb4af1bb85c8.mp4

**Comment by matsbryntse** [comment]
Reproduced
