### ISSUE TITLE
Task not rendered correctly after drag drop

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#257]
http://lh/bryntum-suite/gantt/examples/progressline/
Drag task to far right
Scroll and drop it close to edge

<img width="511" alt="Screenshot 2020-02-03 at 21 55 03" src="https://user-images.githubusercontent.com/218570/73690069-dbeae380-46cf-11ea-85be-05abb07887a3.png">

**Comment by pmiklashevich** [comment]
Solved by this PR https://github.com/bryntum/bryntum-suite/pull/1072
