### ISSUE TITLE
Memory leak when replacing project instance

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2575]
https://www.bryntum.com/forum/viewtopic.php?p=84601#p84601
https://www.bryntum.com/forum/viewtopic.php?p=84602#p84602

http://lh/bryntum-suite/scheduler/examples/bigdataset/
Take a snapshot
<img width="1989" alt="Снимок экрана 2021-03-26 в 14 08 24" src="https://user-images.githubusercontent.com/57486733/112624121-3bf59980-8e3e-11eb-9843-9e1d3ff67ebf.png">

Click 10K and take a snapshot. See 11K in Memory
<img width="1986" alt="Снимок экрана 2021-03-26 в 14 10 05" src="https://user-images.githubusercontent.com/57486733/112624129-3ef08a00-8e3e-11eb-83c7-621009751da3.png">

Click about 10 times 5K and 10K. Take a snapshot. See all records are in memory.
<img width="1988" alt="Снимок экрана 2021-03-26 в 14 11 44" src="https://user-images.githubusercontent.com/57486733/112624126-3e57f380-8e3e-11eb-8733-0c9d1a12d844.png">

**Comment by matsbryntse** [comment]
Store link kept in record.unjoinedStores

After removing all data:
`unjoinedStores: [EventStore]`
