### ISSUE TITLE
Committing style is not removed after second drag

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2585]
http://lh/bryntum-suite/scheduler/examples/crudmanager/

Drag an event 2 times. See committing animation. Inspect event element. See `.b-sch-event.b-sch-committing::after` rule.

https://user-images.githubusercontent.com/57486733/113004283-2bb22700-917c-11eb-8149-899b2840a032.mov

**Comment by matsbryntse** [comment]
Duplicate
