### ISSUE TITLE
Unable to Drag from left corner of event when event time less than 15min

### ISSUE THREAD

**Issue by anjeshgoud** [bryntum/support#2586]
@matsbryntse 
 
our implementation Resize is disabled from the left side.
 ```
eventRenderer: ({ eventRecord, renderData }) => {


eventRecord.resizable = "end";
}
```

event time more than 15mins like 30min , 60mins its working for both side(left to right and right to left) , but we have issue with less time (below 15mins) some time unable drag from left to right side .

**Comment by anjeshgoud** [comment]
@matsbryntse  we are using schedulerpro-4.0.5

**Comment by matsbryntse** [comment]
Please try latest 4.1.0 beta where it likely works

**Comment by matsbryntse** [comment]
No info
