### ISSUE TITLE
Guide for customizing event edit feature

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2587]
https://bryntum.com/docs/scheduler-pro/

Just like seen here for Scheduler https://bryntum.com/docs/scheduler/#guides/customization/eventedit.md
and Gantt https://bryntum.com/docs/gantt/#guides/customization/taskedit.md

**Comment by pmiklashevich** [comment]
It's already there: https://bryntum.com/docs/scheduler-pro/#guides/schedulerpro/taskedit.md
