### ISSUE TITLE
Dependencies are not redrawn when replace resource which has no assignments

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2589]
http://lh/bryntum-suite/schedulerpro/examples/dependencies/
Run in console. See the dependency line stays on the screen.
```
scheduler.resourceStore.data = [{
                "id"   : 1,
                "name" : "Truck 1",
                "icon" : "b-fa-truck"
            }]
```
<img width="847" alt="Снимок экрана 2021-03-30 в 20 24 48" src="https://user-images.githubusercontent.com/57486733/113030182-fdd9dc00-9195-11eb-940f-481ed19e32be.png">

**Comment by fabiojpoli** [comment]
Seems fixed, could you please confirm @pmiklashevich ? Thanks
![Screen Shot 2021-06-10 at 7 50 32 AM](https://user-images.githubusercontent.com/663908/121520209-a9868000-c9c0-11eb-9bf2-27d4248dd692.png)

**Comment by pmiklashevich** [comment]
Not reproducible any more
