### ISSUE TITLE
Invalid type interface EventStoreMixin.getEvents()

### ISSUE THREAD

**Issue by kalkih** [bryntum/support#2591]
The type interface declaration seems to be invalid for `Scheduler.data.mixin.EventStoreMixin.getEvents()` ([docs](https://www.bryntum.com/docs/scheduler-pro/#Scheduler/data/mixin/EventStoreMixin#function-getEvents)).
Function should actually be able to take a option object as argument.

```js
// eventStore is of type SchedulerEventStore
eventStore.getEvents({
  resourceRecord,
  startDate: new Date("2000-01-01"),
  endDate: new Date("2100-01-01")
});
```

Lint error: Expected 0 arguments, but got 1.
![Screenshot 2021-03-31 at 12 39 07](https://user-images.githubusercontent.com/457678/113132241-7ab09880-921e-11eb-8b5e-068056548830.png)
Also invalid in the docs @ https://www.bryntum.com/docs/scheduler-pro/#Scheduler/data/mixin/EventStoreMixin#function-getEvents
The arguments are missing, but if you expand it you can read about the option argument.

![Screenshot 2021-03-31 at 12 40 21](https://user-images.githubusercontent.com/457678/113132164-6076ba80-921e-11eb-86c8-e23dfbbb2485.png)

Type casting the store to any as a temporary workaround.

**Comment by matsbryntse** [comment]
Already fixed in 4.1.0, please try latest beta.
