### ISSUE TITLE
Add support for showing type of return value from async functions

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2594]
Something like:
```
 * @returns {Promise(Boolean)}
```

**Comment by bmblb** [comment]
Typescript uses typings like this:
```
Promise<Boolean>
```

We need to implement this function because in `GanttBase` class we have number of methods which return type should be `Promise<Gantt.model.Task>`

**Comment by isglass** [comment]
We do support combining @returns with @async, should suffice. Also supported in typings, for example @async + @returns TaskModel -> `addSuccessor(taskRecord: TaskModel): Promise<TaskModel>;`
