### ISSUE TITLE
Drag and drop does not work some times for short tasks  less than 15 mins durations

### ISSUE THREAD

**Issue by anjeshgoud** [bryntum/support#2607]
@isglass 

This was determined to be a limitation where the tasks cannot be grabbed when task time short time (15 mins or less )
This is generally okay but some tasks which are around 15 minutes have very little “clickable” area to drag. that time we have issue.

**Comment by matsbryntse** [comment]
Please open forum threads with your test case and we will reply there. https://bryntum.com/forum
