### ISSUE TITLE
Make multiple feature showing demos for frameworks

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#2609]
Maintaining of growing amount small one-feature frameworks demos takes more and more time to build/test/release.

Suggestion is to leave one simple demo per framework which just shows how to use product in it and one or few complex ones which will show several features in one demo.

For client simplicity we can use separate code files for each demonstrated feature like:
```
src/
 lib/
   SearchFeature.ts
   GroupFeature.ts
   SortFeature.ts
   ...
```

Perfectly would be to have as less demos as we can per each framework.
Angular may have one for each Angular version but also less total amount which we have now.

**Comment by isglass** [comment]
Evaluate before going all in on this. Create it for a couple of demos
