### ISSUE TITLE
Focus reverts to body after drag drop to a new day column

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2611]
Run
```setInterval(()=> console.log(document.activeElement), 1000)```
Drag an event in week view to another day
Note focus jumps to body

Also investigate resize operation to ensure focus is kept where expected

**Comment by ExtAnimal** [comment]
Probably use 

```
document.addEventListener('focusin', function(e){console.log(e.target);}, true)
```

To monitor where focus is flying around to.

The DomSync to create the new event layout in the view removes the `activeElement`. Maybe the `doRefresh` could fix it ip.
