### ISSUE TITLE
Merge Crud manager guides

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2615]
Gantt should have one CrudManager guide describing only things relevant to Gantt

**Comment by bmblb** [comment]
@matsbryntse could you please elaborate on the problem? I see there are two crud-related guides in Gantt: *Crud Manager basics* and *Crud Manager in the Gantt*. First is a guide from scheduler which covers basic concepts, another one is more Gantt specific.
What do you suggest to do with them?

**Comment by canonic-epicure** [comment]
So it seems we indeed already have a "Crud manager in Gantt" guide with Gantt specifics, in addition to "Crud manager basics" (which is shared between the products). Closing this one as "already implemented".
