### ISSUE TITLE
Scrolling breaks after event resize

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#263]
Scroll far down
Resize an event
scroll up/down
Note craziness in scroller

http://lh/bryntum-suite/scheduler/examples/bigdataset/

https://www.bryntum.com/forum/viewtopic.php?f=51&t=13275

**Comment by jsakalos** [comment]
The situation is even worse than scroller behavior. The whole view breaks. To reproduce:

1. http://lh/bryntum-suite/scheduler/examples/bigdataset/
2. resize the first event
3. start to scroll

It doesn't seem to be influenced by focusing the first cell logic. If that part of code is commented out in `Grid/lib/Grid/view/mixin/GridNavigation.js:`
```
            else if (!me.skipFocusSelection && me.store.first) {
                // me.focusCell({
                //     id       : me.store.first.id,
                //     columnId : me.columns.visibleColumns[0].id
                // }, focusOptions);
            }
```
 the behavior is same.
![resize-scroll-bug](https://user-images.githubusercontent.com/204844/73931010-d7911700-48d7-11ea-8751-986b447952d3.gif)

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/608
