### ISSUE TITLE
Resource time zones are not exported correctly

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2646]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=51&t=17176

To reproduce add time range for every resource in the export demo and export it. You'll see this: 
![image](https://user-images.githubusercontent.com/45400762/114396352-27d3cb00-9ba6-11eb-8a36-d33990e79273.png)

**Comment by nagasain** [comment]
Can you please prioritize this, this is a blocker for us.

**Comment by matsbryntse** [comment]
It's already marked as the upcoming 4.1.2 release, fix should come soon to be downloaded from nightly builds if you need it before 4.1.2 GA.
