### ISSUE TITLE
Sticky events content positioning issue while scrolling

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2666]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=17212&p=85430#p85430)

Hi

I discovered that on a large dataset if you scroll down, scroll right and then scroll up again:
The content of the events is not always correctly positioned. It is only updated again if you move the horizontal scrollbar again.

![EaUtq3y7ZW.gif](https://www.bryntum.com/forum/download/file.php?id=12998)

Is this something that can be fixed?

Kind regards
jmeire
![EaUtq3y7ZW.gif](https://www.bryntum.com/forum/download/file.php?id=12998)

**Comment by bmblb** [comment]
Problem is still reproducible on the online demo. Enable the feature, scroll a bit horizontally to trigger event content positioning. Then scroll to the bottom and back to the top. You will see that after returning vertical scroll event content is not positioned properly, and if you scroll horizontally by 1px it will be put in place.
https://www.bryntum.com/forum/viewtopic.php?p=89290#p89290

**Comment by bmblb** [comment]
See Anderson and McGregor rows here: 

![image](https://user-images.githubusercontent.com/45400762/124620052-d031bc80-de81-11eb-8fce-393bdfb176fb.png)

after scroll:

![image](https://user-images.githubusercontent.com/45400762/124620103-dcb61500-de81-11eb-91c3-eec5bfebbcef.png)
