### ISSUE TITLE
Preserve endDate for "Manually scheduled" summary task

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#267]
Implement preserving `endDate` for `Manually scheduled` summary task the way it was implemented in ExtGantt

Requested here
https://www.bryntum.com/forum/viewtopic.php?f=52&t=13284

**Comment by PortNumber53** [comment]
any ETA on this?

**Comment by PortNumber53** [comment]
can this also be implemented for Gantt?

**Comment by matsbryntse** [comment]
It's already targeting Gantt yes, no ETA at this time. If you need this feature urgently, you can always sponsor the implementation. Details: https://www.bryntum.com/services
