### ISSUE TITLE
TaskEdit shows resource combo after reopen

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#269]
1. Open TaskEdit
2. Click Successors (or Predecessors)
3. Click Add
4. Click sorting on Name column
5. Select Task from dropdown list (It is invalid **BUG**)
6. Save Don't work (**BUG**)
7. Click Cancel
8. Reopen Dialog
9. Click Successors
10. Invalid Resource combo is still there  (**BUG**)

![TaskEditSucessor](https://user-images.githubusercontent.com/57486330/73927691-07eaac80-48fc-11ea-8e36-b877c590e975.gif)

**Comment by dongryphon** [comment]
Tried this on `release` branch and did not reproduce:

![269-task-edit-validation](https://user-images.githubusercontent.com/722969/74596619-62c88600-5017-11ea-91ff-2855330661c9.gif)

I am probably not doing something exactly the same? Is it possibly a chronograph issue? I may be a step behind on that submodule... I'll check that next.

**Comment by dongryphon** [comment]
Nope, that was up to date.
