### ISSUE TITLE
Resource Histogram is not updated when primary partner is zoomed or gets shifted

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2695]
https://www.bryntum.com/forum/viewtopic.php?p=85647#p85647

To reproduce:
SchedulerPro/examples/frameworks/react/javascript/resource-histogram
```
npm i
npm run start
```
Try in console:
```
bryntum.query('schedulerpro').zoomOut()
```
See weekends are not synced
```
bryntum.query('schedulerpro').shiftPrevious()
```
See histogram data is not shifted accordingly.

Note, shift problem is reproducible in Vanilla (SchedulerPro/examples/resourcehistogram), but non-working time is broken in react only.

Also note, the same problem appears in new Gantt/examples/frameworks/react/javascript/resource-histogram demo.

https://user-images.githubusercontent.com/57486733/115271967-8f5dbd80-a146-11eb-8083-5698b6cae265.mov

**Comment by isglass** [comment]
shiftPrevious() reproduces locally on react demo, not on vanilla version. zooming works

**Comment by isglass** [comment]
when partnering at runtime it reproduces also on vanilla demo
