### ISSUE TITLE
Crash when clicking time picker forward

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#27]
https://www.bryntum.com/examples/grid/celledit/

Choose Russian locale

Edit Time cell, click forward arrow
```

grid.module.js?436929:80 Uncaught TypeError: Cannot read property 'magnitude' of undefined
    at TimeField.onForwardClick (grid.module.js?436929:80)
    at FieldTrigger.onClick (grid.module.js?436929:21)
    at HTMLDivElement._0x117fc7 (grid.module.js?436929:12)
```

**Comment by ExtAnimal** [comment]
The configured `step` of `5m` doesn't parse in the Russian locale.

Configurations should be ingested in English. For times, that should always use canonical names.

DateHelper parsing should be configurable to do this, or there should be a subset of parsing methods which always use canonical names,.

**Comment by ExtAnimal** [comment]
The guts of `DateHelper.applyLocale` which calculates `me.durationRegEx` should be extracted to a method which returns the RegExp, and can do it for a passed set of unit names.

It can be then also be executed statically for the canonical unit names, and the resulting RegExp cached for parsing canonical units which is what should be done when ingesting configs.
