### ISSUE TITLE
Add capability to render custom elements into the Gantt chart timeline

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#270]
Requested at https://www.bryntum.com/forum/viewtopic.php?f=52&t=13293

As in Ext JS version: https://bryntum.com/examples/gantt-for-extjs/kitchensink/#examples/indicators

**Comment by PortNumber53** [comment]
any ETA/progress on this?

**Comment by matsbryntse** [comment]
Seems we missed to close this ticket when we added the feature, you can check it out here: https://bryntum.com/examples/gantt/indicators/
