### ISSUE TITLE
NPM auth with per-project .npmrc file and npm token support

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#2703]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=17269&p=85675#p85675)

Enable using of project's `.npmrc` file for authorization.

**Comment by krazibit** [comment]
This is critical for automated deployments please, tried copying the authToken from my machine after login, this worked for a few weeks until token expired thereby disrupting the whole deployment flow

**Comment by SrgTxi** [comment]
Hello, I'm with the same issue on project, any news about how to solve?
