### ISSUE TITLE
Support for showing tooltips on click

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2713]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=17273&p=85712#p85712)

Currently, the tooltip is shown when hover, I would like to show it on click as I can do with your calendar. Is there any solution or workaround for this?

**Comment by serbs** [comment]
This would be nice to have. Actually showOnHover = false did not work as well

**Comment by matsbryntse** [comment]
This works fine on latest:
```

 features : {
        eventTooltip : {
            showOnClick : true,
            showOnHover : false
        }
    },
```
