### ISSUE TITLE
CellEditor won't close properly after invalid search in combo list

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2724]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=17291&p=85788#p85788)

Copy this code to any grid example

```
const cityCombo = {
    type        : 'combo',
    multiSelect : true,
    items       : [],
    
};

const grid = new Grid({
    appendTo : 'container',

minHeight : '20em',

columns : [
    {
        text       : 'City',
        field      : 'city',
        flex       : 1,
        editor     : cityCombo,
        filterable : {
            filterField : cityCombo,
            filterFn    : ({ record, value }) => !value.length || value.includes(record.text),
        },
        renderer  : ({ record = ''}) => {
                        return record['city'] || 'N/A';
                    }
    },
    {
       text : 'test',
       field : 'test',
    },
],

data : [{city:"",test:"123"},{city:"",test:"12345"}]

});
```

Try to edit "City" field, type into the combo input something (any text) and click on any space except the input to finish editing.
Result: An editor won't close with red borders and it's not possible to close it except "Escape" key.
It is possible to finish editing in other scenarios.

**Comment by fabiojpoli** [comment]
After merge the fix, should set on column https://www.bryntum.com/docs/grid/#Grid/column/Column#config-invalidAction config as "allow" to work as expected.
