### ISSUE TITLE
Scheduler Pro ignores event calendars is scheduling

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2734]
Reported here: https://bryntum.com/forum/viewtopic.php?f=52&t=17295&p=85810#p85810
Steps to reproduce on weekends demo:
1. define calendar like this:
```
"calendars"          : {
        "rows" : [
            {
                "id"        : "weekends",
                "name"      : "Weekends",
                "unspecifiedTimeIsWorking": true,
                "intervals" : [
                    {
                        "recurrentStartDate" : "on Sat at 0:00",
                        "recurrentEndDate"   : "on Mon at 0:00",
                        "isWorking"          : false
                    }
                ],
                "expanded": true,
                "children": [
                    {
                        "id": "cal1",
                        "name": "cal1",
                        "unspecifiedTimeIsWorking": true,
                        "intervals": [
                            {
                                "startDate": "2021-12-18",
                                "endDate": "2021-12-20",
                                "isWorking": true
                            }
                        ]
                    }
                ]
            }
        ]
    }
```
2. adjust scheduler config:
```
startDate         : new Date(2021, 11, 1),
endDate           : new Date(2021, 11, 31),
```
3. create an event before working weekend and then resize/drop it to end on monday. see it skips working weekend. It appears to be ignoring event calendar and schedule events using project calendar always
This should last 3 days and end on saturday
![изображение](https://user-images.githubusercontent.com/45400762/115845286-5b75e700-a429-11eb-8097-17d13f815694.png)

**Comment by canonic-epicure** [comment]
PR with test in engine: https://github.com/bryntum/bryntum-suite/pull/3291

The reason was that resource was still inheriting the project calendar, remaining unavailable during that special weekend for event.

The solution is to assign a 24/7 calendar for resource
