### ISSUE TITLE
Bryntum bundle included twice

### ISSUE THREAD

**Issue by jashworth** [bryntum/support#2743]
Bryntum Gantt / 4.1.1

```
import { BryntumGantt } from "@bryntum/gantt-react";
import { GanttConfig, ProjectModel } from "@bryntum/gantt";
```

causes a runtime error

```
Bryntum bundle included twice, check cache-busters and file types (.js).
Simultaneous imports from "*.module.js" and "*.umd.js" bundles are not allowed.
```

The code is bundled twice because

files in|import
-|---------
@bryntum/gantt-react|gantt.umd.js

but

module|main entry
-|------------------
@bryntum/gantt|gantt.module.js

The docs explain [what to do about it](https://www.bryntum.com/docs/gantt/#guides/integration/react.md#troubleshooting) but why configure the modules in a way that leads to this error in the first place?

**Comment by SergeyMaltsev** [comment]
Hi!

We use `gantt.umd` in our Wrappers and demos.
It is stated here in guide https://www.bryntum.com/docs/gantt/#guides/integration/react.md#troubleshooting

Using module bundle is not yet supported with Wrappers.
We use umd for compatibility with old browsers like IE11 and Old Edge and plan to end their support after May, 1, 2021. 
Than we can rework wrappers to use module.

For now please just use these imports:
```
import { BryntumGantt } from "@bryntum/gantt-react";
import { GanttConfig, ProjectModel } from "@bryntum/gantt/gantt.umd.js";
```

Also please check our demos for sample code.
React demos are located in examples/frameworks/react folder inside distribution zip.

**Comment by jashworth** [comment]
So, for releases after 1 May, it'll possible to import directly from the packages?

```typescript
import { Gantt } from '@bryntum/gantt';
import { BryntumGantt } from '@bryntum/gantt-react';
```

**Comment by SergeyMaltsev** [comment]
You may check release changelogs for these changes.
Unfortunately I can't give you the exact version were this would be implemented yet.

**Comment by SergeyMaltsev** [comment]
Issue to fix this
https://github.com/bryntum/support/issues/2787
