### ISSUE TITLE
No type definitions for Bryntum Gantt React wrappers (or wrapped Gantt instance)

### ISSUE THREAD

**Issue by jashworth** [bryntum/support#2747]
Bryntum Gantt / 4.1.1

No type definitions are available for the Bryntum Gantt React wrappers because

```typescript
// index.d.ts
declare module "@bryntum/gantt-react";
```

It would great to see [this sort of commitment to TS](https://www.bryntum.com/blog/the-mixin-pattern-in-typescript-all-you-need-to-know/) applied to the React wrappers.

In particular, lack of type information means that [access to the Bryntum Gantt instance is untyped](https://www.bryntum.com/docs/gantt/#guides/integration/react.md#the-native-bryntum-gantt-instance)

![image](https://user-images.githubusercontent.com/4151375/115953153-989db000-a4e1-11eb-91f4-b09bd25c094f.png)

As a workaround,

```typescript
import { Gantt } from "@bryntum/gantt/gantt.umd.js";

interface BryntumGanttRef {
  instance: Gantt;
}

function App() {
  const ganttRef = React.useRef<BryntumGanttRef>(null!);

  React.useEffect(()=>{
    console.log(ganttRef.current.instance);
  },[])
  
  return <BryntumGantt ref={ganttRef} {...ganttConfig} />
}
```

provides a typed instance

![image](https://user-images.githubusercontent.com/4151375/115954003-6e022600-a4e6-11eb-809d-43ade846e0e8.png)

but is no substitute for full fidelity type information.

**Comment by isglass** [comment]
Wrapper & typings was improved in 5.0.3, issue: https://github.com/bryntum/support/issues/3378.

Closing this one as a duplicate
