### ISSUE TITLE
Cell editing not working in Predecessor grid of Task Editor

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2748]
http://lh/bryntum-suite/schedulerpro/tests/#features/TaskEdit.t.js

run 

`        scheduler = await t.getSchedulerProAsync();
`

add a few dependencies in predecessor tab, cannot finalize editing

<img width="355" alt="Screenshot 2021-04-24 at 11 24 37" src="https://user-images.githubusercontent.com/218570/115954146-a9edb900-a4ef-11eb-8114-5ba43b1d3fd9.png">

**Comment by fabiojpoli** [comment]
It is not allowing because is cyclic dependency. there are options when invalid value on editor: revert the change and close the editor, allow invalid value and commit, but I think both are not good because user won’t see the error message about cyclic.
