### ISSUE TITLE
PresetManager is exported only as a class, not a variable

### ISSUE THREAD

**Issue by jashworth** [bryntum/support#2752]
Bryntum Gantt / 4.1.1

`PresetManager` is exported only as a class, not a variable.

```typescript
// gantt.umd.d.ts
    export class PresetManager extends PresetStore {
        static deletePreset(id: string): void;
        static normalizePreset(presetOrId: string|object): ViewPreset;
        static registerPreset(id: string, config: object): ViewPreset;
    }
```

which means that when importing it

```typescript
import { PresetManager } from '@bryntum/gantt/gantt.umd.js';
```

only the static members are available (without casting), not instance members like `records`

![image](https://user-images.githubusercontent.com/4151375/115955717-38fad100-a4f0-11eb-85da-f44ccd33128c.png)

**Comment by matsbryntse** [comment]
Thanks a lot for great feedback / bug reports, much appreciated! We'll investigate!

**Comment by jashworth** [comment]
Thanks for the response, especially outside regular office hours.
