### ISSUE TITLE
Row height is not recalculated when collapsing group when using `collapseToHeader`

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2756]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=17315&p=85895#p85895)

Open [example](https://bryntum.com/examples/scheduler/groupsummary/)

See the height of the title row of the first group. Collapse first group, expand first group. See that height is bigger and wasn't updated properly.

**Comment by Nephyron** [comment]
This issue should be reopened, the bug is still present in version 4.2.0

**Comment by bmblb** [comment]
Still reproducible. Related forum post: https://www.bryntum.com/forum/viewtopic.php?f=44&t=18150&p=89839#p89839
