### ISSUE TITLE
STM reacts to changes rejected by engine

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2759]
Open advanced demo.
Drag Install Apache to the left, rejected by engine
Undo button is active now but nothing should have changed

<img width="895" alt="Screenshot 2021-04-26 at 18 05 02" src="https://user-images.githubusercontent.com/218570/116114759-f389ff80-a6b9-11eb-8604-c34a44ffeb32.png">

**Comment by canonic-epicure** [comment]
Duplicate of https://github.com/bryntum/support/issues/3309
