### ISSUE TITLE
Remove leading 0 in hour for US English locale

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2781]
9 AM
10 AM 
etc
<img width="194" alt="Screenshot 2021-04-28 at 15 15 45" src="https://user-images.githubusercontent.com/218570/116410281-e5acb980-a834-11eb-83b7-67441c075e3e.png">

**Comment by fabiojpoli** [comment]
How to reproduce? Tested on master, release and online and it is working (even after change language and back to english):
![Screen Shot 2021-04-30 at 8 53 32 PM](https://user-images.githubusercontent.com/663908/116766007-37e90880-a9f6-11eb-8343-e22b7fb33ede.png)
