### ISSUE TITLE
CellMenu not triggered on iPhone's with 3D touch enabled

### ISSUE THREAD

**Issue by TyLippe** [bryntum/support#2783]
Steps to reproduce

1) Open https://www.bryntum.com/examples/scheduler-pro/constraints/ on iPhone 6s/7/8 
2) Hold down on resource cell
3) Expectation: Cell Menu opens with 'Delete record' option

Cell Menu is not opening when an Apple device has the 3D touch feature turned on

**Comment by matsbryntse** [comment]
Thanks for reporting, we'll investigate!
