### ISSUE TITLE
Print feature

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2784]
Port Calendar's print feature to Widget, 
Dump content to iframe
enable autoHeight for Scheduler / Gantt
Call `window.print()`

https://www.bryntum.com/forum/viewtopic.php?p=86087#p86087

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=117205#p117205) user asking for this.

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?f=44&t=23802&p=117838#p117838) user asking for this.

**Comment by yakeer** [comment]
Hey @matsbryntse 
Is it really planned for 5.4.0?

We are looking for a solution for printing and we're trying to figure out how to make it happen.
If it's in the 5.4.0 milestone, we would wait for it and delay our customers' demands.

**Comment by matsbryntse** [comment]
Implemented in https://github.com/bryntum/support/issues/6218
