### ISSUE TITLE
Wrong event end date when using duration in days with decimal point

### ISSUE THREAD

**Issue by elelad** [bryntum/support#2785]
Bryntum scheduler. 

When using duration with a decimal point the end date Is wrong. 
Can be tested on the [basic demo](https://www.bryntum.com/examples/scheduler/basic/). 

For example, take the first event in the array: 

```
{
  id         : 1,
  resourceId : 'r1',
  startDate  : new Date(2017, 0, 1, 10),
  endDate    : new Date(2017, 0, 1, 12),
  name       : 'Click me',
  iconCls    : 'b-fa b-fa-mouse-pointer'
}
```

And change it to be:

```
{
  id         : 1,
  resourceId : 'r1',
  startDate  : new Date(2017, 0, 1, 0),
  duration   : 1.9993055555555554, // the result of - DateHelper.getDurationInUnit(new Date(2017, 0, 1, 0), new Date(2017, 0, 2, 23, 59), 'day')
  name       : 'Click me',
  iconCls    : 'b-fa b-fa-mouse-pointer'
}
```

The result is an incorrect event end date:

![image](https://user-images.githubusercontent.com/19483651/116528733-d8e79e80-a8e4-11eb-8d22-d59f60332cc4.png)

**Comment by matsbryntse** [comment]
durationUnit on the EventModel is 'd' by default so either include this in your events or subclass our EventModel and redefine defaultValue to 'h'

**Comment by elelad** [comment]
durationUnit of days is ok, this is what I want. 
But I want to see an event with a duration of almost 2 days and I'm getting an extra hour. 

![image](https://user-images.githubusercontent.com/19483651/116804369-d7a5b400-ab26-11eb-9f2c-847c96c7140a.png)
