### ISSUE TITLE
Milliseconds are not displayed correctly in Gantt headers

### ISSUE THREAD

**Issue by jashworth** [bryntum/support#2818]
Bryntum Gantt / 4.1.2

```typescript
PresetManager.add({
  id: "secondAndMinute-60x10ms",
  base: "secondAndMinute",
  headers: [
    { dateFormat: "llll", increment: 1, unit: "minute" },
    { dateFormat: "ss.SS", increment: 10, unit: "millisecond" },
  ],
  tickWidth: 60,
});
```

expected | 45.00 | 45.01 | 45.02
-|-|-|-
actual | 45.00 | 45.10 | 45.20

![image](https://user-images.githubusercontent.com/4151375/117111662-d9b67f80-ad7f-11eb-87ec-cc81d01965ed.png)

**Comment by pmiklashevich** [comment]
Confirmed. To reproduce go to gantt/examples/basic/ and edit app.js:
```
PresetManager.add({
    id      : 'secondAndMinute-60x10ms',
    base    : 'secondAndMinute',
    headers : [
        { dateFormat : 'llll', increment : 1, unit : 'minute' },
        {
            dateFormat : 'ss.SS',
            increment  : 10,
            unit       : 'millisecond',
            renderer   : function(start, end, headerConfig, index) {
                const value = DateHelper.format(start, 'ss.SS');
                console.log(start.getSeconds() + '.' + start.getMilliseconds().toString().padStart(3, '0'), value);
                return value;
            }
        }
    ],
    tickWidth : 60
});

new Gantt({
    viewPreset : 'secondAndMinute-60x10ms',
    startDate  : new Date(2021, 5, 8, 11, 45, 44, 980),
    endDate    : new Date(2021, 5, 8, 11, 45, 46),
```
<img width="1372" alt="Снимок экрана 2021-05-05 в 14 27 33" src="https://user-images.githubusercontent.com/57486733/117134570-69732280-adae-11eb-9f78-9a42a426ec21.png">

There is a problem in DateHelper.format.
`DateHelper.format(new Date(2018, 8, 4, 20, 30, 40, 50), 'SS')` returns "50" which means 500ms. Should return "05" which means 50ms.

**Comment by pmiklashevich** [comment]
@jashworth you can download the nightlies tomorrow to check the fix. It will be a part of 4.1.3 patch release. Cheers!
