### ISSUE TITLE
createSorterFn nested field value such as "departments.name"

### ISSUE THREAD

**Issue by david10sing** [bryntum/support#2830]
Hi,

I have columns which access nested field like so

```
{
    enableCellContextMenu: false,
    field: 'departments.name',
    hidden: true,
    minWidth: DEFAULT_COLUMN_WIDTH,
    text: 'Department',
    width: DEFAULT_COLUMN_WIDTH,
    // sortable(user1, user2) {
    //   return user1.departments?.name.toLowerCase() < user2.departments?.name.toLowerCase() ? -1 : 1;
    // },
  }
```

If I do not supply the sortable function, I can see that `createSorterFn` the nested fields path is not used. Please see screenshot.

![image](https://user-images.githubusercontent.com/6714127/117286784-a99fd700-ae7a-11eb-8ec2-a5ab866104e5.png)

Is it possible to check if there is a `.` in the `field` value? Or use `lodash.get(lhs, field)`?

**Comment by pmiklashevich** [comment]
@david10sing please use our forums for questions/bug reports. We will check your issues and open tickets if needed.
https://www.bryntum.com/forum/viewforum.php?f=44

Regarding this one, please define your record model fields explicitly. You can try how it work in basic demo:
Scheduler/examples/basic/app.js
```
import ResourceModel from '../../lib/Scheduler/model/ResourceModel.js';

const
    resources = [
        { id : 'r1', name : 'Mike', departments : { name : 'foo' } },
....

class MyResource extends ResourceModel {
    static get $name() {
        return 'MyResource';
    }

    static get fields() {
        return [
            { name : 'departmentName', dataSource : 'departments.name' }
        ];
    }
}

const scheduler = new Scheduler({
.....
    // resources        : resources,
    resourceStore : {
        modelClass : MyResource,
        data       : resources
    },
....
    columns : [
        { text : 'Name', field : 'name', width : 130 },
        {
            field : 'departmentName',
            text  : 'Department'
        }
    ]
```

https://www.bryntum.com/docs/scheduler/#Core/data/field/DataField#config-dataSource

**Comment by david10sing** [comment]
Well this is a workaround... But I don't understand why field from columns can navigate to 'departments.name' in the data and createSorterFn cannot...

Would you recommend to use a flat data structure with Bryntum's products? Would a flat data structure be better?
