### ISSUE TITLE
Core should not use b-fa for icon prefix

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2834]
Get rid of all `b-fa` usages in the core code (not examples). Icons should use special `b-icon` class.
![image](https://user-images.githubusercontent.com/45400762/117309723-5c783100-ae8b-11eb-8be6-cfe46ad273c9.png)

**Comment by isglass** [comment]
And b-icon icons should be named after "action", not fa icon. So those two would be `b-icon-first-page` and `b-icon-last-page`(or similar, perhaps more generic `b-icon-first`/ `b-icon-last`)
