### ISSUE TITLE
Shift by whole calendar month when shift unit is month

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#284]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=13266

The shift currently takes a number of days and shifts by that. There could be use cases when user wants to shift to the next/previous calendar month as a whole from 1st day to last day of the month.

This behavior could be configurable.

**Comment by SergeyMaltsev** [comment]
Also shiftNext() by a year on 29-2-2020 (leap year) ends up at 3-1-2021 and I would expect it to be 28-2-2021.
