### ISSUE TITLE
[NPM] Add minified bundles to npm packages

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#2842]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=17414&p=86407#p86407)

Consider adding minified API bundles to published npm packages.

**Comment by licjapodaca** [comment]
Any advance in this issue? ... because we need to implement some DevOps implementation with the Bryntum Gantt NPM package to deploy in our CDN.

Regards

**Comment by SergeyMaltsev** [comment]
This will be a part for next release version.

**Comment by licjapodaca** [comment]
Excellent, thanks...

**Comment by licjapodaca** [comment]
oh by the way ... please do the same with the new Bryntum Taskboard component please ...
