### ISSUE TITLE
weekStart not honored by date picker nor AgendaView

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#2850]
The reported issue is confirmed. Also, clicking next week/previous week shows week starting on Sunday again. Left picker does not honor weekStartDay either.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=17421&p=86450#p86450)

Hi,
I try on the demo :
https://www.bryntum.com/examples/calendar/bigdataset/
I have add this :

```
const calendar = new Calendar({
    ...
    weekStartDay: 1,
    modes : {
        agenda: {
            range: 'week',
            weekStartDay: 1,
        }
    }
    ...
}

```

It's ok on week view but on agenda view, week start with Sunday instead of Monday.

**Comment by ExtAnimal** [comment]
How would "work" be defined?

`AgendaView` doesn't divide time into weeks. It's just a list of days on which events occur.

**Comment by ExtAnimal** [comment]
However, Calendar's `weekStartDay` should definitely be propagated to `this.widgetMap.datePicker`. That's a simple fix.

**Comment by ExtAnimal** [comment]
OK, I get it. `updateRange` has to snap the `date` to the start day of the range, whatever that may be: `'week'`, `'month'`, `'year'` or `'decade'`...

**Comment by ExtAnimal** [comment]
It does try to do that. But `DateHelper` uses the **_locale's_** `weekStartDay` in its calculation. So this is a localization issue. The Calendar is operating "out of locale", the DateHelper is doing what *it* thinks is right. 

Maybe we need a special mode for `DateHelper` to temporarily force its `weekStartDay` value.

**Comment by jsakalos** [comment]
Couldn't it be implemented by changing `DateHelper` `weekStartDay` temporarily to the calendar's one, calculate everything, and change it back?

**Comment by ExtAnimal** [comment]
Yes, the issue os the `DateHelper` has its own ideas. It always uses the locale's `weekStartDay`, or zero.

It should be possible to *set* `DateHelper`'s `weekStartDay`

**Comment by arcady-zherdev** [comment]
I think `weekStartDay` provided on the component level should win. Locale provided value should be treated as default.

**Comment by ExtAnimal** [comment]
It's not honoured by any UI widgets. `DateHelper` has entirely its own idea which is taken from the locale.

If any one view needs this set, it must be set in `DateHelper`. There must be a way to tell `DateHelper` to use a day  number.
