### ISSUE TITLE
AjaxHelper.fetch should support using body parameters for non-GET requests.

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#2855]
`AjaxHelper.fetch` should support using body for query parameters for POST requests.

For `application/x-www-form-urlencoded` content-type queryParams could go to the request body like this:
```
param1=qwe&param2=foo&q=...
```

Requested in this ticket: https://github.com/bryntum/support/issues/541

**Comment by isglass** [comment]
Opt in, change to being the default in 5.0

**Comment by arcady-zherdev** [comment]
As a workaround one can override project `encode` method.
The method can return a `FormData` or `URLSearchParams` instance which coupled w/ using of POST method produces different results:
```js
class MyProject extends ProjectModel {

    encode(packet) {
        let result = super.encode(packet);

        // for load requests send URLSearchParams instance in request body
        if (packet === 'load') {
            const body = new URLSearchParams();
            // const body = new FormData();

            // pass encoded JSON in "q" form data param
            body.set('q', result);

            result = body;
        }

        return result;
    }

}

// use overridden class by the Gantt
const gantt = new Gantt({

    projectModelClass : MyProject,

    project : {
        transport : {
            load : {
                method : 'POST',
...
```

Try switching between `FormData` and `URLSearchParams` in the above code to see what fits better.
