### ISSUE TITLE
Event Adds Without Event Editor Prompt if month cell has many events

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2896]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=17538&p=86933#p86933)

Hi,

When adding events to the calendar from the month view, when a particular day is full of events and you double click to add a new one, it is added without a prompt from the Event Editor as the count on the day goes up and default values are set.

This can be reproduced on any of the demos hosted here. Just double click and add appointments to a day until the day is full and it will start to add them without a prompt eventually.

Thank you.

**Comment by bmblb** [comment]
Note: calendar should also have sort of min height, to always show some reasonable amount of events visible. 2-3 I suppose?
