### ISSUE TITLE
BryntumWidgetAdapterRegister should be public to use from frameworks

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#29]
Requested here
https://www.bryntum.com/forum/viewtopic.php?f=51&t=12676

BryntumWidgetAdapterRegister is marked as `@private` so it is not exported to typing wrappers.

Should export code like this

```
    export class BryntumWidgetAdapterRegister {
        static register(type: string, widgetClass: any): void;
        ...
    }
```

**Comment by isglass** [comment]
Removed in 4.0
