### ISSUE TITLE
Should be possible to configure AjaxStore to use different request methods for reading and saving

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#291]
Requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=13350

User wants to use PUT for saving.

Setting method in https://www.bryntum.com/docs/scheduler/#Core/data/AjaxStore#config-fetchOptions config changes method for both reading and saving data.
```
new Scheduler({
    eventStore : {
        fetchOptions : {
            method : 'PUT'
        },
```

See AjaxStore where AjaxHelper.post and AjaxHelper.get are used. fetchOptions is merged to both config options.

**Comment by matsbryntse** [comment]
Duplicate
