### ISSUE TITLE
Update record value should trigger UI field update

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2920]
Define a basic container with some fields and a record.
```
container = new Container({
            autoUpdateRecord : true,
            record : {
                name : 'Brad',
                surname : 'Pitt',
            }
            items : {
                nameField  : {
                    name : 'name',
                    type : 'text'
                },
                surnameField : {
                    name : 'surname',
                    type : 'text'
                },
```
If we change values through UI, the record values will be updated accordingly. But if we change record's field value, it will not initiate UI field value update. 
It needs to be implemented. 

See `Container.js` file. It has `onFieldChange` with `userAction` check, that should be changed. 
Cover by tests and check that it won't broke the existed logic. See `isolateFields` flag and `TaskEditorBase.js` (it has an override for `onFieldChange` to make it work for task editor) for some details.

**Comment by matsbryntse** [comment]
We now support autoUpdateFields
