### ISSUE TITLE
Wrong type declaration for registerFeature method

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2934]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=52&t=17588&p=87230#p87230

Problem: registerFeature is defined like this:
```
static registerFeature(featureClass: InstancePlugin, onByDefault?: boolean, forType?: string|string[]): void;
```
According to the type, it accepts instance of the InstancePlugin. But in fact it accepts smth of InstancePlugin type. Probably `typeof InstancePlugin`

**Comment by bmblb** [comment]
TS snippet:
https://www.typescriptlang.org/play?#code/MYGwhgzhAEDKD2BbAptA3gKGt6AHATvLtAFzQB2ArogEbL7QC80AjBgL4YaiQwBCYBsgAeAF2TkAJjAQp0nbvHIRR0ME2gAKQQHNS0UQE9cyeADM4SZAEomAPmhmwICMi5hNaPIWJkATNDs1hgeXmbw8PoBQSGasjaxAvjWQA

**Comment by matsbryntse** [comment]
Fixed in release already.

`     * @param {Function} featureClass The feature class constructor to register
`

**Comment by bmblb** [comment]
@matsbryntse not just a regular function, subclass of `InstancePlugin`. so `{Function}` is incorrect, it has to be `typeof InstancePlugin`, but only in typings. IIRC there is a special tag to define how documented symbol gets its typing @SergeyMaltsev as that correct?

**Comment by SergeyMaltsev** [comment]
@bmblb there's no type replace tags for `@param` for typings currently. 
We have `@typings` tag for return type for configs and properties yet.

Also no support for `type of` construction.
