### ISSUE TITLE
Color picker field

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2939]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=17612&p=87280#p87280)

Need to design color picker with dropdown options in custom UI. Need some guidance on implementation process
![Screenshot from 2021-05-27 10-13-49.png](https://www.bryntum.com/forum/download/file.php?id=13348)

**Comment by andersondaniel1980** [comment]
This would be very useful for the component, do you have any release forecast?

**Comment by annheslin** [comment]
This is something we'd love to have as well for our Calendar and Grid implementations. Is there a release forecast?

**Comment by amarsitetracker** [comment]
This would be an awesome feature, and we will use it for our scheduler pro. Any plan to move this in development and release?

**Comment by matsbryntse** [comment]
We should have this wrapped up, with a little luck it's coming in 5.4!

**Comment by JockeLindberg** [comment]
Actually, a lot of progress has already been made in another ticket that will also include a ColorField with a drop-down picker. Will update this issue as a part of that work.
