### ISSUE TITLE
Scheduling Engine should be isomorphic and not access browser globals

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#294]
Scheduling Engine should work for backend and frontend.

We have bunch of window & document references in extended grid classes

Also needs cleanup in shared classes (Common)

Requested here:
https://www.bryntum.com/forum/viewtopic.php?f=52&t=11011
https://www.bryntum.com/forum/viewtopic.php?f=52&t=13714

`npx siesta ./tests in scheduling engine folder
`

**Comment by SamuraiJack** [comment]
The command to run the suite in Node is actually: `node tests/index.js` See this comment as well: https://github.com/bryntum/bryntum-suite/pull/1108#issuecomment-629135974
