### ISSUE TITLE
transformFlatData not compatible with syncDataOnLoad in a tree store

### ISSUE THREAD

**Issue by eangelov** [bryntum/support#2944]
I am not sure if this is a bug or if i'm using syncDataOnLoad on a tree grid in a way that it is not intended to use.

Summary: Render a tree grid with data. Once it is rendered set the store data to an empty array after that set it to array that has data and the flat data is not transformed to a tree.

Component version: Bryntum Grid 4.1.4

Test Case:
`<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		
		<link rel="stylesheet" href="./bryntum-grid-4.1.4/build/grid.material.min.css" id="bryntum-theme">
		<link rel="stylesheet" href="./bryntum-grid-4.1.4/examples/_shared/shared.css">
	</head>
	<body>
		<script data-default-locale="En" src="./bryntum-grid-4.1.4/build/grid.umd.js"></script>
		
		
		<div id="container"></div>
		<script>
			const grid = new bryntum.grid.TreeGrid({
				appendTo: 'container'

				, columns: [{
					"text": "Target"
					, "field": "Target"
					, "type": "tree"
					, "editor": false
					, "htmlEncode": false
					, "width": 200
				}]

				, store: {
					transformFlatData: true,
					syncDataOnLoad: true,
					tree: true,
					data: [
						{
							"id": "1"
							, "expanded": true

							, "Target": "Item 1"
						}, {
							"id": "2"
							, "parentId": "1"
							, "expanded": true

							, "Target": "Item 2"
						}
					]
				}

				, tbar: [
					{ 
						text : 'Load Data'
						, onClick: () => {
							grid.store.data = [];

							grid.store.data = [
								{
									"id": "3"
									, "expanded": true

									, "Target": "Item 3_1"
								}, {
									"id": "4"
									, "parentId": "3"
									, "expanded": true

									, "Target": "Item 3_2"
								}
							];
						}
					}
				]
			});
		</script>
	</body>
</html>`

Steps to reproduce: Once the tree grid is rendered press the "Load Data" button. The loaded flat data is not transformed into a tree.

Expected Result: After pressing the "Load Data" button the data should be transformed into a tree.

What happens: After pressing the "Load Data" button the loaded data remains flat.

Debug info: From what i see there are no errors in the console and if i execute
```
grid.store.data = [];
grid.store.data = [
	{
		'id': '3'
		, 'expanded': true

		, 'Target': 'Item 3_1'
	}, {
		'id': '4'
		, 'parentId': '3'
		, 'expanded': true

		, 'Target': 'Item 3_2'
	}
];
grid.store.data = [
	{
		'id': '3'
		, 'expanded': true

		, 'Target': 'Item 3_1'
	}, {
		'id': '4'
		, 'parentId': '3'
		, 'expanded': true

		, 'Target': 'Item 3_2'
	}
];
```

instead of 

```
grid.store.data = [];
grid.store.data = [
	{
		'id': '3'
		, 'expanded': true

		, 'Target': 'Item 3_1'
	}, {
		'id': '4'
		, 'parentId': '3'
		, 'expanded': true

		, 'Target': 'Item 3_2'
	}
];
```

the flat data is transformed into a tree. From what i can see it looks like the problem is only if you set the data to an empty array and after data you set it to a new dataset.

**Comment by jsakalos** [comment]
Confirmed, this is a bug. I have reproduced it in our Grid/examples/tree by setting the store to:
```
store : {
    transformFlatData : true,
    syncDataOnLoad    : true,
    tree              : true,
    data              : [
        {
            id       : '1',
            expanded : true,
            name     : 'Item 1'
        }, {
            id       : '2',
            parentId : '1',
            expanded : true,
            name     : 'Item 2'
        }
    ]
},
```
and then in console:
```
grid.store.data = [];
grid.store.data = [
        {
            id       : '1',
            expanded : true,
            name     : 'Item 1'
        }, {
            id       : '2',
            parentId : '1',
            expanded : true,
            name     : 'Item 2'
        }
    ]
```

The result is:

<img width="481" alt="Screen Shot 2021-05-28 at 10 14 29" src="https://user-images.githubusercontent.com/204844/119952664-8d84e680-bf9d-11eb-9f01-818823d6f7ba.png">

When `syncDataOnLoad: false` (or removed) the same procedure leads to the expected result of:

<img width="484" alt="Screen Shot 2021-05-28 at 10 16 11" src="https://user-images.githubusercontent.com/204844/119952924-c45afc80-bf9d-11eb-8a51-56312170bb8d.png">

**Comment by eangelov** [comment]
Some more debug info. The same happens if you start with an empty store and then load a flat dataset.

Example:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		
		<link rel="stylesheet" href="./bryntum-grid-4.1.4/build/grid.material.min.css" id="bryntum-theme">
		<link rel="stylesheet" href="./bryntum-grid-4.1.4/examples/_shared/shared.css">
	</head>
	<body>
		<script data-default-locale="En" src="./bryntum-grid-4.1.4/build/grid.umd.js"></script>
		
		
		<div id="container"></div>
		<script>
			const grid = new bryntum.grid.TreeGrid({
				appendTo: 'container'

				, columns: [{
					"text": "Target"
					, "field": "Target"
					, "type": "tree"
					, "editor": false
					, "htmlEncode": false
					, "width": 200
				}]

				, store: {
					transformFlatData: true,
					syncDataOnLoad: true,
					tree: true,
					data: []
				}

				, tbar: [
					{ 
						text : 'Load Data'
						, onClick: () => {
							grid.store.data = [
								{
									"id": "3"
									, "expanded": true

									, "Target": "Item 3_1"
								}, {
									"id": "4"
									, "parentId": "3"
									, "expanded": true

									, "Target": "Item 3_2"
								}
							];
						}
					}
				]
			});
		</script>
	</body>
</html>
```

![image](https://user-images.githubusercontent.com/3601104/119958877-1efb5500-bfac-11eb-8e15-231d0e6e662c.png)

**Comment by jsakalos** [comment]
Also reported here: https://www.bryntum.com/forum/viewtopic.php?p=90275#p90275

**Comment by jsakalos** [comment]
The related, but very important issue is that the store does not fire the correct events when this flag is on. Only `update` is fired correctly. To test, the attached simple application can be used. Make sure that the flag is on and then remove and add records and observe the console log.
[app1.zip](https://github.com/bryntum/support/files/7640107/app1.zip)
