### ISSUE TITLE
Improve "Creating a custom theme" guide

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2966]
https://www.bryntum.com/forum/viewtopic.php?p=87555#p87555
https://www.bryntum.com/forum/viewtopic.php?f=52&t=17714

Need to show how to extend one of our default themes and provide new values to variables and override rules. The closest solution is shown in Scheduler:
Scheduler/examples/theme/resources/custom.scss

Update guides:
https://www.bryntum.com/docs/grid/#Grid/guides/customization/styling.md#creating-a-theme
https://www.bryntum.com/docs/scheduler/#Scheduler/guides/customization/styling.md#creating-a-custom-theme
https://www.bryntum.com/docs/gantt/#Gantt/guides/customization/rendering_and_styling.md#creating-a-theme (fix the demo to extend one of our default themes)
https://www.bryntum.com/docs/calendar/#Calendar/guides/customization/styling.md#creating-a-custom-theme (add a demo)

**Comment by SergeyMaltsev** [comment]
Guides were updated in `5.6.9`
