### ISSUE TITLE
Events are not rendered if scheduler.setTimeSpan is used before setting assignments

### ISSUE THREAD

**Issue by eangelov** [bryntum/support#2968]
To reproduce, edit SchedulerPro/examples/constraints/app.js
```
const scheduler = new SchedulerPro({
    tbar : [{
        type : 'button',
        text : 'Reload data',
        async onClick() {
            const
                events     = [{
                    id        : 99,
                    startDate : new Date(2021, 3, 12, 10),
                    endDate   : new Date(2021, 3, 12, 12),
                    name      : 'Foo',
                    iconCls   : 'b-fa b-fa-users'
                }],
                assigments = [
                    { id : 100, resourceId : 1, eventId : 99 }
                ];

            await scheduler.eventStore.loadDataAsync(events);

            scheduler.setTimeSpan(
                new Date(2021, 3, 12),
                new Date(2021, 3, 13)
            );

            await scheduler.assignmentStore.loadDataAsync(assigments);
        }
    }],
```
Click "Reload data". See the event is NOT shown.
Check
`scheduler.eventStore.last.isScheduled` // true
`scheduler.eventStore.last.isAssignedTo(scheduler.resourceStore.first)` // true
So the event has to be shown.
Click "Reload data" again OR run `scheduler.refreshRows()`. See the event is shown.

Note,
it doesn't work in this order too:
```
scheduler.setTimeSpan(
    new Date(2021, 3, 12),
    new Date(2021, 3, 13)
);

await scheduler.eventStore.loadDataAsync(events);
await scheduler.assignmentStore.loadDataAsync(assigments);
```
but works using project.loadInlineData
```
scheduler.setTimeSpan(
    new Date(2021, 3, 12),
    new Date(2021, 3, 13)
);

await scheduler.project.loadInlineData({
    eventsData      : events,
    assignmentsData : assigments
});
```
and works if setTimeSpan is called after the data is set
```
await scheduler.eventStore.loadDataAsync(events);
await scheduler.assignmentStore.loadDataAsync(assigments);

scheduler.setTimeSpan(
    new Date(2021, 3, 12),
    new Date(2021, 3, 13)
);
```

**Comment by pmiklashevich** [comment]
@eangelov please use [project.loadInlineData](https://www.bryntum.com/docs/scheduler-pro/#SchedulerPro/model/ProjectModel#function-loadInlineData) meanwhile to load events and assignments together

**Comment by eangelov** [comment]
Using project.loadInlineData is not always possible since there are scenarios where changes to "events"/"assignments" are pushed to the client from different sources at different intervals, meaning that you can receive only for 1 and have some time pass until the changes for the other are received. A workaround for the moment is when finding the new start/end date to skips events that have missing assignment and call the recalculation for start/end date in each handler.

**Comment by matsbryntse** [comment]
Seems to work fine now in latest release, @eangelov can you please confirm?
