### ISSUE TITLE
Split task feature

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2975]
https://www.bryntum.com/forum/viewtopic.php?f=52&t=17694&p=87680#p87680

**Comment by christos-ts** [comment]
Hi, is this going to be available in the 5.2 version ?

**Comment by arcady-zherdev** [comment]
Yes we target v5.2.0 release for the feature.

**Comment by christos-ts** [comment]
This is great news! Many thanks, looking forward to it
