### ISSUE TITLE
Make rendering of columnLines to foreground/background configurable

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#2976]
+ b-sch-nonworkingtime-canvas

Requested here:

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=17688&p=87656#p87656)

Hello!

Is it possible to config the schedulerPro so that columnLines overlap resourceTimeRanges and timeRanges but not the events?

Default it look like the columnLines parent div and the parentDiv for the TRs, RTRs and events each have z-index set meaning I can with some simple css fix, have column lines ontop or not. But is there a config to resolve this dom-hierarchy so that I can configure z-index on columnLines in relation to events, TRs, RTRs (siblings) outside of the parents

Any ideas?

**Comment by jsakalos** [comment]
Comments:
@isglass : Column lines would have to move to the foreground canvas for that to be possible. It would then always be in front of rows. I suppose it could be configurable which canvas it renders to.

@matsbryntse : Maybe more reasonable to move background’y (non-touchable things) like time ranges, resources time ranges to background canvas?

**Comment by nagasain** [comment]
Request to prioritize this fix.
[https://www.bryntum.com/forum/viewtopic.php?f=51&t=18115](url)

**Comment by abhisrinu** [comment]
Hi, 
I am coming from [here](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18115&p=89732#p89732).
When are we targetting this to? This is a blocker for us to achieve our UX.

Thanks,
Abhi

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?f=51&t=23552&p=116596#p116596

**Comment by matsbryntse** [comment]
Initial progress in https://github.com/bryntum/bryntum-suite/pull/7536

**Comment by matsbryntse** [comment]
Resolved recently and available in official release

**Comment by emmalyngrace23** [comment]
What version will this feature be available?

**Comment by isglass** [comment]
Hi @emmalyngrace23,

In version 6 (currently available as an alpha version) ResourceTimeRanges has been separated from event bars, making it possible to change the z order of ResourceTimeRange, TimeRanges, events and column lines per type
