### ISSUE TITLE
When event is selected view scrolls to the last resized event

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2978]
Steps to reproduce on the basic demo:
1. switch to the day view on 04.10.2020
2. drag create two events, 8-10 16-18
3. call `calendar.activeView.hourHeight = 80`
4. resize first event to be 8-12
5. scroll down the view and click 2nd event -> view is scrolled to the first event

**Comment by bmblb** [comment]
Problem is that mousedown/mouseup listeners create drag context and always think there was a drag. There should be version of `abort()` which handles not started drag, which just removes CSS and doesn't change the view

**Comment by bmblb** [comment]
Another face of the same problem. After resizing the event focus always moves to it on click. Because drag feature thinks we stopped dragging and is trying to restore the focus. But we didn't drag, we just clicked.

https://user-images.githubusercontent.com/45400762/120777652-30a1a700-c52e-11eb-9ec6-072c84e312d8.mov

**Comment by dongryphon** [comment]
I see the milestone is set to 4.2.x, is this not happening in `release` branch?

**Comment by bmblb** [comment]
It does. Video is recorded with online demo which uses release branch

**Comment by dongryphon** [comment]
Does the focus change between the down and up so that the restore is moving it? Or is the restore only having scroll effects w/o actually changing the focus? If you're not sure, I'll find out when I get in to it

**Comment by dongryphon** [comment]
I think I see - the down/up cycle tries to focus the clicked event but the aborted non-drag attempts to throw the focus back to where it was pre-down

**Comment by bmblb** [comment]
As far as I see, scroll is changed by calling `newEl.focus()` eventually called by the `onDragPointerUp -> dragEnd -> cleanupDrag -> refocus()`

**Comment by bmblb** [comment]
Dragdrop handling sounds like a good place to use FSA, which would eliminate such confusion

**Comment by dongryphon** [comment]
We need this on `cleanupDrag`:
```
        me.refocus?.();
        me.refocus = null;
```

**Comment by dongryphon** [comment]
I'll make a PR w/that and a test for `release` branch
