### ISSUE TITLE
Undo is not working with Note column

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#298]
https://www.bryntum.com/examples/gantt/undoredo/

- Add a New Column - Note
- Enter a note
- Press undo
- Nothing happens

![UndoNote](https://user-images.githubusercontent.com/57486330/74625725-7f7bcf80-5177-11ea-90ee-3512504699f4.gif)

**Comment by matsbryntse** [comment]
Duplicate https://github.com/bryntum/support/issues/297
