### ISSUE TITLE
Region resize splitter problems on touch devices

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#30]
Reported here
https://www.bryntum.com/forum/viewtopic.php?f=51&t=12659

Open this demo on touch device  (checked on Windows Chrome and iPad Safari)
https://www.bryntum.com/examples/grid/multiregion/

![image](https://user-images.githubusercontent.com/57486330/69119898-1a560680-0ac2-11ea-9ecc-cae8757f4d7c.png)

**Comment by SergeyMaltsev** [comment]
Also this shows the problem with splitters and resizing on touch devices.
![TouchResize](https://user-images.githubusercontent.com/57486330/69126786-2e563400-0ad3-11ea-9f90-eeb679378ba6.gif)

**Comment by ExtAnimal** [comment]
RegionResize.onElementTouchStart is

```
    onElementTouchStart(event) {
        const me     = this,
            target = event.target;

        if (target.classList.contains('b-grid-splitter')) {
            me.startMove(target, event.touches[0].clientX);
            event.preventDefault();
        }
    }
```

That test should be `if (target.closest('.b-grid-splitter'))`

**Comment by OuniSaber** [comment]
Hello ,
We have the same problem on the touch devices. The splitter does not remain displayed after the resize.
