### ISSUE TITLE
Repaint issue when using ESC while dragging

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3007]
I was able to reproduce it with our on-line basic demo.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=17757&p=87943#p87943)

We want to report an issue regarding the repaint of the view when using the ESC key while dragging a task.

Steps to reproduce:

Open new Stop planner
	Move a task by dragging it and press ESC key while doing this
	Zoom out

Actual behavior:

The task is not rendered correctly, it jumps at an invalid position. (The transform inline property is not updated anymore)
 

Expected behavior:

The drag should be canceled and the task should be rendered in the correct position based on zoom level. 

Note: If you resize and press ESC key it works fine.

I'm using latest Chrome on a 1920x1080 resolution display.

We have recorded a gif with this issue using your Basic demo.
(https://www.bryntum.com/examples/gantt/basic/)
![pvYyPtTMr2.gif](https://www.bryntum.com/forum/download/file.php?id=13505)

**Comment by mirceabizdadea** [comment]
@matsbryntse Hello, do you have an estimation for this issue?

**Comment by matsbryntse** [comment]
Can you still reproduce? I could not in 5.0.1...

**Comment by mirceabizdadea** [comment]
I cannot reproduce it anymore. Item can be closed, thank you!
