### ISSUE TITLE
Remove `childElementCount` usages, unsupported in LWC

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3008]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=51&t=17761&p=87967#p87967
Replace `childElementCount` with `children.length`

**Comment by isglass** [comment]
Preferably only for LWC, perhaps polyfill `childElementCount` there?

Check performance of `childElementCount` vs `children.length`, since children is a live collection it is likely more expensive
