### ISSUE TITLE
Gantt + Scheduler scroll issues

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3009]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=17769&p=87989#p87989)

Hello.
I found a bug with horizontal scroll.

https://www.bryntum.com/examples/gantt/gantt-schedulerpro/

Scroll is lagging and causing render issues.
It was working good on older versions.

**Comment by bmblb** [comment]
Recording user actions makes demo to lag, disabled logging actions for this demo
