### ISSUE TITLE
Timeline headers missing on partnered Scheduler Pro if partner is set at runtime

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3020]
Steps to reproduce:

1. `Gantt/examples/gantt-schedulerpro/app.js`
2. Comment-out line 82: `partner:gantt`
3. Add line 122: `scheduler.partner = gantt`
4. Run

+ also, it should sync time axis headers when adding the partner before scrolling
Result:
<img width="998" alt="Screen Shot 2021-06-13 at 11 19 06" src="https://user-images.githubusercontent.com/204844/121801768-4d7a6080-cc39-11eb-9d55-ef362707957e.png">

**Comment by isglass** [comment]
Could not repro, asked @jsakalos to check

**Comment by jsakalos** [comment]
I could not reproduce it either. I have tested it both with the above steps and with React drag-between-schedulers demo and it worked w/o problems with both.
