### ISSUE TITLE
Resizing a column with preceding flexed columns moves the column being resized.

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#3025]
https://www.bryntum.com/forum/viewtopic.php?p=88177#p88177

http://lh/bryntum-suite/grid/examples/contextmenu/
All columns have `flex : 1` by default. Try to change the last column width. Dragging between birthplace and birthday changes the size of the birthplace column only. Other columns apply flex width. Dragging at the end of birthday column changes the column width, but it is not possible to make it bigger after that. It should behave the same way it does when there are no flex columns specified (when resizing, the width of both the left and the right columns should be changed)

https://user-images.githubusercontent.com/57486733/121908475-b6470300-cd35-11eb-95c1-f718640da438.mov

https://user-images.githubusercontent.com/57486733/121908128-5cded400-cd35-11eb-8bf4-fe0996e22ed2.mov

https://user-images.githubusercontent.com/57486733/121909119-4f761980-cd36-11eb-8df5-47a4d84d9f67.mov

**Comment by ExtAnimal** [comment]
The solution is to unflex any flexed columns and set them explicitly to the width they happen to be at the current grid width when starting resize of any column:

```
// Unflex all flexed columns so that they do not change size
// in response to sibling size changes
grid.columns.query(c => c.flex).forEach(c => {
    c.element && c.set({
        width : c.element.offsetWidth,
        flex : ''
    });
})
```
