### ISSUE TITLE
Hidden columns are exported anyway

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3036]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=15344&p=88359#p88359)

Hello!!

Here are the steps to replicate:

Open the export demo
Right click on the left grid header, Columns, and uncheck "Start Date"
Hit the export button and accept the default settings
Download the pdf file and open it

Result:
The "Start Date" column is visible

Expected:
The "Start Date" column is not visible

Additional details:
This also occurs with this setting enabled:

```
keepRegionSizes : {
    locked : true
},
```

**Comment by bmblb** [comment]
Still reproducible on gantt and scheduler. Also reproducible on grid if you open the dialog first and then hide columns.
