### ISSUE TITLE
Wrong row selection on click after Grid loses focus

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#306]
Reported here
https://www.bryntum.com/forum/viewtopic.php?f=51&t=13275

# Steps to reproduce
1. Open https://www.bryntum.com/examples/grid/basic/
2. Scroll down
3. Click outside web page contents
4. Click on any grid row
5. Wrong row is selected and scroll position is also wrong.

![WrongSelection](https://user-images.githubusercontent.com/57486330/74719533-68fc7380-525e-11ea-92e3-e6fee769b397.gif)

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/663
