### ISSUE TITLE
Recurrence demo issue

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#3068]
Steps:

1. open `recurrence` demo
2. right click `Every other week` event 2nd occurrence
3. click `Copy event` in the context menu
4. right click on `Arnold` resource on Tue 09 Jan 2018 
5. click `Paste event` in the context menu
6. the copied occurrence build a new chain of events - so far so good
7. drag the new event a week earlier
8. click `Yes` to change all the occurrences

Result: the event start is dragged but its end date is incorrect. It seems it keeps its old value after dragging.

**Comment by matsbryntse** [comment]
Cannot repro in latest
