### ISSUE TITLE
missing `.b-grid-empty` class in Gantt name column when empty

### ISSUE THREAD

**Issue by gpavone** [bryntum/support#307]
It looks like the class `.b-grid-empty` is missing on the element:
```
<div class="b-grid-body-container b-widget-scroller" data-owner-cmp="my-gantt" style="overflow-y: auto;">...</div>
```
Thus, the string specified in the config `emptyText` is not shown properly.

**Comment by matsbryntse** [comment]
Works just fine online, how do you reproduce it?

Go to https://bryntum.com/examples/gantt/basic/
`gantt.taskStore.removeAll()`
