### ISSUE TITLE
Support calculated data fields

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#3070]
Should be possible to calculate the value of a field based on another field's value. For example, `fullName` field should be calculated based on `name` and `surname` fields.

Requested:
https://www.bryntum.com/forum/viewtopic.php?p=88479#p88479
https://www.bryntum.com/forum/viewtopic.php?p=88471#p88471

**Comment by bmblb** [comment]
Event buffer feature uses sort of calculated field that caches the data and gets refreshed when corresponding fields are updated. Probably calculated field could use some logic from there and eventually replace custom getter (`get wrapStartDate()`)

**Comment by mwaddoupcertinia** [comment]
Another vote for the ability to define calculated model fields. We've ended up implementing something similar manually ourselves by listening to store updates, but it would be nice if it was a standard feature that we could hook into.

**Comment by matsbryntse** [comment]
We'll try to prio this!
