### ISSUE TITLE
Exceptions on creating task with drag

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#3071]
Steps:
- Open http://lh/master/bryntum-suite/SchedulerPro/examples/taskeditor/ (seems is working on release)
- Drag on Monday 08 to create a task on "Pressing station" resource

Result:
![Screen Shot 2021-06-18 at 11 47 21 PM](https://user-images.githubusercontent.com/663908/122630203-1c15f080-d090-11eb-93fd-2ac44b0ab026.png)

> EventModelMixin.js:586 Uncaught TypeError: this.incomingDeps is not iterable
>     at ProEventEx.get predecessors [as predecessors] (EventModelMixin.js:586)
>     at DependencyStore.getEventDependencies (DependencyStoreMixin.js:190)
>     at DependencyStore.getTimeSpanDependencies (DependencyStoreMixin.js:326)
>     at Dependencies.updateDependenciesForTimeSpan (Dependencies.js:1798)
>     at EventDragCreate.moveDrag (EventResize.js:663)
>     at EventDragCreate.trackDrag (Draggable.js:492)
>     at DragContext.track (DragContext.js:713)
>     at DragContext.move (DragContext.js:617)
>     at EventDragCreate.onDragPointerMove (Draggable.js:687)
>     at EventDragCreate.onDragPointerMove (EventResize.js:358)
> 
> Entity.js:141 Uncaught (in promise) TypeError: Cannot read property 'read' of null
>     at onEffect (Entity.js:141)
>     at runGeneratorSyncWithEffect (Calculation.js:96)
>     at ProEventEx.run (Entity.js:144)
>     at EventDragCreate.internalUpdateRecord (EventResize.js:838)
>     at EventDragCreate.finalizeDragCreate (DragCreateBase.js:277)
>     at Object.finalize (DragCreateBase.js:262)
>     at EventDragCreate.dragDrop (DragCreateBase.js:226)
>     at EventDragCreate.endDrag (Draggable.js:370)
>     at EventDragCreate.onDragPointerUp (Draggable.js:697)
>     at HTMLDocument.handler (EventHelper.js:518)

**Comment by isglass** [comment]
Cannot repro, did you build engine when switching to master?

**Comment by fabiojpoli** [comment]
just built with this commands: `npx tsc`  on engine folder then `grunt schedulerpro:build`  on schedulerPro folder. Clear cache and run http://lh/master/bryntum-suite/SchedulerPro/examples/taskeditor/.
Still able to reproduce it. To reproduce you have to run the page but not close the editor, keep it open as example open it initially, then try to create event dragging.
