### ISSUE TITLE
Phantom tasks being created when double clicking multiple times

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#3072]
Steps:
- Open http://lh/master/bryntum-suite/SchedulerPro/examples/taskeditor/ (Looks like is working on release)
- Double click quickly many times on different cells to create new tasks but not click on save on the form

Result:
- Some "phantom" tasks have been created:
![Screen Shot 2021-06-19 at 12 07 41 AM](https://user-images.githubusercontent.com/663908/122630584-d7d81f80-d092-11eb-9b43-86755e899c38.png)

**Comment by isglass** [comment]
Same cause as https://github.com/bryntum/support/issues/3075
