### ISSUE TITLE
Resizing task just created anchor the tooltip to top of the page

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#3073]
Steps:
- Open http://lh/master/bryntum-suite/SchedulerPro/examples/taskeditor/
- Close editor
- Double click to create a new task
- Resize the task created

Result: Tooltip go to top of the page (On release it throws an exception):
![Screen Shot 2021-06-19 at 12 28 54 AM (2)](https://user-images.githubusercontent.com/663908/122631011-33f07300-d096-11eb-90c9-f953a26d3ed7.png)

**Comment by isglass** [comment]
Crashes locally too, replacing with a new ticket: https://github.com/bryntum/support/issues/3077
