### ISSUE TITLE
Throwing exception when create dependency on drag

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#3074]
Steps:
- Open http://lh/master/bryntum-suite/Gantt/examples/advanced/ (works on release)
- On Install apache task, click on the icon to create dependency and drag

Result:
![Screen Shot 2021-06-19 at 12 45 14 AM (2)](https://user-images.githubusercontent.com/663908/122631260-8c287480-d098-11eb-9e09-66d79757619e.png)

> DependencyCreation.js:381 Uncaught (in promise) TypeError: Cannot read property 'classList' of undefined
>     at Dependencies.onOverNewTargetWhileCreating (DependencyCreation.js:381)
>     at Dependencies.onTerminalMouseOut (DependencyCreation.js:207)
>     at HTMLDivElement.handler (EventHelper.js:518)
> onOverNewTargetWhileCreating @ DependencyCreation.js:381
> onTerminalMouseOut @ DependencyCreation.js:207
> handler @ EventHelper.js:518
> DependencyCreation.js:381 Uncaught (in promise) TypeError: Cannot read property 'classList' of undefined
>     at Dependencies.onOverNewTargetWhileCreating (DependencyCreation.js:381)
>     at Dependencies.onTimeSpanMouseLeave (DependencyCreation.js:181)
>     at Gantt.trigger (Events.js:1171)
>     at Gantt.unhover (TimelineDomEvents.js:267)
>     at Gantt.onElementMouseOut (TimelineDomEvents.js:258)
>     at Gantt.onElementMouseOut (GanttBase.js:873)
>     at functionChainRunner (InstancePlugin.js:359)
>     at Gantt.plugInto.<computed> [as onElementMouseOut] (InstancePlugin.js:330)
>     at Gantt.handleEvent (GridElementEvents.js:240)
>     at HTMLDivElement.handler (EventHelper.js:518)

**Comment by isglass** [comment]
Does not repro for me, try again?

**Comment by matsbryntse** [comment]
Reproduced
