### ISSUE TITLE
RecurringEvents feature for multiple assignments

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#308]
Requested here
https://www.bryntum.com/forum/viewtopic.php?f=44&t=13364

Add functionality to use `RecurringEvents` feature with `assignmentStore`

**Comment by BonsaiCode** [comment]
Hello, I was wondering if there were updates on this?  I was hoping to migrate my application to use your scheduler, but cannot until this feature is implemented.  I was hoping that full support for RecurringEvents was completely implemented.  Thank you.

**Comment by matsbryntse** [comment]
Implemented
