### ISSUE TITLE
Show rotated title for collapsed column

### ISSUE THREAD

**Issue by isglass** [bryntum/support#3084]
Requested here https://www.bryntum.com/forum/viewtopic.php?f=56&t=17879

**Comment by licjapodaca** [comment]
Is there a plan to include this feature soon in a version release of TaskBoard? ... if not to proceed an implement this feature by ourselves ... 

Regards

**Comment by licjapodaca** [comment]
Is there a plan to include this feature soon? @isglass

**Comment by isglass** [comment]
@licjapodaca Yes, plan to ship it in next minor release (4.3.0). I cannot yet say when that will happen though

**Comment by isglass** [comment]
Since it is mostly CSS we deemed it risk free and decided to include in next patch release instead
