### ISSUE TITLE
Scheduler sticky events get misaligned

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3109]
It is reproducible with our Big dataset demo

![sticky-events-bug](https://user-images.githubusercontent.com/204844/123658832-5cb0ff00-d832-11eb-9f2b-df4a77ad74dc.gif)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=17952&p=88882#p88882)

Hi,

The 'sticky events' feature often breaks with long events while scrolling. I've reproduced this in the big data demo, but i've also reproduced this is in our environment with much less data.

Here's a video with reproduction steps:
https://drive.google.com/file/d/1wZSmSQIbTWwc-hTV_UweUizEj4p1QFRL/view?usp=sharing

Thanks

**Comment by chuckn0rris** [comment]
Dupe? [support/issues/2666](https://github.com/bryntum/support/issues/2666)

**Comment by matsbryntse** [comment]
Should not be a problem anymore now that we use native sticky
