### ISSUE TITLE
Improve the docs to show how to access eventRecord in beforeShow listener

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3117]
eventRecord of the hovered event can be accessed as `e.source.eventRecord ` which is not documented. The documentation inherits from Tooltip widget not adding specifics of EventEdit feature.

Reported here:

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=17978&p=89006#p89006)

How can i disable tooltip with details (and frame) over event when i move mouse over it?
![tooltip.png](https://www.bryntum.com/forum/download/file.php?id=13714)
![tooltip.png](https://www.bryntum.com/forum/download/file.php?id=13714)

**Comment by ExtAnimal** [comment]
It's only possible to add those `Tooltip` event listeners as **configuration** of the `EventTooltip` Feature.

```
scheduler.features.eventTooltip.on('beforeShow', console.log)
```

doesn't work.

The feature should override `addListener` and `removeListener` and route the call through to its owned `tooltip` instance.

This scheme should also be made to work in Calendar's `EventTooltip` feature. That does **not** add its own configured listeners to its tooltip instance at startup time.

This needs to be consistent.

**Comment by jsakalos** [comment]
This looked like an easy documentation fix but the deeper analysis shown that it needs a bit more attention. `TooltipBase.js` feature gets its documentation from tooltip widget using this line:
```
 * @extendsconfigs Core/widget/Tooltip
```
and although it is true that feature config is passed down to the tooltip at the creation time in `onPaint` listener, it is not true at runtime. Therefore,
```
    features : {
        eventTooltip : {
            listeners : {
                beforeShow({ source }) {
                    console.log('beforeShow', source, source.eventRecord);
                },
                beforeHide({ source }) {
                    console.log('beforeHide', source.eventRecord);
                },
                show({ source }) {
                    console.log('show', source.eventRecord);
                }
            }
        }
    },
```
works, but
```
scheduler.features.eventTooltip.on({
    beforeShow({ source }) {
        console.log('beforeShow', source.eventRecord);
    },
    beforeHide({ source }) {
        console.log('beforeHide', source.eventRecord);
    },
    show({ source }) {
        console.log('show', source.eventRecord);
    }
});
```
does not work.

Another problem is that the presence `eventRecord` in tooltip is not documented, because the documentation comes from the tooltip. 
```
