### ISSUE TITLE
Create Angular recurring time ranges demo

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#312]
Requested here
https://www.bryntum.com/forum/viewtopic.php?f=51&t=12640

Demo should reflect 
http://bryntum.com/examples/scheduler/recurringtimeranges

Check if Angular wrapper includes all features for this

**Comment by vincent-dupuy** [comment]
Hi Sergey,
Any update on this topic?
Vincent

**Comment by SergeyMaltsev** [comment]
Hi, Vincent.
No. Demo is not created yet.
Please use latest released version 3.0.4 to enable `recurringTimeSpansFeature` in any Angular demo.

**Comment by matsbryntse** [comment]
Demo now available https://bryntum.com/products/scheduler/examples/frameworks/angular/recurring-timeranges/dist/recurring-timeranges/
