### ISSUE TITLE
First timerange is not shown when using recurring timeranges 

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#313]
Reported here
https://www.bryntum.com/forum/viewtopic.php?f=44&t=13376

Sample config for 
https://www.bryntum.com/examples/scheduler/recurringtimeranges/

```
const scheduler = new Scheduler({
...
    timeRanges : [{
        id             : 1,
        name           : 'DAILY 00-10',
        recurrenceRule : 'FREQ=DAILY',
        startDate      : '2020-01-10 00:00',
        endDate        : '2020-01-10 10:00'
    }],
    startDate  : new Date(2020, 1, 10, 1),
    endDate    : new Date(2020, 1, 12, 23),
...
```
First timerange is not shown until it is fully included in Scheduler display period.

![image](https://user-images.githubusercontent.com/57486330/74830942-6cffc280-533e-11ea-9c49-3096a4904346.png)

**Comment by pmiklashevich** [comment]
Not reproducible
