### ISSUE TITLE
Possibility calendar entries side by side (when there is enough space)

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3140]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?p=89188#p89188)

Thank you bryntum team for this improvement. It help in many usecases!

In some cases now we see some other strange behavior after this update. Do you know why the entries are display like this? (Check my screenshots attached)

Best regards
Marvin

---

Steps to reproduce on a basic calendar demo:
1. take this dataset, wrap array to `{ "success" : true, "events": { "rows": .... } }`
2. declare model and use it in calendar:
```
class MyEventModel extends EventModel {
    static get fields() {
        return [
            { name : 'startDate', type : 'date', convert : (v) => new Date(v * 1000) },
            { name : 'endDate', type : 'date', convert : (v) => new Date(v * 1000) }
        ];
    }
}

const calendar = new Calendar({
    date : new Date(2021, 6, 6),

    crudManager : {
        transport : {
            load : {
                url : 'data/eventstore-data-current-week.json'
            }
        },
        autoLoad : true,

        eventStore : {
            modelClass : MyEventModel
        }
    },

    appendTo : 'container'
});
```
3. run the demo and see blank space. it should be filled with events but it isn't

**Comment by bmblb** [comment]
<img width="1279" alt="Снимок экрана 2021-07-06 130153" src="https://user-images.githubusercontent.com/45400762/124582082-5b975780-de5a-11eb-88d6-8768d7468963.png">

**Comment by doonot** [comment]
Guys what is the progress here? I can see that it's moved back all the time. This is a very annoying bug for us.

**Comment by dongryphon** [comment]
I will be revisiting this in the next few days.
