### ISSUE TITLE
[REACT] CRA prod build: Element.querySelector - not a valid selector

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3142]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18045&p=89329#p89329)

Hi,
We are using Scheduler 4.1.5 with standard react environment (created with create react app) and we got the following error only in production build and with Firefox (Chrome seems OK):

```
SyntaxError: Element.querySelector: '#b-$c-1 .b-grid-header[data-column-id="col8"]' is not a valid selector
```

We found the reason and workaround, but wanted to report this issue.

Reason:
It seems if you don't specify the "id" property inside <BryntumScheduler> component, then the class name will be used.
In production build class name is replaced/minified by webpack and characters like "$" will be used. It's a valid variable character in JS, however Scheduler code uses this name as an ID inside the DOM, which seems not okay, at least Firefox throws an error, when it's used inside the querySelector.
This special character only produced by webpack if you have enough other classes, we only faced with this issue, when added multiple new classes to the code.

Workaround:
We set the id property inside <BryntumScheduler> component, so it doesn't use the class name anymore.

Additional info:
We extended the Scheduler class and using that one.
![scheduler-id.jpg](https://www.bryntum.com/forum/download/file.php?id=13787)

**Comment by bmblb** [comment]
Probably we should use some sort of sanitizer for string we put to the DOM?

**Comment by SergeyMaltsev** [comment]
Any class which extends `Widget` or it descendants you should add valid static `$name()` getter.

This will fix the issue.
```
class MySchedulerClass extends SchedulerClass {
    static get $name() {
        return 'MySchedulerClass';
    }
}
```
