### ISSUE TITLE
Scheduler renders ticks wrong when FromDay/ToDay of the WorkingTime config is changed 

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#315]
Go to https://www.bryntum.com/examples/scheduler/workingtime/
Switch to "Day"
Change "From Day" to 0
Change "To Day" to 7

See:
1. Header name is missing for both Sunday and Saturday
2. Header tick line is missing for Sunday
3. Saturday tick width is too small and there is no scroll bar

<img width="1039" alt="Снимок экрана 2020-02-19 в 17 48 43" src="https://user-images.githubusercontent.com/57486733/74846138-0f20aa00-5341-11ea-9726-7388e4070065.png">

**Comment by matsbryntse** [comment]
not reproducible
