### ISSUE TITLE
Engine in Scheduler takes too much time to handle the data

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3154]
Related forum post: https://www.bryntum.com/forum/viewtopic.php?p=89443&sid=2efc38e940fdf6705c13186ac7eacfc4#p89443

Refer to the attached performance recording. It takes 3 seconds to run `doCommitAsync` function. 1 sec to render the rows (probably ok) and 2 to execute `endBatch`.
[4.2.1-4k.zip](https://github.com/bryntum/support/files/6782386/4.2.1-4k.zip)

**Comment by bmblb** [comment]
Related to #3131

**Comment by bmblb** [comment]
Related issue #3131

**Comment by bmblb** [comment]
Here are recorded profiles comparing 4.2.1 (which already included fixed rendering) with a PR version. loading 8k events to a single resource is down from 12s to 2s
[profiles.zip](https://github.com/bryntum/support/files/6822895/profiles.zip)

**Comment by svmx-abhaydesai** [comment]
@bmblb Performance from 12s to 2s this is really great..**Kudos**.

One clarification if am not wrong this is for loading 8k events to multiple resources I believe.

**Comment by bmblb** [comment]
@svmx-abhaydesai it works for multiple resources too. single resource usage is the worst case scenario in terms of event layout and rendering. This PR fixes adding events to an empty event store.
There is separate performance issue when you add 4k events twice. We will look into that too. Do you add events several times or just add huge amount once?

**Comment by svmx-abhaydesai** [comment]
@bmblb It depends on events data, say if the data is 20k, we fetch the data for 9k add it to the store, then fetch next set which is again 9k add it to the existing events store, then remaining 2k events are fetched and added to the store.

**Comment by bmblb** [comment]
@svmx-abhaydesai we covered this case too. adding large number of events to event store with large number of events should work much faster

**Comment by bmblb** [comment]
@svmx-abhaydesai related PR got merged and fix will be available in the next nightly build. you can try it out on your end to see if any performance issues still remain

**Comment by svmx-abhaydesai** [comment]
@bmblb We took the latest 4.2.2 and tested with our data set, Following are the observations
 - The performance is definitely increased from 4.2.1 to 4.2.2.
 - Earlier when I was not able to add the 9k set of events in batches, it used to fail with first set itself.
 - Now we didn't face any issue while adding 2 sets of 9k events i.e 18k events to the store, however on trying to add 3rd set of 9k events we still see the issue.

**Comment by bmblb** [comment]
@svmx-abhaydesai I tried loading 3 sets of 9k events, both assigned to a single resource and to 100 different resources. Time growth is linear and worst case scenario spends most of its time laying out 27k events in a single resource.
There is a problem when you replace the data though, i.e. you call `add` and pass a dataset with ids that already exist in the store. When store finds such record, it rebuilds indices which is indeed a slow process. But if you have no id duplicates, it should work just fine.
Could you please provide more info about the failing usecase? It'd be good to have a glance on your data set, or a generator function that imitates your dataset and approach you take to add it to the store. For instance this is what I use to test adding events to the store:
```
// scheduler/examples/basic/app.js
const scheduler = new Scheduler({
    appendTo    : 'container',
    crudManager : {
        autoLoad  : true,
        transport : {
            load : {
                url : 'data.json'
            }
        }
    },

    features : { stickyEvents : false },

    startDate : new Date(2017, 1, 7, 8),
    endDate   : new Date(2017, 1, 7, 22),
    tbar      : [
        {
            type     : 'button',
            icon     : 'b-icon b-icon-trash',
            color    : 'b-red',
            text     : 'Add events',
            onAction : () => {
                const eventARR = [];

                for (let i = 1; i <= 9000; i++) {
                    eventARR.push({
                        // id         : i,
                        resourceId : 'a',
                        name       : 'Team scrum ' + i,
                        startDate  : '2017-02-07 11:00',
                        endDate    : '2017-02-07 13:00',
                        location   : 'Some office',
                        eventType  : 'Meeting',
                        eventColor : '#ff0000',
                        iconCls    : 'b-fa b-fa-users'
                    });
                }
                scheduler.eventStore.add(eventARR);
            }
        },
        {
            type     : 'button',
            icon     : 'b-icon b-icon-trash',
            color    : 'b-red',
            text     : 'Add events (100 per resource)',
            onAction : () => {
                const eventARR = [];

                for (let i = 0; i < 9000; i++) {
                    eventARR.push({
                        // id         : i,
                        resourceId : Math.floor(i / 100) + 1,
                        name       : 'Team scrum ' + i,
                        startDate  : '2017-02-07 11:00',
                        endDate    : '2017-02-07 13:00',
                        location   : 'Some office',
                        eventType  : 'Meeting',
                        eventColor : '#ff0000',
                        iconCls    : 'b-fa b-fa-users'
                    });
                }

                scheduler.eventStore.add(eventARR);
            }
        },
        {
            type     : 'button',
            icon     : 'b-icon b-icon-trash',
            color    : 'b-red',
            text     : 'Add 100 res',
            onAction : () => {
                const resouARR = [];

                for (let i = 1; i <= 100; i++) {
                    resouARR.push({ id : i, name : `Resource ${i}` });
                }

                scheduler.resourceStore.add(resouARR);
            }
        }
    ]
});
```
