### ISSUE TITLE
Slow rendering when using Date as startDate/endDate value

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3175]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18111&p=89816#p89816)

It takes a while to load data If `Date` typed data used for `startDate`/`endDate` props. 

Works quick with data like:
```
    {
       "appointmentId":360,
       "branchId":"105",
       "complaint":"Heavy Duty PM B Overdue",
       "startDate": "2021-07-02T14:56:00+00:00",
       "endDate": "2021-07-03T14:56:00+00:00",
       "appointmentStatusId":1,
       "appointmentStatus":null,
       "serviceOrderId":null
    },
```
And slow with:
```
    {
       "appointmentId":360,
       "branchId":"105",
       "complaint":"Heavy Duty PM B Overdue",
       "startDate": new Date("2021-07-02T14:56:00+00:00"),
       "endDate": new Date("2021-07-03T14:56:00+00:00"),
       "appointmentStatusId":1,
       "appointmentStatus":null,
       "serviceOrderId":null
    },
```

Reproduced in basic example for Calendar with 200+ events. Please use the file attached to repro (all data inside).

[app.js.zip](https://github.com/bryntum/support/files/6813663/app.js.zip)

**Comment by ExtAnimal** [comment]
Not sure why this should be. `DateDataField`'s `convert` function should just pass incoming `Date`s right through, so this should make no difference at all.

I'm not sure I believe the report. Once past the data conversion stage, there is of course no difference. Let's run tests with identical data sets one using Dates and one using parseable strings.


Also, `new Date(...)` is not valid JSON:

![Screenshot 2021-07-14 at 08 59 33](https://user-images.githubusercontent.com/200516/125577589-1e88585d-014b-4750-9dca-fd1100e81f37.png)

**Comment by chuckn0rris** [comment]
<img width="783" alt="Screenshot 2021-07-14 at 13 32 31" src="https://user-images.githubusercontent.com/7203098/125584088-26a000be-383c-4112-9c10-3b7c4b6b95d3.png">

**Comment by matsbryntse** [comment]
738K calls to DateHelper.makeKey which generates enormous amounts of Date objects for the garbage collector

<img width="1229" alt="Screenshot 2021-07-17 at 10 23 05" src="https://user-images.githubusercontent.com/218570/126069021-5fb8a853-b304-423d-be31-9e6f8e5573b0.png">

**Comment by bmblb** [comment]
This is a problem with input data. There are few events defined like this:
```
{
    startDate           : new Date('0001-01-01T00:00:00+00:00'),
    endDate             : new Date('2021-06-17T12:55:00+00:00')
}

// Date input
> calendar.eventStore.getById(147).startDate
Mon Jan 01 0001 02:30:17 GMT+0230

// String input
> calendar.eventStore.getById(148).startDate
Tue Jan 01 1901 02:30:17 GMT+0230
```

So for those few events calendar is iterating 2 thousand years day by day to build a values map, which ends up almost a million of keys. Without those few events (i.e. with normalized data) calendar performance is perfectly ok

**Comment by dongryphon** [comment]
I see this on the fast run:
![image](https://user-images.githubusercontent.com/722969/127754583-37dde134-1bf9-4d60-8246-1ef20fd96efe.png)

And this on a slow run:
![image](https://user-images.githubusercontent.com/722969/127754609-86bfb702-13c4-470e-a684-577535c33ac6.png)

**Comment by dongryphon** [comment]
Indeed, Max has it right. The parsing of year `0001` is different if you with `new Date` vs our parser.

**Comment by dongryphon** [comment]
I'd say the best path forward is to tell the customer not to pass events that last 2000 years but we could probably find a way to limit our index to some date range. The challenge there is the event store has no awareness of such ranges from the view layer.

**Comment by dongryphon** [comment]
I checked on the forum post and Max's comment is the last one for a while. Looks like the customer is unstuck.
