### ISSUE TITLE
React custom-event-editor demo issues

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#3177]
Reported here: https://www.bryntum.com/forum/viewtopic.php?p=89884#p89884

Reproducible on scheduler/frameworks/react/javascript/custom-event-editor demo

Issue 1: Cancel button in the custom event editor does not revert event adding
Issue 2: Crud manager `autoSync : true` does not trigger persisting on event adding 

Here is the user provided description:
```
First case
1) I open editor, either through context menu, or through a double click, to create a new event
2) I press cancel button, event remains in the scheduler, request to the server does not occur.
Second case
1) I open editor, either through context menu, or through a double click, to create a new event
2) I press save button, event remains in the scheduler, request to the server does not occur.:
```

**Comment by jsakalos** [comment]
This is most likely related: https://www.bryntum.com/forum/viewtopic.php?f=44&t=18639&p=92352#p92352
