### ISSUE TITLE
Tooltip is not shown for a disabled button

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#3179]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=56&t=18175&p=89922#p89922
https://www.bryntum.com/forum/viewtopic.php?f=56&t=18670&p=92261#p92261

It's not Taskboard specific and can be easily reproduced on any demo like scheduler `configuration` demo for example.

Disabling a button and providing a tooltip for it but it won't show up:
```js
        {
            type : 'button',
            ref  : 'zoomInButton',
            icon : 'b-icon-search-plus',
            text : 'Zoom in',
            disabled : true,
            tooltip : 'foo',
```

**Comment by ExtAnimal** [comment]
It's not a general bug. Tooltips do show on disabled buttons. Here the button disables when there's no records to remove, but the tooltip still shows:

![Screenshot 2021-07-15 at 13 41 42](https://user-images.githubusercontent.com/200516/125782432-8e9823d0-ffe7-4d1c-8d19-03f81f95b60c.png)

**Comment by matsbryntse** [comment]
Reproduced, just like Arcady described. Likely due to Chrome handling of disabled native button el

**Comment by ExtAnimal** [comment]
What are the reproduction steps?

In the Grid Cell Edit example, in Chrome, the tooltip appears for the **initially disabled** button.

**Comment by ExtAnimal** [comment]
It just absolutely IS shown though. I have tested it over and over and over and over and always get the same result. The tooltip is shown. There is NO test anywhere in the tooltip's code path for disabled.

If anybody can show me HOW to make this happen I would be grateful. It Just Works. Every Time.

![Screenshot 2021-09-08 at 10 40 05](https://user-images.githubusercontent.com/200516/132476312-65275ede-c99d-40a4-86e6-abd4e8a65cc9.png)
