### ISSUE TITLE
Dependencies render twice on start

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3193]
Dependency feature adds multiple `transitionend` listeners to schedule redraw which makes some tests unstable.
```
// scheduleDraw
transitionend() { me.draw() }

// draw
transitionend() { me.scheduleDraw(true) }
```

When transitionend fires we draw dependencies immediately and schedule redrawing on the next animation frame. If timeout gets in the same frame with `transitionend` call, we get different rendering process. This is what failing DependencyDrawing_2.t.js in scheduler.

There are two solutions:
1. Somehow get rid of 2nd listener.
2. Make both listeners call `scheduleDraw`. This will reduce initial deps drawing to just one, but at the same time this makes some tests to fail. Scheduler tests just expect too much events, which is fine, but `dependency_rendering_2.t.js` in gantt indeed starts drawing dependency which is far out of the view.

Attached is a troubled screenshot and performance recording. Flaky test is run twice there, 1st time it passes, 2nd time it fails because timeout gets triggered between two dependency drawings.

![image](https://user-images.githubusercontent.com/45400762/126147489-f719f082-3639-45bf-ad19-d8c97cd20d94.png)

[dependency-drawing-two-flows.zip](https://github.com/bryntum/support/files/6840408/dependency-drawing-two-flows.zip)

**Comment by isglass** [comment]
Dependencies feature was refactored, works different now
