### ISSUE TITLE
Order of events changes on scrolling if `eventLayout: 'none'`

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3198]
Confirmed, it behaves as described on forum.

![event-layout-none](https://user-images.githubusercontent.com/204844/126350801-2a7d31c6-d876-4b6b-8b2a-8768e1e9e547.gif)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=18128&p=90179#p90179)

Hello team,
we use the Bryntum Scheduler for our planning function in our project.
We encountered a problem while implementing the functions:
While we set the property "eventLayout: 'none';" to overlap the events, we'd like to get a different row height / bar margin / resource margin based on a property of each event. (https://bryntum.com/examples/scheduler/rowheight/#)

Overall context:
Our planning software relates to the logistics area.
The resources include the vehicles. The assigned drivers and the tours are shown in the events.
A driver can process several tours, so the tours must be presented within the driver event. We have solved this as in the example with the EventLayout 'none' (Attachment_1_OverlapEvents).

Implementation:
We would represent normal events with the normal margins (Attachment_2_NormalMargins) while driver events should receive smaller margins (Attachment_3_SmallMargins).

So we can get the event with smaller rowheight in front of the events with bigger rowheight. 
(e.g. Attachment_2 Event: "Extend test" in foreground of Attachment_3 Event: "Fork project")

We can get the corresponding property inside the eventRenderer.

```
eventRenderer({ eventRecord, resourceRecord, renderData }) {
        switch (eventRecord.eventType) {
            case ds.DispatchEvent.DPDRIVER:
                // driver should have small margins
                break;

            case ds.DispatchEvent.DPLOADING:
            case ds.DispatchEvent.DPDELIVERY:
                // events should get a bigger margin, therefore they are inside the driver events
```

How can we accomplish this?
Thx in advance.

Best regards 
![Attachment_1_OverlapEvents.png](https://www.bryntum.com/forum/download/file.php?id=13901)
![Attachment_2_NormalMargins.png](https://www.bryntum.com/forum/download/file.php?id=13900)
![Attachment_3_SmallMargins.png](https://www.bryntum.com/forum/download/file.php?id=13899)

**Comment by taauntik** [comment]
user asked for the fix [here](https://www.bryntum.com/forum/viewtopic.php?f=44&t=18128&p=108402#p108402)
