### ISSUE TITLE
DateHelper parses dates with time offset wrong (e.g. +01:00)

### ISSUE THREAD

**Issue by jeffrey-planon** [bryntum/support#32]
Using Bryntum Scheduler 2.3.0.

Specifying a startDate containing a datetime with a timezone offset seems to not work correctly.
```
const scheduler = new Scheduler({
    ...
    startDate: '2019-11-19T00:00:00+01:00'
});
```
Executing scheduler.startDate.getTime() returns 1574118000001.

Looks like an issue with the DateHelper since DateHelper.parse('2019-11-19T00:00:00+01:00') returns a Date with time of 1574118000001 (seems to add 1 millisecond). Expected time 1574118000000.

**Comment by isglass** [comment]
Thanks for reporting!

Looks like an issue with our docs for `DateHelper.parse`, it says the default format is:

`YYYY-MM-DDTHH:mm:ssZ`

When in code it actually is:

`YYYY-MM-DDTHH:mm:ss.SSSZ`

Thus is interprents +01 as milliseconds. 

This will probably work for you instead:

2019-11-19T00:00:00.0+01:00

Will fix the docs to reflect reality.

**Comment by jeffrey-planon** [comment]
A document issue???? Seems like a rather annoying workaround for a date format I would expect to be supported no?

I use the same date format for my events and they work fine? Seems like there is some inconsistency going on here then.

**Comment by isglass** [comment]
Well, docs were wrong in relation to the code. But I agree that it makes sense for the default format for Scheduler and Events to match. Checked and currently they differ. 

It should be configurable globally somewhere, I suppose we should make a public setter for `DateHelper.defaultFormat`. I'll turn this issue into a feature request and halt that PR
