### ISSUE TITLE
Resource margin does not affect milestone size

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#320]
Try in animations demo

`scheduler.resourceMargin = 10
`

<img width="610" alt="Screenshot 2020-02-20 at 11 44 43" src="https://user-images.githubusercontent.com/218570/74926577-66248e80-53d6-11ea-8588-f99ad1629c11.png">

**Comment by isglass** [comment]
To fix, change 
```
 onBeforeRowHeightChange(event) {
        const view = this.view,
            newHeight = event ? event.height : this.rowHeight;
```
To:
```
 onBeforeRowHeightChange(event) {
        const view = this.view,
            newHeight = event ? event.height : view.rowHeight;
```

In BaseHorizontalMapper
