### ISSUE TITLE
Header is rendered incorrectly for monthAndYear preset

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3208]
Can be reproduced with our demo and user's data:

<img width="1249" alt="Screen Shot 2021-07-22 at 13 20 42" src="https://user-images.githubusercontent.com/204844/126631887-02d34860-7e6b-496e-aebc-635b2cf5354e.png">

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18258&p=90318#p90318)

Hi,

Do you have an example page for scheduler where you can change the viewPreset and the date at the same time?

In our application we get this behavior when selecting the 1/10 as end date with the viewPreset "monthAndYear": ![Screen Recording 2021-07-22 at 09.31.20.gif](https://www.bryntum.com/forum/download/file.php?id=13982)

When the end date is anything but the first, the column is displayed correctly.
![Screen Recording 2021-07-22 at 09.31.20.gif](https://www.bryntum.com/forum/download/file.php?id=13982)

**Comment by jsakalos** [comment]
This is not a bug but a weird user's configuration.

**Comment by bmblb** [comment]
Problem is not with tooltip itself - it just uses time axis API to get date from under the pointer. Time axis is ok on the data level, it is the header which is rendered incorrectly.

This header ends on Oct 1 (ok)
![image](https://user-images.githubusercontent.com/45400762/126803035-58e9c7ab-f945-4c47-8749-41d28868ed3e.png)

This header ends on Oct 2 (wrong)
![image](https://user-images.githubusercontent.com/45400762/126803041-f99f6b5f-c285-4415-8c92-1be44a318f1e.png)

This header ends on Oct 3 (ok)
![image](https://user-images.githubusercontent.com/45400762/126803045-27fd089a-0bab-401d-a5ca-302fc0de0918.png)
