### ISSUE TITLE
Gantt React: Trial runtime error with development server

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#321]
Reported here
https://www.bryntum.com/forum/viewtopic.php?f=52&t=13384

Gantt react javascript demos fail to run in browser with 
```
npm install
npm run start
```

Runtime error occurs
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
...
```

Build with `npm run start` works fine.

**Comment by jsakalos** [comment]
It is caused by buggy react-scripts version. Just bump the version to "3.4.0" in package.json, remove node_modules, reinstall, re-build and it should work.
