### ISSUE TITLE
Destroyed scheduler still handles events

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3212]
The frameworks require to fully remove Bryntum widgets, including installed global listeners, is some cases, for example when navigation out of the page that contains a Bryntum component.

We need a way how to sense that all widgets are gone and detach the global events in that case.

This can also be done in the framework application but we should not impose this responsibility on the users.

The issue can be reproduced as follows:

1. unzip the attached code [simple.zip](https://github.com/bryntum/support/files/6867807/simple.zip)
2. run `npm i && npm start`
3. navigate to http://localhost:3000
4. follow the steps from this screencast:

![scheduler-not-destroyed](https://user-images.githubusercontent.com/204844/126763042-272b6c33-07f5-432c-942e-483fc3c6a2e5.gif)

The scheduler should have been destroyed completely at that point and should not hang the browser in the infinite loop.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=18250)

Hello,
We have a react app where we use Bryntym Scheduler Pro and we also use jqxGrid. The issue we're having is that when we first navigate to a page with the scheduler, then navigate to a page with jqxGrid and try to change the filtering option, it completely freezes. This does not happen if we don't visit a page with Bryntum scheduler first, indicating that it is the cause of the issue.
Changing this causes the tab to freeze:
https://imgur.com/mn5xK8N
Also, using Firefox's performance profiler reveals that the freeze is caused by the Bryntum Scheduler. It attempts to handle some event, even though it's not being rendered:
https://imgur.com/a/hB1O0nK
Clicking on the highlighted line opens up this:
https://imgur.com/a/m9mnJyb
So, how am I supposed to destroy the scheduler instance, so that it doesn't affect other pages that are irrelevant to it?
Note we are using react-router-dom for navigation.

Thank you,

**Comment by chuckn0rris** [comment]
Requested here https://forum.bryntum.com/viewtopic.php?t=25413

**Comment by pjc2007** [comment]
Hi just wondering if any updated on this, as waiting before I can release (which is becoming due).

Or even a work around, As in one of ,my posts, it appear the problem is the handlers are being added at module loading, which seem to happen at app startup, even though I have mine in an (Angular)  lazy  loaded module,

```
createHandler (c:\dev\my-app\node_modules\@bryntum\scheduler\scheduler.module.js:11093)
addElementListener (c:\dev\my-app\node_modules\@bryntum\scheduler\scheduler.module.js:10990)
on (c:\dev\my-app\node_modules\@bryntum\scheduler\scheduler.module.js:10960)
4296 (c:\dev\my-app\node_modules\@bryntum\scheduler\scheduler.module.js:11387)
__webpack_require__ (webpack/bootstrap:19)
332 (localhost꞉8100/main.js:1415)
__webpack_require__ (webpack/bootstrap:19)
16823 (localhost꞉8100/main.js:7908)
__webpack_require__ (webpack/bootstrap:19)
```

**Comment by matsbryntse** [comment]
We can check if any Bryntum widgets are present and skip all processing if not.

Will try to get this done soon!
