### ISSUE TITLE
EventModel.set() and normalization bug - event moves instead of resizing

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3232]
Reproduced. The expected behavior would be that event updates correctly.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18316&p=90551#p90551)

Hi,

we're receiving event changes from backend and using EventModel.set() to apply these changes, however in certain case it does not work as expected.

Example:
open basic example: https://www.bryntum.com/examples/scheduler/basic/
run from console:

```
scheduler.eventStore.getById(1).set({
  name: 'Test',
  startDate: new Date(2017, 0, 1, 8),
  endDate: new Date(2017, 0, 1, 12)
});

```

As I'd expect the event should start from 8am to 12am after setting these times, however it will "move" (end date will change to 10am instead of 12am as I set it).

If you run again the same code, the end date will be correct.

Any solution for this?
Thanks

**Comment by isglass** [comment]
Only happens when setting with an `endDate` equal to its current `endDate`. Changing `endDate` will then be considered a no-op and only `startDate` will pass through to engine -> and when setting only a `startDate` the default behaviour is to keep the duration.
