### ISSUE TITLE
Dragging & Dropping task row indicates drop in wrong place

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3252]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18381&p=90831#p90831)

Hey Guys,

With the advanced example, I'm dragging task 1.2.5 down to drop it in 1.3.2 sub-tree.
As you can see in the image the blue line indicates a drop location in the 1.3.2 sub-tree, but the parent arrow indicator is a level up. When dropped in this state, it does appear as a sibling of 1.3.2.

I assume this is a visual quirk of having the 1.3.2 sub-tree expanded.

When you move the mouse to  be over 1.3.2.1 then the blue line doesn't move, but the drop behavior changes such that the moved task does appear in the 1.3.2 sub-tree.

This seems a little odd.

Thanks

Chris

**Comment by isglass** [comment]
How we indicate drop location has changed, we now use the same style as Adobe does for layers in photoshop. Will close this as no longer reproducible
