### ISSUE TITLE
Export generates empty pages

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#327]
http://dev.bryntum.com/examples/scheduler-vanilla/examples/export/index.html
<img width="599" alt="Screenshot 2020-02-20 at 21 04 02" src="https://user-images.githubusercontent.com/218570/74973861-8a0ec100-5424-11ea-99d3-d24fb08d72dd.png">

[Scheduler (2).pdf](https://github.com/bryntum/support/files/4232785/Scheduler.2.pdf)

**Comment by bmblb** [comment]
Released with 3.0.4 on 24/02/2020
