### ISSUE TITLE
Follow cursor on event resize when using fillTicks

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#3273]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18412)

Need some config to set resize behavior with `fillTicks` enabled.

> Hi,
> 
> We were using Scheduler 4.0.8, where using fillTicks and resizing the events or using drag to create would update the event size to match the drag handle, before finishing the resize.
> 
> Now, switching to 4.2.3, seems this has been lost, which means the event fills the whole destination "tick", before the drop to finish. 
> We tried to use the showExactResizePosition setting to prevent this, but doesn't seem to make some effect.
> 
> How can we get the old behavior, i.e, the event only fills the whole "day" after the drop, for the users to have a clearer perception of the new end time? Drag to create this way is unusable..

4.0.8

![Resize408](https://user-images.githubusercontent.com/57486330/128835936-0e07af3f-2863-41fb-8c61-097fc1aeb98e.gif)

4.2.3

![Resize423](https://user-images.githubusercontent.com/57486330/128835952-337e805e-5ed6-4bcb-9098-e3099f1c69c9.gif)

**Comment by isglass** [comment]
Opt out of fillTicks on resize/drag create, but only for that event somehow
