### ISSUE TITLE
FilterBar feature doesn't allow to use array for filter config

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3275]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=18420&p=91005#p91005)

Hello,

I recently make an update of Bryntum and I notice that the mulsitselect filter don't show multiple values anymore. You can reproduce the problem here https://www.bryntum.com/examples/grid/filterbar/ and add this values to the filter : 

```
filter      : { property : 'city', value : ['Paris', 'Dubai'] }
```

'Paris' and 'Dubai' is not shown in the filter.

.....
But it works if Paris and Dubai selected in the combo

**Comment by matsbryntse** [comment]
Dupe #2951
