### ISSUE TITLE
After expanding all day header, it overflows the screen and cannot be collapsed again

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3317]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18541&p=91555#p91555)

 Also, if the user drops the the full list of tasks in the week view using the arrow button to the left of the calendar then if any day in that view has more than 19 tasks then they drop below the component view and can't be selected and the list can't be pulled back.

Could someone please take a look at this?
![Image of the bryntum calendar demo after the drop down has been selected](https://www.bryntum.com/forum/download/file.php?id=14269)
![Image of the bryntum calendar demo before the drop down has been selected](https://www.bryntum.com/forum/download/file.php?id=14268)

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/4027
