### ISSUE TITLE
Pop up showing all day events is clipped by the calendar main element

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3318]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18540&p=91554#p91554)

In the Bryntum Calendar, if the user selects to view more tasks on a day using the week or month view, the tooltip that displays is cut off at the edge of the component despite other tooltips and menus not being cut off like this. This can prevent a user from accessing many tasks on the calendar this way.

If theres sufficient room above the Calendar on the page, the tooltip appears above and is clipped. Otherwise the tooltip displays on the Calendar (downward facing). 

This bug occurs in the normal Bryntum Calendar demo - although it was first noticed in the Salesforce LWC version of the Calendar. 

Can someone please look at this?
![Bug viewed without padding above the basic Bryntum Calendar demo](https://www.bryntum.com/forum/download/file.php?id=14267)
![Bug viewed with padding above the basic Bryntum Calendar demo](https://www.bryntum.com/forum/download/file.php?id=14266)

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/4027
