### ISSUE TITLE
Task baselines need to track changes and modify Task 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#336]
Update packet sent by CrudManager must reflect baseline state

**Comment by ExtAnimal** [comment]
Starting point here: https://github.com/bryntum/bryntum-suite/pull/666

**Comment by isglass** [comment]
See also #2685

**Comment by isglass** [comment]
And https://github.com/bryntum/support/issues/5169

**Comment by isglass** [comment]
I plan to work on this after my current set of tasks
