### ISSUE TITLE
WidgetColumn visible property to manage widget's visibility

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3367]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=18621&p=91977#p91977)

Should be possible to manage widgets visibility depends on record data. See [ActionColumn](https://bryntum.com/docs/scheduler/#Grid/column/ActionColumn) for example. It should support both: boolean and callback function.

**Comment by matsbryntse** [comment]
This is supported in 4.3.0, using the regular Column#renderer
