### ISSUE TITLE
New created event is displayed even if assigned to filtered resource

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3375]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18649&p=92113#p92113)

https://www.bryntum.com/examples/calendar/basic/

1. Uncheck a resource in filter panel
2. create a new event using drag-n-drop, assign it to unselected resource (using EventEdit dialog), click save.

A new created event assigned to filtered resource is visible on the calendar. 

https://user-images.githubusercontent.com/7203098/132213992-ff026b74-04d6-4be4-8da7-964376827d40.mov

**Comment by matsbryntse** [comment]
Try setting: https://bryntum.com/docs/scheduler/#Core/data/mixin/StoreFilter#config-reapplyFilterOnAdd

**Comment by matsbryntse** [comment]
Works as intended
