### ISSUE TITLE
Performance degradation in UMD bundle

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3392]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=51&t=18546&start=10

Issue is reproducible with UMD bundle only. `store.add` works faster with sources and modules bundle, but twice as slow in umd bundle. Performance profile shows that constructor takes most of the time.

Data sample and demo code can be found in the related forum thread.

**Comment by SergeyMaltsev** [comment]
Since `5.0.0` umd package is no longer transpiled for IE 11 compatibility and has less polyfills.
Should have same performance and module bundle or source.
