### ISSUE TITLE
[Firefox] Out of memory issue in bigdataset demo

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3398]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=18701&p=92413#p92413

Reproducible in Firefox 92 if you generate initial dataset like `applyPreset(200, 5)`. `applyPreset(2000, 5)` works just fine

**Comment by SergeyMaltsev** [comment]
Found that disabling internal option called `javascript.options.baselinejit` in FireFox fixes the problem with out of memory.

**Comment by SergeyMaltsev** [comment]
Bug report for Mozilla has been created:
https://bugzilla.mozilla.org/show_bug.cgi?id=1732601

**Comment by SergeyMaltsev** [comment]
Mozilla confirmed that issue has been fixed and targeting FireFox 94.
https://bugzilla.mozilla.org/show_bug.cgi?id=1732601
I've checked with latest FireFox nightly 94 alpha 1 and this works.
