### ISSUE TITLE
ColumnsStore batch operation crashes

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3402]
Gantt crashes when columns are updated at runtime with the following code:
```
gantt.columns.beginBatch()
let currentColumns = gantt.columns.query(it => {
    return it.type !== 'timeAxis'
})
gantt.columns.remove(currentColumns)
gantt.columns.add(gantt.columns)
gantt.columns.endBatch()
```
<img width="1182" alt="Screen Shot 2021-09-13 at 10 35 29" src="https://user-images.githubusercontent.com/204844/133051428-211ee1bb-86c6-43c6-9cb8-6b2e8a90045c.png">

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=18716&p=92469#p92469)

Objective: to save columns and their state in the database
Solution: recreating columns from ColumnsStore

Problem:
Very slow work. A large number of events are amazed. I tried using beginBatchI () endBatch.

In code: 

```
gantt.columns.beginBatch()
let currentColumns = gantt.columns.records.filter((it: any) => {
    return it.data.type !== "timeAxis"
})
gantt.columns.remove(currentColumns)
gantt.columns.add(selectedGanttView.columns)
gantt.columns.endBatch()

```

The following error occurred: 
UI gantt does not respond to batch completion

if i change code in:

```
gantt.columns.beginBatch()
let currentColumns = gantt.columns.records.filter((it: any) => {
    return it.data.type !== "timeAxis"
})
gantt.columns.remove(currentColumns)
gantt.columns.endBatch()
gantt.columns.add(selectedGanttView.columns)

```
Then  gantt work.

Tell me, is it permissible to do this? If so, what is my mistake? According to the documentation, this should work

**Comment by matsbryntse** [comment]
invalid
