### ISSUE TITLE
DayView should stretch hours fill available height

### ISSUE THREAD

**Issue by isglass** [bryntum/support#3406]
Similar to how Scheduler stretches ticks to fill the view. Possibly configurable

<img width="966" alt="Screenshot 2021-09-13 at 14 55 24" src="https://user-images.githubusercontent.com/5415653/133087312-5299cd01-f75d-454b-92cc-854ed9dba455.png">

**Comment by dongryphon** [comment]
Looks like this is handled by https://www.bryntum.com/docs/calendar/api/Calendar/widget/DayView#config-fitHours
