### ISSUE TITLE
Missing icon Intraday events in Month and Agenda view

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/support#3409]
http://lh/calendar-4.2.5/examples/shifted/

![Screenshot 2021-09-13 at 17 09 09](https://user-images.githubusercontent.com/25703411/133109565-93f604f6-98e4-4b12-a047-edc2d48d79b6.png)

Should look like this

![Screenshot 2021-09-13 at 16 49 14](https://user-images.githubusercontent.com/25703411/133109673-0a034dac-ff85-4121-936e-bfabe7db92aa.png)

**Comment by ExtAnimal** [comment]
Seems icons in all day events were set to `display:none`

https://github.com/bryntum/bryntum-suite/commit/5b9a9fa239c937f4f98c13d94265a3cbf765c500#diff-64d15748e9b5ba1360a0a4fb3c3da7274139c1822452f4e671b2b105e6aaa9b3R120

**Comment by javascript-programming** [comment]
calendar 4.2.2 is still correct it got broken in 4.2.3

**Comment by dongryphon** [comment]
The data for the "Should be this" image looks completely different than the data for that example... is this a modified example to illustrate the issue? If so, can you attach the revised example here?

Also, is this only observed in the shifted day example or do others (like the basic example) have the problem as well?

**Comment by dongryphon** [comment]
Are we just talking about the red and green icons and not the events/data?

**Comment by javascript-programming** [comment]
Also in the basic example
![Screenshot 2021-09-14 at 14 51 55](https://user-images.githubusercontent.com/25703411/133261062-a4fddfca-b95f-4dd0-a584-8afec6093ddd.png)


![Screenshot 2021-09-14 at 14 52 47](https://user-images.githubusercontent.com/25703411/133261073-5c46880e-5255-4324-870b-300a1b85a718.png)

**Comment by javascript-programming** [comment]
icon class does not seem to be added to intraday events

**Comment by javascript-programming** [comment]
eventColor is set on the icon and with icon missing we have no color display anymore

**Comment by ExtAnimal** [comment]
Reopened. The icons are still `display:none` for `allDay` events. They show up for intraday events, but are explicitly hidden for `allDay` events. I don't think this is right.

https://user-images.githubusercontent.com/200516/133395407-f1129d58-a6ce-4d4f-9829-99471d1db468.mp4
