### ISSUE TITLE
Monthly recurring generates events on wrong day

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3413]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=18728&p=92541#p92541)

Hello,

Even in your own demo site, the monthly recurring doesn't work currently.  We have numerous customers complaining about the monthly recurring appointments not working correctly.

https://ibb.co/1f0NTqY
![image](https://user-images.githubusercontent.com/722969/133905313-044e41bd-0e5c-4231-a97d-cfe1000a9fd9.png)

I created a monthly recurring event every month on the second Wednesday and it shows up in the next month on a Tuesday.

Is there a plan of solving these? They causing quite an issue.

Regards,

Susan, Dan

**Comment by dongryphon** [comment]
I'm also seeing a discrepancy between the text on the edit dialog ("Monthly on the first Wednesday") and the picker in the Repeat event dialog ("second" and "Wednesday").
![image](https://user-images.githubusercontent.com/722969/133905555-0290568f-3864-4422-958d-fffd2c28655e.png)

**Comment by dongryphon** [comment]
Looks like the Nov occurrence is a victim of a DST adjustment issue. Other months correctly display on the 2nd Wed but in Nov that occurrence follows DST change on Nov 1 (2020) and I can reproduce it as well on Nov 7 (2021)...
