### ISSUE TITLE
Virtualized card rendering

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3414]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=56&t=18731&p=92547#p92547)

Hi there, the Taskboard v4.2.5 is very slow when I load multiple card tasks in a column like in the following image example:

![scrollbar-too-slow.png](https://www.bryntum.com/forum/download/file.php?id=14525)

When I trying to scroll the cards renders to slowly with the scrolling motion and some times freezes the Taskboard componen.

Is there a way to handle the performance when there are a lot of card tasks?

Regards
![scrollbar-too-slow.png](https://www.bryntum.com/forum/download/file.php?id=14525)

**Comment by chuckn0rris** [comment]
Another report https://www.bryntum.com/forum/viewtopic.php?f=51&t=22374&p=110698#p110698
