### ISSUE TITLE
Infinite sync loop if `percentDone` value is incorrect

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3427]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=18761&p=92812#p92812)

Make `sync.json` file in `examples/_datasets` folder with the following content:
```json
{}
```
Edit gantt `basic` example `app.js` accordingly:
```js
    project : {
        autoLoad  : true,
        transport : {
            sync : {
                url : '../_datasets/sync.json'
            }
    ...
```

And change `percentDone` field value in `launch-saas.json` to incorrect. As example replace 
```
"percentDone": 50,
// to 
"percentDone": "50%",
```

Run the example, execute in console:
```js
gantt.project.sync().then(() => {
    console.assert(!gantt.project.changes, 'project has commited all its changes')
})
```

**Comment by marciogurka** [comment]
This also happens in SchedulerPro, as reported [here](https://www.bryntum.com/forum/viewtopic.php?f=52&t=18761&p=107838#p107838)

**Comment by marciogurka** [comment]
From the forums, also some information

> I also wanted to add that this issue was not present in scheduler pro 5.0.4. The issue started happening from 5.0.5 and is still there in 5.0.7.
