### ISSUE TITLE
[ANGULAR] EventTooltip template is shown only once when displaying customElement.

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3432]
Confirmed, it behaves as user says. I suspect some XSS logic that strips custom element from the resulting html. If the custom element is wrapped in a div, e.g. `<div><tooltip-renderer></tooltip-renderer></div>` then the resulting html of the tooltip is just `<div></div>` 

It can be reproduced by running this showcase (SchedulerPro):

[resource-histogram.zip](https://github.com/bryntum/support/files/7189994/resource-histogram.zip)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=18775&p=92856#p92856)

Hi!

So I want to show my customElement in tooltip html.

Code for rendering my customElement:
![eventTooltipTemplate.png](https://www.bryntum.com/forum/download/file.php?id=14593)

Html code of my custom element:
![htmlTemplate.png](https://www.bryntum.com/forum/download/file.php?id=14594)

I'm defining customElement before scheduler is rendered.

```
 customElements.define('gantt-task-tooltip', (SomeGanttTaskTooltipComponent, {
      injector: customInjector
    }));

```

I'm doing everything exactly like in another places of scheduler.
(for e.g. in validation I'm using custom elements and all is working)
Result:
![tooltiperror.gif](https://www.bryntum.com/forum/download/file.php?id=14595)

So as you can see, no errors in console - tooltips are working only once.

If I will rerturn only some text in templatemethod, all is working.
![eventTooltipTemplate.png](https://www.bryntum.com/forum/download/file.php?id=14593)
![htmlTemplate.png](https://www.bryntum.com/forum/download/file.php?id=14594)
![tooltiperror.gif](https://www.bryntum.com/forum/download/file.php?id=14595)

**Comment by jsakalos** [comment]
Further analysis has shown that the issue cannot be reproduced in vanilla. For example:
```
class TooltipRenderer extends HTMLElement {
    connectedCallback() {
        this.innerHTML = 'Custom Element Tooltip';
    }
}

window.customElements.define('tooltip-renderer', TooltipRenderer);

// ...

    features : {
        eventTooltip : {
            template : () => '<div>tooltip template</div><tooltip-renderer></tooltip-renderer>'
        }
    },

```

in `scheduler/examples/basic` works as expected.

Therefore it has something to do with how Angular defines/creates/destroys custom elements. The following angular component:
```
import { Component, ElementRef, Input, OnDestroy, OnInit } from '@angular/core';

@Component({
    selector : 'app-tooltip-renderer',
    template : `
        <div class="custom-tooltip">
        <h3>{{ value }}</h3>
        <p>Tooltip (custom element)</p>
        <p><b>{{ name }}</b> of <i>{{ team }}</i> team</p>
        <p>is <b>{{ age }}</b> years old and has <i>{{ color }}</i> color</p>
        </div>
    `
})
export class TooltipRendererComponent implements OnDestroy, OnInit {
    @Input() name : String;
    @Input() age : String;
    @Input() color : String;
    @Input() team : String;
    @Input() value : String;

    constructor(private element:ElementRef) {}

    ngOnInit(): void {
        console.log('running init');
    }

    ngOnDestroy() : void {
        console.log('running destroy');
    }
}
```

logs on the console one init on hover, one destroy on mouse out but never runs init again.

**Comment by AamilShohail** [comment]
What is the solution to this? I'm having the same behavioral issue

**Comment by matsbryntse** [comment]
@AamilShohail This was fixed long ago, probably best you open a new forum thread here Finally would be great for Bryntum team to consider in the future the posibility to offer for trial mode the source code as well, so we can evaluate better what we are about to buy.
