### ISSUE TITLE
Not possible to use filter feature with grouped headers in grid

### ISSUE THREAD

**Issue by eangelov** [bryntum/support#3443]
Using the [grouped headers example](https://www.bryntum.com/examples/grid/groupedheaders/) and enabling the filter feature with default behavior.
![image](https://user-images.githubusercontent.com/3601104/134164439-15a7599e-2b2c-4d16-ba81-8a2483d5bf95.png)

Currently if the the filter feature is enabled only the "Contact" and "Favorites" headers allow for filtering. Meaning any grouped column cannot filtered by from the UI.
![image](https://user-images.githubusercontent.com/3601104/134162794-6b2739d8-fa5d-4b7d-9f85-5bc852639158.png)
![image](https://user-images.githubusercontent.com/3601104/134162941-a2519fa7-ca55-4763-9cac-7d10cb41fefe.png)

Also the default filter behavior for when filtering for example via the "Contact" header is kind of confusing.
Filtering for "Don" which if contained in the loaded data yields nothing, I think this is expected since there is custom filter function defined and the "Contact/Taylor/Moscow" header is just a wrapper around the grouped headers. I think that it will be clearer if by default filtering via grouping header( in this case "Contact" ) is disabled unless a custom filtering function is provided.

![image](https://user-images.githubusercontent.com/3601104/134163425-a68608c2-6e47-4d07-a5d0-016696909c19.png)
![image](https://user-images.githubusercontent.com/3601104/134163464-9f97f78a-0e1e-4c0c-8819-e10beaeaeb20.png)
![image](https://user-images.githubusercontent.com/3601104/134163545-36a5fc05-376c-4a4e-9d23-dcfc06f61dd3.png)
![image](https://user-images.githubusercontent.com/3601104/134163815-c1d722f0-32d1-4706-ae46-fe82a995f5b1.png)

**Comment by matsbryntse** [comment]
Agree, this should be fixed!
