### ISSUE TITLE
startDate and endDate values are inconsistent when edit event with "All day" option selected

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3455]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=18835&p=93159#p93159)

https://bryntum.com/examples/calendar/recurrence/

1. Create new event, select "All day" option. **startDate and endDate values are same**
2. Save changes and dblclick on it to show the editor. **See that startDate and endDate has 1 day difference**
3. Uncheck "All day" and check it again. **startDate and endDate are same again**

Another scenario:
1. Repeat 1 and 2 from previous one
2. Uncheck "All day", try to change time for startDate using arrows. endDate time will be update to the same time accordingly.
3. Try the same with just created event with any duration - 1 hour, 2 days, 3 hours... - if you change startDate time, endDate time will be updated with +1 hour value, not the same

**Comment by ExtAnimal** [comment]
The start date and end date do not become the same. If it's all day, it *does not show* the time portion of start date and end date. The values are still there.

If you uncheck the all day checkbox, the time portion becomes visible again.
