### ISSUE TITLE
loadOnDemand causes fetch loop when involving Scheduler

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3469]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=18907&p=93498#p93498)

Hello,

We're using the timeline view (for which the client purchased a Scheduler license) and if we try to use loadOnDemand, the calendar goes into a fetch loop.

To reproduce the issue, please use this example: https://bryntum.com/examples/calendar/bigdataset/

If you add:

```
loadOnDemand: true
```
to the "features" object, the calendar will fetch events whenever you change the context (the month, the week, etc), as expected.

Then add: 

```
timeline: {
    type: "scheduler",
    displayName: "Timeline"
} 
```
to the "modes" object.

Now if change the context (e.g. click on "Month"), this will throw the calendar into a fetch loop.

**Comment by ExtAnimal** [comment]
This is caused by the Scheduler continuing to operate and update itself and react to data changes while hidden.

It should do what Calendar widgets do. If a signal which updates the UI arrives while hidden, do not react to it, but queue it up until next shown.

```
    refresh() {
        const me = this;

        // If we're being called programmatically, cancel upcoming delayed refreshes.
        me.refreshSoon.cancel();

        // Only refresh immediately if we are visible.
        if (me.isVisible) {
            me.refreshNow();
        }
        // Otherwise wait till next time we get painted (shown, or a hidden ancestor shown)
        else if (me.findListener('paint', 'refreshNow', me) === -1) {
            me.on({
                paint   : 'refreshNow',
                thisObj : me,
                once    : true
            });
        }
    }
```
