### ISSUE TITLE
Milestone labels can overlap if close to each other

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3483]
Steps to reproduce:

1. https://bryntum.com/examples/scheduler/milestonelayout/
2. make the browser window narrower
2. change layout to Default
3. delete events

![milestone-overlap](https://user-images.githubusercontent.com/204844/135581660-838ee714-079a-4e5e-b0a1-16df8fcd03b9.gif)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=18940&p=93644#p93644)

And [here](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19957&p=99053#p99053)

When 2 milestones are close together the milestone names are overlapping. I would rather simply hide them. I tried using the "milestoneLayoutMode : 'estimate'," that doesn't seem to do anything. Is there a mechanism to do this?

**Comment by isglass** [comment]
That is the default and expected behavior for milestones
