### ISSUE TITLE
Overlay of the collapsed panel hides

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3498]
Reproducible on dragfromgrid demo: scheduler/examples/dragfromgrid/

https://user-images.githubusercontent.com/45400762/135832045-ab6f9c77-c1c4-47de-869b-9fde3bb03c06.mp4

**Comment by dongryphon** [comment]
I saw this happen once on Chrome but it won't reproduce for me anymore. I've tried Chrome and FF but they both are behaving correctly now. Can we screenshare to look at this if you can still reproduce it?
