### ISSUE TITLE
Support custom renderers for Calendar EventList view 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3500]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=18983&p=93868#p93868)

Not possible to define custom renderers/columns in EventList without overriding all predefined columns

**Comment by ExtAnimal** [comment]
Not sure what this could mean.

It's a `Grid`.

There are no event bars. It is just a grid view of the event records. Not sure what the forum post means. Grid row background colour? That can be done from the grid API I think.

**Comment by ExtAnimal** [comment]
Suggested  code in https://github.com/bryntum/bryntum-suite/pull/4186

Allows the user's `column` config to override the defaults as well as add new columns. Example is enhanced to show this.
