### ISSUE TITLE
Issue in DurationField setting units

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3504]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18996&p=93922#p93922)

`allowedUnits` and `unit` config doesn't do the job in `DurationField`. 

Open LIve example
https://www.bryntum.com/docs/scheduler-pro/#Core/widget/DurationField

and use this code

```
new DurationField({
    appendTo : targetElement,
    width    : 200,
    allowedUnits: 'hour',
    value: '5',
    label    : 'Duration'
});
```

it shows "5 days". Same if set `unit: 'hour'`.

**Comment by BrandonDH** [comment]
Hi, Is there any update here? I think I may be running into this issue when doing this `                        dependencyModel.setLag(getDependencyLag,'h') shows the same int for `h` and `d`.
`

**Comment by arcady-zherdev** [comment]
@BrandonDH No this is not the same issue. The reason if this case is UI level code and `dependency.setLag` is a data level method.
Please report on our forum (or make a separate ticket) and provide steps on how we can reproduce your issue.
