### ISSUE TITLE
State tracking manager logs incorrect steps when adding new event

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3530]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=18985&p=94058#p94058)

https://bryntum.com/examples/scheduler/undoredo/

Try to add new event, check logs. See 'Updated event "Your new event name"' instead of "Added new event". 

transaction.type returns UpdateAction type instead of AddAction, so it is not possible now to determine if an event

Another moment, create an event using dblclick, type a name, click save. 
Try to Undo your changes. See that 2 steps logged, frist one will revert event name, second one removes an event. 
Try the same using dragCreate, 3 steps recorded. 
See that frist Undo will cnagne the name, second one make an event smaller, 3rd one will remove an event.

**Comment by canonic-epicure** [comment]
I believe this has been fixed recently, I'll double check and close the ticket.

**Comment by canonic-epicure** [comment]
So this part 

> Try the same using dragCreate, 3 steps recorded.
> See that frist Undo will cnagne the name, second one make an event smaller, 3rd one will remove an event.

was fixed in #6699, but this part wasn't:

> Another moment, create an event using dblclick, type a name, click save.
> Try to Undo your changes. See that 2 steps logged, frist one will revert event name, second one removes an event.

**Comment by canonic-epicure** [comment]
Regarding 

> Try to add new event, check logs. See 'Updated event "Your new event name"' instead of "Added new event".
> transaction.type returns UpdateAction type instead of AddAction, so it is not possible now to determine if an event

This is up to the user how to implement transaction title calculation. In our demo we only look at the last action of the transaction and it case of drag-create it will be "edit event". User can implement a better function, that will be checking the 1st action of the transaction as well, which will be "add event". So this we are not going to address.
