### ISSUE TITLE
dragCreate takes wrong dates if weekStartDay is not default

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3544]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19071&p=94335#p94335)

Try to dragCreate an event from the line - beginning of a week, it will jumps to the day before.
![Screen Recording 2021-10-11 at 2 02 05 PM](https://user-images.githubusercontent.com/7203098/136945083-82da102c-13b3-4d52-8852-3ca195e9696e.gif)

Reproducible on week zoom level. Here is modifications for basic Scheduler example to reproduce the issue:

```
    startDate        : new Date(2017, 0, 1, 6),
    endDate          : new Date(2018, 0, 1, 20),
    viewPreset: {
        tickWidth: 75,
        shiftIncrement: 1,
        shiftUnit: 'day',
        timeResolution: {
          unit: 'week',
          increment: 1,
        },
        headers: [
          {
            unit: 'week',
            renderer: (start, end, headerConfig) => {
                return DateHelper.format(start, 'MMM YYYY');
            }
          },
          {
            unit: 'week',
            headerCellCls: 'week-view-preset-header-1',
            increment: 1,
            renderer: (start, end) => {
              return DateHelper.format(start, 'DD');
            }
          },
        ],
        columnLinesFor: 0,
      },
    weekStartDay: 1,
```

The `weekStartDay` config Scheduler has to be forwarded to every call which ends up in a DateHelper method which uses DateHelper.weekStartDay. 

- [x] startOf
- [x] getNext
- [x] getWeekNumber
- [x] snap

**Comment by bryandent** [comment]
Hi.  I was just wondering if this is prioritized for the 4.3.4 release as it's a big show stopper for us.  Also, I wanted to make sure that it's clear that this issue is not only for dragCreate but also editing of events, expand or contract as well.

**Comment by isglass** [comment]
It is targeting 4.3.4, but milestones are a plan rather than a promise. If it does not make the final cut for 4.3.4 it will be moved to 4.3.5

**Comment by matsbryntse** [comment]
DateHelper is not getting the value you set on the Scheduler. Workaround:

`DateHelper._weekStartDay = 1;`

**Comment by bmblb** [comment]
@bryandent could you please clarify editing problem? I reproduced issue with resizing but event editor works just fine

**Comment by bryandent** [comment]
We don’t use any of the widgets, so by editing I just mean dragging the handles on either side.

**Comment by bmblb** [comment]
ok, then it should be covered by this PR
