### ISSUE TITLE
Calendar Manager UI

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#356]
From https://bryntum.com/docs/gantt-for-extjs/#!/api/Gnt.widget.calendar.CalendarManagerWindow

**Comment by arcady-zherdev** [comment]
Screenshots of MSP UI for editing `Exceptions` (comes instead of `Day overrides` in ExtGantt)
![1](https://user-images.githubusercontent.com/6712184/149283531-4de21e29-7204-4308-b893-7183baec5d60.png)
![2](https://user-images.githubusercontent.com/6712184/149283535-d94a4125-31de-466c-8e2d-48beb38f1bb2.png)
![3](https://user-images.githubusercontent.com/6712184/149283537-d27c2257-621b-4bc6-a1e5-9dddacc86658.png)
![4](https://user-images.githubusercontent.com/6712184/149283541-9486b946-c3f0-4eab-a3e1-d89dba9fb697.png)

**Comment by pwmather** [comment]
Hey, do you have an update on estimated release date for this feature?

**Comment by arcady-zherdev** [comment]
No exact release date, sorry. We just have to switch to other issues from time to time ..so the deadline tends to move.
I think we can tell that the feature will be released by the end of this year.

We plan to support the existing data structure as much as possible.

**Comment by pwmather** [comment]
> No exact release date, sorry. We just have to switch to other issues from time to time ..so the deadline tends to move. I think we can tell that the feature will be released by the end of this year.
> 
> We plan to support the existing data structure as much as possible.

Hello, do you have an update for this feature?

**Comment by arcady-zherdev** [comment]
Hello.
The ticket is started but I had to jump to other more critical issues so couldn't finish as it was planned.
I'm going to get back to it when I'm done with my current tasks. That will happen in a week or two.
So in February if nothing crazy happens again I plan to get back working on this ticket.
Let's say Q1 is a next ETA for finishing this ticket.
Sorry about my rather inaccurate estimations..

**Comment by pwmather** [comment]
Hey @arcady-zherdev, 
No worries, thank you for the update.

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=117117#p117117) user asking for this

**Comment by pwmather** [comment]
Hi all, when this is released will Bryntum be removing the requirement to use later.js as this is a very old library that is no longer maintained [https://github.com/bunkat/later](url)?

**Comment by pwmather** [comment]
Hi @arcady-zherdev do you know if later.js will be removed with this update?

**Comment by pwmather** [comment]
Hey all, any update on this one?

**Comment by matsbryntse** [comment]
> Hi @arcady-zherdev do you know if later.js will be removed with this update?
We have no plans to remove later.js, we'll fix any bugs in its code if needed. We are not aware of any defects in later.

> Hey all, any update on this one?
This got delayed a bit and we are now targeting this for 6.0 which should be ready in Q2/Q3. Code completion should be done sooner so we could get you a beta build in Q2.

**Comment by pwmather** [comment]
Hey all, what is the latest for this feature? Keen to be able to add working patterns and holidays / non working exceptions for calendars.

**Comment by arcady-zherdev** [comment]
Hello,
We are working on the ticket at the moment and current state is:

- The data level got few changes (yet backward compatibility is kept as much as possible) and this part of code looks stable by now.
- The UI part is being developed at the moment. We've changed or mind on the way week availability UI should look (just to better support both desktop and mobile devices) and working on that now.

Holidays/exceptions are going to look more flexible when this ticket is done. We've added recurring exceptions support (like non working days starting every year on 21 Dec and finishing on 26 Dec).

Sorry that it takes longer than we thought. We just don't want to release a half-baked solution.

**Comment by pwmather** [comment]
Do you think this feature will be in any release this year @arcady-zherdev ?

**Comment by arcady-zherdev** [comment]
@pwmather Hey. Sorry I missed your question. Yes we plan to release it this year.

**Comment by pwmather** [comment]
No worries, thank you @arcady-zherdev

**Comment by arcady-zherdev** [comment]
@pwmather FYI the feature is in the middle of reviewing at the moment and we plan to merge it soon.
some sneak preview
![1](https://github.com/bryntum/support/assets/6712184/921d457d-1f89-4c08-a1fb-6436f6216640)
![2](https://github.com/bryntum/support/assets/6712184/1955e453-b399-4e27-8e01-86f408f86565)

**Comment by pwmather** [comment]
Thanks for the preview @arcady-zherdev  - that looks great!
