### ISSUE TITLE
Add support for naming calendar working time intervals

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3614]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19225&p=95040#p95040)

resource time ranges / time ranges can be labeled and a user can specify the label text (on the timeAxis's tbar for timeRanges, and on the timeAxis for resource time ranges). 
Should be possible to show labels for calendar intervals (configurable options) same as for resource time ranges.

Can be done as part of https://github.com/bryntum/support/issues/2175

**Comment by matsbryntse** [comment]
Already implemented
