### ISSUE TITLE
Panel collapse improvements

### ISSUE THREAD

**Issue by isglass** [bryntum/support#3625]
- [x] When collapsed to the right/left, the expand icon should go on top
- [x] Clicking collapsed header should expand (possibly configurable)

**Comment by dongryphon** [comment]
I don't see that example... can you show me the situation where the width is not working? It is sometimes difficult to remove all other opinions about the panel's with when going to a collapsed state. There is `width` and `flex` which are obvious but also cross-axis rules can affect it.
