### ISSUE TITLE
Splitter issues on touch devices

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3627]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=52&t=19249&p=95151#p95151

1. It is difficult to resize splitter in chrome's touch device emulator. Also difficult on a touch laptop.
2. Splitter used to expose collapse buttons in touch mode, it does not anymore.

Update: it is important to make sure problem in this ticket has not reappeared: https://github.com/bryntum/support/issues/1605

**Comment by ExtAnimal** [comment]
Works very easily in iPad. The hover area is augmented to be 2em wide on touch:

https://github.com/bryntum/support/assets/200516/05d44b7c-6d60-4770-8274-f647bd672213

**Comment by ExtAnimal** [comment]
The fix is for `BrowserHelper` to use `globalThis.matchMedia('(any-pointer:coarse)').matches` to detect whether touch geatures are possible. `globalThis.matchMedia('(pointer:coarse)').matches` means *only* touch gestures are possible.
