### ISSUE TITLE
[ANGULAR] Touch drag triggers scroll in Scheduler

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3632]
We need to add:
```
.b-dragcreating .b-grid-subgrid {
    touch-action:none ;
}
```
to our css. That resolves the issue.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19248&p=95217#p95217)

We're seeing an issue with the Angular Scheduler drag create and drag move on a touch device (such as a real iPad and Chrome in iPad simulation mode): it scrolls at the same time as the drag is occurring.  Errors in the console when using Chrome: "[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive."

This issue is reproduceable with the Angular Basic demo with scheduler version 4.3.1.  (The regular Basic demo works correctly on touch devices).

"@bryntum/scheduler-angular": "^4.3.1",
    "@bryntum/schedulerpro": "4.3.1",
    "@bryntum/schedulerpro-angular": "4.3.1",

**Comment by palmerzoo** [comment]
This doesn't resolve the issue because scrolling has already begun when the `b-dragcreating` class is applied.

**Comment by chuckn0rris** [comment]
Dupe, will be fixed here https://github.com/bryntum/support/issues/8619
