### ISSUE TITLE
ScrollEventIntoView does not work correctly with infinite scroll

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3636]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=19252&p=95159#p95159

1. Provide event renderer and output event id to tell events apart
2. set path to schedulerpro.umd.js
3. click on `next event` button few times

in console you'll see next selected event, but it is not always in view. it also depends on the action speed, different events fail to scroll into the view if you click button with different frequency

[test-case1.zip](https://github.com/bryntum/support/files/7440134/test-case1.zip)

**Comment by matsbryntse** [comment]
Not reproducible, please reopen with new steps sequence if still possible to reproduce
