### ISSUE TITLE
Dependency links are not shown up at browser zoom level 75% 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3645]
Confirmed in Chrome 

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=18335&p=95434#p95434)
https://www.bryntum.com/forum/viewtopic.php?f=44&t=19309&p=95444#p95444
Hi,

The issue seems to still exist on the latest bryntum build 4.2.4.
It occurs in chrome too through the following steps:

Open Bryntum advanced example - https://www.bryntum.com/examples/gantt/advanced/
Zoom out to 75%
Gantt zoom in once and then out, the dependency lines will not appear

**Comment by bmblb** [comment]
First screenshot shows `get dependencyGridCache` accessor which fills the grid cache, you may see it is triggered before the paint (green bars top row) which suggests that despite code is executed after all the domsync, DOM was not yet updated. This is the use case when we do not see dependencies after zoom in:

![image](https://user-images.githubusercontent.com/45400762/139807842-0d58eae0-34cc-424b-91ab-baa1974c23ec.png)

Second screenshot shows a modified code with `draw` moved not by one but two animation frames. You can see `get dependencyGridCache` is called after paint and in this case dependencies are rendered correctly:

![image](https://user-images.githubusercontent.com/45400762/139808263-3788da88-015a-4af8-8cc1-8dd5bc9427b8.png)

**Comment by bmblb** [comment]
While trying to reproduce user's test case we spotted 2 other issues. And originally reported issue is really a bug in chromium which is reported here: https://bugs.chromium.org/p/chromium/issues/detail?id=1266454
