### ISSUE TITLE
Renderer for Check Column not called when exporting

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3663]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=19340&p=95603#p95603)

I am using the Gantt though not sure if this is just a grid thing. If I try to use renderer with a check column it never gets called during export. It exports out a checkbox in excel and I want some text instead. Is there a way to get this to happen?

**Comment by ExtAnimal** [comment]
Probably the exporter class could be configured with its own renderers for columns which need special treatment *only for exporting*.

Rather than use the column's renderer, if it has its own renderer registered for a column use that.

That would save implementing if/else renderers in columns which would have to know who's doing the rendering.

**Comment by FlowIT-JIT** [comment]
The column renderers seems to be called only for _name_, _duration_, and our read only columns when exporting to Excel. Our renderer is not called for the wbs column, not for our date columns, and not for our checkbox columns. This unfortunately prevents us from using this feature.

@matsbryntse Are you able to prioritize and plan a fix for a patch release in the near future ? I'm fine with the use of args.isExport in the renderer to distinguish between HTML rendering and Excel rendering. - Thanks

**Comment by matsbryntse** [comment]
We'll have a look. WBSColumn seems to work fine for me. What version are you on?

**Comment by matsbryntse** [comment]
For date columns to have your renderer be called, please configure your Export feature with:
`
                exportDateAsInstance : false
`

**Comment by FlowIT-JIT** [comment]
@matsbryntse 
How do we use this with the Excel Exporter feature? TypeScript definitions have not been updated it seems, so not much help there. I have tried the following approach using https://bryntum.com/products/gantt/examples/exporttoexcel/

![image](https://github.com/bryntum/support/assets/10479064/beed8827-6e20-437d-82f6-4147747dd85e)

The renderer is registered for wbs, name, and startDate, and gets called for all three columns when rendering to the screen. But when exporting, the renderer is only called for wbs and name.

**Comment by matsbryntse** [comment]
Like so:
 ```
features : {
        excelExporter : {
          exporterConfig : {
                exportDateAsInstance : false
}

        }
    },
```

**Comment by FlowIT-JIT** [comment]
Thanks, @matsbryntse 😊
