### ISSUE TITLE
After switching mode, the current date is not displayed

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3664]
Can be reproduced in our vanilla demo:

![month-view-bug](https://user-images.githubusercontent.com/204844/140278201-5a49edc9-ae03-46e4-b351-b27233bc7564.gif)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=19334&p=95609#p95609)

Hi bryntum.
The current date did not display after i changed mode to "week" . 
When the date is not displayed but “No Resources” is displayed, the date switching button is also  invalid, and the dateRangeChange event cannot be triggered.
![pic2.png](https://www.bryntum.com/forum/download/file.php?id=15302)
![pic1.png](https://www.bryntum.com/forum/download/file.php?id=15301)

**Comment by ExtAnimal** [comment]
ResourceVIew.createView needs

![Screenshot 2021-11-04 at 13 21 16](https://user-images.githubusercontent.com/200516/140312513-89abd891-2ea2-4763-b901-e5c30f82adeb.png)
