### ISSUE TITLE
constrainDragToResource breaks with partnered scheduler

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3666]
Confirmed. It behaves as described by the user.

![partners-bug](https://user-images.githubusercontent.com/204844/140319953-8f7e6a71-1a09-4df6-a460-e44113ca4cee.gif)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19347&p=95642#p95642)

constrainDragToResource seems to break letting go of an event over a partnered scheduler. It freezes the elements "drag" ui and fires eventListeners in partnered resource.

To reproduce: 
https://bryntum.com/examples/scheduler/drag-between-schedulers/

set constrainDragToResource: true in featuers in scheduler 1

Take an element, and start dragging it (it will be locked to the resource) whilst dragging, move mousepointer over the partnered scheduler (imagine u actually can drag the element there) and then "drop" the event.  

The event will lock itself and listeners will be fired

**Comment by matsbryntse** [comment]
This configuration is not reasonable:
```
eventDrag : {
            constrainDragToTimeline : false,
            constrainDragToResource : true
        },
```
