### ISSUE TITLE
Effort value NaN seen in 'change' event listener

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#368]
Listen for taskStore change while indenting a task  ('indent' branch)
<img width="1133" alt="Screenshot 2020-02-27 at 20 18 01" src="https://user-images.githubusercontent.com/218570/75478438-45dc6d00-599e-11ea-8ee8-a6466e7da8c8.png">

**Comment by ExtAnimal** [comment]
Need more info to reproduce this. But with the full repro info, it shouldn't be that difficult to fix.

If a record initially has an effort value which `isNaN`, that is one bug.

If part of a propagate operation *sets* the value to `NaN`, that's another bug.

Finally, the change detection in `Model.set`. In theory `NaN`->`NaN` is not a change, but Javascript reports that `NaN` is not equal to `NaN`, so the `isEqual` call needs to handle that.
