### ISSUE TITLE
Add option to disable resizing specific time ranges

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3686]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19380&p=95823#p95823)

Like in topic. 
We can enable rezizing in feature config by enableResizing setting, but I can't see any prop I can set draggable: false to time range model added to timeRangesStore.

How this is working in Now timerange?

**Comment by dcruz1990** [comment]
Is there a way to disable specific time ranges and dates in Calendar? how can i achieve that?

**Comment by matsbryntse** [comment]
@dcruz1990 Could you please open a new thread in our forums with details about your use case? https://forum.bryntum.com/

**Comment by matsbryntse** [comment]
Can be solved by setting TimeRange model `readOnly : true`
