### ISSUE TITLE
Add isSelectable template method

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3692]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18131&p=95858#p95858)

Great! For the same reasons, could you also please implement isSelectable for TaskBoard.view.mixin.TaskSelection? We've recently found a need for that as well.

**Comment by isglass** [comment]
Duplicate of https://github.com/bryntum/support/issues/4213, which is about to be resolved
