### ISSUE TITLE
Infinite scroll should provide an easy way to limit the scrolling

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3694]
Requested here:

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=18489&p=95729#p95729)

Hi,

In scheduler pro, user can zoom out with scroll to 100 years range.
I want only to zoom out Calendar start & end dates range.

Is this possible?

Thanks

**Comment by taauntik** [comment]
another request [here](https://forum.bryntum.com/viewtopic.php?p=130338#p130338)

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/3870
