### ISSUE TITLE
TaskEdit feature should trigger preventable beforeTaskEdit event

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3714]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=56&t=19444&p=96139#p96139)

Hi bryntum team.
I want to use customized editor in taskboard .In calendar, I can prevent the default editor from opening by modifying  "beforeEventEdit", and open my customized editor . which method can do that in taskboard ?

**Comment by isglass** [comment]
Was fixed back in may as part of bryntum/support#4215
