### ISSUE TITLE
dataSource property not working on dependency from and to fields

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3720]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19449&p=96218#p96218)

Afternoon,

We're looking at using the dataSource property for our dependency fields so we can map to our backend DTOs. We had no problem doing this with task. However, it appears that the dataSource property isn't working properly from 'from' and 'to' fields on dependency - either that or we're getting it wrong. Either way I'd appreciate your support  

I'd modified the advanced example as follows (I've attached it for each of reproduction):

I've added a custom dependency model:

```
import DependencyModel from '../../../lib/Gantt/model/DependencyModel.js';

export default class Dependency extends DependencyModel {

static get fields() {
    return [
        {
            name: 'fromTask',
            dataSource: 'mapFromTask'
        },
        {
            name: 'toTask',
            dataSource: 'mapToTask'
        },
        {
            name: 'lag',
            dataSource: 'mapLag'
        }
    ];
}
}

```

And then modified all the data in 'launch-saas.json' to change the names of the dependency fields like so:

```
...
      {
        "id"       : 1,
        "mapFromTask" : 11,
        "mapToTask"   : 15,
        "mapLag"      : 2
      },
...

```

I've then also modified the app.js in the example to import the dependency model class and set it on the project config using 'dependencyModelClass'.

I would expect this to load dependencies without issue, but it doesn't none of the dependencies get loaded. I think this is an issue with the mapping of the from and to fields.

I believe this because I followed these steps:
Add a new dependency
Log out the dependencies window.bryntum.query('gantt').project.dependencyStore.allRecords
Compare the values between one of the loaded in dependencies and the one we just created

The dependency loaded in populates 'mapFromTask', 'mapLag' & 'mapToTask'. The new dependency populates 'mapLag' but not the others. This suggests that the mapping isn't setup correctly because it isn't mapping the dataSource on the new records?

Any advice is appreciated, thanks

**Comment by matsbryntse** [comment]
`NOTE: This is not a proper field but rather an alias, it will be serialized but cannot be remapped. If you need to remap, consider using from instead.`

**Comment by bmblb** [comment]
There are still few problems to solve

### from/to fields mapping problem

Steps to reproduce on advanced demo:

1. in launch-saas.json replace fromTask -> fromFoo, toTask -> toFoo
2. declare dependency model and use it in project:
```
class MyDependencyModel extends DependencyModel {
    static get fields() {
        return [
            { name : 'from', dataSource : 'fromFoo' },
            { name : 'to', dataSource : 'toFoo' }
        ];
    }
}

const gantt = new Gantt({
    project : {
        dependencyModelClass : MyDependencyModel,...
    }
})
```

fromEvent and toEvent fields can be mapped.

### general inconsistency in our data samples

1. We use `fromTask` in the advanced demo dataset. But in the docs we mention this field should not be used:
```
NOTE: This is not a proper field but rather an alias, it will be serialized but cannot be remapped. If you need to remap, consider using from instead.
```
This field actually cannot be remapped.
2. We use `from` in the inline dependencies demos. This field also cannot be mapped.
3. We have a field `fromEvent` which we do not use in the demos, but it works, it is the proper field to use and it can be mapped
