### ISSUE TITLE
Resource assignment field should not overflow

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3728]
![image](https://user-images.githubusercontent.com/45400762/141748153-dfa79aef-418c-46b4-be71-c146034a5c70.png)

**Comment by ExtAnimal** [comment]
The `ChipVIew` `<ul>` element has the class `b-hide-scroll`. That has these rules:

```
    &.b-hide-scroll {
        // Blink and WebKit support: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
        &::-webkit-scrollbar {
            display : none;
        }

        // Firefox support: https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width
        scrollbar-width    : none;
    }
```

All modern browser engines support this. There must be something else on that platform that nobody else can reproduce. The person who is able to reproduce this needs to investigate.

**Comment by bmblb** [comment]
Not reproducible anymore
