### ISSUE TITLE
Display unassigned events in Scheduler (pro) without manipulating dummy resources and assignments

### ISSUE THREAD

**Issue by andreas-sakellariou** [bryntum/support#3731]
Feature request:
Sometimes using Scheduler Pro, there is a need to display a set of events that are not assigned in any resource. Currently, this "simple" operation requires creation of dummy resources, assignments and manipulation of stores.

It would be nice to have the above functionality in a very simple way and be able to switch between that and regular resource-bound events.

**Comment by matsbryntse** [comment]
Doesn't this type of UI give you a good overview of unassigned? 

https://www.bryntum.com/examples/scheduler-pro/drag-from-grid/

**Comment by andreas-sakellariou** [comment]
As far as I understand the unassigned events are displayed in the list at the right, that is in textual form. The are visualized only upon assignment.

What I am talking about is to visualize unassigned events on a scheduler's timeline.

**Comment by metratek** [comment]
I noticed that there is a related post from 2018 asking for a similar feature: https://www.bryntum.com/forum/viewtopic.php?f=1&t=9810

**Comment by matsbryntse** [comment]
This demo shows exactly this, will it suffice for you? https://bryntum.com/products/scheduler/examples/shared-crudmanager/
