### ISSUE TITLE
Firefox zoom and drag'n'drop issues

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3738]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19466&p=96315#p96315)
And [here](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19553&p=97083#p97083)

Prerequisites:
Firefox 94, Drag from grid example https://bryntum.com/examples/scheduler/dragfromgrid/

Steps to reproduce:
Zoom out with Ctrl+mouse wheel
Scroll right or left with Shift+mouse wheel
Try to drag tasks from grid
Try to Zoom in/out with Ctrl+mouse wheel

What happens:
You cannot drop a task to the resource free time, current resource is not highlighted.
You cannot zoom the scheduler in/out anymore, the whole view is zoomed.

What should happen:
You can drop a task to the resource
You can zoom in/out

Video is here https://drive.google.com/file/d/1E_Jo1RK1ZjEPJxqv225zOOZG9p5GVd4J/view?usp=sharing

**Comment by matsbryntse** [comment]
Likely dupe of #3815

**Comment by matsbryntse** [comment]
Ping @bmblb please retest with PR for 3815

**Comment by bmblb** [comment]
Not reproducible after this 3815 is resolved
