### ISSUE TITLE
Removing a resource with visible events then adding it does not re-render the events

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#3762]
Just remove and re-add a resource in any example.

**Comment by ExtAnimal** [comment]
`scheduler.removeUnassignedEvent = false` doesn't help.

**Comment by ExtAnimal** [comment]
In the debugger, remove a resource. The row disappears. Add it back, and the row for the resource is appended, but it has no events in it.

The events get deassigned from the resources when the resource is removed.

Which makes total sense. If a resource has **_gone_**, then no events can be assigned to it. And they are almost asking for magic to have the events reattach. But should be possible because of the field modified tracking.

But the deassign process doesn't track the `resources` field in the `modified` property. If we can make assigning/deassigning update that, then we could optionally *re*assign an event using that.

**Comment by chuckn0rris** [comment]
Not a bug. When a resource is removed from a store, all events are unassigned. If a resource with the same id will be added again, it doesn't mean that is an old resource and all changes should be reverted automatically. It is counted as a new resource, which is correct. The only way when all should be reverted, is clear Undo operation with STM manager.
