### ISSUE TITLE
Flaky locked grid row hover effect when moving mouse over task labels

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#377]
https://bigfiles.assembla.com/spaces/cHlz5-LZyr4kUleJe5cbCb/documents/download/dJNV8MuYGr6zTZcK-zJOy8

**Comment by isglass** [comment]
We no longer use grid row hover effect when hovering schedule, but keeping ticket since the background of the row number column blinks when moving mouse over tasks / rows

**Comment by isglass** [comment]
And that is not longer reproducible either, closing
