### ISSUE TITLE
Writing notes to a task then closing the panel with ESC doesn't rollback notes

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3772]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19529&p=96599#p96599)

How to reproduce
Open GanttTaskEditor.
Switch to notes tab.
Write notes.
Close the editor by pressing the escape key.
Open the editor again.

			
		
		
				
			 notes_remains.mp4
						(758.04 KiB) Not downloaded yet
		
		
			

Expected
Written notes are rollbacked to the one before the edit.

Actual
Written notes remains.
The note field of the task seems to be updated sometimes. But sometimes not.

Additional info
It's reproduced at https://bryntum.com/examples/gantt/basic/

**Comment by canonic-epicure** [comment]
Not reproducible anymore:

https://github.com/bryntum/support/assets/72431/331ffb1d-ac9a-49f2-a8db-66bee3d28d28
