### ISSUE TITLE
visibleDate config does not work when autoHeight is set to true

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3784]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=19503&p=96664#p96664

To reproduce on pro histogram demo:
1. change date configs to this
```
startDate         : new Date(2020, 0, 1),
visibleDate       : { date: new Date(2020, 3, 29), block:'start' },
endDate           : new Date(2021, 0, 1),
// autoHeight : true,
```
2. remove partner config from histogram

You'll see first visible date correctly at first, but when you uncomment autoHeight scroll will be set to 0

**Comment by andreas-sakellariou** [comment]
if visibleDate is not present but instead a scrollToDate() is used inside an onMounted(), the scrollToDate() has no effect also.

**Comment by traderGoga** [comment]
hello, is the scrollToDate() already fixed?

**Comment by matsbryntse** [comment]
This is now resolved!
