### ISSUE TITLE
Erratic dragging when using getDateConstraints 

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3786]
The dragging becomes erratic/unpredictable when `getDateConstraints` is used. To reproduce, paste the following code to on-line gantt basic demo code editor:
```

    getDateConstraints(taskRecord) {
        const constraints = {
            start : new Date('2019-01-17 00:00'),
            end   : new Date('2019-02-05 00:00')
        };
        console.log(constraints);
        return constraints;
    },
```
The result:

![get-date-constraints](https://user-images.githubusercontent.com/204844/142833037-63c6f52f-4462-43a2-b32a-3fd6a5f61605.gif)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=19519&start=10)

Early/late dates are calculated by the project. They are not constraining the task, they show earliest/latest date task could begin/end.

If you don't want task to be dragged past certain date I would recommend validator fn, please see link above.

**Comment by matsbryntse** [comment]
Fixed for 5.0 already
