### ISSUE TITLE
if visibleDate is not present but instead a scrollToDate() is used inside an onMounted(), the scrollToDate() has no effect also.

### ISSUE THREAD

**Issue by metratek** [bryntum/support#3791]
if visibleDate is not present but instead a scrollToDate() is used inside an onMounted(), the scrollToDate() has no effect also.

_Originally posted by @andreas-sakellariou in https://github.com/bryntum/support/issues/3784#issuecomment-976166492_

The above is valid if a block is defined in the scrollToDate() function, for example scrollToDate(new Date(2020,10,14), {block: 'start'})

**Comment by matsbryntse** [comment]
@metratek Can you still reproduce this in 6.0+? If so, please let us know and we'll reopen this ticket.

**Comment by metratek** [comment]
I would like to check it in clean code. Are the examples in the Bryntum site running on 6.0.2 or 6.0.3 to use them as basis to attempt to reproduce the issue?
