### ISSUE TITLE
Stm manager clears duration on undo action

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3806]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19553&p=96901#p96901)

To reproduce enable stm with `autoRecord: true` in SchedulerPro `drag-from-grid` demo, and put undoredo widget. Required changes:
```
import '../../lib/Scheduler/widget/UndoRedo.js';
// ....

    tbar : [{
        type  : 'undoredo',
        icon  : 'b-fa-undo',
        items : {
            transactionsCombo : {
                width : 250,
                displayValueRenderer(value, combo) {
                    const stmPos = combo.up('panel', true).project.stm.position || 0;

                    return stmPos + ' undo actions / ' + (this.store.count - stmPos) + ' redo actions';
                }
            }
        }
    }],
    project   : {
        stm : {
            autoRecord : true
        },
```

Grid has records with `duration` set and no startDate/endDate. You can verify in the console.

1. Drag and drop one of the records to the timeAxis.
2. Undo your changes.
3. Check that event record has `duration` = null. Should be old value because it wasn't changed on that action.

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/3f613fd0-1700-45cf-bb19-1d0975b9d3e1
