### ISSUE TITLE
[TaskBoard]  Using `datetimefield` inside the Taskboard modal

### ISSUE THREAD

**Issue by badrAZ** [bryntum/support#3809]
### Issue

The TaskBoard modal isn't populated when using `datetimefield` as field type instead of `date`.

### Step to reproduce

Replace the `date` field type by `datetimefield` in this bryntum example: https://bryntum.com/examples/taskboard/task-edit/

**Comment by isglass** [comment]
Duplicate of https://github.com/bryntum/support/issues/3882
