### ISSUE TITLE
Event listeners stop working properly after scroll using Firefox

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3815]
I have reproduced it with the steps given in the below forum post. In #3 "Scroll vertically..." only mouse wheel turn is necessary, no visual scroll is needed.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19605&p=97098#p97098)

Hi, 

I am currently having trouble, that some event listeners won't get triggered anymore, after I performed a vertical scroll in the scheduler component. This issue seems to be related to Firefox (tested with v94.0.1), as I could not reproduce it when using Chrome.

To reproduce this on your own, you can use your basic example from here:
https://bryntum.com/examples/examples-scheduler/basic/

Do the following steps then:

1. Make sure there is no vertical scrollbar in the schedule
2. (Optional) Double click into a cell (this will open the event create popup which is the correct behavior) and close it again
3. Scroll vertically with your mouse ("trigger native scroll")
4. Double click again into a cell --> See that the event create popup won't be opened again

It looks like the focus of the schedule is somehow lost, when doing this native scroll on Firefox. And as a consequence the event listeners stop working. When having a vertical scrollbar the issue disappears.

**Comment by ShubhamJainSJ** [comment]
@jsakalos Do we have a release date for version `4.3.5` which resolves this issue?
