### ISSUE TITLE
"move" event is not triggered when moving a node in a TreeStore

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3816]
inconsistent with flat store

https://www.bryntum.com/forum/viewtopic.php?f=43&t=19588&p=97105#p97105

**Comment by ExtAnimal** [comment]
In the case of a tree, the relevant in formation which must be sent to a backend is the newParent which the record must be added to, and the index within that newParent where the record must be placed (or more usefully, the id of the following sibling).

All the information about moving a node from one place in a tree to another is already available through the Store `update` event which announces record mutations.

The record has two fields which identify its place in a tree structure:

- parentId - The id of its parent node
- parentIndex - The index within its parent nodes children collection

Any mutation to either of these is announced through the update event. It will look something like this:

```
{
    record: movedRecord,
    records: [movedRecord],
    changes: {
        parentId: {
            value: 9,
            oldValue: 3
        },
        parentIndex: {
            value: 3,
            oldValue: 2
        }
    },
    batch: false,
    source: theStore,
    type: 'update'
}
```

I suggest that the API is already present and this ticket can be closed. Maybe with some increased documentation around this area.
