### ISSUE TITLE
DayLayout error when dayspanning event competes with other events.

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#3845]
Configure the Calendar with

```
modes : {
    week : {
        showAllDayHeader : false
    }
}
```

Which means interDay events will show in the day columns.

Then create a new event which begins just after Breakfast on the 12th and spans several days.

The start block of the new event is *below* the shorter events of that day - it does not join their cluster:

![Screenshot 2021-12-02 at 15 12 30](https://user-images.githubusercontent.com/200516/144438487-004d2499-07f6-4ac9-8449-06d0ef3a6f61.png)

**Comment by dongryphon** [comment]
This was fixed some time ago

![image](https://user-images.githubusercontent.com/722969/179375680-296bd9c4-1f19-4828-9006-30f9fee12fb4.png)
