### ISSUE TITLE
[TaskBoard] Duplicated description value on overriding its field in `bodyItems`

### ISSUE THREAD

**Issue by badrAZ** [bryntum/support#3847]
### Issue

Overriding the `description` field in `bodyItems` makes its value displayed multiple times.

### Step to reproduce

Add the bellow entry to the [example's](https://bryntum.com/examples/taskboard/column-drag/)  `bodyItems` and edit the field using the task editor modal.

```
      description: {
        type: 'template',
        template({ taskRecord }) {
          const { description } = taskRecord;
          return description && {
            html: `<span>${description}</span>`
          }
        }
      },
```

**Comment by isglass** [comment]
Try using key `text` instead of `description`, as listed here in docs: https://bryntum.com/docs/taskboard/api/TaskBoard/view/mixin/TaskItems#configuring-which-items-to-use
