### ISSUE TITLE
minDate / maxDate option for timeline when zooming

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3870]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19718&p=97656#p97656)

- [x] Boundaries for infinite scroll
- [x] Shifting time axis
- [x] Prevent zoom from going too "wide"

Hi,
I work with scheduler 4.3.3 and angular 13.
I need be able to limit the timeline even from scroll/zoom events.
Provide some min start date and max end date and no scroll or zoom can change it.

Is it possible?

**Comment by yakeer** [comment]
@matsbryntse, the one of them the issues in the zooming functionality.

**Comment by taauntik** [comment]
requested here https://forum.bryntum.com/viewtopic.php?p=128622#p128622 too

**Comment by yakeer** [comment]
Any plans to implement this feature?

**Comment by matsbryntse** [comment]
Yes for sure, we'll get to it soon!

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?p=130721#p130721

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?t=12160

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?f=44&t=27867&p=139741#p139741

**Comment by yakeer** [comment]
Hey,
Any ETA for this task?

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?p=147618#p147618
