### ISSUE TITLE
Wrong event height if custom eventRenderer used with changing draggable flag

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3871]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19720&p=97684#p97684
Use attached code to reproduce the problem. 

zoom out to see events, scroll down up to see events with wrong height. Try to remove line with set `eventRecord.draggable` flag, all works great.

[app.js.zip](https://github.com/bryntum/support/files/7677257/app.js.zip)
)

**Comment by matsbryntse** [comment]
Data should never be changed in eventRenderer
