### ISSUE TITLE
Columns in the collapsed region should not be rendered

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3879]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=51&t=19735&p=97754#p97754

To reproduce on grid/examples/lockedcolumns/ demo:
1. add renderer:
```
{
    text   : 'Surname',
    field  : 'surName',
    width  : 180,
    locked : true,
    renderer({ value }) {
        console.log(value);
        return value;
    }
}
```
2. set config:
```
subGridConfigs : {
    locked : {
        collapsed: true
    }
}
```
3. start demo, scroll around, see nothing is logged
4. now expand and collapse region and scroll again - renderer logs values to the console

**Comment by matsbryntse** [comment]
Not reproducible in latest sources
