### ISSUE TITLE
Scrollbar should not be seen when timeaxis ticks has to be stretched to fit viewport

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#388]
If viewed timespan does not fill the available width, the time axis is stretched to fill width. This should not lead to a visible scroll bar. 

https://www.bryntum.com/forum/viewtopic.php?f=51&t=13480

**Comment by ExtAnimal** [comment]
it *should* be as simple as `scheduler.scrollable.overflowX = false`

That should work, and if it doesn't, then it's a bug in `GridScroller`. That should basically set the `overflow-x : hidden` style on the scrolling elements, and hide the fake scrollbars.

**Comment by ExtAnimal** [comment]
Update: that does in fact work.

**Comment by matsbryntse** [comment]
It's not the right fix, I suspect somewhere we're using ceil, where in this case we should use floor

**Comment by SergeyMaltsev** [comment]
This is how it looks like
![ResizeScroller](https://user-images.githubusercontent.com/57486330/104415462-4244db00-559c-11eb-9c3c-80ebef410485.gif)

**Comment by ExtAnimal** [comment]
`TimeAxisViewMode.forceFit` causes use of floor in `TimeAxisViewMode#calculateTickSize`

**Comment by ExtAnimal** [comment]
I've been here before, suggested a fix and got shot down, so this is my last attempt.

**Comment by isglass** [comment]
Not reproducible, we changed approach to calculating fractional tick sizes mid 2021
