### ISSUE TITLE
Calendar Print Feature doesn't work for AgendaView

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#3884]
It produces blank pages:

![Screenshot 2021-12-10 at 08 09 39](https://user-images.githubusercontent.com/200516/145532340-69c050cf-5402-4efd-ae1f-c35f30717c44.png)

**Comment by ExtAnimal** [comment]
The list view doesn't work either. Both are based on the same base which is a `Grid` which will have virtualized rendering. So the Grid print code will have to be called.

**Comment by ExtAnimal** [comment]
Work started here: https://github.com/bryntum/bryntum-suite/pull/4712

**Comment by luisfuertes** [comment]
Any update about this?
