### ISSUE TITLE
Add support for sticky event labels

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#390]
Enable by default for Scheduler + Scheduler Pro.

So it's always possible to see the time axis label when scrolling and a timeaxis is header is very wide
https://codepen.io/michaelwhyte/pen/veVdEx

Requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=11132
and here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=11361
and here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=11662
+ https://www.bryntum.com/forum/viewtopic.php?f=44&t=12769

Work started on branch 7268-sticky

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/2459
