### ISSUE TITLE
ProjectModel ignores fields dataSource specification

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3903]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19781&p=98104#p98104)

Hello,

I've been trying to use dataSource on project model fields in order to map from a server defined object. This works with task and dependencies, but I cannot get the mappings to work with project.

The following codepen has a live demo of the current situation. I have extended Task and Project and used them within the Gantt widget, but only Task dataSource fields seem to take effect: 

https://codepen.io/Howrd/pen/NWaRRvv

Toggle lines 47 and 48 to see what I mean.

The flag displays correctly when loaded with "startDate", but the flag is incorrect when using the dataSource "Start_Date__c" field. Am I misunderstanding how dataSource is applied to models?

Thanks

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=128664#p128664) for this
