### ISSUE TITLE
Child field inherits progress value from the parent 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3911]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=19796&p=98188#p98188)

**Current behavior**

The child of the first task has values inherited from the parent.

**Expected behavior**

The children values should not be inherited from its parents.

**Step to reproduce**

Replace the basic example implementation by the below implementation.

```
import { Gantt } from "../../build/gantt.module.js?455384";

new Gantt({
  appendTo: "container",
  
  columns: [
    { type: "name", width: 250 },
    {
      field: "progress",
      text: "progress",
      renderer: ({ record }) => record.progress && `${record.progress}%`,
    },
  ],
  
  tasks: [
    {
      id: "data1",
      name: "data1",
      progress: 33,
      children: [
        {
          id: "data1Child",
          p
          name: "data1Child",
        },
      ],
      },
      {
        id: "data2",
        name: "data2",
        progress: 33,
        children: [
          {
            id: "data2Child",
            name: "data2Child",
          },
        ],
      },
    ],
});
 
```

data1Child has incorrect progress value

**Comment by arcady-zherdev** [comment]
This is by design. When `renderer` function returns `undefined` means is does `cellElement` mutating in that case Gantt does not update the cell. It's mentioned in the docs https://www.bryntum.com/docs/gantt/api/Grid/column/Column#config-renderer

The `renderer` should return an empty string to update a cell w/ an empty value:
```js
new Gantt({
    ...
    columns : [
        ...
        {
            field    : 'progress',
            text     : 'progress',
            renderer : ({ record }) => record.progress ? `${record.progress}%` : ''
        }
    ],
```
