### ISSUE TITLE
ScrollManager does not start vertical scrolling if mouse leaves scheduler element

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#394]
https://bryntum.com/examples/scheduler/bigdataset

1. Drag from top scheduler to below bottom
2. Back up to scheduler bottom edge, scrolling does not start. Only if mouse comes in from above

https://www.bryntum.com/forum/viewtopic.php?p=70134#p70134

https://www.bryntum.com/forum/download/file.php?id=9890

**Comment by SergeyMaltsev** [comment]
If you drag event below Scheduler's bottom then it is quite hard to scroll scheduler again with this dragging event until you move event above sensitive scroll area and then move down again.

![DragScroll](https://user-images.githubusercontent.com/57486330/76077885-c10bd780-5fcb-11ea-8fc6-a3a1cd55eaef.gif)
