### ISSUE TITLE
Showing task editor for a task partially visible task changes scroll

### ISSUE THREAD

**Issue by isglass** [bryntum/support#40]
It should not. To reproduce, try this on console in the Gantt basic demo:

`gantt.setStartDate(new Date(2019,0,20))`

<img width="546" alt="1" src="https://user-images.githubusercontent.com/5415653/69324109-25d33a00-0c48-11ea-8234-b35466633408.png">

Then double click a task that is partially out of timeaxis (Setup web server).
It focuses the task and extends the timeaxis. It should focus but not extend

<img width="555" alt="2" src="https://user-images.githubusercontent.com/5415653/69324140-3683b000-0c48-11ea-97db-aa2823c5b80f.png">

**Comment by pmiklashevich** [comment]
Related ticket: https://github.com/bryntum/support/issues/58

**Comment by pmiklashevich** [comment]
User requests a flag to be able to disable scrolling events into view:

> Can we somehow disable this click behavior that it scrolls to the end of the event when you click on it

**Comment by isglass** [comment]
Also related: bryntum/support#105
