### ISSUE TITLE
TaskTooltip should use custom percentDone field if specified.

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#4006]
When a custom field is being used in the PercentDone feature, the TaskTooltip is still looking at the percentDone field, and shows 0%

![Screenshot 2022-01-12 at 13 03 35](https://user-images.githubusercontent.com/200516/149137666-930e12d3-d1d0-474f-8a37-a005ce92af75.png)

I suggest we deprecate, then quickly remove the usage of custom field in the PercentBar feature. Because I don't think it's being used because when used the `TaskTooltip` immediately looks wrong with `0%` showing, so this would have been reported.

**Comment by isglass** [comment]
Client might change field for PercentDone feature to indicate something completely different, dont think we can assume tooltip should reflect. Easy enough to implement a custom template for the tooltip
