### ISSUE TITLE
Document event mouse events

### ISSUE THREAD

**Issue by isglass** [bryntum/support#4020]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=20012&p=99208#p99208)

Currently only `eventClick` is documented.
Add docs for:

- [x] eventMouseOver
- [x] eventMouseDown
- [x] eventMouseUp
- [x] eventMouseOut
- [x] eventDblClick

**Comment by ExtAnimal** [comment]
It has all these. But they are named by the usual names. So it's `eventdblclick`, not `eventdoubleclick`. None of our products map the native `dblclick` event to `doubleclick`

![Screenshot 2022-01-14 at 12 03 23](https://user-images.githubusercontent.com/200516/149505430-762f7838-cfe6-497d-b2a1-8f0cd1957131.png)
