### ISSUE TITLE
Gantt dependency feature missing proper documentation

### ISSUE THREAD

**Issue by hazemKrimi** [bryntum/support#4027]
I am looking for a way to improve dependency pathfinding between events. Found that I can specify a pathFinderConfig but don't know the object format.

Doc: https://www.bryntum.com/docs/gantt/api/Gantt/feature/Dependencies#config-pathFinderConfig

**Comment by matsbryntse** [comment]
@hazemKrimi It's better you ask in our support forums here: www.bryntum.com/forum

GitHub is for bugs / feature requests only.
