### ISSUE TITLE
Time axis broken after creating event ending outside view

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#406]
Vue Custom Event Editor demo

https://www.loom.com/share/ded685a9935549ed91a23d67bc7c79a1

**Comment by jsakalos** [comment]
I cannot reproduce it in the latests `release` branch but it is broken on site. It is probably related to the fixed but yet unreleased bug: https://github.com/bryntum/support/issues/380

Re-test on site after release.

**Comment by jsakalos** [comment]
Re-tested this issue cannot be reproduced on-line anymore. 

https://bryntum.com/examples/scheduler/vue/javascript/custom-event-editor/dist/index.html
