### ISSUE TITLE
Add resource time ranges support to Calendar ResourceView

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4062]
Similar to Scheduler's https://bryntum.com/examples/scheduler/resourcetimeranges

+ add feature to ResourceView demo

**Comment by ExtAnimal** [comment]
Also TimeRanges could be done in the same context: https://github.com/bryntum/support/issues/1166

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?f=54&t=20104&p=115943#p115943) user asking for this feature.

**Comment by ExtAnimal** [comment]
Fixed by https://github.com/bryntum/bryntum-suite/pull/6394

**Comment by lx-0** [comment]
Is this Feature documented somewhere? It is not in the ResourceView Demo nor in the ResourceTimeRange documentation. I have the same feature request and I did not manage to enable it in Calendar ResourceView in version 5.4.1.
