### ISSUE TITLE
zoomToSpan doesn't work with infinite scroll enabled

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4070]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20128&p=99813#p99813)

Try to call in https://bryntum.com/examples/scheduler/infinite-scroll/
```
scheduler.zoomToSpan({
        startDate:new Date('2017-01-02T00:00:00'),
        endDate:new Date('2017-01-02T23:59:00')
        })
```

It works in basic example

**Comment by isglass** [comment]
Seems to have been fixed since the ticket was created
<img width="1633" alt="Screenshot 2022-07-28 at 07 52 03" src="https://user-images.githubusercontent.com/5415653/181430570-ef380300-4f30-4d9a-9c3b-890e991042db.png">
