### ISSUE TITLE
[REACT] onPaint listener on wrapper broke sorting

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4074]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20127&p=99828#p99828)

Try to add listener to grid wrapper like this

```
            <BryntumGrid
                ref={grid}
                {...useGridConfig(handleCellButtonClick)}
                rowHeight={rowHeight}
                onSelectionChange={handleSelectionChange}
                onPaint={() => console.log('paint')}
            />
```
Open app and try to sort by click on column's header, it doesn't work.

**Comment by matsbryntse** [comment]
Should not be reproducible any longer as we do not use onPaint internally any longer
