### ISSUE TITLE
Make dependency line easier to hover (its hit area wider)

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#41]
Requested here
https://www.bryntum.com/forum/viewtopic.php?f=44&t=12731
https://www.bryntum.com/forum/viewtopic.php?f=51&t=21001&p=103962#p103962
https://www.bryntum.com/forum/viewtopic.php?f=52&t=21888&p=108180#p108180

> It is really difficult to hover the cursor on this one pixel line. I
s there a way to increase the amount of hoverable space on these lines?

**Comment by egraves-accuer** [comment]
upvote for this one.
