### ISSUE TITLE
Remove EventMode column

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#4115]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=20201)

Hi,

is there a difference between these two columns? They seem to refer to the same data field.

Thanks, Peter

**Comment by isglass** [comment]
My vote is on removing the EventMode column, ManuallyScheduled is simpler and sufficient IMO

**Comment by arcady-zherdev** [comment]
Not sure why we have two columns. I agree `ManuallScheduledColumn` is enough.
