### ISSUE TITLE
Wrong position of cell editors in scrolled subgrids

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4119]
Open https://bryntum.com/examples/gantt/advanced/

Make browser window smaller to see scroll on grid section. Dblclick on ResourceAssignmentColumn to open an editor. See wrong position.
<img width="552" alt="Screenshot 2022-02-04 at 15 07 41" src="https://user-images.githubusercontent.com/7203098/152486722-5850a2ae-09a6-409a-8c0f-759f342c59b7.png">

**Comment by isglass** [comment]
Affects all cell editors, try it for example on https://bryntum.com/examples/grid/multiregion/

**Comment by isglass** [comment]
Test pushed to branch 4119-scroll-editor
