### ISSUE TITLE
Id collision when adding new task

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#412]
Steps to reproduce on advanced gantt demo:

0. SchedulingEngine/lib/Engine/data/model/ProjectMixin.ts
remove all entities of `idField     : 'id',` and rebuild SchedulingEngine (confirmed by @bmblb and @SamuraiJack )
1. map id field in Gantt/examples/advanced/lib/Task.js
```
{ name : 'id', dataSource : 'Id' }
```
2. Change `install apache` task id in launch-saas:
```
"Id": 11
```
3. Open demo, add task below `install apache` using context menu. See exception in console
```
Store.js:1349 Uncaught (in promise) Error: Id collision on 11
    at TaskStore.register (Store.js:1349)
    at TaskEx.joinStore (Model.js:1566)
    at TaskEx.joinStore (PartOfProjectMixin.js:14)
    at TreeNode.js:743
    at Array.forEach (<anonymous>)
    at TreeNode.js:741
    at Array.forEach (<anonymous>)
    at TaskEx.internalAppendInsert (TreeNode.js:738)
    at TaskEx.insertChild (TreeNode.js:596)
    at Gantt.addTask (GanttBase.js:597)
```

**Comment by pmiklashevich** [comment]
Adding `Task.idField = 'Id';` to the bottom of Gantt/examples/advanced/lib/Task.js fixes the issue. And it's a valid approach to implement id field mapping.

**Comment by bmblb** [comment]
`high-priority` label removed because using `idField` works. although it would be good to apply same mapping rules for all fields, not just `id`. bunch of places in the code is fixed already, only few are missing, like context menu

**Comment by isglass** [comment]
We have basic tests covering that you can remap id field this way. It should be made to work
Other ways of changing id field should be deprecated
