### ISSUE TITLE
Milestone element disappears

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#4139]
Steps:
Note: it probably depends on the browser window size since requires scrolling. I have it about 1600 x 900.

0. open `criticalpaths` demo
1. convert `UI unit tests / individual screens` task to milestone w/ context menu
2. scroll vertically to the bottom
3. scroll horizontally to the right
4. scroll vertically to the top
5. scroll horizontally to the left

Result: `UI unit tests / individual screens` task element is gone

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/f0b9fec5-9465-490f-b05c-85bf0a248787
