### ISSUE TITLE
Improve docs on formatting currency values on `NumberField`

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#415]
Requested here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=13549

Need to be able to show numbers in a currency format (configurable), for example: "€ 2,222,222.00"
But when you enter to editing mode it should show only value, similar to what we do in cell editor.

**Comment by pmiklashevich** [comment]
@dongryphon has thoughts about it.

> a lot of the underpinnings are there in NumberFormat and NumberField on master ... just need to deal w/currency symbol ... I was thinking to hoist it out as a trigger. It could be visual only based on current locale, or clickable to pick the currency but that's a lot more interesting
