### ISSUE TITLE
Daily recurrence stop condition issue

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#4152]
Steps to reproduce:

1. open `basic` demo
2. create a new event recurring `Daily` and stopping `After` 2 times
3. save changes
4. re-open the event in the editor again
5. change recurrence `End repeat` to `Never`
6. save changes

Result: the event is still introduced twice.

The issue is probably not something Calendar specific and could be seen in Scheduler too but that needs to be checked.

**Comment by matsbryntse** [comment]
No repro
