### ISSUE TITLE
Left arrow key does not navigate from selected task

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#4162]
Reproducible on basic gantt demo:
1. select cell in the name column
2. press right arrow key twice. see selection go to the task bar and then to the name cell in the next row
3. press left arrow key twice. see selection go to the task bar on the previous row and remain there

looks related to the accessibility task by @ExtAnimal

**Comment by ExtAnimal** [comment]
Just a typo:

![Screenshot 2022-02-22 at 17 20 55](https://user-images.githubusercontent.com/200516/155174148-2cbc6e5e-3d54-4a6c-997c-64d2765cd300.png)
