### ISSUE TITLE
Copy paste task from external source

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4169]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=20239&p=100429#p100429)

Hi,

Does the gantt support copy a data (task/s) from external source, like excel?
I wish to be able to select multiple tasks from any source ctrl+c to copy to clipboard and then paste to the gantt.

I tried the built-in feature and it looks I can only copy from gantt to gantt.

Also is there a way to copy the data from the gantt to clipboard to export it somewhere else?

Thank you in advance.

**Comment by matsbryntse** [comment]
Initial progress in https://github.com/bryntum/bryntum-suite/pull/4872

**Comment by marciogurka** [comment]
[+1](https://www.bryntum.com/forum/viewtopic.php?p=112377#p112377) user asked for this feature
