### ISSUE TITLE
ResourceView that groups resources by date

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4174]
![image001 copy](https://user-images.githubusercontent.com/218570/153368420-6732cb33-61c1-44d5-b77a-9616674d09a0.jpg)

**Comment by ExtAnimal** [comment]
This will probably be a new Calendar widget subclass.

I suggest that DayView be broken up in to an abstract base class which manages multiple child columns with no opinions about dates contained.

Then DayView will extend that and own a date range.

And this new view will also extend it, but in a different way. It will gather its `cellMap` in a different way. 

Also `CalendarRow` which provides the all ay events at the top will have to be refactored long the same lines. It has a lot of capabilities that are needed. The height calculation, and expand/collapse capability. So some form of it will be needed by this new view.

**Comment by ExtAnimal** [comment]
Related to https://github.com/bryntum/support/issues/4641

That will be possible using the new base class.
