### ISSUE TITLE
Events not re-scheduled from non working time when dag-n-drop multiple events

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4194]
https://bryntum.com/examples/scheduler-pro/non-working-time/

enable `multiEventSelect`. Try to select 2 events and drop as on the picture below. startDate for second event stays on non working time period.

<img width="1188" alt="Screenshot 2022-02-11 at 17 53 55" src="https://user-images.githubusercontent.com/7203098/153570921-5f9085d7-c223-49cd-9716-38119e1f9062.png">

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20272&p=100620#p100620)

I have set 'multiEventSelect' in scheduler config.As shown in the image, I selected two events, last event start time is '08',  when i drag first event, 'timerange' config doesn't work in last event， it start time is '06', but '06' is not working time.

**Comment by matsbryntse** [comment]
Works fine in 5.0
