### ISSUE TITLE
[REACT] Reorder Rows tree grid: Insert child Row in an empty Parent row

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#4198]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=20281)

This is an issue I have highlighted several times. What does "drop below" mean? As a sibling or as a child?

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/227

**Comment by web-developer2020** [comment]
https://prnt.sc/p6wG_IF4e-B-
I want to insert a new child row to this part.
using this code
source.store.insert(childPath, { costType: "child 1", align: 'right' });
But this code work only for the parent row
Do u have any ideas?
