### ISSUE TITLE
Collapsed column header shrinks when all columns are collapsed

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4202]
Compare
<img width="951" alt="Screenshot 2022-02-13 at 10 37 39" src="https://user-images.githubusercontent.com/218570/153747336-49567551-0ed7-48c5-8eaf-57bda4cd18e7.png">

<img width="899" alt="Screenshot 2022-02-13 at 10 37 36" src="https://user-images.githubusercontent.com/218570/153747340-8ad46e6b-ffc2-4dc1-a6ba-2b4c03d9ec22.png">

**Comment by isglass** [comment]
Fixed along the way
