### ISSUE TITLE
Error when undoing delete action on filtered store

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4205]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20289&p=100720#p100720)

If tasks are filtered, undo deleted tasks doesn't work.
It can be reproduced at https://bryntum.com/examples/gantt/advanced/.

		
		
		

https://user-images.githubusercontent.com/7203098/153812700-cbdfcdcd-00ac-4464-bb71-64d03bc0c98e.mp4

**Comment by canonic-epicure** [comment]
The exception after undo does not appear in the latest code anymore, however the restored state after seems to be still filtered and rendering seems to be broken.
