### ISSUE TITLE
Incorrect event position/dates when create an event on daylight saving time day

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4220]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20331&p=100915#p100915)

For scheduler here https://www.bryntum.com/forum/viewtopic.php?f=51&t=20335&p=100929#p100929
 Change timezone to Munich local time (in your OS settings)

```
new Date()
Thu Feb 17 2022 09:35:09 GMT+0100 (Central European Standard Time)
```

Open https://bryntum.com/examples/calendar/basic/ on Week view.

Goto March 27 2022, try to create an event using dragCreate. See that event is moved 1 hour down while dragging and moved up after, but has wrong date (1 hour difference)

https://user-images.githubusercontent.com/7203098/154437766-89d40d84-0a5d-4fd7-afa9-776aa759586c.mov

**Comment by taauntik** [comment]
user asked for the fix [here](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20331&p=108385#p108385)

**Comment by mikekorth** [comment]
bumping this again as it doesn't appear to be part of the most recent release
