### ISSUE TITLE
Wrong `endDate` when dragging events over days at which DST/STD change

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4225]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20335&p=100929#p100929)

Use Berlin timezone to reproduce. Basic example, 27.03.2022
See that tooltip info before drop and after drop are not equal.

https://user-images.githubusercontent.com/7203098/154631491-00dc6724-d162-45ba-9bc3-750e9bccf6db.mov

**Comment by chuckn0rris** [comment]
Still reproducible here https://bryntum.com/examples/scheduler/basic/

**Comment by marciogurka** [comment]
Client asked for this [here](https://www.bryntum.com/forum/viewtopic.php?p=107911#p107911)

**Comment by marciogurka** [comment]
User shared another example with Vue 2.

[TestCase.vue.zip](https://github.com/bryntum/support/files/9284990/TestCase.vue.zip)

https://user-images.githubusercontent.com/16693227/183512440-a174995d-185e-48d9-b40a-24cf78c3ac80.mp4
