### ISSUE TITLE
Validation demo - incorrect validation on muti dragging 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4290]
See video for steps to reproduce.
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20445&p=101440#p101440)

https://user-images.githubusercontent.com/7203098/156145332-e1821f07-aaf2-4063-b55f-65536c47c75c.mov

https://user-images.githubusercontent.com/7203098/156152119-9e61f8c4-b245-4f9a-8f23-71a98f89d464.mov

**Comment by matsbryntse** [comment]
Should be fixed in v6+, please reopen if still reproducible
