### ISSUE TITLE
When using mergecells feature, schedulerpro won't scroll

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4292]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20448&p=101450#p101450)

https://bryntum.com/examples/examples-scheduler/merge-cells/

Steps to reproduce:
Change date range to see scroll after load, try to scroll

**Comment by ExtAnimal** [comment]
Recheck this after https://github.com/bryntum/bryntum-suite/pull/4912 merges.


MergeCells had a method call order error which left the grid in an erroneous state.

**Comment by isglass** [comment]
It scrolls both locally and online for me, must have been fixed by other changes. Closing as not reproducible
