### ISSUE TITLE
Not possible to unschedule the task

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4318]
https://bryntum.com/examples/gantt/advanced/
Try to remove this data from any task in the cells or task editor

**Comment by canonic-epicure** [comment]
Should be possible to unschedule the task by clearing some of its `start/end/duration` fields. 

The easiest way to do it right now would be to set the cleared field to `null` (and let the engine to propagate the change setting to `null` dependent fields). More complex would be to detect this situation and not trigger the propagation, to preserve the user input, however, that would require a flag? (if a unscheduled task has incoming dependency it ignores the user input).

Perhaps we need a flag - "unscheduled" similar to "inactive", which will prevent normal scheduling.
