### ISSUE TITLE
Widget column with button doesn't pass text into child widget

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4324]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20528&p=101830#p101830)

Hi,

I did Bryntum Grid upgrade from 4.3.5 to 5.0 on my project.

I noticed my Grid widget-type column doesn't render texts inside the buttons anymore as they used to. I am using the column object's field-property to get the button values depending on the data-object property value. So the button widget doesn't have text-property defined at all. It used to work like this in version 4.3.5. Couldn't find breaking changes on this matter from change log. Has something changed perhaps?

Steps to reproduce:
Go to column types demo https://www.bryntum.com/examples/grid/columntypes/

Find widget-type column from the code that has button-type widget:
 
```
{
    text    : 'Widget',
    width   : 150,
    type    : 'widget',
    cellCls : 'age',
    widgets : [{
        type     : 'button',
        text     : 'Add age',
        flex     : 1,
        icon     : 'b-fa b-fa-plus',
        cls      : 'b-blue b-raised',
        onAction : ({ source: btn }) => {
            btn.cellInfo.record.age++;
        }
    }]
},
```

Remove "text: 'Add age'" property from the widget definitions, as we want the text from the data object (column field-property).
Add "field: 'age'" to the column properties. This field is also used in column next to it, but we are using it just for demonstrating some value in buttons.

So the code should look like this:

```
{
    text    : 'Widget',
    width   : 150,
    type    : 'widget',
    cellCls : 'age',
    field : 'age',
    widgets : [{
        type     : 'button',
        flex     : 1,
        icon     : 'b-fa b-fa-plus',
        cls      : 'b-blue b-raised',
        onAction : ({ source: btn }) => {
            btn.cellInfo.record.age++;
        }
    }]
},
```

**Comment by matsbryntse** [comment]
Should set `defaultBindProperty` to "text". Needs to be added to 5.0 docs upgrade guide

**Comment by isglass** [comment]
Updated docs + upgrade guide
