### ISSUE TITLE
Failed to render cell element correctly after search on column

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4325]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=20524&p=101827#p101827)

After using a custom renderer, when I search for events if it doesn't match with the text of the column it shows the full HTML which was returned from the renderer function.

![Capture](https://user-images.githubusercontent.com/75997756/157192674-31e334ce-152a-4cf4-80d8-279df857ed52.PNG)

To reproduce the bug [click here](https://codepen.io/dv-auntik/pen/LYOoEXE?editors=0010) inside of the code pen output search for a string that doesn't match any record.

**Comment by matsbryntse** [comment]
Column should be using https://bryntum.com/docs/scheduler/api/Grid/column/Column#config-htmlEncode set to `false`
