### ISSUE TITLE
Dragging column header to edge should trigger scroll

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4366]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20614&p=102213#p102213)

Hi Team,

I'd like to modify the column header drag behavior, to scroll the column grid as you drag the header:

![Screen Shot 2022-03-14 at 4.32.34 PM.png](https://www.bryntum.com/forum/download/file.php?id=16777)

			
		
		
				
			 Screen Recording 2022-03-14 at 4.27.25 PM.mov
						(256.28 KiB) Not downloaded yet
		
		
			

Right now the behavior is that the header is fixed within whatever range you have scrolled into.

Where would be a good place to start with this feature? Is there existing behavior I can tap into inside Bryntum?

Thank You!
![Screen Shot 2022-03-14 at 4.32.34 PM.png](https://www.bryntum.com/forum/download/file.php?id=16777)

**Comment by BrandonDH** [comment]
Hi All, Has this been added to a new release? Thanks
