### ISSUE TITLE
Assigning tasks to project when `syncDataOnLoad:true` results in empty Gantt

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#4370]
This creates problem especially for framework users as we set syncDataOnLoad to true in the wrappers.

To reproduce append the following lines to `bryntum-suite/Gantt/examples/basic/app.js`:
```
setTimeout(() => {
    gantt.project.taskStore.syncDataOnLoad = true;
    gantt.project.tasks = [{id:1, name:'Task 1'}];
}, 2000)
```
The expected result is that `Task 1` would be visible after 2 seconds.

See the screencast:

![sync-data-on-load-bug](https://user-images.githubusercontent.com/204844/158358099-787a57a3-2208-409e-95a8-f3add67b7a65.gif)

Related issues:

* https://github.com/bryntum/support/issues/4238
* https://github.com/bryntum/support/issues/4337

**Comment by matsbryntse** [comment]
When fixed, please verify if it also fixes https://github.com/bryntum/support/issues/4337

**Comment by jsakalos** [comment]
Unfortunately, it’s not fixed. Better to say, we now have another issue. To reproduce (in the `inline-data folder`):
```
grunt npm:build
grunt fw:local:switch:offline
npm i && npm start
```
Now click “Change Data” button (works). Click “Change Data” button again and it crashes with:
```
gantt.module.js:48231 Uncaught Error: Parent node with id 1 not found, cannot add children.
    at gantt.module.js:48231:1
    at Map.forEach (<anonymous>)
    at Object.add (gantt.module.js:48227:1)
    at Object.add (gantt.module.js:53319:1)
    at Object.syncDataset (gantt.module.js:52995:1)
    at Object.setStoreData (gantt.module.js:54861:1)
    at Object.setStoreData (gantt.module.js:128347:1)
    at Object.setStoreData (gantt.module.js:193851:1)
    at Object.set data (gantt.module.js:54795:1)
    at Object.set data (gantt.module.js:195577:1)
```
I’ve never seen this error message before so I suspect it was introduced by the fix.
