### ISSUE TITLE
newTaskDefaults not applied when pressing Enter on last row

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4376]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=20635&p=102317#p102317)

Add to basic Gantt demo
Press Enter on last row while editing, name not applied

```
newTaskDefaults   : {
        name : 'foo'
    },

```

When adding a new task you are using newTaskDefaults to determine what data to set. However that does not appear to be working when you press enter on the last task and it adds a new task at the end. Is there a way I can fix for now?

I also used to override that method in the taskkeydown and reading enter key but that no longer works in 5x as it never calls that function when editing a task. If you are not editing a task and hit enter it does work.

**Comment by ExtAnimal** [comment]
This ticket is related to https://github.com/bryntum/support/issues/4399

There should only be one config for the Scheduler family (Scheduler and Gantt) for automatically created events (from dblClick or the schedule context menu)

And that one config should contain all the possible defaults that could be needed.

Take a look at how https://www.bryntum.com/docs/calendar/api/Calendar/widget/mixin/CalendarMixin#config-autoCreate works.

I suggest what would be a breaking change, but unifying all these in a new `autoCreate` config to unify with Calendar.
