### ISSUE TITLE
Event jumps back to previous invalid position after deleting dependency

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4380]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=51&t=20670&p=102482#p102482)

Hi team,

I found a case regarding dependencies, which is not clear to me whether it is expected behavior or a bug. You can test it here in your examples: https://bryntum.com/examples/scheduler-pro/dependencies/.

Reproduction:

1. Create event a
2. Create another event b
3. Create dependency between them (end of a to start of b)
4. Drag b to start earlier than a -> b will jump back as expected because of the dependency 
5. Delete dependency 
6. See that b jumps automatically to the position where it was dragged in step 4.

I would have expected b would not jump to this position. But is it though? Thanks for you help.

**Comment by arcady-zherdev** [comment]
The reason is the event after dragging step the event got `Start No Earlier Than` constraint set implicitly. The Engine in Scheduler Pro normally schedules ASAP events having incoming dependencies, but apparently it also does that for ones having a constraint.

**Comment by canonic-epicure** [comment]
The desired behavior can be achieved with the addConstraintOnDateSet option: [SchedulerPro.model.ProjectModel#field-addConstraintOnDateSet](https://bryntum.com/products/schedulerpro/docs/api/SchedulerPro/model/ProjectModel#field-addConstraintOnDateSet) (will need to set it to false)
