### ISSUE TITLE
`DragCreate` fails when event store is reloaded while dragging

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4411]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20781&p=103017#p103017)

Hi,

I have infinite scroll enabled and when I'm drag creating, resizing, or moving an event to the end of the time axis, which loads a new dataset via crud manager, the event I was dragging disappears or is not dropped where it should be.

Reproducable using https://www.bryntum.com/examples/scheduler/crudmanager/ and adding these options:

```
    infiniteScroll: true,
    bufferCoef: 1,
    listeners: {
        timeAxisChange: ({config}) => {
            // normally config.startDate + endDate are passed as parameters
            window.scheduler.crudManager.load({}); 
        }
    },

```

**Comment by JeffDerk** [comment]
Hi, any updates on this?

**Comment by chuckn0rris** [comment]
@JeffDerk not yet. It's planned to be fix in one of closest releases.
