### ISSUE TITLE
Typing into Gantt `DateField` freezes browser

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4417]
- [x] min / max for startDate/endDate/constraintDAte columns to be set + synced with Project start / end date
- [x] Tests

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=20776&p=103004#p103004)
[Forum post 2](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20922&p=103634#p103634)
[Forum post 3](https://bryntum.com/forum/viewtopic.php?f=51&t=21984&p=108695#p108695)

Reproducible in Gantt advanced demo when using attached data set. [launch-saas.json.zip](https://github.com/bryntum/support/files/8372482/launch-saas.json.zip)

If you have a calendar with some intervals repeating like weekends. And you try to type into a date field like so (3/3/200) it locks up the browser. In debugging it appears to be taking the date 0020 instead of 2020 but it also appears to be doing calcs before I am done typing so I cant ever get to 2022 before locking up. I even turned instantUpdate to false and it still seems to be doing calcs when you type. This was previously working in 4x.

you can view it here. Just clear out a date and enter something by typing 3/3/20.
https://templates.oneplan.ai/gantt/examples/advanced

**Comment by taauntik** [comment]
Another case from [this forum post](https://bryntum.com/forum/viewtopic.php?f=52&t=22675&p=112101#p112101)

You can reproduce this here https://bryntum.com/examples/gantt/advanced/

The use case is:

- On the Gantt, edit any Startdate value from the grid, by double click then go with the key arrow to the right and try just to remove the last number, then it crash and the browser window freezes.

I sent attached a screenshot from the Examples Bryntum Page, where I've been able to reproduce exactly the same issue as in Our Project. 
![Captura de pantalla 2022-10-19 124016](https://user-images.githubusercontent.com/75997756/196676030-b5342c97-1843-40fe-bcd8-dfdd533a2b7e.png)

**Comment by marciogurka** [comment]
[Another post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22743&p=112438#p112438) regarding this one
