### ISSUE TITLE
Not possible to change month/year using arrows in endDate field

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4420]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=20792&p=103083#p103083)

https://bryntum.com/examples/gantt/advanced/
Add endDate field into grid using "Add Column" column. DblClick to edit endDate using cellEditor for any task, try to change month using arrows left/right, or year. Nothing happens. Try to use keyboard "down" button to navigate to next month - it's possible to do.

**Comment by matsbryntse** [comment]
Dupe of https://github.com/bryntum/support/issues/4333
