### ISSUE TITLE
pdf export feature should be capable of grabbing events html without scrolling the view

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#4449]
Timeline header and event renderer only render content to the visible part of the view. Export server is generally unaware of that so it has to scroll left and right to make scheduler render events and then collect HTML.
Ideally, export feature would just call an API method that would return HTML of the event or disable optimization to render complete set of events.

Reported here: https://www.bryntum.com/forum/viewtopic.php?f=52&t=20859&p=103360#p103360

**Comment by Aarbel** [comment]
@bmblb 

We had white space problems (due to chromium scrolling limits) using pdf export on older version of bryntum.

Do you think it could be solved with this ?

If i understand well, right now the html is rendered server side right ? Or you still take frontend screenshots sent to the export server ?

**Comment by bmblb** [comment]
@Aarbel we never sent screenshots to the server. Export server always worked like this:
1. grab HTML and send to server
2. render HTML to a webpage, create PDF/PNG and send to client

> We had white space problems (due to chromium scrolling limits) using pdf export on older version of bryntum.
>Do you think it could be solved with this ?

Since version 5.2.0 we no longer scroll the view, instead we directly render what we need to render to an invisible element. Export became faster, but general idea is intact - grab HTML, send to server, receive PDF

**Comment by Aarbel** [comment]
> @Aarbel we never sent screenshots to the server. Export server always worked like this:
> 
> 1. grab HTML and send to server
> 2. render HTML to a webpage, create PDF/PNG and send to client
> 
> > We had white space problems (due to chromium scrolling limits) using pdf export on older version of bryntum.
> > Do you think it could be solved with this ?
> 
> Since version 5.2.0 we no longer scroll the view, instead we directly render what we need to render to an invisible element. Export became faster, but general idea is intact - grab HTML, send to server, receive PDF

Ok thanks, i'm trying it, but yes server side chromium rendering may have glitches with long lists.

Moreover how is that possible to optimise the html sent ? (header, etc..)

**Comment by Aarbel** [comment]
@bmblb where can i find the full code of this example: https://www.bryntum.com/products/gantt/examples/export/ ?

So i can directly show you an example with big dataset

**Comment by bmblb** [comment]
You can find in your Gantt distributable which you can download from customer zone. Or you can download trial and take example from there.

**Comment by Aarbel** [comment]
@bmblb i don't have access to the full code here ( and yes i have a licence): 
<img width="871" alt="image" src="https://user-images.githubusercontent.com/25119847/233588736-923003d2-1b6e-4135-891f-d16707ad5d53.png">

**Comment by bmblb** [comment]
@Aarbel log in to customer zone, download latest gantt release, extract it, navigate to `examples/export` folder. You will find full code there

**Comment by SergeyMaltsev** [comment]
@Aarbel this is guide to get distribution
https://bryntum.com/products/gantt/docs/guide/Gantt/download

**Comment by Aarbel** [comment]
@bmblb @SergeyMaltsev 

Just to be sure which changes were operated with this update:
- did it updated the export-server ? If so, looks like export-server didn't had any uopdates since 9 months
- if not, which code / library was updated ? 

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/25119847/233857951-832da08f-9b45-4904-aa4d-22b30a99a74a.png">

**Comment by Aarbel** [comment]
> @Aarbel this is guide to get distribution https://bryntum.com/products/gantt/docs/guide/Gantt/download

@SergeyMaltsev i spent all my sunday to try to make your example work: https://www.bryntum.com/products/gantt/examples/export/

I think i just need a little bit more documentation to achieve my goal, check my questions bellow:

---

# How to fully setup the "client" side

The client side is inside ./examples/export/ when downloading the distribution zip of bryntum gantt
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/25119847/233859633-59fce8c3-0f72-4130-b62e-4a5b52d40286.png">

How can i run it ?

When i open the `./examples/export/index.html` it tells me that this file should be run from a Webserver. Which Webserver are you talking about here and where is the code for it ? Moreover where should i put this index.html file which also needs app.js etc... 

<img width="825" alt="image" src="https://user-images.githubusercontent.com/25119847/233859745-c0a2e330-3f39-4f43-af6f-8a63c1de1a72.png">

---

# How to fully setup the "server" side ? 

I run the docker image of the repo https://github.com/bryntum/pdf-export-server, everything runs well on ports 8080

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/25119847/233860304-4255cf33-3967-48e6-918b-0fce664395f9.png">


Also i understood that i had to copy `./examples/export/resources` to the Export Web Server (the one that runs in docker) and mention the "destination" of these ressources inside the webserver (i chose `pdf-export-server/src/web/application/styles`) and added the `-r src/web/application/styles` in the Dockerfile of pdf-export-server.

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/25119847/233860242-5d38b34b-e8bf-48ca-8e17-627a3ae33032.png">

What i understand is that the Export Webserver needs the same css styles as the frontend to render the html given by the frontend when the frontend request for an export right ?

Am i globally doing it right on the server side ?

**Comment by Aarbel** [comment]
@SergeyMaltsev  @bmblb sorry to ping you back, i just need your last help to fully test the "dev" example of bryntum gantt export 🤞

**Comment by bmblb** [comment]
> I tried to run it simply with http-server but sub paths like ../_shared/browser/helper.js are not well served.
> What methodology do you use to serve this client index.html file ?
Apparently, you should serve directory which is reachable by all resources used by the web app. Root folder in distributable, for example.

> Also i understood that i had to copy ./examples/export/resources to the Export Web Server
This is not necessary and completely depends on your environment settings. Please carefully read this guide: https://github.com/bryntum/pdf-export-server/blob/main/docs/architecture.md It should point out possible configurations.
For instance, if your export server can reach application page, you don't need to load anything into export server image.

To run our export demo, you need to:
1. serve distributable root
2. start pdf export server container
3. point export demo app to `localhost:8080`

**Comment by Aarbel** [comment]
Thanks @bmblb 

Can you be really precise about the commands to run ?

1- serve distributable root
Do you mean running `http-server` inside gantt folder ?

I've got this but nothing loads:
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/25119847/234567285-ce719d0c-44c1-4b27-ab19-be3d9af58288.png">


2- start pdf export server container
OK, works

3- point export demo app to localhost:8080
OK, i see clearly what to change in the code.

**Comment by bmblb** [comment]
> I've got this but nothing loads in Chrome:

You need to serve entire directory, not a single html file. Make entire distribution available via web server.

**Comment by Aarbel** [comment]
> > I've got this but nothing loads in Chrome:
> 
> You need to serve entire directory, not a single html file. Make entire distribution available via web server.

@bmblb can you give a simple example ? (a zip works)

**Comment by bmblb** [comment]
You already have an export example in your distribution. Alternatively you can go to online export demo and download it directly from there.

**Comment by Aarbel** [comment]
Yes i know, but please can you tell what `command` i should run when i am at the root of this repo =>

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/25119847/234894810-50f24294-3755-41f7-bf06-c996ec47529a.png">

Nothing works at all.

**Comment by bmblb** [comment]
Let me emphasize: you need to serve this folder using webserver. And there are plenty of options, e.g. this is the first article from google showing how to serve the folder: https://codingshower.com/quick-local-web-server/

This discussion is no longer in scope of this ticket. If you do not succeed and have further questions, please post on http://forum.bryntum.com

**Comment by Aarbel** [comment]
Ok the answers are just:

- Run `http-server` at the root of the folder "gantt-5.3.3" => it runs the client fo all the possible demos of gantt. Please @bmblb add it inside your Readme
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/25119847/234900952-823cb6dd-cd28-4eab-8273-2b64c416376b.png">

- It's not possible to run specific examples (like the `export` one) with `http-server` independently, as app.js refer to files in parent directories.
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/25119847/234901294-e0c97ae8-0520-4602-bcc0-6a4cdd4f8e4d.png">
