### ISSUE TITLE
Copy-paste event to collapsed group should be a no-op

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4455]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20868&p=103430#p103430)

https://bryntum.com/examples/scheduler/grouping/

1. Select first event, press Cmd+C
2. Collapse the group with copied event, press Cmd+V
3. Expand the group

See that event is copied, but resource is also copied

**Comment by isglass** [comment]
Sounds like it should be a no-op

**Comment by matsbryntse** [comment]
Cannot repro
