### ISSUE TITLE
[Typescript] Add typings for Events

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#4456]
All firing events should have typings.

And all "onClick", "onFoo" methods too

**Comment by jehret** [comment]
This also causes an issue in the documentation in the Angular integration guide here
https://www.bryntum.com/docs/grid/guide/Grid/integration/angular/guide#using-datachange-event-to-synchronize-data
where the syncdata function is expecting this
```syncData({ store, action, records } : { store : Store; action : String; records : Model[]}) : void {
        console.log(`${store.id} changed. The action was: ${action}. Changed records: `, records);
        // Your sync data logic comes here
    }```
