### ISSUE TITLE
Dropping event outside window causes drag operation to get "stuck"

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4462]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=44&t=20884&p=103485#p103485)

Dropping an event outside the browser window causes the drag operation to get "stuck".
After this I cannot do any other event drag operations.
It only happens if you drop it outside the window and the scheduler is scrolling.

I can confirm the drag is stuck by checking

```
window.scheduler.features.eventDrag.isDragging
```

To reproduce:

1. Open https://www.bryntum.com/examples/scheduler/configuration/

2. Make browser not full screen and make the window width small enough so the scheduler has a horizontal scrollbar.
    Also make sure you have some screen space on the right side of the window where we will drop the event.
 
3. Pick up an event on the scheduler, drag it all the way to the right, outside the browser window.
    At this point the event should be completely outside the window and the scheduler should start scrolling to the right.
    Now drop/release the event.
4. Notice the event is moved back to where it was
5. Now try dragging any event and notice it won't pickup the event since the scheduler thinks we're still dragging.

**Comment by matsbryntse** [comment]
Cannot reproduce in latest release
