### ISSUE TITLE
Event drag create on big dataset generates error

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4463]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=44&t=20881&p=103480#p103480)

Hi

I ran into an issue that was reproduceable on the big data set demo:
https://bryntum.com/examples/scheduler/bigdataset/

Reproduction steps:
Put a lot of overlapping stacked events on the same resource within the same timespan. 20+
Then drag to create a new event between one of the events on top of the page.
Make sure that the visualization of the new event that's being dragged is out of the viewport.

Result:
No new event created.
An error is visible in console:
![dragToCreateOnBigDataSetError.PNG](https://bryntum.com/forum/download/file.php?id=17059)

How can this be resolved?

Kind regards
jmeire

**Comment by matsbryntse** [comment]
- [ ] lockLayout should be set to `true` by default on EventDragCreate
- [ ] Pick correct "lane" based on mouse down event (event will move upon mouse up which is ok)

**Comment by taauntik** [comment]
The user is asking for the fix [here](https://forum.bryntum.com/viewtopic.php?p=113872#p113872)
