### ISSUE TITLE
Find best practices to create custom bundles with our components

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4466]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20883&p=103505#p103505)

Hello, thank you for your amazing product!

We use the Scheduler in our Angular app, and the scheduler bundle size is quite large. Is it possible to use the technique described in 'Custom build using WebPack' example to decrease the bundle size by not including features we don't need?

But I can see that 'scheduler-angular' wrapper imports everything from the lite bundle @bryntum/scheduler/scheduler.lite.umd.js, so probably we can't, right? Should we write our own angular wrapper, maybe?..

What do you think?

**Comment by SergeyMaltsev** [comment]
Resolved with this update
https://github.com/bryntum/support/issues/4670
