### ISSUE TITLE
zoomToFit does not work correctly when infiniteScroll is enabled

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4484]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20950&p=103740#p103740)

https://www.bryntum.com/forum/viewtopic.php?f=51&t=21069&p=104268#p104268

Hello,

When infiniteScrool feature is enabled the zoomToFit() function does not fit to the events of the eventStore so that the all the events are visible. 
An example can be found in the attached file. The issue can be reproduced by using the provided example in the code editor of https://bryntum.com/examples/scheduler.
In case the infiniteScrool feature is disabled, zoomToFit will have the expected behavior.
I am currently using Bryntum Scheduler 5.0.0.

Thank you,
Alex

**Comment by BrandonDH** [comment]
Hi team, was this fix added to a release? - thanks

**Comment by SergeyMaltsev** [comment]
Yes. It is in `5.0.3` released version.
