### ISSUE TITLE
Cut and paste between resources will assigned to both

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4495]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=44&t=20987&p=103925#p103925)

If I cut and paste the event between resources, it will be assigned to both. You can see it here:
https://bryntum.com/examples/scheduler-pro/highlight-time-spans/

Steps to reproduce:
1. Cut an event from a resource.
2. Paste it into another resource.
The event will assign to both.

It looks like a bug, it should behave the same as dragging events around...

**Comment by matsbryntse** [comment]
Cut should move event + update assignment resource
