### ISSUE TITLE
Resource avatars demo not showing any event bars

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4499]
full screen on a laptop you only see the +1
https://bryntum.com/examples/calendar/resource-avatars/

Needs to show content looking like the screenshot
<img width="1440" alt="Screenshot 2022-04-14 at 18 01 21" src="https://user-images.githubusercontent.com/218570/163428694-1928d805-20ce-45e5-b976-abd24ebc0903.png">

Expected:
![image](https://user-images.githubusercontent.com/218570/163428798-0202c6b3-7afe-4caa-9fe9-151e15bc5572.png)

**Comment by isglass** [comment]
Requested more info, looks good down to 737px vertically here
