### ISSUE TITLE
Calendar doesn't accept `project` instance

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#4516]
It is not possible to assign project to Calendar instance.

Muted test exists in `release` `Calendar/tests/view/CalendarProject.t.js`

This code doesn't show events
```
const project = new ProjectModel({
    resources,
    events
});

const calendar = new Calendar({
    // Start life looking at this date
    date : new Date(2020, 9, 12),

    appendTo : 'container'

});
calendar.project = project;
```

This works fine
```
const project = new ProjectModel({
    resources,
    events
});

const calendar = new Calendar({
    // Start life looking at this date
    date : new Date(2020, 9, 12),

    appendTo : 'container',

    project
})
```

- [x] Unmute and update test `Calendar/tests/view/CalendarProject.t.js`
- [ ] #6619

**Comment by ExtAnimal** [comment]
Doesn't work setting the `project` after instantiation in Scheduler either. This is a Scheduler thing.
