### ISSUE TITLE
Fix icons for frameworks guides on /guides page

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4518]
Open https://bryntum.com/docs/gantt/api/guides
Scroll to integration section. See that integration section showed in one level and Angualr, React, Vue guides shown just as Guide, Guide, Guide, with the same icons, same for Data binding. 

<img width="1674" alt="Screenshot 2022-04-21 at 12 29 22" src="https://user-images.githubusercontent.com/7203098/164375698-ca1c0ba9-b71f-4458-b7b2-d23eea40533e.png">

**Comment by SergeyMaltsev** [comment]
Resolved in `5.0.4`
