### ISSUE TITLE
[REACT] values for useState variable not updated in event listeners

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4522]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21022&p=104175#p104175)

To reproduce add some useState variable and listener. As example, most close to user's case, update resource-histogram demo with the next code
```
const [selectedTasks, setSelectedTasks] = useState([]);

    useEffect(() => {
        schedulerRef.current.instance.on('beforeDragCreate', () => {
            console.log('selectedTasks',selectedTasks);
            if (selectedTasks.length === 0) {
                return false;
            }
    });
    }, []);


   // Zoom In/Out handler
    const onZoom = ({ source }) => {
        // update on zoom
        setSelectedTasks([1,2,3]);

        const {
            dataset: { action }
        } = source;
        schedulerRef.current.instance[action]();
    };

```

Update variable in some other method. See that value for `selectedTasks` on event trigger is always `[]`.

**Comment by jsakalos** [comment]
This is the solution:
```
    useEffect(() => {
        schedulerRef.current.instance.onBeforeDragCreate = () => {
            console.log('beforeDragCreate', selectedTasks);
        };
    }, [selectedTasks])

    const onZoom = ({ source }) => {
        setSelectedTasks([1,2,3]);
    }
```

It is how React functional components work, it. has nothing to do with our code.

Here `useEffect` runs when `selectedTasks` change. (Beware that the whole array must change, not only one element of the array.) That creates new `on` function all with it's closure so the state is reflected correctly.

**Comment by jsakalos** [comment]
The ticket can be closed, there's no action required by us.
