### ISSUE TITLE
Error on row reordering on tree grid

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4525]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=21028&p=104216#p104216)

Use test case attached.
Drop record as shown on the video. It's important to see the line when dropping and see that record itself is not highlighted.
You can see that on the video.

https://user-images.githubusercontent.com/7203098/164644043-090fefc7-da14-4011-9319-f4e35bc8799b.mov

[Archive.zip](https://github.com/bryntum/support/files/8538362/Archive.zip)

**Comment by chuckn0rris** [comment]
Not reproducible in current codebase.

**Comment by sipi41** [comment]
Don't understand why it says "not reproducible" when I even sent a sample and they told me there was in fact a bug... what's your suggestion ? or how can we overcome this problem?
