### ISSUE TITLE
`loadOnDemand` with sidebar date picker using `showEvents : true` causes an infinite loop

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4530]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=18907&p=104234#p104234)

Also [Forum post](https://forum.bryntum.com/viewtopic.php?t=23160)

[examples/calendar/basic/](https://bryntum.com/examples/calendar/basic/)

Steps to reproduce:

1. Go to the URL above.
2. add these pieces of code
```
datePicker : {
    showEvents : true
}
```
Inside of the features object :
```
loadOnDemand : true
```

**Comment by ExtAnimal** [comment]
CrudManager does not tolerate two active load requests. I don't know t he reason behind that, but that is the cause of this issue.

The view sends off for its events. And the date picker sends off for its events and CrudManager panics at two requests for data being made.

@arcady-zherdev needs to have some input on this.
