### ISSUE TITLE
Error appeared when state try to apply selection on already removed record

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4535]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21077&p=104309#p104309)
[Forum post 2](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20916&p=103608#p103608)

Try to select record, save state, remove selected record and try to apply state.  State has `selectedCell` info.

**Comment by dotchetter** [comment]
Hi, 
I see that this bug isn't included in the release notes but 5.0.3 is selected as milestone. 
Can we assume 5.0.3 contains this fix?

**Comment by chuckn0rris** [comment]
It is included into Grid component release notes as it mentioned in "Projects" section. The fix will be available in all related components.
Yes, 5.0.3 contains that fix.
