### ISSUE TITLE
Calendar fires an eventundefined event upon key down

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4544]
https://bryntum.com/examples/calendar/basic/
Steps to reproduce:
1. go to the URL above
2. add this code snippet inside of calendar
```
    listeners : {
        eventundefined() {
            console.log('fires');
        }
    },
``` 
3. then select an event
4. press any key on the keyboard
5. and it fires

This is the bug.

**Comment by ExtAnimal** [comment]
Bug exists because of incomplete event name map in `EventHelper`.
