### ISSUE TITLE
[LWC] Columns reordering and row reordering features doesn't work

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4545]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21111&p=104467#p104467)

Build our Salesforce example, try to reorder rows/columns using drag-n-drop. Drop is always invalid.

**Comment by freddyLang** [comment]
hi,

where is the solution ??

BR

**Comment by SergeyMaltsev** [comment]
@freddyLang Did you try latest version? If it doesn't work please post a question on [forum](https://forum.bryntum.com) with the details.

**Comment by bmblb** [comment]
@freddyLang you would need to register on the forum to post a question. Sorry for the inconvenience
