### ISSUE TITLE
SimpleTaskEditFeature issues

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4550]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=51&t=21119&p=104495#p104495)

Issue 1 & 2:
Add the following in the AppConfig.ts file inside the config:

```
simpleTaskEditFeature: {
	disabled: false
}
```

1. After enabling the feature the following issue occurs:
2. Click + to create new item in DOING or DONE column
3. Press enter to create task with default name
4. First issue: Task addNewTaskAtEnd does not happen the created task is simply selected.
5. Press enter AGAIN

Second issue: Multiple new tasks are added! And also often some of the new items are added in the 1st column (TODO)
(screenshots attached for these 3 steps)

Issue 3:
Disable addNewAtEnd:

```
simpleTaskEditFeature: {
	disabled: false,
	addNewAtEnd: false
}
```
Here is the video of two issue:

https://user-images.githubusercontent.com/75997756/165777737-e336a508-86ab-4585-934b-73083f2f5bf1.mp4

This config option is ignored and issues above still happen.

Cheers,
Martin
![step1.png](https://bryntum.com/forum/download/file.php?id=17264)
![step2.png](https://bryntum.com/forum/download/file.php?id=17263)
![step3.png](https://bryntum.com/forum/download/file.php?id=17262)

**Comment by isglass** [comment]
Replaced by more on point https://github.com/bryntum/support/issues/4576
