### ISSUE TITLE
Siesta 6 should be published on a company registry

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#4557]
Following the guide here: https://www.npmjs.com/package/@bryntum/siesta I cannot install siesta:
```
npm i -D @bryntum/siesta
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://npm.bryntum.com/@bryntum%2fsiesta - user %USERNAME% is not allowed to access package @bryntum/siesta
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```

Previously I added registry to local npm config as described in our guide:
```
npm config set "@bryntum:registry=https://npm.bryntum.com"
```

I have a feeling that because of that registry NPM is looking for siesta in the wrong registry.

**Comment by SergeyMaltsev** [comment]
`@bryntum/siesta` and `@bryntum/chronograpth` are now proxied from public https://www.npmjs.com repo
