### ISSUE TITLE
Custom defined placeholder for nameField resets after add new event

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4568]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=21136&p=104718#p104718)

Define a placeholder for nameField

```
eventEdit: {
            items: {
                nameField: {
                    label: 'New Label',
                    placeholder: 'New Placeholder'
                }
            }
        }
```
1. Double click on any event, clear text in the field. See the placeholder is correct.
2. Create new event using dblclick on a timeAxis. See that placeholder text now changed on "New Event".
Try to edit any other event as on step 1, see that placeholder is empty now.

**Comment by ExtAnimal** [comment]
This is the config to use: https://bryntum.com/docs/calendar/api/Calendar/widget/mixin/CalendarMixin#config-autoCreate

![Screenshot 2022-08-14 at 14 30 03](https://user-images.githubusercontent.com/200516/184536923-63d5ba5d-cf5a-442c-93cb-89d1a817c5ea.png)
