### ISSUE TITLE
Firefox Resources disappear when Zoom is less than 100%

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4570]
Reproduced with zoom 30% on macbook 13 inches.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21172&p=104774#p104774)

Hi, we have a problem with Bryntum Scheduler when opening it in Firefox.

Prerequisites:
Firefox Version 100.0 (64-Bit)
Basic demo https://www.bryntum.com/examples/scheduler/basic/

How to reproduce:
Chane Zoom of browser to 90% (for a big screen - 70% on a 15 inch laptop) 
Reload basic demo, then resources and the tasks are not visible anymore.

**Comment by AamukthaAukunooru** [comment]
Hi, 
We are waiting on this, could you please provide an update, or any workaround would be appreciated.
Thanks.

**Comment by MosckRF** [comment]
Hello,
It also happens in my application that use Bryntum Gantt.
It can also reproduce in your demo https://bryntum.com/examples/gantt/frameworks/angular/advanced/dist/advanced/
We are waiting for your update.
Thank you

**Comment by matsbryntse** [comment]
@AamukthaAukunooru  @MosckRF Can you please confirm this is working ok for you now?

**Comment by MosckRF** [comment]
Ha @matsbryntse, yes! Now it works properly! thank you

**Comment by matsbryntse** [comment]
Thanks for quick confirmation :) And Happy New Year!
