### ISSUE TITLE
Allow configuring away the RowReorder tree indicator 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4582]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21204)

Hi-

 Using version 5.0.3, while dragging a row to reorder it, we are noticing an insertion/drop indicator appear at the far left of the screen, but not where the drop is going to take place/complete.  We don't see this in the grid row reorder example as it appears this might be due to using a tree column.  The indicator appears on the parent, regardless of which level within the tree you are performing the reorder. 

![row-reorder.gif](https://www.bryntum.com/forum/download/file.php?id=17374)

In the attached movie, notice the small arrow that appears between Project 1 & Project 2, regardless of where i'm dropping the task related to Project 2, so this becomes unintuitive.  Can this specific feature of the RowReorder be disabled like you can the grip, via a toggle?  We are trying to stay away from additional style overrides. 

-Bryan
![row-reorder.gif](https://www.bryntum.com/forum/download/file.php?id=17374)

**Comment by bryandent** [comment]
Hi.  Can you point me to the documentation for this so that I can apply the setting correctly?  Thanks for implementing this!
