### ISSUE TITLE
Implement React JSX support for TaskBoard card items (jsx item type)

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4600]
Our docs for TaskBoard said it's possible to use JSX in renderer, but it fact it's not supported, more than that - renderer method specified in columns object in that code snippet, will be never called. We need to update that section and create an example of using React components inside task element of TaskBoard (CustomElement?). We also need to add an example of implementation into our demos.

https://bryntum.com/docs/taskboard/guide/TaskBoard/integration/react/guide#using-simple-inline-jsx

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=56&t=21226&p=105056#p105056)

**Comment by isglass** [comment]
Guide generation gone wrong, there is currently no support for JSX in TaskBoard at all unfortunately

**Comment by isglass** [comment]
Check the guide in all products!

**Comment by jehret** [comment]
Same problem with the Calendar. 
_Using simple inline JSX_ and Using a _custom React component_ sections should be removed.
