### ISSUE TITLE
Getter to get data from record as plain object

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#4606]
Usecase: When you need to sync data using non-bryntum transport (axios for example), you need to get data from record. 

These are possible temp solutions:
- `record.data` is private
- `JSON.parse(record.json)` skips undefined values (which sometimes is good), but this requires 2 operations to stringify and parse.
- custom function like the one below. It uses public API. ("data" getter is taken.)
```
  /**
   * Returns a simple data object which includes all fields
   * @property {Object}
   * @readonly
   */
  get simpleData() {
    const data = {};

    this.fields.reduce((result, x) => {
      if (!x.internal) {
        result[x.name] = this[x.name];
      }
      return result;
    }, data);

    return data;
  }
```

Note, from my experience users often get data wrong, like `record.originalData` or `record._data` etc

**Comment by matsbryntse** [comment]
Isn't it most relevant to just get the https://bryntum.com/docs/scheduler/api/Core/data/Model#property-modificationData

Assume you don't want to write back any unmodified data...?

**Comment by matsbryntse** [comment]
You can also use https://bryntum.com/docs/scheduler/api/Core/data/Model#function-toJSON to get all raw model data

**Comment by pmiklashevych** [comment]
Thanks! This is exactly what I've been looking for. The naming is confusing. At first glance I thought it was an alias to `json` getter. Could you please improve docs by 
 - adding cross references between `json` property and `toJSON` function
 - adding a block to the top of Model class (though looks like it is already overloaded)
 
 As a feedback, users often search by "data" in the docs. Please consider to update naming. For example use `jsonData` getter to return object and `jsonString` getter to return string.
 
About usecase. It's not only about saving data. When users implement custom components like event editor (that is reusable in different parts of app), they need to pass a plain object instead of bryntum record. So this kind of transformation is quite often operation.
