### ISSUE TITLE
Docs do not scroll members into view correctly

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#461]
https://bryntum.com/docs/grid/#Core/widget/DateField#config-id

gives

<img width="1049" alt="Screenshot 2020-03-25 at 15 15 15" src="https://user-images.githubusercontent.com/218570/77546271-e9d90b80-6eab-11ea-894a-64c7ca64bc41.png">

**Comment by bmblb** [comment]
Not reproducible in latest version of docs
