### ISSUE TITLE
Small screen improvements

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4617]
On mobile devices
- [x] hide Learn button
- [x] hide full screen 
- [x] hide bryntum logo icon
- [x] bigger toolbar button icons (Hamburger, previous / next view buttons)
- [x] Year view, what's ideal view..? Should it stretch to fit width? Google Calendar doesn't include year view in their app. Apple shows 3 side by side, in order to pick month

![IMG_0973](https://user-images.githubusercontent.com/218570/168462925-30956b0b-3020-4b59-8927-659acaf19c14.PNG)

**Comment by dongryphon** [comment]
Not a lot comes to mind except to bump up the font size on small screens:

![image](https://user-images.githubusercontent.com/722969/173829001-60bd8b21-87fe-42f0-9668-992f7438dd7a.png)

**Comment by dongryphon** [comment]
The buttons on the toolbar (as part of https://github.com/bryntum/support/issues/2899) have been moved to a menu

![image](https://user-images.githubusercontent.com/722969/173829237-ecce8693-79d7-4f05-8c73-f3f071b98151.png)
