### ISSUE TITLE
Grid row selection cleared when navigating with keyboard

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4628]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21302&p=105382#p105382)

Hi, I noticed that if there is a selection checkbox column visible on the grid, the user can use the arrow keys and spacebar to select rows. However, if the user then uses the arrow keys to navigate to the rest of the columns, if they are still focused on a selected row then the selection is preserved, but as soon as they navigate to an unselected row, the selection is cleared and the current row is selected. This seems to only happen on certain column types like a Text or Number column, but not on a Percent column. 

I first saw this in the Salesforce environment but was able to reproduce on the Column Types demo https://www.bryntum.com/examples/grid/columntypes/ and I've included a screen recording to show the behaviour. 

Thanks,
Beth

**Comment by marciogurka** [comment]
+1 [here](https://www.bryntum.com/forum/viewtopic.php?p=109210#p109210)

**Comment by matsbryntse** [comment]
https://user-images.githubusercontent.com/218570/187213398-0a042458-e1d4-4f1f-b78f-98a883679a78.mov
