### ISSUE TITLE
[REACT] Bryntum widget wrappers don't accept all component properties in React 18

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4654]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21349&p=105640#p105640)
[Forum post 2](https://www.bryntum.com/forum/viewtopic.php?f=54&t=21713&p=107354#p107354)
[Forum post 3](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21953&p=108594#p108594)
[Forum post 4](https://www.bryntum.com/forum/viewtopic.php?f=44&t=22584)

To reproduce use React 18 and wrap your app into `<React.StrictMode>`

```
<React.StrictMode>
    <App />
  </React.StrictMode>
```

Update - Forum post 2
The React.StrictMode also ignores some custom configurations when enabled.

Related issue
https://github.com/bryntum/support/issues/5390

**Comment by taauntik** [comment]
user asked for the fix [here](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21953&p=108594#p108594)
