### ISSUE TITLE
`OnToggle` in the `CheckColumn` not working

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4661]
Since Column has no `callOnFunctions` field.
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=21353&p=105682#p105682)

In the code below, when I click the checkbox column, the "onToggle", or "onBeforeToggle" or "onToggleAll" event is not triggered.

```
// grid with CheckColumn
let grid = new Grid({
    appendTo   : document.body,
    // makes grid as high as it needs to be to fit rows
    autoHeight : true,
    data       : DataGenerator.generateData(5),
    columns    : [
        { field : 'name', text : 'Name', flex : 1 },
        { type : 'check', field : 'done', text : 'CheckColumn', showCheckAll: true, flex : 1, align : 'center', 
         onToggle: () => Toast.show('onToggle clicked'), onBeforeToggle: () => Toast.show('onBeforeToggle clicked'), onToggleAll: () => Toast.show('onToggleAll clicked') }
    ]
});

// Text only
new Button({
    appendTo   : document.body,
    text     : 'Text only',
    onClick: () => Toast.show('Button clicked')
});

```

**Comment by henriquewerlang** [comment]
`// grid with CheckColumn
let grid = new Grid({
    appendTo   : document.body,
    // makes grid as high as it needs to be to fit rows
    autoHeight : true,
    data       : DataGenerator.generateData(5),
    columns    : [
        { field : 'name', text : 'Name', flex : 1 },
        { type : 'check', field : 'done', flex : 1, align : 'center', text : 'CheckColumn', showCheckAll: true, 
          callOnFunctions : true, 
          onToggle: () => Toast.show('onToggle clicked'),
          onBeforeToggle: () => Toast.show('onBeforeToggle clicked'), 
          onToggleAll: () => Toast.show('onToggleAll clicked') }
    ]
});`

**Comment by henriquewerlang** [comment]
Any news about this bug?

**Comment by taauntik** [comment]
user asked for the fix [here](https://www.bryntum.com/forum/viewtopic.php?f=43&t=21353&p=108510#p108510)

**Comment by henriquewerlang** [comment]
This still not working!
