### ISSUE TITLE
Event bar is not updated after resetting a constraint

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#4675]
Steps: 
1. open `constraints` demo
2. double click `Annual inspection` event
3. in the event editor open `Advanced` tab (has gearbox icon in the demo)
4. there clear `Constraint` field and then click `Save` button

Result: the event bar is not re-rendered - the constraint icon is still drawn.

**Comment by arcady-zherdev** [comment]
Probably duplicates these issues:
https://github.com/bryntum/support/issues/3493
https://github.com/bryntum/support/issues/1372

**Comment by matsbryntse** [comment]
Dupe #1372
