### ISSUE TITLE
TaskBoard doesn't work in React 18

### ISSUE THREAD

**Issue by greglecki** [bryntum/support#4678]
When using React 18 with createRoot the TaskBoard doesn't render on the screen.
There are no errors in the console, just blank screen.

Repro:

1. Update React to version 18
2. Replace ReactDOM.render with  ReactDOM.createRoot
3. Run the app

**Comment by jsakalos** [comment]
This is duplicate of https://github.com/bryntum/support/issues/4654

@greglecki to make the app working in dev mode, remove "strict".
