### ISSUE TITLE
Support dynamically enable/disable the header

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4679]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21388&p=105870#p105870)

Hi,

Is there a function available to dynamically enable/disable the header for the resource utilization widget using a toggle rather than only by the 'hideHeaders' creation config. Users would like to be able to try both options to decide which config to settle on.

Thanks,
Rayudu

**Comment by matsbryntse** [comment]
Easy:

`gantt.eachSubGrid(g => g.header.hide())
`
