### ISSUE TITLE
Scrollbar disappears while scrolling at a certain zoom level

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#470]
Forum: https://www.bryntum.com/forum/viewtopic.php?f=51&t=13644

To reproduce:
http://lh/bryntum-suite/scheduler/examples/basic/

1. See there is no scroll initially
<img width="1773" alt="Снимок экрана 2020-03-27 в 18 14 11" src="https://user-images.githubusercontent.com/57486733/77771018-357be880-7057-11ea-9e2c-a1f9490858a0.png">

2. scheduler.zoomIn() -> see scroll bar appears
<img width="1774" alt="Снимок экрана 2020-03-27 в 18 14 36" src="https://user-images.githubusercontent.com/57486733/77771095-4f1d3000-7057-11ea-82a7-7a9cb831dcde.png">

3. scheduler.zoomOut() -> see there is no scroll
<img width="1773" alt="Снимок экрана 2020-03-27 в 18 14 11" src="https://user-images.githubusercontent.com/57486733/77771018-357be880-7057-11ea-9e2c-a1f9490858a0.png">

4. scheduler.zoomOut() -> see scroll bar is there
<img width="1768" alt="Снимок экрана 2020-03-27 в 18 15 16" src="https://user-images.githubusercontent.com/57486733/77771275-8c81bd80-7057-11ea-8d55-f9649d12a559.png">

3. scheduler.zoomIn() -> see there is no scroll again
<img width="1773" alt="Снимок экрана 2020-03-27 в 18 14 11" src="https://user-images.githubusercontent.com/57486733/77771018-357be880-7057-11ea-9e2c-a1f9490858a0.png">

**Comment by ExtAnimal** [comment]
When it returns to the *initially configured* `ViewPreset`, it also returns to the initially configured start and end date

**Comment by peterwake** [comment]
I am glad you worked this out guys as I was trying to get a demo version to show this (and failing miserably!)
