### ISSUE TITLE
No possible to get ResourceUtilization instance from getBarText method

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4704]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21402&p=105981#p105981)

ResourceUtilization has `getBarText` to customize text, but it is not possible to get ResourceUtilization instance and its store.

**Comment by arcady-zherdev** [comment]
Closing as this is not a bug. It's trivial to get `ResourceUtilization` (shown in the class docs introduction actually). Reaching the store is also trivial:
```js
 new ResourceUtilization({
     getBarText(datum) {
         // view is ResourceUtilization instance
         const view = this.owner;
         // view is corresponding ResourceUtilizationStore instance
         view.store
```
