### ISSUE TITLE
SelectAll checkbox lacks focus rendition

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4707]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21415&p=106009#p106009)

Hi, I noticed that there is discernible UI difference when a user is focused on the Select All checkbox in the header of the selection column and when they are not. This makes it harder to know where the focus is or realise that they can toggle the selection state with the spacebar. I've attached a screen recording where I reproduced this in the Bryntum examples where I use the arrow keys to navigate between the column headers and, unlike the other column headers, there is no change in the state of the checkbox column when it is focused.

https://user-images.githubusercontent.com/75997756/171002700-705da35a-3e42-4c97-b490-184946a59793.mp4

**Comment by marciogurka** [comment]
+1 [here](https://www.bryntum.com/forum/viewtopic.php?p=109210#p109210)
