### ISSUE TITLE
STM tracks changes before cell editing save

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4713]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21420&p=106032#p106032)

Hi Bryntum,

Changing schedule with cell editing puts 2 changes into undo queue.
I think it's a bug.

It can be reproduced in your demo site.
https://bryntum.com/examples/gantt/undoredo/

https://user-images.githubusercontent.com/75997756/171107164-71f0d390-2521-4a12-adf2-158c7e51b267.mp4

I hope it will be fixed in the future.

**Comment by canonic-epicure** [comment]
Seems its not reproducible in the latest code:
https://github.com/bryntum/support/assets/72431/42b9b0be-6a64-42b5-8f7f-b1b1e7c6525a

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/b134b62c-8b3e-46f2-a3ec-b723bbcc4936
