### ISSUE TITLE
Menu is too narrow in the Scheduling cycle window.

### ISSUE THREAD

**Issue by egraves-accuer** [bryntum/support#4752]
![image](https://user-images.githubusercontent.com/93935209/171865055-2ea9c539-0e90-44fa-89b8-e9d3ef396294.png)

**Comment by arcady-zherdev** [comment]
How can we reproduce this? We need a runnable test case ideally ..or at least a dataset that we could load and reproduce the issue.

**Comment by egraves-accuer** [comment]
Our developer submitted via the forum and was assigned a ticket number:
***@***.***

Thanks,
Eric

**Comment by arcady-zherdev** [comment]
This one looks duplicating https://github.com/bryntum/support/issues/4803 which was fixed and released in v5.0.6
