### ISSUE TITLE
PDF export hangs trying to restore component

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4756]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21451&p=106156#p106156)

We have two situations reported and tested that is happening when trying to export to PDF.

1st case:
Zoom in (top bar consists of 2 AM, 8 AM, 2 PM, and 8 PM), select Visible schedule in the export window, and hit export. The export is now stuck. 

![Zoom in stuck page](https://user-images.githubusercontent.com/16693227/171922153-1178b3c7-9761-48d3-b81e-68b8dba8b90c.png)

2nd case:
Zoom out far (for me the least detailed zoom level that is possible), select a date range (I selected 21.07.2022 to 30.09.2022), set landscape, and hit export. The export is now stuck. (on testing returned an error).

![Zoom out error page](https://user-images.githubusercontent.com/16693227/171922325-35c10529-69f4-4475-aa1a-7ac966292702.png)

Also, this happened in the export to PDF example page, so no specific framework was being used.

**Comment by bmblb** [comment]
Cannot reproduce first issue, fixed 2nd one
