### ISSUE TITLE
Using mapped lag field breaks cell editing

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4759]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21448&p=106170#p106170)

Hello,

we are using the React GANNT chart and implemented our own save logic by extending the ProjectModel class and implementing a custom sendRequest method:

```
class CDSProjectModel extends ProjectModel {

public async sendRequest(request: any): Promise<any> {
	// Custom save logic and communication with backend happens here
	// Send request is not called for changes to dependencies...
}
}

```

When the user makes changes to tasks the sendRequestMethod is triggered as we expect. However if a user does changes to dependencies (i.e. changing the lag of a dependency or setting it inactive, etc.) the sendRequest method is not triggered and thus we cannot persist the changes to the backend.

For debug purposes I also attached a listener to the dependency store by doing:

```
gantt.dependencyStore.on('change', (event) => {console.log("Dependency change: ", event})

```

On making changes to dependencies the 'change' event is triggered as expected. A sync or save via sendRequest of the ProjectModel is never triggered though.

I also tried setting gantt.dependencyStore.writeAllFields=true just in case.

Do we have to do some additional configuration? Is there anything we have to set up first in order for the ProjectModel sendRequest method to get triggered on changes to the dependency store's records?

I know this question is maybe not specific enough but would appreciate any hints as we are currently pretty lost in fixing this issue...

Many thanks in advance
[advanced.zip](https://github.com/bryntum/support/files/8839077/advanced.zip)

**Comment by chuckn0rris** [comment]
Seems like this problem happens with other fields as well. Please see user notes in forum post.
