### ISSUE TITLE
"Go to task" button at the side of the time axis view when scrolling view 

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4765]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21461&p=106201#p106201)

The goal here is to have an arrow button or something similar when scrolling inside the view, which would trigger a scrollToTask when clicked, similar to the video attached here.

https://user-images.githubusercontent.com/16693227/172171575-d7172890-c793-4c17-87d7-edd544f32e78.mov

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/225
