### ISSUE TITLE
Not able to edit other rows after adding invalid successor

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4770]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=52&t=21434&p=106215#p106215)

Steps to reproduce:
1. Go to this example https://bryntum.com/examples/gantt/advanced/
2. Then do what the video shows below

https://user-images.githubusercontent.com/75997756/172329158-3bb93b26-9141-4fb2-bddb-2fb9b2c38047.mp4

Expected:
1. It should not clear the input area. It seems that it is simply an invalid dependency. 1.1.5;1, and it's correct that you cannot exit with an invalid value. But the input area should not be blank. It should show the bad value

**Comment by matsbryntse** [comment]
I cannot reproduce on latest version, please comment if you are still able to
