### ISSUE TITLE
mask not updated after element resize

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4778]
Go to web sockets demo (which calls maskBody) http://lh/bryntum-suite/scheduler/examples/websockets/
make screen taller

<img width="1680" alt="Screenshot 2022-06-07 at 21 03 13" src="https://user-images.githubusercontent.com/218570/172461802-7bc1d7a1-a71b-40bf-9b46-0955af6b999c.png">

**Comment by dongryphon** [comment]
I am not seeing this locally:

![image](https://user-images.githubusercontent.com/722969/172504482-0304a253-7527-449f-9915-55d4637e97c9.png)

Now taller:

![image](https://user-images.githubusercontent.com/722969/172504518-bf89072d-d6b5-4354-96f9-f20c3dce012b.png)
