### ISSUE TITLE
React calendar issue when setting state

### ISSUE THREAD

**Issue by cruiser8-203x** [bryntum/support#4782]
https://user-images.githubusercontent.com/5343004/172693392-a9000511-d36c-436d-bba8-fbe09d22dff3.mp4

When using react calendar, if a state hook is used to set a variable in the component containing the calendar or from a parent component, the calendar rerender causes the top bar to lose its original display. It also causes the eventEditor to stop functioning with the following error. 

`Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at get editor (calendar.module.js:109839:1)
    at EventEdit.internalShowEditor (calendar.module.js:109912:1)
    at EventEdit.internalShowEditor (calendar.module.js:127458:1)
    at EventEdit.doEditEvent (calendar.module.js:127417:1)`

**Comment by marciogurka** [comment]
The setState function seems to trigger the following method inside `BryntumCalendar.js`.

```
shouldComponentUpdate(nextProps, nextState) {
    return shouldComponentUpdate(this, nextProps, nextState);
  }
```

and it's kind of "resetting" the toolbar, I still need to take a deeper look into that. @matsbryntse @cruiser8-203x

**Comment by marciogurka** [comment]
Hey @cruiser8-203x I tried to reproduce that behavior and created a sample project, but didn't get the result that you shared. Could you please check if the example is a valid one and adjust it if needed?

[visible-hours.zip](https://github.com/bryntum/support/files/12313288/visible-hours.zip)

**Comment by jsakalos** [comment]
Actually, I can reproduce the problem with your showcase @marciogurka. Anyway it is not a problem in Bryntum libraries but the problem of the demo (I will update the demo to solve it). 

If you watch the console, you can see the warning:

<img width="820" alt="Screenshot 2023-08-10 at 16 10 02" src="https://github.com/bryntum/support/assets/204844/d8fff549-059c-47e7-a25f-16968c47aca3">

Although it's just a warning it is really serious and needs to be fixed for the app to work properly. The fix here would be:
```
    const calendarConfig = useState({
        // Start life looking at this date
        date : new Date(2020, 9, 12),
    // ...
```
