### ISSUE TITLE
No response when pressing the down key in a textarea field of the event editor

### ISSUE THREAD

**Issue by cruiser8-203x** [bryntum/support#4787]
https://user-images.githubusercontent.com/5343004/172857715-17471cfa-336d-4beb-b5a0-e35e4a239c9c.mp4

<BryntumCalendar
                {...calendarConfig}
                {...props}
                eventEditFeature={{
                    editorConfig:{
                        items:{
                            textAreaExample:{
                                label:'Textarea',
                                type:'textarea'
                            }
                        }
                    }
                }} ref={calendarRef}/>

I can click the up key and use the return key but there is no response when clicking **down key** in a textarea to move the cursor downwards.

Bryntum Calendar React 4.3.9

**Comment by matsbryntse** [comment]
Can you please try the latest 5.0.5 version? I cannot reproduce this.

**Comment by cruiser8-203x** [comment]
I was ready to ship a feature for react calendar 4.3.9 when I found this issue. It caused an issue where getting the value for the bryntum textarea could not be retrieved so I had to use basic javascript. I tried upgrading it to 5.0.5 and it failed for our project due to a bug I filed previously.

**Comment by matsbryntse** [comment]
> I tried upgrading it to 5.0.5 and it failed for our project due to a bug I filed previously.
Can you please let us know which bug so we can follow up?

**Comment by cruiser8-203x** [comment]
> Can you please let us know which bug so we can follow up?

https://github.com/bryntum/support/issues/4782

**Comment by matsbryntse** [comment]
We will look into that one shortly!

**Comment by matsbryntse** [comment]
@cruiser8-203x Can you still reproduce this issue?
