### ISSUE TITLE
Calendar - recurring events

### ISSUE THREAD

**Issue by dongryphon** [bryntum/support#479]
User should be able to create and edit recurring events.

- [x] Reuse recurrence editor if possible
- [x] Event instances should be individually editable and cancelable.
- [x] Event series should be editable and cancelable.
- [x] Should be able to delete "this and subsequent events"

**Comment by ExtAnimal** [comment]
Also implementing https://github.com/bryntum/bryntum-suite/issues/1104

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/1160
