### ISSUE TITLE
Grid row freezes when reordering multiple rows

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4798]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21498&p=106356#p106356)

https://www.bryntum.com/forum/viewtopic.php?f=43&t=21522&p=106436#p106436
Hello!

We integrated Bryntum 5.0.0 in our application and we have a problem that is reproducible on the official row reordering example: https://bryntum.com/examples/grid/rowreordering/

Steps to reproduce: using drag and drop, reorder multiple rows in the demo, one after the other. After a few seconds of repeating this action, the current active row freezes in an intermediate/overlapping position. No other operations can be performed on the scheduler unless the page is being refreshed.

Video:

https://user-images.githubusercontent.com/75997756/173100000-1d5f1ff2-ec20-4b20-a817-6c4386be40c4.mp4

**Comment by SergeyMaltsev** [comment]
> Looks like it reproducible on Windows only

Reproducible on MacOS in Chrome and Safari.
