### ISSUE TITLE
Rendering fails if normal region is collapsed initially

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#48]
Add to basic scheduler sample:
```

subGridConfigs: {
        locked: { collapsed: false },
        normal: { collapsed: true } // swap these booleans for same issue
    },
```

Console logs: "No available space provided for time axis. Make sure you have set width for horizontal mode and height for vertical"

**Comment by matsbryntse** [comment]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=12748&p=66755#p66755

**Comment by ExtAnimal** [comment]
The Scheduler's `timeAxisSubGrid` relies a lot on width.

It initializes itself on first paint (Used to be on render, but that has no meaning as a lifecycle stage now)

But if at first paint time, the width is zero, it cannot initialize itself. It has to put this off until expand.

But the `set width` part of expand fires events into parts of the machinery which assume everything is all functional. This is in fact now part of the setup phase.

Part of the solution is a proper `SubGrid` subclass to encapsulate a timeAxisSubGrid which could then have its own specializations.

One of which would be a `set width` implementation which could route into necessary initialization.

**Comment by ExtAnimal** [comment]
So `GridSubGrids#initSubGrids` should not do `new SubGrid`.

It should call `me.createSubGrid(subGridConfig)` which by default would just create  base `SubGrid`, but subclasses could implement their own ways of instantiating and initializing the sub grids.

**Comment by isglass** [comment]
Replaced by bryntum/support#248
