### ISSUE TITLE
Changes not reverted when close TaskEditor with Esc

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4805]
1. Open advanced example.
2. Dblclick on task to open TaskEditor
3. Change task name
4. Click Esc to close editor

See name changes remain applied. Should be reverted.

**Comment by isglass** [comment]
Problem is that ESC blurs the field, updating the record. But that update happens after stm undos the edit, so it slips through. Need to block this, perhaps by checking `!this.hidden` in FormTab#onFieldChange, or by blurring earlier
