### ISSUE TITLE
Selected value doesn't appear when using basic combo editor for a column

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4814]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21520&p=106421#p106421)
Use  https://bryntum.com/examples/gantt/basic/
Add a column

```
 {
    text: "Hold",
    htmlEncode: false,
    renderer: ({ value }) => {
        return value;
    },
    editor: {
          type: "combo",
          items: ["","Hold"]
        }
    }
```

Select "Hold" click outside to save selected value. See that cell remains empty. Scroll down to hide row from visible area, and scroll back. See value is there after re-render.

**Comment by JockeLindberg** [comment]
I have investigated this issue and the problem is that there is no valid field specified on the column. Specify a field to the column and also configure the TaskModel with the same field.
