### ISSUE TITLE
Prevent changing month when clicking dates in month view

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4832]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=21563&p=106621#p106621)

2. how to disable switch to pre month or next month when click the first row days or last row days

**Comment by ExtAnimal** [comment]
This requirement is addressed in this PR: https://github.com/bryntum/bryntum-suite/pull/5018

In `CalendarPanel` (`MonthV iew` isa `CalendarPanel` there is

```
            /**
             * Configure this as true to disable interaction with cells which are outside the range of the current month.
             * @config {Boolean}
             */
            disableOtherMonthCells : null,

            /**
             * Configure this as true to hide cells which are outside the range of the current month.
             * @config {Boolean}
             */
            hideOtherMonthCells : null,
```

So the client can either make "other month" cells non interactive, or hide them completely.
