### ISSUE TITLE
Summary feature showing incorrect values when enabled after scheduler initialization

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4835]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21569&p=106633#p106633)

Use summary example for the scheduler. Add `disabled: true` in config for summary feature.
Open app, scroll right a bit (few cells) and enable feature in console. `scheduler.features.summary.disabled = false`.

See that summary cells are not aligned correctly. Try to scroll a bit, it will fix alignment.

**Comment by taauntik** [comment]
user asked for the fix [here](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21569&p=108660#p108660)
