### ISSUE TITLE
Custom component doesn't appear in the toolbar overflow menu

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4844]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21582&p=106738#p106738)

The `CustomButton` is shown on the toolbar but when you decrease the browser window it goes inside of a toggle button then when you click on the toggle button the overflow menu pops up and it doesn't show the custom button

The following code adds a custom-button widget as the last item in the toolbar:

```
import Toolbar from '../../../lib/Core/widget/Toolbar.js';
import '../../../lib/Scheduler/widget/UndoRedo.js';
import Button from '../../../lib/Core/widget/Button.js';

/**
 * @module GanttToolbar
 */

/**
 * @extends Core/widget/Toolbar
 */
export default class GanttToolbar extends Toolbar {
    static get type() {
        return "gantttoolbar";
    }

    static get configurable() {
        return {
            items: [
                {
                    type: "buttonGroup",
                    items: [
                        {
                            color: "b-green",
                            ref: "addTaskButton",
                            icon: "b-fa b-fa-plus",
                            text: "Create"
                        }
                    ]
                },
                {
                    type: "datefield",
                    ref: "startDateField",
                    label: "Project start",
                    width: "30em",
                },
                {
                    type: "textfield",
                    ref: "filterByName",
                    width: "30em",
                    label: "Find tasks by name",
                },
                {
                    type: "custom-button"
                }
            ]
        };
    }
}

class CustomButton extends Button {
    static get type() {
        return "custom-button"
    }

    compose() {
        return {
            text: "Some Text"
        }
    }
}

CustomButton.initClass();
GanttToolbar.initClass();
```

Steps to reproduce :
1. Open our Gantt advanced example
2. In the `GanttToolbar.js` add the above code
3. then run the app.
4. then you'll see the `some text` button shown on the toolbar
5. then decrease the size of the browser window until it creates a toggle button on the right
6. then click on the toggle button it'll pop up the overflow menu but the custom button doesn't appear

![image (2)](https://user-images.githubusercontent.com/75997756/175039273-fa908ee9-9a87-4fa9-b36e-3c0da5513a58.png)
![image (1)](https://user-images.githubusercontent.com/75997756/175039304-7d55deab-13a8-4a1e-aeac-ecfed4748236.png)

**Comment by isglass** [comment]
The snippet overwrites the buttons default DOM structure, loosing the label element. Have suggested alternative approach in the forum thread. Close this ticket if that is accepted
