### ISSUE TITLE
Ctrl btn press causes scroll to selected task on Windows

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4848]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21596&p=106794#p106794)

video:

https://user-images.githubusercontent.com/75997756/175285503-84454710-b514-473a-bef3-e3ce65410934.mp4

You can reproduce it here: https://bryntum.com/examples/gantt/advanced/

Steps to reproduce:
1. select a cell
2. scroll the Gantt chart to the right 
3. then press the Ctrl key

**Comment by JockeLindberg** [comment]
I cannot reproduce this in 5.2.4. @taauntik , can you?

**Comment by taauntik** [comment]
Yes. I'm also not able to reproduce it. then closing it.
