### ISSUE TITLE
Task dragging causes crash

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4859]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=56&t=21635&p=106930#p106930)
[Forum post 2](https://www.bryntum.com/forum/viewtopic.php?f=56&t=22006&p=108814#p108814)

Here is a reproduction video:

https://user-images.githubusercontent.com/75997756/176099153-be45327e-ad35-4fe0-a556-853ae1f44eae.mp4

https://www.bryntum.com/examples/taskboard/columns/

When I drag tasks quickly (as quickly as you can) between columns, it will be crashed as below image displayed, it seems the data flow control issue, please help to look at this issue.

![taskboard-crashed.png](https://www.bryntum.com/forum/download/file.php?id=17833)

**Comment by turnerguo** [comment]
looks like you are not quick enough~ :D do it back and forth will be easy reproduce it.

**Comment by marciogurka** [comment]
+1 post [here](https://www.bryntum.com/forum/viewtopic.php?f=56&t=22006&p=108814#p108814)
