### ISSUE TITLE
Calendar - provide indicator for current day

### ISSUE THREAD

**Issue by dongryphon** [bryntum/support#486]
A filled circle around the day number.

<img width="643" alt="Screenshot 2020-03-30 at 16 06 49" src="https://user-images.githubusercontent.com/218570/77921757-79156300-72a0-11ea-9d7b-3a17ee1f0b8e.png">

**Comment by ExtAnimal** [comment]
Not sure what the context is. The date picker in the sidebar has that.

**Comment by matsbryntse** [comment]
> Not sure what the context is. The date picker in the sidebar has that.

Updated ticket

**Comment by ExtAnimal** [comment]
It does  that.

<img width="523" alt="Screenshot 2020-03-30 at 16 26 43" src="https://user-images.githubusercontent.com/200516/77930815-41f48100-72a3-11ea-9c60-9623b008a56b.png">
