### ISSUE TITLE
Packed events overlap when fillTicks is true and times don't overlap

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4870]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=1&t=21622&p=107038#p107038)

Using the [layouts demo](https://www.bryntum.com/examples/scheduler/layouts/) and just adding the `fillTicks: true` to the configuration and the pack layout, when we schedule two events in the same time range (i.e. 10 AM - 11 AM) but the events don't overlap between them (i.e. Event 1 from 10:10 AM to 10:20 AM and Event 2 from 10:25 AM to 10:35 AM) there is a wrong overlap between them.

![image](https://user-images.githubusercontent.com/16693227/176538519-810e1772-c698-4257-943d-c50429d1e676.png)

**Comment by Syrah-NL** [comment]
Thank you for making a bug report for this. I can add that setting "allowOverlap" to false does *not* fix this.

**Comment by tbrandenburger** [comment]
I had the same issue. When I changed the value of the property headerHeight from 'auto' to a specific number, for example headerHeight: 30 it's working :-)

**Comment by matsbryntse** [comment]
Closing as it seems to work fine for me in the latest version.  @tbrandenburger @Lxxrxns Can you please confirm if it works too for you (without headerHeight magic setting)?
