### ISSUE TITLE
Add support for EmberJS 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4877]
Right now Gantt doesn't work as expected with EmberJS app, there is an error when we open TaskEditor.

Create a demo with EmberJS.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21623&p=106923#p106923)

we install the v5.0.6 into emberjs. The UI shows up but the task edit dialog has error when double click task.

```
gantt.module.js:899 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Store.value (gantt.module.js:899:750704)
    at CalendarField.value (gantt.module.js:899:1210769)
    at CalendarField.set (gantt.module.js:899:31836)
    at CalendarField.value (gantt.module.js:899:1203780)
    at CalendarField.set (gantt.module.js:899:31836)
    at CalendarField.value (gantt.module.js:899:1196983)
    at new Base$1 (gantt.module.js:899:38677)
    at CalendarField.eval (gantt.module.js:891:5694)
    at new m (gantt.module.js:899:100782)
    at CalendarField.eval (gantt.module.js:891:5694)


```

However, after we use the v4.3.0, the edit dialog works fine.
![Screen Shot 2022-06-27 at 11.42.09 AM.png](https://www.bryntum.com/forum/download/file.php?id=17827)
[ember-quickStart-master.zip](https://github.com/bryntum/support/files/9019765/ember-quickStart-master.zip)

**Comment by TonnyBiDa** [comment]
Any updates?

**Comment by rajeshbnv1994** [comment]
Hi,

we are in the process of buying the package, can we have update on this please.

Thanks
Rajesh

**Comment by chuckn0rris** [comment]
@TonnyBiDa @rajeshbnv1994  we've increased priority for this issue. It will be fixed in one of 5.2.x releases. 
Thank you for you patience.

**Comment by rajeshbolisetty** [comment]
@chuckn0rris Any update on this, it has been months, we are not able to use latest feature or bug fixes after version 5,

**Comment by matsbryntse** [comment]
@rajeshbolisetty Is this still an issue for you or is it working in our latest release?

**Comment by rajeshbolisetty** [comment]
@matsbryntse it is working for us, currently we are using 5.5.3
