### ISSUE TITLE
Grid Vue demo error rendering

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4879]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=21659&p=107094#p107094)

The Grid demo that is integrated inside a Quasar-based application with Vue3 has strange behavior when scrolling up. As you'll be able to see in the video link attached.

[Video](https://www.loom.com/share/5ce49306bb4a4b77b7d8bb823f22ca8d)

[This repo](https://github.com/nethopper2/bryntum) has the example with the error happening, it's just clone, run `npm install `and `npm dev`.

The error triggered in this line inside `WrapperHelperVue3.js`.

Need to confirm if it's something wrong in this Wrapper file or it is related to Quasar.

**Comment by jsakalos** [comment]
Somewhere between Vue versions 3.0.0 and 3.2.7 the `refs[key]` was changed to Array. The fix checks for it so the wrapper is now compatible with all Vue 3 versions.
