### ISSUE TITLE
`ResourceFilter` should continue to filter when its own `Store` is filtered

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4897]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=21693&p=107253#p107253)

Open basic calendar demo and run in console:
```
calendar.resourceStore.filter({
    filters: event => event.name.match(new RegExp('o', 'i')),
    replace: true
});
```

After that you will see some of events are filtered in calendar view.

Try to uncheck one of items in resourceFIlter. All works correct, another set of events are hiddeen.
Now try to check it back, so all items in available list of resources (filtered list of resources) looks checked.
See that all events are visible now, even that was hidded because of console filter.
Uncheck resource again, see same result as before - 2 filters applied - console filter (again) and resourceFilter, as it should. 

The reason of such behaviour might be in `onSelectionChange` method of `ResourceFilter.js` .

```
disabled = selected.count === me.eventStore.resourceStore.count;
```

and how this flag is handled after that. So, it just check if selected count equal to store.count, but in case it filtered, it will give wrong result.

**Comment by ExtAnimal** [comment]
I don't understand this.

You filter the **resourceStore**. But refer to the candidate record as `event`. That will not hide any events. It will filter the resourceStore. That has no bearing on which **events** are shown.

It will have an effect on which events show up in the resource filtering list to allow filtering of *events which match resources*.

That filters out **events** for a resource when a resource is unchecked.

Given this confusion, I don't see what a problem could be.

**Comment by ExtAnimal** [comment]
Yes, your analysis is in fact correct. Will fix.
