### ISSUE TITLE
EmptyCalendarEffect description is not clear enough

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#4902]
Sometimes the effect is yielded when a task and its resource calendars have no any availability intersection.
And in these cases the description `"foo" calendar does not provide any working time intervals.` does not explain anything to user.

Need to detect such cases and show a more meaningful message. Plus would be nice to suggest `Ignore resource calendars` option (should be not that hard to implement).

**Comment by chuckn0rris** [comment]
Please also check if working interval is shorter than tasks duration planned.
Example: task duration - 3 days.
calendar:
```
    "calendars"          : {
        "rows" : [
            {
                "id"                       : "day",
                "name"                     : "Day shift",
                "unspecifiedTimeIsWorking" : false,
                "intervals"                : [
                    {
                        "startDate" : "2020-03-23T07:00",
                        "endDate"   : "2020-03-23T17:00",
                        "isWorking" : true
                    }
                ]
            }
        ]
```
