### ISSUE TITLE
when infiniteScroll is enabled and left menu is collapsed, task dragging jumps to the past

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4913]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21612&p=107342#p107342)

video:

https://user-images.githubusercontent.com/75997756/177998804-6246cf48-8e06-40bb-a98c-23c1ef62fadf.mov

Steps to reproduce:

1. enable infinite scroll config.
2. close the left menu
3. And then dragging a task will go to the past

**Comment by bbcgreg** [comment]
Is there any ETA on a fix for this issue?

**Comment by Aarbel** [comment]
up !

**Comment by matsbryntse** [comment]
Can you reproduce this in in our latest version? Are you able to provide a minimal test case that we can use to reproduce against latest version?

**Comment by taauntik** [comment]
Not reproducible with the latest version.
