### ISSUE TITLE
Support for rendering custom html in ResourceTimeRanges

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4922]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21738&p=107479#p107479)

We currently don't support a customTemplate into the Resource TimeRange feature. Maybe we could add it as we have with Toolbar or something like that, with a DOM structure object or with an HTML markup.

**Comment by marciogurka** [comment]
[+1](https://www.bryntum.com/forum/viewtopic.php?p=110562#p110562)

**Comment by jeffallen6767** [comment]
+1 for this feature, we could use this as well

**Comment by Francisco-Araujo** [comment]
+1 Any update in this feature? It would be very useful

**Comment by tcs-rliess** [comment]
+1

**Comment by matsbryntse** [comment]
Implemented, will be part of 5.6!

**Comment by matsbryntse** [comment]
Yes it did! Here you go https://bryntum.com/products/scheduler/docs/api/Scheduler/feature/ResourceTimeRanges#function-resourceTimeRangeRenderer

**Comment by Manish-Pradhan-FP** [comment]
Awesome. Thank you!!!
