### ISSUE TITLE
Scrollbar remains after removing all rows

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4926]
Advanced demo, remove all tasks:

<img width="1103" alt="Screenshot 2022-07-13 at 10 18 09" src="https://user-images.githubusercontent.com/218570/178685644-741c14f1-119e-49eb-b8ec-f3f862b61312.png">

**Comment by ExtAnimal** [comment]
Missing a call to `grid.rowManager.esimateTotalHeight` when the store's count grows or shrinks.
