### ISSUE TITLE
Double click edit modal not functioning as expected

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4942]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21771&p=107611#p107611)

In the SchedulerPro example provided, there is a basic configuration with a defined EventStore, ResourceStore, and AssignmentStore, but when loaded, the default double-click modal to edit an event doesn't open, and after creating a new event, there are some wrong store updates being executed. 

https://user-images.githubusercontent.com/16693227/179282203-4dd22f73-ddc8-4c25-9cf0-ebabeb5b5bc9.mp4

[SchedulerPro-issue.zip](https://github.com/bryntum/support/files/9123004/SchedulerPro-issue.zip)

**Comment by matsbryntse** [comment]
Invalid data
