### ISSUE TITLE
Changing the time by dragging an event triggering an error

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4943]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21772&p=107608#p107608)

In the example provided, with a simple configuration, when the user tries to add/remove more time to an event by clicking and dragging the left/right side of an event, an error occurs, and the SchedulerPro freezes.

![Console error call stack](https://www.bryntum.com/forum/download/file.php?id=18067)

[SchedulerPro-issue.zip](https://github.com/bryntum/support/files/9123135/SchedulerPro-issue.zip)

**Comment by marciogurka** [comment]
This maybe is related to #4942

**Comment by chuckn0rris** [comment]
As user reported, this issue may be fixed if `eventEdit` feature is enabled in config. Please check that moment, why it fix this problem.

**Comment by Tomboi88** [comment]
@chuckn0rris,

I do not believe the tickets are related.

The `eventResize: true` feature is still an issue in `v5.1.0`.

Thanks

**Comment by chuckn0rris** [comment]
Hi @Tomboi88,
We will investigate that deeply when we start work on this ticket. The error we see is the same in both cases, we don't know if it's related or not, but it will be tested with all described scenarios, no worries.
