### ISSUE TITLE
Error when dragging tasks in Gantt+TaskBoard application

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4949]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21727&p=107561#p107561)

Not consistently reproducible, but I was able to repro 4 times in 5 minutes. 
1. Opened gantt-taskboard demo
2. Created a new task in TaskBoard using "+" button. 
3. Dblclick to change name and add start/end dates. As example 1 day duration.
4. Clicked on task in taskboard to scroll gantt view to that task.
5. Drag task and drop it to make it child of last expanded parent task.

From now, try to drag and drop task from one parent task to another, drop it outside of parent task into root, and back to make it subtask. I've seen this problem when I dragged it from subtask to root, as well as moved it from one parent to another.

<img width="1661" alt="Screenshot 2022-07-18 at 18 26 42" src="https://user-images.githubusercontent.com/7203098/179549799-4e8b2853-5c34-4f45-afbc-a80f0449697b.png">

**Comment by matsbryntse** [comment]
Can't repro
