### ISSUE TITLE
Enable CheckColumn to be read-only

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4960]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=21808&p=107779#p107779)

Using a demo like [this one](https://bryntum.com/examples/grid/celledit/).

Change the column snippet as follows:

```
        { text : 'check', field : 'done', type : 'check', readOnly : true },
```

We want that with that configuration, the checkbox renders in readOnly mode.

------------------------------------------------------------------------
UPDATE 07/22

The editor is not a valid configuration in any situation because the check type renders a widget, we currently don't have support for readOnly in this field, so, I'll change the ticket for a feature request type.

**Comment by henriquewerlang** [comment]
If uses "editor : false", the check can be changed too.

**Comment by marciogurka** [comment]
Hey @henriquewerlang,

Actually, the checkbox type renders a widget, so the editor configuration is not valid in any situation, so the only valid configuration for the checkbox would be this one

``` { text : 'check', field : 'done', type : 'check', readOnly : true },```

Which still remains to implement it, as a feature request.

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=112951#p112951) user asking for this

**Comment by matsbryntse** [comment]
Working fine in 6.0!
