### ISSUE TITLE
Grid Vue Docs quick start guide navigation issue

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4967]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=21821&p=107849#p107849)

- Go to Grid/Quick start/Vue 3. 
- The text in the "broad steps" section at the top doesn't match the text in the "Contents" section on the right for Step 4. 
- Also clicking the "Configuring the Grid Component" link doesn't do anything.
- Additionally for Step 4, it looks like the same code snippet is shown under "Edit the src/App.vue file and replace the content with the following" and under "Create a src/AppConfig.js file with the following content:"

**Comment by jehret** [comment]
It moved from "Configure" to "include" the component and I think none of them are good. "Add" seems better.

**Comment by jehret** [comment]
[fixed in branch](/bryntum/bryntum-suite/tree/4967-grid-vue-docs-navigation)
