### ISSUE TITLE
Performance issue taking lot of time to load

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4977]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21860&p=108075#p108075)

Hi Team,
We have around 4000 events and 700 resources to load.But this is causing a performance issue and on loading it is taking more then 6 sec.
I check this example https://bryntum.com/examples/examples-scheduler/bigdataset/ and found that here in 800 resource and only in 100 event it is taking more then 5 sec which is again not a good user experience.
We want to know  the maximum threshold value for resources and event that we can load without any performance issue, it should load(render) in maximum 2 secs.
Added video for reference.

**Comment by matsbryntse** [comment]
Not enough information
