### ISSUE TITLE
zoomToFit(options) - options object doesn't work

### ISSUE THREAD

**Issue by FlowIT-JIT** [bryntum/support#4985]
The zoomToFit(..) function takes an options argument:
`gantt.zoomToFit({ marginLeft: 100, marginRight: 100 });`
https://www.bryntum.com/docs/gantt/api/Gantt/view/Gantt#function-zoomToFit

No matter what _number_ values are passed via `options` it doesn't change anything in regards to spacing on the left and right side of the gantt diagram.

I'm working with Gantt version 5.1.0

**Comment by matsbryntse** [comment]
Typo in your code:

`gantt.zoomToFit({ leftMargin: 100, rightMargin: 100 });
`

**Comment by FlowIT-JIT** [comment]
Well, that was embarrassing. Thanks.
