### ISSUE TITLE
Horizontal scrollbar missing in Firefox on Ubuntu

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4989]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=21897&p=108257#p108257)

Looks like it is only reproducible in ubuntu.

Reproducible in here (e.g. https://bryntum.com/examples/grid/multiregion/)

In **windows + firefox**:
![Screenshot 2022-07-29 163451](https://user-images.githubusercontent.com/75997756/181756754-5622d46d-b579-47f7-895e-127ac416e2d5.png)

In **ubuntu + firefox**:
![no_scrollbar](https://user-images.githubusercontent.com/75997756/181756960-31ad5cdb-de4a-400f-8de0-d8209d4c400d.png)

**Comment by Xatenev** [comment]
@taauntik Any news regarding this issue? Will this be fixed?

**Comment by canonic-epicure** [comment]
This is just a FF setting on Ubuntu - scrollbars are hidden by default. To show them always one need to enable the special seting: https://superuser.com/questions/1720362/firefox-scroll-bar-disappearing
