### ISSUE TITLE
Should not allow creating or dragging events for `readOnly` resources

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#4995]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21913&p=108317#p108317)

In any Angular demo, if you set up a resource to be read-only, you still be able to add an event by double-clicking the row, and also able to drop some event to that resource, but in read-only mode that shouldn't be possible.

**Comment by isglass** [comment]
We need a more detailed way of specifying what read-only means. Currently it means that you can't directly edit the resource. But assigning events technically adds an assignments, it does not manipulate the resource. Converting this to a feature request
