### ISSUE TITLE
`AjaxStore` `beforeRequest` doesn't allow to make changes in request body

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4999]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21918&p=108362#p108362)

https://bryntum.com/docs/scheduler/api/Core/data/AjaxStore#event-beforeRequest has `body` param that contains request body. But changes applied on that won't be catch. 
More than that if you change `read` http method to POST using our public api, body won't be send to `beforeRequest` as well as somehow checked/generated in the code.

It should be working. 

Code for test

```
eventStore : {
            readUrl: '/url',
            updateUrl: '/url',
            autoLoad : true,
            useRestfulMethods : true,
            httpMethods : {
                create : 'POST',
                read : 'POST',
                update : 'PATCH',
                delete : 'DELETE'
            },
            headers : {
                'Content-Type': 'application/json'
            },
            listeners : {
                beforeRequest : (event) => {
                    debugger
                    event.body = {hello: 1};
                }
            }
        },
```

**Comment by ExtAnimal** [comment]
We should allow them to replace the property. We'd just need to add one line to extract the data to send *after* the event handler has been called.

There are three occurrences of code like this in `AjaxStore`:

```
            event.body = { ids : removed.map(r => r.id) }; 

            me.trigger('beforeRequest', event);

            // Extract the data object *after* event handler has seen the event.
            let dataToSend = event.body
```
