### ISSUE TITLE
Input elements returned from eventRenderer cannot be focused

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#500]
Reported here https://bryntum.com/forum/viewtopic.php?f=44&t=13654

Steps to reproduce: 

1. Return `<input type="text" />` from eventRenderer
2. run and try to type a text in an input.

I'm not sure if we should support it. If not, we should say that in docs.

**Comment by ExtAnimal** [comment]
Qe should definitely not support it. An isolated input field in a transiently rendered element. What would they do with it?

There is https://www.bryntum.com/docs/scheduler/#Scheduler/feature/SimpleEventEdit

It edits the `name` field, but that should be configurable.
