### ISSUE TITLE
Group expanders still visible after stopping grouping

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#5010]
To reproduce:

1. navigate to https://bryntum.com/examples/scheduler-pro/resource-non-working-time/
2. right-click on "SHIFT" column and select "Group ascending" – mind the special rows with group expanders
3. right-click on "SHIFT" column again and select "Stop grouping" – the group selectors are still visible.

![grouping](https://user-images.githubusercontent.com/204844/183072019-c33ba150-9576-4417-bc46-40206d38fa0b.gif)

**Comment by EchNet** [comment]
@matsbryntse  Swivu is hoping that this is an easy fix that makes it into the next point release!
