### ISSUE TITLE
Support merging cells in unsorted columns

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5012]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21962&p=108608#p108608)

Hi there,

when reordering rows that are both part of the same merged cell of a column using mergeCells, the cells of the column are not merged anymore. 

How to Reproduce:
Go to https://bryntum.com/examples/examples-scheduler/merge-cells/
Add rowReorder: true to features
Exchange two rows of same merged cell (Apparently this works)
Exchange two more rows of same merged cell
Now it breaks in the sense that the cells are not merged any more

Before 4:
![Screenshot 2022-08-05 at 18.52.09.png](https://www.bryntum.com/forum/download/file.php?id=18320)
After 4:
![Screenshot 2022-08-05 at 18.57.24.png](https://www.bryntum.com/forum/download/file.php?id=18321)

A quickfix is to add scheduler.resourceStore.sort('team', true); after the rows have been reordered, but there is still a small flicker where you can see that it is wrong in between.
![Screenshot 2022-08-05 at 18.52.09.png](https://www.bryntum.com/forum/download/file.php?id=18320)
![Screenshot 2022-08-05 at 18.57.24.png](https://www.bryntum.com/forum/download/file.php?id=18321)

**Comment by isglass** [comment]
MergeCells only works for sorted columns (stated in docs), reordering rows means it is no longer sorted. Could add a more clear note on that it does not play well with RowReorder feature

**Comment by schTi** [comment]
Hi @isglass,

I see that sorting and mergeCells are closely related. Just one thing: If you check the example I linked, and additionally remove the `name` sorter on the resourceStore, it is still breaking when reordering. The point is if you reorder rows that are part of the same team, the teams are still sorted correctly, and should therefore not break the grouping.

**Comment by lassesteffen** [comment]
Hi @isglass I see that you removed the bug label, but we still believe it's a bug and concerning us, can you check again?

**Comment by isglass** [comment]
It is behaving according to spec, it is designed to only work with sorted columns and when reordering rows sorting is disabled. But I can repurpose the ticket to be a feature request for supporting merging cells with same value even if not sorted by the column

**Comment by schTi** [comment]
@isglass Yes, it would be great to have this implemented.

**Comment by taauntik** [comment]
[Another user requested this feature](https://forum.bryntum.com/viewtopic.php?p=120048#p120048)

**Comment by isglass** [comment]
Requested here too https://forum.bryntum.com/viewtopic.php?p=121896#p121896
