### ISSUE TITLE
STM queue should not update its queue on phantom to real Id change 

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#5013]
Steps to reproduce:

1. open gantt `php` demo
2. click `Create` button to add a new task
3. Undo button badge shows 1 action to rollback
4. click `Save`

Result: Undo button badge shows 2 actions to rollback but STM actually ignores id changes. So it looks like STM puts an empty change set into its queue.

**Comment by arcady-zherdev** [comment]
Should be fixed in this method of `ModelStm` mixin
```js
    shouldRecordFieldChange(fieldName, oldValue, newValue) {
        const store = this.firstStore;

        // By default we do not record:
        // - not persistable field changes
        // - null vs undefined changes
        // - "id" changes
        // - "parentId" changes caused by parent record idChange
        return !(
            this.constructor.nonPersistableFields[fieldName] ||
            (!oldValue && !newValue) ||
            fieldName === 'id' ||
            (fieldName === 'parentId' && store && store.oldIdMap[oldValue] === store.getById(newValue))
        );
    }
```
should ignore both `id` (already does) and `$PhantomId` (doesn't do it currently and that's the root cause of the bug) field changes.

**Comment by canonic-epicure** [comment]
Already fixed in https://github.com/bryntum/bryntum-suite/commit/3d28204d24428525daf868c836adaa3e8b492b3b
