### ISSUE TITLE
[TypeScript] Column type property is not defined 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5031]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21973&p=108666#p108666)

"type" config is not public on [Column](https://bryntum.com/docs/grid/api/Grid/column/Column) class. There is only property. So I get another typings issue.

**Comment by pmiklashevych** [comment]
@isglass please prio it for 5.1.2. Should be an easy fix.
