### ISSUE TITLE
Dependency tooltip contents are misaligned

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5040]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22003&p=108774#p108774)

You can reproduce it here https://bryntum.com/examples/gantt/basic
![collapsed_dependency_tooltip.png](https://www.bryntum.com/forum/download/file.php?id=18374)

It should be aligned like this

![Screenshot 2022-08-10 120103](https://user-images.githubusercontent.com/75997756/183826856-59669854-66c0-48c5-967e-fc3e362204be.png)

**Comment by ExtAnimal** [comment]
It's a naming issue brought about by RTL.

The little "battery" looking things have the classes `b-right` and `b-left`. They should be b-start` and `b-end`. That way, they will have content, and thereby take up their grid layout column.
