### ISSUE TITLE
[REACT] Gantt crashes when destroyed while the React editor is open

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#5041]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=21982&p=108678#p108678)

Hello,

Can you specify a react editor for columns?

I have it working initially, but it throws an error when I unmount the gantt component with an open editor. Since this feature isn't documented (at least in the gantt docs, although it is included in examples), I was wondering if it wasn't officially supported yet.

The error happens during the destroy method of the Base class. When trying to remove some property from the widget wrapping the react component. gantt.module.js:2873 Uncaught TypeError: Cannot delete property 'value' of [object Object]

Not much is needed to reproduce. The frameworks/react/basic example can be used as long as you introduce a way to unmount the gantt component. Here is what I used:

```
class MyEditor extends React.Component {
  getValue() {
    return '';
  }

  setValue() {}

  isValid() {
    return true;
  }

  focus() {}

  render() {
    return 'editor';
  }
}

const columns = [
  {
    field: 'name',
    editor: ref => <MyEditor ref={ref} />
  }
];

const data = [{ id: 1, name: 'Task 1' }];

const MyGanttWrapper = () => {
  const [show, setShow] = useState(true);
  const toggleShow = () => setShow(currentShow => !currentShow);

  return (
    <>
      <button onClick={toggleShow} type="button">
        Toggle
      </button>
      {show && <BryntumGantt columns={columns} data={data} />}
    </>
  );
}
```
Open up an editor then click the toggle button to unmount the gantt component.

**Comment by gaoJSir** [comment]
How to solve this problem urgently

**Comment by gaoJSir** [comment]
“Cannot delete property 'value' of [object Object] ”     I also have the same problem. How can I solve this problem? I am using version 4.3.5?

**Comment by gaoJSir** [comment]
How to solve the problem of inability to upgrade due to project reasons

**Comment by gaoJSir** [comment]
I don't use a custom editor, do I still want to achieve the effect of custom editing cells? Is there any other way

**Comment by taauntik** [comment]
If you just want the look and feel, it should be doable with our default cell editor with some CSS styling. We might be able to suggest a better solution, if you share your use-case with us!

**Comment by gaoJSir** [comment]
[pmplan.zip](https://github.com/user-attachments/files/20601847/pmplan.zip)

**Comment by gaoJSir** [comment]
@taauntik

**Comment by gaoJSir** [comment]
I found that the same effect can be achieved through a renderer, but after the modification is completed, the value of the cell changes while Gantt remains unchanged. How to make Gantt follow the value changes of the cell
`{ type: 'date',field:con.fieldId,text:con.fieldName,width:con.gridWidth,align:"center",
                    editor :false,
                    renderer: (data:any) => {
                        
                            if(data.value==null || data.value==undefined || data.value==0){
                                return "";
                            }
                            const date = new Date(data.value);
                            const year = date.getFullYear();
                            const month = (date.getMonth() + 1).toString().padStart(2, '0');
                            const day = date.getDate().toString().padStart(2, '0');
                            const formattedDate = `${year}-${month}-${day}`;
                            return <CellEditDate text={formattedDate} data={data}/>;
                        }
                    }`
`import { DatePicker } from "antd";
import React,{ useState } from "react";
import dayjs from 'dayjs';

const CellEditDate = (props:any) => {
    const [show,setShow] = useState(false);
    console.log(props);
    const columnfield = props.data.dataField.name;
    const [value,setValue]=useState(dayjs(props.text, "YYYY-MM-DD"));
    return (
        <>
          {show?
          <DatePicker 
            allowClear={false}  
            onChange={(date,dataString)=>{
               props.data.record.set(columnfield,new Date(dataString));
               setValue(date)
               setShow(false)
            }}
            value={value}
            onBlur={()=>{
              setShow(false)
            }}
          />
          :
          <span onClick={()=>setShow(true)}>{props.text}</span>}
        </>
    );
};
export default CellEditDate;`

**Comment by gaoJSir** [comment]
Okay, you can achieve the same effect through the renderer. Thank you

**Comment by taauntik** [comment]
@gaoJSir Is your problem solved?
