### ISSUE TITLE
Dependency creation tooltip has html encoding issue when adding an html tag with the task name

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5042]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=51&t=22003&p=108790#p108790)

Here is how you can reproduce it:
1. go to https://bryntum.com/examples/gantt/advanced
2. watch this video and do the following

https://user-images.githubusercontent.com/75997756/183843440-b60e55c6-4f6f-4d1d-805a-7f8fa4368570.mp4

**Comment by matsbryntse** [comment]
Not reproducible
