### ISSUE TITLE
New tasks now display their `wbsCode` in Predecessors/Successors picker. Advanced example now uses  `wbsMode: 'auto'`

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5054]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22000&p=108823#p108823)

Here is how you can reproduce it:
1. Open gantt [advanced demo](https://bryntum.com/examples/gantt/advanced/)
3. create some new task
4. connect some dependencies between them
5. open the task editor
6. go to the successors tab
![Screenshot 2022-08-11 110522](https://user-images.githubusercontent.com/75997756/184067941-7953d852-5a29-469c-9042-6c043b8e1d51.png)
7. new tasks don't have the WBS code with it

**Comment by dongryphon** [comment]
It turns out that with `wbsMode: 'auto'` set, the `wbsCode` was assigned but the task pickers did not render it properly
