### ISSUE TITLE
MS Project import demo cannot handle a file

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#5055]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=52&t=22004&p=108775#p108775

The demo cannot handle the attached file: [file.zip](https://github.com/bryntum/support/files/9306296/file.zip)

JSON is built w/o exception yet list of extracted tasks is empty.

**Comment by darshishahtatva** [comment]
Hello @arcady-zherdev ,

If you can find, can you tell us which project / tasks / dependency / calendar is causing the issue? So, we can remove that element from the file and import other elements for now.

Thanks.

**Comment by arcady-zherdev** [comment]
The reason is in MPXJ library we use in the demo. It doesn't handle some versions of MPP files. We need to upgrade it which will be made in this ticket.
