### ISSUE TITLE
Link to Grid basic demo showing 404 error

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5065]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22030&p=109029#p109029)

You can go to this link :
https://bryntum.com/docs/grid/guide/Grid/integration/react/guide#using-react-as-cell-editor 

Here is how you can reproduce it:

https://user-images.githubusercontent.com/75997756/184578664-74933c67-7b9c-45c7-aad5-9893f0929b5c.mp4

**Comment by jehret** [comment]
REJECTED
