### ISSUE TITLE
`readOnly` disables Slider fields and makes them unfocusable

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5067]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22050&p=109099#p109099)

In the [Tree with locked columns](https://www.bryntum.com/examples/grid/lockedcolumnstree/)

When trying to keyboard navigate through the Grid, everything works correctly until the user tries to navigate to a read-only widget cell, when the navigation stop working correctly, for the other read-only cells (not widget), the navigation works correctly. See the video attached.

https://user-images.githubusercontent.com/16693227/184681239-5664a266-56aa-4a3c-84cc-38b4c969b804.mov

**Comment by ExtAnimal** [comment]
Strange that one of the slider inputs gets the `disabled` property. Is that correct for being readOnly? Somebody must have made that decision for Slider field based on a bug in Chrome. `readonly="true"` does not work on Sliders in Chrome. It does in Firefox. The correct solution is to use `readOnly="true"` when readOnly, and report a bug to Chromium.

**Comment by ExtAnimal** [comment]
It appears that the vendors see no problem with readOnly not working on sliders: https://github.com/w3c/html/issues/89

We need to come up with a workaround to make these immutable but still focusable rean readOnly.

**Comment by ExtAnimal** [comment]
This makes a Slider readOnly:

![Screenshot 2022-08-16 at 09 27 55](https://user-images.githubusercontent.com/200516/184822457-49185074-51bb-4f39-a522-5818596129d7.png)

And obviously this to correct disabledness: 

![Screenshot 2022-08-16 at 09 29 24](https://user-images.githubusercontent.com/200516/184822697-6990d9dd-5338-4c7a-bc04-8e1aa659defe.png)
