### ISSUE TITLE
Aggregate Columns Become Fixed to 0 after they're Outdented

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5075]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22061&p=109207#p109207)

Using the example [here](https://bryntum.com/examples/gantt/aggregation-column/)

- Indent any leaf task (e.g. "Configure Firewall"), making the above leaf a parent task;
- Outdent the same task, the parent task will become a leaf task with cost (aggregation column) to 0;
- Try to change the 0 to any other value, it keeps locked in 0;

Video attached with the described behavior.

https://user-images.githubusercontent.com/16693227/185139026-3351015a-d058-4024-bb6c-08a9b23352d0.mp4

**Comment by matsbryntse** [comment]
Not reproducible in latest
