### ISSUE TITLE
Gantt color picker for task bar

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5082]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=9&t=22083&p=109265#p109265)

Hi,

For ExtJS Gantt there was a color picker to change taskbar color, is there something similar in bryntum gantt. Please share references if any

Thanks!!

**Comment by JockeLindberg** [comment]
https://bryntum.com/products/gantt/docs/api/Scheduler/column/EventColorColumn
