### ISSUE TITLE
[REACT] TimeAxis header rendering problem when switch view presets

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5085]
Was not able to reproduce in vanilla. Looks relevant to React. Header becomes visible after scroll a bit.

Reproducible only in case browser window width is small enough to have scroll appeared. Reproduced using path 2 described below.

Test case below in a comment.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=22058&p=109294)

We have a datepicker and a preset switcher. In month view, not all days are always shown. 

What are we doing wrong? I have attached our project as an attachment. I've also added some images

Reproduction path 1

Open the react application
Switch from day to month
Switch from month to day
Switch from day to month
Notice that not all days are shown

Reproduction path 2

Open the react application
Switch from day to month
Use datepicker and click on 01/09/2022
Use datepicker and click on 01/10/2022
Notice that not all days are shown
![Screenshot 2022-08-16 at 14.42.06.png](https://www.bryntum.com/forum/download/file.php?id=18456)
![Screenshot 2022-08-16 at 14.42.24.png](https://www.bryntum.com/forum/download/file.php?id=18455)

**Comment by chuckn0rris** [comment]
[bryntumplainreact 2.zip](https://github.com/bryntum/support/files/9380441/bryntumplainreact.2.zip)

**Comment by jeffreybos** [comment]
Do you have an estimate of when it will be fixed?

**Comment by chuckn0rris** [comment]
@jeffreybos our product management didn't prioritize it yet. You can subscribe on ticket updates to see when milestone is set and when ticket changed the status.

**Comment by chuckn0rris** [comment]
Not reproducible in latest version
