### ISSUE TITLE
`Datepicker` year select doesn't allow to configure year options

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5096]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=22104&p=109358#p109358)

In the Core.widget.DatePicker, if you click on the year inside the header, you'll see a select with the year options (20 years before and 20 years after), but if we need to add more years, we can't have that (even if we add minDate property)

For example, try to add a DatePicker like this:

```
const picker = new DatePicker({
    appendTo : 'container',
    width    : '24em',
    date     : new Date(),
    minDate  : '1995-01-01'
});
```

If you check that year select, the minimum year is still 2002, when it should be 1995.

![screenshot.png](https://www.bryntum.com/forum/download/file.php?id=18514)

**Comment by ExtAnimal** [comment]
There's a PR for a more standard infinitely navigating YearPicker: https://github.com/bryntum/bryntum-suite/pull/4978
