### ISSUE TITLE
Add `autoWidth´ config to Column

### ISSUE THREAD

**Issue by isglass** [bryntum/support#51]
To update its width automatically when contents change (update, sort, filter etc).
Columns already have a `resizeToFitContent()` fn that can be used for this.

Transfered from Assembla #7157

**Comment by dongryphon** [comment]
PR to `master` https://github.com/bryntum/bryntum-suite/pull/381

**Comment by dongryphon** [comment]
The `autoWidth` config and its corresponding grid feature `ColumnAutoWidth` use a buffered method to resize columns when the underlying data change.
