### ISSUE TITLE
Labels should be rendered below other task unless task z-index is higher

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#510]
when a task is selected/focused it should have labels on top to be always readable.

<img width="286" alt="Screenshot 2020-04-06 at 11 47 32" src="https://user-images.githubusercontent.com/218570/78545707-88466480-77fc-11ea-81f1-d3865780ed8c.png">

**Comment by isglass** [comment]
We now increase z-index for selected event, no longer reproducible
