### ISSUE TITLE
Order the fields in the edit view for any tabs

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5100]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22105&p=109361#p109361)

Inside a configuration in the tabs of the Task editor, we would like to have a way to sort it programmatically (as a config mostly).

For example, I would like to have constraintTypeField displayed before the manuallyScheduledField, or any combination like that.

```
 advancedTab: {
          items: {
            constraintTypeField: true,
            constraintDateField: true,
            manuallyScheduledField: true,
            inactive: false,
            calendarField: false,
            schedulingModeField: false,
            effortDrivenField: false,
            rollupField: false,
            divider: false
          }
        }
```
![edit.PNG](https://www.bryntum.com/forum/download/file.php?id=18515)

**Comment by isglass** [comment]
Fields can already be rearranged by specifying new weights
