### ISSUE TITLE
Mouse events not being triggered properly in events on same day

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5111]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=22126&p=109438#p109438)

Using the [basic calendar demo](https://bryntum.com/examples/calendar/basic/)

Set up some mouse listeners the listeners configuration like this:

```
listeners : {
        eventMouseOut  : (event) => console.log('out out out', event.eventRecord.name),
        eventMouseOver : (event) => console.log('in in in', event.eventRecord.name)
    }
```

Then open the browser console and watch the output.

- Moving the pointer vertically over multiple consecutive events in one day does not log any events although the events are highlighted correctly.

- Moving the pointer out to the bottom of an event that has no immediate successor in a day does not log a mouseOut event in the console, although moving back into the event does log a mouseOver event and the highlighting is updated correctly.

**Comment by ExtAnimal** [comment]
Also fails in MonthView when moving *horizontally* into an event in the previous or next day cell.
