### ISSUE TITLE
Implement `startGutter` config in `DayLayout` class

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#5113]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=22107&p=109447#p109447)

Analogous to the `gutter` config, this would be a free space on the start side of a day column.

Probably the `gutter` setting should be renamed to `endGutter` for CSS-like consistency. (But with `gutter` continuing to work for backwards compat)

![image](https://user-images.githubusercontent.com/722969/189543542-d1add4d5-be57-4075-b1b3-fc1a46ccf0b3.png)

**Comment by marciogurka** [comment]
[+1](https://www.bryntum.com/forum/viewtopic.php?p=110051#p110051) for this

**Comment by dongryphon** [comment]
For naming ... maybe `indent`? ... since renaming configs is messy

**Comment by dongryphon** [comment]
This evolved into adding support for "time ranges" to Calendar. A feature like this exists for the Scheduler product, so it made sense to take the same approach in Calendar.

Screenshot from the new demo:

![image](https://user-images.githubusercontent.com/722969/200854349-5ba1ffb7-fb52-44e2-8d37-449d8f0da247.png)
