### ISSUE TITLE
Scheduler doesn't load when zoom level is less than 100%

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5118]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=1&t=22151&p=109536#p109536)

Hello,

https://bryntum.com/examples/scheduler/rowheight/

Scheduler is not loading on Mozilla Firefox when browser zoom is less than 100%.
You can check loading Bryntum scheduler examples with 80% or 90% zoom.

Please help with any workaround.
![firefox_zoom_issue.png](https://www.bryntum.com/forum/download/file.php?id=18558)

**Comment by matsbryntse** [comment]
Dupe #4570

**Comment by MosckRF** [comment]
Hello,
It also happens in my application that use Bryntum Gantt.
It can also reproduce in your demo https://bryntum.com/examples/gantt/frameworks/angular/advanced/dist/advanced/
We are waiting for your update.
Thank you
