### ISSUE TITLE
Project calendar data missing in sync request payload

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5138]
Calendar data missing in sync request payload after change calendar for entire project

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22184&p=109749#p109749)

Enable autoSync in one of our examples and try to set new calendar for a project.

For advanced example it might be
```
gantt.project.setCalendar('night')
```

See that sync request has been triggered and contains changed tasks, but nothing about new project calendar id

**Comment by matsbryntse** [comment]
[#https://github.com/bryntum/support/issues/219](https://github.com/bryntum/support/issues/219)

**Comment by matsbryntse** [comment]
Works fine when setting:

`            trackProjectModelChanges : true,
`
