### ISSUE TITLE
`calendarInterval` doesn't change after an interval is added

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5143]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22190&p=109801#p109801)

You can reproduce it here: https://bryntum.com/examples/gantt/resourceutilization
1. Open browser console
2. paste this code 
```
gantt.resourceStore.getById(5).calendar.intervals;
```
3. then you'll get 2 intervals in an array
4. then paste this code into the console
```
gantt.resourceStore.getById(5).calendar.addInterval({ startDate: '2022-09-02 08:00', endDate: '2022-09-02 18:30', isWorking: false });
```
5. Again run this code
```
gantt.resourceStore.getById(5).calendar.intervals;
```
6. you'll still get 2 intervals

expected : as I added an interval it should show 3 intervals but it shows 2.

**Comment by isglass** [comment]
Intervals are added to `calendar.intervalStore`, which is private. Either that should be documented, or `intervals` should return `intervalStore.records`

**Comment by isglass** [comment]
`calendar.intervals` will point to the interval store, but when serialized it will yield the expected array (with 3 intervals in the scenario above)
