### ISSUE TITLE
Timeline scrolls when event creation canceled

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5155]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=1&t=22214&p=109877#p109877)

Hello,

On vertical view, try creating a new event in the bottom after scrolling down, and click cancel on the event creating popup, then scheduler is automatically scrolling top to the first assignment.

I've attached a screen recording of the same which is happening on vertical view example.
Is there any config to disable this? or do we need to override this fn onGridBodyFocusIn?

https://user-images.githubusercontent.com/75997756/187858758-c2b57d04-a41c-45f3-8310-3b7494899fba.mp4

**Comment by nagasain** [comment]
Can you please prioritize it, it is critical issue for us.
