### ISSUE TITLE
showOnClick shows the tooltip on top-center always

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5160]
it should show where the forSelector directs
![Screenshot 2022-09-01 160934](https://user-images.githubusercontent.com/75997756/187889662-2ad6e43e-3526-4ba0-9865-f061b698408e.png)

**Comment by ExtAnimal** [comment]
More detail needed. Who is sowing that tooltip? Is it a grid feature? The picture is too small to see what is happening.

**Comment by ExtAnimal** [comment]
`Popup` needs `onElementUserAction` to be fixed like this:

```
    onElementUserAction() {
        if (!this.disabled) {
            this.showBy(this.forElement);
        }
    }
```

But `Tooltip` has more to do. It can probably be routed to the pointer over handling by adding `onElementUserAction`:

```
    onElementUserAction(domEvent) {
        this.internalOnPointerOver(domEvent);
    }
```

**Comment by matsbryntse** [comment]
@taauntik Cannot reproduce, please reopen with test case if you can still repro
