### ISSUE TITLE
Add an article with explanation task duration approach

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5162]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22217&p=109906#p109906)

Add an article why any date +1 day cannot finish in the same day and why task with startDate 01.01.2022 with 1 day duration will have endDate 02.01.2022

**Comment by kitsunekyo** [comment]
just stumbled over this issue. i think this is already done and can be closed

https://www.bryntum.com/products/gantt/docs/api/Gantt/model/TaskModel#start-and-end-dates

**Comment by chuckn0rris** [comment]
Thank you for pointing! Closing the issue.
