### ISSUE TITLE
Context menu not working correctly inside the schedule

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5163]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=1&t=22215&p=109879#p109879)

Using Safari Version 15.6.1 (17613.3.9.1.16)

When trying to open a menu inside the scheduler canvas, it flicks and closes. No error is triggered in the console, and on other parts of the application, it opens correctly.

See the video attached for example

https://user-images.githubusercontent.com/16693227/187904150-d65bb566-b822-45df-98d9-cfbc5e8bddf5.mp4

**Comment by AamukthaAukunooru** [comment]
Hello,

We are experiencing a similar issue on Safari 13.1 on macOS Catalina, but in our case, even schedule & event tooltips, and any kind of menu or popups aren't visible.

Could you please prioritize this, it is a critical issue for us as it is blocking almost all basic user actions in Catalina.

Thanks.

**Comment by AamukthaAukunooru** [comment]
Any update on this, please?

**Comment by AamukthaAukunooru** [comment]
Hi,

I see that this is planned for 5.1.x, could you please provide an accurate release timeline also please suggest any workaround if possible.

**Comment by nagasain** [comment]
Hello @marciogurka,

It's been more than 2months since this issue was reported, and as I see that it has been moved to 5.2.x, may I know when we can expect it to be fixed and released, we would request you prioritize this and get it fixed at the earliest.

**Comment by matsbryntse** [comment]
We'll try to look at this shortly. I cannot reproduce this on Safari 16 - can you please try to upgrade as a temp workaround?

**Comment by marciogurka** [comment]
That behavior only happens when the user tries to open the context menu with a ctrl + mouse-click action. 

When used with right-click, it works correctly. Investigating what's causing that.
