### ISSUE TITLE
Calendar listview doesn't respect columns order when rendering

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5164]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=22229&p=109933#p109933)

Using the calendar listview demo, when we set up the columns like this, for example:

```
  modes : {
        list : {
            // If we use field names which the EventList creates for itself, our config
            // gets merged into the default, so we can affect the EventList's own columns.
            columns : [{
                field : 'id',
                text  : 'ID'
            },
            {
                text  : 'Name',
                field : 'name',
                flex  : 1
            }, {
                text  : 'Finish',
                type  : 'date',
                field : 'endDate',
                renderer({ record, value }) {
                    return record.allDay ? DateHelper.format(value, 'L') : this.defaultRenderer(...arguments);
                }
            }, {
                text  : 'Start Date',
                type  : 'date',
                field : 'startDate',
                renderer({ record, value }) {
                    return record.allDay ? DateHelper.format(value, 'L') : this.defaultRenderer(...arguments);
                }
            }]
        }
    },
```

We expect that the order of the grid renders as **ID | Name | Finish | Start Date** 

But we got a different order

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/16693227/187949735-0f808d17-c3df-417e-af00-46f88b333641.png">

**Comment by ExtAnimal** [comment]
See the `mergeColumns` merging function which tries to merge an incoming column set with the default set.

See how https://bryntum.com/examples/calendar/listview/ has a  custom renderer merged into the column definition which matches `field === 'name'`

It has a default set of columns and if you supply a column with the same `field`, it merges yours with the existing definition.

The function could be rejigged to honour incoming order.
