### ISSUE TITLE
Row height slider in Grid Angular 6, 7, 8 demos does not work

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#5166]
See:
https://bryntum.com/examples/grid/frameworks/angular/angular-6/dist/
https://www.bryntum.com/examples/grid/frameworks/angular/angular-7/dist/angular-7/
https://www.bryntum.com/examples/grid/frameworks/angular/angular-8/dist/angular-8/

**Comment by Splaktar** [comment]
It works for me in Chrome 108.0.5359.124. What browser did you see that in?
