### ISSUE TITLE
`setBaseline` not triggering sync method

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5169]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22226&p=109926#p109926)

Using the [baselines demo](https://www.bryntum.com/examples/gantt/baselines/), replace the following configuration to the project

```
const project = window.project = new ProjectModel({
    transport : {
        load : {
            url : '../_datasets/launch-saas.json'
        },
        sync : {
            url : `http://localhost:3000/sync`
        }
    },
    listeners : {
        beforeSync(ev) {
            console.log('before sync', ev);
        }
    }
});
```
And then set one of the baselines.

Expectation: triggers the sync, as it updates the tasks.

But currently the sync is not being called (as the beforeSync listener)

**Comment by isglass** [comment]
Related to https://github.com/bryntum/support/issues/336
