### ISSUE TITLE
`FilterBar` doesn't work for `startDate`/`endDate` columns when date has `hour`/`minute` provided

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5173]
enable filterBar feature, try to filter data by startDate/endDate

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22235&p=109981#p109981)

Hi,
I have a query regarding column filtering, when filtering 'startdate' and 'enddate' type data. The filtering is not working when the type is set as type:'startdate' or type:'enddate', if type is replaced with type:'date' ,it will not show any data in the column.

I have attached the app.js and json file and the screenshots.

Thanks.
![scrt2.PNG](https://www.bryntum.com/forum/download/file.php?id=18682)
![scrt1.PNG](https://www.bryntum.com/forum/download/file.php?id=18681)

**Comment by matsbryntse** [comment]
Date filtering uses exact time comparison. We need a more relaxed version for date-only comparison.
```

  case a instanceof Date && b instanceof Date:
                    // faster than calling DateHelper.isEqual
                    // https://jsbench.me/3jk2bom2r3/1
                    return a.getTime() === b.getTime();

```
