### ISSUE TITLE
New property name for mapping tree children property

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5177]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=22240&p=110041#p110041)

User suggestion is very similar to something that already exists, as we have 

- [Core.data.AjaxStore#config-responseDataProperty](https://www.bryntum.com/docs/grid/api/Core/data/AjaxStore#config-responseDataProperty)
- Core.data.AjaxStore#config-responseSuccessProperty](https://www.bryntum.com/docs/grid/api/Core/data/AjaxStore#config-responseSuccessProperty) 
- [Core.data.AjaxStore#config-responseTotalProperty](https://www.bryntum.com/docs/grid/api/Core/data/AjaxStore#config-responseTotalProperty)

Following the same idea, we have `children: true` to identify tree nodes, and we could have like

```
childrenProperty: 'hasChildren'
```
To map the property to identify tree nodes.

**Comment by matsbryntse** [comment]
We have https://bryntum.com/docs/grid/api/Core/data/Model#property-childrenField-static
