### ISSUE TITLE
Container with autoUpdateRecord: true not updating record 

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5178]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=22238&p=110017#p110017)

With the following structure

```
class Person extends Model {
   static get fields() {
      return [
         { name: "id", type: "string" },
         { name: "Order", type: "model" },
         { name: "Name", type: "string" }
      ];
   }
}

let myPerson = new Person();
myPerson.Name = "My name";

let myField = new TextField({
    appendTo : document.body,
    width    : 200,
    label    : 'Enter text',
    name : 'Name',
    style    : 'margin-right: .5em'
});

let myButton = new Button({
   text: 'My button',
   onClick: function () 
      {
          Toast.show("Field value: " + myField.value);
          Toast.show("Record value: " + myPerson.Name);
      }
});

let myButton2 = new Button({
   text: 'Clear button',
   onClick: function () 
      {
          myField.clearError();
      }
});

let MyContainer = new Container({
    appendTo : document.body,
    autoUpdateRecord: true,
    items: [myField, myButton, myButton2]
})

 MyContainer.record = myPerson;

myField.setError("My error");

```

Expected behavior: when we change the input value, the record has the Name property updated as well, so when we click the "My button", the toasts have the same value.

Current behavior: the record doesn't get updated as the input changes.

Just as the user mentioned, if you click the "Clear Error" button, and modify the field, the Toast shows both the same (and correct) value.

**Comment by matsbryntse** [comment]
Code is written to update field with a text field is blurred.

**Comment by henriquewerlang** [comment]
I'm not native to English, so I didn't understand the comment that was made. Is there something wrong with my example?

**Comment by matsbryntse** [comment]
Works when removing

`myField.setError('My error');
`

since we don't want to autoUpdate invalid values

**Comment by henriquewerlang** [comment]
Yes, if removing it works. But the problem I have, is for example, the user puts invalid characters in the field, when he tries to save the information, I mark the field with error and put the message. Of course, the user will remove these invalid characters and try to save the information, but because the record is not updated, the validation error remains. Because validation is done in the record, not in the field that is on the screen.

**Comment by henriquewerlang** [comment]
One path I found to resolve is to put in the field change event, to remove the error, but the problem I have multiple fields with would have to replicate this change in various locations of my system, which makes this implementation inviable.

**Comment by matsbryntse** [comment]
Ok thanks for your feedback, we will discuss internally.

**Comment by henriquewerlang** [comment]
Any news about this?

**Comment by matsbryntse** [comment]
Try this way of setting the error:

`setError('fooo', false, true)`


Does that fix it?

**Comment by canonic-epicure** [comment]
@henriquewerlang Hi, so there's a bit of confusion here regarding the semantic of the `setError()` call. By default, it switches the field into the "erroneous" state, which blocks the auto-update to not let the invalid data to sneak in the record.

It is also expected that you will clear the error added with the `setError()` by using `clearError()`. 

You can also use the private 3rd argument for the `setError()` which will make this error "temporary" - in such case, it will be cleared upon the next user action. 

I'll update the docs for `setError()` to make this behavior more clear and also will make the 3rd argument public.

Hope that helps, please let me know if you have any other questions.
