### ISSUE TITLE
Bad UX when typing into date field

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5179]
https://bryntum.com/products/gantt/examples/filterbar/
Trying to type "jan 14, 2019" (same date format as in column)

https://user-images.githubusercontent.com/218570/188269568-5e9c93b4-eb2f-4542-bcd3-ba06704a3c59.mov

**Comment by canonic-epicure** [comment]
Seems no longer reproducible?

https://user-images.githubusercontent.com/72431/209794679-6b0d2a57-0239-4194-9fb1-99ac3459f20d.mp4

**Comment by canonic-epicure** [comment]
The "blocking" label was meant for another ticket
