### ISSUE TITLE
Not possible to set some of constraints to a parent task

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#518]
Click on the items has no effect. The combo picker gets closed and old value stays there.
<img width="1124" alt="Снимок экрана 2020-04-08 в 12 08 15" src="https://user-images.githubusercontent.com/57486733/78766558-13a52e80-7992-11ea-9809-e9b335fce29b.png">

**Comment by pmiklashevich** [comment]
when I click an item I should see a reasonable feedback:

- A popup with error message that this constraint type is not allowed
- Or select it and mark this field as invalid with the corresponding message
- Or just make not allowed items disabled.
- Or remove not allowed items from the options

But simple ignoring the click looks like a bug to me

**Comment by isglass** [comment]
The picker no longer shows those for parents
