### ISSUE TITLE
Group by array or function, allowing record to appear in multiple groups

### ISSUE THREAD

**Issue by isglass** [bryntum/support#5185]
Possible to implement now with linked records. First usage of a record will be the original, others links to it.

**Comment by MuhammetDilmac** [comment]
@SergeyMaltsev how to implement this feature? Can I get any documentation?

**Comment by matsbryntse** [comment]
This is now available in 5.6 alpha-1 released earlier today. Grid has a new demo: https://bryntum.com/products/grid-next/examples/multi-group/

Simply use an array field as your group field and it should work out of the box.
