### ISSUE TITLE
An error occurred when undo baseline date change

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5203]
Use advanced example, enable baselines feature.
In console

```
gantt.taskStore.getAt(4).baselines.getAt(2).endDate = new Date();
```

Click Undo button to revert this change. See the error:
![image](https://user-images.githubusercontent.com/7203098/189297786-a1ef3d70-e8b4-4b61-bbb3-896f8b320607.png)

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/aa0f74fd-7732-46d0-88a7-93a5887b9522
