### ISSUE TITLE
Filter config error when set up callOnFunctions: true

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5215]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=22188&p=110382#p110382)

Using our [filtering demo](https://www.bryntum.com/examples/grid/filtering/)

Replace ```
    filter    : { property : 'city', value : 'Paris' },
``` to ```filter    : { callOnFunctions : true }```, it triggers an error, but it should be possible to have that configuration, as it enables the filter and have the _callOnFunctions_ also working.

**Comment by isglass** [comment]
The Filter feature accepts a filter config object, and filters does not trigger any events so setting `callOnFunctions` would not achieve anything
