### ISSUE TITLE
`eventDragSelect` does not select events when scrolling

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5231]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22337&p=110504#p110504)

Hi there,

when selecting events with eventDragSelect in SchedulerPro, it might happen that a user wants to select events outside of the visible range. Currently, when scrolling while doing the select operation, the new events (that were formerly outside of the viewport), are not being selected. Specifically, the select box always has the same boundaries when scrolling and does not extend.

Would it be possible to change this behavior such that more events can be selected when scrolling?

**Comment by ExtAnimal** [comment]
Fixed by https://github.com/bryntum/bryntum-suite/pull/5740/

Will add drag select tests to it
