### ISSUE TITLE
Frameworks wrappers components not triggering some events

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5233]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=22333&p=110506#p110506)

Using the [Filtering demo](https://bryntum.com/examples/examples-scheduler/frameworks/angular/filtering/dist/filtering)

`bryntum-text-field` Angular component not triggering `(onInput)` event.

When you type something into the text fields, no action is triggered, checking the source code, it looks like the (onInput) event is not being triggered.

Side note: if you change to (onChange), it triggers as expected.

- [x] Check all frameworks to trigger all documented events

**Comment by PatrickHuetter** [comment]
+1
