### ISSUE TITLE
DayViews time axis should be a bit wider when zooming is allowed

### ISSUE THREAD

**Issue by isglass** [bryntum/support#5248]
<img width="437" alt="Screenshot 2022-09-15 at 11 26 25" src="https://user-images.githubusercontent.com/5415653/190368275-1da77e15-72b8-4ada-9af6-885d0339c653.png">

**Comment by ExtAnimal** [comment]
It's just been changed from `4.5em` to `3.5em` in master.

It just needs fixing back to `4.5em`

**Comment by ExtAnimal** [comment]
In fact it[s this code:

```
widestDate          = new Date(2020, 10, 22, 22, 59, 59)
```

That was old code, in `master`, it's now 

```
widestDate          = new Date(2020, 10, 22, 22),
```

So it's not getting the widest possible time to create the width.
