### ISSUE TITLE
Split task outside of task element does nothing

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#5249]
Using any Gantt demo

1. Right-click on a row with a editable task outside of a task element
2. Click Split task.

Also, split task on locked grid results in crash.

**Comment by arcady-zherdev** [comment]
The first one is expected - user is supposed to right click at the point he wants the task to get split.

But throwing exception when calling the entry on the locked part is a bug. The menu entry should not appear when calling from the locked part.
