### ISSUE TITLE
Scheduler booking demo allows to book on non-available dates

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#5255]
Example : Scheduler/examples/booking/

### Steps
* Drag create new booking event
* Edit dates to contain invalid period in dialog
* Save

![Booking](https://user-images.githubusercontent.com/57486330/190379146-9a0f7dd9-b2a7-4fd0-8afc-39deb54785d9.gif)

**Comment by isglass** [comment]
Closed, no changelog on purpose because demo has not been released yet
