### ISSUE TITLE
Saving/reading state for grouped headers not working

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5264]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=22346&p=110556#p110556)

In the example provided (based on one of our demos), we have a nested header configuration, and we save/read the state of the Grid every time the user reorders the columns the state is saved in the user localstorage and when it loads/reloads the page the state gets retrieved from the same source.

It works correctly with non-grouped headers, but if we change the order of some column in a grouped header, even with the correct localstorage update (as it seems to be looking into the console.logs), when the user reloads the headers are not in the right order.

[export-excel.zip](https://github.com/bryntum/support/files/9577954/export-excel.zip)

**Comment by chuckn0rris** [comment]
Dupe https://github.com/bryntum/support/issues/5261
