### ISSUE TITLE
Improve documentation of dateRangeChange event

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5265]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=22344&p=110546#p110546)

Using the [List view demo](https://www.bryntum.com/examples/calendar/listview/)

Adding the **daterangechange** listener like this

```
    listeners : {
        daterangechange : (ev) => {
            console.log('ev', ev);
        }
    }
```

Is expected according to the [dateRangeChange documentation](https://www.bryntum.com/docs/calendar/api/Calendar/view/Calendar#event-dateRangeChange)

> Fired when the range of dates required to produce the UI changes. This will be when moving to a **_different view_**, or moving a view in time.

So, the first time, you access some of the available views, the event is triggered, but after that, when you re-enter a view, the method is not triggered.

**Comment by ExtAnimal** [comment]
If you have a month's range in the store, and you go to week, the store does *not* need to request more info. It does not cause the store to request a new date range.
