### ISSUE TITLE
Feature flag for remove/hide red border when shift key is used

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5271]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=22351&p=110643#p110643)

Currently, we have the current CSS class set for outline when the user selects an event with the keyboard:

`body.b-using-keyboard .b-grid-cell:focus, body.b-using-keyboard .b-grid-cell:focus-within`

User asked to have a feature flag to disable/remove that red (dark theme)/blue (light theme) outline. 

![image](https://user-images.githubusercontent.com/16693227/190718241-6a6c1ec6-fd9b-4841-ba6f-9cd42668ab96.png)

**Comment by jeffallen6767** [comment]
Would be nice to be able to set a feature flag:
Scheduler.features.enableKeyboardCssModifiers: true/false

Which could enable/disable the 'b-using-keyboard' css class from being added to the body - this could enable/disable all 176 css modifications tied to this css class feature.

The actual modification I had to make to the *.css file to disable the red border on 'shift' key usage was:
/* JDA-2022-09-16: remove the red outline around last item selected when 'shift' key is used...
.b-using-keyboard .b-sch-event-wrap:not(.b-milestone-wrap).b-active .b-sch-event {
  outline: 2px solid #e64a19;
  outline-offset: 3px;
}
*/

**Comment by matsbryntse** [comment]
Adding `DomHelper.enableKeyboardCssModifiers` to control this behavior
