### ISSUE TITLE
Add support for grouping multiple fields

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5289]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22404&p=110825#p110825)

HI Team,
I want to set grouping for more than one column, 
for example like this:

```
groupFeature={[{field: 'taskType'}, {field:'region'}]}

```
How can we set more then one column on grouping adding expected design for reference.
![Screenshot 2022-09-21 at 4.18.48 PM.png](https://www.bryntum.com/forum/download/file.php?id=18859)

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/3227
