### ISSUE TITLE
Export feature settings A6 landscape gives odd blank pages

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#5297]
1. Use Grid Basic example.
2. Settings from picture: 
![image](https://user-images.githubusercontent.com/100013589/191697491-32d4564e-cadc-4150-8713-d81d477ebd01.png)
3. Results in odd blank pages:
![image](https://user-images.githubusercontent.com/100013589/191697610-4fd5b09c-e72b-49a1-a430-d5d76f71a0dd.png)

**Comment by bmblb** [comment]
Clients sends correct number of pages, but page height is a little bit too high for puppeteer
