### ISSUE TITLE
Export feature generated PDF splits row in page break

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#5298]
1. Use Grid Basic example.
2. Use these settings:
![image](https://user-images.githubusercontent.com/100013589/191699461-eae172fa-bd83-45ae-b115-3d292cd8c401.png)
3. Will result in splitted row
![image](https://user-images.githubusercontent.com/100013589/191699575-931019b2-21f3-4ab0-b2b5-f4c5dfc37038.png)

**Comment by bmblb** [comment]
This is expected behavior. Align rows config is meant to align first on the page with the page top.
