### ISSUE TITLE
Cell editing is broken when a column uses a field that is missing in the model

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#53]
Forum: https://www.bryntum.com/forum/viewtopic.php?f=51&t=12767&p=66840#p66840

autoExposeFields should work in Gantt, ticket here: https://github.com/bryntum/support/issues/54
But in case the first record doesn't have all fields, some of definitions still might be missing.

To reproduce:
Gantt/examples/basic/app.js
```
    columns : [
        { text : 'status', field : 'status', width : 250 },
```
Go to browser.
Double click a status cell.
Type in a new value.
Press enter.
See value is missing.
Double click the cell again.
See the value is there.
Remove focus from the cell.
Value is missing again.

All fields have to be defined. Add a warning if a column uses a field that is missing in the model.

**Comment by isglass** [comment]
As long as “status” is defined in the data for the first loaded record this should work out of the box, we define fields from that on the fly unless configured not to.

I see this is something Gantt specific, ChronoModelMixin breaks this behaviour. Adding a warning for when Model.autoExposeFields is false and field is not defined is fine, but this scenario should work anyway. Needs fixing in ChronoModelMixin or docs changes for gantt that state that it does not work the same way as the other products.

Also need to make sure that the autoAddField setting on the ColumnStore works in Gantt.

**Comment by ExtAnimal** [comment]
The fix is feature/CellEdit line 479 should be ```record.set(dataField, value)```

**Comment by pmiklashevich** [comment]
ONLY THIS PR IS RELEVANT TO GET THIS ISSUE FIXED: https://github.com/bryntum/bryntum-suite/pull/418

**Comment by pmiklashevich** [comment]
EDITING IS NOT SUPPOSED TO WORK WHEN FIELD IS NOT DEFINED
