### ISSUE TITLE
Multi-level sort with custom sorting fn not working

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5325]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=22458&p=111070#p111070)

Using the [Grid sorting demo](https://www.bryntum.com/examples/grid/sorting/)

1) Sort by Rank ascending.
2) Add the Age column as the 2nd sort by Ctrl/Cmd + Clicking it. You can see that no matter the sort direction on Age, the 2nd sort level is never applied, even though there are multiple instances of "Rank" that are the same, which would logically allow a 2nd sort to change the order of the displayed records.

https://user-images.githubusercontent.com/16693227/192372672-784350be-3325-4056-800c-20acab8fa998.mp4

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?f=43&t=24182&p=119757#p119757
