### ISSUE TITLE
Not able to scroll the content in task editor

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5339]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=44&t=22488&p=111257#p111257)

You can reproduce it here https://bryntum.com/examples/scheduler-pro/constraints/
1. Just open a task editor 
2. and add a lot of resources
3. and if you try to scroll to the bottom to see the content then, you can't scroll.
![chrome_8FfOO2Dzav](https://user-images.githubusercontent.com/75997756/193241580-97f51605-734f-4a26-9c54-0c38cbf6b17a.gif)

**Comment by ghulamghousdev** [comment]
Fixed by this ticket https://github.com/bryntum/support/issues/7683
