### ISSUE TITLE
Dependency line jumps while scrolling vertically

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#534]
Forum: https://www.bryntum.com/forum/viewtopic.php?f=52&t=13728

Looks bad especially on multi-page pdf export.

![Запись активности на экране 2020-04-10 в 16 47 56](https://user-images.githubusercontent.com/57486733/78995755-c2d93580-7b4b-11ea-8007-01c7df3aad6f.gif)

Gantt/examples/basic/app.js
```
new Gantt({
    adopt : 'container',

    startDate  : new Date(2019, 4, 1),
    endDate    : new Date(2019, 10, 1),
    viewPreset : 'monthAndYear',
....
```
Gantt/examples/_datasets/launch-saas.json replace with 
[launch-saas.json.zip](https://github.com/bryntum/support/files/4461845/launch-saas.json.zip)

Go to http://lh/bryntum-suite/gantt/examples/basic/
Scroll  to task `gantt.scrollTaskIntoView('ZTGAvs7jO', { block : 'start', highlight : true })`
Scroll a bit down, see one of dependency lines changes its position.
<img width="1033" alt="Снимок экрана 2020-04-10 в 17 06 11" src="https://user-images.githubusercontent.com/57486733/78996619-a4743980-7b4d-11ea-8736-42fd8b3f1358.png">
<img width="1038" alt="Снимок экрана 2020-04-10 в 17 06 25" src="https://user-images.githubusercontent.com/57486733/78996629-a9d18400-7b4d-11ea-9bdb-a6c6ef899cc8.png">

**Comment by isglass** [comment]
Check if repos on master, rendering has changed
