### ISSUE TITLE
Overlapping milestones in Timeline widget

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5351]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=22473&p=111252#p111252)

[one more](https://forum.bryntum.com/viewtopic.php?f=52&t=23033&p=113873#p113873)

1. open timeline demo, change some task with duration=0. See that the task has not being shown in diamond style.
2. Open Gantt timeline demo, we have milestones there by default. Click on milestone, try to hover mouse - see style is broken. 
video:

https://user-images.githubusercontent.com/7203098/193549529-3cf29926-e675-46bd-af74-cb9ae95a091c.mov

3. Gantt timeline demo. Select more milestones to be displayed in timeline. See wrong alignment.
video:

https://user-images.githubusercontent.com/7203098/193549887-63f25439-3d7b-4aa7-a3ee-175a967104a9.mov

4. Multiple assignments are not showing correctly on the graph

https://github.com/bryntum/support/assets/52177956/faa47f06-90cb-422a-a169-6642259ab957

**Comment by anubrij** [comment]
any update on this bug, is it fixed in any version ?
