### ISSUE TITLE
`TimeRange` header element styling bug

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5362]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22550&p=111443#p111443)

Open https://bryntum.com/examples/gantt/timeranges/
Click Hide headers button
See that CSS is wrong

<img width="263" alt="Screenshot 2022-10-05 at 19 14 43" src="https://user-images.githubusercontent.com/7203098/194110060-233cbffb-d138-435b-9b39-b5df34a24551.png">

**Comment by Steven-J-Alves** [comment]
I used this aproach!
`
.b-grid-header .b-sch-timerange {
  z-index: -1;
}
`
