### ISSUE TITLE
Unable to find task `id` with the id got from changes in `dataChange` event

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5371]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=51&t=22556&p=111486#p111486)

Here is how you can reproduce it:
1. Go to the basic example https://bryntum.com/examples/gantt/basic
2. Use this code 
```
    listeners : {
        dataChange(args) {
            console.log("OnDataChanged fired: ", args.project.changes);

            if (args.project.changes) {
                args.project.changes.tasks.updated.forEach((task) => {
                    const taskRecord = args.project.tasks.find((currentTask) => currentTask.id === task.id);
                    // console.log(taskRecord);

                    if (!taskRecord) { // BUG: Why is this null when dragging and dropping a task for the second time?
                        throw new Error("Unexpected error occurred - unable to find task record with ID '" + task.id + "'");
                    }
                });
            }
        }
    }
```
3. Here is a gif how to reproduce it
![chrome_JSwJ9HiF93](https://user-images.githubusercontent.com/75997756/194290584-ebb16209-16e6-4d5f-a868-86d5de0a18fc.gif)

**Comment by FlowIT-JIT** [comment]
@taauntik Do you know why this hasn't been fixed yet? This is a critical bug in the data foundation. I would expect critical bugs like this to be fixed within days. I'm curious to know how you guys categorize and prioritize bugs.

The example code no longer works when injected on the demo page.  The event is suddenly fired during initialization with calendar changes.

Here is a modified working example which proves the bug has not been resolved yet:

```
  listeners : {
        dataChange(args) {
            console.log("OnDataChanged fired: ", args.project.changes);

            if (args.project.changes && args.project.changes.tasks) {
                args.project.changes.tasks.updated.forEach((task) => {
                    const taskRecord = args.project.tasks.find((currentTask) => currentTask.id === task.id);
                    // console.log(taskRecord);

                    if (!taskRecord) { // BUG: Why is this null when dragging and dropping a task for the second time?
                        throw new Error("Unexpected error occurred - unable to find task record with ID '" + task.id + "'");
                    }
                }) ;
            }
        }
    }
```

**Comment by matsbryntse** [comment]
We'll take a look at this right away, sorry for the wait!

**Comment by matsbryntse** [comment]
Fix in place, enabled with a flag (see change log in next patch release)

**Comment by FlowIT-JIT** [comment]
Thank you so much, @matsbryntse .
How come the fix needs to be enabled with a flag? Is this something temporarily until the fix has proven stable, or are there actual cases where you want data to "disappear" from the task store?

**Comment by matsbryntse** [comment]
Our user base could potentially be expecting 'remove' to be called, and we don't want to break anyones app.  In 6.0, this is the new default behavior.

**Comment by FlowIT-JIT** [comment]
@matsbryntse Great, thanks 😊
Also, would you mind taking a look at #6033? The title makes it appear as a rant, but it is actually a bug report, and we have _major_ concerns going forward with our Gantt project. We are experiencing way too many problems with the React wrapper. Even with basic things. Thanks again.

**Comment by matsbryntse** [comment]
Sure we'll take a look right away!

**Comment by FlowIT-JIT** [comment]
@matsbryntse Thank you so much! 😊
