### ISSUE TITLE
Allow EventDrag to be configured with resolutionUnit and resolutionIncrement

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#5375]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22568)

Hello,

I would like to know if it is possible to avoid defining a time resolution in the view preset and avoid that events "snap" to the closest time resolution tick when dropping them.

Or does the only possible option consist in using a tiny time resolution, such as 1 second or less?

Thanks!

**Comment by isglass** [comment]
Was not what the user was looking for according to forum reply
