### ISSUE TITLE
Resource gets hidden on event creation in first parent resource

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5378]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22572&p=111564#p111564)

Hi guys,

We have an issue with resource getting hidden after particular set of actions is made.
You can reproduce this through your official example on the link bellow:
https://bryntum.com/examples/scheduler/bigdataset-tree/

Steps to reproduce it:
      - Open this example
      - Try to create event on first parent resource on 1k ( Moscow ) and then cancel creation
      - Click to load 5k events example
      - Try to create event on first parent resource on 5k ( Paris ) and then cancel creation
      - Parent resource is hidden after this actions

video:

https://user-images.githubusercontent.com/75997756/194533216-a68c2de6-9868-467d-80f5-beb9f835d8a1.mp4

**Comment by grale88** [comment]
Hi,

I have the same issue in my application with the tree view. Is there any kind of workaround, as it is blocking me to deliver the feature to the customer? Thanks for the feedback.

**Comment by isglass** [comment]
Test comment

**Comment by grale88** [comment]
Any updates on the issue status?

**Comment by matsbryntse** [comment]
We're still looking into this one!
