### ISSUE TITLE
Have both a resizable and locked region within the Bryntum Grid

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5381]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22565&p=111576#p111576)

"From what I can tell theres no public solution to have a 3 region grid with both a locked and resizable region at the same time. The regionResize feature of the Bryntum Grid enables the resize of all regions on the grid; in our case we would like the ability of the left region to be resizable and the right region locked."

The following screenshot is an example representation of the desired behavior.

![Screen Shot 2022-10-06 at 16 26 49](https://user-images.githubusercontent.com/16693227/194598720-732e4dd4-fa23-4ba4-a874-94e7e6ef3bf3.png)

Currently, we can achieve similar behavior with a **fixed** prop column, but the region is allowed to overflow the fixed column, which is not the desired behavior as the user suggested.

**Comment by matsbryntse** [comment]
SubGrid has this supported already, just not public:
```

    /**
             * Set to `false` to prevent this subgrid being resized with the {@link Grid.feature.RegionResize} feature
             * @internal
             * @config {Boolean}
             * @default true
             */
            resizable : null,
```

**Comment by matsbryntse** [comment]
Will be public in the next patch release.
