### ISSUE TITLE
Non working hours is not allocated for specially defined working hours

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5396]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22595&p=111696#p111696)

Hi,

Please open the demo site "https://producttraining.cipplanner.net//gantt/examples/resourceutilization_pfm/", which is based on the official demo "https://bryntum.com/examples/gantt/resourceutilization/" modified 01/15/2022 to be a working day.

In this demo, Dave and Rob was assigned a three-day task that began on 01/14/2022.

In the resource utilization view, you can see that Dave and Rob are assigned working hours on 01/14/2022 and 01/18/2022. 
The 01/15/2022, which has been modified as a weekday, has no working hours assigned to it, why?

![1.png](https://www.bryntum.com/forum/download/file.php?id=19111)
![2.png](https://www.bryntum.com/forum/download/file.php?id=19110)

Use this JSON file to reproduce

[launch-saas-overallocated.txt](https://github.com/bryntum/support/files/9756159/launch-saas-overallocated.txt)

**Comment by arcady-zherdev** [comment]
Assigned resource calendar do not allow working on weekends that's why the allocation for those days is not shown. The task does not perform on those days.
