### ISSUE TITLE
Auto exposing fields is broken

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#54]
Model.autoExposeFields should define fields automatically based on data in the first loaded record. ChronoModelMixin breaks this behaviour in Gantt.

To reproduce:
Gantt/examples/basic/app.js
```
    columns : [
        { text : 'status', field : 'status', width : 250 },
```
Gantt/examples/_datasets/launch-saas.json
```
    "tasks" : {
        "rows" : [
            {
                "id": 1000,
                "name": "Launch SaaS Product",
                "status": "test",
```
Go to the browser, see "test" in the first cell.
Run in console:
```
gantt.taskStore.modelClass.getFieldDefinition('status')
// undefined
```
Adding the code below to Gantt/examples/basic/app.js creates the definition:
```
import TaskModel from '../../lib/Gantt/model/TaskModel.js';
class MyTaskModel extends TaskModel {
    static get fields() {
        return [
            { name : 'status', type : 'text' }
        ];
    }
}
const project = new ProjectModel({
    taskModelClass : MyTaskModel,
```
Run in console:
```
gantt.taskStore.modelClass.getFieldDefinition('status')
// {name: "status", type: "text", dataSource: "status", persist: true}
```

It causes issues with cell editing. See here: https://github.com/bryntum/support/issues/53

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/407
