### ISSUE TITLE
Text overflows editor after opening cell editor

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5402]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22608&p=111766#p111766)

Hi,

We have found an issue with the text editor and combo editor when using them as a column editor.

This is reproducible in the Cell Edit demo.
Open the editor for the Name column on any row
Enter a name that is really long and overflows the width of the column
Close the editor and reopen it
The text will go outside the boundary of the editor and overflow into the next column

The expect behaviour is that the text will be truncated/cut off. See the attached screenshot.

Thanks.
![Screenshot 2022-10-12 at 14.51.59.png](https://www.bryntum.com/forum/download/file.php?id=19132)

**Comment by ExtAnimal** [comment]
celledit.scss, `.b-gridbase .b-editing` needs `clip-path: inset(0 0 -100em 0);` to clip the cell's right side, but allow the bottom to overflow.
