### ISSUE TITLE
`ResourceHistogram` view fails when `eventStore` config is passed

### ISSUE THREAD

**Issue by simonihmig** [bryntum/support#5406]
After upgrading from `@bryntum/schedulerpro` 5.0.x to 5.2.0 we are seeing `ResourceHistogram` views start to throw this error: `TypeError: Cannot set property eventStore of #<ResourceHistogram> which has only a getter`.

This happens when passing `eventStore` in its config. I does not happen with a scheduler view, and also apparently not with other stores configs like `resourceStore`.

Here is a reproduction: https://codepen.io/simonihmig/pen/qBYgVBN

This is the basic example from https://www.bryntum.com/docs/scheduler-pro/api/SchedulerPro/view/ResourceHistogram, where I only added `eventStore: {}` to the config to get a minimal reproduction.

**Comment by isglass** [comment]
Inheritance playing a trick on us here, we have not considered using ResourceHistogram any other way than by configuring it with a project. But will try and unbreak this

**Comment by isglass** [comment]
Glad to hear that, and I agree with @matsbryntse, that would be the recommended approach. But the fix is merged already, so your old way should also work after next patch release 🙂
