### ISSUE TITLE
CrudManager wrong params handling

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#541]
Forum: https://www.bryntum.com/forum/viewtopic.php?p=85029#p85029

We can configure CM with params:
```
transport : {
    load : {
        url    : '../_datasets/launch-saas.json',
        params : {
            foo : 'bar'
        }
    }
}
```
In this case, params go to the query string what is correct. 

However, when we configure CrudManager as follows:
```
autoSync : true,
transport : {    
    load : {
        url    : '../_datasets/launch-saas.json',
        params : {
            foo : 'bar'
        }
    },
    sync : {
        url    : 'success.json',
        method : 'POST',
        params : {
            hello : 'world'
        }
    }
}
```
params of sync action still go to URL query string despite the method is POST. We do send POST method payload but the user's params are not included therein:

<img width="1025" alt="Screen Shot 2020-04-14 at 11 23 55" src="https://user-images.githubusercontent.com/204844/79208691-ae928280-7e42-11ea-9aa9-5e3aa7a1a305.png">

The only way how to include user params in POST payload is:
```
sync : {
    url           : 'success.json',
    method        : 'POST',
    requestConfig : {
        fetchOptions : {
            body : JSON.stringify({
                hello : 'world'
            })
        }
    }
}
```

in which case the whole previously sent payload is replaced with user params:
<img width="788" alt="Screen Shot 2020-04-14 at 11 29 10" src="https://user-images.githubusercontent.com/204844/79209175-590aa580-7e43-11ea-960b-458bbe49f355.png">

Recommendation: user params should be merged into the default payload if the method is other than GET.

**Comment by pmiklashevich** [comment]
Workaround is to modify PACK inside beforeLoad/beforeSync events.
```
new Scheduler({
    crudManager : {
        listeners : {
            beforeLoad({ pack }) {
                Object.assign(pack, {
                    foo: 1
                });
            }
        },
        transport : {
            load : {
                url: 'php/read.php',
                method: 'POST'
            },
            sync : {
                url : 'php/sync.php'
            }
        },

    autoLoad      : true,
    autoSync      : true,
```

**Comment by arcady-zherdev** [comment]
The issue actually describes two parallel things:

1. The ability to put some values into Crud Manager package, like:
```
{
    "parameters" : {
        "foo"   : "Bar!!!",
        "smth"  : 123
    },

    "events" : ...
}
```
This has nothing to do w/ sending requests actually. It should be done on the package encoding stage.

2. Ability to put POST request parameters to the request body. Parameters sending in a POST request depends on the request `Content-Type`. Should look like this for example for `application/x-www-form-urlencoded` content type:
```
foo=Bar!!!&smth=123&q=%7B%22events%22%3A%7B...
```

**Comment by arcady-zherdev** [comment]
For 2nd subject I suggest making a separate feature request.

Regarding 1st one I would represent a new config:
```js
new CrudManager({
    encoder : {
        requestData : {
            qweqwe : {
                "foo"   : "Bar!!!",
                "smth"  : 123
            }
        }
    },
    transport : {
        ...
    }
})
```
Encoder would have its own section as transport does. And `requestData` would be merged w/ request data before it gets serialized by the encoder. 

The the above snippet would result having a request package like this:
```
{
    "qweqwe" : {
        "foo"   : "Bar!!!",
        "smth"  : 123
    },

    "events" : {
        ...
