### ISSUE TITLE
Should be possible to toggle constrainDragToResource dynamically

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#542]
`                scheduler.on('beforeEventDrag', () => scheduler.features.eventDrag.constrainDragToResource = true);
`

**Comment by sylvainmouret** [comment]
Hello,
Does this dynamic toggling also applies to the event for which the drag is about to start?
I did an experiment that seems to indicate that the event which is about to be dragged is not impacted by the new value of constrainDragToResource.
Thanks
