### ISSUE TITLE
Scheduler "Custom event styling" demo has wrong styles

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#5422]
https://www.bryntum.com/examples/scheduler/customeventstyling/

* Milestones labels overflow events
* Hovering event shows unexpected elements over it 

<img width="826" alt="image" src="https://user-images.githubusercontent.com/57486330/196336714-2e79f7a9-8dda-4f75-b66d-7ec12a07cdd3.png">

**Comment by isglass** [comment]
Fixed on master already IIRC, pull the changes to the demo over
