### ISSUE TITLE
Error after call `loadInlineData` with resource tree structure

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5435]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22662&p=112075#p112075)

Test case attached.
To run:
```
yarn install
yarn start
```

In app:
1. Click "Toggle grouping mode" button.
2. Try to resize a task with drag-n-drop

Error:
```
Uncaught (in promise) TypeError: field is undefined
    applyValue schedulerpro.module.js:187337
    inSet schedulerpro.module.js:45028
    set schedulerpro.module.js:44887
    node_modules 0.chunk.js:53011
    preWalkWithParent schedulerpro.module.js:50672
    syncTreeDataset schedulerpro.module.js:51143
    syncDataset schedulerpro.module.js:50945
    setStoreData schedulerpro.module.js:52798
    setStoreData schedulerpro.module.js:124503
    setStoreData schedulerpro.module.js:188164
    set data schedulerpro.module.js:52725
    loadInlineData schedulerpro.module.js:190801
    loadInlineData schedulerpro.module.js:141712
    App App.js:94
    App App.js:100
```

Background:
Application has `tree: true` configuration for `resourceStore`.
First loaded data is flat. After you clicked button in step 1, resourceStore will replace data on tree structured.
`field` that is undefined in the error, should be an instance for `parentId` field. 
If you open "schedulerpro/examples-scheduler/bigdataset-tree/" example and check 
```
scheduler.resourceStore.modelClass.allFields
```
You will see that `parentId` is missing there as well. Looks like the problem in field exposing. 

[bryntum-schedulerpro-issues-issues-grouped-resources.zip](https://github.com/bryntum/support/files/9819320/bryntum-schedulerpro-issues-issues-grouped-resources.zip)

**Comment by canonic-epicure** [comment]
PR: https://github.com/bryntum/bryntum-suite/pull/6011
