### ISSUE TITLE
Browser freezing when updating task start date

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5438]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22685&p=112139#p112139)

"Hello Support,

As shown in attached video while trying to change dates its hanging the browser.

Its very critical to us,please share how to correct this browser hang problem 

Thanks"

How to reproduce the issue (in [Advanced demo](https://www.bryntum.com/examples/gantt/advanced/))

- Double click into Start date field of "Configure Firewall"
- Type a date like 10/14/2022 (it'll already freeze for a while)
- After that, make the same thing for the next task "Setup load balancer", the page will freeze.

https://user-images.githubusercontent.com/16693227/196785517-dcdeb194-c59e-4ac2-9691-0264f9254db8.mp4

**Comment by matsbryntse** [comment]
Dupe #4417  ?

**Comment by marciogurka** [comment]
Yes @matsbryntse, you're correct, it's a duplicate from #4417. Closing this one and adding a note there.
