### ISSUE TITLE
Error when compiling TS Scheduler with filterType: string config

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5444]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=22692&p=112178#p112178)

In the Scheduler TS Filtering example, add a filterType config like this 

```
const schedulerConfig: BryntumSchedulerProps = {
    eventStyle        : 'colored',
    resourceImagePath : 'users/',
    columns           : [
        {
            type  : 'resourceInfo',
            text  : 'Staff',
            width : 170,
            filterType: 'string'
        },
```

And when executing the application, you'll see a compile error

`Uncaught Error: Invalid type name "stringfield" passed to Widget factory`

![invalid_stringfield.PNG](https://www.bryntum.com/forum/download/file.php?id=19209&sid=654c7fb0a631c5e706feaf58e0e94e5a)

**Comment by matsbryntse** [comment]
should say 'text', docs typo
