### ISSUE TITLE
Grid with pagination and sorting not changing the records when navigating

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5445]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=43&t=22694&p=112184#p112184)

When we apply sorting for example column "Name", and try to go to the next page, the records not refresh (changed)

for example use [Grid paged demo]( https://bryntum.com/examples/grid/paged/)

**Comment by ExtAnimal** [comment]
@marciogurka I think this was fixed by another ticket.

**Comment by chuckn0rris** [comment]
Dupe https://github.com/bryntum/support/issues/5403
