### ISSUE TITLE
startTransaction and stopTransaction raise exception

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5453]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=22700&p=112232#p112232)

Hi,

following code raises an exception.

```
gantt.project.stm.startTransaction("Outdent Task");
await gantt.taskStore.outdent(gantt.selectedRecords);
gantt.project.stm.stopTransaction("Outdent Task");

```
![sdfa](https://user-images.githubusercontent.com/75997756/197187810-5e6087f8-96f9-4b07-a604-cd242f1c5837.png)

Same with indent.

BR, Walter

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=118244#p118244) user asking for this.

**Comment by isglass** [comment]
`gantt.outdent()` calls `project.tryPropagateWithChanges()` internally, which in turn stops any ongoing transaction and then starts & stops its own. Thus making the snippet above crash, since the transaction was stopped already.

Needs engine team on it, will ask @canonic-epicure  and/or @arcady-zherdev to check it

**Comment by isglass** [comment]
Removed `high-priority` since it does not seem crucial for users app

**Comment by canonic-epicure** [comment]
Closing as "Wont fix". As discussed, the indent/outdent/row move operations are complex ones, and they possibly require a rollback (if a dependencies structure after the indent becomes cyclic), that is why it starts/stops the internal STM transaction. It should be always possible to just run such operation alone, w/o combining it with another actions. If not, such use case should be demonstrated.
