### ISSUE TITLE
LTS date format does not parse seconds

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#5455]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=22704)

Hi, last time I asked for help in this forum, the support did a really great job, so we decided to use Bryntum Calendar for our product. Hopefully, this time, you can also help me out.

In the calendar view configs I was able to set the increment property to '1 seconds', so that the user can now drag and drop events to the second. The start and end dates of events can also be dragged to the second now. On the other side, I tried to also support this feature in the eventEdit timeField, but it doesn't work out. I managed to set the timeFormat of the start and end timeFields to 'LTS'. So, seconds are also shown within the timeField, but the timePicker still only shows hours and minutes. Editing the seconds within the timeFields, when editable is set to true, is also not possible -- it always sets seconds to '00'. Did I miss something? When it's possible to edit events start- and enddates to the second by dragging, it should also be possible to do so within the eventEdit timeField right?

Here is the corresponding code I used:

```
 eventEdit: {
                    dateFormat: 'YYYY-MM-DD',
                    timeFormat: 'LTS',
                    items: {
                        startTimeField: {
                            editable: true,
                            step: '5m'
                        },
                        endTimeField: {
                            editable: true,
                            step: '5m'
                        }
                    },
                }

```

I'm looking forward to your feedback!
![Bildschirmfoto 2022-10-21 um 18.02.01.png](https://www.bryntum.com/forum/download/file.php?id=19226)

**Comment by matsbryntse** [comment]
test

**Comment by matsbryntse** [comment]
test
