### ISSUE TITLE
Remove Full button

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5459]
Make it opt-in
Change label to "Show weekends"

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=22716&p=112310#p112310)

Want to disable or hide new FULL button that appear in weekview, monthview,..
![Captura desde 2022-10-24 14-17-39.png](https://www.bryntum.com/forum/download/file.php?id=19240)

**Comment by dongryphon** [comment]
Can we use this localized text for the button?
```javascript
    ModeSelector : {
        includeWeekends : 'Include weekends'
    },
```
It is currently used for the popup menu:
![image](https://user-images.githubusercontent.com/722969/197533397-980bcbb6-ff3f-445b-b4eb-9cab564bdd6d.png)
