### ISSUE TITLE
Wrong endDate when dragging events over days at which DST/STD change

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5474]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20335&start=10)

Open inline-data example for SchedulerPro
apply these changes
```
        startDate        : new Date(2022, 2, 20),
        endDate          : new Date(2022, 2, 30),
        viewPreset       : 'weekAndDay',
```

Create 1 day event and try to drag and drop it to start at 12am March 27
See that duration now 25 hours instead of 24 hours.
Video:

https://user-images.githubusercontent.com/7203098/197833988-1787af8a-cc5f-468d-b628-3453d0974798.mov

**Comment by canonic-epicure** [comment]
To activate the fix, one need to enable the `adjustDurationToDST` config object of the ProjectModel: https://bryntum.com/products/gantt/docs/api/Gantt/model/ProjectModel#config-adjustDurationToDST

Originally we had this fix always enabled. Then it was decided, that it should be off by default. But still, if user need the fix, the option is available.

**Comment by schTi** [comment]
@canonic-epicure I checked this for SchedulerPro, and it works correctly. Unfortunately, it was not added to the types of the SchedulerPro, can you please add it? (Setting `adjustDurationToDST` on the ProjectModel works, but it's saying that the option does not exist on the type)

**Comment by canonic-epicure** [comment]
@schTi Glad to hear it works. Ok, I'll update the types as well.
