### ISSUE TITLE
Bryntum Gantt with zoom less than 100% on Firefox not rendering correctly

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5475]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=1&t=22151&p=112402#p112402)

Similar to https://github.com/bryntum/support/issues/4570

but with Gantt, check [https://bryntum.com/examples/gantt/frameworks/angular/advanced/dist/advanced/](https://bryntum.com/examples/gantt/frameworks/angular/advanced/dist/advanced/) with zoom level less than 100%.

![Screen Shot 2022-10-25 at 14 15 08](https://user-images.githubusercontent.com/16693227/197839482-e7026812-d0b0-4187-bbe0-16fd9cb4aeaa.png)

**Comment by ExtAnimal** [comment]
`GridBase.measureRowHeight` needs

```
 multiplier     = BrowserHelper.isFirefox ? devicePixelRatio / Math.max(Math.trunc(devicePixelRatio), 1) : 1
```
