### ISSUE TITLE
Canceling task creation with conflict popup crashes Gantt chart

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5477]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22736&p=112416#p112416)

Hi Bryntum support,

This is a bug report.
When I cancel task creation with conflict popup, Gantt chart crashes.

[How to reproduce1]

open https://bryntum.com/examples/gantt/advanced/
collapse the "Launch SaaS Product"
execute the code below.
Click cancel on the conflict popup.
error 1 : 
![Screenshot 2022-10-26 17:36:48](https://user-images.githubusercontent.com/75997756/198016690-0388762a-d71b-495b-a597-9219dc6d7187.png)
```
gantt.project.taskStore.rootNode.appendChild([{
    name: 'b',
    startDate: "2019-01-22",
    constraintDate: '2019-01-06',
    constraintType: 'muststarton',
    duration: 1,
}]);

```
error 2 :

![Screenshot 2022-10-26 17:39:55](https://user-images.githubusercontent.com/75997756/198016977-817199a9-3e40-4626-8dd4-0dde79027e73.png)

[How to reproduce2]
open https://bryntum.com/examples/gantt/advanced/
execute the code below.
Click cancel on the conflict popup.

```
gantt.project.taskStore.rootNode.appendChild([{
    name: 'b',
    startDate: "2019-01-22",
    constraintDate: '2019-01-06',
    constraintType: 'muststarton',
    duration: 1,
}]); gantt.project.resourceStore.add({
    name: 'c',
});

```

I'm facing this bug when I'm developing that importing MPP file into the existing Gantt chart.
I hope it will be fixed.

Regards,
Takafumi

**Comment by matsbryntse** [comment]
@ Takafumi  I cannot repro 1st issue anymore can you?
