### ISSUE TITLE
`dayNumberClick` and `monthNameClick` events are not firing for specific modes

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#5528]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=22860)

Hello,

According to the documentation the events 'dayNumberClick' and 'monthNameClick' should be fired on all respective views where the day number or month name is visible,  however I am experiencing the issue that the events are not fired on some views (modes).

Docs: 
Calendar.view.Calendar#event-dayNumberClick
Calendar.view.Calendar#event-monthNameClick

Example:
'dayNumberClick' does not fire when clicked on day number when the current mode is 'week' or 'month'. 
'monthNameClick' does not fire when clicked on month name while current mode is 'year'.

I have created a dummy app as example here:
https://github.com/jgavric/bryntum-calendar-events-repro/blob/master/src/app/app.component.ts

Please let me know if you need any additional information.

Thanks,

**Comment by jgavric** [comment]
@ExtAnimal Thanks for the fast response.
One more note (maybe it should be a separate topic but its kinda related):
When the current mode is 'year',  the navigation via day number is executed only on double click, in contrast to the week and month view where its navigated on single click.  Therefore it would be really good if there is 'dayNumber**Dbl**Click' event.

**Comment by ExtAnimal** [comment]
That is by design. A year cell offers to show an overflow popup, and they show on single click.

Maybe if there's no overflow popup to shoe because there are no events on that day, it should navigate on single click.
