### ISSUE TITLE
When applying remote changeset store should apply current filters/sorters to affected records

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#5534]
Consider gantt advanced demo with this data and filter for the task store:
```
const tasksData = [
    { id : 1, name : 'Task 1', visible : true },
    { id : 2, name : 'Task 2', visible : true },
    { id : 3, name : 'Task 3', visible : false }
];

gantt.taskStore.filter(r => r.visible);
```

In the view only task 1 and task 2 should be visible.

Now, if user clicks `add new task` and starts editing it, we do not want that new task to get filtered out (this is why `reapplyFilterOnAdd` is false by default, it is expected behavior)

However, for a case when we call `project.applyProjectChanges` we do want new records to get filtered out if they do not match current filter. E.g.

```
gantt.project.applyProjectChanges({
    tasks : {
        added : [
            { id : 100, name : 'Remote task 100', visible : true },
            { id : 101, name : 'Remote task 101', visible : false }
        ],
        updated : [
            { id : 1, visible : false },
            { id : 3, visible : true }
        ],
        removed : [
            { id : 2 }
        ]
    }
});

```

Current implementation will not filter out new records, it will display them, so view will look like:
```
Task 1 (even though it is hidden by the remote client, we still want to see it locally)
Task 3 (this task was made visible by the remote client, and we should bring it up to the view)
New task (this is the one we have added locally)
Remote task 100 (remote task matches filter it should be visible)
```
Task 2 was removed. Remote task 101 does not match the filter and should be filtered out.

To summarize, rules for `project.applyProjectChanges/store.applyChangeset` are as follows:
- Filter is only applied to the changeset being applied (local changes should still be visible to the user)
- Only `remove` should be capable of removing records from the view
- add/update action can only append records to the view
- Among new records only those matching filter should become visible
- if updated record stops matching filter, it should stay in the view
- if updated record starts matching filter, it should be added to the view

Todo:
- make sure filter API can apply filter to a subset of records
- make sure order of filtered records is consistent

Implementation details:
- Filtering is implemented on the collection level (store.storage is a Collection instance). Collection has `_values` property which holds complete dataset an `_filteredValues` which returns subset of records matching filter. Collection should get a new method that would apply filter function to the records affected by the changeset. That method should modify `_filteredValues` collection and insert/append records to correct positions. 
- Partial filtering code path should trigger event to allow view to react to the change. Probably it can trigger standard `filter` event. Or new one, smth like `partialfilter`. In the normal filter workflow view is refreshed due to `refresh` event fired by the store.
- To make sure affected records are included into filtering, we need to build a complete list: take new records from the changeset and resolve updated records from the target store. Updated records can only be filtered _in_ not _out_
- Speaking of a records order, I would expect new records to be added to the bottom of the view. While existing records which started to match the filter should be brought to the appropriate position - same as if we ran filter on the entire store.
- There has to be flag to turn this behavior on/off because this will target patch release. Similar to `reapplyFilterOnAdd/reapplyFilterOnUpdate`, smth like `reapplyFilterOnApplyChangeset`. We probably shouldn't allow to enable behavior for only new/updated records. It is either apply to all, or do not apply at all.

**Comment by ExtAnimal** [comment]
If it's a removed/added/updated operation, it should use some kind of abstracted code from the syncDataSet way of updating the store

That is for when frameworky people throw a whole new dataset at a store and it does minimal changes. It updates records which need updating, adds records which need adding and removes records which need removing.

That is basically the operation that is being referenced here.

There is a method in `StoreSync.js` called `synDataset`. That ingests a new dataset and calls a method which calculates the `toAdd, toRemove, toMove, updated` by comparing the incoming data block with the store's current dataset. It applies the calculated changes and ensures the current filter state and sort order is maintained.

That could be broken up to offer a method for `applyProjectChanges` to use.
