### ISSUE TITLE
Inconsistent End Date information in event tooltip when zooming out

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5535]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=22871&p=113060#p113060)

Hi,

We spotted a small UI glitch reproduce in any example (but I used Basic for this report).

First, position a task so that it end at midnight on a given day.
The tooltip should show an end date at 12:00 AM in the next day.
![Picture1.png](https://forum.bryntum.com/download/file.php?id=19447)
The task editor shows the end date with the same format, so this is consistent.
![Picture2.png](https://forum.bryntum.com/download/file.php?id=19448)

Now, zoom out some more until the tooltip only shows the date, without the hour information.
In this case, is shows the day during the task is still being executed, and not the next day.
![Picture3.png](https://forum.bryntum.com/download/file.php?id=19449)
The task editor still behaves the same of course, but the information displayed between the tooltip and the editor now seem inconsistent.

It feels like the day displayed in the tooltip should not be changed depending on the zoom level, which it currently does.

Sylvain
![Picture1.png](https://forum.bryntum.com/download/file.php?id=19447)
![Picture2.png](https://forum.bryntum.com/download/file.php?id=19448)
![Picture3.png](https://forum.bryntum.com/download/file.php?id=19449)

**Comment by sylvainmouretfico** [comment]
Hello,
I just check the online example, which should now be using version 5.2.4, but it still exhibit the same behaviour.
Was the issue really resolved?
Can you double-check?
Sylvain
