### ISSUE TITLE
`allDayEvents : null` in `DayView` children of `resourceView` leaves all day rows in the timeaxes

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#5536]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=22861&p=113038#p113038)

Hi,

Is it possible to remove the days of week section at the top of each day - particularly in resource View - but more generally also ? 

Thanks
![1.JPG](https://forum.bryntum.com/download/file.php?id=19425)

**Comment by dcruz1990** [comment]
What's the solution for this?
