### ISSUE TITLE
Events not being displayed properly when nestedEvents: true

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5540]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=22872&p=113120#p113120)

To reproduce the behavior, we have an example attached to SchedulerPro inline data demo

```

const schedulerPro = new SchedulerPro({
    appendTo : 'container',

    // makes scheduler as high as it needs to be to fit rows
    autoHeight : true,

    features : {
        nestedEvents : true
    },

    rowHeight : 80,
    startDate : new Date(2022, 2, 20),
    endDate   : new Date(2022, 2, 27),

    columns : [
        { field : 'name', text : 'Name', width : 100 }
    ],

    project : {
        resourcesData : [
            { id : 1, name : 'Dude' }
        ],

        eventsData : [
      
            { id : 11, name : 'Start here', startDate : '2022-03-21', duration : 2 },
            { id : 12, name : 'End here', startDate : '2022-03-24', duration : 2, eventColor : 'orange'  }
      
        ],

        assignmentsData : [
            { id : 2, event : 11, resource : 1 },
            { id : 3, event : 12, resource : 1 }
        ]
    }
});
```

With that configuration, you'll see no events being displayed (check attached screenshot)
![Screenshot 2022-11-07 at 20 10 39](https://user-images.githubusercontent.com/16693227/200435360-7711fa82-2996-4b32-b874-34966f505cfc.png)

But if you set `nestedEvents: false`, it'll display correctly
![Screenshot 2022-11-07 at 20 06 34](https://user-images.githubusercontent.com/16693227/200435407-3337bf60-418a-490d-bf78-0f7f01569310.png)

**Comment by isglass** [comment]
NestedEvents requires EventStore to be a tree store. Adding `eventStore : { tree : true }` to the project config makes the events appear
