### ISSUE TITLE
Drag create when using showExactResizePosition doesn't show invalid rendition for 0 duration event

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5546]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=22851&p=112942#p112942)

By default (showExactResizePosition: false) when using event drag create, the tentative event being drawn, as the pointer moves, changes between semi-transparent when invalid (too short) to fully opaque when valid.  Works great. 

However, when using showExactResizePosition: true, the tentative event is not semi-transparent when the event is too short.  To reproduce this, drag to start creating a new event and then move your cursor back toward the starting position then let go of the button.  No new event will be created.  It is confusing our users who are trying to create short events because the same, solid look is displayed whether it will create (long enough) or not (too short).  See the attached video of the Bryntum basic scheduler example.

```
const scheduler = new Scheduler({
features: { 
   eventDragCreate: { 
      showExactResizePosition: true
   }
}, ...
```

**Comment by matsbryntse** [comment]
https://user-images.githubusercontent.com/218570/200613197-eb4279b1-e1d9-46ca-a245-4c66ec5c9658.mp4

**Comment by hostrowski04** [comment]
Hello, we still have this issue with the v5.3.2 upgrade.  Team updated the original forum post.
