### ISSUE TITLE
[ANGULAR] "beforeEventAdd" cancellation doesn't seem to prevent event creation

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5557]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=22909&p=113275#p113275)

"Greetings.
In our current project, we need to prevent users from adding new events to the scheduler (scheduler pro version 5.2.2). We're able to prevent event add from schedule menu with this config, which is bound to scheduleMenuFeature:

```
scheduleMenu: {
      items : {
          addEvent: false
      }
    },
```

But we also need to prevent event add when the user performs a double click on a resource row. We tried to achieve that result by binding to the "onBeforeEventAdd" with in the component template:

```
(onBeforeEventAdd)="beforeEventAdd($event)"

```

with the following callback:

```
  beforeEventAdd(args: any){
    console.log('before event add called');
    return false;
  }
```

The callback is called correctly, but even if we return false (according to your documentation on cancellable events) the event is added anyway to the scheduler."

**Comment by isglass** [comment]
Events are prevented differently in Angular, closing
