### ISSUE TITLE
Combo filter works incorrect in multiSelect mode

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5565]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=22912&p=113342#p113342)
On docs page
https://bryntum.com/docs/grid/api/Core/widget/Combo#multiselect--grouped-list

Try to expand the list of editable combo and type few letters, as example "co"
Select filtered value "Cobol" using Enter.
See that "co" is still in the input and list is expanded. Remove letters to see more results - see that list is collapsed.

It should not be collapsed after first value selected, when typed text is removed.

https://user-images.githubusercontent.com/7203098/201248382-d31dc147-1e25-4d6a-8930-6f0802532d22.mov

**Comment by isglass** [comment]
It behaves as we want it to, closing
