### ISSUE TITLE
Changing event programmatically with segments field doesn't change the event

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5567]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=22925&p=113371#p113371)

Hi,

I'd like to report a bug. As far as I see it is present in the SchedulerPro, but it is working in the normal Scheduler.
Tested in 5.2.0-beta and 5.2.2.

Steps to reproduce:
Open: https://bryntum.com/examples/scheduler-pro/percent-done/ (you can open other example as well)
Run in the console: 
```
schedulerPro.eventStore.getAt(0).setAsync({ eventColor: 'red', segments: undefined });
```

Expected: first event turns red
Actual: scheduler did not change, did not re-render

Notes:
if you zoom in or our (or trigger some kind of refresh), then scheduler will be re-rendered and the first event turns into red

**Comment by ghulamghousdev** [comment]
This issue is already fixed and not reproducible anymore.
