### ISSUE TITLE
Using sort feature triggers `autoLoad` for `AjaxStore`

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5572]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=22865&e=1&view=unread#unread)

To reproduce use live demo on https://bryntum.com/docs/grid/api/Core/widget/PagingToolbar 
Change `autoLoad` on `false`. 
Add
```
features : { sort : 'name' }
```

See that grid will be loaded automatically. 
This makes problems to user when he tries to apply saved state on grid that also contains sort direction.

User story:

> To reproduce the issues, please follow the following steps:
Sorting parameter is not correct in the request after reloading
1. Load the application
2. Order the name column
3. The state is now saved the local storage
4. Refresh the page
The state is loaded from the local storage
The url for getting the data is not having the correct sorting

> Filter parameter is being used on the the request after reloading
1. Load the application
2. Filter the name column
3. The state is now saved the local storage
4. Refresh the page
The state is loaded from the local storage
The url for getting the data is not having the filter parameter

**Comment by taauntik** [comment]
The user is asking for the fix [here](https://forum.bryntum.com/viewtopic.php?p=113987#p113987)
