### ISSUE TITLE
eventColor and cls styling are ignored for segments in Gantt

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5575]
In the inline example in docs https://bryntum.com/docs/scheduler-pro/api/SchedulerPro/feature/EventSegments
see one event segment has been set with `eventColor: 'indigo'`, but it's green.

Try to set `cls` for segment with `background-color`, it will be overridden with default styling.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=22914&p=113417#p113417)

**Comment by chuckn0rris** [comment]
Another request https://forum.bryntum.com/viewtopic.php?f=52&t=23858&p=121960#p121960

**Comment by JockeLindberg** [comment]
From reading both forum post this comes down to support for setting `eventColor` on a Task segment. There is currently no support for setting `eventColor` on a task in Gantt, that only works in Scheduler. But, in https://github.com/bryntum/support/issues/857, which will be a part of 5.4.0, there will be support for that. There will also be support for setting different colors on different segments using `eventColor`.

**Comment by JockeLindberg** [comment]
Closing, track bryntum/support#857 instead.

**Comment by vulevukusej** [comment]
@JockeLindberg #857 refers to gantt tasks?
