### ISSUE TITLE
Make configurable amount of days in CalendarRow widget

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5580]
<img width="735" alt="Screenshot 2022-11-14 at 22 05 12" src="https://user-images.githubusercontent.com/7203098/201693881-652b5138-2772-4596-b61a-67cce4acf095.png">

[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=22945&p=113494#p113494)

Hi,

After upgrading from 5.1.1 to 5.2.1, the day view displays additional dates in the header row.
Is it possible to configure the day view to show only single (current) date in the center of the day view header to look the same way as it was in version 5.1.1?

Thanks

**Comment by ExtAnimal** [comment]
`fullWeek : false`
