### ISSUE TITLE
No validation error message on save overlapped data by event editor

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5597]
https://bryntum.com/examples/scheduler/validation/

[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=22975&p=113629#p113629)

Hello,

```
allowOverlap: false
```

Validation message is shown in tooltip while dragging event to overlap over existing event.
Validation message is not shown in editor when the user saves modified/created event that overlaps existing event. This is not user-friendly not letting user know why the Save operation is not performed.
![Screenshot_1.png](https://forum.bryntum.com/download/file.php?id=19566)
![Screenshot_1.png](https://forum.bryntum.com/download/file.php?id=19566)

**Comment by mkiriejevas** [comment]
Hello,
Additional note: the same issue is for event created directly in timeaxis by dragging mouse and making timerange overlap over existing event - no tooltip is shown and after releasing mouse button the event is not created without notifying user.

**Comment by matsbryntse** [comment]
Dupe #2841
