### ISSUE TITLE
When I try to setconfig column, I only want to change the resource axis, but the timeline also receives heroes

### ISSUE THREAD

**Issue by Jsonpig** [bryntum/support#5598]
![image](https://user-images.githubusercontent.com/86960818/202378186-ad5a5c43-8190-4545-95be-8950a45a8f74.png)

![image](https://user-images.githubusercontent.com/86960818/202378240-9d8ae8df-9345-4751-ae65-139e103c99eb.png)

Why is the timeline bound to the resource axis？How should I solve this problem？

**Comment by matsbryntse** [comment]
How can we reproduce this? Can you please provide us a test case?

**Comment by Jsonpig** [comment]
![image](https://user-images.githubusercontent.com/86960818/202387297-09386970-691f-42e6-915b-b48a625e0169.png)
After creating an instance, call setConfig directly to reset the values of columns

![image](https://user-images.githubusercontent.com/86960818/202387937-f616ab24-97d8-4df3-899b-409abbedea54.png)
This is the content of my original columns

When a change in the original columns value is detected, setConfig updates the columns directly.

Something like the following
![image](https://user-images.githubusercontent.com/86960818/202388298-5c4feeff-79e9-47a3-b906-2532572194fc.png)

Updating the value of the column will refresh the value of the timeline. I guess because columns also contain the timeline, is there a way to update the table column of the Scheduler without affecting the timeline?

**Comment by matsbryntse** [comment]
This works fine on our latest, can you please confirm? Test coverage added.
