### ISSUE TITLE
ExtjsModern demo: Mask is not removed when Ext.Msg.alert is closed

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#56]
Forum: https://www.bryntum.com/forum/viewtopic.php?f=44&t=12600#p66291

According to the user it used to work in 2.2 and stopped working in 2.3

To reproduce:
https://bryntum.com/examples/grid/extjsmodern/
In console:
```
Ext.Msg.alert('Message', 'Click OK to unmask');
```
Click OK.
See mask is still there.

**Comment by matsbryntse** [comment]
Same issue as https://github.com/bryntum/support/issues/91
