### ISSUE TITLE
Calendar events duplicated in UI when events start date is changed.

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5606]
Open https://www.bryntum.com/examples/calendar/basic/

Goto Month view.
Create an event.
Dblclick to edit. Set startDate 2 days before, endDate 2 days later initial values. 
Save.

See event doubled on the UI and have 2 titles.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=22994&p=113703#p113703)

**Comment by ExtAnimal** [comment]
It's not really duplicated. It's just that the refocus operation on hide of the editor focuses the previously active part of the event which is now the normally invisible event bar in the second cell. It just needs to refocus better.

**Comment by ExtAnimal** [comment]
`Calendar` needs this:

<img width="884" alt="Screenshot 2022-11-17 at 18 00 16" src="https://user-images.githubusercontent.com/200516/202509772-181381f8-138e-439a-b5ef-c4c33bf909f8.png">

And `Calendar/view/mixin/EventNavigation` needs this:

<img width="1161" alt="Screenshot 2022-11-17 at 18 01 36" src="https://user-images.githubusercontent.com/200516/202510055-fd69a09e-8364-4f71-b6bd-4a43f371b961.png">
