### ISSUE TITLE
contextMenu feature should support being disabled

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#561]
The contextMenu should not show.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?p=71385#p71385)

I thought I was in the right spot at Grid.feature.ContextMenu#disabled, but om not.

```
 scheduler = new Scheduler({
            features: {
                contextMenu: {
                    disabled: true
                },
```

Does not disable the context menu. Any clues?

**Comment by chuckn0rris** [comment]
Respond on forum. Waiting for client's response to decision.

**Comment by jsakalos** [comment]
I have re-tested it and it is not reproducible with the current sources in the `release` branch.  As it was clarified with the user in forum, he actually wanted to remove "Delete record" item from the resource grid context menu for which he was advised to set `showRemoveRowInContextMenu:false`.

**Comment by chuckn0rris** [comment]
Won't fix. Client said it's resolved to him https://www.bryntum.com/forum/viewtopic.php?p=71385#p71385
