### ISSUE TITLE
Gantt crashes when dragging a resource to a collapsed grid

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5614]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23011&p=113787#p113787)

"Hi 

this is reproducible on your demo as well.

If Gantt chart left grid is collapsed (only gantt shown), then dragging and dropping from the Resources tab, crashes.

[https://bryntum.com/examples/gantt/drag-resources-from-grid/](https://bryntum.com/examples/gantt/drag-resources-from-grid/)

thanks."

Also added a video for reference

https://user-images.githubusercontent.com/16693227/202765475-4afea95d-131c-4cb6-8774-756249216048.mp4

**Comment by marciogurka** [comment]
The error that appears is `Uncaught (in promise) TypeError: resourceAssignmentCell.querySelector is not a function`

**Comment by taauntik** [comment]
This is still reproducible

https://user-images.githubusercontent.com/75997756/204780260-dec92434-2498-45a3-aa1b-38b3c113af16.mp4

reopening the ticket
