### ISSUE TITLE
Issues with date column filter with custom format

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5615]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=22976&p=113746#p113746)

Based on [https://www.bryntum.com/examples/grid/filtering/](https://www.bryntum.com/examples/grid/filtering/)

When you add the following format configuration to the column definition

```
{ text : 'When', field : 'start', width : 200, type : 'date', format : 'YYYY-MM-DD' },
```

You experience the following behavior (check the video)

https://user-images.githubusercontent.com/16693227/202803749-22d3cf81-8bac-4622-8700-1080636575fc.mp4

**Comment by chuckn0rris** [comment]
User said using correct field type in data model fixed this bug.

**Comment by canonic-epicure** [comment]
Thanks for pointing @chuckn0rris.
