### ISSUE TITLE
Task indicator support

### ISSUE THREAD

**Issue by pradosh123** [bryntum/support#5616]
In my client project, I'm using Ext JS 6.0.2.437 which internally uses Gantt Pro 5.0.3 (licensed)  from bryntum for Gantt chart representation. I want to render custom indicators to a task row and also that should be positioned by dates. I need the similar one that is mentioned [here](https://bryntum.com/docs/gantt-for-extjs/?#!/api/Gnt.plugin.TaskIndicators)  by using the TaskIndicators plugin. I tried the same plugin configuration in my  project and ended up with the below error

![WhatsApp Image 2022-11-19 at 10 21 05](https://user-images.githubusercontent.com/12003613/202834795-7252ca34-e839-43c9-97bb-f659cd35d33e.jpeg)

![WhatsApp Image 2022-11-19 at 10 21 04](https://user-images.githubusercontent.com/12003613/202834874-9a28f710-d1c3-4222-86da-4e861fda22b2.jpeg)

Does this happen because of the versions of my  Ext JS  and  Gantt Pro? How can i fix this? Do I need to update my packages? if so which version?

Or is there any alternative solution available within my current version for adding task indicators? I'm here as a newbie in Ext JS and bryntum Gantt pro. could someone please help

**Comment by matsbryntse** [comment]
Better to ask questions in our support forums, and if this is a bug, we'll create a ticket in GitHub. Please post here: http://forum.bryntum.com/

**Comment by pradosh123** [comment]
@matsbryntse As you mentioned, I had created a support ticket in the forum(http://forum.bryntum.com/) with the same query which I quoted here (https://forum.bryntum.com/viewtopic.php?t=23015). Not only my post has not received a single reply but also that is got disappeared from the forum. I created the same post again but that also got removed from the forum within one day(https://forum.bryntum.com/viewtopic.php?t=23028). I'm not sure why. could you please help?
