### ISSUE TITLE
dropOnLeaf not working correctly in Salesforce

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5628]
`dropOnLeaf` doesn't work, no styling applies as well.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23023&p=113840#p113840)

Code to reproduce in file attached 

[grid_component.zip](https://github.com/bryntum/support/files/10066482/grid_component.zip)

**Comment by amurashinffdc** [comment]
This one seems to be related to #5635 as well.

**Comment by matsbryntse** [comment]
@amurashincertinia Is this one still reproducible for you?

**Comment by chuckn0rris** [comment]
Tested in 6.1.0, worked good to me. I am closing this ticket.
