### ISSUE TITLE
Tick size cannot be set less than certain value

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#563]
Reproducible on vertical demo https://www.bryntum.com/examples/scheduler/vertical/:
```
scheduler.tickSize = 40 // no effect
scheduler.tickSize = 100 // tick size increased
scheduler.tickSize = 40 // tick size is reduced to 80, because 80 is fitting tick size (available space / tick count)
scheduler.endDate = new Date(2019, 0, 1, 12) // tick size is 160 now and cannot be lower
scheduler.tickSize = 100 // no effect
```

**Comment by chuckn0rris** [comment]
`suppressFit: false` as a default value in the `TimeAxisViewModel` class don't allow to use a full range of 'tick height' slider.

**Comment by nnistala** [comment]
+1
This is actually a blocking issue for us, can we expect it to be resolved in the next update?

**Comment by abhisrinu** [comment]
This is blocking for us also and we are waiting for this to move our product to production. Please consider this in the next patch
