### ISSUE TITLE
Make DayView time division lines optionally more granular

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#5645]
The gradient applied should match the breakpoint class names applied by https://www.bryntum.com/products/calendar/docs/api/Calendar/widget/DayView#typedef-HourHeightBreakPoints

So for `small`, it would use the current gradient with 60 and 30 minute lines.

We would have to code up `background-image` gradients for the other sizes.

Customers with CSS skills (and `backhground-image` gradients are difficult) would be able to override these in their own CSS.

Related to https://github.com/bryntum/support/issues/5644

**Comment by stewart-mcleod** [comment]
Our software is used to record time for lawyers and accountants. Conventionally, these users record their time in decimal hours (i.e. 6 mins intervals = 0.1 hours) a granular zoom incorporating a 6 minute timescale would be amazing.

**Comment by ExtAnimal** [comment]
@stewart-mcleod So as I understand it, the __labels__ down the left side need to be on the six minute marks, not the five minute marks, so when the [hourHeight](https://bryntum.com/products/calendar/docs/api/Calendar/widget/DayView#config-hourHeight) is set large enough, you would like to see this:

<img width="482" alt="Screenshot 2023-01-16 at 10 50 50" src="https://user-images.githubusercontent.com/200516/212648927-7fb7eab5-7381-4653-bed7-330c722007c3.png">

The "snapping" when drag-creating or resizing or moving events is controlled by the [increment](https://bryntum.com/products/calendar/docs/api/Calendar/widget/DayView#config-increment) config option on the `DayView` mode. (Remember that a `WeekView` is just a multi day `DayView`) so this already has what you need.

I am thinking of adding a new config option to switch to this mode of dividing an hour:

`sixMinuteTicks : true`

Configuring a `DayView` with that (Or setting it in the [modeDefaults](https://bryntum.com/products/calendar/docs/api/Calendar/view/Calendar#config-modeDefaults) option) would change how an hour is divided to make six minutes the base tick size.

Would this completely fulfil the requirement?

**Comment by stewart-mcleod** [comment]
@ExtAnimal yes correct 6 mins down the left and all the other points noted.

**Comment by stewart-mcleod** [comment]
Nice.

**Comment by stewart-mcleod** [comment]
@ExtAnimal 

An issue we discovered in testing:

Even though the Zoom increment was 6 minutes (5 in our view), when you create a new calendar item there is a default time duration, that only allows you to create (or edit) in increments of 30 minutes. Is there a setting for time duration (using the mouse to add either single click or click / drag)?

In the example above I can see it properly renders in 6 minute intervals. So may be this is a setting we can't identify through the knowledge base.

Thanks

**Comment by stewart-mcleod** [comment]
Of course! THis appears to be the [increment](https://bryntum.com/products/calendar/docs/api/Calendar/widget/DayView#config-increment) config option.
