### ISSUE TITLE
Columns sometimes collapse when resizing

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5647]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23062&p=113982#p113982)

Hey,
So we noticed that sometimes when you try and resize columns the header collapses but the content of the column doesn't. I have attached a video showing this on the column types demo.

You can reproduce it here https://bryntum.com/products/grid/examples/columntypes/
Here is how you can reproduce it :
Please make sure your window should not be fullscreen

https://user-images.githubusercontent.com/75997756/203777690-5b42f79b-772f-409e-bc1c-9551fdbffc4e.mp4

**Comment by isglass** [comment]
Also breaks if you hit ESC during resize
