### ISSUE TITLE
drag and drop does'nt work in lwc

### ISSUE THREAD

**Issue by freddyLang** [bryntum/support#5650]
Hi,

i create a DomHelper in an lwc salesforce, like this : 
        this.DomHelper = new bryntum.scheduler.DomHelper();
and i use it in drag:
                    coordinate   = this.DomHelper[`getTranslate${schedule.isHorizontal ? 'X' : 'Y'}`](context.element),
but the task always come back to the grid list.

BR

**Comment by matsbryntse** [comment]
Can you please share some more details of how we can reproduce this?

**Comment by freddyLang** [comment]
Hi Mats,

i don't have acces to the bryntum support, heaven with my utb account.

I don't have acces to the last version of scheduler.

My prof email is ***@***.***, and my account is ***@***.***

thank you for your feed back

BR
________________________________
De : Mats Bryntse ***@***.***>
Envoyé : dimanche 1 janvier 2023 11:06
À : bryntum/support ***@***.***>
Cc : freddyLang ***@***.***>; Author ***@***.***>
Objet : Re: [bryntum/support] drag and drop does'nt work in lwc (Issue #5650)


Can you please share some more details of how we can reproduce this?

**Comment by bmblb** [comment]
Drag from grid works in LWC when properly configured. Please check out this demo: https://bryntum-dev-ed.develop.lightning.force.com/lightning/n/SchedulerProTempDemo You can find credentials here: https://bryntum.com/products/gantt/docs/guide/Gantt/quick-start/salesforce#online-example
