### ISSUE TITLE
Event Editor fields misaligned with longer label

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#568]
There is no easy way to (re)align Event Editor fields. To reproduce add the following code to `Scheduler/examples/react/javascript/simple/src/containers/Main.js` and run the demo. There should be a simpler way as workaround advised in the forum.
```
eventEditFeature={{
    resourceFieldConfig:{
        label:'Add to resource'
    }
}}
```

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=13769&p=71409#p71409)

Hi ,
I have added a customised combo box and it is not aligned.

Can you please help me to fix this out. 

Please refer the image i have attached

**Comment by isglass** [comment]
Closing this in favor of https://github.com/bryntum/support/issues/4296
