### ISSUE TITLE
Sticky event bug after reverted drag drop

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5702]
https://bryntum.com/products/schedulerpro/examples/dependencies/
Drag an event to the left of the schedule
Note stickiness is now wrong
<img width="629" alt="Screenshot 2022-12-02 at 12 04 37" src="https://user-images.githubusercontent.com/218570/205278818-e35ba23b-656d-42e9-b38d-f0819c9ca078.png">

**Comment by matsbryntse** [comment]
Browser bug, nothing to be done

**Comment by JeffDerk** [comment]
> Browser bug, nothing to be done

We're facing a similar issue where the sticky event text is off-screen or miss positioned but when you move the cursor over the Scheduler the text is positioned correctly.

Is this a confirmed browser bug?
