### ISSUE TITLE
Implement negative filter in menu

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#5708]
Requested by a client:
> is there already a way for end-users to negative filter in Bryntum?  Example:  Job Title <> “Janitor” (see all job titles but “Janitor”)

Current menu only shows `equals` filter
![image](https://user-images.githubusercontent.com/45400762/205607395-137fe627-40a5-45a3-a75b-45662ff801e5.png)

**Comment by dongryphon** [comment]
The "not" is useful in a lot of ways, even with string matching, "in" operator, empty vs not-empty, etc.. A couple jobs back, we implemented a generic "not" toggle that applied to any filter clause. fwiw
