### ISSUE TITLE
Task end date changes when open the editor

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5715]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23137&p=114439#p114439)

Using the data sample provided by the user, you'll see the end date of the task/project is 2023-09-25, but when you open to edit, it shows 2023-09-23. A video is attached to demonstrate the issue.

To facilitate, you could use the basic demo from Gantt and set the start date of the Gantt like this 
```
    startDate         : '2023-09-23',
```

https://user-images.githubusercontent.com/16693227/205655493-158ad298-bda9-49c4-a017-49cf616444a5.mp4

**Comment by matsbryntse** [comment]
This has already been fixed in another ticket, please try using latest version with this Project config added:
```

project : {
        skipNonWorkingTimeInDurationWhenSchedulingManually : false,
```
