### ISSUE TITLE
Improve TypeScript definitions for Bryntum

### ISSUE THREAD

**Issue by TheNoim** [bryntum/support#5722]
Hello Bryntum team,

We are using Bryntum in our TypeScript project, but we have noticed that the TypeScript definitions for the library are incomplete and do not provide correct typings for the `data` property of the store classes. Currently, the `data` property has the type `object[]` in these classes, but more specific types such as `EventModel[]` or `ResourceModel[]` would be more appropriate.

We would like to kindly request that you improve the TypeScript definitions for Bryntum to provide correct typings for the `data` property of the store classes. This would help us and other TypeScript developers who are using the library to write more type-safe and efficient code.

Thank you for your consideration.

Best regards,

Nils

Edit: Furthermore, optional values should actually be optional. It's crazy how often I've come across an optional field that was labeled as required. In fact, I believe all fields should be optional unless explicitly stated otherwise.

**Comment by SergeyMaltsev** [comment]
All topics related to TypeScript updates and improvements are here
https://github.com/bryntum/support/issues/5176
Closing as duplicate
