### ISSUE TITLE
`index` is ignored when insert into filtered store

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5730]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=23185&e=1&view=unread#unread)

Apply filter to grid store.
Insert new record into grid with index
```
grid.store.insert(2, {name : 'ABBA'})
```

See that record added to the end. Works well if remove filter.

**Comment by meta-amit-jodha** [comment]
great, when are we expecting this fix to be released (which version)

**Comment by SergeyMaltsev** [comment]
It has been released with `5.2.5` version.
