### ISSUE TITLE
Combo should update value collection silently when replacing store

### ISSUE THREAD

**Issue by isglass** [bryntum/support#5732]
It now leads to unexpected events being triggered

**Comment by ExtAnimal** [comment]
Upon receipt of a new Store, the existing content of the `valueCollection` must be silently updated so the the record instances held by the `valueCollection` are the same instances that entered in the new Store.

This is a similar operation to how GridSelection reacts to large scale Store changes. It has

```
                // Update selected records collection
                selectedRecordCollection.forEach(record => {
                    const newRecord = store.getById(record.id);
                    // If record still exists after reload, update selectedRecordCollection with a reference to the new task version
                    if (newRecord) {
                        const index = selectedRecordCollection.indexOf(record);
                        selectedRecordCollection.splice(index, 1, newRecord);
                    }
                    else {
                        toRemove.push(record);
                    }
                });

```

Matched records from the new Store are spliced into the selection and records which are not present in the new Store are removed from the selection.

`Collection` needs a new method like `match(otherCollection)` which does this operation. Then both `Combo` and `GridSelection` could use that.
