### ISSUE TITLE
Entering invalid date in task edit freezes and crashes the browser

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5779]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23259&p=115069#p115069)

Steps:
 Go to any of the Gantt examples the have the date column editable
 click on a date and start typing a year 
 lets say by mistake the user pressed 20222 in the year
 the Gantt will freeze and also the browser tab will crash

It seems that the Gantt actually rejects the value but still it freezes and crash which means something is happening on the backside of the gantt, like calculations being attempt of so

is there a way to manually validate inputs on date fields and also prevent the gantt from doing any calculations based on this validation

**Comment by canonic-epicure** [comment]
So what resolution to apply? Some options:
1) One can hard-code the check for the extra digit in the year number, lets say into the `DateHelper.isValidDate()`
2) Implement a new validation hook into the editor's value applying flow
The hook should be called very early. Right now there's a `finalizeCellEdit` config, which seems to be not used for the "instantUpdates" (??)
3) Or may be, the date column can accept a `isValidDate` config (analogues to `DateHelper.isValidDate`, which is used to determine date's validity internally)
