### ISSUE TITLE
Problem with pan enabled for 2 partnered schedulers

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5781]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23261&p=115087#p115087)

Hello,

We have a reproducable issue when we partner two schedulers or a gantt with a scheduler.
The problem occurs when in both components the pan feature is activated.

Reproduce in for example:
https://bryntum.com/products/schedulerpro/examples-scheduler/partners/

In both components enable panning:

```
pan: true,
eventDragCreate : false
```

Now, after panning around for a while between the two components the view starts to jump away/shaking/flashing under the mouse.
How to fix this/is there a workaround?

**Comment by tomvanoost** [comment]
@chuckn0rris Any update on this?
