### ISSUE TITLE
Automatic dependency setting not working after resetting events array

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5788]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23234&p=115139#p115139)

I just found another rather serious bug for us, that seems to be related to the vue package of SchedulerPro.

The issue is that the scheduling stops working, after resetting the events array passed in as a prop to the vue component. Below is a video of the problem. The transcript is like this:

For two events A, B with dependency from the end of A to the start of B, I am moving A to start one day earlier. This will correctly update B.
Now, I am resetting the events array to the initial dates (it's an actual reset of the array). As expected, both A and B jump back to the initial position
I do the same as in 1. and move A to start one day earlier. Now, B is not updated.

https://user-images.githubusercontent.com/75997756/207769891-727ee4fe-7dd0-4574-8e1e-2e8ea78473aa.mov

You can reproduce it with this code attached in the zip below
[test-app.zip](https://github.com/bryntum/support/files/10233609/test-app.zip)

**Comment by isglass** [comment]
My guess without checking anything is that `syncDataOnLoad` sets the dates, leading to constraint dates, preventing scheduling by deps. If so, need to make sure that does not happen

**Comment by canonic-epicure** [comment]
Caused by this code in the test case:
```
      onClick : () => {
const e1 = scheduler.eventStore.getById(1);
const e2 = scheduler.eventStore.getById(2);
e1.startDate = new Date(2017, 0, 1, 10)
e2.startDate = new Date(2017, 0, 1, 13)
}
```
Which sets the constraint on `e2` as Johan mentioned. If intention is to keep the `e2` scheduled by the dependencies flow, one should not assign a start date to it.

**Comment by canonic-epicure** [comment]
User is requesting the flag that would prevent the creation of the constraints. IIRC, in SchedulerPro, we don't stick events to the project start date, they "hang around" on the date they were originally placed. So such config possibly make sense. Need to discuss with Arcady.

**Comment by canonic-epicure** [comment]
Ok, we'll be adding such flag.

**Comment by canonic-epicure** [comment]
After the resolution - the automatic addition of the constraint won't happen for the case when data is loaded to the store with `syncDataOnLoad` enabled. This should fix the issue already. Plus, there's a new `addConstraintOnDateSet` config on the project to explicitly disable this behavior completly.
