### ISSUE TITLE
Timeline is broken when event is scrolled into view

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#58]
Forum: https://www.bryntum.com/forum/viewtopic.php?f=44&t=12781

To reproduce:
http://lh/bryntum-suite/scheduler/examples/bigdataset/
```
scheduler.eventStore.first.startDate = new Date(2019, 9, 1)
scheduler.eventStore.first.endDate = new Date(2020, 5, 1)
```
Scroll timeline to the right.
Click on the first event.
See timeline is scrolled.
Header is broken.
<img width="1246" alt="Снимок экрана 2019-11-28 в 18 12 20" src="https://user-images.githubusercontent.com/57486733/69817037-ba223b80-120a-11ea-9111-ce6557fea538.png">

**Comment by pmiklashevich** [comment]
Related ticket: https://github.com/bryntum/support/issues/40 (should be fixed first)

**Comment by bmblb** [comment]
Related ticket: #75

**Comment by ExtAnimal** [comment]
Duplicated by https://github.com/bryntum/support/issues/105

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/311
