### ISSUE TITLE
Watermark shown in online Calendar demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5803]
https://bryntum.com/products/calendar/examples/frameworks/react/javascript/filtering/build/

<img width="1145" alt="Screenshot 2022-12-17 at 19 49 35" src="https://user-images.githubusercontent.com/218570/208257048-d3f11b68-f103-4e34-9f60-817b75c68bb4.png">

**Comment by taauntik** [comment]
Not reproducible
