### ISSUE TITLE
Modifying just event start time also updates endtime

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5806]
You can reproduce it here https://bryntum.com/products/scheduler/examples/basic/

By adding this `tbar` to the scheduler
```
    tbar : [
        {
            type : 'button',
            text : 'Update',
            onClick : ({ source }) => {
                const events = source.parent.parent.eventStore.records;
                
                const exampleEvent = events[0];
                exampleEvent.name = 'I am being updated';

                let startDate = new Date(exampleEvent.startDate);        
                        
                startDate.setTime(startDate.getTime() - 1200000);   
                exampleEvent.startDate = startDate;
            }
        }
    ]
```
-------------------------------------

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23277&p=115272#p115272)

Hi, I am using version 5.2.3 of bryntum-schedule in an Angular application.

I am finding when I update just the startDate of an event it is also changing the endtime, so the whole event moves rather than the duration changing.

I have attached a simple example (taken from the Angular basic example) to demonstrate.

In the attached, you will see a button "Update Event start time". When this is pressed, is runs the update() method where we just adjust the start time, and we see the whole task moving rather than just the start time changing. This happens even if I get the current end time and set it back to the same thing.

This happens regardless of if we are using batch mode or not.

Any ideas  what could be wrong here?

Thanks in advance

**Comment by isglass** [comment]
That is the indented behaviour, explanation added to the post
