### ISSUE TITLE
[REACT] Implement support for JSX in ResourceHeader::headerRenderer

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#5808]
This is a follow-up of https://github.com/bryntum/support/issues/774 which implements JSX support in tooltips and widgets.

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?p=127773#p127773

**Comment by taauntik** [comment]
another request https://forum.bryntum.com/viewtopic.php?p=128113#p128113 with some info

**Comment by jsakalos** [comment]
Here is the docs: https://bryntum.com/products/scheduler/docs/api/Scheduler/view/ResourceHeader

**Comment by jsakalos** [comment]
And here is the old duplicate: https://github.com/bryntum/support/issues/762
