### ISSUE TITLE
Horizontal scroll not working when mergeCells feature is enabled

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5812]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=23306&p=115292#p115292)

You can reproduce it here https://bryntum.com/products/grid/examples/merge-cells/

Do the following to reproduce it

![chrome_deK0Ts4k4y](https://user-images.githubusercontent.com/75997756/208457388-6e8cbc23-8629-452e-a25e-ac7376860ae7.gif)

**Comment by isglass** [comment]
Because it forces `overflow: visible` for stickyness to work. Need to make that configurable to allow opting out (or perhaps in)
