### ISSUE TITLE
Rectangle for events outside of rendered block calculated wrong

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#5815]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=23312)

The dependency lines pointing to events outside of the rendered region are calculated wrong. The rectangle includes the preamble. When these events are scrolled into view the lines switch to pointing to the beginning of the true event start.

**Comment by FilipiRafael** [comment]
Hello everyone, the problem will be solved by the engineering team, is it a library error?

**Comment by matsbryntse** [comment]
@FilipiRafael Are you still able to reproduce this issue? Please let us know if so, and we'll reopen this issue.

**Comment by FilipiRafael** [comment]
> @FilipiRafael Are you still able to reproduce this issue? Please let us know if so, and we'll reopen this issue.

Hey @matsbryntse, actually this is already solved I guess, but thanks 👍🏻
