### ISSUE TITLE
schedulerpro.module.js:29985 Uncaught (in promise) Error: Id collision on 441aea50-e766-ed11-9560-00224896cb88,71217435-1871-ed11-81ad-00224893307c,e2f1aaa2-707b-ed11-81ac-002248930713

### ISSUE THREAD

**Issue by ivanthas** [bryntum/support#5816]
Hi Team, 

Im getting this error in when pushing data from Dynamics 365 to schedular. What could be the error in these records. Please see the JSON for the relevant ID's

"id":"441aea50-e766-ed11-9560-00224896cb88",
            "eventType":"appointment",
            "name":"Access FMS and SCC FRC Team Meeting",
            "resourceId":"9701e083-723d-ed11-bba2-0022489338ac",
            "startDate":"2022-12-21 14:00",
            "endDate":"2022-12-21 16:00",
            "showInTimeline":true,
            "duration":120,
            "durationUnit":"m",
            "sessionId":null,
            "eventColor":"#2F5597",
            "sessionStatusId":null,
            "repeatPattern":null,
            "allDay":false

"id":"71217435-1871-ed11-81ad-00224893307c",
            "eventType":"appointment",
            "name":"Farewell AFC",
            "resourceId":"9bd24821-d821-ed11-9db2-002248127756",
            "startDate":"2022-12-16 12:00",
            "endDate":"2022-12-16 13:30",
            "showInTimeline":true,
            "duration":90,
            "durationUnit":"m",
            "sessionId":null,
            "eventColor":"#2F5597",
            "sessionStatusId":null,
            "repeatPattern":null,
            "allDay":false,

"id":"e2f1aaa2-707b-ed11-81ac-002248930713",
            "eventType":"appointment",
            "name":"Penrith Centre lunch",
            "resourceId":"5b01e083-723d-ed11-bba2-0022489338ac",
            "startDate":"2022-12-20 13:00",
            "endDate":"2022-12-20 14:00",
            "showInTimeline":true,
            "duration":60,
            "durationUnit":"m",
            "sessionId":null,
            "eventColor":"#2F5597",
            "sessionStatusId":null,
            "repeatPattern":null,
            "allDay":false,

**Comment by matsbryntse** [comment]
Sounds like you add many records with the same `id`. Try to inspect the data you are loading to see if you spot anything?

**Comment by ivanthas** [comment]
Thanks mate. I noticed there are duplicates. We should be able to setup one appointment for two resources. Appointment Id is duplicating. Any solutions?

**Comment by matsbryntse** [comment]
All id's should be unique. To assign two resources to one event, use the assignment store. See this demo: https://bryntum.com/products/scheduler/examples/multiassign/
 
Closing this for now, if you need help to get this working - please ask in our support forums. http://forum.bryntum.com/
