### ISSUE TITLE
Recurring Timeranges showing up as added in sync

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#582]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=13796&p=71504#p71504)

It is reproducible with our Recurring TimeRanges Demo by adding `autoSync:true` and `sync: {url:'...'}` to crudManager config. After editing an event, `added` property is populated:
<img width="1153" alt="Screen Shot 2020-04-24 at 13 47 38" src="https://user-images.githubusercontent.com/204844/80209546-9258c780-8632-11ea-997e-e646b9dca92d.png">

**Comment by matsbryntse** [comment]
Can't repro, @jsakalos Confirm?

**Comment by jsakalos** [comment]
Not reproducible. Neither on-line, nor locally in master (currently 4.1.0-alpha-1). Closing the ticket.
