### ISSUE TITLE
Infinite scroll demo shows lots of Toasts

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5825]
https://www.bryntum.com/products/scheduler/examples/infinite-scroll/
<img width="382" alt="Screenshot 2022-12-21 at 16 31 20" src="https://user-images.githubusercontent.com/218570/208942295-accccbb5-f40e-4470-a367-37065f102ef3.png">

**Comment by JockeLindberg** [comment]
Fixed by https://github.com/bryntum/bryntum-suite/pull/6326
