### ISSUE TITLE
Combo clearable trigger doesn't reset validation

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5838]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23375&p=115674#p115674)

"[Core.widget.Combo](https://bryntum.com/products/schedulerpro/docs/api/Core/widget/Combo)
Go to your [demo](https://codepen.io/pen?editors=0010).
Update first widget by adding clearable: true

```
new Combo({
    items    : ['Fanta', 'Loranga', 'Jaffa', 'Zingo', 'Orangina'],
    label    : 'Items as strings',
    appendTo : targetElement,
    style    : { marginRight : '.5em' },
    clearable: true
});

```
Type in a value that doesn't exist int the list.
See validation saying "Value must be selected from the list".
Clear value with X trigger.
See the validation stays warning you. This prevents event editor from saving even when the value is not required.
When you type a letter and then backspace to erase it, validation is updated and there is no errors."

The video is attached for more clarification about how to reproduce that error.

https://user-images.githubusercontent.com/16693227/209552243-f1e990d8-db66-4ef3-b32f-1eea64881101.mp4

**Comment by pmiklashevych** [comment]
@matsbryntse it is so nice to open a newly create ticket and see it is fixed already and in "ready for review" state. Thank you for keeping the pace and fixing such bugs instantly. Cheers!

**Comment by matsbryntse** [comment]
> @matsbryntse it is so nice to open a newly created ticket and see it is fixed already and in "ready for review" state. Thank you for keeping the pace and fixing such bugs instantly. Cheers!

Most welcome! :) Thanks for reporting the bugs, please let us know if you find anything else!
