### ISSUE TITLE
scheduler.eventStore.add is not bringing up the event that's newly added

### ISSUE THREAD

**Issue by egemen-dev** [bryntum/support#5847]
Hi folks,

I will keep it simple for the sake of understandability. I described my issue in the title, but want to give you some context regarding the problem I have with `scheduler.eventStore.add`

I am dragging and dropping a table row from a html table into the bryntum scheduler, and this row contains some info about the event. Example code below gets triggered inside of `onDrop()`
```
scheduler.eventStore.add({
        color: 'red',
        style: 'rounded',
        type: 'job',
        id: 0000001,
        name: 'My Event',
        startDate: new Date('2022-12-26T16:00:00Z'),
        endDate: new Date('2022-12-26T17:00:00Z'),
        customer: "John Doe",
        resourceId: '123456',
        resizable: true,
        draggable: true,
        status: 'example_status'
});
```
As far as I observed, this is creating the event successfully but not rendering the event in the screen. I cannot see the event in the scheduler, however when I put a debugger in the code and open up the browser console and run this -> `scheduler.eventStore`,  I can clearly see that event has been successfully created and sits with other events in the `data:` section.

Why event that's been newly created is not showing up in the scheduler even though it's been added to the `eventStore`?

Is this the correct way to add an event?

Thanks in advance.

**Comment by matsbryntse** [comment]
Please ask questions in our support forums instead. This GitHub repo is for bugs and feature requests. Please post here: http://forum.bryntum.com/
