### ISSUE TITLE
Panel.collapse and Panel.expand should be public

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5871]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=23427&p=115985#p115985)

**Comment by isglass** [comment]
We need to rename `expand()` / `collapse()` in the Group & Tree features before we can make this public. And that will be breaking changes, so have to wait until next major.

**Comment by isglass** [comment]
Decided we will use `expandPanel()` / `collapsePanel()` to avoid breaking
