### ISSUE TITLE
[Vue2] Disabling context menu in Grid.

### ISSUE THREAD

**Issue by dcruz1990** [bryntum/support#5881]
Guys, i swear, i tried to look for it on the documentation but i can't find anything related to it.. is there a way to do it? 

Im passing this feature to the grid:
![image](https://user-images.githubusercontent.com/43586145/210675606-5e6ecd32-a0fe-4196-837d-1f5dcfa59e19.png)

But the context menu keeps showing. 
![image](https://user-images.githubusercontent.com/43586145/210675698-d01f2d05-481f-4e57-a4c5-e59c976a0033.png)

**Comment by TMcKinley** [comment]
[Docs for CellMenu](https://bryntum.com/products/grid/docs/api/Grid/feature/CellMenu)

`cellMenuFeature: false`
