### ISSUE TITLE
Setting maxLength to TextAreaPickerField doesn't seem to work

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5892]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23459&p=116198#p116198)

You can reproduce it with our Grid basic example here https://bryntum.com/products/grid/examples/basic

```
        {
            text   : 'Name',
            field  : 'name',
            flex   : 2,
            editor : {
                type     : 'textareapickerfield',
                required : true,
                picker : {
                    maxLength : 1
                }
            }
        }
```

Then you'll see that still, you're able to type greater than 1 character
https://bryntum.com/products/gantt/docs/api/Core/widget/TextAreaPickerField#config-maxLength

**Comment by matsbryntse** [comment]
This is the correct syntax
```
picker : {
                    elementAttributes : { maxLength : 1 }
                }
```
