### ISSUE TITLE
getDateConstraint: Breaking constraints on specific zoom level(s)

### ISSUE THREAD

**Issue by devandreassimmeth** [bryntum/support#5903]
I'm new in the Bryntum world and I'm currently validating the scheduler on our purpose.

While doing this I found some strange behavior when using "getDateConstraint" and "allowOverlap" on some specific zoom level. Here's a snipped of my current SchedulerConfig:
```
{ 
  allowOverlap : false,

  columns : [
    {
      type : 'resourceInfo',
      text : 'Vessel',
      showImage: false
    }
  ],
  
  resources : [
    {
       "id": "ship_01",
       "name": "Ship 1"
    }
  ],
  events : [
    {
      "id": 1,
      "resourceId": "ship_01",
      "name": "Loaded Travel 1",
      "type": "Loaded",
      "startDate": "2023-02-27",
      "endDate": "2023-03-28",
      "eventColor": "gray"
     },
     {
       "id": 2,
       "resourceId": "ship_01",
       "name": "Empty Travel 1",
       "type": "Empty",
       "startDate": "2023-03-28",
       "endDate": "2023-04-26",
       "eventColor": "red"
     },
     {
       "id": 3,
       "resourceId": "ship_01",
       "name": "Loaded Travel 2",
       "type": "Loaded",
       "startDate": "2023-04-27",
       "endDate": "2023-05-25",
       "eventColor": "gray"
     }
  ],

  startDate : new Date(2022, 12, 1),
  endDate   : new Date(2023, 11, 30),
  viewPreset : {
    timeResolution : {
      unit      : 'week',
      increment : 1
    },
    headers : [
      {
        unit       : 'month',
        dateFormat : 'MMM YYYY'
      },
      {
        unit       : 'week',
        dateFormat : 'WW'
      }
    ],
  },
  zoomKeepsOriginalTimespan: true,
  ...
}
```

This results in the following Scheduler:
![Scheduler_Loaded](https://user-images.githubusercontent.com/98212488/211520390-fbd0f650-0258-484f-9fa7-9993db3204f6.png)

In the "OnInit" of the component which encapsulates the scheduler I add the "getDateConstraint" method to the SchedulerConfig, which should set the date boundaries for Empty travels between the endDate of the loaded travel before and the startDate of the loaded travel after the empty travel. So in our case this function returns:
```
{
    "start": "2023-03-28T00:00:00.000Z",
    "end": "2023-04-27T00:00:00.000Z"
}
```

When I now drag and drop the empty event in the pre-defined view, the following is happening:
![Scheduler_Dropped](https://user-images.githubusercontent.com/98212488/211522207-ebd615c5-9810-4d1a-ab52-b449f1824c5c.png)

The Empty event has now the properties `startDate: 2023-03-26` and `endDate: 2023-04-24` although the return of "getDateConstraint" and `allowOverlap: false` are violated with that.

So now is the question: Is this an issue or am I making something wrong. After studying the documentation and the examples, it looks more like an issue for me.

**Comment by devandreassimmeth** [comment]
Update: I fixed it using the following timeResolution:
```
timeResolution : {
  unit      : 'day',
  increment : 1
},
```

Still, it is unattractive that the functionality breaks in the above configuration.

**Comment by matsbryntse** [comment]
Good thing you found a way forward, we'll investigate the issue. Thanks for reporting! :)

**Comment by matsbryntse** [comment]
@devandreassimmeth You test case seems to work ok for me now in latest release, can you please confirm?

**Comment by devandreassimmeth** [comment]
@matsbryntse Nice, thanks for coming back to that error! 

Our application grew extremely over the last year and looks completely different now. But I will have a look whether I can verify this when I have a free minute for it. :)
