### ISSUE TITLE
[BUG] Loop in pathifyKeys on sync segmented task!

### ISSUE THREAD

**Issue by javascript-programming** [bryntum/support#5906]
![Screenshot 2023-01-10 at 14 17 05](https://user-images.githubusercontent.com/25703411/211561849-0b905b6f-d690-453f-ae31-5f4d618a23c3.png)

Steps to reproduce:

1) Open advanced and change the project config to autoSync

``` project : {
       ...
        transport      : {
            load : {
                url : '../_datasets/launch-saas.json'
            },
            sync : {
                url : '../_datasets/save.json'
            }
        },
        ....
        autoSync : true,
        ...
 ,
```

2) Split a task.

**Comment by ExtAnimal** [comment]
@javascript-programming what does `save.json` look like? We don't have it.

**Comment by ExtAnimal** [comment]
It does not reproduce locally on the release branch.

**Comment by canonic-epicure** [comment]
Does not seem to be reproducible
https://github.com/bryntum/support/assets/72431/329936b3-e1bf-4e05-88e9-f72f856d5c47

**Comment by canonic-epicure** [comment]
Closing this one as not reproducuble, @javascript-programming please feel free to re-open with new steps to reproduce.
