### ISSUE TITLE
Events remain hidden after closing EventTooltip on Safari

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5909]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=23485&p=116308#p116308)

Hello,

I have noticed when the EventTooltip is closed, the previously selected event will continue to hide any events which overlap with that previously selected event. I was wondering if this was the intended behavior and if so, is there a way around this so that all events are visible when the EventTooltip is closed? The following screenshots are from the "basic demo" here where I just resized and moved two events into the time range that "Check-In in Hotel" occupies: https://bryntum.com/products/calendar/examples/basic/ !Thanks,
Connor
![before clicking the event](https://forum.bryntum.com/download/file.php?id=20205)
![after closing  EventTooltip](https://forum.bryntum.com/download/file.php?id=20206)

https://user-images.githubusercontent.com/7203098/211709307-66127b9c-492e-4925-ad15-5a29ca9466c2.mov

**Comment by ExtAnimal** [comment]
I cannot reproduce it. I see the movie, but I cannot make one event stay expanded.

**Comment by ExtAnimal** [comment]
OK, the key is the bug platform is Safari.

**Comment by chuckn0rris** [comment]
Not a bug, it is by design. An event will stay on top while it's active (focused). When clicked outside or do any other action to blur, the layout will back to normal.
