### ISSUE TITLE
Filtering new custom columns in Gantt not working

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5919]
[Forum Post](https://forum.bryntum.com/viewtopic.php?f=52&t=23486&p=116320#p116320)

Added a custom example with a custom column (just a simple combo with 3 options), and some data for testing.

The issue is that when using the filter feature, the data is not being filtered correctly (check the video attached).

[inline-data.zip](https://github.com/bryntum/support/files/10392728/inline-data.zip)

https://user-images.githubusercontent.com/16693227/211822432-201a86d4-7d20-459b-ba64-71014be311d8.mp4

**Comment by matsbryntse** [comment]
Misconfiguration in the combo. Data has:

`                    visibility     : 'NAME_ONLY'
`

Combo needs to be defined with this id field as follows:

```
 filterField : {
                    type         : 'combo',
                    multiSelect  : true,
                    editable     : false,
                    valueField   : 'id',
                    displayField : 'name',
                    items        : [{ id : 'NAME_ONLY', name : 'Name only' }]
                }
```
