### ISSUE TITLE
Error when scrolling and then switching to collapsed tree structure

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5927]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23499&p=116367#p116367)

and https://forum.bryntum.com/viewtopic.php?f=43&t=24855&p=123464#p123464

Hi.

We found an issue when using loadInlineData and switching from a long (long enough to scroll down a bit), scrolled down, resource list to tree structure resource list with a collapsed group. In that case, the following error is thrown:

```
schedulerpro.module.js:110337 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at RowManager.jumpToPosition (schedulerpro.module.js:110337:1)
    at RowManager.warpIfNeeded (schedulerpro.module.js:110425:1)
    at RowManager.updateRenderedRows (schedulerpro.module.js:110453:1)
    at SchedulerPro.onGridVerticalScroll [as onGridVerticalScrollNow] (schedulerpro.module.js:117947:1)
    at SchedulerPro.<anonymous> (schedulerpro.module.js:17236:1)
    at SchedulerPro.invoker (schedulerpro.module.js:16543:1)
    at schedulerpro.module.js:16915:1
```

You can find an example to reproduce the issue at **https://github.com/mx-liebald/bryntum-schedulerpro-issues/tree/issues/grouped-scrollable**.
Branch: **issues/grouped-scrollable**.
**See project README for steps to reproduce.**

The error is thrown after calling loadInlineData, in jumpToPosition (RowManager.js) when trying to access the id of record. record was received from store with an invalid index. It seems like the while loop does not check if targetIndex is valid or if the store data is a flat record array or a tree record.

Side note: The example is based on previous issues posted here. See this post for reference.

Regards
Alexander Liebald

**Comment by ExtAnimal** [comment]
Is this reproducible in /`SchedulerPro/examples/bigdataset/` ?

Please post reproduction steps in tickets.

**Comment by marciogurka** [comment]
User added a brief description [here](https://forum.bryntum.com/viewtopic.php?p=123464#p123464) @ExtAnimal

**Comment by taauntik** [comment]
Still reproducible with the repository with 5.3.7

**Comment by taauntik** [comment]
Also reproducible with 5.5.0

**Version A: switching from no group to collapsed group:**
1. Start example
2. Scroll down in resource list
3. Change grouping mode from `all` to `large-group` or `small-group`
4. See console log for error

https://github.com/bryntum/support/assets/75997756/ddd4aebc-63d5-4b8d-9d6a-a66bca85e0df

**Version B: switching from large expanded to small collapsed group:**
1. Start example
2. Set grouping mode to `large-group` and expand group
3. Scroll down in resource list
4. Set grouping mode to `small-group`
5. See console log for error

https://github.com/bryntum/support/assets/75997756/df1d5179-1dd3-4c3d-8c81-8382aeb16f9e

**Comment by isglass** [comment]
Hopefully a better fix this time
