### ISSUE TITLE
API Error being triggered on small resolutions

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5948]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23533&p=116499#p116499)

When using a small screen size (as an example any mobile resolution with developer tools), when reloading the Gantt (can be the basic demo), it triggers an error, check the screenshot

`Uncaught Error: Deprecated API use. Handle size is from CSS`

![Screenshot 2023-01-13 at 13 07 34](https://user-images.githubusercontent.com/16693227/212366460-c3138d47-998e-4b40-a474-733710a813ce.png)

**Comment by matsbryntse** [comment]
Already fixed

**Comment by SergeyMaltsev** [comment]
Duplicate
https://github.com/bryntum/support/issues/5931
