### ISSUE TITLE
Calendar interval wrongly applied on DST period

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5964]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23557&p=116621#p116621)

Hi Bryntum support,

I found nonworking time is incorrect when timezone is America/Santiago.
Maybe, summertime affects the bug.

[How to reproduce]
Set OS timezone to America/Santiago.
Open the advanced demo. https://bryntum.com/products/gantt/examples/advanced/
Execute the code below.

```
gantt.project.calendar.clearIntervals();
gantt.project.calendar.addIntervals({
   "recurrentStartDate": "on Sat",
   "recurrentEndDate": "on Sun",
   "isWorking": false
});

```

[Expected]
Only Saturday is nonworking day

[Observed]
April is nonworking day in addition to Saturday 

Please see the video for details.

			
		
		
				
			 incorrect_working_time.mp4
						(2.47 MiB) Not downloaded yet
		
		
			

Our customer is in big trouble with this bug.
Could you please provide us with a workaround?

**Comment by canonic-epicure** [comment]
Works fine if one uses time in the intervals:
```
gantt.project.calendar.clearIntervals();
gantt.project.calendar.addIntervals({
   "recurrentStartDate": "on Sat at 00:00",
   "recurrentEndDate": "on Sun at 00:00",
   "isWorking": false
});
```
