### ISSUE TITLE
Scroll To Date In RTL not working correctly

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5968]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23570&p=116676#p116676)

"Hi I use scheduler 5.2.7v with angular 14.
After start to try work with "rtl" i found that the "scrollToDate" method not work as expected.

One of my uses is jump to first event when the first event is in the start of the view.
Second is jump to last event when the last event is in the end of the view.

The code that do it is 

```
 goToLast() {
        this.scheduler.scrollToDate((this.scheduler.project.eventStore.getTotalTimeSpan())['endDate'], { block: 'end' });
    }

goToFirst() {
    this.scheduler.scrollToDate((this.scheduler.project.eventStore.getTotalTimeSpan())['startDate'], { block: 'start', animate: false });
}

```

The Result is:
Go to last: the end is in the start of the scheduler.
Go to first: the start is in the end of the scheduler."
![screen-capture.gif](https://forum.bryntum.com/download/file.php?id=20330)

**Comment by yakeer** [comment]
Any plans for this issue?
We want to implement RTL functionality to our Gantt.
