### ISSUE TITLE
[REACT] Error when useEffect and subGridConfigs are set

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6008]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23595&p=116919#p116919)

In the example below, with the subgrid configured like this 

```
subGridConfigs ={{
                    normal: {
                        flex: 1
                    },
                    locked : {
                        // Grid region splitter width has increased. Setting subgrid with 2px smaller.
                        width : 98
                    }
                }}
```
and a simple useEffect like this 

```
 useEffect (()=>{
        setReloadPage(true);
    },[])
```

Triggers and error
`schedulerpro.module.js:18482 Uncaught Error: Id schedulerComponent-lockedSubgrid already in use`

[reLoadResize.zip](https://github.com/bryntum/support/files/10548018/reLoadResize.zip)

**Comment by marciogurka** [comment]
Updated demo with `.env` to avoid eslint build error.
[reLoadResize.zip](https://github.com/bryntum/support/files/10549777/reLoadResize.zip)

**Comment by jsakalos** [comment]
This is not a bug. We have configs which are set when class is instantiated
<img width="888" alt="Screenshot 2023-02-21 at 15 25 17" src="https://user-images.githubusercontent.com/204844/220371802-4ff95f67-fd22-4145-bdd8-81bbea8f3ff7.png">

and we have properties that can be changed at both instantiation time and runtime
<img width="887" alt="Screenshot 2023-02-21 at 15 25 38" src="https://user-images.githubusercontent.com/204844/220372061-42c845d7-719e-42d6-8200-06b9154b149f.png">

In React, the component function runs many times (we cannot prevent this, it's how React works) but we are using same instance of Bryntum component. That results, if not configured properly, in console warnings at least or in crashes at most.

<img width="522" alt="Screenshot 2023-02-21 at 15 20 14" src="https://user-images.githubusercontent.com/204844/220372463-0a61ffe9-0753-4917-8d9f-c59f6ce46712.png">

Setting of `subGridConfigs` on an existing instance results in crash (this can be easily tested on any of our online demos).

The solution is very easy (and should be done for any warnings in console):

```
    const [subGridConfigs] = useState({
        locked: {
            // Grid region splitter width has increased. Setting subgrid with 2px smaller.
            width: 98
        }
    });

    // ...

    <BryntumSchedulerPro
        subGridConfigs={subGridConfigs}
```
```
