### ISSUE TITLE
`ZoomIn`/`ZoomOut` goes to a different location

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6012]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23617&p=116941#p116941)

Hi,

After updating to Bryntum Gantt 5.2.8, the zoomIn/zoomOut feature completely moves the scroll to another location. This occurs when the weekends are hidden.

Steps to reproduce:
Go to advanced example ( https://bryntum.com/products/gantt/examples/advanced/ )
In console, paste the following code to hide Weekends:

```
const oneDayInSeconds = 1000 * 60 * 60 * (24) * 1;
      gantt.timeAxis.filter({
        id: 'hideWeekendFilter',
        filterBy: tick => {
          let weekday = true;
          if ((tick.duration >= oneDayInSeconds && tick.duration <= oneDayInSeconds) && (tick.startDate.getDay() == 6 || tick.startDate.getDay() == 0)) {
              weekday = false;
          }
          return weekday;
        }
      });
```
Try zooming in 2-3 times using either mouse or buttons.
The zoom would go to a different location

Can we maintain the centerDate/mouseFocus in scroll like it was in the previous versions?

Thanks,
Rayudu

**Comment by ExtAnimal** [comment]
🥲🥲🥲 I go to great lengths to attempt to maintain the position under the mouse. Recording the mouse position, date and scroll position in `zoomContext`. And then trying to restore that after the change of ViewPreset.

I have no idea how to fix this. I cannot imagine what could be wrong. I just use the various getFromPosition and positionFromDate APIs to try to keep everything matched up.

I'm going to need some help with this.

**Comment by egraves-accuer** [comment]
It worked fine in 5.2.2.

**Comment by egraves-accuer** [comment]
and 5.2.3
