### ISSUE TITLE
Add renderer method to customize CSS classes for timeline column lines

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6016]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=23616&p=116939#p116939)

Hi,
Is it possible to have custom column timeline styles based on a certain day or hour. There are two classes 'b-column-line' and 'b-column-line-major' which are predefined to differ between days. But what i need is to differentiate this in more granularity. Based on what hour/date/weekday it is, i want to have a different column timeline.

**Comment by MrLightWood** [comment]
I am facing the same need for this feature. Definetely would like to have it implemented
