### ISSUE TITLE
Display events in group header when collapsed

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6042]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23659&p=117162#p117162)

Hi, We have been trying to display the events of the sub-resources whenever the group is collapsed. We tried assigning the events directly to the group's resource ID which ideally seems to be "group-header-GROUP NAME" but it doesn't display the events on the group even though we see the event in the eventStore. 

Is there any way to display the events of the resources in the parent group row when collapsed (instead of using Tree-view) ?

Before Collapsing,

![image (1).png](https://forum.bryntum.com/download/file.php?id=20452)

We would like this to display after collapsing

![image (2).png](https://forum.bryntum.com/download/file.php?id=20453)
![image (1).png](https://forum.bryntum.com/download/file.php?id=20452)
![image (2).png](https://forum.bryntum.com/download/file.php?id=20453)

**Comment by chuckn0rris** [comment]
Another [request](https://forum.bryntum.com/viewtopic.php?f=51&t=27141&p=135466#p135466)

**Comment by matsbryntse** [comment]
Will be implemented in https://github.com/bryntum/support/issues/8384
