### ISSUE TITLE
Add support for adding different core hours times for each day

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6043]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=22243&p=117166#p117166)

Hey,

We are just wondering if it's possible to setup a different set of "core hours" for each day of the week?

We currently have the following config

```
  
  week: {
...
    weekStartDay: 1,
    hourHeight: 70,
    dayStartTime: 6,
    dayEndTime: 18,
    coreHours: {
      start: "10:30",
      end: "16:30",
      overlayDay: true
    },
    fitHours: {
      minHeight: 18
    }
  }
```

This sets the hours at the week level - is it possible to pass in a custom object thats lets us set different start and end times for each day?

Thanks

**Comment by ExtAnimal** [comment]
This could be done with custom linear gradient background on each day:

```
linear-gradient(to bottom,
    var(--core-block-out-color) 0%, var(--core-block-out-color) 30%,
    transparent 30%, transparent 90%,
    var(--core-block-out-color) 90%, var(--core-block-out-color) 100%);
```

Where the %ages are calculated to be the time percentage through the day by the same code that lays out events.
