### ISSUE TITLE
Widget's showAnimation config not working properly

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6058]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23676&p=117240#p117240)

Hi I use angular 14 with scheduler 5.2.8v.

I use the showAnimation feature for add some animation and delay, the config looks like it:

```
  // Create a hover jobs tooltip new format.
        eventTooltip: {
            template: (
                event: {
                    tip: Tooltip,
                    eventRecord: EventModel,
                    startDate: Date,
                    endDate: Date,
                    startText: string,
                    endText: string,
                    startClockHtml: string,
                    endClockHtml: string,
                }) => {
                return `
            ${event.eventRecord.get('name')}
        `;
            },
            floating: true,
            hideOnDelegateChange: true, // Destroy the tooltip every hover source change.
            showAnimation: {
                opacity: {
                    to: 1,
                    duration: '6s',
                    delay: '5s'
                }
            }
        }

```

The animation definition not works.
I create simple demo for show the problem:

Before it works fine what I can do for make it works again?

------------------------------------

You could repro this here https://bryntum.com/products/scheduler/examples/basic

By add this code
```
    features : {
        eventTooltip : {
            showAnimation : {
                to : 1,
                duration : '6s',
                delay : '4s'
            }
        }
    }
```

**Comment by yakeer** [comment]
Any forecast for this issue?
We have clients that are quite nervous about it.

It's a regression from previous versions.

**Comment by yakeer** [comment]
@matsbryntse 
Could you please check out this issue?
It would really help us.
