### ISSUE TITLE
Update code inside onEditComplete at Editor class

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6061]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=23683&p=117267#p117267)

"In the Editor class, exists the function onEditComplete, with set the value to the column field. In this function has a check, if the field has a colon in the name, to complex field name, but the function used to fill the value is the "set" function, of the record, and to work as expected must be the "setPath" of ObjectHelper, this can be changed in the next release?"

**Comment by marciogurka** [comment]
The suggestion is to change the line located at `Core/lib/Core/widget/Editor.js`

```
else if (dataField.includes('.')) {
    record.set(dataField, value);
}
```

to use the `setPath` method that is available at `Core/lib/Core/helper/util/Objects.js`

```
/**
     * Sets value for a given path in the object
     * @param {Object} object Target object
     * @param {String} path Dot-separated path, e.g. 'object.childObject.someKey'
     * @param {*} value Value for a given path
     * @returns {Object} Returns passed object
     */
    static setPath(object, path, value) {
```

So the new code would look something like this

```
ObjectHelper.setPath(...);
```

**Comment by henriquewerlang** [comment]
News about this?

**Comment by matsbryntse** [comment]
@henriquewerlang Is this working for you in the latest release? The code lines mentioned above no longer exist. If still reproducible, can you please provide us a simple test case showing the problem?
