### ISSUE TITLE
Time spans disappear when timeline date range changes

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6063]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23690&p=117299#p117299)

"Hello!

Here's how to replicate:

 Load the [time span demo](https://www.bryntum.com/products/gantt/examples/highlight-time-spans/)
 From the console, add a timespan early in the Gantt so you see a timespan appear:

```
gantt.highlightTimeSpans([{name: 'test', startDate: new Date(2019, 0, 1), endDate: new Date(2019, 0, 3) }])

```
 Right click on the timeline, date range
 Click on the right arrow until the timespan is no longer visible
 Click on the left arrow until the timespan comes back into view
  The timespan is not visible anymore.

A workaround is to call highlightTimeSpans() every time the timeline date range changes. A bit inefficient though."

**Comment by matsbryntse** [comment]
Fixed for 5.3
