### ISSUE TITLE
Incorrect rendering of a timeaxis when forceFit enabled

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6064]
Goto https://bryntum.com/products/schedulerpro/examples/inline-data/

Try to zoom out

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23688&p=117295#p117295)

https://user-images.githubusercontent.com/7203098/214999635-217cf3ac-4944-4b92-bfb8-3f10626c3153.mov

**Comment by marciogurka** [comment]
User added a [new comment](https://forum.bryntum.com/viewtopic.php?p=117770#p117770) when the `forceFit` option is not enabled
