### ISSUE TITLE
[VueJS] [Calendar] Calendar Drag: resourceId property doesn't update properly.

### ISSUE THREAD

**Issue by dcruz1990** [bryntum/support#6072]
Im looking in the documentation: 
![image](https://user-images.githubusercontent.com/43586145/215158070-f66dc7bf-1f51-4ff0-96fd-d5cb91d767ee.png)
And inside the `eventRecord` object we get the actual and the old data, but in my case it returns empty.. any idea?
![image](https://user-images.githubusercontent.com/43586145/215158736-475cae67-24df-479e-9804-b15a45f4e6f2.png)
I'm just trying to put new info in the events when the drag event ends.

**Comment by matsbryntse** [comment]
Can you please share a snippet showing the code you use that produce the wrong output?

**Comment by dcruz1990** [comment]
I'm just using the component wrapper as follows:

```javascript
<calendar
          v-if="showing"
          ref="calendar"
          class="h-100"
          :date="calendarDate"
          :tbar="tbar"
          :modes="modes"
          :events="calendarEvents"
          :resources="calendarResources"
          :sidebar="false"
          :listeners="listeners"
          :eventTooltipFeature="eventTooltipFeature"
          :dragFeature="dragFeature"
        />
```
Then, i have the listeners:
```javascript
listeners: {
         dragResizeEnd: this.dragMoveResizeEnd
      },
```
Finally, i have the function declared like this:
```javascript
async dragMoveResizeEnd({ eventRecord }) {
     console.log(eventRecord);
    }
```
Everything looks pretty normal i think..

**Comment by dcruz1990** [comment]
Well, the issue itself is that the `resourceId` property that i get is the source, not the destination.

**Comment by dcruz1990** [comment]
It comes inside `view` object, closing now.
