### ISSUE TITLE
When compactMode is enabled `align: right` doesn't work

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6079]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23715&p=117408#p117408)

Hi,

Is it intentional or a bug that the Column's align: 'right' -property doesn't work, when Grid's FilterBar compact-mode is enabled?

https://www.bryntum.com/products/grid/examples/filterbar/
Modify the Age-columns config -> align: 'right'

```
{ text : 'Age', field : 'age', width : 100, type : 'number', align: 'right' }
```
Toggle on the compact-mode
The "AGE" text is on left instead of right
![1.png](https://forum.bryntum.com/download/file.php?id=20522)

**Comment by matsbryntse** [comment]
Fixed in 6.0
