### ISSUE TITLE
Checkbox columns are always unchecked in exported PDF

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6086]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23724&p=117445#p117445)

Here http://lh/release/bryntum-suite/gantt/examples/export/
add checkcolumn
```
        { field : 'active', text : 'Active', type: 'check' },
```

Check few rows and export to PDF. See nothing selected.

**Comment by chuckn0rris** [comment]
Another [request ](https://forum.bryntum.com/viewtopic.php?f=52&t=23741&p=117527#p117527)

**Comment by kollster** [comment]
Do you have an E.T.A. on this issue?

**Comment by Mhbuur** [comment]
@chuckn0rris @matsbryntse please see https://github.com/bryntum/support/issues/6083 for a fully qualified reproduce example. 
Can you say anything about an ETA for a fix?
