### ISSUE TITLE
Resource filter not respected on initial loading

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6093]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=23755&p=117590#p117590)

"Hello,

I am running into an issue with the ResourceFilter; it seems that adding events to the EventStore via an async function is causing the events to all display, regardless of whether or not the resource(s) they are associated with are selected. An example of this behavior can be found here: [https://codepen.io/connor-veeva/pen/ExpOEEg?editors=0010](https://codepen.io/connor-veeva/pen/ExpOEEg?editors=0010), where I'd only like the events for one of these resources to display, but all are visible until the checkbox is manually toggled.

Let me know if there's any more information I could provide, any help would be appreciated."

**Comment by marciogurka** [comment]
The user [updated](https://forum.bryntum.com/viewtopic.php?p=117665#p117665) the test case

> That looks like it fixes the initial case, but when I remove the other resource from the resourceFilter's initially selected values, the problem persists; ie. if there are supposed to be no resource events displaying, it displays them all anyways. I updated the codepen to display this issue. Let me know if there's anything else I'm missing.

**Comment by annheslin** [comment]
Hi @marciogurka - do you think you'll be able to prioritize a fix for this? 
In our, situation Users will often unselect their external calendars (that we are showing in the ResourceFilter), which will cause ALL the external resource events display on the next page load.
