### ISSUE TITLE
`ScheduleContext` feature cannot be disabled

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6109]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23758&p=117791#p117791)

You could reproduce it with our online scheduler basic demo
by adding this to the code
```
    features : {
        scheduleContext : {
            disabled : false,
            triggerEvent : 'hover',
            renderer     : (context, element) => {
                element.innerText = '😎';
            }
        }
    },
    tbar : [
        {
            type : 'button',
            text : 'deselect',
            onAction : ({ source : { parent : { parent : scheduler } } }) => {
                scheduler.features.scheduleContext.disabled = true;
            }
        }
    ],
```

And Here are the steps to reproduce

https://user-images.githubusercontent.com/75997756/216906588-5e7d33ae-ffc6-4687-bfdd-d0b27073cd54.mp4

### Consider making `clearContext` public

**Comment by pjc2007** [comment]
In my case, I would like this to still be "enabled", but just clear it ("unselect it") in code.

**Comment by pjc2007** [comment]
OK, thanks for that. I added a small comment to the issue

In my case, I would like this to still be "enabled", but just clear it ("unselect it") in code.

i.e. I want to clear it, but the next time we click a cell, it will still add the highlight

**Comment by taauntik** [comment]
@pjc2007 to achieve this you could use `scheduler.features.scheduleContext.clearContext();`
But it's a private method, I've added to make it public. As `clearContext` is private, the name might change

![chrome_oKTmkP5wTb](https://user-images.githubusercontent.com/75997756/216912549-953c49d7-9e37-4dec-98db-91227e06f16a.gif)
