### ISSUE TITLE
`store.load()` doesn't work if TreeGroup feature used

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6120]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=23812&p=117865#p117865)

If we disable autoLoad, and after call tree.store.load(), data not loaded

You can check it on your example https://bryntum.com/products/grid/examples/tree-grouping/

**Comment by isglass** [comment]
`tree.store` points to the transient "display store". Original store is `tree.features.treeGroup.originalStore`, but that is private. We should offer a public way of reaching it

Meanwhile, store `tree.store` in a var before grouping, and call load on that

**Comment by xiregroup** [comment]
Hello
When will it be decided? We can't work properly

**Comment by matsbryntse** [comment]
Did you try using the workaround (keep the original store in a variable)?
