### ISSUE TITLE
ScrollTo functionality does not work with infinitescroll enabled

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6132]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=23825&p=117946#p117946)

Hi,
We are trying to use the scroll functionality and are noticing som strange behaviour.  At first we occasionally noticed that the scrollTo functionality is not scrolling all the way to the event.

After some investigation we have narrowed it down to be related to the use of infinite scroll.
If the event passed to the scroll method is outside of the loaded view the problem occurs. 

Managed to reproduce the issue in:
https://bryntum.com/products/scheduler/examples/scrollto/
-> Add infinite scroll to the scheduler config 
-> editing the start/end days of Event-1 to a few years from now 
-> then choose Event-1 in the scroll to dropdown.

The scheduler does not scroll all the way and the promise from the scrollmethod does not resolve 

Tested with: scrollEventIntoView  & scrollResourceEventIntoView

Here is the video of reproduction

https://user-images.githubusercontent.com/75997756/217526016-a32ec97c-232d-4e76-92e6-650f35d00d35.mp4

**Comment by matsbryntse** [comment]
Test added to 6132-scroll
