### ISSUE TITLE
Crash when dragging events between two schedulers

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6133]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23823&p=117960#p117960)

Hello Bryntum Team,

I have a problem with configuring Bryntum dragging between schedulers using https://bryntum.com/products/scheduler/examples/drag-between-schedulers/ as an example. But after drag ends it throws error in console:
```
ERROR Error: Uncaught (in promise): TypeError: record.instanceMeta is not a function
TypeError: record.instanceMeta is not a function
    at SchedulerPro.isInTimeAxis (schedulerpro.module.js:173407:20)
    at schedulerpro.module.js:154121:36
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new ZoneAwarePromise (zone.js:1429:21)
    at asyncToGenerator.js:19:12
    at EventDrag.updateAssignments (schedulerpro.module.js:154187:6)
    at schedulerpro.module.js:153802:25
    at resolvePromise (zone.js:1211:31)
    at zone.js:1118:17
    at zone.js:1134:33
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:24313:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at core.mjs:23999:55
```

After some debugging it looks like isInTimeAxis function gets record's id as value instead of reference to dragged record and this is done in:
```
// Pro Engine does not seem to handle having the event already in place on the copied assignment,
// replacing it with id to have events bucket properly set up on commit
if (newAssignment.event) {
  newAssignment.event = newAssignment.event.id;
  newAssignment.resource = newAssignment.resource.id;
}
```

Not sure if i'm doing something wrong?
Also here is drag configuration:
```
eventDrag: {
	showTooltip: false,
	constrainDragToTimeSlot: true,
	constrainDragToTimeline: false
}
```

**Comment by jsakalos** [comment]
To reproduce:
1. unzip [drag-between-schedulers.zip](https://github.com/bryntum/support/files/10698835/drag-between-schedulers.zip) to `SchedulerPro/examples` and then run it. 
2. drag an event from the bottom scheduler to the top one
3. it crashes:
<img width="1017" alt="Screenshot 2023-02-09 at 16 38 14" src="https://user-images.githubusercontent.com/204844/217862209-322235ca-ef5c-4a5d-b9a4-f7f2513f997c.png">

Note: The content of `app.js` is copy & paste from Scheduler examples adjusted to use SchedulerPro.
