### ISSUE TITLE
Buffer time renderer, allowing change of text, color and icon

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6136]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23838&p=117975#p117975)

"Hi team,
I have to change the color and Icon of buffer time of the event based on the each event object array.
How can I change this dynamically based on the event object?"
![Screenshot 2023-02-08 at 10.02.27 PM.png](https://forum.bryntum.com/download/file.php?id=20699)

**Comment by ShoppasRR** [comment]
Have you found a way to dynamically change the content or style of event buffer? I am wanting to change the color based on a time threshold.
