### ISSUE TITLE
Drag between Schedulers Pro does not work

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#6143]
To reproduce:
1. unzip [drag-between-schedulers.zip](https://github.com/bryntum/support/files/10698835/drag-between-schedulers.zip) to `SchedulerPro/examples` and then run it. 
2. drag an event from the bottom scheduler to the top one
3. it crashes:
<img width="1017" alt="Screenshot 2023-02-09 at 16 38 14" src="https://user-images.githubusercontent.com/204844/217862209-322235ca-ef5c-4a5d-b9a4-f7f2513f997c.png">

Note: The content of `app.js` is copy & paste from Scheduler examples adjusted to use SchedulerPro.

**Comment by matsbryntse** [comment]
Dupe #6133

**Comment by jsakalos** [comment]
Closing as duplicate
