### ISSUE TITLE
StartDateColumn shows error on MM/DD/YYYY

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6168]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23872&p=118185#p118185)

Hi,

Are there any recent changes in the supported date format for Gantt? Before this release, MM/DD/YYYY format was allowed and now it is throwing errors.

![Screenshot 2023-02-14 at 1.44.40 PM.png](https://forum.bryntum.com/download/file.php?id=20750)

**Comment by ExtAnimal** [comment]
SchedulerPro onwards (Gantt) use strict date parsing. Don't know why.

https://github.com/bryntum/bryntum-suite/pull/6391/files#diff-d2613fde9d79570ebcb5bf8ed7428a2cb9be261627059f52ced5a924b936f12dR60

@canonic-epicure added the flag.
