### ISSUE TITLE
`EventSelection`'s `isEventSelectable` not called by Calendar's `EventSelection` mixin

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#6177]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=23881)

**Comment by dcruz1990** [comment]
Also, when using `beforeEventSelectionChange()` listener, i access to the event but get undefined in the selection:
![image](https://user-images.githubusercontent.com/43586145/219060763-01d3d2c1-d137-41a2-8898-3d1a65a94811.png)
, even returning false in that listener it doesn't prevent the event to be selected. 

If i put a `debugger;` until return false, it works.
