### ISSUE TITLE
Unwanted focus on column header while scrolling

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6203]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23917&p=118369#p118369)

Hello Bryntum Team!
We encountered an issue when selecting one of resource elements, then scrolling makes focus on the header of the selected resource column.
Reproduced on: https://codepen.io/jan-veovo/pen/JjBqMZY
Video: https://streamable.com/7qnlwe

Also it's reproducible here https://bryntum.com/products/scheduler/examples/bigdataset/

**Comment by dkornel** [comment]
Any update on this ticket ? The video was archived and is not available, do you still need it ?

**Comment by isglass** [comment]
@dkornel This is the intended behavior, please see animals response in the forum
