### ISSUE TITLE
insertChild with silent = true raised update event

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6204]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23919&p=118371#p118371)

Hi,

if you do

```
gantt.taskStore.rootNode.insertChild({ name: 'New task' }, true);
```

the update event of the taskStore is raised. Why is this the case?

Thanks,
Matt

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/2471
