### ISSUE TITLE
Adding a task and drawing a dependency breaks undo/redo

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6209]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=23923&p=118396#p118396)

"Hello

We've found a weird bug. Creating a task in SchedulerPro, and afterwards just checking if a dependecy is valid through dragging dependency, undoing the task and redoing it, breaks the scheduler. See attached video.

Code is attached and the example used is this:
https://bryntum.com/products/schedulerpro/examples-scheduler/undoredo/

	
We've located the fault in the code on version 5.2.10:
File SchedulerProProjectMixin.ts on line 278 in function isDependencyCyclic:

```
const branch            = this.replica.branch({ autoCommit : false, onComputationCycle : 'throw' })
```

When this is called the redoing of an undo on create task fails. If we don't check for isDependencyCyclic then undo/redo works fine."

![undo_redo_draw_dependency_bug.gif](https://forum.bryntum.com/download/file.php?id=20808)

[adding_task_and_drawing_dependency_breaks_undoredo.txt](https://github.com/bryntum/support/files/10768185/adding_task_and_drawing_dependency_breaks_undoredo.txt)

**Comment by marciogurka** [comment]
User added a side note [here](https://forum.bryntum.com/viewtopic.php?p=119139#p119139)

**Comment by canonic-epicure** [comment]
Seems its not reproducible?

https://user-images.githubusercontent.com/72431/230379379-a8806f16-28e2-4b6e-a911-6fb17a0dbd96.mp4

**Comment by canonic-epicure** [comment]
Closing this one as not reproducible. Please feel free to re-open with more detailed steps to reproduce.
