### ISSUE TITLE
Hover styling broken in 3d-bars demo

### ISSUE THREAD

**Issue by isglass** [bryntum/support#621]
If not fixable in 10 min, remove demo until fixed
<img width="420" alt="Screenshot 2020-04-29 at 14 47 33" src="https://user-images.githubusercontent.com/5415653/80597638-65d4ef00-8a28-11ea-8ac0-e78899daeeea.png">

**Comment by jsakalos** [comment]
Closed as a duplicate of https://github.com/bryntum/support/issues/1050
