### ISSUE TITLE
Sync not fired when edit Milestone

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6214]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23106&p=118349#p118349)

Steps: 
Right click in first task -> Add -> Milestone. See `sync` request in Network tab.
Right click on Milestone -> Add -> Subtask. See `sync` request in Network tab.
Double click on new created Subtask, edit name in TaskEditor, Save. See **no** `sync` request in Network tab.

Apps for reproduce. Simple server and very simple React app. 
To run server: `npm i && node index.js`
To run app: `npm i && npm run start`
[nodejs_sample (1).zip](https://github.com/bryntum/support/files/10776457/nodejs_sample.1.zip)
[gantt_chart_reactjs (1).zip](https://github.com/bryntum/support/files/10776458/gantt_chart_reactjs.1.zip)

**Comment by isglass** [comment]
Sync response for new tasks has to include a proper id, otherwise they will continue to be considered added, and changes will lead to another add instead of an update.

For example ```
if(req.body.tasks && req.body.tasks.added) {
      rows_tasks = req.body.tasks.added;
      rows_tasks.forEach(taskData => {
            taskData.id = idCounter++;
      });
  }```

**Comment by chuckn0rris** [comment]
No repro after id fix. Closing
