### ISSUE TITLE
Client-side PDF export using browser Print feature

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6218]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=118440#p118440)

**Comment by yakeer** [comment]
We would use this feature as well.
Currently we're encountering multiple bugs with printing.
We're still trying to figure out the source of the issue.

**Comment by Mhbuur** [comment]
We are interested in this feature as well. The current print server solution is not a viable way for us to go, mainly due to concerns about its complexity and possible security issues.

A client side PDF export (not via the browser print dialog) could also work.

**Comment by matsbryntse** [comment]
A full client-side PDF generating (not using print dialog) is far away, as there's no known way to solve it. 

We have a nice looking print feature, which is almost done - so you can simply use Save as PDF in the print dialog to get a clean PDF.

**Comment by Mhbuur** [comment]
Thanks, that sounds interesting. 

As such is not imperative that the solution _does not_ use the print dialog - we did look into the "Save as PDF" via the print dialog too, but concluded that there was too much left for the end user to work out in order to get a useful output.

On the other hand, the pure JS PDF generating solutions we looked into, seem to render the dom to an image and stuff that into the PDF, which is not optimal for several reasons, mainly quality loss when scaled up.

If you have an early preview available somewhere, I'd like to check it out :-)

**Comment by matsbryntse** [comment]
It should not be too long now actually, so keep an eye out on our nightly builds after this ticket is marked as *Resolved*

**Comment by yakeer** [comment]
We have a license. And we would love to experiment it.we have high demand for it.

**Comment by bmblb** [comment]
@yakeer @Mhbuur could you please send me a message to maxim at bryntum.com so I could send you a download link once we make a preview build

**Comment by kollster** [comment]
@bmblb Could we get a status update regarding this issue? Has a nightly or preview build containing the feature been made available?

**Comment by bmblb** [comment]
PR is being reviewed. Should be merged in the next couple days. Then it will be available in the master branch nightly build (5.6.0)

**Comment by kollster** [comment]
Okay, sounds great👍Looking forward to it.

**Comment by bmblb** [comment]
PR has been merged to master branch, feel free to try next nightly build for 5.6.0

**Comment by Aarbel** [comment]
@bmblb have you made tests with very large datasets for this feature ?

(big tasks list, and big time range)

**Comment by bmblb** [comment]
@Aarbel how large dataset are we talking about? how many pages? how many records? what is the expected length of a timespan and in which preset? 
Our tests mostly cover logic of splitting to pages and checking that content is not lost.
