### ISSUE TITLE
[Gantt] Wrong data when sorting Columns (due to custom renderer ?)

### ISSUE THREAD

**Issue by davidavz** [bryntum/support#6253]
Hi there 👋 

I'm using the React Gantt component and I have 2 columns (start_date, end_date) that use a custom renderer function to display their data.
Everything works well but when I sort these columns, it gets a little bit messy and the data is not consistent anymore. The empty cells get filled with random data (from the previous row I guess)

Here is a video of what is happening (I can send you a .zip example if needed) : 

https://user-images.githubusercontent.com/6774576/221197952-dd73872c-f716-448e-ba2d-f23c0acc9d1d.mov

**Comment by matsbryntse** [comment]
A ZIP test case uploaded here would help debugging yes. What version are you on?

**Comment by matsbryntse** [comment]
Also make sure your renderer functions always returns a string in all paths ('' if cell should be empty)

**Comment by davidavz** [comment]
I was returning `undefined`, switching to an empty string definitely fix it! 🥳 

Thanks a lot 👍

**Comment by matsbryntse** [comment]
Anytime, have a great weekend!
