### ISSUE TITLE
Should be possible to add barMargin to only one side top or bottom 

### ISSUE THREAD

**Issue by gudzdanil** [bryntum/support#6257]
Scheduler Pro

Make it possible to configure bottom space(padding) in event cell so that users can use this space for "click to create" and for cell context menu.
Without this feature if there are 2 events in a cell then it is not possible to create more events in this cell by context menu

Example picture of expected result:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/8312145/221533866-374ae1dc-e200-4b23-8449-166d1e166a96.png">

**Comment by gudzdanil** [comment]
I've tried to patch Row class by overriding `height` getter, it works to create that space in the bottom but it breaks "virtual scroll"

**Comment by matsbryntse** [comment]
You can achieve this with the https://bryntum.com/products/scheduler/docs/api/Scheduler/view/mixin/SchedulerEventRendering#config-resourceMargin setting on the scheduler.

**Comment by gudzdanil** [comment]
> You can achieve this with the https://bryntum.com/products/scheduler/docs/api/Scheduler/view/mixin/SchedulerEventRendering#config-resourceMargin setting on the scheduler.

umm.. how is that possible to archieve? If I need 15px bottom margin for example? I have in the application sliders to tweak both resourceMargin and barMargin and none of those can do an expected result. Symmetrical margin on top "eats" too much usefull space on screen, when you have 50+ resource and lots of events for each resource on each day on fillTicks=true mode

**Comment by ExtAnimal** [comment]
I seem to remember a recent request for asymmetric `barMargin`. I thought that a ticket had been created from it.

Meaning that the `barMargin` value may either be a number, *or* an object of the form :

```
{
    top    : 10,
    bottom : 20
}
```

This should be easy to achieve. Would that enable the required result?

**Comment by gudzdanil** [comment]
@ExtAnimal that would. But as I understand it's not implemented yet?

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/6185
