### ISSUE TITLE
Drag proxy not aligned under cursor when dragging overlapping event

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6261]
https://user-images.githubusercontent.com/218570/221562979-d3beaf68-a411-4f56-8717-37845161bfff.mov

**Comment by ExtAnimal** [comment]
I don't think that the dragging event bar should be layed out in the same way as real events. In particular, it should start at inset-inline-start : 0 and be 100% width.

So this code may need to do something different with `eventInset` and `eventWidth`:

![Screenshot 2023-02-27 at 13 37 25](https://user-images.githubusercontent.com/200516/221565725-1591e8f9-ad8b-43e3-b672-97794430ad3f.png)

There may be a reason those values were used, but I can't see it always being valid.

**Comment by dongryphon** [comment]
I am not seeing that issue - see below. What browser are you using? (Linux Chromium here)

To @ExtAnimal 's comment: the event maintains its size/placement during drag primarily for up/down movement as shown in video. Happy to discuss what the horizontal placement rules should be if not these.

https://user-images.githubusercontent.com/722969/224504115-4be6a61d-a52f-48e8-b36f-a58aa34c983c.mp4

**Comment by dongryphon** [comment]
Tested locally and [on the web site](https://bryntum.com/products/calendar/examples/basic/)

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/support/issues/2113

**Comment by matsbryntse** [comment]
> I don't think that the dragging event bar should be layed out in the same way as real events. In particular, it should start at inset-inline-start : 0 and be 100% width.

Agree with this, same Apple does in its calendar

**Comment by dongryphon** [comment]
https://github.com/bryntum/support/assets/722969/80af727a-32fc-4445-9dbf-56eda39f855b
