### ISSUE TITLE
 ApplyChangeset On Event Store Not Change Custom Fields

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6268]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24008&p=118850#p118850)

"Hi I use scheduler 5.2.10 with angular 14.

I found that the event store applyChangeset not change the custom fields that was added to event model.
If I use the "=" operator works fine.

My project definitions:

1) Custom class definition:

```

export class MyEventClass extends EventModel {
    static get $name() {
        return 'MyEventClass';
    }

isChanged: boolean;
someObject: { isChanged: boolean };


// Add my new fields.
static get fields() {
    return [
        { name: 'isChanged', type: 'boolean' },

        { name: 'someObject', convert: value => value as { isChanged: boolean } }
    ];
}
}
```

2) Project definition:

```
    project: {
        eventStore: {
            modelClass: MyEventClass
        }
    },

```

All my event initialized like this:

```
{
            resourceId: 'r1',
            startDate: new Date(2017, 0, 1, 10),
            endDate: new Date(2017, 0, 1, 12),
            name: 'Click me',
            iconCls: 'b-fa b-fa-mouse-pointer',
            isChanged: false,
            someObject: { isChanged:false }

    },

```
The custom fields is false.

Then when I click to update button I change the fields to true like this:

```
 chengeAllEvents() {

    const newEvents = this.schedulerConfig.events.map((event: Partial<MyEventClass>) => {
        const item = { ...event };
        item.isChanged = true;
        item.someObject.isChanged = true;
        return item;
    });
    this.scheduler.project.eventStore.applyChangeset({
        updated: newEvents
    });

```
And after check found that this fields still with false values.

I create simple demo that reproduce the problem.

How to reproduce:
1) click on some event and in the console you will see the current values:
![firstclick.png](https://forum.bryntum.com/download/file.php?id=20928) 

2) Click on update button and in the console you will see the data that enter to update:
![update.png](https://forum.bryntum.com/download/file.php?id=20926)

3) Click on the same event and in the console you will see that the values not changed.:
![secondclick.png](https://forum.bryntum.com/download/file.php?id=20927)

"

[angular14-5.2.10.zip](https://github.com/bryntum/support/files/10843082/angular14-5.2.10.zip)

**Comment by yakeer** [comment]
Any update on this?

**Comment by canonic-epicure** [comment]
It seems this issue is caused by the absence of the `type` on the custom `someObject` field. If you set it to `object`, it will work correctly:
```
{ name: 'someObject', type : 'object', convert: value => value as { isChanged: boolean } }
```

We'll fix this, in the meantime, please apply the workaround above. 

Note, that with [`object`](https://bryntum.com/products/schedulerpro/docs/api/Core/data/field/ObjectDataField) type, the changes will be applied "inside" of the `someObject`'s object and will not replace the object instance itself. So if you'll need to delete some key, you might need to provide it with `null` value.
