### ISSUE TITLE
Unified drag initial animation is slow

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#627]
Reproducible on dragselection demo https://www.bryntum.com/examples/scheduler/dragselection/
Enable unified drag, select 5-6 event, try to drag them. Animation is far from smooth
![laggy drag](https://user-images.githubusercontent.com/45400762/80598831-96ba2180-8a32-11ea-9101-9cfa9ff37525.gif)

**Comment by matsbryntse** [comment]
Seems ok now
