### ISSUE TITLE
[Angular] IVY based Angular wrappers 

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#6270]
Create new IVY based Angular package or decide to update existing.

**Comment by eliraneliassy** [comment]
@SergeyMaltsev 
I know that you folks are working on it.
Just want to give another side effect that might be crucial.

Given the fact that this PR was approved already:
https://github.com/angular/angular/pull/49101

This issue is dramatically necessary for Angular v16 migration. 

FYI

**Comment by SergeyMaltsev** [comment]
@harellevy it is almost ready, please wait for the next patch `5.3.3` release. Release is scheduled for the next week.
