### ISSUE TITLE
Gantt docs links to non-existing "Displaying data" guide

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6285]
https://bryntum.com/products/gantt/docs/guide/Core/data/storebasics

> 
>This guide shows how to manage records in a Store, for example how to retrieve records and how to sort or filter the store. >It assumes you have read the "Displaying data" guide, which has info on how to create a Store, populate it with data and >how to use it with your grid.

**Comment by khattakdev** [comment]
This issue no longer exist.
