### ISSUE TITLE
Multi event drag produces invalid results

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#6293]
![Screenshot 2023-03-03 at 09 14 09](https://user-images.githubusercontent.com/200516/222667457-8b0493b2-b25c-49ea-a6a7-c76b82f5bcda.png)

The multi event drag behaviour is inconsistent *by design*. Because of variable row height the actual action triggered by the mouseup is not clear to a user.

But it's worse than that. It renders the events outside of the resource bounds, so the user cannot know wha is happening.

**Comment by isglass** [comment]
Requires dragging multiple times to reproduce
