### ISSUE TITLE
Undo actions doesn't add info to crudManager "changes" array

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6305]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=23909&p=119229#p119229)

"I have included in the drag-from-grid example a basic implementation of the STM listeners, and I can confirm that when I Undo the Drag, there is no crudManager changes"

"If I try to unassign an event I just dragged, there is no crud changes either.

Also, if I try to unassign an event I just dragged from the grid, the action doesn't work and the "scheduleEvent" function returns an error."

[drag-from-grid-with-stm-listener.zip](https://github.com/bryntum/support/files/10885361/drag-from-grid-with-stm-listener.zip)

https://user-images.githubusercontent.com/16693227/222804693-c2f9116c-8ea6-46c5-b7a3-30685e1122ad.mp4

https://user-images.githubusercontent.com/16693227/222804699-637b9c15-f696-45d7-afd6-992da1ee15da.mp4

https://user-images.githubusercontent.com/16693227/222804704-b2079522-833d-4df5-b717-9a3f01a2050c.mp4

**Comment by canonic-epicure** [comment]
https://user-images.githubusercontent.com/72431/236384929-a564f22b-321b-4687-8472-508997bb3c8a.mp4

**Comment by canonic-epicure** [comment]
See the forum thread, not reproducible in the latest code.
