### ISSUE TITLE
CellMenu feature could be configured to show outside of row range

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#6316]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=24091)

![Screenshot 2023-03-07 at 08 36 04](https://user-images.githubusercontent.com/200516/223355384-ef092899-bb9c-4fa7-a63f-97420d4bf42b.png)

If the `data` is null, this means there's no cell. If configured with some option, it could continue to show the menu.

**Comment by henriquewerlang** [comment]
Any news about this issue?

**Comment by matsbryntse** [comment]
Dupe #4262
