### ISSUE TITLE
`effortDriven` + fixed duration not working when setting it in the data level initially

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6320]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24118&p=119408#p119408)

we are using on a task these settings:

```
"id"          : 11,
                                "name"        : "10 CAM",
                                "percentDone" : 50,
                                "startDate"   : "2019-01-14",
                                "rollup"      : true,
                                "duration"    : 10,
                                "effort"      : 1000,
                                "effortDriven": true,
                                "ignoreResourceCalendar":true,
                                "schedulingMode":"FixedDuration",
```

as adviced by arcady setting effortDrive:true + schedulingMode:FixedDuration should not change anything in duration + effort of the task. But the effort is recalculated as you can see from the screenshot (we are using your advanced example).
When updating the task with an effort of 1000 it works, so the problem is the initial reading/setting.
We need a robust setting to set keep duration + effort untouched for that specific task
![fixed-1.jpg](https://forum.bryntum.com/download/file.php?id=21095)
![fixed-2.jpg](https://forum.bryntum.com/download/file.php?id=21094)

**Comment by arcady-zherdev** [comment]
Happens only when endDate is not provided
