### ISSUE TITLE
Built in `DateField` validation not working properly

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6321]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24121&p=119421#p119421)

Hi

We are using the DateField widget as a component. 

Currently it is possible to enter a date of 55/27/2023 and not get any invalid date message (as it fulfills the date format, presumably). When we try to check and parse the value ourselves onAction, the value does not appear to be an incorrect date as it has been changed through the built in Bryntum validation to a valid (but unintended) date (in this example, it was changed to 24/04/2025). 

What is the best way to amend / add our own validation on top of the built-in Bryntum date validation that occurs on input to fix this type of issue? 

Thanks.

```
<BryntumDateField
      :width="150"
      :height="30"
      :format="'DD/MM/YYYY"
      :value="newDate"
      :strict-parsing="true"
      @action="newDate = $event.value"
    />
```

Reproducible with vanilla js

https://user-images.githubusercontent.com/75997756/223631559-0acc0821-f04b-4f99-b292-14539531ffd6.mp4

code I used to repro
```
    tbar : [
        {
            type : 'datefield',
            format : 'DD/MM/YYYY',
            onAction : event => {
                const res = DateHelper.format(event.value, 'DD/MM/YYYY');
                console.log(res);
            }
        }
    ]
```

**Comment by ExtAnimal** [comment]
I suggest a universal date parsing method. I did this at my previous job before Sencha.

Basically, all you need to configure is the desired *order*: `DMY`, `YMD`, or the bizarre outlier, `MDY`.

With this information, the *ingestion* of dates can be flexible. You can use any delimiter character, space or `-` or `.`. You can use text for the month which can be matched, case insensitive to the first characters of locale month names, or use a numeric month. The individual user can use what she is conformable with

When I wrote this flexible parser, you could also type things like `+10` which means ten days from today.

And you could configure textual abbreviations to functions which would yield certain results, eg `'nm' : () => nextMonth()`

**Comment by TanyaJRB** [comment]
@ExtAnimal This approach would be significantly better and avoid a lot of validation errors, since all that really matters is the order.

**Comment by TanyaJRB** [comment]
Just following up on this - do we know when this might be resolved?
