### ISSUE TITLE
Prevent checkbox column to be scrolled out of view

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#6331]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=119505#p119505)

You should be able to configure a Grid with

```
    selectionMode : {
        checkbox : {
            region : 'checkbox'
        }
    },

...

    subGridConfigs : {
        checkbox : {
            splitterElement : null
        },
        locked : {
            flex : 3
        },
        normal : {
            flex : 4
        }
    }
```

And have that create its own `SubGrid` at initialization time. Doing this actually throws an error.

Also, a SubGrid ignores `splitterElement : null`. It *always* creates a splitter to make itself user-resizable. This must be configurable.

Also, dynamic creation of `SubGrid`s based on changes to a column's region should honour the named sub grid's configuration

![Screenshot 2023-03-09 at 07 51 09](https://user-images.githubusercontent.com/200516/223943283-66341d1c-e17f-4888-b867-658166b0dd22.png)

So the above code should be

```
me.add(toAdd.map(region => me.createSubGrid(region, me.subGridConfigs[region])));
```

**Comment by isglass** [comment]
There is no public config `splitterElement`. Try `resizable: false` instead
