### ISSUE TITLE
Events empty after scrolling 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6343]
https://bryntum.com/products/scheduler/examples/frameworks/react/javascript/react-events/build/
edit an event
scroll max right
scroll back
events blank

<img width="870" alt="Screenshot 2023-03-10 at 09 30 01" src="https://user-images.githubusercontent.com/218570/224264500-050ca647-f483-4bd9-8e94-49439a31a019.png">

**Comment by jsakalos** [comment]
The events' content also disappears on changing zoom level, which is probably the simplest way to reproduce.
