### ISSUE TITLE
Scheduler: Using React components for renderEvents causes them to disappear

### ISSUE THREAD

**Issue by keithhackbarth** [bryntum/support#6363]
Below is an example but I'd be cautious about dismissing it as an edge case. In our case, using the AjaxEventStore and a day view present, we cannot even get events to render at all - even on the first load because of this issue.

Reproduction steps:
- Load the react events demo: https://bryntum.com/products/scheduler/examples/frameworks/react/javascript/react-events/build/
- Switch to weekly view
- Adjust browser window size

Expected: Events are still visible
Actual: Events disappear

https://user-images.githubusercontent.com/309034/224611947-4a6c465a-6431-4549-a7a4-d1d109cf88f0.mov

**Comment by matsbryntse** [comment]
Dupe #6343
