### ISSUE TITLE
Unable to drop task as a child unless children already contained

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6385]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24214&p=119876#p119876)

Hi.

Please see attached video.

We can drag a task and make it a child of another task by dropping it exactly in "the middle" of the target task (the one to become the parent). But it only works if it already has children.

Can be reproduced using the online demo: https://bryntum.com/products/gantt/examples/basic/

![Screenshot 2023-03-15 at 15.16.37.png](https://forum.bryntum.com/download/file.php?id=21197)

**Comment by isglass** [comment]
Already supported, see https://bryntum.com/products/gantt/docs/api/Grid/feature/RowReorder#config-dropOnLeaf
