### ISSUE TITLE
Toggling working time on and off does not redraw

### ISSUE THREAD

**Issue by isglass** [bryntum/support#639]
<img width="1106" alt="Screenshot 2020-04-29 at 15 49 24" src="https://user-images.githubusercontent.com/5415653/80603696-0b8c5c00-8a31-11ea-9436-2d6a2a4e24c9.png">

**Comment by bmblb** [comment]
Same in pro-weekends demo. When you change calendar on `ventilation` event (which is around christmas) to have the day off on christmas, it doesn't redraw. But tooltip shows correct end date
