### ISSUE TITLE
WBS code does not update when dragging and dropping between task

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6393]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=24212&p=119909#p119909)

"Hello,

When dragging and dropping a task, the WBS code does not seem to update correctly. 
I've attached an image and this issue occurs in the demo as well.

Thanks"
![WBS_Gantt.PNG](https://forum.bryntum.com/download/file.php?id=21192)

- Using the [https://bryntum.com/products/gantt/examples/frameworks/angular/inline-data/dist/inline-data/](https://bryntum.com/products/gantt/examples/frameworks/angular/inline-data/dist/inline-data/)
- Try to drag some tasks, the WBS code does not update correctly.

**Comment by matsbryntse** [comment]
If you want your WBS codes auto-updated, please set wbsMode "auto" on your taskStore:


```

project : {
        // Let the Project know we want to use our own Task model with custom fields / methods
        taskModelClass : Task,
        transport      : {
            load : {
                url : '../_datasets/launch-saas.json'
            }
        },
        autoLoad  : true,
        taskStore : {
            wbsMode : 'auto'
        },
        // The State TrackingManager which the UndoRedo widget in the toolbar uses
        stm : {
            autoRecord : true
        },
        // Reset Undo / Redo after each load
        resetUndoRedoQueuesAfterLoad : true
    },
```
