### ISSUE TITLE
Grid: add ability to control checkboxSelectionColumn visibility via the selectionMode config

### ISSUE THREAD

**Issue by eangelov** [bryntum/support#6396]
Currently there is no way to render the grid with a "checkbox selection column" hidden from the start.

The "checkbox selection column" can be hidden/shown manually after the grid is rendered.
![image](https://user-images.githubusercontent.com/3601104/225558083-15421b3d-1d8a-400c-8e87-e4efafd36062.png)

**Comment by matsbryntse** [comment]
This is already supported, since `checkbox` can be a column config object.
```

selectionMode : {
        cell       : true,
        dragSelect : true,
        rowNumber  : true,
        checkbox   : {
            hidden : true
        }
    },
```
