### ISSUE TITLE
Grid: 5.3.0 ColumnConfig type missing literal types

### ISSUE THREAD

**Issue by olsgreen** [bryntum/support#6398]
Hello 👋🏽

Just tried updating to 5.3.0, running into typescript errors with the `ColumnConfig` type. 

The `type` property specifies 'column' as the only string type:

    type ColumnConfig = {
        type: 'column'
        ...
    }

Where as the documentation differs: https://bryntum.com/products/grid/docs/api/Grid/column/Column#column-types

Can we get them added back?

**Comment by isglass** [comment]
Hi @olsgreen,

Thanks for your report. Each type of column now specifies its own correct type, WidgetColumn has `type: 'widget'`, NumberColumn `type: 'number'`. All column types are then union:ed into the `GridColumnConfig` type.

This allows TypeScript to type column configs objects, in scenarios like this for example:

```
{
  columns : [
    { type : 'number', ... only stuff from NumberColumn works here ... },
    { type : 'widget', ... WidgetColumn stuff works here ... }
  ]
}
```

So probably what we should do is change docs (and thus typings, they are generated from docs) somewhere to use `GridColumnConfig`. Could you give some more info on where you are trying to use it?

**Comment by olsgreen** [comment]
I've been dynamically building grid configuration using the `ColumnConfig` type:

    const columns: Partial<ColumnConfig>[] = [
        {
            type: 'template',
            ...
        },{
            type: 'checkbox',
            ...
        },
        ...
    ]

    if (x === y) {
        columns.push({ 
            type: 'template', 
            ...
        })
    }

I've just switched out `ColumnConfig` for `GridColumnConfig` and then more specific column types out to their new sub-types, issue resolved. 

Thanks for your help & quick response 😊
