### ISSUE TITLE
Labels for milestones not centered

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#640]
"new-engine" branch
convert a task to be 0 duration. 
Event wrapper element lost 'align-items:center' which it used to have. Find how it was lost
Labels demo http://lh/bryntum-suite/scheduler/examples/labels/
<img width="538" alt="Screenshot 2020-04-29 at 19 11 11" src="https://user-images.githubusercontent.com/218570/80625229-32588b80-8a4d-11ea-8563-7a39ea33e73e.png">

<img width="213" alt="Screenshot 2020-05-04 at 08 44 27" src="https://user-images.githubusercontent.com/218570/80941811-ac896700-8de3-11ea-8879-9b35691d79ea.png">

**Comment by isglass** [comment]
Fixed earlier
