### ISSUE TITLE
Id field is hardcoded in model change event

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6401]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24251&p=120105#p120105)

"Hi,

We are encountering some strange behaviour when we are assigning new ids to records in our tree grid. It seems that the root cause of this problem is the onModelChange handler in Store.js assumes the id fields is called id. In our implementation, we set Model.idField to be something different.

See this code snippet from onModelChange:

```
if ('id' in wasSet) {
  const { oldValue, value } = toSet.id;

  me.updateDependentRecordIds(oldValue, value);

  me.onRecordIdChange({ record, oldValue, value });
}
```

Should this be something like this, instead?

```
if (record.idField in wasSet) {
  const { oldValue, value } = toSet[record.idField];

  me.updateDependentRecordIds(oldValue, value);

  me.onRecordIdChange({ record, oldValue, value });
}
```

If we call onRecordIdChange manually when we assign the new id, everything works fine."

**Comment by matsbryntse** [comment]
Test added to `6401-id` branch

**Comment by isglass** [comment]
Requested more info on the forum
