### ISSUE TITLE
Dropping events past noon gives unexpected results

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6403]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24254&p=120112#p120112)

Hi,

On 5.3.1, I am experiencing this issue where dropping an event will jump to the previous day if the event starts after noon. Look at this video where events starting prior to noon ends on the drop target but events starting after noon jumps to the previous day: https://www.dropbox.com/s/i0itjahydogvx7j/past-noon-fails.mov?dl=0

REPLICATING THE ISSUE
Download the zip file.

Since we do need a backend to server a few things, it is a multi-step setup.

In the project root:

```
python3 server.py
```
In another terminal window, do this to get an interactive session with npm 16:

```
docker run -it --rm -p 3000:3000 -v $PWD:/home/node/app node:16-buster /bin/bash
```

Inside the container do:

```
cd /home/node/app/ && npm install && npm run dev
```

Once done, you can now open this in your browser: http://localhost:3030/public/index.html

**Comment by marciogurka** [comment]
[User asking](https://forum.bryntum.com/viewtopic.php?p=121230#p121230) for this fix with urgency.

**Comment by isglass** [comment]
Issue seems to be related to `snapRelativeToEventStartDate`
