### ISSUE TITLE
Setting scheduler.startDate to current date not working properly on infiniteScroll enabled

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6404]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24257&p=120126#p120126)

You could reproduce it here https://bryntum.com/products/scheduler/examples/basic/
1. First set `infiniteScroll` to `true`
2. Then, in the console scheduler.startDate = new Date(); 
3. Then use the horizontal scrollbar to scroll right or left then paste the same code in the console again. you'll see it's showing a future date not today's date

**Comment by taauntik** [comment]
related https://github.com/bryntum/support/issues/6032

**Comment by mightym** [comment]
@taauntik as you mentioned this is related to #6032 This issue seems to be marked as resolved and available in Release `5.3.3`. But for me this issue is still there in that release? Or is #6032 actually something else?

**Comment by isglass** [comment]
Solution is to use `visibleDate` instead, will repurpose ticket to clarify this in docs.

**Comment by isglass** [comment]
Docs clarification https://github.com/bryntum/bryntum-suite/pull/7008. Closing this ticket
