### ISSUE TITLE
`zoomIn`/`zoomOut` doesn't work properly with RTL + `zoomPosition`

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6415]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24275&p=120219#p120219)

Open https://bryntum.com/products/scheduler/examples/bigdataset/
Add `direction: rtl` CSS to the scheduler.
Try to call zoomIn/zoomOut in console using `zoomDate` and `zoomPosition` properties

here is the code, `date` might be any point that you want to keep on the place. As example `scheduler.eventStore.first.startDate`
```

    zoomOut() {
        const offset = this.scheduler.getCoordinateFromDate(date);
        console.log(offset);
        this.scheduler.zoomToLevel(this.scheduler.zoomLevel + 1, {
            zoomDate : date,
            zoomPosition: this.offset
        });
    }
    zoomIn() {
        const offset = this.scheduler.getCoordinateFromDate(date);
        this.scheduler.zoomToLevel(this.scheduler.zoomLevel - 1, {
            zoomDate : date,
            zoomPosition: offset
        });
    }
```

It works well with ltr direction, but doesn't with rtl.

**Comment by yakeer** [comment]
Hey @chuckn0rris & @matsbryntse 
We'll appreciate a quick fix for this, as we didn't encounter the issue in our internal tests, and it has been rolled out to production already.
Our zoom feature depends on it, and it's a commonly used feature.

Thanks.

**Comment by yakeer** [comment]
@chuckn0rris @matsbryntse 
Any news on this?

**Comment by matsbryntse** [comment]
Not yet, hope to get it looked at this week!
