### ISSUE TITLE
Unexpected behaviour when resizing column

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#6421]
1. Try the Grid's Column drag toolbar demo
2. Resize on the right side of the Year or Repair frequency column.

[screen-capture (1).webm](https://user-images.githubusercontent.com/100013589/226579990-0aa1d6dc-d5fa-41c5-a715-409e4feeb581.webm)

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/3025
