### ISSUE TITLE
EventEditor not showing in FullScreen

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6427]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24300&p=120325#p120325)

"Hi all,

Could you have a look at this? The eventEditor is not showing in full-screen:
https://www.dropbox.com/s/03jxf096r9pcxgd/Screen%20Recording%202023-03-21%20at%2014.55.40.mov?dl=0

The FullScreen mode is implemented in tbar like this:

```
{
        ref: 'fullscreenButton',
        id: 'fullscreen-button',
        type: "button",
        tooltip: "Fullscreen",
        icon: 'b-icon-fullscreen',
        ignoreLearn: true,
        onClick() {
            if (Fullscreen.enabled) {
                const element = document.getElementById("schedule-calendar")
                if (element === null) {
                    throw new Error("You renamed ID of the scheduler component")
                }
                if (!Fullscreen.isFullscreen) {
                    Fullscreen.request(element);
                } else {
                    Fullscreen.exit();
                }
            }
        }
    },
```

REPLICATING THE ISSUE
Download the zip file.

Since we do need a backend to server a few things, it is a multi-step setup.

In the project root:

```
python3 server.py
```
In another terminal window, do this to get an interactive session with npm 16:

```
docker run -it --rm -p 3000:3000 -v $PWD:/home/node/app node:16-buster /bin/bash
```

Inside the container do:

```
cd /home/node/app/ && npm install && npm run dev
```

Once done, you can now open this in your browser: http://localhost:3030/public/index.html"

As checked in the demo example, if you go fullscreen, the editor is rendered in the DOM, but not correctly shown on the screen 
![Screenshot 2023-03-21 at 11 30 53](https://user-images.githubusercontent.com/16693227/226638876-2ca38ea6-b5ef-47a7-b891-5d944dcba626.png)

[bryntum-demo-main.zip](https://github.com/bryntum/support/files/11029421/bryntum-demo-main.zip)

**Comment by marciogurka** [comment]
Using the [https://bryntum.com/products/scheduler/docs/api/Core/widget/Widget#function-requestFullscreen](https://bryntum.com/products/scheduler/docs/api/Core/widget/Widget#function-requestFullscreen) function make it work correctly, so it's the proper way to change to full-screen.

**Comment by knobel-dk** [comment]
This is how it looks like in a partnered scheduler setup. Not a proper way: https://www.dropbox.com/s/2dfglj8y34850pm/Screen%20Recording%202023-03-21%20at%2017.56.39.mov?dl=0
