### ISSUE TITLE
Merged Cells Re-sort after Reorder

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6429]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24303&p=120349#p120349)

"Hi,
I have 2 columns in the grid which are merged.  I am also enabling the Row Reordering. After row reordering, the cell merge is reset to normal rows. 
I want to manually re-sort the grid based on both the columns after row reordering in order to display the cell merge. How to achieve this in the change event?
Please refer the below example. 

```
const grid = new Grid({
    appendTo : targetElement,

// makes grid as high as it needs to be to fit rows
autoHeight : true,
  

features : {
    // enable row reordering by dragging
    rowReorder : true,
sort : ['surName','city'],
mergeCells:  true,
    },

data : DataGenerator.generateData(10),

columns : [
    { field : 'firstName', text : 'First name', width : 150, locked : true },
    { field : 'surName', text : 'Surname', width : 150, locked : true , mergeCells: true},
    { field : 'city', text : 'City', flex : 1, mergeCells: true },
    { field : 'team', text : 'Team', flex : 1 },
    { field : 'score', text : 'Score', flex : 1 },
    { field : 'rank', text : 'Rank', flex : 1 }
]
});

```"


https://user-images.githubusercontent.com/16693227/226704335-fa65158b-df78-4c75-b97a-42d2caa225c5.mp4

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=120657#p120657) user asking for this.

**Comment by isglass** [comment]
Going to implement #5012, which is going allow it to merge the cells even after reordering, since sorting wont be required
