### ISSUE TITLE
Support `stickyEvents` feature in RTL mode

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6438]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24316&p=120394#p120394)

**Comment by yakeer** [comment]
Hey @matsbryntse ,
Basically, it's not a feature request, but a bug in an existing feature - in RTL mode.

I believe that should be fixed in order to have full RTL support functionality.

We'll appreciate a higher priority for this.
