### ISSUE TITLE
Wrong item picked in combo box when using key navigation

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#645]
Reproducible on `multiassign-with-dependencies` demo (online too)
Steps:
1. expand combo
2. navigate somewhere to bottom, hit enter twice to select/unselect item
3. close editor
4. open again, expand combo, hit down arrow, see that previous item is picked
![combo bug](https://user-images.githubusercontent.com/45400762/80731419-8f1e7980-8b13-11ea-8259-6cad9e4471d8.gif)

**Comment by ExtAnimal** [comment]
It's the same combobox instance.

A combobox has navigation and that's the last one navigated to. Nothing changes it, so that's where it's current navigated-to item is. Who thinks this is a bug?
