### ISSUE TITLE
[VUE 3] Kebab-case names for Vue wrappers

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#6455]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=24345)

- [x] Update wrappers to use kebab case convention for vue events/features.
- [x] Update guides

Stated here:
https://vuejs.org/guide/components/events.html#emitting-and-listening-to-events

Currently these supported:

Using `onFunctions`:

```
<bryntum-calendar
    ref="calendar"
    v-bind="calendarConfig"
    :onBeforeDragMoveEnd="handleBeforeDragMoveEnd"
    :onDragMoveEnd="handleDragMoveEnd"
/>
```

Using events with camelCase:

```
<bryntum-calendar
    ref="calendar"
    v-bind="calendarConfig"
    @beforeDragMoveEnd="handleBeforeDragMoveEnd"
    @dragMoveEnd="handleDragMoveEnd"
/>
```

## TODO
Support this

```
<bryntum-calendar
    ref="calendar"
    v-bind="calendarConfig"
    @before-event-resize="handleBeforeEventResize"
    @before-drag-move-end="handleBeforeDragMoveEnd"
/>
```

**Comment by jsakalos** [comment]
We need to support kebab names for ALL configs/props/events because Vue 3 guys strongly recommend that. So `on-load` in a Vue template has to be transformed to our `onLoad` config/prop name.
