### ISSUE TITLE
[Ext JS] Availability duration [00:00-00:00] is not supported

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#6474]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=12242&p=120825#p120825)

In Ms project, the defaultAvailability of "24 Hours" calendar is [00:00-00:00], after a .mpp file is imported into Bryntum gantt. Duration [00:00-00:00] is considered to be zero. 

Seems it can work after I update [00:00-00:00] to [00:00-24:00]. But support  [00:00-00:00] need to be supported as well since it's a valid availability duration in MS project.

**Comment by arcady-zherdev** [comment]
@vincentcn  e'll take a closer look at this next week and will update you with ETA then.

**Comment by vincentcn** [comment]
@arcady-zherdev, thanks for the quick response. Please keep us updated. 
Besides, please help to check https://github.com/bryntum/support/issues/6517 as well. Thanks.

**Comment by arcady-zherdev** [comment]
@vincentcn this ticket is partly done so can also be released in the next patch release I think.
