### ISSUE TITLE
[Ext JS] Assignments in task editor is not synced to "Assigned Resources" in specific scenario

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6476]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=49&t=13960&p=120822#p120822)

The issue can be reproduced in sample https://www.bryntum.com/examples/gantt-for-extjs/kitchensink/#examples/calendars.
Reproduce steps:
1. Open the sample page. Click "Assigned Resources" column of task "Ext JS 4.0.2" to open the assignment grid. Update Nickolay's Units from 80% to a different value(E.g. 70%). Then click "Save and Close" to commit the changes.
2. Double click task  "Ext JS 4.0.2" to open task editor. Switch to "Resource" tab and remove resource "Nickolay". Then click "OK" to commit the changes.
3. The "Assigned Resources" column is not updated and changes in step 2 is not reflected. Open task editor again and we can see that assignments in "Resource" tab are not consistent with the value in "Assigned Resources" column.

![Screen Shot 2020-05-14 at 11.02.31 PM.png](https://forum.bryntum.com/download/file.php?id=10276)

**Comment by vincentcn** [comment]
Hi @chuckn0rris,  any ETA of the fix? This issue has been raised for a long time.

**Comment by arcady-zherdev** [comment]
@vincentcn will check this next week and update you with ETA here
