### ISSUE TITLE
Angular Ivy Rendering Engine Support for Bryntum Scheduler

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6486]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24427&p=121041#p121041)

"Angular View Engine and the Angular Compatibility Compiler have not been officially supported and marked as deprecated for a while (since Angular 12 I think - May 2021).

With the upcoming Angular v16 release (ETA 1-2 months, May 2023) the ngcc view engine compiler will be deprecated completely. This will make the Bryntum scheduler fully incompatible with new release. 

I would be thankful if you could consider upgrading and creating a new release of the Bryntum Scheduler with an ivy distribution."

Source: https://github.com/angular/angular/blob/main/CHANGELOG.md#1600-next0-2023-02-22

**Comment by cwoebker** [comment]
Thanks @marciogurka for posting here as well. I am the author of the forum post, so to whom it may concern, feel free to tag me here as well if there are follow on questions!
