### ISSUE TITLE
Tooltip's start time is not consistent with Gantt header

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6490]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=39&t=10164&p=120949#p120949)

Hi,

When the event's start time < Gantt's start time, we found if dragging the event the tooltip's start time will not consistent with the header's time, any suggestions about it?
I tried with the sample, the issue also can reproduce, please check the snapshot.
https://www.bryntum.com/products/scheduler-for-extjs/examples/kitchensink/#examples/dragselectorplugin

![Screen Shot 2018-12-04 at 9.01.08 PM.png](https://forum.bryntum.com/download/file.php?id=6746)

https://user-images.githubusercontent.com/7203098/228730976-dcdcb771-be52-42b8-bc5c-0271a5f1a5cc.mov

**Comment by vincentcn** [comment]
Hi @chuckn0rris  any ETA of the fix? This issue has been raised for a long time.

**Comment by arcady-zherdev** [comment]
@vincentcn  we'll try to fix this in the v6.1.22 patch release. I'll update you here with a more specific release date estimation next week

**Comment by arcady-zherdev** [comment]
I've rechecked the issue and the tootip seems work fine in that case.
The misleading thing is the dragged event element. It's cropped and thus the tooltip values look incorrect.
For example:
1. I drag an event to start at `03:00` before the view start date
![00](https://github.com/bryntum/support/assets/6712184/844bde04-8929-4e37-907e-168046a15e76)
2. The left part of the element representing the event is cropped and thus when you start dragging the event the tooltip values (which display the event start/end dates) do not match the element left side. Here the tooltip shows that the dragged event start is at `06:30`:
![01](https://github.com/bryntum/support/assets/6712184/60bad736-689b-4599-97e5-631e288ac8de)
3. And after we drop the event we see that the event was indeed at that date/time position:
![02](https://github.com/bryntum/support/assets/6712184/e5294d50-60a7-49da-a198-889aece61734)

So the ticket is not about toolitp actually ..it's about cropped element.

**Comment by arcady-zherdev** [comment]
@vincentcn this one will also be included in the next patch release

**Comment by vincentcn** [comment]
Thanks a lot. @arcady-zherdev
