### ISSUE TITLE
Should be possible to add extra buttons to column header

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6497]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=56&t=24322&p=120969#p120969)

We saw that it's possible to add stuff (buttons, etc.) below the column header like here the plus button: https://bryntum.com/products/taskboard/examples/column-toolbars/

However, we are wondering, if it's possible to add stuff at the very top (where the column name is the collapse button and the menu), or at least to make the column header clickable...

**Comment by matsbryntse** [comment]
@morphace Column header can now contain HTML content after setting `htmlEncodeHeaderText` to `false` on a column. Will this suffice to cover your use case?

**Comment by morphace** [comment]
Yes, I think so! Thanks @matsbryntse
