### ISSUE TITLE
Add support for `resourceIds` to `EventModel`

### ISSUE THREAD

**Issue by isglass** [bryntum/support#6502]
https://forum.bryntum.com/viewtopic.php?t=24345&start=10

Allow assigning multiple resources using this approach:

```
{
  id : 1,
  name : 'Event 1',
  resourceIds : [2, 5]
}
```

Should result in two assignments being created in the assignment store.

When used, the array also needs to be kept up to date on reassignments, flagging the event as modified etc. Should be assignable at runtime and so on

**Comment by jnarowski** [comment]
This is great. Thanks for the followup on this.
