### ISSUE TITLE
Copying more than two events paste only first and last

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6505]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24460&p=121215#p121215)

I am trying to implement additional functionality to copy/paste, using beforePaste event and notice that, when I click copy on two separate events in sequence and paste these events in one place. At first glance it looks like a multiple copying behavior, but it is always two events and doesn’t matter how many events I was copying. When copying three or more events, only the first and last copied events are pasted.

I attached video that shows this behavior. In my opinion, it looks like a bug.
And you can reproduce this behavior in demo too: https://bryntum.com/products/scheduler/examples/dragfromgrid/
Is there any way how to fix this behavior in order to allow copy/paste single record.

https://user-images.githubusercontent.com/75997756/229112573-f38c62d0-b44d-4c27-9535-1fb2b227f676.mp4

**Comment by matsbryntse** [comment]
This is working as intended, you have to first select (CTRL-key) and then use context menu and it'll work as you want.
