### ISSUE TITLE
[ExtJS] The Gantt will be crashed after add new predecessor for a task

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#6517]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=49&t=20855&p=121281#p121281)

Dear Bryntum Team,

We found the Gantt will get crashed after add the `Summary #2` predecessor for `Task 1`. It also can reproduce on the basic example with the following test data:
[dependencies.zip](https://github.com/bryntum/support/files/11134582/dependencies.zip)
[tasks.zip](https://github.com/bryntum/support/files/11134583/tasks.zip)

Reproduced on Gantt-pro-6.1.15.

**Comment by vincentcn** [comment]
Hi @arcady-zherdev  any ETA of the fix? This issue has been raised for a long time.

**Comment by arcady-zherdev** [comment]
@vincentcn we'll check this one next week too and return with ETA

**Comment by vincentcn** [comment]
Thanks for the update. Do you have the exact date of the August patch release?

**Comment by arcady-zherdev** [comment]
@vincentcn no exact date yet but plan is to do it in the beginning of August
