### ISSUE TITLE
[ExtJS] Scheduler drag tip issue in RTL orientation

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#6518]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=9&t=11252&p=121280#p121280)

We found a drag tip display position issue when RTL is enabled. The issue can be easily reproducible via https://www.bryntum.com/examples/scheduler-for-extjs/rtl/, especially when narrowing down the duration to a small one e.g., a half hour.

The issue origin is in Ext JS code. Here is it's reported to Sencha: https://www.sencha.com/forum/showthread.php?471735-RTL-Tooltips-misaligned-in-RTL&p=1324904#post1324904

**Comment by matsbryntse** [comment]
This needs to be fixed by Sencha
