### ISSUE TITLE
[ANGULAR] Resource Utilization - custom tick contect is not updated when shift timeline

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6527]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24482&p=121345#p121345)

[resource-histogram.zip](https://github.com/bryntum/support/files/11138441/resource-histogram.zip)

Applied minimal changes to resource-histogram demo, use Shift next/previous buttons on tbar to reproduce. See that data inside ticks is not updated. It works well in vanilla and doesn't in Angular.

**Comment by arcady-zherdev** [comment]
Duplicates of the issue:
https://github.com/bryntum/support/issues/5059
https://github.com/bryntum/support/issues/2695
