### ISSUE TITLE
Dragging allDay event in DST period adds 1 hour

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6537]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24499&p=121525#p121525)

Hallo,

in our current application all events are in size intervals of 1 week and are set as "allDay". This is done via a viewpreset like this:

```
 new ViewPreset({
        id: 'calenderWeek', 
        shiftIncrement: 1, 
        shiftUnit: 'week', 
        mainUnit: 'week', 
        timeResolution: {
          unit: 'week', 
          increment: 1,
        },
        headers: [
          {
            unit: 'month',
            dateFormat: 'MMM YY',
            headerCellCls: 'vertically-devided horizontally-devided',
          },
          {
            unit: 'week',
            headerCellCls: 'horizontally-devided calendar-week',
          },
        ]
 })
 
```
However, if we create an event the week before March 26 and then drag it across the daylight saving date, the date then gets added 1 hour which in the case of an "allDay" event is an additional 1 day. This also happens if we drag&drop the event into the 13. calender week. 

In addition, the duration is still "7 days" or "14 days" if we examine the event.

Example screenshots:
Initial Event (7 days)
![InitialEvent.png](https://forum.bryntum.com/download/file.php?id=21621)

Drag&Drop into calender week 13:
![Drag&Drop.png](https://forum.bryntum.com/download/file.php?id=21620)

Resize into calender week 13:
![Resize.png](https://forum.bryntum.com/download/file.php?id=21622)
![InitialEvent.png](https://forum.bryntum.com/download/file.php?id=21621)
![Drag&Drop.png](https://forum.bryntum.com/download/file.php?id=21620)
![Resize.png](https://forum.bryntum.com/download/file.php?id=21622)

This is data to repro:
```
{
    "resources": [
        {
            "id": "p1",
            "name": "Phase 1",
            "expanded": "true",
            "children": [
                {
                    "id": "s1",
                    "name": "Lane 1.1",
                    "parentId": 1
                },
                {
                    "id": "s2",
                    "name": "Lane 1.2",
                    "parentId": 1
                }        
            ]
        },
        {
            "id": "p2",
            "name": "Phase 2",
            "expanded": "true",
            "children": [
                {
                    "id": "s3",
                    "name": "Lane 2.1"
                }
            ]
        }
    ],
    "events": [
        {
            "id": "e1",
            "name": "Daylight saving",
            "startDate": "2023-03-19",
            "endDate": "2023-03-26",
            "allDay": true
        }
    ],
    "assignments": [
        {
            "id": "a1",
            "eventId": "e1",
            "resourceId": "s3"
        }
    ]
}
```

**Comment by canonic-epicure** [comment]
Does not seem to be reproducible in the latest 5.3.2 code or I am missing something. Requested additional info from user, also advised to check if `adjustDurationToDST` helps.

**Comment by canonic-epicure** [comment]
User reported that `adjustDurationToDST` has fixed the problem. Closing as non-reproducible.
