### ISSUE TITLE
WBS cells are fillable with `fillHandle`

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6546]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=24425&p=121607#p121607)

Additionally columns like WBS can be dragged over. Also if the entire gantt is readOnly it allows you to drag as well.

Go here: https://bryntum.com/products/gantt/examples/cellselection/ Add the wbs column
```
{type:'wbs'}
```
and try to drag down. This is one example where the drag should not be working. We have many locations where drag is happening and shouldn't be. By drag I am talking about the cell editing fillable, not dragging whole lines. FillHandle feature

**Comment by isglass** [comment]
We should not allow filling (or cell copy paste) in columns that are `editor: null` or readOnly
