### ISSUE TITLE
Event flicking out when scrolling when long widths used

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6558]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24488&p=121503#p121503)

Using the [https://bryntum.com/products/scheduler/examples/bigdataset-vertical/](https://bryntum.com/products/scheduler/examples/bigdataset-vertical/) demo, and adding the following snippet:

```
  eventRenderer({ renderData }) {
        renderData.style = "width:500px;";
    },
```

You'll see the following behavior of the events 

https://user-images.githubusercontent.com/16693227/230500329-df592d59-4487-4931-92e2-661ba8aee823.mp4

**Comment by isglass** [comment]
Only events in view are rendered, based not on the element but on the layout we calculate. We do not currently support stretching events over multiple resources
