### ISSUE TITLE
Add ResourceTimeRanges feature to Calendar

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6608]
Should appear in ResourceView, DateResourceView and Scheduler

**Comment by ExtAnimal** [comment]
This was done. Obviously they only show up when the view *has* that resource.

Otherwise, they'd just be TimeRanges.

<img width="2449" alt="Screenshot 2023-08-14 at 13 03 11" src="https://github.com/bryntum/support/assets/200516/a7d13564-7f39-44cd-b4f2-650a5c723eca">
