### ISSUE TITLE
Should be possible to disable dependencies feature for particular task

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6609]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=24624&p=122301#p122301)

Hi,

Given the example below, how can I disable attachment of dependencies to 'Inform management about decision' task. If I mouse over on the milestone icon, the two small white circles should not be visible.

![Capture.PNG](https://forum.bryntum.com/download/file.php?id=21831)

Thanks

**Comment by b26** [comment]
I don't think beforeShowTerminals works. The event is triggered but the terminals are always displayed regardless if you are return false for them all
