### ISSUE TITLE
[REACT] StateProvider doesn't keep column sizes or page reload

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6618]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24595&p=122326#p122326)

Demo attached.
If you move splitter and reload - position will be properly restored. If you resize column and reload - size won't be saved.
Works well in vanilla.
 
[Bryntum-demo-2023-04-18-001.zip](https://github.com/bryntum/support/files/11271477/Bryntum-demo-2023-04-18-001.zip)

**Comment by FlowIT-JIT** [comment]
@matsbryntse Would it be possible for you guys to commit to having this issue resolved for the next patch version of 5.3 ?

**Comment by matsbryntse** [comment]
Yes, we'll try our best!

**Comment by FlowIT-JIT** [comment]
Thanks a lot, @matsbryntse

**Comment by jsakalos** [comment]
I took the above sample for testing, changed the version of Bryntum libraries to `5.3.2` in `package.json` and started the app with `npm i && npm start`. Then I've deleted existing (probably stale) local storage and the columns' widths are restored on reload as expected. See the screencast:
![state](https://user-images.githubusercontent.com/204844/233598013-89ca8fda-a8fd-4c71-997d-80197bd298cc.gif)

**Comment by FlowIT-JIT** [comment]
@jsakalos Thank you for investigating.
I'm not entirely sure why the bug report started focusing on column widths since that was not what I reported. Perhaps to simplify things. But please see the original forum post. When we re-create Gantt (use the [Create new Gantt instance] button), customization done to the order of columns are reverted - and possibly other view settings as well, I don't remember. I have just verified that the problem is still present with version 5.3.3.

**Comment by FlowIT-JIT** [comment]
I have attached a video demonstrating the problem with version 5.3.3.
[Bryntum-2023-04-21-001.m4v.zip](https://github.com/bryntum/support/files/11295285/Bryntum-2023-04-21-001.m4v.zip)

**Comment by jsakalos** [comment]
Thanks for the info, I'll check that too.

**Comment by jsakalos** [comment]
@FlowIT-JIT, so I have finally cracked it. What's going on behind the scene is that columns configuration objects are converted to records for ColumnStore and their ids are auto-generated, if not provided. So when we reload the page, the column ids generation starts at zero. However, when we destroy and re-create the instance, the id generation continues from the previous instance, effectively unlinking the columns from the saved state.

The solution is simple: give your columns' configs ids, for example:
```
            "columns": [
                {
                    "text": "",
                    "type": "wbs",
                    "id":1
                },
                {
                    "type": "check",
                    "text": "Manuel",
                    "field": "manuallyScheduled",
                    "id":2
                },
                {
                    "type": "name",
                    "text": "Titel",
                    "field": "name",
                    "width": 350,
                    "id":3
                },
```
and it will work. I will also create a ticket to check whether we could improve the auto-generation of ids logic.

**Comment by isglass** [comment]
Replaced by #6646

**Comment by FlowIT-JIT** [comment]
@jsakalos Thank you so much for providing a fix 😊
