### ISSUE TITLE
.mpp file import problem for turkish characters

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6623]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=24645&p=122422#p122422)

"Dear Bryntum Support Team,

I hope this finds you well. I have been using your jar file in my project, and I have encountered an issue with Turkish characters being displayed incorrectly. When I use the original jar file, the Turkish characters appear garbled and unreadable.

However, when I update the jar file to use UTF-8 encoding, the Turkish characters are displayed correctly. I kindly request you to revise the original code in your jar file to support the proper display of Turkish characters by default.

This change would greatly improve the usability of your product for Turkish-speaking users and would be much appreciated.

After you update the code, could you please share it with me?

Thank you for your attention to this matter, and I look forward to your prompt response."

**Comment by sefadogan** [comment]
Hi marciogurka,

Any improvements? Our customer asks me this per two days :)

**Comment by arcady-zherdev** [comment]
@sefadogan 
1. Can you please provide a sample mpp-file that doesn't work for you?

2. We had a similar report from one of our Japanese clients. It was fixed by setting utf-8 charset in php code:
```php
<?php

require 'UploadException.php';

$dir      = dirname(__FILE__);
$jar_path = $dir . '/../projectreader/target/bryntum-project-reader-6.1.22.jar';
$tmp_dir  = $dir . '/tmp/';

// Force UTF-8 encoding to make sure multi-byte characters returned by bryntum-project-reader-xxx.jar
// are not corrupted
putenv('LANG=en_US.UTF-8');
```

Can you please check if you have that line in your `load.php` file?

**Comment by arcady-zherdev** [comment]
Application level problem
