### ISSUE TITLE
Not possible to partner grouped SchedulerPro with Histogram

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#663]
Grouping injects meta records into store which should not be shared

Test added:
ResourceHistogram.t.js

`    t.xit('Should work paired with a grouped Scheduler', async t => {
`

**Comment by pmiklashevich** [comment]
We have http://lh/bryntum-suite/schedulerpro/examples/resourcehistogram/ in SchedulerPro. If you group Scheduler the partnering works good:
```
const scheduler = new SchedulerPro({
    features : {
        group : 'city'
    },
```
