### ISSUE TITLE
Zooming with mouse wheel broken in RTL

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6641]
http://lh/bryntum-suite/scheduler/examples/basic/?rtl

**Comment by matsbryntse** [comment]
Tested in 6641-zoom-rtl

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?t=24763

**Comment by yakeer** [comment]
Any update on this? Is it scheduled for work soon?

**Comment by matsbryntse** [comment]
It’s in progress, just taking some time.
