### ISSUE TITLE
Calendar: after zoom, scroll jumps on click-n-drag event creation

### ISSUE THREAD

**Issue by steveschmitt** [bryntum/support#6651]
Steps to reproduce:

1. Go to https://bryntum.com/products/calendar/examples/day-zoom/
2. On the small calendar in the upper left, click on October 27 to go to an empty week.
3. Move the Hour height slider all the way to the right, to zoom in.  The scroll position will be ~1pm.
4. Using the vertical scroll bar on the far right, scroll up to the top so that 1am is visible.
5. Click and drag to attempt to create an event starting at 1am with a duration of 15 minutes.

**Expected**: you can drag from 1am to 1:15 am to create the event
**Actual**: the calendar scroll position jumps ~12 hours to the center of the previous scroll position, giving you a 12-hour long event.

Environment: Chrome on Windows

**Comment by matsbryntse** [comment]
Confirmed
