### ISSUE TITLE
Incorrect date when infiniteScroll is enabled on example

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6662]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24752&p=122880#p122880)

"We are currently setting up a quite full featured date navigation setup, with moving to dates, zoom in/out buttons, custom preset zoom levels among other things. We also want to use infiniteScroll, but when we enabled that we found that it doesn’t play nice with any of the mentioned features.

We’ve found examples you have of each feature, and I’ll try to describe how the error presents itself in each case. For each of the examples, just add infiniteScroll: true to the scheduler config.
[...]

3. Go to date, for example [https://www.bryntum.com/products/schedulerpro/examples/drag-unplanned-tasks/](https://www.bryntum.com/products/schedulerpro/examples/drag-unplanned-tasks/). Going to a specific date (like “today” in the example) produces erratic results. Approximately every other time it goes to the correct date, and the other times it goes to another date."

**Comment by ExtAnimal** [comment]
This ticket was created in error.
