### ISSUE TITLE
zoomToSpan works different for custom and original presets

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6674]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24702&p=122917#p122917)

In basic Scheduler demo add
```

const presets = PresetManager.map((preset) => {
    const newPreset = JSON.parse(JSON.stringify(preset));
    newPreset.id = `custom${preset.id}`;
    newPreset.timeResolution = {
         unit: 'minute',
         increment: 1
    };


    return newPreset;
    

});

const scheduler = new Scheduler({
    appendTo         : 'container',
    rstartDate         : new Date(2017, 0, 1, 6),
    // endDate           : new Date(2017, 0, 1, 20),
    presets,
    viewPreset        : 'customhourAndDay',
```

In console 
```
scheduler.zoomToSpan({startDate: new Date(2017, 0, 1),  endDate: new Date(2017, 0, 8)})
```

See that ticks get width of the viewport

<img width="1359" alt="Screenshot 2023-04-28 at 14 27 07" src="https://user-images.githubusercontent.com/7203098/235147144-3d3089da-88b5-4702-a41f-54d7abb0d7fe.png">

Change the code a bit, to use origin presets as a `base`:

```

const presets = PresetManager.map((preset) => {

    return {
        id: `custom${preset.id}`,

        // For change the delta changes.
        base: preset.id, // Based on an existing preset
        timeResolution: {
            unit: 'minute',
            increment: 1
        }
     
    }

});

const scheduler = new Scheduler({
    appendTo         : 'container',
    rstartDate         : new Date(2017, 0, 1, 6),
    // endDate           : new Date(2017, 0, 1, 20),
    presets,
    viewPreset        : 'customhourAndDay',
```

In console 
```
scheduler.zoomToSpan({startDate: new Date(2017, 0, 1),  endDate: new Date(2017, 0, 8)})
```

See that 

<img width="1359" alt="Screenshot 2023-04-28 at 14 26 01" src="https://user-images.githubusercontent.com/7203098/235146877-b3e12b4e-2a27-4b3f-a865-d5172e280ff2.png">

**Comment by yakeer** [comment]
@matsbryntse 
There are several zoom issues that we've reported, some are new and some are regression.
We need to stabilize our zooming functionality in our app, so we would appreciate if it's possible to work on all of them in the same version update - otherwise one bug conflicts with the other.

**Comment by matsbryntse** [comment]
We'll try to investigate and fix them, thanks for reporting!
