### ISSUE TITLE
Keyboard shortcut not triggering Collapse / Expand when tree column outputs a link

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6675]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24774&p=123008#p123008)

"Hi,

When using a standard 'tree' column in the Tree Grid, highlighting a tree column cell and pressing space on the keyboard triggers a toggle of the collapsed / expanded state. This can be seen in the demo here.

We have customised the tree column in order to show the text as a hyperlink. We have done this using a custom renderer. However, we have found that doing so has stopped the space bar triggered collapse / expand mentioned above. 

Is there a recommended way to achieve this customisation without losing the expand / collapse behaviour on space bar press? 

This can be replicated easily using the same demo with the following two small changes:

1) turn off the context menu

```
features: { cellEdit: false, rowCopyPaste: false, cellMenu: { items: { removeRow: false } } }
```

2) add renderer which adds anchor tags to the Name 'tree' column

```
renderer({ value, record, row }) {
  if (record instanceof Terminal) { ... }
  return `<a href="#" target="_blank">${StringHelper.encodeHtml(value)}</a>`;
}
```

Note - we decided against using the standard href property since that turns the whole cell into a hyperlink, although I think that has the same behaviour."

https://user-images.githubusercontent.com/16693227/235163657-fbbde3af-5967-48fa-a94d-ea958daeaae8.mp4

**Comment by matsbryntse** [comment]
Test:```


// https://github.com/bryntum/support/issues/6675
    t.iit('Should toggle expanded state for parent when rendering a hyperlink inside', async t => {
        grid = await t.getTree({
            columns : [{
                type       : 'tree',
                text       : 'Name',
                field      : 'name',
                htmlEncode : false,
                renderer({ value, record, row }) {
                    return '<a href="#" target="_blank">value</a>';
                }
            }]
        });

        await t.click('.b-tree-cell');

        await t.type(null, ' ');
        t.is(grid.store.first.isExpanded(grid.store), false);

        await t.type(null, ' ');
        t.is(grid.store.first.isExpanded(grid.store), true);
    });

```

**Comment by marciogurka** [comment]
[+1 user](https://forum.bryntum.com/viewtopic.php?p=123588#p123588) reporting that
