### ISSUE TITLE
Unable to drag dependency to future tasks

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6679]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=123037#p123037)

Hi Team,

unable to create the dependency for future tasks . While creating the dependency for future tasks, gantt horizontal scroll was not increasing. 

I am able to reproduce this issue in bryntum advanced example https://bryntum.com/products/gantt/examples/advanced/. please find the video for ref:

Steps to reproduce:
change the task start date to  future year like video.
try to draw the dependency from task with past year to newly changed task. 
gantt Scroll was not moving to future task.

https://user-images.githubusercontent.com/75997756/235305529-8c58b42a-32ff-4b42-ab95-829e36a7cef5.mp4

**Comment by ExtAnimal** [comment]
The event is simply outside the rendered range of the Scheduler.

Either extend the startDate and endDate or the Scheduler, using an appropriate ViewPreset for a zoomed out view, or use `infiniteScroll`

In a *real* long running project, a zoomed out ViewPreset would be used with a startDate and endDate that encompassed all reasonable task starts and ends.
