### ISSUE TITLE
Editor Sass syntax error

### ISSUE THREAD

**Issue by naten3** [bryntum/support#670]
I'm trying to compile the Sass in my project to make customization easier, and it builds fine with Dart Sass as long as I fix this single-equals comparison in `/resources/core-sass/common/widget/editor.scss`.
```@if ($field-background-color = transparent)```
We can fix it in our local source for now but would like to not have to do so in future versions.

**Comment by matsbryntse** [comment]
Thanks for reporting, fixed for next release :)
