### ISSUE TITLE
Task Baseline columns

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6709]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=24840)

Hello,
Do you support displaying the baseline fields on the grid so on the grid table view you could have:

Name | Duration | Start | Finish | Baseline 1 Start Start | Baseline 1 Finish | Baseline 1 Duration | Start Variance | Finish Variance

I can't see this in any demos you have. If this is not possible, is this a feature you are planning to support soon?
Thank you
Paul

**Comment by matsbryntse** [comment]
Progress pushed to baselines-demo branch

**Comment by isglass** [comment]
Previously resolved, but ticket mistakenly left open
