### ISSUE TITLE
An option should be given to not use certain colors, when assigning random colors to items

### ISSUE THREAD

**Issue by SmileToWorld1** [bryntum/support#6724]
- **A couple of certain colors are using some special purposes. So, while assigning random colors to items, there should be option that some colors can discard from normal items color**. 

![image](https://user-images.githubusercontent.com/100558531/237014645-426bfda8-7936-4f2a-b99c-b962bb8abaff.png)

**Comment by isglass** [comment]
@SmileToWorld1 How colors are assigned is up to the application implementation. If you have a question related how to do that, please post on our support forum instead: https://forum.bryntum.com.
