### ISSUE TITLE
Should be possible to disable ArrowRight and ArrowLeft navigation between events

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6731]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=118187#p118187)

I need to add custom behavior for  'ArrowLeft' and 'ArrowRight'  event keys to navigate between events in scheduler. How do I disable Bryntums default behavior?
I also noticed that eventKeyDown listener is not registering ArrowLeft and ArrowRight

**Comment by matsbryntse** [comment]
Already possible to handle with
```

scheduler = new Scheduler({
            listeners : {
                eventKeyDown({ event }) {
                    const { key } = event;
                    if (key === 'ArrowRight' || key === 'ArrowLeft') {
                        event.preventDefault();
                    }
                }
            }
        });
```
