### ISSUE TITLE
Tooltip not displaying on children object inside taskRenderer

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6735]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24839&p=123552#p123552)

1. Use the bryntum demo here https://bryntum.com/products/taskboard/examples/config-panel/ or have a bryntum taskboard.

2. In the taskRenderer, add a coffee icon which contains a tag, class and tooltip. The taskRenderer should look like this:
```
// Custom task renderer
            taskRenderer({ cardConfig, taskRecord }) {
                cardConfig.dataset.prio = taskRecord.prio;
                cardConfig.children.header.children.icon = {
                  tag : 'i',
                  class : 'b-fa b-fa-coffee',
                  tooltip : {
                    html        : 'Click me and you won\'t believe what happens next',
                    newInstance : true
                  }
                }
            }
```

You will see that the tag and class property both work correctly. The tooltip property fails to work.

**Comment by isglass** [comment]
DomConfig / HTML does not have a `tooltip` attribute. Use `data-btip` instead
