### ISSUE TITLE
Nuxt 3 navigation doesn't work when 2 different components on pages

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6737]
To repro just  try to switch via pages using navigation buttons. Only one component might be displayed, that was shown first.

[bryntum-forum-sample.zip](https://github.com/bryntum/support/files/11433691/bryntum-forum-sample.zip)

[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=24862&p=123533#p123533)

My company is currently evaluating whether or not we will be using this product in our app. We are running a Nuxt app, and I am trying to have the Calender component on one page, and the Scheduler on a different page. 

However only the first component navigated to loads. There are no errors indicating what the issue is. The problem seems to arise during the import of the component, as when I remove the import, then both pages load, although one is blank because the component is no longer imported. 

Does anyone have any experience using these components in a Nuxt app?

**Comment by tcm151** [comment]
@chuckn0rris has there been any progress or updates on this issue? We are looking at whether we want to continue with our implementation or find another product

**Comment by matsbryntse** [comment]
@tcm151 Raising the prio on this one to (hopefully) get it fixed for v6.0.4. Sorry for the wait!

**Comment by matsbryntse** [comment]
@tcm151 This was actually fixed in August last year, did you have a chance to try the thin bundles out? Let me know if you still face issues and we'll try to help
