### ISSUE TITLE
Add strong typing to use EventRenderer and various events.

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6738]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24872&p=123592#p123592)

"Can you provide this example with TS version of NextJs v13? The type of Function is too broad to use EventRenderer and various events.

I want strong typing. I'd like to avoid answers telling me to use @ts-ignore.

https://bryntum.com/products/scheduler/examples/frameworks/react/javascript/vertical/build/"

**Comment by isglass** [comment]
Typings for `eventRenderer` are now 
```
eventRenderer: (detail: { eventRecord: EventModel, resourceRecord: ResourceModel, assignmentRecord: AssignmentModel, renderData: { event: EventModel, cls: DomClassList|string, wrapperCls: DomClassList|string, iconCls: DomClassList|string, left: number, width: number, height: number, style: string|Record<string, string>, wrapperStyle: string|Record<string, string>, eventStyle: string, eventColor: string, children: DomConfig[] } }) => string|object|DomConfig|DomConfig[]
```
