### ISSUE TITLE
Setting percentBar valueField doesn't effect the tooltip

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6746]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=24890&p=123672#p123672)

Hi,

Setting valueField on the percentBar works fine. However the information popup is not using the valueField instead calculating the value from children. See picture on popup which should display the value 70%

```javascript
     percentBar: {
          allowResize: false,
          valueField: "okrGrade"
        },

```
![bryntum bug.png](https://forum.bryntum.com/download/file.php?id=22230)

**Comment by matsbryntse** [comment]
Need to change the TaskTooltip `template`

https://bryntum.com/products/gantt/docs/api/Gantt/feature/TaskTooltip
