### ISSUE TITLE
Confusing behaviour of scheduler not allowing drag & drop zoomed out

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6750]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=24892&p=123710#p123710)

"Hi,

We have found a behaviour that we would classify as a bug in your Angular advanced example. 

If you zoom in you can drag a task but if you zoom out a lot the scheduler rejects the drag (event.valid equal false in afterTaskDrop event). This is because the task start/end date resolution is increased when zoomed out e.g. from day to month. So, zoomed out, only if you drag the task one month the date is actually changed although the task is clearly moved on the gantt.

From a user perspective this is indeed very confusing and it took us a long time understanding the background. The right behaviour should be that if you move a task in the gantt, that the user visually can see and allowed by scheduler, then it should snap into the new position.

https://bryntum.com/products/gantt/examples/advanced/"

https://github.com/bryntum/support/assets/16693227/ad70a662-ff6b-4bab-a59b-22f50a9ffaf2

**Comment by marciogurka** [comment]
User suggested a way of improvement [here](https://forum.bryntum.com/viewtopic.php?p=123987#p123987)

**Comment by chuckn0rris** [comment]
Won't fix. It might be changed with `timeResolution` setting as user desire.
