### ISSUE TITLE
Avatar overflow element tooltip should show all resource names

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6751]
<img width="339" alt="Screenshot 2023-05-10 at 14 58 43" src="https://github.com/bryntum/support/assets/218570/fad0e16c-02ae-4e70-a5d6-bccf2664084f">

**Comment by mazzafabio** [comment]
I guess it could be enough using `avatarTooltipTemplate` fn
`
    {
            type        : 'resourceassignment',
            ...
            avatarTooltipTemplate({ taskRecord, resourceRecord, assignmentRecord, overflowCount }) {
                let resourcesNameMissingHTMLOutput = '';
               
               // Just the last visible resource could have an **overflowCount** value
                if (overflowCount > 0) {
                    resourcesNameMissingHTMLOutput = taskRecord.assignments
                        .filter(a => a.resource)
                        .sort((lhs, rhs) => lhs.resourceName.localeCompare(rhs.resourceName))
                        .filter((element, index, array) => array.indexOf(element) > array.indexOf(assignmentRecord))
                        .reduce((htmlOutput, assignmentRecord) => {
                            return `
                                ${htmlOutput}
                                <br />
                                <div>${assignmentRecord.resourceName} ${assignmentRecord.units}%</div>
                            `;
                        }, '');
                }

                return `
                    <div>${resourceRecord.name} ${assignmentRecord.units}%</div>
                    ${resourcesNameMissingHTMLOutput}             
                `;
            }
        }
`
![image](https://github.com/bryntum/support/assets/50654914/cff16e0d-bcb9-4e60-8f66-630afa9fe8a7)
