### ISSUE TITLE
Error: Bryntum Grid bundle was loaded multiple times by the application

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6754]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24898&p=123739#p123739)

"Hi Team,

I have a React project and added gantt and schedulerpro dependencies to my project and getting following issue  The Bryntum Grid bundle was loaded multiple times by the application.

I am suprised because I did not import grid component yet and tried to follow advise of following link :  Grid/Gettingstarted/Es6bundle#troubleshooting

Unfortunalty I am not able neither my team to point out the issue we have."

![Capture d’écran 2023-05-10 190125.png](https://forum.bryntum.com/download/file.php?id=22244)

**Comment by marciogurka** [comment]
Will be solved with this one https://github.com/bryntum/support/issues/4670

**Comment by fungaldore** [comment]
Hi @marciogurka, I'm using Grid, Calendar, and SchedulerPro in a React app and encountering this same problem. I tried v5.6.0-beta-1 but I'm still getting this error. Will this actually be fixed in #4670?

**Comment by johnny090807** [comment]
After following #4670 I also still get the error in v5.6.0-alpha-1 with React. Which version is the fix in?

**Comment by SergeyMaltsev** [comment]
@johnny090807 
Please use latest stable 5.6.0 version.
Please open a question on [support forum](https://forum.bryntum.com/) with details on the problem and attach your code which we can run and build.

**Comment by jsakalos** [comment]
If it is React + Vite, you need to edit `vite.config.js`:
```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
    plugins      : [react()],
    optimizeDeps : {
        include : ['@bryntum/scheduler', '@bryntum/scheduler-react']
    },
    base  : '',
    build : {
        // Suppress warning for chunk size
        chunkSizeWarningLimit : 3000,

        // Turn warnings into errors. For build testing purposes
        // https://rollupjs.org/configuration-options/#onlog
        rollupOptions : {
            onLog(level, log, handler) {
                if (level === 'warn') {
                    handler('error', log);
                }
                else {
                    handler(level, log);
                }
            }
        }
    }
});

```
Add all products you use to `optimizeDeps`

Also, take care not to import normal (non-thin) npm. Those contain more than one product packed.

**Comment by matsbryntse** [comment]
@johnny090807 @fungaldore  Can you confirm all is working now for you?

**Comment by johnny090807** [comment]
Yes it was an issue with react building twice. Thanks anyway and have a great year!

**Comment by isaelsilva1039** [comment]
Even using all the thin packages, the same error persists. I believe it might be a Bryntum-related issue. I'll describe some tests I conducted that worked for me (in development).


Notice that it accuses the package of being used more than once, however, it is only being used once.

![image](https://github.com/bryntum/support/assets/71187451/c8bfcae9-96d1-47a5-bbe6-4b7fd5158c87)

Quando eu faço o seguinte teste, funciona 
![image](https://github.com/bryntum/support/assets/71187451/890d8861-4c5d-4167-82b4-d93ccc84cfc3)

For different thin packages, you return (core and the version), which causes the error.

**Comment by SergeyMaltsev** [comment]
@isaelsilva1039 

Make sure that you have used the same version for all `*-thin` packages and didn't install/import full packages.
We have "Multiple products" guides for each framework in [online docs](https://bryntum.com/products/grid/docs/).
See inside Integration section.

Please send a question to our [support forum](https://forum.bryntum.com/) and attach your application so we can check what's is in there.
