### ISSUE TITLE
WidgetHelper.showContextMenu does not display the context menu when using Number[]

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6762]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24925&p=123858#p123858)

"Hi,

I added the following code to the [inline-demo](https://bryntum.com/products/schedulerpro/examples/inline-data/) example:

```
import { SchedulerPro, WidgetHelper } from '../../build/schedulerpro.module.js?467718';
...
listeners: {
    scheduleClick: () => {
        console.log("show context menu");
        WidgetHelper.showContextMenu([300, 300], { items: [ { id: 'addItem', icon: 'add', text: 'Add' } ] });
   }
},
```

When I click in the background of the scheduler, the console log is correctly displayed, however no context menu is shown."

Checking the [docs](https://bryntum.com/products/schedulerpro/docs/api/Core/helper/WidgetHelper#function-showContextMenu-static), you could use a Number array of coordinates to display the context menu, but when you try, the following error is triggered

> Uncaught TypeError: Cannot read properties of undefined (reading 'defaultView')

If you use an element, it displays correctly.

**Comment by ExtAnimal** [comment]
Fix:

```
    static showContextMenu(element, config) {
        const me = this;

        if (me.currentContextMenu) {
            me.currentContextMenu.destroy();
        }

        if (element instanceof HTMLElement) {
            config.forElement = element;
        }
        else {
            config.forElement = document.body;
            if (Array.isArray(element)) {
                element = new Point(...element);
            }
            if (element instanceof Point) {
                config.align = {
                    position : element
                };
            }
        }

        me.currentContextMenu = Widget.create(config, 'menu');

        me.currentContextMenu.ion({
            destroy : () => {
                me.currentContextMenu = null;
            }
        });

        return me.currentContextMenu;
    }
```
