### ISSUE TITLE
Start and End Dates are wrong after importing .mpp file

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#6766]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=123768#p123768)

Hi,

I am having some discrepancies with the start and end dates when I use the sample .mpp file provided in the demo. These discrepancies occur both when I import the .mpp file into the demo on your website and when I import it into a Microsoft Project itself.

I noticed that the start and end dates do not match between the two platforms, which is causing some confusion and disrupting the flow of my work.

I have attached the sample .mpp files and results.

Thanks,
Sefa DOĞAN

mpp-file: [another-sample-project.zip](https://github.com/bryntum/support/files/11460913/another-sample-project.zip)

**Comment by canonic-epicure** [comment]
Also requested [here](https://forum.bryntum.com/viewtopic.php?p=147313#p147313)

**Comment by canonic-epicure** [comment]
Also marking the internal ticket explicitly here: https://github.com/bryntum/support/issues/6769

**Comment by matsbryntse** [comment]
Dupe? https://github.com/bryntum/support/issues/3211

**Comment by canonic-epicure** [comment]
Looks like it, yes.
