### ISSUE TITLE
Started tasks should preserve their start date value

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#6769]
Started tasks should behave similar to manually scheduled ones:

1. they don't fallback to the project start 
2. they aren't pinned with a constraint when moving
3. Tasks should be rescheduled if the % done is set to 0

Implementing this will fix: https://github.com/bryntum/support/issues/6766

Related https://forum.bryntum.com/viewtopic.php?t=11101

**Comment by canonic-epicure** [comment]
Duplicate of https://github.com/bryntum/support/issues/3211?

**Comment by canonic-epicure** [comment]
Closing as duplicate of #3211.
