### ISSUE TITLE
Opened Event is overwritten by other records form the Task Editor

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6773]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24900&p=123751#p123751)

"Issue: Opening the Task Editor by double-clicking on an event block causes changes on other records to override the double-clicked record.

E.g
Event A is selected from the scheduler (double-click). This opens a grid in the TaskEditor (see background below).
When a new row - "Event B" - is added to the grid by clicking the "add" button, Event A's values are subsequently overwritten to match Event B.
If another row were added - "Event C" - Event A will then match Event C - or the value of whatever record was changed. 
It appears to be reference connected to grid changes.

Codepen: https://codepen.io/d365dev/project/editor/8a1e5b60ee0c052b617d25235377ca89
A video clip depicting the issue is attached; I am available to add more context wherever helpful.

Background: 
A grid has been added to the taskEditor, in a new tab. The default tabs are hidden.
The intent is to provide an option to edit related records at the same time."

**Comment by isglass** [comment]
Usecase out of scope of what the task editor is intended to handle
