### ISSUE TITLE
Displaying a tooltip while the data is being updated throws errors

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6782]
In basic example add
```
    features : {
        eventTooltip: {
            anchorToTarget: false,
            allowOver: true
        }
    }
```

In console
```
setTimeout(()=>{scheduler.eventStore.first.endDate = new Date()}, 5000)
```

Hover on first event, see tooltip and wait. Error thrown on endDate changed
```
oltip.js:935 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'position')
    at Tooltip.alignTo (Tooltip.js:935:40)
    at EventTooltip.onRecordUpdate (TooltipBase.js:344:26)
    at EventStore.trigger (Events.js:1504:44)
    at AbstractPartOfProjectStoreMixin.js:62:52
    at Array.forEach (<anonymous>)
    at ProjectModel.dataReady (AbstractPartOfProjectStoreMixin.js:61:56)
    at ProjectModel.trigger (Events.js:1504:44)
    at ProjectModel.doCommitAsync (SchedulerCoreProjectMixin.js:493:20)
a
```
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24949&p=124076#p124076)

**Comment by ExtAnimal** [comment]
Fix is in `Scheduler/feature/base/TooltipBase.js`:

![Screenshot 2023-05-17 at 11 12 16](https://github.com/bryntum/support/assets/200516/2ad88a4d-e41d-4959-8686-c66223611cdd)

**Comment by ExtAnimal** [comment]
Though should it actually do anything? Or should it hide if the event has moved from its initial point? In which case whny was this added?

Need to ask the original author what the purpose was: https://github.com/bryntum/bryntum-suite/pull/3323
