### ISSUE TITLE
Copy Paste between schedulers are not possible

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6786]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24965&p=124131#p124131)

Hi there,

A few patches ago I am that I could copy/paste shifts from one scheduler to another in this example: https://bryntum.com/products/scheduler/examples/shared-crudmanager/

This does not seem possible any more?

Thanks

**Comment by isglass** [comment]
Closed because of inactivity, info was requested but no response
