### ISSUE TITLE
Stm has not updated values for canUndo/canRedo at the moment of event trigger

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6797]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24974&p=124191#p124191)

Gantt Advanced demo

In UndoRedoBase.js make this change 
```
    updateStm(stm) {
        this.detachListeners('undoredo');

        stm?.ion({
            name          : 'undoredo',
            recordingstop : 'updateUndoRedoControls',
            restoringstop : 'updateUndoRedoControls',
            queueReset    : 'updateUndoRedoControls',
            // disabled      : 'updateUndoRedoControls', // <<< comment this line
            thisObj       : this
        });
    }
```

In demo move any task, click undo. See both buttons are disabled. If you dive into the code, you'll find that `recordingstop`/`restoringstop` has old values for canUndo/canRedo flags in handlers, and state was updated in `disabled` event, which is unclear for users and shouldn't work like that in the scenario we mentioned here.

**Comment by canonic-epicure** [comment]
The way it is implemented right now, is that STM is temporarily disabled right after state restore, then a `project.commitAsync()` is performed and then STM is enabled. The purpose of disabling the STM is to not pick up this "maintenance" commit as a new STM transaction. 

That is why updating the controls state on `disabled` event is required. I'll update the docs to reflect that.
