### ISSUE TITLE
`lagUnit` for newly created dependency in `DependencyTab` should be use default model field value

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6802]
From the code of DependencyTab.js
```
        const [newDep] = grid.store.insert(0, {
            type              : DependencyType.EndToStart,
            lag               : 0,
            lagUnit           : TimeUnit.Day,
            [me.negDirection] : me.record
        });
```

[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=24993&p=124260#p124260)

Hi guys, 
Is there a way to change lagUnit to "minute" for newly created dependency in predecessors/successors tabs in taskEditFeature?
I've customized lagUnit field in the DependencyModel, however it worked only for existing dependencies, the newly added are displayed with "days" unit as following:
![lagUnit.png](https://forum.bryntum.com/download/file.php?id=22362)
![lagUnit.png](https://forum.bryntum.com/download/file.php?id=22362)

**Comment by isglass** [comment]
Probably we should just remove `lagUnit` there, making it use the default value from DependencyModel instead
