### ISSUE TITLE
Web page freezes when using Scheduler with big data set

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6803]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24984&p=124214#p124214)

"Hi
In our application we use Scheduler 5.3.1 and it works quite well, but when we load a large dataset, say 50,000 records, the whole page is frozen and we cannot use our application until the loading is complete. Our server returns data in less than one second, but the website freezes for 15-20 seconds. Sometimes a window pops up that the card is not responding. We noticed that there is some kind of bottleneck between the "beforeLoad" and "load" methods of crudManager. Is there any lazy loading? Or is there something we can do to allow Schduler to load but keep the website alive so the user can do something else?
This can be reproduced in this demo https://bryntum.com/products/scheduler/examples/bigdataset/
In custom mode, set resources to 10,000 and events to 100. The web page will freeze until data is loaded."

**Comment by isglass** [comment]
10,000 resources with 100 events each is much more (20x) than 50,000 records

**Comment by Malnen** [comment]
Yes. It was just an example. The main problem is that the website is frozen

**Comment by matsbryntse** [comment]
At some point, for sure the website will freeze if you load millions of records. Can you please provide a test case where you have problems? Did you do a performance analysis using Chrome Dev Tools?

**Comment by matsbryntse** [comment]
Need a better test case, will reopen if we get one.
