### ISSUE TITLE
Add support to renderer function to render JSX components

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6806]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=24999&p=124289#p124289)

"We can render the JSX in the tooltip (gray background object) but it is not possible in the "day event" itself (orange object). 

Would it be possible to add the ability to insert JSX into the day event so we can add javascript events such as onClick?"
![Screenshot 2023-05-17 094039.png](https://forum.bryntum.com/download/file.php?id=22367)

**Comment by matsbryntse** [comment]
Dupe #6792
