### ISSUE TITLE
Dependencies being able to drag before initial dependency

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6813]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25023&p=124447#p124447)

In the [Documentation demo](https://bryntum.com/products/schedulerpro/docs/api/Scheduler/feature/Dependencies) regarding dependencies, the user can drag a second dependency before the first one.

You can't reproduce that in the complete demo[https://bryntum.com/products/schedulerpro/examples/dependencies/](https://bryntum.com/products/schedulerpro/examples/dependencies/)

https://github.com/bryntum/support/assets/16693227/79ed3844-78c0-449d-8ca7-29de9d1fa988

**Comment by matsbryntse** [comment]
Working as designed. Scheduler feature vs Scheduler Pro engine
