### ISSUE TITLE
Nested events should keep relative position when crossing non-working periods

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6821]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24958&p=124202#p124202)

[Another request ](https://forum.bryntum.com/posting.php?mode=reply&t=24876)
The problem is that the nested events do not keep track of their position relative to each other.
You can this in my examples here:

[Screen Recording 2023-05-16 at 5.06.51 PM.mov](https://forum.bryntum.com/download/file.php?id=22346)

Task 1. There are no gaps in working-time between the subtasks in this series, but dragging subevents across the weekend causes them to overlap on the next available working day. I would expect that the original order is preserved after moving the parent task (i.e. no gaps/overlaps after drop).
Task 2. Overlapping subtasks are not preserved. I would expect the same order & overlaps after drop.
Task 3. Gaps between tasks get larger/smaller depending on where you drop the parent task. I would expect the same gap of working time no matter where I drop it.

I attached the example I modified (nested events example with a working day calendar with the modifications you suggested).

**Comment by canonic-epicure** [comment]
Experimental code in `6821-parent-delay-experiment` branch
