### ISSUE TITLE
Should be possible to sort only clicking on the icon

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6827]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25054&p=124583#p124583)

Hey team,

The grid column headers have a feature where when the user clicks anywhere on the header, it sorts the column. I'd like to adjust this to only sort when the user clicks on the sort icon instead of the entire header. ![Screenshot 2023-05-22 at 5.39.52 PM.png](https://forum.bryntum.com/download/file.php?id=22432)

**Comment by BrandonDH** [comment]
Hi team, am I able to grab the latest `5.3.7` release and have this feature? I did not see this in the release email list. thanks!
