### ISSUE TITLE
View Other Users Working on your Project

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#6859]
Are you planning a feature to highlight when another user is working on the Gantt at the same time?  So you may see their avatar appear or be notified that they are working on those tasks.

Do you support web socket technologies?

**Comment by matsbryntse** [comment]
> Are you planning a feature to highlight when another user is working on the Gantt at the same time? So you may see their avatar appear or be notified that they are working on those tasks.
No plan yet, sounds a bit like an application-domain problem but feel free to share some more details of your desired UX and we can discuss internally


> Do you support web socket technologies?
Yes, and we're working on docs + demos for this now

**Comment by matsbryntse** [comment]
Ok we already fully support it. Please start a thread in our support forums and we can try to get you started with the web sockets. (we only use github for bugs / feature requests).

https://forum.bryntum.com/
