### ISSUE TITLE
Not possible to switch am/pm in time picker in mobile Safari

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6866]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=24909&p=124972#p124972)

Open https://bryntum.com/products/calendar/examples/print/ in Safari on iPhone
Start edit task. Try to change AM to PM for any event date (start/end). It remains old and cannot be changed.

**Comment by chuckn0rris** [comment]
Another [report ](https://forum.bryntum.com/viewtopic.php?f=51&t=25641&p=127562#p127562)

**Comment by isglass** [comment]
Seems not working in desktop Safari either
