### ISSUE TITLE
[REACT] timeAxisHeaderMenu and headerMenuFeature not disabling

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6870]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25147&p=125028#p125028)

If you configure a React demo with the following

```
timeAxisHeaderMenu : false,
 headerMenuFeature: false,
```
or
```
timeAxisHeaderMenu : { disabled: true },
 headerMenuFeature: { disabled: true },
```

It's not working and the menu is still displayed, if you configure that in a plain JS, it work as expected.

**Comment by swapnakonakanchi** [comment]
Hi Team, Any update on this.

**Comment by jsakalos** [comment]
It is not reproducible with the latest version (6.0.3). The proper configuration is:
```
const ganttConfig = {
    timeAxisHeaderMenuFeature : false,
    headerMenuFeature : false,
    // ...
```

Closing as not reproducible
