### ISSUE TITLE
Implement paging support in Scheduler

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#69]
Reference: https://www.bryntum.com/forum/viewtopic.php?f=44&t=11299

https://www.bryntum.com/forum/viewtopic.php?f=51&t=18916&p=93534#p93534
https://www.bryntum.com/forum/viewtopic.php?f=51&t=19030&start=10

We need to synchronize resource, event, assignments and dependencies stores while paging. 

There should also be a solution for CrudManager.

**Comment by ManishFP** [comment]
Any updates on this? Is there a rough date that you have in mind or is this not going to be done at all?
Is there a RoadMap page for the Scheduler where I can see what new features are coming?

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=117699#p117699) user asking for this for SchedulerPro also.

**Comment by chuckn0rris** [comment]
Another request https://forum.bryntum.com/viewtopic.php?f=44&t=26010&p=129662#p129662

**Comment by JockeLindberg** [comment]
Another request for SchedulerPro https://forum.bryntum.com/viewtopic.php?f=9&t=28921&p=145559#p145559

**Comment by AamilShohail** [comment]
Hi team, 
May I know if this feature is enabled in SchedulerPro? Having this feature would be very helpful to me.

**Comment by matsbryntse** [comment]
It will be supported in both Scheduler + Scheduler Pro
