### ISSUE TITLE
Time ranges grid has empty line in Gantt demo

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#6902]
## Steps

* Open `Gantt/examples/timeranges/` demo
* See empty line in place of `Critical milestone`

![image](https://github.com/bryntum/support/assets/57486330/b3b61a2b-c0ca-4f76-906e-aed033289730)

**Comment by ExtAnimal** [comment]
It's the icon class `b-fa` being added to the row which gets it `display: var(--b-fa-display, inline-block);`
