### ISSUE TITLE
Issue while restoring state with multiple filters

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6919]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25201&p=125385#p125385)

https://bryntum.com/products/gantt/examples/fieldfilters/

https://github.com/bryntum/support/assets/7203098/6ffcf1d0-f620-4c9e-a09f-fb6c0297e6fa

**Comment by isglass** [comment]
Fixed by related changes
