### ISSUE TITLE
`exportProgressMask` does not change value on PDF Export

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6924]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25208&p=125484#p125484)

"Hi,

when I set the config option 'exportProgressMask' the text won't be replaced.
I can reproduce it on your demos."

- Go to https://bryntum.com/products/schedulerpro/examples-scheduler/export/
- Add the configuration like the following
```
features : {
            pdfExport : {
                exportProgressMask: 'test message'
            }
        }
```
Expected behavior: the custom message is displayed when waiting for the export.

But as you can see in the attached video, is not working correctly

https://github.com/bryntum/support/assets/16693227/cdf895b1-9c1c-4e9c-ab50-b621094181d0

**Comment by abrenner94** [comment]
Any news regarding this issue @marciogurka ?

**Comment by matsbryntse** [comment]
Should be fixed for the next patch release!

**Comment by abrenner94** [comment]
Thank you!
