### ISSUE TITLE
`beforeRemove` for `eventStore` not prevent deletion in SchedulerPro

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6941]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25253&p=125642#p125642)

In dependencies demo add `beforeRemove` listener and return `false` to prevent all delete actions

```
const scheduler = new SchedulerPro({
    // A Project holds the data and the calculation engine for Scheduler Pro. It also acts as a CrudManager, allowing
    // loading data into all stores at once
    project : {
        autoLoad   : true,
        loadUrl    : './data/data.json',
        eventStore : {
            fields : ['highlight'],
            listeners : {
                beforeRemove : () => {
                    console.log(1);
                    return false
                }
            }
        }
    },

```

Try to remove using Delete key press. It's still possible to remove an event. 
It's working correct in Scheduler but not in SchedulerPro

**Comment by canonic-epicure** [comment]
It seems the event is not removed correctly, but its assignment is. Fixing.

**Comment by canonic-epicure** [comment]
Actually it seems it works as intended. 

When the event store uses multi-assignments mode (which is a default for scheduler pro), the "Delete" key removes the currently selected _assignment_. The "Delete event" context menu removes the event itself (and consequently all its assignments). 

These are 2 different UI actions, even that looks very similar, so user need to handle them both and add `beforeRemove` listener for the Assignment store as well.
