### ISSUE TITLE
Freeze after copy pasting top level node

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6956]
http://lh/bryntum-suite/gantt/examples/grouping/

Clear grouping
Click top row
Copy paste a few times quickly

https://github.com/bryntum/support/assets/218570/21f72489-b0a7-406f-bf79-a3f8896c5169

**Comment by canonic-epicure** [comment]
Does not seem to be reproducible

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/b71161e4-874c-4e72-ade1-f78b071de9c2

**Comment by canonic-epicure** [comment]
Any extra details how to reproduce?
