### ISSUE TITLE
Should be possible to show chart with no columns

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6978]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25288&p=125805#p125805)

Hello,
Is it possible to completely remove the default "Name" column from the Gantt control and also remove the "double arrow" button between the gantt chart and the "Name" column?  Please see a screenshot attached.
We have a requiremet to display only the Gantt chart without any columns. 
![BryntumGanttColumns.png](https://forum.bryntum.com/download/file.php?id=22855)

**Comment by ExtAnimal** [comment]
GanttBase.js needs

```
    changeColumns(columns, currentStore) {
        if (columns) {
            let cols = columns;

            if (!Array.isArray(columns)) {
                cols = columns.data;

                // Need to pull the taskstore in, to make sure any fields added by columns are added to it
                this._thisIsAUsedExpression(this.taskStore);
            }

            // Always include the name column
            if (!cols.some(column => {
                const constructor = column instanceof Column ? column.constructor : ColumnStore.getColumnClass(column.type) || Column;

                return constructor === NameColumn || constructor.prototype instanceof NameColumn;
            })) {
                cols.unshift({
                    type : 'name'
                });
            }
        }

        return super.changeColumns(columns || [], currentStore); // Just added " || []"
    }
```

Then `columns : null` will work.

**Comment by Andemki** [comment]
> GanttBase.js needs
> 
> ```
>     changeColumns(columns, currentStore) {
>         if (columns) {
>             let cols = columns;
> 
>             if (!Array.isArray(columns)) {
>                 cols = columns.data;
> 
>                 // Need to pull the taskstore in, to make sure any fields added by columns are added to it
>                 this._thisIsAUsedExpression(this.taskStore);
>             }
> 
>             // Always include the name column
>             if (!cols.some(column => {
>                 const constructor = column instanceof Column ? column.constructor : ColumnStore.getColumnClass(column.type) || Column;
> 
>                 return constructor === NameColumn || constructor.prototype instanceof NameColumn;
>             })) {
>                 cols.unshift({
>                     type : 'name'
>                 });
>             }
>         }
> 
>         return super.changeColumns(columns || [], currentStore); // Just added " || []"
>     }
> ```
> 
> Then `columns : null` will work.

@ExtAnimal, Is it something that user of the Bryntum Gantt component can add to the application where this component is used or this is an internal change for the Gantt component and can be done only by Bryntum Dev team?
