### ISSUE TITLE
[REACT] React component is not rendered correctly on expand / collapse

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#6987]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25298&p=125868#p125868)

"Hey there!

I'm defining a custom column renderer. Everything is fine on the first run of the renderer, but when the renderer runs a second time (after the tree node has been expanded), the value of data.record.visibleDescendantCount goes from 0 => 1, but the component never receives the newly passed props. Is this because the component is treated as a template, and not as a standard react component?

If so, how would I render an element that renders differently based on the context provided in arguments of the column renderer? i.e. where it looks one way when visibleDescendantCount = 0, and another when visibleDescendantCount = 1?"

Added a demo with the configuration shared by the user, if you check the video, the console.log shows the correct value, but the component is not correctly updated.

[simple.zip](https://github.com/bryntum/support/files/11728299/simple.zip)

https://github.com/bryntum/support/assets/16693227/37189440-c862-449d-a8dd-bc38d47f56c9

**Comment by jsakalos** [comment]
The problem here is that the rendered React component is never made to re-run. It is caused by the fact that config, including columns and the renderer, is contained in state so never changing. I'm looking for a solution.
