### ISSUE TITLE
[VUE] An exception when use workingTime config in calendar timeline view

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6995]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25269&p=125948#p125948)

Not able to repro this in vanilla example.  Please read forum topic, `workingTime` that throws an error depends on current  time.

See app attached below

https://github.com/bryntum/support/assets/7203098/aff90109-b9fe-4033-b7f7-f5138c104b64

[bryntum-calendar-vite.zip](https://github.com/bryntum/support/files/11738789/bryntum-calendar-vite.zip)

**Comment by jnarowski** [comment]
JP from Spectora here. This is a blocker for us, as we can't release calendar availability without this. Right now we have just gotten around it by hard coding the day starting at 5am and ending at 11pm. If anyone opens the calendar before 5am or after 11pm it crashes.
