### ISSUE TITLE
[REACT] StateTrackingManager not working correctly

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7004]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25305&p=125978#p125978)

Check the attached project, the STM looks correctly configured, but no actions are being registered after changing data inside the Scheduler.
[bryntum-example-stm.zip](https://github.com/bryntum/support/files/11750997/bryntum-example-stm.zip)

**Comment by canonic-epicure** [comment]
So it seems we do not support passing the pre-configured instance of STM to the project model, only a config object:
This will not work (as in the example):
`new ProjectModel({ stm : stm })`
this will work:
`new ProjectModel({ stm : { autoRecord : true } })`
