### ISSUE TITLE
TimeZone and syncDataOnLoad

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#7012]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=126029&sid=5875d59f87aef620b752609d445b7409#p126029)

At the moment, syncDataOnLoad will break time zone conversion. We need to fix that.

Also, we need to come up with a solution to add and update records that is not time zone converted to a store that is time zone converted.

**Comment by chuckn0rris** [comment]
another [request](https://forum.bryntum.com/viewtopic.php?f=44&t=23445&p=127517#p127517)
