### ISSUE TITLE
Chained store for eventStore and resourceStore don't work for SchedulerPro

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7036]
Please see topic for details. Basically user wants to have filtered set of data from single project in 2 SchedulerPro instances. It doesn't work for eventStore and resourceStore.

[Forum post](https://forum.bryntum.com/viewtopic.php?t=25295&start=10)

Hello Marcio, 

Alright, now I see it. Yes, it seems like that solves the problem. Thank you for that.

However, this solution raises more questions. What if I need to chain both resources and events stores, for example? Since I can't use the resourceStore and the eventStore properties, what should I do?

Currently, it's not a requirement for me, but I would appreciate knowing the answer for future reference.

Thank you for your support!

**Comment by ExtAnimal** [comment]
Can this be closed?

It seems obvious that if you use different stores in two Schedulers, there will be two Projects, since a Project owns all of the Stores for a Scheduler.

You can't share one Project but expect there to be different stores somehow between each Scheduler.

**Comment by chuckn0rris** [comment]
See the comment above
