### ISSUE TITLE
Available slot for `startDate` calculates wrong when non-working periods defined

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7038]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25372&p=126341#p126341)

Here
https://www.bryntum.com/products/schedulerpro/examples/resource-non-working-time/
If change day to next with forward arrow of dateField, new date will go to far forward and jump next available slot. 
If click back arrow and forward arrow again, it will jump to another slot. If repeat back-forward, date will change again.

https://github.com/bryntum/support/assets/7203098/fe9a5274-a132-40cb-8dd4-e2c2df7b1128

**Comment by canonic-epicure** [comment]
So this happens because the `StartDateField` increments its value by "working" time. Also in that example `hoursPerDay` config of the project is set to `24`. So it shifts the events over several days. 

This seems to be unexpected for the user, should be changed to some other behavior may be?
