### ISSUE TITLE
shiftNext initiates partnered scheduler updated when partner was removed before

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7045]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25391&p=126382#p126382)

Hi Team,

As you know we use: https://bryntum.com/products/scheduler/examples/drag-between-schedulers/
structure and we have already utilised independent scrolling using - the 'removePartner' function.

However, if we use shiftNext() or shiftPrevious() for each scheduler instance they still move together.
Is this something we can do or would you suggest some option to get the following functionality?
![grid.png](https://forum.bryntum.com/download/file.php?id=22991)

As you can see we have a lock/unlock method with a padlock to activate independent scrolling using removePartner/addPartner

We want to introduce two arrows as per the picture so that we can navigate the time axis. 
When we remove the partner scheduler we should be able to navigate only the bottom grid unit by unit in time axis by using arrows.

Appreciate your help.
![grid.png](https://forum.bryntum.com/download/file.php?id=22991)

--------------------------------
Reproducible here https://bryntum.com/products/scheduler/examples/partners/
By adding this code in tbar
```javascript
{
    type : 'button',
    text : 'shift next',
    onAction : () => topScheduler.shiftNext()
}
```

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=128421#p128421) asking for this

**Comment by taauntik** [comment]
https://github.com/bryntum/support/issues/7542
