### ISSUE TITLE
Sass: Compatibility with Dart-Sass

### ISSUE THREAD

**Issue by naten3** [bryntum/support#705]
I know it's probably on your radar already but we had to switch our project over to node-sass to compile the Bryntum sass because dart-sass no longer supports compound selectors, eg `@extend .b-fa-check:before`
https://sass-lang.com/documentation/breaking-changes/extend-compound

Also I think lib-sass is more forgiving about extending classes which weren't declared earlier. This causes errors in dart-sass without !optional

We don't need this fixed urgently but lib-sass will stop supporting extending compound selectors in the future.

**Comment by matsbryntse** [comment]
We're moving to theming based on native CSS variables
