### ISSUE TITLE
DateHelper returns wrong week number

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7053]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25405&p=126445#p126445)

"Hi

The DateHelper week formatting does not seem to follow the normal ISO-8601 standard, where the first week of the year is based on first 4-day week. This is commonly used in Europe.

Is this meant to follow another standard or is it a bug? We will switch to the Luxon package for now.

See attachments for example."

![week_number_code.JPG](https://forum.bryntum.com/download/file.php?id=22998)
![week_number_result.JPG](https://forum.bryntum.com/download/file.php?id=22997)

**Comment by taauntik** [comment]
This is a localization issue.
Javascript uses Sunday as the weekStartDay by default.

Changing the locale file should solve the issue
```javascript
    DateHelper : {
        weekStartDay   : 1
    }
```
