### ISSUE TITLE
`beforeDragMoveEnd`  and `beforeDragResizeEnd` has not correct event ids

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7059]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=25070&p=126438#p126438)

Add to basic demo 

```
    listeners: {
        beforeDragMoveEnd: async ({ eventRecord, validation }) => {
            console.log(eventRecord.id);
            return false;
        },
        beforeDragResizeEnd: async ({ eventRecord, validation }) => {
            console.log(eventRecord.id);
            return false;
        }
    }
```

Try to resize, try to drag-n-drop. See different ids logged in console, but no one is correct.

**Comment by canonic-epicure** [comment]
Will be best if someone who is more in the calendar context will check this issue. It seems the calendar indeed creates a new empty record when drag starts and copies source record data into it. Then this "proxy" record is used when event is fired. There's probably a logical explanation of this and probably a fix is quite simple.

**Comment by chuckn0rris** [comment]
Another [report](https://forum.bryntum.com/viewtopic.php?f=54&t=25606&p=127367#p127367)

**Comment by marciogurka** [comment]
User added a note about that [here](https://forum.bryntum.com/viewtopic.php?p=127416#p127416)

**Comment by ExtAnimal** [comment]
I believe this ticket is fixed by this: https://github.com/bryntum/bryntum-suite/pull/7549

Assigning @mazzafabio so that he can check and close this ticket if that is the case.
