### ISSUE TITLE
Export to PDF feature missing paper formats

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7065]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25415&p=126497#p126497)

"I have a question regarding the pdfexport and its "paperformat" property. According to the documentation the formats "A1" and "A2" are available. But in the dropdown these two are not selectable. If I set the value "A1" for the "paperformat" property the export fails -> others are working. Is there another property that has to be set and is not in the documentation?"

Checking the `Grid/feature/export/Utils.js` we have

```
export const PaperFormat = {
    A6 : {
        width  : 4.11,
        height : 5.81
    },
    A5 : {
        width  : 5.81,
        height : 8.25
    },
    A4 : {
        width  : 8.25,
        height : 11.69
    },
    A3 : {
        width  : 11.69,
        height : 16.49
    },
    Legal : {
        width  : 8.5,
        height : 14
    },
    Letter : {
        width  : 8.5,
        height : 11
    }
};
```

So we're missing A1 and A2. Do we support that and need to add that configuration? Or do we need to update our docs and remove those options?

**Comment by ghulamghousdev** [comment]
+1 for this: https://forum.bryntum.com/viewtopic.php?p=147123#p147123

**Comment by ghulamghousdev** [comment]
Another report here: https://forum.bryntum.com/viewtopic.php?p=150034#p150034

In our docs https://bryntum.com/products/gantt/docs/api/Grid/feature/export/PdfExport#config-paperFormat, we mention that paper format can be `A1`, `A2`, ... but when applying either A1 or A2 in config, it fails.

**Comment by ghulamghousdev** [comment]
This is happening because we have a missing entries for `A1 and A2` in the `PaperFormat Object` in `Grid/feature/export/Utils.js`.
