### ISSUE TITLE
Event drop context data conflict

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7066]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25420&p=126520#p126520)

Hi I work with angular 14 and scheduler 5.3.7.

I found some conflict in "eventDrop" event, some times I got new "newResource" different from "targetEventRecord" resource id.
![screen-capture (7).gif](https://forum.bryntum.com/download/file.php?id=23016)

I create some demo that print in the console when you get conflict between this two objects.

Expect:
If I got "targetEventRecord" I expect to get in the "newResource" the "targetEventRecord's" resource.

For reproduce:
1) Take a job like you see in the gif in max top point you can.
2) Drag the job until you see that the target job as in the gif enter to focus but the  dragged job is on the previous resource.
3) drop.

You will see in the browser console the conflict.

--------------------------------------------------------
Reproducible here https://bryntum.com/products/scheduler/examples/basic/
with this code
```javascript
    listeners : {
        eventDrop(event) {
            console.log(event);
            console.log('target event resource id', event.context.targetEventRecord.resourceId);
            console.log('new resource', event.context.newResource.id);
        }
    }
```

**Comment by yakeer** [comment]
We would appreciate a quick fix here,
Right now we've implemented a workaround to overcome this issue, but the workaround has a performance degradation to our app. 

Thanks.

**Comment by matsbryntse** [comment]
Fix is on the way!
