### ISSUE TITLE
Zoom To Level With offset not working

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7074]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25436&p=126614#p126614)

Hi I work with angular 14, and after upgarde the scheduler from 5.3.6 to 5.3.7 I found that the zoomToLevel with zoomPosition is broken again.

I create some demo that reproduce the problem.

Reproduce steps:
1) Run the app.
2) Click on zoom in/out buttons in the top toolbar.

----------------------------------------
Use this code in basic scheduler demo to Reproduce
```javascript
    tbar : [
        {
            type : 'button',
            text : 'zoom in',
            onAction : (props) => {
                const sc = props.source.parent.parent;
                console.log(sc);
                sc.zoomToLevel(sc.zoomLevel + 1, {
                    zoomDate     : new Date(2017, 0, 1, 12),
                    zoomPosition : sc.getCoordinateFromDate(new Date(2017, 0, 1, 12)),
                });
            }
        },
        {
            type : 'button',
            text : 'zoom out',
            onAction : (props) => {
                const sc = props.source.parent.parent;
                console.log(sc);
                sc.zoomToLevel(sc.zoomLevel - 1, {
                    zoomDate     : new Date(2017, 0, 1, 12),
                    zoomPosition : sc.getCoordinateFromDate(new Date(2017, 0, 1, 12)),
                });
            }
        }
    ]
```

**Comment by Planit-Scheduler-Solutions** [comment]
Hi, any updates on this. 
We cannot perform version upgrades from 5.3.6v, as this operation is the default operation for users.

**Comment by mazzafabio** [comment]
Hello :)
I write you on forum https://forum.bryntum.com/viewtopic.php?p=128181#p128181
let me know if it worked
