### ISSUE TITLE
"No color" looks like white color and checkmark not updating

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#7080]
http://lh/bryntum-suite/gantt/examples/taskstyles/

- [x] Replace with other color? 

- [x] Checkmark not updated when selecting new color with menu open

<img width="276" alt="Screenshot 2023-06-27 at 09 11 23" src="https://github.com/bryntum/support/assets/218570/9d404103-ddb3-4269-b729-18041b81b948">

**Comment by JockeLindberg** [comment]
For history: White color is actually "No color". Will make that more apparent.
