### ISSUE TITLE
beforeEventEdit event should handle async handlers

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7085]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=25448&p=126686#p126686)

"Hi,

i use the [Scheduler.feature.EventEdit#event-beforeEventSave](https://www.bryntum.com/products/calendar/docs/api/Scheduler/feature/EventEdit#event-beforeEventSave) listener to do some validation. On events without recurrence, it works fine. But when i do the validation in a recurring event, the [Scheduler.view.recurrence.RecurrenceConfirmationPopup](https://www.bryntum.com/products/calendar/docs/api/Scheduler/view/recurrence/RecurrenceConfirmationPopup) does not use the result from the listener.

To reproduce the issue go to: https://bryntum.com/products/calendar/examples/recurrence/ and set this additional config:

```
                listeners: {
                    beforeEventSave: async () => {
                        return false;
                    },
                }

```

As far as my understanding goes, one shouldn't be able to change any event after you interacted with the confirmation dialog."

**Comment by ExtAnimal** [comment]
It's nothing to do with recurring events. The handler is async, so the feature will have to be updated to handle the event trigger returning a Promise.

**Comment by ExtAnimal** [comment]
Upon deeper investigation, it does affect recurring events specifically. But *also* async handlers affect it. It's a two level issue. We will fix both levels.
