### ISSUE TITLE
Missing type of `null` in `ColumnConfig.editor`

### ISSUE THREAD

**Issue by LouwQ** [bryntum/support#7090]
According to the docs on this page: https://bryntum.com/products/schedulerpro/docs/api/Grid/column/Column#config-editor

It should be possible to configure `GridColumnConfig.editor` as `null` to prevent it from being edited, however the type doesn't actually say this is possible 

![image](https://github.com/bryntum/support/assets/23165877/364e4acc-db18-4adb-8b4f-dad6b7dd3a5d)

**Comment by matsbryntse** [comment]
Thanks for reporting, fixed!
