### ISSUE TITLE
Feature mixin `on-owner` events are not exposed on class

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7092]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25474&p=126776#p126776)

"Hi,
I'm using Bryntum Gantt and I would like to use event which will be trigger on adding dependencies between two elements in the Gantt (like in the screenshot below).
![2023-06-29_13h17_43.png](https://forum.bryntum.com/download/file.php?id=23097)
I tried to use onBeforeDependencyAdd which I found in the code but it was not working.
![2023-06-29_13h14_54.png](https://forum.bryntum.com/download/file.php?id=23098)
Do you have idea what kind of trigger can I use ?"

Checking this issue, I noticed that some of the events available here [https://bryntum.com/products/gantt/docs/api/Scheduler/feature/Dependencies#events](https://bryntum.com/products/gantt/docs/api/Scheduler/feature/Dependencies#events) are not available on the React way (using onEventName), so we need to add that.

**Comment by marciogurka** [comment]
The following listeners are missing on the React Wrapper

```
afterDependencyCreateDrop,
beforeDependencyCreateDrag,
beforeDependencyCreateFinalize,
beforeShowTerminals,
dependencyCreateDragStart,
dependencyCreateDrop,
dependencyValidationComplete,
dependencyValidationStart
```
So the following configuration works
```
const listeners = {
  afterDependencyCreateDrop: (eventData) => {},
  beforeDependencyCreateDrag: (eventData) => {},
  beforeDependencyCreateFinalize: (eventData) => {},
  beforeShowTerminals: (eventData) => {},
  dependencyCreateDragStart: (eventData) => {},
  dependencyCreateDrop: (eventData) => {},
  dependencyValidationComplete: (eventData) => {},
  dependencyValidationStart: (eventData) => {},
}
```
but this one doesn't:
```
<BryntumGantt
  onAfterDependencyCreateDrop={handleEvent}
  ...
/>
```

**Comment by jsakalos** [comment]
Confirmed. The events should be in the wrapper.

**Comment by Jmurawsk** [comment]
@marciogurka any update here ? I also found listener which can be added to React Wrapper - dependencyContextMenu

**Comment by jsakalos** [comment]
As investigated by @ghulamghousdev these events are really not present in the wrapper. @SergeyMaltsev to check/fix as this seems to be the wrapper generator bug.
