### ISSUE TITLE
Copy & Paste of tasks looses color thus leaves unreadable task text

### ISSUE THREAD

**Issue by lubber-de** [bryntum/support#7097]
## Description
https://bryntum.com/products/schedulerpro/examples/weekends/

- Select a Task
- Press CTRL+C
- Press CTRL+V
Task is copied as expected but misses background color, so the white text is not readable anymore on white background ;)

## Screenshot
![copypastemissingcolor](https://github.com/bryntum/support/assets/18379884/3b21ed36-b9bb-405f-aeb8-0a50e46a6bda)

**Comment by matsbryntse** [comment]
Just a demo code issue, have a look at the eventRenderer and you'll see the cause. Demo updated for next patch.
