### ISSUE TITLE
Extra horizontal scrollbars shown in resourceview in narrow window

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#7107]
https://bryntum.com/products/calendar/examples/resourceview/

+ look at video for drag drop proxy misplacement

<img width="1119" alt="Screenshot 2023-07-03 at 10 47 37" src="https://github.com/bryntum/support/assets/218570/76112f02-1c02-47b4-b2d8-122de0df9d6d">

https://github.com/bryntum/support/assets/218570/5dc2245f-a188-438b-9185-7babd63d8d23

**Comment by dongryphon** [comment]
Not able to reproduce the extra scrollbars. Maybe this is Mac only?

**Comment by dongryphon** [comment]
The issue is reproducible if you drop an event into all day, then drag it out.
