### ISSUE TITLE
The dependency line not render correctly after scroll out

### ISSUE THREAD

**Issue by benjaminliugang** [bryntum/support#7125]
Hi Bryntum Team,

Sometimes the dependency line does not render correctly if scroll out of the event block with the dependency line in view. More details please check the forum post: https://forum.bryntum.com/viewtopic.php?t=25517&sid=3bcc36a88d1edc7944aed2a67612829a

**Comment by matsbryntse** [comment]
Let's continue discussion in forum and we'll promote to Issue here if confirmed as a bug.

**Comment by vincentcn** [comment]
Hi @matsbryntse 
Any updates/ETA on this? @benjaminliugang has shared the reproduction steps in https://forum.bryntum.com/viewtopic.php?t=25517&sid=3bcc36a88d1edc7944aed2a67612829a.
