### ISSUE TITLE
Group icon not showing when sorting is disabled

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#7128]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=25542&p=127083#p127083)

I have a table which has sorting disabled but you can still group (even though the rows get sorted) and it worked fine until one of the recen upgrades. Now the group icon does not show.

**Comment by taauntik** [comment]
It work if the grid is grouped on initial load but even then the indicator only shows on that column and not on the others.

To test:
```
features : {
    sort  : false,
    group : 'food'
}
```

You can reproduce it here https://bryntum.com/products/grid/examples/grouping/

https://github.com/bryntum/support/assets/75997756/430ddcb7-2e07-4f60-9586-09b3c9506444

**Comment by Chochek** [comment]
Any updates on this?

**Comment by matsbryntse** [comment]
Sorry for the delay, should be fixed now - coming in next release
