### ISSUE TITLE
Add collapse/expand events for columns & swimlanes

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#7136]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=56&t=25551&p=127137#p127137)

Hi bryntum team
 I am using bryntum Taskboard .In my project , task board has a lot of data ，So there may be some lag on the page. I want to display a portion of the taskboard data by expand or collapse the swimlane. When a certain swimlane is expanded, the data of that swimlane will be displayed, other swimlanes will be collapsed, and the data of other swimlanes will also be remove from the projectModel. That is my idea.
But I encountered some problems. First, my data was requested from the back-end. Can I bind a click event on a swimlane? When  user clicks on a swimlane, I can obtain information about that swimlane and then request corresponding data from the back-end based on that swimlane。

**Comment by thewebartisan7** [comment]
This feature request is good idea to handle big data. 
Also with a combination with virtualization or [infinitescroll](https://github.com/bryntum/support/issues/7300).
