### ISSUE TITLE
`change` event not fired on TaskStore after renaming segment

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#7137]
gantt.taskStore.on('change', console.log)

**Comment by canonic-epicure** [comment]
Probably already fixed in https://github.com/bryntum/support/issues/8079

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/02e3faa1-2a39-4135-85cb-f93b60783e7e

**Comment by canonic-epicure** [comment]
Confirmed.
