### ISSUE TITLE
Issue with drag-and-drop feature, multiday event and workingTime

### ISSUE THREAD

**Issue by kkokiev** [bryntum/support#714]
Hello. Working with your awesome Bryntum scheduler for some time.
I found a bug that I would like to report.
In my opinion, it will be easier to show this bug by example than to describe in words.
Steps to reproduce:

1. Go to demo page https://www.bryntum.com/examples/scheduler/vertical/ and open Code editor

2. In the scheduler config:
a. Change `startDate` to `new Date(2019, 0, 1, 0)`, `endDate` to `new Date (2019, 0, 2, 24)`
b. Add parameter 
```js
workingTime: {
  fromHour: 8,
  toHour: 18,
}
```
![demo-1](https://user-images.githubusercontent.com/13585148/81142811-42a2c600-8f79-11ea-8a85-561b99da3e35.png)

3. Edit some event dates, `start` to `Dec 31, 2018`, `end` to `Jan 03, 2019`

![demo-2](https://user-images.githubusercontent.com/13585148/81142851-5a7a4a00-8f79-11ea-81a5-8344e07e027b.png)

4. Drag and drop this event to another resource

**Expected behavior**: event will go to another resource with the current start and end dates.

**Current behavior**: event go to another resource but change `start to Dec 30, 2018 and end Jan 02, 2019`

![demo-3](https://user-images.githubusercontent.com/13585148/81142923-84337100-8f79-11ea-8faa-9aefacc78646.png)

**Comment by pmiklashevich** [comment]
Hello,

It's not reproducible with the latest sources. If you have an access to the customer zone, please download the latest nightly build and try how the demo works there. If you have a question or want to report a bug, please create a thread in one of our forums: https://www.bryntum.com/forum/
It's easier to communicate there. And this is the way to share our and our user's experience with others. We will create a ticket if we think the report is valid.

Cheers,
Pavel

**Comment by chuckn0rris** [comment]
Can be reproduced in nightly-release version `scheduler-2020-05-14-release`. Need to be checked again after next nightly release.

**Comment by matsbryntse** [comment]
Can't reproduce
