### ISSUE TITLE
Add preamble/postamble to calendar events

### ISSUE THREAD

**Issue by lx-0** [bryntum/support#7148]
It would be very nice to see the scheduler pro feature of travel time (preamble/postamble) in the calendar component as well.

**Comment by matsbryntse** [comment]
Nice idea!

**Comment by lx-0** [comment]
Is this feature planned in the near future? Would really love to see that in the Calendar.

**Comment by chegix** [comment]
Are there any news on this feature?

We really would like to implement it.

**Comment by matsbryntse** [comment]
Not yet, we'll discuss if we can accelerate the implementation

**Comment by chegix** [comment]
Thanks your the update, let us know if there any news.

**Comment by ghulamghousdev** [comment]
Another client requested for it here: https://forum.bryntum.com/viewtopic.php?p=149169#p149169

**Comment by ExtAnimal** [comment]
This will be easy. Just needs two new elements. 

```
.b-cal-preamble {
    position: absolute;
    bottom: 100%;
    width: 100%;
    background: var(--cal-preamble-background);
}

.b-cal-postamble {
    position: absolute;
    top: 100%;
    width: 100%;
    background: var(--cal-postamble-background);
}
```

And the height can be a %age, the proportion of the preamble/postamble time against the event's duration, so it will size itself using CSS.

<img width="1224" alt="Screenshot 2024-07-11 at 08 19 57" src="https://github.com/bryntum/support/assets/200516/f39c025c-9566-417a-8fb9-81a0ae88599f">

**Comment by ExtAnimal** [comment]
It needs this:

```
.b-dayview {
    // Create the "T" background images for the preamble and postamble elements
    --event-preamble-background: linear-gradient(90deg, transparent, transparent calc(50% - 0.5px), #ccc calc(50% + 1px), transparent calc(50% + 0.5px), transparent 100%), linear-gradient(180deg, #ccc 1px, transparent 1px);
    --event-postamble-background: linear-gradient(90deg, transparent, transparent calc(50% - 0.5px), #ccc calc(50% + 1px), transparent calc(50% + 0.5px), transparent 100%), linear-gradient(0deg, #ccc 1px, transparent 1px);
}

.b-cal-event-buffer {
    position: absolute;
    width: 100%;
    background-size: 0.5em 100%;
    background-repeat: no-repeat;
    background-position: 50% 0%;
}

.b-cal-preamble {
    bottom: 100%;
    background: var(--event-preamble-background);
}

.b-cal-postamble {
    top: 100%;
    background: var(--event-postamble-background);
}
```

And `.b-cal-event-wrap` should not be `overflow : hidden`.

The result is this:

<img width="405" alt="Screenshot 2024-07-11 at 10 19 56" src="https://github.com/bryntum/support/assets/200516/42c9961a-a16a-4c90-8784-ecf30cdbdc36">

**Comment by matsbryntse** [comment]
Try it out in the new `date-resource-non-consecutive-dates` demo
