### ISSUE TITLE
Allow HTML in column headers

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7160]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=56&t=25608&p=127395#p127395)

Hi, 

We are using a Bryntum Taskboard, and we would like to modify in some cases the headers of the columns with custom content.

I've been checking the docs and the examples, but did not find anything about that. 

What would be the easiest way of customizing the content of the headers? 

I send you attached a simple example of something similar we want to achieve. 

Thank you in advance.
Regards
![MicrosoftTeams-image (4).png](https://forum.bryntum.com/download/file.php?id=23278)

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?f=56&t=25887&p=128858#p128858)

**Comment by isglass** [comment]
There is a private `columnHeaderRenderer`, we could make it public
