### ISSUE TITLE
Task record is inserted into wrong position in the tree

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#7171]
Reported by client.

Steps to reproduce on advanced demo:
1. apply code snippet (below) to the app.js
2. add this config to project: ```transport : { sync : { url : 'sync' } }```
3. set project `autoSync` to true
4. open advanced demo
5. collapse root node
6. open context menu, pick 'add task below'. observe wbs is 2 and id is 2
7. open context menu on the same node again, pick 'add task below'

Task should be added in the middle with wbs 2 and id 3. Task wbs and id are correct, but task is added to the end of the view. As if view was sorted by id.

Should be:
![image](https://github.com/bryntum/support/assets/45400762/5cd0277a-c064-4d2c-a357-d38fca68285c)

Got:
![image](https://github.com/bryntum/support/assets/45400762/8ae0dba4-d0c3-4a7c-8bf5-ce1816de7109)

```
import AjaxHelper from '../../lib/Core/helper/AjaxHelper.js';

let counter = 100;
AjaxHelper.mockUrl('sync', (url, params, options) => {
    const request = JSON.parse(options.body);
    const idMap = {};
    console.log(request);
    const rows = request?.tasks?.added?.map(r => {
        const id = ++counter;

        idMap[r.$PhantomId] = id;

        return {
            id,
            $PhantomId       : r.$PhantomId,
            $PhantomParentId : r.$PhantomParentId,
            parentId         : idMap[r.$PhantomParentId] || null
        };
    });

    console.log({
        success   : true,
        requestId : request.requestId
    });
    if (request?.tasks?.added?.length) {
        return {
            responseText : JSON.stringify({
                success : true,
                tasks   : {
                    rows
                }
            })
        };
    }
    else {
        return {
            responseText : JSON.stringify({
                success   : true,
                requestId : request.requestId
            })
        };
    }
});
```

**Comment by canonic-epicure** [comment]
Reproduced, need to change the project config to:
```
    project : {
        // Let the Project know we want to use our own Task model with custom fields / methods
        taskModelClass : Task,
        transport      : {
            load : {
                url : '../_datasets/launch-saas.json'
            },
            sync : {
                url : 'sync'
            }

        },
        autoLoad  : true,
        autoSync  : true,
        taskStore : {
            wbsMode : 'auto',
            forceWbsOrderForChanges : false
        },
        // The State TrackingManager which the UndoRedo widget in the toolbar uses
        stm : {
            autoRecord : true
        },
        // Reset Undo / Redo after each load
        resetUndoRedoQueuesAfterLoad : true
    },
```

**Comment by canonic-epicure** [comment]
The issue is caused by this line in the response data:
```
parentId         : idMap[r.$PhantomParentId] || null
```
So the example applied the new `parentId` (`null`) instead of the previous `parentId` (something like `_generatedProjectModel_8baa838f-f092-4271-9350-aa260ac3b42d`). In the same time `parentIndex` is not provided. This effectively moves the task to the end of the root node's children.

Interesting that changing that line to 
```
parentId         : idMap[r.$PhantomParentId] || undefined
```
fixes the problem.

Looking further
