### ISSUE TITLE
Non working intervals hidden for manuallyScheduled tasks when skip non working time in duration disabled 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7176]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25625&p=127549#p127549)

Open https://bryntum.com/products/gantt/examples/calendars/
In console 
```
g = gantt
g.project.skipNonWorkingTimeInDurationWhenSchedulingManually = false
g.taskStore.getAt(3).manuallyScheduled = true
```

See non working periods are not visible anymore for task "Configure firewall" (which is with index 3).

**Comment by PWbio** [comment]
For react version 5.6.4, `skipNonWorkingTimeInDurationWhenSchedulingManually` is missing in type file.

**Comment by chuckn0rris** [comment]
Thanks! Will be fixed here https://github.com/bryntum/support/issues/8126
