### ISSUE TITLE
dragMoveEnd listener in DayResourceView not having updated data

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7178]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25647&p=127589#p127589)

"Hello Bryntum Team,

we are using Bryntum Calendar (5.4.1) with the new DayResourceView.

I discovered a Bug when i move an Event from one Resource to another Resource.
The Error can be reproduced in your Online Example:

https://bryntum.com/products/calendar/examples/date-resource/

When you add the marked Code and move for Example an Event like shown in my Example
Pictures the resourceId is not correct. It is still the old resourceId and not the Updated one.

![bug_bryntum_1.png](https://forum.bryntum.com/download/file.php?id=23329)

![bug_bryntum_2.png](https://forum.bryntum.com/download/file.php?id=23330)"

Code added for testing

```
listeners: {
  dragMoveEnd: function(event){
    console.log('startDate:' + event.eventRecord.startDate);
    console.log('endDate:' + event.eventRecord.endDate);
    console.log('resourceId:' + event.eventRecord. resourceId);
  }
},
```

**Comment by ExtAnimal** [comment]
<img width="1078" alt="Screenshot 2023-07-31 at 09 07 52" src="https://github.com/bryntum/support/assets/200516/97f173fc-bd20-48b7-adc9-1bb94e1312ad">
