### ISSUE TITLE
Null element on time localization WWp format

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7190]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25677&p=127705#p127705)

"I'm trying to show "week (week number)" in italian but instead of settimana or sett. i obtain null. I'm using a localization and a presetmanager. Maybe i'm missing something on the LocaleManager part?
![Screenshot 2023-07-20 170844.png](https://forum.bryntum.com/download/file.php?id=23375)"

[angular (2).zip](https://github.com/bryntum/support/files/12112678/angular.2.zip)

**Comment by mazzafabio** [comment]
After I dived into it for a while, it turned out that translation for italian language is correct.
There is an incorrect implementation by our client.
Following code could be solve his issue:

```
import it from '../../lib/SchedulerPro/localization/It.js';

new SchedulerPro({
    .....
});

const updatedLocale = LocaleHelper.mergeLocales(it, {
    localeCode: "it",
    localeDesc: "italian",
    localeName: "It",
    DateHelper: {
        locale: "it",

        parsers: {
            L: "DD MM YYYY",
            LT: "HH:mm",
            LTS: "HH:mm:ss"
        },

        weekStartDay: 1
    },
    PresetManager: {
        weekAndDay: {
            topDateFormat: 'DD MMMM YYYY WWp',
        },
        weekAndDayLetter: {
            topDateFormat: 'DD MMMM YYYY WWp',
        }
      }
});
LocaleHelper.publishLocale(updatedLocale);
LocaleManager.applyLocale('it', updatedLocale);
```

**Comment by marciogurka** [comment]
Here is an updated version with the code that @mazzafabio shared it here and it's working as expected

[angular.zip](https://github.com/bryntum/support/files/12134064/angular.zip)
