### ISSUE TITLE
Vertical Scroll for Notes column Missing

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7191]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25678&p=127708#p127708)

"Hello,

For the standard notes field, when a user inputs text greater than the size of the expanded box, there is no scroll option for the user.

![Note as no scroll.png](https://forum.bryntum.com/download/file.php?id=23381)

Any advice?"

**Comment by matsbryntse** [comment]
Solution posted here:

https://forum.bryntum.com/viewtopic.php?f=52&t=25678&p=127708#p127708
