### ISSUE TITLE
Drag and drop task cards sometimes works incorrect on iPad

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7195]
Verified on BrowserStack

[Forum post](https://forum.bryntum.com/viewtopic.php?f=56&t=25604&p=127554#p127554)

Hi,

We have an issue that also appears in the examples on your homepage (where you can add columns).

When there are more columns that can fit to the display size, you can scroll horizontally to show columns that are on the left/right side respectively.

However, if you try to drag and drop cards, it sometimes happens that while dragging the taksboard below scrolls horizontally, which makes dropping very difficult. It's not always, but often the case. As I said, you can reproduce that with the examples.

Thanks

Video:
https://nx37697.your-storageshare.de/s/yb4ZgaMFNnoxyBB

Demo: https://bryntum.com/products/taskboard/examples/columns/

**Comment by morphace** [comment]
Any update on that?

**Comment by matsbryntse** [comment]
Not yet but we should get to it soon!
