### ISSUE TITLE
`timeFormat` localization is ignored

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7199]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=25330&p=127672#p127672)

We have demos with localized timeFormat property in calendar views, as this DayView for De locale
```
    DayView : {
        Day               : 'Tag',
        collapseAllDayRow : 'Ganztägigen abschnitt reduzieren',
        dayUnit           : 'tag',
        daysUnit          : 'tage',
        expandAllDayRow   : 'Erweitern sie den ganztägigen bereich',
        timeFormat        : 'LT'
    },
```

But timeFormat is ignored by the view. To repro change it and see events are still have default time format from the current locale.
```
timeFormat : 'H:mm A'
```
<img width="541" alt="Screenshot 2023-07-21 at 14 23 46" src="https://github.com/bryntum/support/assets/7203098/b49c59f7-c1df-403b-b768-d3112feb2849">

**Comment by SO-Eng** [comment]
FYI, tooltips also affected. I guess the fix will then achieve same result all over the calendar.
I do timeFormat: .... also in tooltip now calling my workaround function.
