### ISSUE TITLE
Drop date is resolved based on cursor position instead of proxy element

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#72]
Drop date is resolved based on cursor position instead of proxy element
https://www.bryntum.com/forum/viewtopic.php?f=44&t=11733

When constrained to dates (vertically) the dragging is constrained but drop operation moves the event to the cursor position.

#issue 2: In non-continuous mode, cannot drag outside visible timeaxis
#issue 3: Missing else in resolveStartEndDates method, for the case where event starts before time axis and ends after

Docs: https://www.bryntum.com/docs/scheduler/#Scheduler/view/TimelineBase#config-getDateConstraints

http://lh/scheduler/examples/basic/
```

getDateConstraints(resourceRecord, eventRecord) {
    return eventRecord instanceof EventRecord ? {
        start : eventRecord.startDate,
        end   : eventRecord.endDate
    } : null;
},

```
![image](https://user-images.githubusercontent.com/218570/70438954-40524380-1a8f-11ea-9742-8474f523d6c7.png)

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/243
