### ISSUE TITLE
`onVisibleDateRangeChange` is not subscriber on `visibleDateRangeChange` event but separated method

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7203]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25687&p=127748#p127748)

Try to subscribe on `visibleDateRangeChange` event with 'on' notation

```
        onVisibleDateRangeChange(event) {
            debugger
        },
```

See that params list contains only `range` and nothing else. Sometimes that range has incorrect dates. In the code it's clear that there is a `onVisibleDateRangeChange` method exists that is not a listener.

**Comment by isglass** [comment]
Should probably rename the internal fn to `internalOnVisibleDateRangeChange`
