### ISSUE TITLE
Events not displaying with eventStore.applyChangeset

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7205]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25697&p=127825#p127825)

I can reproduce on live [basic test](https://bryntum.com/products/scheduler/examples/basic/).

Can u copy that in code parts : 

```javascript
import { Scheduler, ResourceModel, EventModel, ResourceStore, EventStore } from '../../build/scheduler.module.js?469229';
import shared from '../_shared/shared.module.js?469229';

//region Data

class RoadResourceModel extends ResourceModel {

    // Fields used by bryntum component
    static get fields() {
        return [
            { name: 'isForeman', type: 'boolean', defaultValue: false },
            { name: 'alias' },
            { name: 'entityIdentifier' }
        ];
    }

}

class RoadEventModel extends EventModel {

    static get fields() {
        return [
            //{ name: 'name', dataSource: 'businessData.label', alwaysWrite: true },
            //{ name: 'foreman', type: 'object' },
            { name: 'resourceIds', persist: true },
            { name: 'businessData', type: 'object' },
            { name: 'rowVersion' },
            { name: 'hasBeenCommited', type: 'boolean', defaultValue : true }
        ];
    }

}

const resourceStore = new ResourceStore({
            modelClass: RoadResourceModel,
            useRawData: false,
            autoCommit: false
        });


const eventStore = new EventStore({
            modelClass: RoadEventModel,
            useRawData: false,
            autoCommit: false,
        });


const scheduler = new Scheduler({
    appendTo         : 'container',
    resourceStore: resourceStore,
eventStore: eventStore,
    startDate        : new Date(2023, 7, 1),
    endDate          : new Date(2023, 7, 30),
    viewPreset       : 'hourAndDay',
    rowHeight        : 50,
    barMargin        : 5,
    multiEventSelect : true,
    columns          : [
        { text : 'Name', field : 'name', width : 130 }
    ]
});



        // Loading resources
fetch('https://bryntum.com/products/scheduler/examples/dragfromgrid/data/data.json').then(async (value) => {
            let json = await value.json();
console.log(json);
            if (json.resources && json.resources.rows) {
                await resourceStore.loadDataAsync(json.resources.rows)
            }

        }).catch((error) => { console.log(error); })
```

And apply this in the console

```javascript
window.scheduler.project.eventStore.applyChangeset({
            added: [{
                id: 4,
                name: "Addedd test ",
                eventColor: "#00FFF0",
                comment: "",
                iconCls: "",
                businessData: {
                    jobIdentifier: "JOB-0003",
                    isLorie: true,
                    isLorieSync: true
                },
                rowVersion: "123456789",
                startDate: "2023-07-08T00:00:00",
                endDate: "2023-07-09T00:00:00",
                draggable: false,
                resizable: true,
                resourceIds: [1, 2]
            }], updated: [], removed: []
        })
```
And you won't see any event added in UI

**Comment by Sisco21** [comment]
Just to complete. This happen too when i send data to server and want to update values back.
Indeed, data are not updated, event when i look in toJSON from eventStore, data had not been updated.
 
The code

`  this.eventStore = new EventStore({
            modelClass: RoadEventModel,
            useRawData: false,
            autoCommit: false,

            onChange: ({ action, records }: any) => {

                this.onChange();

                if (action === 'update' || action === 'add' || action === 'remove') {
                    records.forEach((value: Model) => {
                        value.set('needToBeSaved', true);
                        //EdIdb.getInstance().add(value.toJSON(), EntityType.ganttPlannerEvent);
                    });
                }
                //this.eventStore.revertChanges();
                //change.modified.forEach((value: Model) => {

                //     value.set('hasBeenCommited', false);

                // });

                // change.added.forEach((value: Model) => {

                //     value.set('hasBeenCommited', false);
                //     EdIdb.getInstance().add(value.toJSON(), EntityType.ganttPlannerEvent);


                // });
            },
            onCommit: async ({ changes, source, action }: any) => {
                
                console.log("Save");

                this.eventStore.suspendEvents(true);

                //this.scheduler.suspendRefresh();

                //this.scheduler.suspendEvents(false);

                this.scheduler.maskBody('<div style="text-align: center">Saving</div>');

                let events = [];

                //       this.eventStore.beginBatch();

                let createdEvents = [];
                let updatedEvents = [];
                let removedEvents = [];


                for (let model of changes.added) {
                    createdEvents.push(model.toRoadPlannerEvent());
                }

                for (let model of changes.modified) {
                    updatedEvents.push(model.toRoadPlannerEvent());
                }

                for (let model of changes.removed) {
                    removedEvents.push(model);
                }

                try {
                    let data = await GanttPlannerSchedulerApi.save({ added: createdEvents, updated: updatedEvents, removed: removedEvents });

                    if (data) {
                        for (let e of (<any>data).added) {
                            e.needToBeSaved = false;
                            console.info(e);
                        }
                        for (let e of (<any>data).updated) {
                            e.needToBeSaved = false;
                            console.info(e);
                        }
                    }
                    console.info(data);
                    this.eventStore.applyChangeset(data, undefined, 'phantomId');
                }
                catch (err) {

                }
                finally {

                    this.eventStore.resumeEvents();

                    //this.scheduler.resumeEvents();

                    //this.scheduler.resumeRefresh(true);

                    this.scheduler.unmaskBody();
                }

            }
        });`

**Comment by Sisco21** [comment]
There is a workaround to show data on Gantt. Indeed i'm blocked. I'm doing this : 

`
                this.eventStore.beginBatch();

                this.scheduler.suspendRefresh

                let result = await GanttPlannerSchedulerApi.save(data);

                this.eventStore.applyChangeset(result, undefined, 'phantomId');

                this.eventStore.endBatch();
`

And after doing 'window.scheduler.eventStore.toJSON()' i see my new created task but not displayed.
