### ISSUE TITLE
`getDateFromPosition` sometimes returns incorrect date

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7214]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25622&p=127805#p127805)

Add tooltip for timeAxis header cells
```
new Tooltip({
    forSelector: '.b-sch-header-timeaxis-cell',
    listeners: {
        beforeShow: (props) => {
            const { source: tip } = props;

            const date = schedulerPro.getDateFromDomEvent(tip.triggeredByEvent);
            tip.html = `<div>${date}<div/>`
        }
    }
});
```

Select viewPreset with days cells. Hover cursor over cells, see that sometimes it shows same day for 2 different cells

https://github.com/bryntum/support/assets/7203098/de4156b9-adbd-4a10-bafd-89e96dcec5e4

**Comment by matsbryntse** [comment]
Use 
`
            const date = scheduler.timeAxis.getDateFromTick(tip.activeTarget.dataset.tickIndex);
`
