### ISSUE TITLE
Add support for recurring timeranges

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7217]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=25713&p=127922#p127922)

We need the ability to block out time across days like for lunch or other un-schedulable time.  Are we able to do that with Calendar? If so, what does that object look like?  Thanks.

**Comment by ExtAnimal** [comment]
There is no `TimeRangeStore` class defined in the `Scheduler/data` package. There should be, and it should mixin `RecurringTimeSpansMixin`

Then `Scheduler/model/mixin/ProjectModelMixin` has to include a definition for `timeRangeStore`

Then recurring time ranges would be supported natively on all platforms, and the `Scheduler/examples/recurringtimeranges/` example would not need any custom code.
