### ISSUE TITLE
Searching html tag changes the value of searched cell

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7225]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25734&p=128011#p128011)

Hello,

We have discovered a XSS vulnerability in the grid search demo.

![Screenshot 2023-07-27 at 10.55.19.png](https://forum.bryntum.com/download/file.php?id=23460)

To replicate:

1. Open the search demo.
2. Alter one of the cells to include your favourite HTML tag. For example, `<s>Orange</s>`.
3. Search for `<s>`.
4. Press enter.
5. Observe a strikethrough in the "Orange" cell.

Could this be fixed ASAP please - it is a severe vulnerability in our software product!

**Comment by matsbryntse** [comment]
Issue fixed - for now please HTML encode the string you pass to the `search` method.

**Comment by ogardnerffdc** [comment]
Thanks!

When we HTML encode the string that we pass to the `search` method, the highlighting is removed. Will this be fixed as part of this issue?

**Comment by matsbryntse** [comment]
Once fix is out, you can remove your own encoding, and all will work ok.
