### ISSUE TITLE
Bug with event rendering when apply filter with `fixedRowHeight` enabled

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7228]
Apply this to https://bryntum.com/products/scheduler/examples/bigdataset/
```
fixedRowHeight: true, 
eventLayout: 'none',
preserveScrollOnDatasetChange: true,
// ...
features : {
    // ...
    filterBar: true
}
```

Follow steps on video:

https://github.com/bryntum/support/assets/7203098/db500ea6-b45a-4173-a001-067fbeca6a10

[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25723&p=128015#p128015)

Hi,

Using https://bryntum.com/products/scheduler/examples/bigdataset/ with the feature filterBar enabled and the settings fixedRowHeight  and preserveScrollOnDatasetChange  enabled i can generate an empty section in the scheduler if i use the filter after i scroll to the bottom of the scheduler.

I can workaround this by disabling the fixedRowHeight  setting.

**Comment by matsbryntse** [comment]
Cannot reproduce on latest
