### ISSUE TITLE
New event has red start/end labels

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#723]
https://www.bryntum.com/examples/scheduler-pro/pro-dependencies/

double click to create
open task editor

<img width="419" alt="Screenshot 2020-05-07 at 09 59 27" src="https://user-images.githubusercontent.com/218570/81269347-777e4e00-9049-11ea-8443-f34843e493dd.png">

**Comment by ExtAnimal** [comment]
This is just the new DateTime field marking itself invalid upon construction. Probably because it is `required`, but obviously begins empty. Seems it does not reevaluate its validity upon `set value`

The DateTime field is not a finished product.
