### ISSUE TITLE
BUG preset and infiniteScroll set to true

### ISSUE THREAD

**Issue by Sisco21** [bryntum/support#7231]
Hello,

When i'm using `infiniteScroll: true,` on the example [https://bryntum.com/products/scheduler/examples/dragfromgrid/](url). I have got the error bellow when changing preset. 

> scheduler.module.js?469544:63 Uncaught TypeError: Cannot read properties of undefined (reading 'getTime')

https://forum.bryntum.com/viewtopic.php?p=127531#p127531

**Comment by matsbryntse** [comment]
Please continue discussion in the forums and provide us a test case so we can reproduce. If we find it's a bug, we'll open a GitHub ticket
