### ISSUE TITLE
non-working-time doesn't get rendered properly after 6+ years long timespan

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7234]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25747&p=128089#p128089)

Hi,

Currently if the timespan is increased greater than 5 years, it renders the non-working time for the first 5 years and then does not render.

Can be reproduced in the advanced gantt example:
Open the advanced example: https://bryntum.com/products/gantt/examples/advanced/

Paste the below code to the console

```
gantt.setTimeSpan(new Date(2021, 6, 28), new Date(2027, 6, 28))
```

Scroll to 19 Jul 2026 and non-working-time weekends does not render after that
![non_working_time_stops_rendering.png](https://forum.bryntum.com/download/file.php?id=23477)

Is there a config to allow the render to the complete timespan?

Thanks,
Rayudu

**Comment by canonic-epicure** [comment]
Need to increase the [maxCalendarRange](https://bryntum.com/products/gantt/docs/api/Gantt/model/ProjectModel#config-maxCalendarRange) config to fix this.

**Comment by canonic-epicure** [comment]
Actually `setTimeSpan()` can automatically increase the `maxCalendarRange` per call, as suggested by Mats.
