### ISSUE TITLE
Splitting (event segment) doesn't work for parent tasks

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7239]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25753&p=128118#p128118)

"Hello Bryntum Team,

We are having issues splitting a parent task and are only able to split the child task. If you delete all the child tasks, you can split the parent task however, once you add a child task that split goes away. Is there a way to split the parent task?

For example, here We would like the ability to split that blue bar, but there is no an option for that
![image (8).png](https://forum.bryntum.com/download/file.php?id=23486)

However, in the green one you can do it, it seems to be related to the fact that it doesn't have a child task, in this one you have the option
![image (9).png](https://forum.bryntum.com/download/file.php?id=23485)

We also notice if a sub-task becomes a parent, you can't split it anymore, we believe that could be a potential bug.
![image (10).png](https://forum.bryntum.com/download/file.php?id=23487)"

**Comment by arcady-zherdev** [comment]
You cannot split a summary task. That's by design. A task should reset its segments as soon as it becomes a parent. I've made a ticket for that bug here: https://github.com/bryntum/support/issues/7273
