### ISSUE TITLE
Add support for resizing task from left side

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7251]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25764&p=128182#p128182)

Hi Team,
 

I was trying to resize the task from the left side but the current behavior of Gantt is that it supports Gantt resizing only from the right side.

Is there a way we can implement task resizing from the left side as well?

**Comment by matsbryntse** [comment]
Dupe: https://github.com/bryntum/support/issues/6814
