### ISSUE TITLE
Missing typings in ResourceUtilizationFeaturesConfigType after upgrading to version 5.4.0

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7259]
Need to check the list of available features in ResourceHistogram widget and fix typings accordingly. 
Before 5.4 all features from Scheduler was available, but is that correct?

[gantt-resource-utilization (2).zip](https://github.com/bryntum/support/files/12239103/gantt-resource-utilization.2.zip)

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25585&p=128369#p128369)

Hi,

After upgrading to version 5.4.0 of your Bryntum Gantt, we have noticed that certain settings are missing in the ResourceUtilizationFeaturesConfigType. Specifically, the following settings are not present:

 
```
features: {
            scheduleTooltip: false,
            eventTooltip: false, //missing
            pan: true, //missing
            search: true,
            nonWorkingTime: false, //missing
            resourceNonWorkingTime: {
                maxTimeAxisUnit: 'week',
            }//missing,
            dependencies: false,//missing
            timeRanges: {
                showCurrentTimeLine: {
                    name: this.translationService.getTranslation('TODAY')
                }
            },
...
```

These settings are not listed in the API upgrade guide. Could you please provide some guidance on where we can find these missing settings or if there are any alternative configurations available?

Best regards

**Comment by SergeyMaltsev** [comment]
Missing dependencies have been added.
