### ISSUE TITLE
Bug when using split and panel

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7263]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25804&p=128394#p128394)

"Hello,

I want to use Splitter and Panel from Core.widget.Splitter. But when i try to split, i have an issue like in the video.

There is an incompatibility? I have attached the js file to use with the example https://bryntum.com/products/scheduler/examples/split/. in the DOM i have only remove your header.

and when i split the panel come to the right."

You need to add ` flex-direction: row;` to the `.container` to see as the video.

https://github.com/bryntum/support/assets/16693227/8810dc14-971f-425b-95be-2339aeee1185

[Bug_Split_And_Panel_app.module.js_469663.zip](https://github.com/bryntum/support/files/12242244/Bug_Split_And_Panel_app.module.js_469663.zip)

**Comment by Sisco21** [comment]
Marcio do you have news?

**Comment by matsbryntse** [comment]
This has now been fixed for next patch!
