### ISSUE TITLE
Utilize recurring time spans feature in ES5

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7266]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25742&p=128484#p128484)

Checking the post, the user wants a way to use the Recurring time spans features in the ES5 way if possible.

**Comment by jeffallen6767** [comment]
specific use case: color/shade the background of every other day ( any workaround that could accomplish this would be a plus ! thanks )

**Comment by marciogurka** [comment]
In the next minor (mostly likely 5.6), it'll be always part of TimeRangeStore, so please try with a nightly `-next` build

**Comment by jeffallen6767** [comment]
Thanks! This is working in 5.6.0-alpha-1

`
project = new bryntum.scheduler.ProjectModel({
  useRawData: true,
  resourceStore: {
    id: 'aircraftStore',
    idField: ID_KEY,
    reapplySortersOnAdd: true,
    reapplyFilterOnAdd: true,
    reapplyFilterOnUpdate: true,
    applyChangesetFilterSortTarget: 'changes'
  },
  eventStore: {
    id: 'flightsStore',
    idField: ID_KEY
  },
  assignmentStore: {
    id: 'assignmentStore',
    idField: ID_KEY
  },
  // store for "timeRanges" feature:
  timeRangeStore: {
    id: 'timeRangeStore',
    idField: ID_KEY,
    // zs-2988 #4-Alternating grey & white background to differentiate the days
    data: [{
      id: 1,
      resourceId: 'daily-background-color-001',
      // start this range some day in the distant past:
      startDate: '2000-01-02T00:00',
      // make the range span the entire day:
      endDate: '2000-01-02T23:59',
      // this time range should repeat every other day
      recurrenceRule: 'FREQ=DAILY;INTERVAL=2',
      // we add the .background class (.b-timeaxissubgrid .background)
      cls: 'background'
    }]
  }
})
`

**Comment by jeffallen6767** [comment]
hey that works in 5.6.0-alpha-1

Should we wait for the minor release or is the alpha low enough risk for customers?
