### ISSUE TITLE
Bypassing recurrence popup about single or all recurring events

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7281]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=25813&p=128615#p128615)

We would like to bypass the question about editing single or all recurring events and just automatically save all events.  What is the best way to do that?

There are 2 buttons displayed in a dialog box "Save Only This Event" or "Save All Events", we want to disable the dialog box when saving a recurring event and assume they always want to "Save All Events". Not sure how to do that. Thanks.

**Comment by matsbryntse** [comment]
Dupe #7606
