### ISSUE TITLE
Not navigable to next month if selected date is next month

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7297]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25876&p=128776#p128776)

Hello Team,

In our application using bryntum Scheduler, it seems it's not possible to navigate to the next month, if selected date is outside of that month. The same issue exists in official Bryntum demo. Could you kindly assist?

Reproducible here https://bryntum.com/products/scheduler/examples/vertical/

![Not being able to select the next month.](https://forum.bryntum.com/download/file.php?id=23618)
![Selecting a day outside of the current month](https://forum.bryntum.com/download/file.php?id=23617)

**Comment by alekscislowski** [comment]
Hello @taauntik , do you have any update on this issue. 
This still appears in our application and on the Bryntum demo -  https://bryntum.com/products/scheduler/examples/infinite-scroll/
