### ISSUE TITLE
App stops working after Conflict Resolution dialog appeared

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7324]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=25928&p=129100#p129100)

When I tried to implement the conflict feature into my salesforce org I encountered this bug at first I thought It might be from my code, however, I went to the salesforce demo org which bryntum provides on the documentation and I was able to replicate this issue there as well

Please refer to the attached link for the recorded video.

https://www.awesomescreenshot.com/video/19978802?key=a1fabd14748571d3e3db60f5ab0e5f4a

**Comment by bmblb** [comment]
This turned out an app-level issue. Asked for more details

**Comment by bmblb** [comment]
No response from the user, demo code updated. Closing ticket.
