### ISSUE TITLE
Changing start date of manual task does not move successors

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#733]
https://www.bryntum.com/forum/viewtopic.php?f=52&t=13902&p=71844#p71844

http://lh/bryntum-suite/gantt/examples/advanced/
```
gantt.taskStore.removeAll()
gantt.taskStore.rootNode.appendChild([{
name : 'manual',
startDate : '2019-01-13',
duration : 1,
manuallyScheduled : true
}, {
name : 'auto',
startDate : '2019-01-13',
duration : 1
}])
gantt.dependencyStore.add({
fromTask : gantt.taskStore.rootNode.firstChild,
toTask : gantt.taskStore.rootNode.lastChild
})
gantt.project.propagate()
```
Change start date of manual task, move it, see auto task stays on its place.
Change duration, see auto task moves by the same value.

Auto task should be rescheduled according to its manually scheduled predecessor.

**Comment by isglass** [comment]
Better ask @arcady-zherdev or @SamuraiJack to be sure which behaviour is expected

**Comment by pmiklashevich** [comment]
> Better ask @arcady-zherdev or @SamuraiJack to be sure which behaviour is expected

I asked @SamuraiJack and he confirmed it's a bug and auto task should be rescheduled
