### ISSUE TITLE
Crash when double clicking calendar icon in dual-dayview demo

### ISSUE THREAD

**Issue by isglass** [bryntum/support#7332]
![crash](https://github.com/bryntum/support/assets/5415653/dfc47276-ff14-4c5a-893c-a4979fddc6a5)

**Comment by isglass** [comment]
Same crash if double clicking empty space in the unscheduled calendar

**Comment by ExtAnimal** [comment]
The fix is just to disable auto create in that second view in `DualDayView.js`

<img width="620" alt="Screenshot 2023-08-18 at 11 08 31" src="https://github.com/bryntum/support/assets/200516/f8783ca0-ecf8-4686-b4f0-91f1b06ce8d6">
