### ISSUE TITLE
Drag/Dropping multiple events doesn't show all event's start date in beforeEventDropFinalize

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7367]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=26017&p=129639#p129639)

+ https://forum.bryntum.com/viewtopic.php?f=44&t=26152&p=130330#p130330
https://forum.bryntum.com/viewtopic.php?p=133456#p133456

Hi,

how can I get the new date of multiple events before EventDrop is completed?
If I move only one event, there is no problem, I can get startDate of the context.
But if I move multiple events, I can get only one startDate from the context.
But I need all new start dates for all events.

Any idea?

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=130332#p130332) for this

**Comment by mazzafabio** [comment]
A solution could be that, for multiple drop events, we could map each moved event to its new startDate in place of current startdate field, passed in the context, like:
```
{
    'ev1' : 01/01/2023,
    'ev2' : 02/01/2023 ...
}
```

**Comment by abrenner94** [comment]
For clarification: not only the `startDate` is relevant, but also the new `endDate`

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=130941#p130941) for this

**Comment by abrenner94** [comment]
Hi, any news regarding this request? @matsbryntse

**Comment by matsbryntse** [comment]
Not yet, no

**Comment by jimmycallin** [comment]
+1 from us!
