### ISSUE TITLE
Nested Events showing as duplicates outside parent event

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7375]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25983&p=129426#p129426)

"Hi There,

I am having some very strange UI bugs around rendering children events (nested events) in the scheduler. Sometimes (1/10 events) will be rendered with duplicate children events and one set of those children events outside the parent.

PureJS version, no React/Vue, etc. Looks great when only viewing parent events. The Scheduler shows many duplicate children events when they are unfiltered

What the problem looks like in Scheduler UI:  - link to screenshot https://ibb.co/8mTXHMN

A buggy fix I found, changing the name through task-editor and saving:  - link to screenshot https://ibb.co/8mTXHMN

I'm using Bryntum Gantt 5.5.0 and importing the SchedulerPro through the Gantt.module.js file. I tried importing through the Scheduler.module.js file but it caused issues with conflicting/duplicate imports of the Bryntum Grid.

```
const { SchedulerPro, WidgetHelper, StringHelper, Popup, Panel, Combo, TabPanel, DateHelper } = require('bryntum/gantt/gantt.module.js'); 
```

A few other things I've tried with no noticeable difference...
Refreshing scheduler.. 
```
scheduler.refreshRows();
    scheduler.restartInitialAnimation();
```
Changing the child/nested event name through code, then refreshing, then changing back... Trying to mimic the task-edit name change that sometimes works. Did not work. 
```
// Kinda stupid... maybe will fix...
// change name like with manual fix, refresh, then change back
                    
            scheduler.eventStore.forEach((event) => {
                if (event.id.toString().endsWith('S')) {
                    event.name = event.name + '[|__|]';
                }
            });
            
            triggerRefresh(scheduler);
            
            scheduler.eventStore.forEach((event) => {
                if (event.id.toString().endsWith('S')) {
                    event.name = event.name.replace('[|__|]', '');
                }
            });
            
            triggerRefresh(scheduler);
```
Tinkering around with my scheduler settings (in case it was a sizing/config issue). Made little visual tweaks but did not change the children event duplicates rendering outside parent events 
```
				 eventHeight: 40,
                                // Reserve more space above the nested events container
                                headerHeight: 30,
                                // Space between nested events
                                barMargin: 10,
                                // Space between nested events
                                eventMargin: 10,
                                // Space between nested
                                eventSpacing: 10,
                                // Space between nested events
                                eventSpacingMargin: 10,
```
"

It doesn't seem that it's duplicate, but the positioning of some events is not correctly aligned, then it gives the impression of duplication.

**Comment by marciogurka** [comment]
User added an example and a video

[bug_replication.zip](https://github.com/bryntum/support/files/12432374/bug_replication.zip)

https://github.com/bryntum/support/assets/16693227/e9724c41-8d57-4554-bf5b-836c26251d80

**Comment by marciogurka** [comment]
Also added a [comment](https://forum.bryntum.com/viewtopic.php?p=129706#p129706)

> I've gone through the nested child events that are not being rendered inside the parent, all of the children events with issues DO NOT have dependencies.
I'm not sure how that is impacting the scheduling/rendering engine, but all the problem events do not have dependencies before/after them.
All the good events (children rendering inside parents) DO have dependencies.

**Comment by mazzafabio** [comment]
Wrong library imported
