### ISSUE TITLE
ResourceUtilization should not expand a collapsed resource when assigning it

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7387]
Should not need to fully re-group tree data when a record is added/removed/updated from original store.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26050&p=129819#p129819)

[Forum post 2](https://forum.bryntum.com/viewtopic.php?p=131285#p131285)

[screen-capture.webm](https://github.com/bryntum/support/assets/75997756/72710617-3d20-403a-b66e-f729ad196ed6)

**Comment by chuckn0rris** [comment]
Another [request](https://forum.bryntum.com/viewtopic.php?p=131285#p131285)

**Comment by jonrs-prevas** [comment]
I just want to say that we are also waiting for this feature. It would be great with a milestone on this issue.

Thanx
Jon

**Comment by matsbryntse** [comment]
Test in `7387-resourceutilization`

**Comment by matsbryntse** [comment]
@jonrs-prevas Thanks for your feedback, we'll try to prioritize this!
