### ISSUE TITLE
Make possible to share Gantt's ProjectModel with Calendar

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7391]
Makes sure all calculations works as expected when moving tasks in Calendar. Make a demo.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=26075&p=129904#p129904)

I am trying to use same project for Gantt and Calendar components but it is not working.

Is it possible to do the same?

My requirement is I have a task list in which some tasks have dependancies to each other. I want to use same tasks list for both Calendar and Gantt components because I need to do same dates calculations for Gantt and Calendar as Calendar does not matter the dependancies but Gantt maintain dependancies and recalculate date accordingly as I moved one task it automatically moved its dependant tasks but Calendar does not.

Is it possible to get same calculations return by Bryntum engine from both the components?
and i the case, how we will get the updated tasks list while having dependencies.

**Comment by matsbryntse** [comment]
Some progress here https://github.com/bryntum/bryntum-suite/pull/6921

**Comment by recf25** [comment]
Hi @matsbryntse - do we have any updates on this?

**Comment by matsbryntse** [comment]
No, it'll need a bit of thinking about how this should look and work when you load a Gantt project into a Calendar. Should parent tasks render? Should milestones render, etc? Hopefully we can look at this sometime in Q4.

**Comment by recf25** [comment]
Hi Mats,

There should be no change in what is showing in calendar - no rendering of parent tasks.  We currently dont have milestones in place, so I dont think this would be a necessary requirement at this time.  

The goal is to allow a date change outside of Gantt view, and for those changes to be validated using the scheduling engine.

**Comment by matsbryntse** [comment]
Duplicated: https://github.com/bryntum/support/issues/1956
