### ISSUE TITLE
Zoom to span not show correct view span when RTL used

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7392]
Reproducible only in a wrapper. If you don't see the problem, try to play with browser window size. As example, if you opened a DevTools panel, screen might be too small to reproduce the problem. Try to minimize devtool width.

[Forum post](https://forum.bryntum.com/viewtopic.php?p=129913#p129913)

Hi I am working with scheduler 5.4.2v and angular 15.
I found that the combination of scheduler "rtl" and infinity scroll make zoom to span broken.
Implementation :

```
<bryntum-scheduler
    #scheduler
    [columns] = "schedulerConfig.columns"
    [events] = "schedulerConfig.events"
    [infiniteScroll]="true"
    [resources] = "schedulerConfig.resources"
    
   
(onPaint)="schedulerPaint($event)"
</bryntum-scheduler>
```

```
 // Init scheduler data when finish pain the scheduler.
    schedulerPaint(event: object) {

    // If it is first paint.
    if (event['firstPaint'] === true) {
        this.scheduler = event['source'];
        this.initComponentWithScheduler();
    }
}
initComponentWithScheduler() {
    // @ts-ignore
    this.scheduler.rtl = this.direction === 'rtl';
    console.log({ startDate:new Date('2021-01-01T12:00'), endDate:new Date('2021-01-03T12:00') });
    this.scheduler.zoomToSpan({ startDate:new Date('2021-01-01T12:00'), endDate:new Date('2021-01-03T12:00') });
}

```

Ass you can see I expected to see the dates that in the console but I See:
![1.png](https://forum.bryntum.com/download/file.php?id=23863)

I create some simple demo that show the problem.

Note:
I found that where you open the inspect influence on the view zoom result.
![1.png](https://forum.bryntum.com/download/file.php?id=23863)

[angular15-5.5-1.0.zip](https://github.com/bryntum/support/files/12463856/angular15-5.5-1.0.zip)

**Comment by yakeer** [comment]
Hey,
Any ETA for this bug?

**Comment by yakeer** [comment]
@matsbryntse, could you please advise when is it going to be solved?
That's an annoying bug since we use this method to restore viewport positions when refreshing the data.

**Comment by matsbryntse** [comment]
> @matsbryntse, could you please advise when is it going to be solved? That's an annoying bug since we use this method to restore viewport positions when refreshing the data.

Fix is ready, just waiting for review. Should be out in the 5.6.12 release due the next few days
