### ISSUE TITLE
Data on tooltip does not align with placement of task

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7395]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=26064)

"Hello,

We're experiencing a problem where the data displayed in the task tooltip is not accurately aligned with the task's actual position. In the attached video, you can see that when I drag the task to a new date, the date changes in the tooltip but the task does not change position. I have to move the mouse even further along the X-axis for the task to re-position. I've also experienced cases where the task gets dragged but the data in the tooltip does not change. 
It's worth noting that we've enabled fillTicks and snap features.
Link to demo: https://bryntum.com/products/gantt/examples/fill-ticks/
"

https://github.com/bryntum/support/assets/16693227/cbdc0854-c234-4c81-8ab6-5f7702cd6706

https://github.com/bryntum/support/assets/16693227/60eb76ac-6875-42e2-9efa-de960385f2c5

**Comment by ExtAnimal** [comment]
Surely this is expected with fillTicks and a short event?

The short event is being moved *inside* the tick. It's not moving to the next tick, it's still inside its original tick. But fillTicks is true, to its filling that tick.

**Comment by drolin-suffolk** [comment]
With both the fillTicks and snap features enabled, we'd expect the task to move in courser steps, for example at a zoom level that has ticks at the day level, we'd expect the task to move in one day increments.  Likewise, we'd expect the tooltip to match the same granularity and we'd also see one day increments.
