### ISSUE TITLE
List group should be toggleable

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7405]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=26072&p=130045#p130045)

Hi Team, 
Is it possible to have left sidebar resources as follows
![a9100430e7b4b66d99a010768cbbccb0.png](https://forum.bryntum.com/download/file.php?id=23875)
We would like to load different types of resources as grouped, Is it possible to provide a toggle to open up/ hide the resources as a group

**Comment by ExtAnimal** [comment]
Must be done in the 5.6.x branch, whatever that is.

`List.js` should get a `data-group="group-id"` property:

```
    itemWrapperTpl(record, i) {
        const
            {
                selected,
                getItemStyle
            }           = this,
            style       = getItemStyle ? `style="${this.callback(getItemStyle, this, [record])}"` : '',
            groupParent = record.groupParent?.get(this.store.id),
            group       = groupParent?.id || record.isGroupHeader && record.id;

            return TemplateHelper.tpl`<li ${style} ${group ? `data-group="${group}"` : ''} class="${this.getItemClasses(record, i)}" role="option" aria-selected="${selected.includes(record)}" data-index="${i}" data-id="${StringHelper.encodeHtml(record.id)}" ${this.itemsFocusable ? 'tabindex="-1"' : ''}>${this.itemContentTpl(record, i)}</li>`;
    }
```

To identify group members within the list. They can then be hidden or shown using a `[data-group=""]` selector.
