### ISSUE TITLE
Implement dragging multiple tasks at once

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#7408]
Multiple task selection is supported, but it is not possible to drag several tasks at once. It should work like in Scheduler.

Due to involved scheduling this feature is more complicated. Dragging a task sets SNE constraint by default, but when dragging multiple tasks we should try to avoid setting constraints on all of them.

Example:
```
tasksData : [
  { id : 1, duration : 1 },
  { id : 2, duration : 2 },
],
dependenciesData : [
  { fromTask : 1, toTask : 2 ]
```

If we drag task 1 back is time, task 2 will move as well because of the dependency. If we select both tasks and drag them back in time, we should avoid setting SNE constraint on the successor, because successor is already in the desired position.

To paraphrase, our goal is to move both tasks 1 day before. If we drag only predecessor, we achieve the goal with one explicit constraint. If we drag two tasks at once, behavior should remain the same

**Comment by chuckn0rris** [comment]
https://forum.bryntum.com/viewtopic.php?p=137824#p137824
