### ISSUE TITLE
Scheduler Pro demos do not work on iPad

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#741]
iPad 7gen
OS 13.3.1
Safari and Chrome

UMD works. No "nomodule" script tag added

https://bryntum.com/examples/scheduler-pro/
Loads preview, but live demo is missing on the left top corner, information icons are broken
Error in console:
https://bryntum.com/examples/scheduler-pro/
<img width="1001" alt="Снимок экрана 2020-05-08 в 13 13 49" src="https://user-images.githubusercontent.com/57486733/81396831-d2d63c00-912e-11ea-838c-7b2d22afafec.png">

All demos are broken, show blank page
Error in console:
<img width="999" alt="Снимок экрана 2020-05-08 в 13 22 14" src="https://user-images.githubusercontent.com/57486733/81396896-f305fb00-912e-11ea-8ac6-20c3cb5d9ee9.png">

**Comment by matsbryntse** [comment]
Only on older versions of Safarri
