### ISSUE TITLE
Filtering predecessors/successors not working proplery with filterbar

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7417]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=130103#p130103)

Reproducible in Gantt Advanced demo with filterBar feature enabled.
![Screenshot_48](https://github.com/bryntum/support/assets/75997756/5555e588-0145-4b94-b684-775ef268ea7a)

**Comment by matsbryntse** [comment]
There is no task with Task "1.1" as predecessor, we don't use partial matching.
