### ISSUE TITLE
Column re-order with local storage not working

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7444]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26150&p=130319#p130319)

This issue is also reproducible in your demo, here https://bryntum.com/products/gantt/examples/state/

Steps:

1) Order a column, example move "Duration" before or after a column. 
2) Reload page and then try again move some column.

You can then see that header of column doesn't move, just the content.

This works fine if there is not any localStorage data.

But if there is localStorage data already, then this error happen.

This worked fine before 5.4.1, and from 5.4.2 this error start happening.

https://github.com/bryntum/support/assets/75997756/14db8745-2766-4c46-b439-fd1e58ce9c49

**Comment by ghulamghousdev** [comment]
This issue is fixed by https://github.com/bryntum/support/issues/7689
