### ISSUE TITLE
Calendar column doesn't load data when setting project after gantt intialization

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7450]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=130370#p130370)

Reproducible in[ gantt advance demo](https://bryntum.com/products/gantt/examples/advanced/)

To reproduce it, you need to take the project config out of the gantt config and add it after the gantt initialization
```javascript
const project = new ProjectModel({
    // Let the Project know we want to use our own Task model with custom fields / methods
    taskModelClass : Task,
    transport      : {
        load : {
            url : '../_datasets/launch-saas.json'
        }
    },
    autoLoad  : true,
    taskStore : {
        wbsMode : 'auto'
    },
    // The State TrackingManager which the UndoRedo widget in the toolbar uses
    stm : {
        autoRecord : true
    },
    // Reset Undo / Redo after each load
    resetUndoRedoQueuesAfterLoad : true
});
const gantt = new Gantt({
    ...
});
gantt.project = project;
``` 

https://github.com/bryntum/support/assets/75997756/09f9f01d-62d6-48c6-b579-e8789a3cdc7f

**Comment by atremel** [comment]
Can you please update us on the bug's progress?

**Comment by matsbryntse** [comment]
Should be fixed now, coming in next patch.
