### ISSUE TITLE
`onChange` function becomes field in SchedulerPro ProjectModel

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#7457]
When we define `onChange` on `ProjectModel` like this:
```
    project : {
        autoLoad  : true,
        transport : {
            load : {
                url : 'data/data.json'
            }
        },
        onChange : () => {
            console.log('here we are');
        }
```

it will become a `DataField` on instantiation. That can cause the scheduler to crash such as here: https://github.com/bryntum/support/issues/7454

<img width="1292" alt="Screenshot 2023-09-07 at 14 39 53" src="https://github.com/bryntum/support/assets/204844/1afa507a-1941-46fc-aae1-b2fdab5f7661">

**Comment by isglass** [comment]
ProjectModel should probably not autoExpose fields
