### ISSUE TITLE
Current Timeline should get a unique css class to allow its customization 

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#7482]
We got a request from the client to customize current timeline appearance.

**Comment by ExtAnimal** [comment]
It already gets `b-sch-current-time`.

Of course it's only rendered if the current time is in the visible range:

![Screenshot 2023-09-14 at 11 21 19](https://github.com/bryntum/support/assets/200516/1f288f60-3f9f-4f36-a6d9-4cf1bbb60154)
