### ISSUE TITLE
RowExpander refreshOnRecordChange creates duplicate instances of widget

### ISSUE THREAD

**Issue by muhammad-faisal101** [bryntum/support#7515]
- When Enabling `refreshOnRecordChange` updating the Parent Record creates duplicate instances of widget
![image](https://github.com/bryntum/support/assets/109215133/47125a79-103d-4e8a-b27c-7286e924e117)

Loom: https://www.loom.com/share/950066bb02244540959108dd8252c386

**Comment by JockeLindberg** [comment]
Separated into two issues. The other one: #7546
