### ISSUE TITLE
Subsequent filter actions only consider initially filtered events

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7516]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=26288&p=131006#p131006)

"Hello,

I'm running into an issue when filtering an event store. When declaring initial filters on the event store, subsequent filter actions only seem to consider initially filtered events, even when replacing the filter entirely.

This is quite easily reproduceable on the [filter](https://bryntum.com/products/schedulerpro/examples-scheduler/filtering/) demo, by replacing crudManager with:

```
crudManager : {
	eventStore: {
		filters: event => event.name.includes('plan'),
	},
        autoLoad  : true,
        transport : {
            load : {
                url : 'data/data.json'
            }
        },
        // This config enables response validation and dumping of found errors to the browser console.
        // It's meant to be used as a development stage helper only so please set it to false for production systems.
        validateResponse : true
},
```"

In the demo, we have the filter
```
// Replace all previous filters and set a new filter
                scheduler.eventStore.filter({
                    filters : event => event.name.match(new RegExp(value, 'i')),
                    replace : true
                });
```

So it should be replaced, but it's not working as expected.

**Comment by isglass** [comment]
Issue is caused by assignments not being created for initially filtered out events
