### ISSUE TITLE
Memory leak on change tasks and revert changes

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7522]
Reproduced here https://bryntum.com/products/gantt/examples/resourcehistogram/

See video 

https://github.com/bryntum/support/assets/7203098/a1c805cd-dec1-47e8-a302-4d593bc373a0

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26163&p=131013#p131013)

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/aef2f23b-b79f-40a6-b0ac-b125181b6a78

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/09f71546-f41c-4b82-aaaf-f01052b371d7

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/eb9f1aec-8c26-4b64-9ade-63e33ba349c4

**Comment by canonic-epicure** [comment]
The fix was included in the 5.5.5 release (even though it seems the changelog entry is missing).
