### ISSUE TITLE
Removing partner does not break the timeAxis link

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#7542]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=131198#p131198)

A single `TimeAxis` is shared between partners. When partnership is broken, the party being removed should acquire a new `TimeAxis` configured the same as the existing `TimeAxis`

When a partnership is dyncamically created, the TimeAxis should be set into the scheduler being added.

**Comment by isglass** [comment]
Should also apply `infiniteScroll` setting to partner
