### ISSUE TITLE
Dutch Rollup translation

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#755]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=13941&p=71987#p71987)

Hi,

Just a suggestion for your Dutch translation file (if your Dutch translators agree). The word/term "Rollup" is now translated to "Samenvouwen". I think, a better translation in this context concerning parent and child tasks would be "Oprollen". That's in any way the word/term we use for it.

**Comment by matsbryntse** [comment]
Fixed
