### ISSUE TITLE
Show dirty markers on aggregated values

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7559]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26363&p=131416#p131416)

Hi,

We've noticed that the aggregate column does not show dirty markers for aggregated values. In the demo (https://www.bryntum.com/products/grid/examples/aggregation-column/) if you set showDirty: true, when you make a change to a child record it gets a dirty marker but the rollup values do not.

We'd like to request an option to allow dirty markers on the aggregated values. It should also account for changes to child records that result in the same aggregated value (which should not show dirty markers).

Thanks,
Josh

![Cuf8RQhDzI](https://github.com/bryntum/support/assets/75997756/893cc8e4-6954-4c5c-a65b-d88ebe9f816b)

**Comment by isglass** [comment]
Already supported
