### ISSUE TITLE
Cannot copy task when using deep: true 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#756]
## Note
Please, update docs for `copy` method in `Gantt.model.TaskModel` class. There is 2nd parameter exists which has influence on copied data set because of `ChronoModelMixin` (if required).

Should also offer a flag to copy assignments optionally.

Cannot read property 'constraintType' of undefined when using deep: true while copying.
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=13946&p=72012)

Hi!

Here's how to reproduce the error.

- Load the Basic demo. It's using Gantt v2.1.2.
- In the code editor, change
```
new Gantt({
```
to
```
window.gantt = new Gantt({
```
so it's easily accessible in the console.
- In the console, enter this command:
```
gantt.project.taskStore.add(gantt.project.taskStore.getById(2).copy({deep: true}))
```

Result:
Cannot read property 'constraintType' of undefined

Expected:
The task tree is duplicated successfully

Additional details:
This works fine if I use {deep: false}

**Comment by chuckn0rris** [comment]
We need to implement copy dependencies as well. Maybe add a flag to manage this option.

**Comment by Jerther** [comment]
(forum OP here)
A flag to also copy assignments would be very nice too!
