### ISSUE TITLE
FilterBar feature doesn't keep value in filter field when hide/show a column

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7568]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=26342&p=131477#p131477)

https://bryntum.com/products/grid/examples/filterbar/
https://github.com/bryntum/support/assets/7203098/11f664d3-989e-4489-9374-2ae1a78767a7

**Comment by matsbryntse** [comment]
`clearStoreFiltersOnHide` needs to be made public
