### ISSUE TITLE
State mixin to use configurable's onConfigChange hook

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#758]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=13937&p=71998#p71998)

> Great. Thank you very much! I also looked through the events, but could not find any, which represents the state change. What event would you suggest, if I would like to persists the user settings in the background, without having the user to click a button?

Also:
https://www.bryntum.com/forum/viewtopic.php?p=73163#p73163
https://www.bryntum.com/forum/viewtopic.php?p=84133#p84133

**Comment by chuckn0rris** [comment]
@dongryphon @isglass @ExtAnimal

**Comment by dongryphon** [comment]
It is straight forward in the new `configurable` mechanism to decorate config properties with booleans such as `stateful`:
```javascript
    static get configurable() {
        return {
            width : {
                value : null,
                $config : 'stateful'
            }
        };
    }
```
That simply takes a `stateful : true` on the config descriptor that can be used later.

Changes to any config can be observed in the `onConfigChange` template method. I have TODO's in the code to add `evented` and possibly `preventable` options but these would require logic support in the setter to act upon these properly. They aren't required here if the goal is simply to save values for next time.

**Comment by dongryphon** [comment]
On further reflection, the `stateful` idea is probably best not added like this. The `onConfigChange` is still useful there but probably best to have a config like Ext JS does for those configs that should be saved/restored to state so the customer can tune this.
