### ISSUE TITLE
onBeforeDragMoveEnd returns incorrect datetime on event record

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7587]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=26382&p=131672#p131672)

Background

I am upgrading from v5.3.5 to v5.5.3 to test out the fix for:
#7059 – beforeDragMoveEnd and beforeDragResizeEnd has not correct event ids

Issue

There seems to be a change in the returned date for the onBeforeDragMoveEnd callback. On v5.3.5, when I drag a 1:30PM to 2:00PM event to 2:00PM to 2:30PM, the callback returns the correct updated datetime (2:00PM to 2:30PM).

![Screenshot 2023-09-25 at 12.57.23 PM.png](https://forum.bryntum.com/download/file.php?id=24287)

On v5.5.3, using the same example, the callback does not return the updated date time (it returns 1:30PM to 2:00PM).

![Screenshot 2023-09-25 at 1.03.03 PM.png](https://forum.bryntum.com/download/file.php?id=24288)

This is not ideal for us because we need to upgrade to receive the correct event IDs, but at the same time, the callback seems to now be returning the wrong datetime.

Code

```
            <BryntumCalendar
                ref={calendar}
                project={project}
                onBeforeDragMoveEnd={({eventRecord}) => {
                              const { startDate, endDate } = eventRecord;
                              console.log('startDate', startDate);
                              console.log('endDate', endDate);
                }}
            />

```
![Screenshot 2023-09-25 at 12.57.23 PM.png](https://forum.bryntum.com/download/file.php?id=24287)
![Screenshot 2023-09-25 at 1.03.03 PM.png](https://forum.bryntum.com/download/file.php?id=24288)

**Comment by marciogurka** [comment]
Still reproducible on 5.6.9 (just added the onBeforeDragMoveEnd listener to the basic React demo)


https://github.com/bryntum/support/assets/16693227/eb8c4d9a-4252-4ed5-94e9-ed5e25c31999

**Comment by marciogurka** [comment]
Just saw the new parameters, so, I'll close again.
