### ISSUE TITLE
Cycle when setting ASAP/ALAP on individual tasks level

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#7605]
Reported here: https://forum.bryntum.com/viewtopic.php?f=51&t=26472&p=131937#p131937

Steps to reproduce:

1. make a summary task scheduled ALAP
2. add a subtask scheduled ASAP
3. make the parent task manually scheduled

Result: a cycle is thrown.

...Or simply execute this code in any demo (for example in `basic`):
```js
gantt.project.taskStore.add({
    id                : 'parent',
    name              : 'parent',
    expanded          : true,
    manuallyScheduled : true,
    direction         : 'Backward',
    children          : [{ id : 'child', name : 'child', direction : 'Forward' }]
});

```

**Comment by canonic-epicure** [comment]
Both scenarios passes now.
