### ISSUE TITLE
RecurrenceConfirmation should be configurable to always update one path - "only this" or "all future"

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#7606]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=131983#p131983)

Hello,

I'm trying to figure out how I can overrule the RecurrenceConfirmationPopup and always use "Only this event". I haven't been able to find any configuration I can do to do this, can you guys help me out?

The use case is that we do the recurrence editing on another screen, and the calendar is only used to change specific events.

**Comment by chuckn0rris** [comment]
Should be working for event drag-drop as well

**Comment by taauntik** [comment]
Requested here https://forum.bryntum.com/viewtopic.php?t=28789 too
