### ISSUE TITLE
[REACT] Support rendering JSX in a ResourceHeader.headerRenderer

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#762]
[Forum post](https://bryntum.com/forum/viewtopic.php?f=44&t=13948)
https://www.bryntum.com/docs/scheduler/#Scheduler/view/ResourceHeader#config-headerRenderer

> Since we now have the ability to render JSX in a cellRenderer when the scheduler is in horizontal mode it'd be very nice to be able to do the same in vertical mode.
> I'm building a view where the user can pick the mode themselves and it'd be great if I could reuse the same react component for both cases instead of having to use plain html to support the vertical layout.

**Comment by jsakalos** [comment]
Use information from [the forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=13948&p=72545&sid=8e960647d9deca487e38484150722636#p72183) when implementing it.
