### ISSUE TITLE
Task Duration Limit

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#7624]
Task / Project duration is set to a maximum of 5 years.  Is there a simple fix to remove this constraint?

**Comment by arcady-zherdev** [comment]
There is a config to adjust that range: https://www.bryntum.com/products/gantt/docs/api/Gantt/model/ProjectModel#config-maxCalendarRange
```js
new Gantt({
    project : {
        // adjust calendar iteration limit to 10 years roughly:
        // 10 years expressed in ms
        maxCalendarRange : 10 * 365 * 24 * 3600000,
        ...
    }
});
```
