### ISSUE TITLE
Print demo issues

### ISSUE THREAD

**Issue by isglass** [bryntum/support#7642]
- [x] Both print buttons seems to do the same thing, dialog looks the same:

<img width="718" alt="Screenshot 2023-10-12 at 09 09 50" src="https://github.com/bryntum/support/assets/5415653/09327a16-ffad-4b82-b47e-88c4ef9f10c0">

- [x]  Nice if print dialog was modal (preferably with transparent mask)
- [x] Landscape print in FF on Mac

<img width="1171" alt="Screenshot 2023-10-12 at 09 17 15" src="https://github.com/bryntum/support/assets/5415653/5620f2b7-26f4-4f9c-89a4-b48a0ac303d4">

- [x] Landscape print in Chrome on Mac

<img width="1355" alt="Screenshot 2023-10-12 at 09 18 29" src="https://github.com/bryntum/support/assets/5415653/f099c04e-3db2-468a-ac98-6faa9e74f216">

**Comment by taauntik** [comment]
Print issues Fire Fox on windows
- [ ] Portrait in Fire Fox on windows
![image](https://github.com/bryntum/support/assets/75997756/460d5df6-934b-4865-8b3f-91ff60f3a27e)
![image](https://github.com/bryntum/support/assets/75997756/a8357d1a-bc44-4439-8d53-49f8db9825a9)

- [ ] Landscape in Fire Fox on windows
![image](https://github.com/bryntum/support/assets/75997756/11e95ee9-5084-49e2-9d58-de2fa5109eec)

**Comment by taauntik** [comment]
Scheduler Print issues in Fire Fox on windows

- [ ] Portrait without dependencies
![image](https://github.com/bryntum/support/assets/75997756/869dd16a-4501-404c-8478-fc90560aae16)
![image](https://github.com/bryntum/support/assets/75997756/77e600c2-4d3e-4761-b1f1-b59dbe58de96)

- [ ] Landscape without dependencies
![image](https://github.com/bryntum/support/assets/75997756/1673491b-6088-420f-b683-a5cad7715e2d)

- [ ] Portrait with dependencies
![image](https://github.com/bryntum/support/assets/75997756/24d30069-8100-464c-bfe2-80b4600d3862)

- [ ] Landscape with dependencies
![image](https://github.com/bryntum/support/assets/75997756/58efa3e9-a04d-4ee6-9544-87d301074251)
