### ISSUE TITLE
Issues with `rowexpander-regions` demo

### ISSUE THREAD

**Issue by isglass** [bryntum/support#7645]
- [x] CSS rule to fill width in last column hits wrong element when expanded:

<img width="678" alt="Screenshot 2023-10-12 at 09 27 59" src="https://github.com/bryntum/support/assets/5415653/e681a72d-535f-4f6b-bb27-99f056ba5f65">

- [x] Use a minHeight on the skills grid to match height of buttons: 

<img width="1354" alt="Screenshot 2023-10-12 at 09 34 51" src="https://github.com/bryntum/support/assets/5415653/be159db6-2087-47e5-a93b-f713e95f3c24">

- [x] Empty text could say "No skills assigned" or similar ^
- [x] Add skill does nothing for row that has no skills initially
- [x] "Deactivate" button could perhaps change to "Activate" after click
- [x] Resizing skill column (probably worth its own ticket)

![resizing](https://github.com/bryntum/support/assets/5415653/b9c4830a-1325-404a-b20d-298ae378895f)

**Comment by bmblb** [comment]
- [ ] open time report button shows message saying "we didn't implement logic, but here is a button". We can replace button with smth like `clear skills`

**Comment by JockeLindberg** [comment]
Maybe same as above, but sharing anyway:

Using Edge on Windows:
![image](https://github.com/bryntum/support/assets/100013589/3b35d8e3-6999-45b2-b37b-f0598004eb2c)

gives

![image](https://github.com/bryntum/support/assets/100013589/5de93315-c653-4ff7-949e-6923cb5ff043)

However, if I choose "No margins" in the system print dialog, it fits one page.

**Comment by bmblb** [comment]
@JockeLindberg wrong ticket?
