### ISSUE TITLE
`Name` column shrinks after row expanding in `rowexpander-regions` demo

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#7652]
Steps to reproduce:

1. open the demo
2. collapse the first row (it's expanded initially)
3. expand left grid region width
4. start cell editing `Name` column - the cell editor (and the column) takes all the width available
5. expand the row and start editing the cell again

Result: the column (and the editor) looks shrinked

**Comment by JockeLindberg** [comment]
Same problem root cause as reported in #7963.
Closing this.
