### ISSUE TITLE
Custom `eventLayout` in Scheduler vertical mode

### ISSUE THREAD

**Issue by kronaemmanuel** [bryntum/support#7659]
Feature Request for custom `eventLayout` fn in Scheduler Vertical Mode.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26595&p=132554#p132554)

Hi guys, 
 
we need a custom eventLayout similar to the "Layout function" on https://bryntum.com/products/schedulerpro/examples/custom-layouts/ - but for vertical mode. The docs don't mention any limitation when switching the mode.
 
Right now, the function is ignored entirely (doesn't even log anything) after setting

```
mode: 'vertical'
```
 
Please let me know if this can be done, or if there are any known workarounds.

Thanks in advance,
Martin

**Comment by jbrtl** [comment]
Hi @kronaemmanuel I don`t see it as a feature request, but as a bug. By switching the mode the setting doesn`t work. If there are no limitation in useing it according to the docs, then I expect the feature to work in all modes.

**Comment by einmalick** [comment]
The layoutFn should have a reference to scheduler as mentioned in #5133

The ref is currently still missing in vertical mode:

`new SchedulerPro({
    mode: 'vertical',
    eventLayout : {
        layoutFn(items) {
            console.log(this.scheduler) // => undefined
           // this.scheduler is not defined
           return this.scheduler.rowHeight
        }
    }
})
`
`new SchedulerPro({
    mode: 'horizontal',
    eventLayout : {
        layoutFn(items) {
            console.log(this.scheduler) // correctly logging scheduler ref in horizontal mode
            // this.scheduler is
            return this.scheduler.rowHeight
        }
    }
})
`
