### ISSUE TITLE
TaskEditor not vertically scrollable when shown on a small screen

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#7683]
https://bryntum.com/products/schedulerpro/examples/travel-time/

**Comment by ExtAnimal** [comment]
In what way is this a regression? The form containing tabs have never had

```
scrollable : {
    overflowY : true
}
```

The tab panel was always heighted to accommodate the tallest tab. Popups have always been constrained to show within the viewport which removes come of that height.

If the forms should scroll, configured them `scrollable`
