### ISSUE TITLE
Overflow avatar is not the rightmost avatar

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#7686]
Recent regression, works in release branch

https://bryntum.com/products/gantt-next/examples/drag-resources-from-grid/
<img width="483" alt="Screenshot 2023-10-16 at 17 54 21" src="https://github.com/bryntum/support/assets/218570/413ab1ba-1f1b-4c7d-8117-61b56ba97d3c">

**Comment by ExtAnimal** [comment]
`resourceassignmentcolumn.scss`

The `.b-overflow-img` rule lost its `position : relative;` last month: https://github.com/bryntum/bryntum-suite/pull/7823/files#diff-94016c5c0cf20d82cbc3493cd113ffdcd46a8565a91371fc94d8f081ad33bf0fL43
