### ISSUE TITLE
[Salesforce] Error when open Grid in Firefox if LWS enabled

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7690]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26626&p=132738#p132738)

Hi,

Opening and interacting with any grid-based component in Salesforce with LWS enabled using Firefox results in "Lightning Web Security: Cannot access rangeParent" error modals being repeatably fired until the entire screen is black.

This is reproducible in https://bryntum-dev-ed.develop.lightning.force.com but is also present in our product.
![Screenshot 2023-10-17 at 12.32.25.png](https://forum.bryntum.com/download/file.php?id=24578)

**Comment by marciogurka** [comment]
User mentioned a workaround [here](https://forum.bryntum.com/viewtopic.php?p=132748#p132748)
