### ISSUE TITLE
[REACT] Issue when loading more events with segments

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7700]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=26649)

Hi!

We see issues when adding more events to the scheduler with segments.

In the attached video, my example app simulates appending more and more events and assignments to the list, and there are two weird behaviors that are occurring:

One segment somehow turns into a milestone
We see console log errors complaining about getTime not being a function.

You can try it out yourself in the attached example app.

This is a major blocker for us, so we would appreciate if you could prioritize looking at this.

Thank you!

https://github.com/bryntum/support/assets/75997756/1d002fe6-0bfa-40a4-a762-d81aa84c89f3

**Comment by canonic-epicure** [comment]
Seems its not reproducible with 5.6.10 anymore:
https://github.com/bryntum/support/assets/72431/5f6848b9-da27-478b-b520-81f9f2dad297

**Comment by canonic-epicure** [comment]
Seems its not reproducible with 5.6.10 anymore

**Comment by canonic-epicure** [comment]
Closing this one as not reproducible.
