### ISSUE TITLE
NumberField limits typed input to minimumFractionDigits not maximumFractionDigits (ex: "9,999.99#####")

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#7703]
On setting the `numberField` `format` attribute to '9,999.99#####' should result in the 7 maximum fraction digits but unable enter the value 1.010101.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=26651&p=132838#p132838)

Hi, I have a number type column configured with the following template for the format attribute:
'9,999.99#####'
Because of this configuration, I’m not able to specify a double value for this kind of column like '1.0001' , although I’m able to specify '1.0010' According the documentation, I understand that these mentioned properties should set the minimum and maximum number of decimal digits. It is also expected that the minimumFractionDigits property sets the máximum number of sequential zeros allowed after the dot? To be honest, I don’t understand it by reading the documentation. May it be a lack of it, some kind of defect or a misunderstanding by myself?

Thank you in advance!

**Comment by dongryphon** [comment]
The issue is caused when typing `0`s after reaching `minimumFractionDigts`. As the field reformats the input, the trailing 0 is removed as the `format` indicates. The fix will be something along the lines of allowing trailing 0's during input.

**Comment by dongryphon** [comment]
To clarify `decimalPrecision=3` is equivalent to `maximumFractionDigits=3` and `minimumFractionDigits=0` or `format='9.###'. It is perhaps more intuitive in some sense, as in less to think about, but is ambiguous regarding trailing zeros. For example, `decimalPrecision=3` doesn't convey whether you will see "1.000" or "1". While `format='9.###'` vs `9.999` is certainly more flexible, it perhaps requires more learning to master.
