### ISSUE TITLE
Link is created to a task when trying to abort building the link

### ISSUE THREAD

**Issue by mazzafabio** [bryntum/support#7716]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=26668)

When building a link, and I happen to mouse-over a task that is a valid task to link to, after moving cursor off of the task, it continues to hold it as the task to link to. Letting go of the cursor in space, trying to cancel the creation of the link, it still gets created. See image attached.

in earlier versions (5.4) taking my cursor off of the task would remove that task as the item to link to, and enable canceling the link build. Can that behavior be restored?
![bad link.png](https://forum.bryntum.com/download/file.php?id=24643)

Step to reproduce it:
1) Go to this [gantt example](https://bryntum.com/products/gantt/examples/advanced/) (however it occurs in scheduler / schedulerPro as well).
2) Try to create a valid dependency by dragging from the terminal of a task to the terminal of another task WITHOUT DROP ON IT.
3) Keeping the mouse down, move away from the task to link to and look at the popup: in the description still remains the old task info.
4) At this point, if dropped to an empty space, the link is still created: the correct flow should end up with the abort of the link building.

**Comment by egraves-accuer** [comment]
This is still happening on 5.6.2 - both on our local version and on your samples site.
![image](https://github.com/bryntum/support/assets/93935209/82b5d5c7-3b38-48ed-a481-4c649ef9a35f)

-Eric
