### ISSUE TITLE
undefined query parameter in CrudManager URLs

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#772]
[https://www.bryntum.com/examples/gantt/basic/](https://www.bryntum.com/examples/gantt/basic/)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=13962&p=72081#p72081)

Here's how to reproduce. Just load the Basic demo while watching for the load query in the network monitor. Here's what it does:

```
Request URL: https://www.bryntum.com/examples/gantt/_datasets/launch-saas.json?undefined=%7B%22type%22%3A%22load%22%2C%22requestId%22%3A15894808349900%2C%22stores%22%3A%5B%22timeRanges%22%2C%22calendars%22%2C%22tasks%22%2C%22dependencies%22%2C%22resources%22%2C%22assignments%22%5D%7D
```

I'm pretty sure the "undefined" parameter shouldn't be there

**Comment by matsbryntse** [comment]
Test + assert added to 772-undefined branch
