### ISSUE TITLE
Improve ProgressBar column

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#773]
Base it on new ProgressBar column class.

Remove our gray background by default, should look like modern options below:

https://files.slack.com/files-pri/T3AJK2M0C-F013NRGSFDK/screenshot_2020-05-15_at_11.45.20.png

Option to have text outside bar
labelPosition: 'inside' / 'left' / 'right'

![image](https://user-images.githubusercontent.com/218570/82036861-b04da100-96a1-11ea-9ba8-5282d444a815.png)

<img width="691" alt="Screenshot 2020-05-15 at 11 46 36" src="https://user-images.githubusercontent.com/218570/82036914-c0fe1700-96a1-11ea-8813-e3f13a2e1f79.png">

**Comment by isglass** [comment]
Background or not should be easily configurable, when not sorted by the column background gives a less messy feeling in my opinion
