### ISSUE TITLE
[REACT] Implement JSX support for widget content

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#774]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=13949&p=72060&sid=15ac52ce9b7542608bc99e58ad811c68#p72060)

[And here](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21089&p=104476#p104476)
I started using the react advanced demo as reference and then read that I need to use the BryntumGantt component from bryntum/shared on the examples to be able to render a react component. I was able to render a react component on a column, but I'm not hable to do the same inside the pop up. Also, I would like to be able to use a react component inside the Core.widget.Popup. Is any of this possible?

How can I create my own react components on taskEditor pop up custom tabs?

Thanks

---
The idea is to have a widget that would be capable of rendering a JSX as its content in React apps.

**Comment by alex20044** [comment]
+1. I believe that this is a very important feature.

**Comment by taauntik** [comment]
[Requested here too](https://bryntum.com/forum/viewtopic.php?f=52&t=20986&p=103914#p103914)

**Comment by jsakalos** [comment]
The implementation should also provide support for:
- [ ] headers
- [ ] events
- [ ] tooltips

**Comment by chuckn0rris** [comment]
Requested here https://www.bryntum.com/forum/viewtopic.php?f=43&t=22392&p=110817#p110817

**Comment by jsakalos** [comment]
From the potential user:

> We’re evaluating Bryntum’s React Gantt. A feature that’s required for us is being able to customize the task tooltip and the task editor by providing our own React components. This is a critical feature for us since we’re using very complex components and we want to ensure reusability and consistency across the application. We haven’t been able to find any mention of how to do this on the React docs and I saw this thread (started in 2020) https://forum.bryntum.com/viewtopic.php?t=13554&hilit=fetchTooltipHtml&start=10 that seems to indicate that the feature hasn’t been developed. Is this feature supported now? If it is, that would be a quick buy decision for us.
