### ISSUE TITLE
Start date column not working when set min value

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7742]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26701&p=133182#p133182)

- Go to [https://bryntum.com/products/gantt/examples/advanced/](https://bryntum.com/products/gantt/examples/advanced/)
- Add the following configuration for the start date column
```
{ type : 'startdate', min: new Date(2018, 1, 14) }
```
- Try to open the editor, an error is triggered

<img width="1381" alt="Screenshot 2023-10-25 at 13 39 47" src="https://github.com/bryntum/support/assets/16693227/b81eba08-1b1f-4bbb-9364-4726204eed5b">

**Comment by ExtAnimal** [comment]
Suggested code here: https://github.com/bryntum/bryntum-suite/pull/8076/files
