### ISSUE TITLE
Unable to copy rows from Gantt to clipboard.

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7749]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26722&p=133230#p133230)

Hello bryntum team,
Thank you for your support.

I'm trying to copy rows from Gantt.
I'm using rowCopyFeature with useNativeClipboard = true and copyOnly = false.
Why am I not able to copy the row to my clipboard ?

![clipBoard1.gif](https://forum.bryntum.com/download/file.php?id=24719)

**Comment by JockeLindberg** [comment]
Closing this. RowCopyPaste and TaskCopyPaste shouldn't both be active.
