### ISSUE TITLE
`StateTrackingManager` events not firing on Event edit from column

### ISSUE THREAD

**Issue by kronaemmanuel** [bryntum/support#7790]
Issue reproducible in vanilla too

I'm using the StateTrackingManager, and events (recordingstop, restoringstop) are only firing when changes are made from the "Edit" modal. These events are not firing when editing fields directly from the Gantt chart.

[Forum Post](https://forum.bryntum.com/viewtopic.php?t=26805)

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=134111#p134111) for this

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/a7e1af92-2c83-49a6-992f-fbf75fbdafe8

**Comment by canonic-epicure** [comment]
Does not seem to be reproducible (see the video above), or perhaps you need to provide the fully runnable test case, to demonstrate the issue.

Also, you can check if adding an extra listener for `disabled` event on `stm` instance removes the need for the workaround: https://bryntum.com/products/schedulerpro/docs/api/Core/data/stm/StateTrackingManager

**Comment by canonic-epicure** [comment]
Closing this one as not reproducible, please feel free to re-open with more information.
