### ISSUE TITLE
Cannot configure mode selector as minified

### ISSUE THREAD

**Issue by isglass** [bryntum/support#7808]
Try this in a demo:

```
 tbar : {
        items : {
            modeSelector : {
                minified : true
            }
        }
}
```

- [x] Minified works
- [x] Make the minified button show menu icon and not the calendar icon, except for when very minimized - then show only calendar icon

Large size:
![image](https://github.com/bryntum/support/assets/722969/c112a9ce-ccb4-4be1-9f55-1c5ae3f9d0c6)

Tablet / medium size:
![image](https://github.com/bryntum/support/assets/722969/ed01d082-2c98-4a49-9bdd-ceb65685057f)

Small size:
![image](https://github.com/bryntum/support/assets/722969/e2916f38-7769-4243-b82d-5c29a085b32b)

**Comment by dongryphon** [comment]
Blocked by #6441
