### ISSUE TITLE
Time selection should support drag create

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7828]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=26857&p=134030#p134030)

Hi Team,

I'm wondering if it's feasible to enable users to drag and select a date range directly from the view preset header. Similar to how we can drag and select dates when creating an event. 

Thanks!
![Screenshot 2023-11-08 at 11.27.23 AM.png](https://forum.bryntum.com/download/file.php?id=24942)

**Comment by Pallavid28** [comment]
Can you please provide the implementation part.

**Comment by matsbryntse** [comment]
It's available in our upcoming 6.0 release. If you have a license, you can grab the nightly build from our customer zone to try it out.
