### ISSUE TITLE
Show error message in event editor for overlapping event if `allowOverlap : false`

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#7835]
Currently if `allowOverlap` is set to `false` then clicking on save button does nothing when event is overlapping some other event. We need to show the error message in this case.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=26856&p=134094#p134094)

i am pretty new to the bryntum world but i have a calendar i am working on for scheduling.

I am disallowing overlapping events per resource  

```
allowOverlap : false
```

How can i catch when an event is prevented/blocked and show a warning?

I could either show a warning, or simply highlight the field in the event editor in the same way that would happen if a required input was missing.  Currently the overlapping event is blocked from being saved, but there's no error or warning that would be obvious to the user why it was blocked.

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/5597
