### ISSUE TITLE
[TypeScript] Missing layout classes and config types

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7836]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=26275&p=134076#p134076)

Checking the documentation and this [ticket](https://github.com/bryntum/support/issues/7520), the following configuration should be valid 

```
export const calendarConfig : Partial<CalendarConfig> = {
    // other configurations...
    viewContainer : {
        layout : {
            animateCardChange : false
        }
    }
};
```

But the types do not match correctly.

<img width="503" alt="image" src="https://github.com/bryntum/support/assets/16693227/debed1ed-337c-42e9-852a-a4a230952c7e">

**Comment by ExtAnimal** [comment]
The generation of the `LayoutConfig` could be improved. Right now, it pulls in properties from only the `Layout` class.

Would it be possible to label that class as `@polymorphic`? Which would indicate to the docs generation that it should include in config props all config props from _classes which extend that class_.

So `LayoutConfig` should aggregate the config options not only of itself, but also of `Card`, `Box`  and `Fit`
