### ISSUE TITLE
TimeSelection feature to also offer drag-create of selection

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#7837]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=134121#p134121)

Also, it should show tooltip which has a configurable content callback.

**Comment by taauntik** [comment]
dupe https://github.com/bryntum/support/issues/7828

**Comment by taauntik** [comment]
tooltip property needs to be added to timeSelection to customize the tooltip with configs

**Comment by ExtAnimal** [comment]
There is code in there which *looks like* it was intended to handle drag-creation of a time selection. But none of it works.
