### ISSUE TITLE
TimeSelection on booking demo should should total amount of all available cells

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7838]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=26857&p=134030#p134030)

The goal is to check which resources are available during those dates (when users select a date range) and we would like to highlight the available resources by showing the total booking amount for those days.

I've attached a mock-up screen to illustrate the idea.

Thanks!
![Screenshot 2023-11-08 at 11.27.23 AM.png](https://forum.bryntum.com/download/file.php?id=24942)

**Comment by ExtAnimal** [comment]
The example app needs a little extra validaton:

<img width="955" alt="Screenshot 2023-11-09 at 08 49 26" src="https://github.com/bryntum/support/assets/200516/4d542ec5-0fc9-4e04-9497-e16d0549f142">

**Comment by ExtAnimal** [comment]
Add this:

```
    onBeforeEventEdit({ eventEdit, eventRecord, resourceRecord }) {
        // Ensure the guest count field conforms to the defined property's maximum
        eventEdit.editor.widgetMap.guestsField.max = resourceRecord.sleeps;
    },
```

**Comment by matsbryntse** [comment]
Max setting fixed, other requirements seem like application domain
