### ISSUE TITLE
Add vertical lines to the scheduling

### ISSUE THREAD

**Issue by JonSagarminaga** [bryntum/support#7844]
Is there any way to add lines in the scheduling without putting the hours? For example, to gofrom this:

![image](https://github.com/bryntum/support/assets/55576623/396a37f0-b07d-420a-a429-82c760b4bcae)

To this (adding vertical lines but not hours texts in halfs hours):
![image](https://github.com/bryntum/support/assets/55576623/c5e00bc2-e260-45e2-bf4c-b926ab990485)

And it would be possible add those lines only in the .pds export? Not in screen view, for helping the view in case they want print it.

**Comment by marciogurka** [comment]
Hey @JonSagarminaga, perhaps a custom view preset would work for you? Please check the documentation here https://bryntum.com/products/schedulerpro/docs/api/Scheduler/preset/ViewPreset#defining-custom-header-rows

Also, please don't open tickets here, this is for our customer support only, please start a thread on our forum support explaining your situation and we can assist you better from there. https://bryntum.com/forum/
