### ISSUE TITLE
Clicking on event, changes the start date of the view

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7846]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=26880&p=134168#p134168)

Hello,

When using the '2 Weeks' range view, on event click, the day of the selected event (which in this case is an event that falls in the second week) becomes the first day of the view now - meaning the start date is being changed.
Having said this, can you please tell me how to stop the view change on even click?

There is video attached, please take a look and try to reproduce the scenario.

https://github.com/bryntum/support/assets/75997756/08748bf1-859f-44eb-b713-5a34550f86c0

reproducible here http://lh/bryntum-suite/calendar/examples/date-resource/
With this code
```javascript
    modes : {
        day         : null,
        week        : {
        range : '2 week'
    },
```

**Comment by ExtAnimal** [comment]
The poster should use `DayView` to encapsulate an arbitrary range of dates.

But when using that, there is a bug:

The fix in in `DateRangeOwner.updateDate`,

It needs

```
            // If there's no endDate, we MUST be configured with a range, so snap
            // the date to the closest range start.
            else {
                // Round the date to the start of our range boundary. Must *base* it from the current startDate
                me.startDate = DateHelper.floor(date, me.range, me.startDate, me.weekStartDay);
            }

```
