### ISSUE TITLE
[SALESFORCE] Multi event select not selecting events in Salesforce

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7850]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26873&p=134120#p134120)

Hi,

Multi event selection feature fails to select the events in the bryntum salesforce demo.
Version which we used to test this is scheduler 5.5.4

please check this
![regionSelect2.gif](https://forum.bryntum.com/download/file.php?id=24980)

This feature works fine in the online example
![regionSelect1.gif](https://forum.bryntum.com/download/file.php?id=24979)

I turned on the following config and feature.
```
// config
multiEventSelect : true
// features
eventDragSelect : true
eventDragCreate : false.
```

**Comment by chuckn0rris** [comment]
@JockeLindberg if it will be possible and fix not required changes in ,any files, please share a patch fix with a customer in forum thread.

**Comment by chuckn0rris** [comment]
Reproduced in current release. Reopened.

**Comment by JockeLindberg** [comment]
Asked the poster to try again, since we couldn't repro it (Alex attempt was faulty bacause of cache).
No response, so closing.
