### ISSUE TITLE
ColumnReorder feature optionally highlight using a full height drag proxy

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7870]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=26928&p=134422#p134422)

Hi everyone,

I am trying to highlight the area of the column on Column Drag
I was able to highlight the column but not the whole area.
![Screenshot 2023-11-15 at 1.31.23 PM.png](https://forum.bryntum.com/download/file.php?id=25055)

So I am looking for a solution with which I can highlight the whole area of a column on column drag.

**Comment by matsbryntse** [comment]
https://github.com/bryntum/support/assets/218570/8c88a37d-9d5a-4d07-80ee-4c19f2a61d33
