### ISSUE TITLE
`Scheduler` cannot set width when placed alongside with `Panel` 

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#7873]
## Steps to reproduce

Combine `Scheduler` and `Panel`  in one `div`.
When you resize div's width, so event's left side is at the edge of visible area, you get this behavior in `Chrome`. 
It is infinite loop.

Replace code for `basic` Scheduler app here:

Scheduler/examples/basic/app.js

with:

```
import Panel from '../../lib/Core/widget/Panel.js';
import Scheduler from '../../lib/Scheduler/view/Scheduler.js';

document.body.innerHTML = '<div id="mycontainer" style="display:flex; flex: 1"></div>';

const scheduler = new Scheduler({
    appendTo  : 'mycontainer',
    columns   : [{ id : 'name1', text : 'Name', field : 'name', width : 150 }],
    startDate : new Date(2011, 0, 5),
    endDate   : new Date(2011, 0, 8),
    events    : [{
        id        : 1,
        startDate : new Date(2011, 0, 8),
        duration  : 4,
        name      : 'Assignment'
    }],
    resources   : [{ id : 'r1', name : 'Mike' }],
    assignments : [{ resourceId : 'r1', eventId : 1 }]
});

const panel = new Panel({
    appendTo : 'mycontainer',
    html     : 'My panel',
    width    : 500
});
```

Then navigate to:
http://lh/bryntum-suite/Scheduler/examples/basic/

Try resizing window.

![ResizeLoop](https://github.com/bryntum/support/assets/57486330/da8b5a53-874d-486a-8ef3-b26a23e66f58)

**Comment by ExtAnimal** [comment]
Who came up with this scheme? Because it's all kinds of messed up.

Whether #mycontainer has overflow:hidden makes a difference. The fact is that not everything you throw at any software is guaranteed to do something valid.

**Comment by ExtAnimal** [comment]
Setting the scheduler to suppressFit : true stops this.
