### ISSUE TITLE
Planned % Complete

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#790]
Can you implement a Planned % Complete custom field please?

We have Actual % by assigning progress, but calculating Planned % complete is essential for tracking project shift

**Comment by matsbryntse** [comment]
Sure, we'll take that into consideration - thanks for the feature request! :)

**Comment by isglass** [comment]
Removed high prio, we have other more requested features that need implementing first

**Comment by MRC38** [comment]
When do you think you will incorporate the planned % complete feature?

**Comment by MRC38** [comment]
Is a Planned % complete calculation in your plans for the near future?  I see in June 2022 you removed the high priority label

**Comment by canonic-epicure** [comment]
[x] Status date field on project, refer to it from `ProgressLine` feature and from PlannedPercentDone column (if not specified on those features directly)
[x] Localization
[x] Use calendar for duration calculation
[x] Separate demo?
