### ISSUE TITLE
Event flashes after drag creating new event

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#7913]
https://github.com/bryntum/support/assets/218570/809d6a8c-65a0-4b45-a673-8d8aaa9e690a

**Comment by ExtAnimal** [comment]
The change at this line has been reverted: https://github.com/bryntum/bryntum-suite/commit/0ef58ae1a0bc78ebbf09b5e3ea916e530d1e9bc2#diff-4c3e33f4f09d47ab447a64abf7e5e757eb9274fb37a7e42a588c0ac83a4bf780L379

cleanup was being invoked during drag when there are two views which may both take on the dragging. In this case `DayView` and its `CalendarRow`. The two zones can start and stop dragging as the mouse moves between them.

It caused errors to be thrown when dragging. Tested here: https://github.com/bryntum/bryntum-suite/blob/release/Calendar/tests/examples/basic.t.js#L19
