### ISSUE TITLE
Print should support Salesforce

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#7917]
`<link>` tags are stripped by patched `parseFromHTML`. Salesforce print need to use different way to load styles to an iframe.

**Comment by chuckn0rris** [comment]
another [request](https://forum.bryntum.com/viewtopic.php?f=51&t=27904&p=139961#p139961)

**Comment by Howrd** [comment]
Hello, is there at ETA for this fix? We're also encountering it at Certinia.

In addition, the iframe produced isn't hiding in it's entity in the Salesforce Lightning environment. It leaves a small amount of visible space. Could you change this to use display=none instead?

**Comment by bmblb** [comment]
@Howrd we will look into it this/next week

**Comment by bmblb** [comment]
`contentDocument` is not supported on the IFrame element in LockerService. Therefore Print feature cannot work with locker service
