### ISSUE TITLE
Fix getAssignmentsForEvent param type inside AssigmentStore

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7920]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27073&p=135204#p135204)

The function available here [https://bryntum.com/products/schedulerpro/docs/api/Scheduler/data/mixin/AssignmentStoreMixin#function-getAssignmentsForEvent](https://bryntum.com/products/schedulerpro/docs/api/Scheduler/data/mixin/AssignmentStoreMixin#function-getAssignmentsForEvent)

has a different parameter type compared to here [https://bryntum.com/products/schedulerpro/docs/api/Scheduler/data/mixin/EventStoreMixin#function-getAssignmentsForEvent](https://bryntum.com/products/schedulerpro/docs/api/Scheduler/data/mixin/EventStoreMixin#function-getAssignmentsForEvent)

<img width="534" alt="Screenshot 2023-11-27 at 14 07 23" src="https://github.com/bryntum/support/assets/16693227/0bda3e1b-9a52-42c1-8d05-9dab721d4a5e">
<img width="669" alt="Screenshot 2023-11-27 at 14 08 10" src="https://github.com/bryntum/support/assets/16693227/1c7dff6e-43e6-430f-a0cb-5040f760fdad">

**Comment by isglass** [comment]
Docs for EventStoreMixin are incorrect, it only accepts records, not ids (string / number)
