### ISSUE TITLE
Ctrl + v creates a new task instead of pasting data in cell

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7933]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=27088&p=135266#p135266)

Hi everyone,

I have text copied in the clipboard that I want to paste in the name cell of a task in Gantt Grid but when I press ctrl + v after selecting the name cell of the task on which I want to paste my text it creates a new task with a blank name.

The issue can be easily produced on this demo,
https://bryntum.com/products/gantt/examples/advanced/
1. Steps to reproduce:
2. Copy some text
3. Select the name cell of any task
4. Press ctrl + v

![chrome_0hm2aqRQc2](https://github.com/bryntum/support/assets/75997756/d2139811-4ea6-40d9-85ae-069eaa0f4eb0)

**Comment by JockeLindberg** [comment]
This is related and will party be resolved by https://github.com/bryntum/support/issues/7966.
But if the CellCopyPaste feature is active (which it is in the Advanced demo), we need another fix (this ticket).
