### ISSUE TITLE
Can resize event out of original bounds

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#7952]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=27130&p=135428#p135428)

Hi there, 

in SchedulerPro 5.6.2, I noticed you can do the following two things when resizing an event:

1. when resizing the end of an event, resize it to end earlier than the original start (Though in final state end date does not exceed the start date)
2. when resizing the start of an event, resize it to start later than the original end (Though in final state start date does not exceed the end date)

I was wondering if that is a new feature or actually a bug, since I believe this was not the case in previous versions. I thought it may be a bug because as you can see in the video,  when resizing beyond the original bounds,  the tooltip is not getting updated with the new dates, and also the validatorFn of eventResize is not getting called again.

https://github.com/bryntum/support/assets/52177956/175849c6-cc42-47ed-8c7c-3f090113eb94

**Comment by ExtAnimal** [comment]
Regression is here: https://github.com/bryntum/bryntum-suite/pull/7872/files#diff-a2e1d1ec9b52000e22ed5a32e33fa30262181d9b35e8af6fa883845f95627639L744
