### ISSUE TITLE
Add "fixed" elements on the side of rows in Scheduler

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#7965]
- [x] renderer method to present next to the arrow (like the start / end date) can be a good. include count before/after as params

We have already added support for this in Gantt. User wants the same behaviour for Scheduler as well here https://github.com/bryntum/support/issues/5152#issuecomment-1810032470

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=22211&p=135537#p135537)

Hi Bryntum team,

Problem:
Really often, it's quite hard to read a gantt / scheduler when starting from a "blank" part of the agenda, or when navigating in a blank part of a gantt.

For that, we'd like to:
Show the name of task as "fixed" on the left
Show right / left arrows to scroll to the task horizontally

In attachement a video of what we'd like to do with bryntum.

Do you know a way to provide these two features ? 

Thanks a lot

**Comment by Aarbel** [comment]
@ghulamghousdev this feature is highly necessary as we wait for it since one year and a half (cf #5152).

When do you plan to include it inside the scheduler ? (maybe with a number possible to display in the arrow if 1 or more elements are on the right or left)

Thanks a lot !

**Comment by matsbryntse** [comment]
@Aarbel Do you have any video showing how you'd like the interaction / UX?

**Comment by Aarbel** [comment]
at least @matsbryntse just like #5152

I just suggested a little additional option: being able to display a number in the arrow of total events on the left or right (but that's really a nice to have, having left + right arrows in the scheduler to show that there are elements on the right or left on this line would be perfect first)


https://github.com/bryntum/support/assets/25119847/c31ce1d9-e60d-4c3d-a195-3fcae594d7c6

**Comment by Aarbel** [comment]
@matsbryntse do you have any news about this little element ? 

cf https://forum.bryntum.com/viewtopic.php?p=138200#p138200

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=138200#p138200) for this.

**Comment by Aarbel** [comment]
@marciogurka @matsbryntse 

here a little UI screen for the issue:

- Clicking on a arrows makes the user jump to the "next" event on the left or the right 
<img width="1096" alt="image" src="https://github.com/bryntum/support/assets/25119847/ac812d4b-daf1-4b7e-aade-0efa2a987591">

**Comment by matsbryntse** [comment]
Thanks for the input! Should have it wrapped up shortly.

**Comment by Aarbel** [comment]
Thanks a lot @matsbryntse

**Comment by Aarbel** [comment]
@matsbryntse do you have any news including this in scheduler , Thanks a lot !

**Comment by Aarbel** [comment]
thanks @kronaemmanuel

**Comment by Aarbel** [comment]
@kronaemmanuel @matsbryntse 

After testing the scrolling arrows feature on Gantt, keep in mind these two fixes to have a fully working feature for scrolling arrows:

- https://forum.bryntum.com/viewtopic.php?p=143316#p143316
- https://forum.bryntum.com/viewtopic.php?p=143318#p143318

**Comment by Aarbel** [comment]
cf https://github.com/bryntum/support/issues/8895

**Comment by Aarbel** [comment]
thanks a lot @kronaemmanuel 

I just updated the last checkbox to make it even more clear

**Comment by Aarbel** [comment]
thanks @SergeyMaltsev

**Comment by matsbryntse** [comment]
@Aarbel Just wanted to follow up on your requirements, are the scroll buttons working the way you like now? If not, can you please post your list of improvement suggestions in our forums? https://forum.bryntum.com/
