### ISSUE TITLE
Document how to make custom themes based on the npm package

### ISSUE THREAD

**Issue by isglass** [bryntum/support#7990]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=27168&p=135738#p135738)

Current guides assume local sources.

Also make per product per framework theming demos.

**Comment by taauntik** [comment]
Docs should mention changing the path of font to correct path
```
$fa-font-path: "@bryntum/grid/fonts";
```

[Forum Post](https://forum.bryntum.com/viewtopic.php?p=136022#p136022)

**Comment by khattakdev** [comment]
@isglass please confirm if this is different than https://github.com/bryntum/support/issues/8618
