### ISSUE TITLE
Project lines are missing when you change time span

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#80]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=51&t=12652

To reproduce on advanced demo, move default start dates to 2020 and zoom to fit. See lines are missing. Re-enable the feature - lines appear.

**Comment by SergeyMaltsev** [comment]
Also reported here
https://www.bryntum.com/forum/viewtopic.php?f=52&t=13083

Note that Project lines are also not synchronized with project on resize.

![Project-Lines-Synch](https://user-images.githubusercontent.com/57486330/72056430-cb289700-32f6-11ea-86b1-6f609e7b9bfc.gif)
