### ISSUE TITLE
[REACT] `resourceTimeRangeRenderer` function is not  supported

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8035]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27286&p=136271#p136271)

Please install the attached demo
[inline-data.zip](https://github.com/bryntum/support/files/13647702/inline-data.zip)

See that the `console.log` is not logging in the console from `resourceTimeRangeRenderer`

**Comment by jsakalos** [comment]
I have investigated it and the new function `resourceTimeRangeRenderer` is really missing from the wrapper. @SergeyMaltsev may need to add it to a list in the wrapper generators.

**Comment by SergeyMaltsev** [comment]
@jsakalos it is `fn` not a config so it is not valid for setting it in config.
https://bryntum.com/products/schedulerpro/docs/api/SchedulerPro/view/SchedulerPro#function-resourceTimeRangeRenderer

We have this in Scheduler booking demo for 5.6.3
Scheduler/examples/frameworks/angular/booking/src/app/app.component.ts

Should be set after component is created in app code.

**Comment by jsakalos** [comment]
I see, fair enough. @taauntik inform please the user and help him if he doesn't know how to do that.

**Comment by SergeyMaltsev** [comment]
I see in docs examples for [ResourceTimeRanges](https://bryntum.com/products/schedulerpro/docs/api/Scheduler/feature/ResourceTimeRanges#rendering-custom-html-markup) it is used as config. So it has wrong declaration in API.
Should be moved to configs with appropriate `Function` type, parameters, etc.

**Comment by taauntik** [comment]
User wants it as a config to use like `eventRenderer`
https://forum.bryntum.com/viewtopic.php?p=136393#p136393
