### ISSUE TITLE
Wrong URL pushed when navigating to React Guide from Docs Search

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8037]
When searching React in Docs Search, the result React Guides pushes wrong url and eventually page is not found.

- Wrong URL: https://bryntum.com/products/scheduler/docs/api/Integration/React
- Correct URL:https://bryntum.com/products/scheduler/docs/api/integration-react

https://github.com/bryntum/support/assets/52177956/f279ecbb-8d7b-4ca4-879e-cb599fc4352e

Same behaviour for the other items shown in the screenshot:

<img width="265" alt="Screenshot 2023-12-12 at 5 56 35 PM" src="https://github.com/bryntum/support/assets/52177956/df7d0a54-ba2d-46be-bc4e-5f6893d90561">

**Comment by khattakdev** [comment]
It should direct the users to the overview page. The guide page is a subpage in every language integration. Moreover, it should be renamed from "Guide: React" or "Guide: Angular" to "Integration: React" or "Integration: Angular"

That being said, we also need to fix this: (https://github.com/bryntum/support/issues/8038)
<img width="600" alt="image" src="https://github.com/bryntum/support/assets/37709578/c52a849d-148c-47cc-bfe3-27d23154acb9">

@matsbryntse your thoughts?
