### ISSUE TITLE
Setting task.cls using model.set method doesn't update the value and DOM

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#804]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=13996#p72268

http://lh/bryntum-suite/scheduler/examples/basic/
Expect `scheduler.eventStore.first.set('cls', 'foobar')` to add 'foobar' class to the task Dom element similar to `scheduler.eventStore.first.cls = 'foobar'`

```
scheduler.eventStore.first.set('cls', 'foobar')
//{cls: {…}}
scheduler.eventStore.first.get('cls')
//"foobar"
scheduler.eventStore.first.cls
//DomClassList {Symbol(dirty): true}Symbol(dirty): trueisDomClassList: (...)length: (...)value: 
scheduler.eventStore.first.cls.value
//""
```

**Comment by JeffDerk** [comment]
Also cls.add('test') or cls.remove('test') does not update the DOM.
