### ISSUE TITLE
If `visibleDate` is set multiple times before paint, Scheduler goes into infinite loop

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8071]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=27331&p=136510#p136510)

Hi, we are using the Calendar + Scheduler integration and we're currently experiencing a nasty bug that leads to a crash.

Steps to reproduce:
1. use the default demo (https://bryntum.com/products/calendar/examples/calendar-scheduler/)
2. Set the following config:
```
mode: "month"
``` 
and 
```
date: new Date()
```
3. click on an event that's not in the current week; then click on the Timeline button.

Screen recording: https://www.dropbox.com/scl/fi/j27gd59nbujw77oytmslc/bryntum-freeze.mov?rlkey=i0avtppy125gekg20fpwknhhu&dl=0

Using Calendar 5.6.3.

https://github.com/bryntum/support/assets/52177956/0c11013b-9cab-4410-8b8a-051916d50472

**Comment by ExtAnimal** [comment]
`TimelineBase.js` needs

```
    updateVisibleDate(options) {
        const me = this;

        // Infinite scroll initialization takes care of its visibleDate after
        // calculating the optimum scroll range in TimelineScroll#initScroll
        if (!(me.infiniteScroll && me.isConfiguring)) {
            if (me.isPainted) {
                me.scrollToDate(options.date, options);
            }
            else {
                // Remove any previous listener
                me.visibleDatePaintListener?.();
                me.visibleDatePaintListener = me.ion({
                    paint : () => me.scrollToDate(options.date, options),
                    once  : true
                });
            }
        }
    }
```
