### ISSUE TITLE
Task Segment name change doesn't call project sync api

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8079]
- [ ] Change type of `segments` field from `array` to `store`

[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=27345&p=136597#p136597)

On gantt chart, I changed task segment, it changed on front end but it didn't call sync function to update on back end.
What should I do?
Thank you,
Cuong Ngo

**Comment by cngoEnsite** [comment]
Any update about this bug?
