### ISSUE TITLE
Upgrade Pdf Export Server to Node 21

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8082]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=27349&p=136596#p136596)

Hi, 
I tried to npm i pdf export server but it does not run. 
Here is the error log.
Thank you,
Cuong Ngo
https://drive.google.com/file/d/1M4XN-7ofKZm1QhtMY93dQQIqcceAJTzT/view?usp=sharing

**Comment by SergeyMaltsev** [comment]
This error from log
```
3437 error Traceback (most recent call last):
3437 error   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
3437 error     import gyp  # noqa: E402
3437 error     ^^^^^^^^^^
3437 error   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
3437 error     import gyp.input
3437 error   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
3437 error     from distutils.version import StrictVersion
3437 error ModuleNotFoundError: No module named 'distutils'
```

Node 21 (which is not a sable version) may have no precompiled gyp binaries, so it requires some python build tools installed on client's machine.
It is not related to PDF export server.
