### ISSUE TITLE
Hide `scrollable` config from Menu docs

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8084]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27358&p=136657#p136657)

This is not a bug. Menu's are not scrollable. Need to hide the scrollable option in the docs for menu's.

**Comment by isglass** [comment]
Menus are not intended to be scrollable, make it a Popup instead by supplying `type : 'popup'`

```
  menu : {
                type       : 'popup',
                header     : 'Filter',
```
