### ISSUE TITLE
Row cls doesn't get added on first render in colum renderer

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8094]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=136718#p136718)

Reproducible in [basic Gantt demo](https://bryntum.com/products/gantt/examples/basic/)

Add this renderer to the name column
```javascript
            renderer({ row, record }) {
                row.cls.myClass = true;
                return record.name;
            }
```

And add some styles for this cls
```CSS
		[data-ref="locked"] .myClass {
			background: green;
		}
```

And here is a video on how to reproduce it

https://github.com/bryntum/support/assets/75997756/d0a2bf3b-f39a-476e-beb3-d5d7c88c2b77

### Note

From @ghulamghousdev :
Same issue also exists for the `taskRenderer` as well. It did worked fine with our basic vanilla example for taskRenderer but when I tested with user's demo, it didn't worked, only applied on the parent tasks.

**Comment by isglass** [comment]
`row.cls` is not reactive, use `row.assignCls()` instead
