### ISSUE TITLE
Record with id: 0 cannot be selected in grid

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#81]
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=51&t=12890

To reproduce on grid basic demo add new record with id: 0 and try to select or edit.

**Comment by pmiklashevich** [comment]
Not reproducible:
http://lh/bryntum-suite/grid/examples/basic/
`grid.store.add({ id : 0, name : 'foo' })`
It's possible to select and rename it

**Comment by matsbryntse** [comment]
Not reproducible with latest
