### ISSUE TITLE
State doesn't store to localeStorage on shiftNext/shiftPrevious

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8102]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27367&p=136860#p136860)

Reproducible here https://bryntum.com/products/scheduler/examples/state/
```
 {
            ref: 'previousButton',
            icon: 'b-fa b-fa-angle-left',
            tooltip: intl.formatMessage({ id: 'Button_MoveLeft' }),
            onAction: () => {
              scheduler.shiftPrevious();
            },
          },
          {
            ref: 'nextButton',
            icon: 'b-fa b-fa-angle-right',
            tooltip: intl.formatMessage({ id: 'Button_MoveRight' }),
            onAction: () => {
              scheduler.shiftNext();
            },
          },
```

Video

https://github.com/bryntum/support/assets/75997756/2a7fed16-d494-4259-b33c-49424dbbc74c

**Comment by ExtAnimal** [comment]
What is the expectation here? There *is* no state associated with changing the date of an active view. So if anything this is a Feature Request for... for... Need a little help here!
