### ISSUE TITLE
Disabled checkboxes can be selected with keyboard shortcut

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8116]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=27396&p=136932#p136932)

Hello Bryntum teams!

While accessibility testing our product, we noticed we are allowed to select a disabled checkbox with the keyboard, i.e. highlighting it and pressing space bar.

https://github.com/bryntum/support/assets/52177956/b5358da8-a602-48e8-81ac-aa7ec3e3a0d4

**Comment by ExtAnimal** [comment]
There is explicit key handling in CheckColumn which should not be there. The Checkbox `<input>` element is focused and will handle its own keystrokes.

The question is should the SPACE continue to go on and trigger the cell context menu which is the default action for SPACE when on a cell and the cell context menu is enabled.
