### ISSUE TITLE
WidgetColumn leaks widgets and recreates new ones on column hide/show

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8123]
Should not need a full redraw.
Noticeable with many columns and many rows.

**Comment by ExtAnimal** [comment]
WidgetColumn caches the created widgets on the cell DOM element.

It should cache them internally. The widgets are *not* destroyed when the column is hidden, they are just lost and leaked.

When the column is added, the rendering creates new cells. They contain no widgets and new widgets are created for each cell.

This is a memory and performance drain.

Will implement a global cache of widgets by `type` which all widget columns share to pool widgets.
