### ISSUE TITLE
applyLocale does not apply the same locale twice

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8124]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27300&p=136917#p136917)

Date format doesn't change of the viewpreset when adding custom format to the current locale

Reproducible here https://bryntum.com/products/scheduler/examples/localization/

Steps to reproduce it
1. First set `LocaleManager` to window `window.LocaleManager = LocaleManager`
2. Select the locale english from the locale combo
3. Apply this code snippet to change the dateformat of viewpreset
```javascript
LocaleManager.applyLocale({ localeName : 'En',
  
PresetManager : {
    hourAndDay : {
        // Date format used by tooltips etc.
        topDateFormat : 'DD/MM'
    }
} });
```
4. The format doesn't apply
5. Now if you try to change some other locale of English
```javascript
LocaleManager.applyLocale({ localeName : 'En',     DatePicker : {
        gotoPrevYear  : 'Go to previous year ⬅️',
        gotoPrevMonth : 'Go to previous month ⬅️',
        gotoNextMonth : 'Go to next month ➡️',
        gotoNextYear  : 'Go to next year ➡️'
    } });
```
6. You'll see in the event editor date picker it's changed.

Video

https://github.com/bryntum/support/assets/75997756/9e2d6aa0-f0f7-497c-a25a-b8c7101d2cca

**Comment by isglass** [comment]
Issue is that applyLocale does not apply the same locale twice, it bails out. Either need a force flag, or it should apply it again when passed a config (not only a name). Since that likely means it is a change of a translation

**Comment by taauntik** [comment]
It's actually not a bug. It's documented in docs that setting the config property to `true` will reapply the locale
![image](https://github.com/bryntum/support/assets/75997756/82875cca-f39e-4868-a3b7-96ada0362039)
