### ISSUE TITLE
Updating "only this event" of first Monthly-every-first-Monday event causes infinite loop

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#8131]
In the `Scheduler/recurrence` example's `data.json`, change event id `2`'s rule to be

```
        "recurrenceRule" : "FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1"
```

Then drag "Monthly task" forward by a few days and click the "ONLY THIS EVENT" button.

Then click the debugger's "pause" button because the browser is in an infinite loop.

**Comment by arcady-zherdev** [comment]
Closing this since it duplicates https://github.com/bryntum/support/issues/9039. Which is fixed in v5.6.11.
