### ISSUE TITLE
Group icon stopped handling click when resourceCollapse column added

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8143]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27443&p=137263#p137263)

Can you please add below code in grouping demo - https://bryntum.com/products/scheduler/examples/grouping/ and try to expand/collapse by clicking on the grouping icon
```
{
            type  : 'resourceCollapse',
            width : 50
        },

```

https://github.com/bryntum/support/assets/7203098/0f8978fd-9e0f-4729-8e6c-a73683cf6e38

**Comment by ExtAnimal** [comment]
It just needs to not process the click if `record.isSpecialRow` - which means it's a group row, and outside of the dataset.

<img width="1000" alt="Screenshot 2023-12-29 at 13 49 16" src="https://github.com/bryntum/support/assets/200516/0784b3ca-a568-4078-adce-ad5be1466624">
