### ISSUE TITLE
`toggleSidebar` item has not consistent naming 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8145]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=137272#p137272)

see docs:
https://bryntum.com/products/calendar/docs/api/Calendar/view/Calendar#config-tbar

we have `toggleSidebar` name, but in the code we use `toggleSideBar`. SOo, docs or code should be fixed.

**Comment by ExtAnimal** [comment]
"Sidebar" is a noun and a class name, so the item name is incorrect and should be changed.

The docs use the correct name.

We can change the name in the configuration, but add

```
    changeTbar(tbar) {
        if (tbar.toggleSideBar) {
            tbar.toggleSidebar = tbar.toggleSideBar;
            delete tbar.toggleSideBar;
        }
        return super.changeTbar(...arguments);
    }
```
