### ISSUE TITLE
State is not saving in grouped column headers when reordering child to another group

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8148]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=27453&p=137297#p137297)

Hi There 

Happy new year!

We have implemented a custom memory StateProvider that backs onto our API. It's generally working really well, with the exception of Grouped Headers (https://www.bryntum.com/products/grid/examples/groupedheaders/).

When a user drags and drops a column from one group to another the state is not preserved using our StateProvider setup. When we restore the state the column will revert to its 'default' parent. I'm guessing this is due to the data not being held within the GridStateClass column array entries?  How can we get this data into the state, persist the change of parent column and restore it?

We're using vue & typescript, but a native JS example would be great.

Thanks in advance,

Oliver

------------------------

Video of reproduction

https://github.com/bryntum/support/assets/75997756/1d16bc49-553a-4f8e-b258-14612f8100ad

**Comment by olsgreen** [comment]
Thanks for opening this, if there's any further info required from myself just let me know.

**Comment by olsgreen** [comment]
Any chance this can get into [5.6.7](https://github.com/bryntum/support/milestone/228)? My heart jumped briefly this morning when I read the 5.6.6 release notes and I thought that #8103 was this. 😂🙏🏽

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=142316#p142316) for this update
