### ISSUE TITLE
MsProject file import demo broken

### ISSUE THREAD

**Issue by kronaemmanuel** [bryntum/support#8173]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=27430&start=10)

Steps to repro:
1. Run `aspnetcore` Gantt backend example. Use `docker-compose up bryntum_gantt_mysql` to start the db and `dotnet run` inside `BryntumGanttDemo` folder to start the backend
2. Open msprojectimport demo: `http://lh/bryntum-suite/gantt/examples/msprojectimport/` and run it's php server + update the `projectLoaderScript` url to match the php server. Also, make sure to make the request `no-cors` so we don't get cors errors.
3. Update URLs for load and sync so it gets data from the aspnetcore backend. Load backend data from the aspnetcore backend calling `gantt.project.load()`. This also needs changes to `Startup.cs` to allow cors requests from the frontend.
3. Upload mpp file (sampledata.mpp)
5. Run `gantt.project.sync()`
6. Error in console: `Invalid JSON error`
7. To get the actual error, go to `Gantt\examples\frameworks\aspnetcore\BryntumGanttDemo\Controllers\GanttCrudController.cs` and remove the sync request try-catch block, so it forwards the exception to the frontend also:
```
                // decode request object
                try
                {
                    syncRequest = JsonConvert.DeserializeObject<GanttSyncRequest>(json, new Newtonsoft.Json.Converters.IsoDateTimeConverter{ DateTimeFormat = dateFormat });
                }
                catch (Exception e)
                {
                    throw new Exception("Invalid sync JSON");
                }
```
8: You'll get this error: `Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.ICollection...`

**Comment by sefadogan** [comment]
Hi @kronaemmanuel,

Any chance to get an estimate of when this bug will be completed to inform the customer? They constantly ask :/

Thanks
