### ISSUE TITLE
Using react components in header renderer

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8178]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=27471&p=137477#p137477)

"When integrating the Bryntum grid into an existing codebase, I want to be able to use my existing components when rendering the grid columns & headers. For example, say you have a simple component such as 
```
const ColumnHeader = ({ name }) => <div>{name}</div>
```

It would make sense to me that we could use this component as the headerRenderer within Bryntum. 

```
columns: [{
        type: "name",
        field: "name",
        headerRenderer: (data) => {
          return <ColumnHeader name={data.column.text} />
        },]
      }
```
However, it seems like this may not be possible. Is it true that headerRenderer can only return a string? If so, that would mean you cannot use any pre-existing components when rendering columns. Please correct me or point me to the documentation stating otherwise.
"

Using the basic React demo and adding the following code, it displays `[Object object]` in the header renderer

```
const App = () => {
    // edit button click handler
    const handleEditClick = ({ record, grid : gantt }) => {
        gantt.editTask(record);
    };
    const ColumnHeader = ({ name }) => <div>{name}</div>
    
    const updateConfig = {
        ...ganttConfig,
        columns: [
            ...ganttConfig.columns,
            {
                type: 'name', field: "name",
                headerRenderer: (data) => {
                    return <ColumnHeader name={data.column.text} />
                }
            }
        ] 
    }

    return (
        <Fragment>
            {/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
            <BryntumDemoHeader />
            <BryntumGantt
                {...updateConfig}
                extraData={{ handleEditClick }}
            />
        </Fragment>
    );
};

export default App;
```

<img width="1322" alt="Screenshot 2024-01-03 at 19 36 17" src="https://github.com/bryntum/support/assets/16693227/50f2f6b4-fa82-47aa-a2c4-6de0c3e0819d">

**Comment by marciogurka** [comment]
Related to https://github.com/bryntum/support/issues/774

**Comment by matsbryntse** [comment]
You can try using `headerWidgets` config on Column. It's private currently but will be public in 6.0!

**Comment by jamesonhill** [comment]
@matsbryntse When you say "it's private", does that mean only available on the paid version but not on free trial?
