### ISSUE TITLE
Task duration is calculated according to wrong calendar

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#820]
Caught by test TaskEdit.t, subtest `End date result should match what is selected in the picker when business 8/5 calendar is used`.
Project definition:
```
project : {
                calendar      : 'business',
                calendarsData : [{
                    id           : 'business',
                    name         : 'Business',
                    hoursPerDay  : 8,
                    daysPerWeek  : 5,
                    daysPerMonth : 20,
                    intervals    : [
                        {
                            recurrentStartDate : 'on Sat at 0:00',
                            recurrentEndDate   : 'on Mon at 0:00',
                            isWorking          : false
                        },
                        {
                            recurrentStartDate : 'every weekday at 12:00',
                            recurrentEndDate   : 'every weekday at 13:00',
                            isWorking          : false
                        },
                        {
                            recurrentStartDate : 'every weekday at 17:00',
                            recurrentEndDate   : 'every weekday at 08:00',
                            isWorking          : false
                        }
                    ]
                }]
            }
```

task definition:
```
{ id : 11, startDate : '2017-01-15', duration : 10 }
```
Problem:
```
duration = gantt.taskStore.getById(11).getDuration('hour');
```
This logs 240, 10 days for 24 hour calendar. It should be 80 - 10 days for 8 hours calendar.

**Comment by bmblb** [comment]
Reproducible also on advanced example. Change project calendar to `business` in data and see how tasks get incorrect duration

**Comment by SamuraiJack** [comment]
Not a bug - the duration convertion configs are now on the project - calendar does not have those (`hoursPerDay` etc). Need to move the configs to the project.

**Comment by bmblb** [comment]
- HoursPerDay is an attribute of calendar. Project doesn't really know how much hours per day is there, it knows only calendar and can ask for its availability.
- Calculating tasks duration in days only makes sense in context of project calendar. What point is there to have project with hoursPerDay value different from one implemented on project calendar?
- This change would force us to change the crud API to receive `hoursPerDay` and other configs from the backend. It would force clients to do the same. Or just read `hoursPerDay` from calendar instance, which then would again raise question: why have this on project level instead of calendar level?
- "this would make tasks durations incomparable". This is a well studied case. For years we have been aswering questions "why my task is 3 times wider than it should be?". We told that duration is calculated by `hoursPerDay` set on project calendar. And in that context all tasks are perfecly comparable.

I don't see any benefit from this change. Only thing it does - it decouples hoursPerDay from calendar and forces user to keep track of it himself. And I predict that in majority of cases he will just sync that value with project calendar.

**Comment by arcady-zherdev** [comment]
Yes we'll have to change backend demos accordingly since the database structure is going to change.

**Comment by arcady-zherdev** [comment]
The fields are moved to the project level because they initially should've been defined on the project level.
Having the fields on calendars causes questions from users. They try to use the fields and don't see expected results (one of popular questions on the gantt forum)

**Comment by bmblb** [comment]
> The fields are moved to the project level because they initially should've been defined on the project level.

Why?

Let me emphasize on this: you are suggesting that we change our backend. But along with that **all current users will have to change backend** too. There is no way even major release could enforce this.
Especially given that there is a workaround on a client side: 
```
project.hoursPerDay = calendar.hoursPerDay
```

> Having the fields on calendars causes questions from users.

This workaround will start a lot of questions of sort *why cannot it be done on a framework level*. It can. And thus it should.

**Comment by arcady-zherdev** [comment]
Added a workaround in the scheduler pro crud manager to support old fields location.
