### ISSUE TITLE
Date Picker should support selecting multiple dates with click

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8211]
Two new modes offered for single clicking. Should be on by default for devices without pointer (mobile et al)

1. Click to select start, then end (airbnb / google flights etc)
2. Click to pick individual dates, not creating a range

[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27525&p=137798#p137798)

I have a date picker in Angular to select multiple dates (ie. a start and end date). It seems to only work if I hold shift and select the dates. Do you know if there is a work around this?

**Comment by ExtAnimal** [comment]
This was implemented months ago.

**Comment by ExtAnimal** [comment]
So alternate clicks select start and end? Click once that's the start, click somewhere else and that's the end?

And then click on yet another cell, and the existing range clears, and you just selected s start?

Is this how it should be? It seems more difficult to understand than using click to shit+click to mean start and end.

**Comment by ExtAnimal** [comment]
The Airbnb one is bizarre. Once I select the start date of the 10th that's it! I can't unset it! I'm starting my holiday on the 10th! I have to refresh the page to change my mind! Let's not follow.

**Comment by TheOuen** [comment]
I attempted using an incrementing button to no success. Is there a workaround for the shift + select on mobile devices?
