### ISSUE TITLE
Using bryntum-gantt name as a tag name for Angular component is not possible

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#822]
https://www.bryntum.com/forum/viewtopic.php?f=52&t=13918&p=72547#p72543

[GanttTag](https://www.bryntum.com/docs/gantt/#Gantt/customElements/GanttTag) class uses "bryntum-gantt" as a custom tag name, so when Angular component has name collision, the application fails.

To reproduce replace "gantt-panel" with "bryntum-gantt" in Gantt/examples/angular/advanced demo:
Gantt/examples/angular/advanced/src/app/app.component.html
```
<bryntum-gantt></bryntum-gantt>
```
Gantt/examples/angular/advanced/src/app/gantt/panel.component.ts
```
@Component({
    selector : 'bryntum-gantt',
```
Gantt/examples/angular/advanced/src/styles.scss
```
bryntum-gantt {
    flex: 1;
}
```

Open http://localhost:4200/ and see the errors:
```
localhost/:1 Refused to apply style from 'http://localhost:4200/build/gantt.stockholm.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
and 
```
zone.js:199 Uncaught TypeError: Cannot read property 'querySelector' of null
    at TimeRanges.getElementsByRecord (gantt.umd.js:169577)
    at TimeRanges.onStoreChanged (gantt.umd.js:169631)
    at TimeRanges.updateCurrentTimeLine (gantt.umd.js:180397)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
    at ZoneTask.invoke (zone.js:487)
    at timer (zone.js:2281)
```
<img width="2048" alt="Снимок экрана 2020-05-22 в 14 16 28" src="https://user-images.githubusercontent.com/57486733/82663257-fa9dc780-9c37-11ea-857b-182f5f1e05cb.png">

**Comment by pmiklashevich** [comment]
We can add to the docs that the name is reserved. Or can change it to something more specific to what the GanttTag was designed for. Or add `b-` prefix to show this is something our and private. We can decide on it in scope of the ticket. This or that. To my mind locking 'bryntum-gantt' name is too bad, because the name is a good name to be used for a client solution. Whatever we choose, the name should be documented as reserved.

**Comment by isglass** [comment]
GanttTag (webcomponent) was moved to a separate bundle in 5.0 or 5.1
