### ISSUE TITLE
Editing the baseline `startDate` of newly added task results in crash

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8236]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=27406&p=137959#p137959)

Thanks for that, it seems to work - im facing one more problem, when adding a new task with a baseline and trying to edit the date it breaks the component. you can check it out also in your example:
https://bryntum.com/products/gantt/examples/baselines/
try to add a task and then change a baseline date manually

https://github.com/bryntum/support/assets/52177956/fac38aa9-454c-4515-9519-20c1660a2e23

**Comment by matsbryntse** [comment]
Also check https://app.therootcause.io/#bryntum/bryntum-gantt/errors/55cf90af162fc5c7b50b611b2a915a7bdaf488f7

**Comment by canonic-epicure** [comment]
Yes, same issue
