### ISSUE TITLE
EventDragSelect ignores selection after close-to-edge-scroll

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#8240]
1. Use https://bryntum.com/products/schedulerpro/examples-scheduler/dragselection/
2. Resize window so there is vertical scroll
3. DragSelect from one point downwards so to initiate auto scroll
4. After dragselect, no events is selected (the bug)

[Forum post](https://forum.bryntum.com/viewtopic.php?t=26873&start=10)

**Comment by ExtAnimal** [comment]
On mouseup, `EventDragSelect` navigates to the last event in the newly selected block.

Selection happens upon navigation. So that event ends up as the sole selected event.
