### ISSUE TITLE
Broken HTML in React events section

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8254]
Empty <> tag 

https://bryntum.com/products/grid/docs/guide/Grid/integration/react/events

<img width="889" alt="Screenshot 2024-01-14 at 14 47 55" src="https://github.com/bryntum/support/assets/218570/b6ce783e-5c2f-4b74-93a1-18e2eb9c4a4a">

**Comment by SergeyMaltsev** [comment]
It is supported shorthand for  `<Fragment>`
https://legacy.reactjs.org/docs/fragments.html
