### ISSUE TITLE
EventBuffer renderer config not appear in the docs

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8267]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27596&p=138204#p138204)

"Hi!

I'd like to edit how the preamble is displayed when using the EventBuffer feature.

I saw in this demo (https://bryntum.com/products/schedulerpro/examples/travel-time/) that there is a "renderer" method that seems to be doing what I want, but I can't seem to find anything about it in the documentation nor in the type definitions.

What would be the correct way to use this with the React based version of the control?
"

The renderer is used in the demo, but is not available in the documentation of the feature.

-------------------------------------
Need to add docs and type definitions (for typescript) for it

**Comment by ExtAnimal** [comment]
Fix this bug at the time time: https://github.com/bryntum/support/issues/8344
