### ISSUE TITLE
eventDragSelect not working

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8276]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27606&p=138266#p138266)

Hi,

when is start the eventDragSelect then everything works fine, but after i release the mouse it is unselected.

Please try it with your demo here:

**[Scheduler.feature.EventDragSelect](https://bryntum.com/products/scheduler/docs/api/Scheduler/feature/EventDragSelect)**

**Comment by JockeLindberg** [comment]
This is fixed in https://github.com/bryntum/support/issues/8240
