### ISSUE TITLE
Scheduler Pro header date is not sticky

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#8283]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=138304#p138304)

<img width="222" alt="Screenshot 2024-01-17 at 07 00 43" src="https://github.com/bryntum/support/assets/200516/1a0c75a9-0cc7-4f51-841a-ff19e25e08f5">

**Comment by ghulamghousdev** [comment]
Another report here: https://forum.bryntum.com/viewtopic.php?p=152274#p152274
