### ISSUE TITLE
Event content overflow not hidden in Firefox

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8288]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=138327#p138327)

Hello, 

When using Mozilla FireFox, the hover event label is not truncated.

<img width="816" alt="Screenshot 2024-01-17 at 3 07 12 PM" src="https://github.com/bryntum/support/assets/52177956/ae206088-5e13-4247-b429-0b130e9024ca">

**Comment by isglass** [comment]
FF flexbox quirk, set `min-width: 0` on `.b-sch-event-content` to fix
