### ISSUE TITLE
`Filter` feature is not working for nested columns

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8298]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=27650&p=138478#p138478)

Hi,
I think there is a bug with nested columns and Bryntum filter.

https://bryntum.com/products/grid/examples/filtering/

If make (f.e. Age) column as nested the filter does not work

```
columns : [
  {
    children: [
      {
          text : 'Age',
          field : 'age',
          width : 100,
          type : 'number'
      },
   ]
}
```

Is it a real issue or i do something wrong?

Thanks.
![Screenshot 2024-01-18 at 16.43.45.png](https://forum.bryntum.com/download/file.php?id=26300)

**Comment by yazhylinski** [comment]
@chuckn0rris Thanks.
What approximate time you going to fix it?

Thank you.

**Comment by chuckn0rris** [comment]
We marked it high-prio so it should be fixed asap. Can't give you terms, it's a bug and not clear if it takes 1 day or 1 week of work. Hopefully, we will fix it with next patch release (we release every 1-2 weeks). We already asked our developer to start with it. You can subscribe on ticket updates to be notified when status changed.

**Comment by yazhylinski** [comment]
@chuckn0rris it works. Thank you
