### ISSUE TITLE
Drag selection element position wrong if page is scrolled

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#83]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=12893

http://lh/bryntum-suite/scheduler/examples/dragselection/
Make sure body is scrolled, then drag select

**Comment by dongryphon** [comment]
I am not seeing this on `release`:

![83-drag-selection](https://user-images.githubusercontent.com/722969/74595145-c8127c00-5003-11ea-8ef0-2cea402fc20f.gif)

**Comment by matsbryntse** [comment]
Remove on BODY
`overflow: hidden;`

Add to #container 
`margin: 20em;`
