### ISSUE TITLE
Task Drag and Task Resize should only update value in STM once the drag/resize is complete

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8307]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=26956&start=10)

Steps:
1. Visit this https://bryntum.com/products/gantt/examples/undoredo/
2. Drag a task and drop.
3. STM shows lots of steps taken for task resize
4. Now change the end date by resizing a task to the right
5. STM shows lots of steps taken for task resize.

**Comment by matsbryntse** [comment]
Related https://github.com/bryntum/support/issues/8302
