### ISSUE TITLE
Duration column decimal separator is not localized

### ISSUE THREAD

**Issue by isglass** [bryntum/support#8309]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=27670&e=1&view=unread#unread)

DurationColumn & EffortColumn does not respect current locales decimal separator, they always use `.`

**Comment by ExtAnimal** [comment]
It works in the localization example in 5.5.6, so something must have gone awry in 6.0

<img width="1136" alt="Screenshot 2024-01-19 at 19 17 02" src="https://github.com/bryntum/support/assets/200516/2367a750-d14d-4c79-b70d-6f061d0b76b6">
