### ISSUE TITLE
AjaxStore JSON encode/decode intervention

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#8314]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=27638)

We need to add a hook to allow apps to encode and decode JSON/

**Comment by chuckn0rris** [comment]
Make sure this cover functionality of 
Reader:

https://docs.sencha.com/extjs/7.7.0/modern/Ext.data.reader.Json.html#method-getResponseData
https://docs.sencha.com/extjs/7.7.0/modern/Ext.data.reader.Json.html#cfg-transform

Writer:

https://docs.sencha.com/extjs/7.7.0/modern/Ext.data.writer.Json.html#method-writeRecords
https://docs.sencha.com/extjs/7.7.0/modern/Ext.data.writer.Json.html#cfg-transform
