### ISSUE TITLE
Attempting to scroll the entire task element of a very long task into view is a bad UX.

### ISSUE THREAD

**Issue by robinhuy** [bryntum/support#8315]
I have adjusted the _viewPreset_ configuration in [this online example](https://bryntum.com/products/scheduler/examples/timeresolution/) to reproduce the bug (in a real project, there might be various other presets):

```
    presets: [
        {
            base: 'dayAndWeek',
            id: 'WeeklyView',
            tickWidth: 50,
            headers: [
                {
                    unit: 'day',
                    dateFormat: 'ddd MM/DD',
                },
                {
                    unit: 'hour',
                    dateFormat: 'hA',
                },
            ],
            timeResolution: { 
                unit: 'minute',
                increment: 15,
            },
        },
    ],

    viewPreset: 'WeeklyView',
```

Create an Event with:
- StartDate within the range of View's StartDate and EndDate, however, it is not immediately visible within the View and requires scrolling to become visible.
- EndDate outside the range of View's StartDate and EndDate (Event's EndDate is greater than View's EndDate).

After that, right-click on the Event and select _Edit Event_.

**Expected**: The scrollbar automatically scrolls and snaps to the beginning of the Event (Event's StartDate), then opens the Edit Event modal.
**Bug**: The scrollbar automatically scrolls to the beginning of the View (View's StartDate) instead of the beginning of the Event, and the Edit Event modal is not visible.

**Comment by ExtAnimal** [comment]
It's not scrolling to the project start. It is doing what it has done for a long time, scrolling what is now an extremely long element into view. It's a 1300 pixel wide element:

<img width="1597" alt="Screenshot 2024-01-22 at 12 49 19" src="https://github.com/bryntum/support/assets/200516/93548b60-3a59-4af4-863e-a7980a6933c4">

It scrolls as much as possible into view. I propose to make it only want to scroll at least 100 pixels of width into view, and the bar height.

Calendar does the same (height and width flipped in this case). You can see below that it scrolls the width fully in, but it just needs to see the top 100 pixels of the element:

https://github.com/bryntum/support/assets/200516/83be9630-6e45-4e7e-95fd-f1d1aa0a0bb3

**Comment by ExtAnimal** [comment]
So it works like this now:

https://github.com/bryntum/support/assets/200516/a7b0095d-a618-4146-b3a7-cacad07388de

I'll make `minEditSize` configurable, defaulting to 100

I'm using "size", because the same issue is flipped in Scheduler vertical mode:
