### ISSUE TITLE
Set `useRawData`to true as default in 6.0

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8335]

**Comment by ubaidkhan7** [comment]
@matsbryntse 

`useRawData` default to true causing a bug. The bug is if I have a `defaultValue` set for fields in my model class and then I try to create a record with data, the default values in model class replaces my provided data with the defaults.


```js
import { Model, Store, ProjectModel } from '../../build/schedulerpro.module.js?478335';
import shared from '../_shared/shared.module.js?478335';

class MyModel extends Model {
  static get fields() {
    return [
      { name: "myName", dataSource: "name", defaultValue: "novalue" },
      { name: "isDefaultView", dataSource: "is_default_view", type: "boolean", defaultValue: false },
    ]
  }
}

const testStore = new Store({
  storeId: "testStore",
  modelClass: MyModel,
  useRawData: false
});

const testProject = new ProjectModel({
  crudStores: [
    testStore
  ],
  loadUrl: "https://www.test.com",
})
console.log(testProject)
testProject.useRawData = false;

const viewToAdd = testStore.createRecord({
    myName: "test",
    isDefaultView: true,
});
console.log(viewToAdd.myName, viewToAdd.isDefaultView); // logs: novalue, false

```

As you can see from the output my provided values are ignored but If I sets the `useRawData` in store to false it works fine.

**Comment by isglass** [comment]
Hi @ubaidkhan7,

I am not able to reproduce your issue. Slightly adopted your test case to load data from a local json file:

```
class MyModel extends Model {
    static fields = [
        { name : 'myName', dataSource : 'name', defaultValue : 'novalue' },
        { name : 'isDefaultView', dataSource : 'is_default_view', type : 'boolean', defaultValue : false }
    ];
}

const testStore = new Store({
    id  : 'testStore', // storeId was removed in 6.0
    modelClass : MyModel,
    useRawData : true
});

const testProject = new ProjectModel({
    crudStores : [
        testStore
    ],
    loadUrl : 'data/data.json'
});

await testProject.load();

console.log(testStore.first.myName, testStore.first.isDefaultView);
```

The data looks like this:

```
{
  "success"   : true,
  "testStore" : {
    "rows" : [
      {
        "id" : 1
      }
    ]
  }
}

```

Console outputs:

<img width="221" alt="Screenshot 2024-07-30 at 20 05 41" src="https://github.com/user-attachments/assets/71398b97-cfc5-47fb-8dff-eead12d33de5">

Please adjust the code in a way that reproduces your issue, and we will look into it

**Comment by ubaidkhan7** [comment]
@isglass 

Lets reproduce the issue from your example. In the given code below I've added two new statements after the `await testProject.load();` and an `AjaxStore.mockUrl` to mock the get data request.

```js
import { ProjectModel, Model, Store, SchedulerPro, Timeline, StringHelper, AjaxHelper } from '../../build/schedulerpro.module.js?478335';

AjaxHelper.mockUrl('load', () => {
    console.log("Mock Function Called...")
    return {
        responseText : JSON.stringify({
            success   : true,
            events: { rows: [] },
            testStore : { rows : [{ id: 1, name: "xyz", is_default_view: false }] }
        })
    }
});


class MyModel extends Model {
    static fields = [
        { name : 'myName', dataSource : 'name', defaultValue : 'novalue' },
        { name : 'isDefaultView', dataSource : 'is_default_view', type : 'boolean', defaultValue : false }
    ];
}

const testStore = new Store({
    id  : 'testStore', // storeId was removed in 6.0
    modelClass : MyModel,
    useRawData : true
});

const testProject = new ProjectModel({
    crudStores : [
        testStore
    ],
    loadUrl : 'load'
});

await testProject.load();

const viewToAdd = testStore.createRecord({
    myName: "test",
    isDefaultView: true,
});
console.log(viewToAdd.myName, viewToAdd.isDefaultView, "Phantom Record"); // logs: novalue, false
```

Console outputs:
![image](https://github.com/user-attachments/assets/97a9ee3e-06f3-4d0d-a20c-8aad644a3bd1)


One thing I noticed If you remove the `defaultValue` property from the modal class then `viewToAdd` logs correct data.

**Comment by isglass** [comment]
@ubaidkhan7 

`createRecord´ accepts a raw data object, eg. using your `dataSource` names. It should be:

```
const viewToAdd = testStore.createRecord({
    name: "test",
    is_default_view: true,
});
```

**Comment by ubaidkhan7** [comment]
@isglass 

I believe the `createRecord` api has been changed, since we are using the property alias instead of `dataSource` names in our project for almost two years.

If I set `useRawData` to `false` then the code works well.

Additionally if I skip `defaultValue` property in my data `Model` while `useRawData` being truthy, then my recent code provided above works well.

**Comment by ubaidkhan7** [comment]
I cannot do that big change in my project where I need to replace aliases with `dataSource` names as there are so many places to make this change. For now I am disabling `useRawData` in all of the stores.

**Comment by isglass** [comment]
@ubaidkhan7 I went back to 5.6.13 and the behavior is the same there for me. But I can confirm that `useRawData` does affect the outcome in both versions. Will look into that, meanwhile it sounds like it is working for you now with `useRawData : false`?

**Comment by ubaidkhan7** [comment]
@isglass 
we moved our upgrade from bryntum's version 5.5.4 to 6.0.3 and it was not happening in that version.
Yes for now `useRawData: false` works fine.

**Comment by isglass** [comment]
Opened a follow up ticket on the default value issue https://github.com/bryntum/support/issues/9712
