### ISSUE TITLE
TaskEditor configuration is not listed in breaking changes

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#834]
Bab names were changed to camelcase: `generaltab` -> `generalTab`, etc. This change was not reflected in integration demos and regular examples which use old name, it is not mentioned in the changelog.

Suggestion: revert everything back to lowercase.

**Comment by isglass** [comment]
For other kinds of keys (event names for example) we do case-insensitive comparisons. Risk of breaking should be minimal, since namedItems approach is pretty new and not widely used on release

**Comment by canonic-epicure** [comment]
Closing as outdated.
