### ISSUE TITLE
Project / time lines misplaced in RTL

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8340]
https://bryntum.com/products/gantt/examples/advanced/?rtl

<img width="1100" alt="Screenshot 2024-01-24 at 11 21 21" src="https://github.com/bryntum/support/assets/218570/34e0a5af-93c8-433b-8e56-cb6c24b530b7">

**Comment by matsbryntse** [comment]
Same issue? https://github.com/bryntum/support/issues/8509

**Comment by isglass** [comment]
Fixed by https://github.com/bryntum/bryntum-suite/pull/9161
