### ISSUE TITLE
Missing field configuration in New Gantt for ResourceModel when migrating from ExtJS

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8342]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=9&t=27736&p=138980#p138980)

"Hi Team,

In ExtJS Gantt, we are using rateField, rateUnitField configs but these are not available in new gantt. Can you check and provide how to use these configurations in new Gantt?

ExtJS Gantt APIs: https://bryntum.com/products/gantt-for-extjs/docs/#!/api/Gnt.model.Resource-cfg-rateField

New Gantt APIs: [Gantt.model.ResourceModel](https://bryntum.com/products/gantt/docs/api/Gantt/model/ResourceModel)
"

**Comment by matsbryntse** [comment]
Will be fixed as part of https://github.com/bryntum/support/issues/2904
