### ISSUE TITLE
Export scheduler view with custom component as eventRenderer

### ISSUE THREAD

**Issue by isglass** [bryntum/support#8359]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=27752&p=139106#p139106)

Angular components on events are not shown in the exported PDF.

Probably we have to traverse their shadow DOM and also transmit that to the backend. Or worst case, support alternative export output for eventRenderer

**Comment by aaronbach** [comment]
Some news on this? Do you have an estimated fix-date?

**Comment by matsbryntse** [comment]
No news yet but we will try hard to fix it for the next patch release. Sorry for the wait!
