### ISSUE TITLE
Float root displaced after going to Fullscreen and back

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8382]
- [x] Multiple copies of Fullscreen.js loaded

Make a docs fiddle Fullscreen, exit and hover code icon. https://bryntum.com/products/scheduler/docs/api/Grid/feature/Summary

<img width="1401" alt="Screenshot 2024-01-29 at 13 43 53" src="https://github.com/bryntum/support/assets/218570/c3f2c7ec-baae-454f-93df-0e80e10d04a9">

**Comment by matsbryntse** [comment]
- [ ] Wrong CSS import order

<img width="667" alt="Screenshot 2024-01-29 at 22 48 54" src="https://github.com/bryntum/support/assets/218570/c986d8ba-35e6-4bfd-ba9f-5ca6970f1f73">

**Comment by SergeyMaltsev** [comment]
Re:  Wrong CSS import order

This need to be fixed in
```
resources/templates/docs/index.html
resources/templates/docs-dist/index.html
```

The regenerate index pages for each product using
```
grunt all:docs-templates
```

And commit changes

**Comment by matsbryntse** [comment]
Double CSS imports also causes conflicts:

<img width="489" alt="Screenshot 2024-04-11 at 10 49 36" src="https://github.com/bryntum/support/assets/218570/72516844-23e0-48f4-a1c5-88ec54625a25">

**Comment by SergeyMaltsev** [comment]
Patched Fullcreen to work with 2 imported bundles.
CSS issue and proper imports fix is a part of https://github.com/bryntum/bryntum-suite/issues/9202
