### ISSUE TITLE
Unwanted lag after dependency

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#839]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14169&p=72688#p72688)

Here are the steps to reproduce:

Open the Basic demo
Add a new root task at the top
Edit the task
Change the effort to 40 hours
In the advanced tab, select Effort Driven, then fixed units
Save
Add a new task below this one. This creates a copy.
Now drag a dependency from the start of the first one to the beginning of the second one.

Result:
 The second task is move all the way to the end of the project

Expected:
The second task is moved to the end of the first one.

I understand Fixed Units requires some assignments. But that's still weird

**Comment by arcady-zherdev** [comment]
Need to check ..this might be already fixed in #838
