### ISSUE TITLE
Add option to hide currentTimeLine menu inside headerMenu

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8425]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=27840&p=139625#p139625)

When configuring the timeranges feature - https://bryntum.com/products/scheduler/examples/timeranges/ - an option is added to the header menu, but trying to disable the option inside headerMenu configuration doesn't work.

**Comment by marciogurka** [comment]
Hey @SergeyMaltsev,

Perhaps we should have something like:

```
features : {
        headerMenu : {
            items : {
                currentTimeline: false
            }
        }
    }
```

Or something like

```
features : {
        timeRanges : {
            showHeaderMenuItem: false
        }
    }
```

To have a config for that, the listener works fine, but it would be nice to have a config for that.

**Comment by SergeyMaltsev** [comment]
@marciogurka not sure if we have working API already

**Comment by isglass** [comment]
This should already work:
```
features : {
        timeAxisHeaderMenu : {
            items : {
                currentTimeline: false
            }
        }
    }
```

**Comment by marciogurka** [comment]
Yes, using the following configuration works like expected

```
features : {
        timeAxisHeaderMenu : {
            items : {
                currentTimeLine: false
            }
        }
    }
```
