### ISSUE TITLE
Support styling holidays / non-working time 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#843]
Similar to https://bryntum.com/docs/scheduler/#Scheduler/feature/NonWorkingTime

Base upon a generic TimeRanges superclass https://github.com/bryntum/support/issues/2389

**Comment by dongryphon** [comment]
Not sure the best way to go here. Colors and styles come from a variety of places. In calendar, the resource filter sits in the place where Google calendar puts "Calendars" and the resource is one way to set these values, so my PR starts there.

Is there a "holidays" store of some kind? It may be nice to have styling per holiday if there were a HolidayModel or something.

**Comment by jsakalos** [comment]
Also requested here https://www.bryntum.com/forum/viewtopic.php?p=87344#p87344

**Comment by jonek** [comment]
We requested this feature as it would allow us to highlight office hours that are different each day and potentially consist of multiple intervals per day and resource (think of "closed during lunch break"). See: https://github.com/bryntum/support/issues/2389

**Comment by matsbryntse** [comment]
You can now implement this using TimeRanges: https://bryntum.com/products/calendar/examples/timeranges/
