### ISSUE TITLE
Task bars are missing in the PDF Export

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8433]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=27460&p=139664#p139664)

Steps to repro:
1. Go to https://bryntum.com/products/gantt/examples/export/
2. Click on export to pdf and export with default settings
3. See the task bars are not rendered in pdf

<img width="761" alt="Screenshot 2024-02-02 at 2 55 07 PM" src="https://github.com/bryntum/support/assets/52177956/143b128c-707c-497c-aa74-502ec6d39f72">

[Gantt.pdf](https://github.com/bryntum/support/files/14138387/Gantt.pdf)

**Comment by ghulamghousdev** [comment]
Pretty similar to this https://github.com/bryntum/support/issues/7929 but the only difference here is issue is reproducible with out dependencies as well. Also reproducible in Scheduler as after all we extend the pdf export feature from Scheduler for Gantt.

**Comment by bmblb** [comment]
This problem was solved by this ticket: https://github.com/bryntum/support/issues/8291 Current problem is likely caused by outdated puppeteer. Server apparently has version 1.17, latest server uses version 15. @SergeyMaltsev please upgrade pdf export server used by our online export demos

**Comment by bmblb** [comment]
server updated, problem is fixed
