### ISSUE TITLE
[Bug] Mismatch between rendering of events in calendar view and in datepicker

### ISSUE THREAD

**Issue by JustDoItSascha** [bryntum/support#8434]
Hello!

I have taken on a project which uses Scheduler Pro 5.1.1.

There is a bug which I’m not able to solve. I hope you can help me:

I have an event with a start date and an end date of course. Let’s assume it’s starting on 2024-02-01 and is ending on 2024-02-03. In the event editor I choose “2024-02-03” and “2024-02-03T00:00:00Z” is saved. But the calendar only renders a column until 2024-02-02. When I’m manually changing the enddate to “2024-02-03T12:00:00Z” or every other time, e.g. 00:00:01, then the rendering of the calendar is correct, but the datepicker shows “2024-02-04". There is always a difference of a day between these two.

It feels so weird, because I think we can’t be the only ones who want to render events without a time. I mean only whole days.
But I have no idea how to fix that.

Thanks for any help!

<img width="1079" alt="Bildschirmfoto 2024-02-02 um 11 41 53" src="https://github.com/bryntum/support/assets/8389022/b5e8de3a-ef72-457a-9c66-eaa549157a9b">

**Comment by matsbryntse** [comment]
@JustDoItSascha Better if you post this in our support forums, and our team will take a look. Please provide code / test case that we can have a look at too. https://forum.bryntum.com/
