### ISSUE TITLE
Successor/predecessor fields do not close on `escape`

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#845]
Steps to reproduce on advanced demo (master):
1. start editing predecessor field
2. type Escape key
Other fields close, this one does not.

**Comment by chuckn0rris** [comment]
Checked in `master` and `release`, not reproducable:
![presessor-gantt](https://user-images.githubusercontent.com/7203098/87244477-8aedd100-c45f-11ea-8362-a7b1a4a1e63b.gif)
