### ISSUE TITLE
Tools should have white color in tooltip header 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8458]
https://bryntum.com/products/calendar/examples/frameworks/angular/drag-onto-tasks/dist/drag-onto-tasks/

<img width="619" alt="Screenshot 2024-02-03 at 17 05 33" src="https://github.com/bryntum/support/assets/218570/138963ed-3417-4698-b46a-9e5b5aa33655">

**Comment by ExtAnimal** [comment]
`$panel-tool-color` just needs to be set in that theme

**Comment by ExtAnimal** [comment]
Seems that might have regressed here: https://github.com/bryntum/bryntum-suite/pull/7749
