### ISSUE TITLE
Filter is not shown and not working in hidden parent element

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8471]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=27877&p=139791#p139791)

Steps:
1. Go to https://bryntum.com/products/gantt/examples/fieldfilters/
2. run in console: `$('#container').style.visibility = 'visible'`
3. run in console: `$('body').style.visibility = 'hidden'`
4. Then filter is not showing at all.

https://github.com/bryntum/support/assets/52177956/14b8c7e4-3ae9-4b26-853b-e85322e1346d

**Comment by Jmurawsk** [comment]
@ghulamghousdev do you have any update here ?
