### ISSUE TITLE
Can't apply multiple filters for one column by default

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8482]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=27888&p=139883#p139883)

Hi,
Thanks for fix viewtopic.php?f=43&t=27650&p=138478#p138478

I have another question about filtering.
I try to apply multiple filters for one column by default.
In the example(https://bryntum.com/products/grid/examples/filtering/) try apply following filter:

```
    store: {
        filters: [
           {
              property : 'age',
              operator : '>',
              value : '22'
           },
           {
              property : 'age',
              operator : '<',
              value : '50'
            }
        ]
    },
```
It applies only the latest one.

On clicking on the filter icon it removes the second filter
![chrome_LcLT0if9gt](https://github.com/bryntum/support/assets/75997756/b27d059c-adc0-4a68-bff5-2996e7218ac2)

**Comment by yazhylinski** [comment]
@SergeyMaltsev it's still an issue, i left a comment here https://forum.bryntum.com/viewtopic.php?t=27888

**Comment by ghulamghousdev** [comment]
> @SergeyMaltsev it's still an issue, i left a comment here https://forum.bryntum.com/viewtopic.php?t=27888

I have replied you on the forums. Please check.
