### ISSUE TITLE
Gantt for ExtJS: "Late Start" and "Late Finish" cannot be adjusted automatically

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#849]
[Simple project plan.mpp.zip](https://github.com/bryntum/support/files/4693677/Simple.project.plan.mpp.zip)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=49&t=13861)

According Bryntum gantt doc, the "Late Start" and "Late Finish" should be adjusted automatically when rescheduling a task and its successor.

But looks like "Late Start" and "Late Finish" cannot be adjusted in Bryntum gantt while it can in MS project. The attached sample mpp file can be used to reproduce the issue.

**Comment by matsbryntse** [comment]
Moved to Assembla

**Comment by leslieli** [comment]
> Moved to Assembla

@matsbryntse is this bug fixed and released? Where can be check if the bug is fixed or not? Could you share us the related ticket link in Assembla? Thanks.
