### ISSUE TITLE
Filter menu misaligns on selecting a value from Filter combo

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8490]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=27652&p=139943#p139943)

The reason for this is, the values in the column cells changes resulting the column width and the position of the column on which filter menu is opened also changes. Because of that filter menu does not respond to the position change. 

https://github.com/bryntum/support/assets/52177956/be780760-5383-4344-96f0-f59f6570bcfe

[scheduler.zip](https://github.com/bryntum/support/files/14193192/scheduler.zip)

**Comment by Harish-dev22** [comment]
Hi @SergeyMaltsev @matsbryntse 

Has this problem been addressed and included in the 5.6.7 release? I couldn't find it listed in the 5.6.7 change log.

**Comment by matsbryntse** [comment]
Yep fixed, you can find it in Grid's change log https://bryntum.com/products/grid/changelog/
