### ISSUE TITLE
Recurring time ranges not display in RTL

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8509]
Zoom out in this demo and ranges disappear https://bryntum.com/products/scheduler/examples/recurringtimeranges/?rtl

[Forum post](https://forum.bryntum.com/viewtopic.php?p=140080#p140080)

Hi I am working with scheduler 5.6.1v and angular 15.
I found that the combination of rtl and infinity scroll stop show all recurring time ranges in 5.6.2 version and in all above versions(All above versions checked).

ltr view:
![ltr-view.png](https://forum.bryntum.com/download/file.php?id=26764)

rtl view:
 ![rtl-view.png](https://forum.bryntum.com/download/file.php?id=26765)

I create some demo based on 5.6.2 recurring time range example.

Steps for reproduce:

1) Run the custom demo and see the ltr view.
2) Click on "Change direction" button.
3)If the view will jump to another view(Still happens sometimes) click on "GoToTimeranges" button it will scroll to the time ranges dates.
![exapmple.gif](https://forum.bryntum.com/download/file.php?id=26766)

The demo code:
![ltr-view.png](https://forum.bryntum.com/download/file.php?id=26764)
![rtl-view.png](https://forum.bryntum.com/download/file.php?id=26765)
![exapmple.gif](https://forum.bryntum.com/download/file.php?id=26766)

**Comment by yakeer** [comment]
What's going on with this issue?
It's urgent for us as it is a regression and we cannot go further.

**Comment by yakeer** [comment]
Any news about this one?
It's a regression that prevents us from upgrading further to resolve issues you've already solved.

**Comment by isglass** [comment]
The issue here is that time ranges uses `display : contents` on their parent element, to allow their z-index to be adjusted to be above or below other parts of the schedule. This is fine in LTR, but in RTL it leads to the width of their parent being lost, and it is needed for positioning.

To fix it, we have to position using direction-neutral `inset` instead. But that is a pretty big change, thus retargeting the ticket to 6.0

**Comment by yakeer** [comment]
Hey @matsbryntse ,
Is there any way you add this fix to 5.x branch?
Is quite urgent to us and we cannot wait until 6.x branch is final.

**Comment by matsbryntse** [comment]
Sorry, this is not feasible as the changes are too many.
