### ISSUE TITLE
[VUE 3] Repeated cell content on grid scrolling with Vue renderers

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#8519]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=27913&p=140205#p140205)

The scrolling leads to repeated content in cells:
<img width="1643" alt="Bildschirmfoto 2024-02-09 um 12 16 45" src="https://github.com/bryntum/support/assets/204844/29f7c865-a5aa-4445-be2e-755f77257c96">

The showcase used:

[showcase.zip](https://github.com/bryntum/support/files/14224767/showcase.zip)

It is probably that the content of the vue-cell-renderer container is not cleared on scrolling but the new content is appended to the old markup.

**Comment by awacode21** [comment]
@jsakalos i send that reproduction per mail instead of posting it in the forum, because it contains our node token to our paid product. Can you please remove that npmrc? i don't want our token exposed here!

**Comment by awacode21** [comment]
@jsakalos i sent that reproduction per mail instead of posting it in the forum, because it contains our node token to our paid product. Can you please remove that npmrc? i don't want our token exposed here!

**Comment by ghulamghousdev** [comment]
Another client facing the same issue here https://forum.bryntum.com/viewtopic.php?p=142322#p142322
