### ISSUE TITLE
[ANGULAR] Scheduler does not load if `direction: rtl` and `infiniteScroll: true` is set

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8533]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=27971&p=140341#p140341)

Hi I found in scheduler 5.6.6 that if scheduler parent element has "rtl" direction and the scheduler property "infinityScroll" is on the scheduler fires a error and not loaded.

If the direction is "ltr" no problem.

Html example:

```
<div [style.direction]="direction">
    <button (click)="changeDirection()">Change Direction</button>
    <button (click)="print()">Print</button>
    <bryntum-scheduler #scheduler [barMargin]="schedulerConfig.barMargin" [columns]="schedulerConfig.columns"
        [endDate]="schedulerConfig.endDate" [events]="schedulerConfig.events" [infiniteScroll]="true"
        [mode]="schedulerConfig.mode" [resourceImagePath]="schedulerConfig.resourceImagePath"
        [resources]="schedulerConfig.resources" [resourceTimeRanges]="schedulerConfig.resourceTimeRanges"
        [resourceTimeRangesFeature]="schedulerConfig.features.resourceTimeRanges"
        [rowHeight]="schedulerConfig.rowHeight" [startDate]="schedulerConfig.startDate"
        [viewPreset]="schedulerConfig.viewPreset" [stripeFeature]="stripeFeature"
        [columnLinesFeature]="columnLinesFeature"></bryntum-scheduler>
</div>

```
The direction of parent element is not for the scheduler it for all other child elements and the css.

Error:
![1.png](https://forum.bryntum.com/download/file.php?id=26815)

The problem is only if the direction is "rtl" and "infiniteScroll" is true.
I create some demo that reproduce the problem.

[rtl-broken.zip](https://github.com/bryntum/support/files/14239343/rtl-broken.zip)

**Comment by yakeer** [comment]
Any news about this bug?
It's a breaking change which prevents us to upgrading to newer versions and resolve other closed issues.
