### ISSUE TITLE
`autoRowHeight` performance issue with Vue 3

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8542]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=50&t=27787&p=140297#p140297)

Open app, switch view to Week, go back to Month, try to switch to Week again - app is freezed.  It uses about 5k events, but if you reduce to 1k, it still will freeze for a second.

[quasarBryntumCalendar.zip](https://github.com/bryntum/support/files/14270929/quasarBryntumCalendar.zip)

**Comment by ExtAnimal** [comment]
There is no bug. This is framework code and misunderstanding of the API.

**Comment by chuckn0rris** [comment]
The ticket is about investigation of performance problem. If there is nothing to improve, we can close this.
