### ISSUE TITLE
`EventHandlers` are not searchable in docs

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8557]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=28018&p=140640#p140640)

When try to find an event handler in the documentation search it doesn't show the searched values, like the print below:

![Screenshot_7.png](https://forum.bryntum.com/download/file.php?id=26909)

**Comment by ExtAnimal** [comment]
Dupe of https://github.com/bryntum/support/issues/8555

These two events should be hoisted to the `Container` class with appropriate warnings that they are only fired if the Container uses `card` layout.

**Comment by matsbryntse** [comment]
Not a duplicate
