### ISSUE TITLE
Sync triggered (fromSide and toSide removed) after opening and saving unmodified dependency

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#856]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14211&p=72845)

Open the Basic demo
Adjust the project configuration:
```const project = new ProjectModel({
    autoSync: true,
    transport : {
        load : {
            url : '../_datasets/launch-saas.json'
        },
        sync: { url: 'sync'}
        ...
```
Enable the dependencyEdit feature:
```new Gantt({
    features: {dependencyEdit : true},
    ...

```
Double click any dependency to open the dependency editor
Watch the network monitor
Hit save

Result:

A sync request is made with the following data:
```{
	"type": "sync",
	"requestId": 15907744236732,
	"dependencies": {
		"updated": [{
			"fromSide": null,
			"toSide": null,
			"id": 5
		}]
	}
}
```

Expected:
No request at all since nothing has actually changed

**Comment by isglass** [comment]
Check if it still repros

**Comment by isglass** [comment]
Reproduced
