### ISSUE TITLE
`ProjectLines` feature ignores `showCurrentTimeLine` config

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8563]
https://bryntum.com/products/gantt/docs/api/Gantt/feature/ProjectLines#config-showCurrentTimeLine

[Forum post](https://forum.bryntum.com/viewtopic.php?t=28023&e=1&view=unread#unread)

I am trying to replicate the "today" line in this demo: https://bryntum.com/products/scheduler/examples/timeranges/

In my config I set the config below, but no line is being drawn (see screenshot attachment). A line for project start/end is shown, but not for the current date. Is there additional configuration needed to make this work?

```
projectLinesFeature: { showCurrentTimeLine: true }

```

Here is a public repo that reproduces the issue: https://github.com/jamesonhill/-bryntum-issue
![Screenshot 2024-02-15 at 11.09.23 AM.png](https://forum.bryntum.com/download/file.php?id=26914)

**Comment by ghulamghousdev** [comment]
Hi @apdrsn,

`showCurrentTimeLine` is not working in ProjectLines. But I am not sure it ever intended to work. We will investigate this issue. Ideally But meanwhile you can use `showCurrentTimeLine` on timeRanges feature. https://bryntum.com/products/gantt/docs/api/Scheduler/feature/TimeRanges#config-showCurrentTimeLine and https://bryntum.com/products/gantt/docs/api/Scheduler/feature/TimeRanges.

In framewroks:

```
        timeRangesFeature : {
            showCurrentTimeLine : true
        }
```

in Vanilla JS:

```
        timeRanges : {
            showCurrentTimeLine : true
        }
```

**Comment by apdrsn** [comment]
@ghulamghousdev thank you very much - that worked 👍
