### ISSUE TITLE
LockRows event drag drop issue

### ISSUE THREAD

**Issue by isglass** [bryntum/support#8567]
First time it is moved, second time an assignment is added instead:

![dragdropbug](https://github.com/bryntum/support/assets/5415653/8f82fb0e-15ae-4924-b62e-4378a63bb9bf)

**Comment by isglass** [comment]
Disappears from locked next time you move it, some refresh missing?

Moving the one in the split makes it crash also

**Comment by chuckn0rris** [comment]
Also disappeared when move in not locked area and drop into locked are afterwards

https://github.com/bryntum/support/assets/7203098/e32fd525-b463-45b5-bdd1-471f319abe22
