### ISSUE TITLE
Gantt should support taskColor similar to Scheduler

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#857]
To style / color task elements easily. 

Case: https://www.bryntum.com/forum/viewtopic.php?f=52&t=14209&p=72840
https://www.bryntum.com/forum/viewtopic.php?f=52&t=18084&p=89519#p89519

**Comment by matsbryntse** [comment]
https://forum.bryntum.com/viewtopic.php?f=52&t=23415&p=115899#p115899

**Comment by JockeLindberg** [comment]
Separated the taskStyle part into it's own issue: bryntum/support#6199
