### ISSUE TITLE
Drag from tree demo not working correctly

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8571]
dropping a task from list causes change to other tasks in the scheduled part

http://lh/bryntum-suite/scheduler/examples/drag-from-grid-to-tree/

https://github.com/bryntum/support/assets/218570/d00940df-f90a-45fe-b2a7-b3e2e704888d

**Comment by mazzafabio** [comment]
@matsbryntse  How is it supposed to work? All Scheduler events are the same as the grid ones, so if dropping the same event in the same resource (already assigned) the only thing that should change should be its date.
Or when dropping, does it need to duplicate the event?
