### ISSUE TITLE
[REACT] Events disappear when scrolling and using jsx eventRenderer and resourceTimeRanges

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#8572]
Reproduced with the code user provided. 

It is really caused by the combination of resourceTimeRanges and JSX event renderer. When I disabled resourceTimeRanges the events are rendered correctly.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28028&p=140752#p140752)

When using custom eventRenderer returning jsx component while also using resourceTimeRanges rendered jsx content disappear during scrolling.

I'm attaching minimal reproducible example.

**Comment by danielrubak** [comment]
Hello guys, any update? When we can expect a fix for this bug?

**Comment by matsbryntse** [comment]
We will fix this in the next patch which is due in a few days.
