### ISSUE TITLE
Scrolling with EventEdit Modal open makes events disappear

### ISSUE THREAD

**Issue by kronaemmanuel** [bryntum/support#8579]
1. Open Scheduler/examples/lock-rows/ example in master branch
2. Lock by any type
3. Drag to create new event, eventEdit modal opens
4. Scroll, all events disappear

https://github.com/bryntum/support/assets/18748983/4a7a6828-4af6-4026-80a8-3af1d9cd841d

**Comment by isglass** [comment]
Probably fixed by changes to chain both stores
