### ISSUE TITLE
It is possible to hide all columns with no chance to show them.

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8584]
Reproduced with Microsoft edge browser in `nested-grid-with-chart` example in `Master Branch`

Steps to reproduce :
1. Right click on a column header
2. Hover on the columns item so the columns will be shown with a checkbox
3. Uncheck all the columns
4. Focus out of the headerMenu
5. Now right click on the header again
6. You'll see there is no options to show those column again

https://github.com/bryntum/support/assets/75997756/85f0799b-5bb3-45bf-b16d-69323b0684d2

**Comment by ExtAnimal** [comment]
You should never be allowed to hide all columns. The last checked item should become disabled. It usually works. In other examples it works. This is a bug in the `ColumnPicker` feature where it tries to disable the last checkable item in the column menu to prevent this very case.

**Comment by ExtAnimal** [comment]
It's the presence of the `expanderActionColumn` in that example.
