### ISSUE TITLE
Cutting from locked rows and pasting to normal rows doesn't paste to the normal rows and vice versa

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8589]
Reproduced with Microsoft edge browser in `/grid/examples/lock-rows/` example in `Master Branch`

Steps to reproduce:
1. Cut a record from locked rows
2. Paste into the normal rows
3. Now you'll see that the row isn't pasted to the normal rows
4. Now do vice versa you'll see the same

**Comment by taauntik** [comment]
Looks like copying from normal rows and pasting to normal rows pasted on normal and locked rows and vice versa

https://github.com/bryntum/support/assets/75997756/1125e828-c1ce-486f-a6ee-1cbf19634b76

**Comment by taauntik** [comment]
Simple cutting doens't seem to be working as well

https://github.com/bryntum/support/assets/75997756/8a0efcfa-6643-43be-acf7-207933ee7033

**Comment by ghulamghousdev** [comment]
Reported here as well https://forum.bryntum.com/viewtopic.php?p=142555#p142555
