### ISSUE TITLE
TimeAxisHeaderMenu disappears when changing the date range's startDate with the arrow

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8602]
Reproducible in `scheduler/examples/infinite-scroll/` demo in `Master Branch`
Browser : Mircorsoft Edge

Steps to reproduce :
1. Right Click on the timeAxis cell
2. Move mouse to Date Range
3. Try change the start date by clicking on the arrows of date field
4. After clicking on the arrow the whole menu disappears

It works fine when you click on the arrow of endDate's date field

Video:

https://github.com/bryntum/support/assets/75997756/894b256a-e066-437d-9b94-8d6f91a677bd

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/8597
