### ISSUE TITLE
Event drag does not work on iPad - it triggers timeline scrolling

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#8619]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=140844#p140844)

**Comment by ghulamghousdev** [comment]
[+1 here](https://forum.bryntum.com/viewtopic.php?p=144498#p144498)

**Comment by ghulamghousdev** [comment]
This is a blocking issue for the customer: https://forum.bryntum.com/viewtopic.php?p=148353#p148353

**Comment by ghulamghousdev** [comment]
+1 for customer asking the fix: https://forum.bryntum.com/viewtopic.php?p=149364#p149364
