### ISSUE TITLE
`startDate` and  `endDate` are `undefined` in `beforeDragMoveEnd` listener

### ISSUE THREAD

**Issue by kevinschweikert** [bryntum/support#8626]
We are creating an Event from an external source. When we drag and drop the element into the calendar, the `beforeDragMoveEnd` callback is called, but the fields `startDate` and `endDate` are `undefined`.
To recreate this issue, add the following lines to the `listener` object in https://bryntum.com/products/calendar/examples/dragfromgrid/:

```js
beforeDragMoveEnd: async ({ eventRecord, view, drag }) => {
     console.log(eventRecord.startDate)
     return false
},
```

**Comment by matsbryntse** [comment]
Try using:
```

beforeDragMoveEnd: async ({ eventRecord, newStartDate, newEndDate, view, drag }) => {
     console.log(newStartDate)
     return false
},
```

Is that sufficient for your use case?

https://bryntum.com/products/calendar/docs/api/Calendar/feature/CalendarDrag#event-beforeDragMoveEnd
