### ISSUE TITLE
Incorrect page size while printing in Letter Page format

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8658]
[[Forum post](https://forum.bryntum.com/viewtopic.php?p=141173#p141173)
](https://forum.bryntum.com/viewtopic.php?p=141173#p141173)

**Comment by chuckn0rris** [comment]
reproduced the problem in Portrait orientation

**Comment by taauntik** [comment]
This issue seems to be happening when the paper size you select from the print feature popup doesn't match with the browser's print popup paper size. If you select the same size in the in the browser's native print popup it should work.

**Comment by taauntik** [comment]
not fixable
