### ISSUE TITLE
bbar : { type : 'pagingtoolbar' } typing error 

### ISSUE THREAD

**Issue by rubiconsid** [bryntum/support#8672]
When working with Grid Paged fw demos, noticed that `bbar : { type : 'pagingtoolbar' }` is not working in typescript 
 
 
```
const gridConfig : Partial<GridConfig> = {
......
    bbar : { 
        type : 'pagingtoolbar'
    }
 
```

Have discussed with Saki, and suggested to report to Sergey to have a look in typing bug for below: 

![image](https://github.com/bryntum/support/assets/116875109/8f10d0c2-0131-40a2-a79c-f473a939ef01)

![image](https://github.com/bryntum/support/assets/116875109/b6c34f6f-70bb-4db6-a4f5-823ec99883e1)

In fw demos now, it is using `strips` instead as workaround for issue above .
```
      strips : {
            bottom : {
                dock : 'bottom',
                type : 'pagingtoolbar'
            }
        }

```
![image](https://github.com/bryntum/support/assets/116875109/a8bf9a84-5d86-49cb-91f6-2c8339b74642)

**Comment by SergeyMaltsev** [comment]
@rubiconsid from docs and type declaration it shows that you may use `Partial<ContainerItemConfig>` or `string`  as array

![image](https://github.com/bryntum/support/assets/57486330/0dabd815-731d-41b2-9d61-7dd2937073c6)

https://bryntum.com/products/grid/docs/api/Core/widget/Panel#config-bbar

Did you try the below?

```
const gridConfig : Partial<GridConfig> = {
....
    bbar : [ 'pagingtoolbar' ]
```

or


```
const gridConfig : Partial<GridConfig> = {
......
    bbar : [{ 
        type : 'pagingtoolbar'
    }]
```

Please change docs for `tbar` and `bbar` if they don't match the API code.

**Comment by SergeyMaltsev** [comment]
@rubiconsid please fix docs to match what is expected by API. Please contact our API devs for clarifying.

**Comment by rubiconsid** [comment]
Prediscussed with Sergey for a fix as below in Paged demo PR, which will need Johan's doublecheck: 
`In Panel.js`
```
/**
             * A Config object representing the configuration of a {@link Core.widget.PagingToolbar}, <---
             * or array of config objects representing the child items of a Toolbar.
             *
             * This creates a toolbar docked to the top of the panel immediately below the header.
             * @config {Array<ContainerItemConfig|String>|ToolbarConfig|PagingToolbarConfig} <---
             * @category Content
             */
            tbar : null,

            /**
             * Get toolbar {@link Core.widget.Toolbar} docked to the bottom of the panel
             * @member {Core.widget.Toolbar} bbar
             * @readonly
             * @category Content
             */
            /**
             * A Config object representing the configuration of a {@link Core.widget.PagingToolbar},  <----
             * or array of config objects representing the child items of a Toolbar.
             *
             * This creates a toolbar docked to the bottom of the panel immediately above the footer.
             * @config {Array<ContainerItemConfig|String>|ToolbarConfig|PagingToolbarConfig} <----
             * @category Content
             */
            bbar : null, 
```
