### ISSUE TITLE
Implement copyKey for EventDrag feature

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#869]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=14223
https://www.bryntum.com/forum/viewtopic.php?f=44&t=17891&p=88588#p88588

Need to be able to configure EventDrag feature to copy events if a "copyKey" pressed, for example ctrl key. 

User's use case is to be able to copy events when drag between schedulers in http://lh/bryntum-suite/scheduler/examples/drag-between-schedulers/

**Comment by bmblb** [comment]
Fixed by: https://github.com/bryntum/support/issues/4940
