### ISSUE TITLE
CSV exported data shows special character Â for indentation in Windows OS

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8690]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=141490#p141490)

1. Go to https://bryntum.com/products/gantt/examples/exporttoexcel/
2. click on export to csv
3. open the csv file in excel on windows
4. See the special char being shown for indentation.

The imp thing, this issue is not reproducible on Mac.

![image](https://github.com/bryntum/support/assets/52177956/0c3b61ec-f167-491e-b9b3-4237a9a1ed5c)

[Launch SaaS Product.csv](https://github.com/bryntum/support/files/14415452/Launch.SaaS.Product.csv)

Typo in demo(s) button. Should be `XLSX`

![image](https://github.com/bryntum/support/assets/57486330/c95a992e-399b-486f-9210-8e16f249f52a)

In docs also

![image](https://github.com/bryntum/support/assets/57486330/e7b925d2-655d-4857-a426-644d4f6abeed)

**Comment by SergeyMaltsev** [comment]
This config
https://bryntum.com/products/grid/docs/api/Grid/util/TableExporter#config-indentationSymbol
defaults to `'\u00A0\u00A0\u00A0\u00A0'`.

This outputs spaces in cvs as non-breaking spaces
This works for `xslx` export, but breaks csv.

This config in app fixes csv export
```
    features : {
        excelExporter : {
            // Choose the date format for date fields
            dateFormat : 'YYYY-MM-DD HH:mm',

            exporterConfig : {
                indentationSymbol : '    '
            }
        }
    }
```
