### ISSUE TITLE
Panel header changes size when collapsing / expanding panel in Stockholm theme

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8698]
Causes animation to jump when collapsing filter panel in this demo:

https://bryntum.com/products/gantt/examples/fieldfilters/

**Comment by dongryphon** [comment]
This happens in Stockholm theme (not in Material or Classic afaict) due to the collapsed header not having any tools in the panel header. This causes the header to reduce in height by a few pixels at the start of the collapse.
