### ISSUE TITLE
Adding resources from resources tab crashes

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8710]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28174&p=141597#p141597)

Good morning,
using the resources tab inside the task editor i found a bug.

You can reproduce it in this example: https://bryntum.com/products/gantt/examples/advanced/

Steps to reproduce the issue:

1. take for example the task Install Apache (1.1.1)
2. open the task editor and go to the resources tab -> you will have only Celia
3. add a new resource: type a name in the dropdown to filter the list of available resources using the keyboard and press two times enter to add the resource (important: use the keyboard otherwise it won't give the error)
4. click cancel (on the task editor) -> the task editor will close and you will receive this error on the console:
![Bug 1.png](https://forum.bryntum.com/download/file.php?id=27131)
5. after receiving the error the task editor won't open anymore and will continue to give the same error on console when trying to open it

**Comment by canonic-epicure** [comment]
https://github.com/bryntum/support/assets/72431/3df79da0-d4b9-4325-b37b-fe69dcc89c4e

**Comment by canonic-epicure** [comment]
Does not seem to be reproducible (see the video above)? Please provide steps to reproduce the issue.
