### ISSUE TITLE
Vue components within cells causing unexpected results

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8721]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28184&p=141695#p141695)

"First of all - just wanted to take a brief second and commend Bryntum on making great products. Keep up the good work.

A glitch has recently been brought to my attention when rendering a Vue component within the cells of a column. I'm experiencing the content of the cell being repeated within the same cell. This could very well be something I'm doing wrong. Below, I've whittled down the code to the most basic form I could that demonstrates the problem.

Bryntum Version: Vue2 5.5.0 (also tried with 5.6.7)
Chrome 122, Firefox 95 (doesn't seem to be a browser specifc issue)
No console errors

This problem happens when scrolling up or down, and seems to only happen on larger data sets where there are at least a couple hundred rows. Continuing to scroll up or down until the rows are not visible, then scrolling them back into view resolves it temporarily. It seems like the renderer is having a difficult time keeping up with the scrolling rows.

It seems to be fairly random, and I'm unable to pinpoint the culprit. Within our fully configured Gantt, fiddling around with changing the height, rowHeight, and even adding/removing the tbar seems to have a bit of an effect on how prevalent the glitchiness is. Strangely, when using this most basic example below, different height settings seem to have no affect (or lesser) and the repeated content is somewhat more consistent. It also is not restricted to the percentDone column, but has similar unpredictability on any column where a vue component is rendered.

I have followed the Bryntum example found here:
[Gantt/Integration/Vue/Guide#implement column renderer](https://bryntum.com/products/gantt/docs/guide/Gantt/integration/vue/guide#implement-column-renderer)"

[https://photos.app.goo.gl/WpLYHXaCcL2rSfYn9](https://photos.app.goo.gl/WpLYHXaCcL2rSfYn9)

[inline-data.zip](https://github.com/bryntum/support/files/14453393/inline-data.zip)

**Comment by awacode21** [comment]
maybe related with this one? https://github.com/bryntum/support/issues/8519

**Comment by jsakalos** [comment]
Not reproducible with Bryntum version 6.0.2 and Vue 2 version 2.7.16. Closing the ticket.

**Comment by jsakalos** [comment]
I have re-investigated the ticket and I found that it is not reproducible with Vue 3.2.13 and Bryntum 6.1.3 versions. I'm attaching the new showcase.

[inline-data.zip](https://github.com/user-attachments/files/17702030/inline-data.zip)
