### ISSUE TITLE
Invalid record(s) count in store

### ISSUE THREAD

**Issue by muhammad-faisal101** [bryntum/support#8737]
During grouping, collapsing the group header changes the store's `originalCount`.

Loom: https://www.loom.com/share/0fbbe01c09094ef09cc7d6939c2259de

**Comment by ExtAnimal** [comment]
The property indicates the  number of real, non-group header records currently in the store. Maybe the docs could explain this better.

What is the use case, what records are you wanting to manipulate?

**Comment by ExtAnimal** [comment]
The number of records in the store changes. When you collapse a group, the children are removed.

The property indicates the number of real, **non-group header** records currently in the store:

![Screenshot 2024-03-05 at 07 08 13](https://github.com/bryntum/support/assets/200516/9c64d773-c479-4793-96a2-dda24c0e6652)

What is the use case, what records are you wanting to manipulate?

**Comment by muhammad-faisal101** [comment]
I need to fetch the overall count of data records stored, without considering any group header records and filters. So, I assumed that utilizing the `originalCount` property would be the appropriate choice for this, based on the description provided in the documentation.

https://bryntum.com/products/schedulerpro/docs/api/Core/data/Store#property-originalCount

**Comment by ExtAnimal** [comment]
Try this

```
let totalCount = 0;
myStore.groupRecords.forEach(g => totalCount += g.groupChildren.length);
```

![Screenshot 2024-03-05 at 08 46 02](https://github.com/bryntum/support/assets/200516/aaa7759c-9723-4d09-82e6-587848718cd9)

**Comment by muhammad-faisal101** [comment]
> Try this
> 
> ```
> let totalCount = 0;
> myStore.groupRecords.forEach(g => totalCount += g.groupChildren.length);
> ```
> 
> ![Screenshot 2024-03-05 at 08 46 02](https://private-user-images.githubusercontent.com/200516/310026502-aaa7759c-9723-4d09-82e6-587848718cd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzk0NjMsIm5iZiI6MTcwOTYzOTE2MywicGF0aCI6Ii8yMDA1MTYvMzEwMDI2NTAyLWFhYTc3NTljLTk3MjMtNGQwOS04MmU2LTU4Nzg0ODcxOGNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMTQ2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWRjYmQ4Y2ZjZTE1MmE3NmJjY2ViZDg3ZmEzNDA3NmEzNzVjYWRhNWE4YTk5MDQ4MWRiZjAwODA2YmNhMmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zM8dvVHepsRJMUMyXYn-liljtpfnxoTYKXXob3SYZFI)

![image](https://github.com/bryntum/support/assets/109215133/24812c48-a83a-4dfc-bc2b-f7cb398a8ea2)
Cannot rely on this implementation because filtering will affect the record count.

**Comment by ExtAnimal** [comment]
You can sidestep filtering:

```
let totalCount = 0;
grid.store.unfilteredGroupRecords.forEach(g => totalCount += g.unfilteredGroupChildren.length);
console.log(totalCount);
```

![Screenshot 2024-03-05 at 15 35 56](https://github.com/bryntum/support/assets/200516/11d43c1a-6b60-4274-975b-5b525ad14058)

But yes, these are currently private properties. Perhaps we should publicize them.

**Comment by ExtAnimal** [comment]
There is a private function which we could publicize.

```
getAllDataRecords(searchAllRecords)
```

Pass `true` to cut through filtering.

**Comment by muhammad-faisal101** [comment]
Are you guys planning to resolve this fix in any of the future release?

**Comment by isglass** [comment]
This has been resolved, `originalCount` and `allCount` are now deprecated since their behavior was undefined / unexpected. We have instead improved the `getCount()` function to allow detailed control over what count to get, letting the app decide how to count
