### ISSUE TITLE
Release email not looking that good in Outlook

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#8743]
From Outlook on my Windows machine:
![image](https://github.com/bryntum/support/assets/100013589/87d091e8-56a2-4f30-9aa5-f081a2331ab6)

Seems that it doesn't like "&apos"
Also, the "backtick" styled background doesn't look that good

**Comment by SergeyMaltsev** [comment]
Thunderbird 115.8.0
![image](https://github.com/bryntum/support/assets/57486330/df28e15c-cd92-48ea-8fbb-b83d3ecc2a0c)
