### ISSUE TITLE
Unplanned tasks resets duration on revertChanges

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8746]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=28243&p=141939#p141939)

Hi, 

We have a use case for unplanned work/ unplanned tasks to revert the changes when the backend returns an error on the save event. This all works fine, except the scheduler does not reset the duration field -> with as result the task is back in the unplanned grid, but the duration field is not set anymore. 

It is reproducible on the public demo of unplanned work (https://bryntum.com/products/schedulerpro/examples/drag-unplanned-tasks/). Replace the onSave method with the following: 

```
onSave() {
                Toast.show('TODO: Save data (see onSave() event for SchedulerPro)');
                // console.log('Changes:', this.project.changes);
this.project.commitAsync().then(() => {
    this.project.revertChanges();
    return this.project.commitAsync()
}).then(() => {
    this.project.acceptChanges();
});

        },
        
```

https://drive.google.com/file/d/1-9C4OUWLCAxXk-caWiK_3_1QTW0X5joi/view?usp=sharing

**Comment by matsbryntse** [comment]
Looks engine related @canonic-epicure, after event is "descheduled", start+end are reset to null which triggers duration to be lost too.

**Comment by ghulamghousdev** [comment]
[+1 here](https://forum.bryntum.com/viewtopic.php?p=144850#p144850)
