### ISSUE TITLE
need to change date format and display time in calendar header

### ISSUE THREAD

**Issue by venugopalpathuri** [bryntum/support#8749]
Hi

I don't know how to change the date display like below:
 
the header of calendar
 
need to change date format and display time

from  Mar 09, 2024 (week 10)

to    Mar 03 - Mar 09, 2024 , IST
![image](https://github.com/bryntum/support/assets/159218205/8488cc20-c4df-4dd7-b449-b5203ed39453)

**Comment by matsbryntse** [comment]
@venugopalpathuri Better to post in our forums, GitHub is only for bug reports / feature requests. Please join here https://forum.bryntum.com/
