### ISSUE TITLE
Gantt docs issues

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#875]
Problems on master branch are revealed by `open-all-links` test. So far I found two types of issues:
1. wrong link to guide
2. incorrect class name is used for inline demos

#### Wrong link to guide
SchedulerPro/view/SchedulerPro class references **getting_started** guide, which references **styling** guide. SchedulerPro docs are not updated when moved to the gantt, so it expects same structure from guides:
- customization
- - styling
- Pro
- - calendars
- - getting_started // references `styling`

Styling guide has to be somehow copied to the gantt docs, but not into the **customization** folder which exists there, because it only has gantt-specific guides. It should probably be copied to **Scheduler PRo** folder during build step and link in the docs updated too?

#### Incorrect class name is used for inline demos
Some inline demos in schedulerpro use syntax `new ProjectModel`. Problem is that it expects `SchedulerPro/model/ProjectModel` and when run in gantt docs that is a `Gantt/model/ProjectModel` class. `SchedulerProProjectModel` should be used instead.
So, once again source code has to be processed during copy.

I think changes should only be in the build script, not in the scheduler pro docs/code.

**Comment by arcady-zherdev** [comment]
Wrong repo ..the Gantt 3.0.0 is not released yet
