### ISSUE TITLE
Fail to render the Gantt after change the sorting of Duration column

### ISSUE THREAD

**Issue by leslieli** [bryntum/support#8750]
Hi there,

We are using Gantt Pro 6.1.22 + Ext JS 7.3.1.27 in our project. The project Gantt is rendered well after initialing.
But after we changed the sorting of Duration column and tried to refresh the Gantt with `gantt.taskStore.setRootNode({ children: tasksData, id: 'root', name: 'root' });`, there was a `Can't find a project calendar in 'getProjectCalendar'` error occurred.

It happened when trying to sort the tasks in `setupNodes` since the tasks have no `calendar` info during setup the nodes.

Please help check if it is a bug of Gantt component and suggest the solution/fix if any. Thanks.

**Comment by matsbryntse** [comment]
@leslieli Can you please post this in our support forums with a small test case so we can try to reproduce it? https://forum.bryntum.com/viewforum.php?f=49&sid=b6d31db7eed6d28777b5dfadc2b3c972

**Comment by leslieli** [comment]
Posted it in https://forum.bryntum.com/viewtopic.php?t=28259.
