### ISSUE TITLE
[TypeScript] incorrect declaration of `GridConfig` comparing to the docs

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8762]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=28262&p=142040#p142040)

"Hi!

I'm creating a grid in my application, and reading the GridConfig type, in TS file and some fields isn't from Grid. In the documentation the grid is inherited from Panel, but the field configuration is from ToolTip class, like "anchorToTarget" and "allowOver".

I guess is this only a problem from file generation.

But this can be fixed to have only the real configuration of the grid?"

![Screenshot 2024-03-06 at 18 54 17](https://github.com/bryntum/support/assets/16693227/40d9b9da-fd76-4b38-8d32-cfd77498ed68)
![Screenshot 2024-03-06 at 18 54 40](https://github.com/bryntum/support/assets/16693227/c293b1dc-7a74-433d-8179-34c6694920b1)

**Comment by henriquewerlang** [comment]
Any news about this?

**Comment by matsbryntse** [comment]
Should be fixed now!
