### ISSUE TITLE
Interim Display of "No Record to Display" Message in BryntumGantt

### ISSUE THREAD

**Issue by osamaarshad20** [bryntum/support#8766]
Hi there,

I'm encountering an issue with the BryntumGantt package where, upon data loading, there's an interim display of the message "No record to display." I've invested considerable time into investigating this matter, and it seems that there isn't a straightforward solution.

The problem appears to stem from the data loading process itself, specifically when utilizing the package via `import { BryntumGantt } from '@bryntum/gantt-react';`. It seems that this delay in data loading causes the premature display of the "No record to display" message.

I'm reaching out for support and guidance on how to address this issue effectively. Any insights, workarounds, or potential fixes would be greatly appreciated.

Thanks in advance.

**Comment by matsbryntse** [comment]
@osamaarshad20 Can you please post this in our support forums, and share details of how we can reproduce this? https://forum.bryntum.com/ 

The team is on standby ready to assist!
