### ISSUE TITLE
Resizing event weirdly behaving on weekview

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8769]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28282&p=142192#p142192)

Please fine below Demo link

https://www.bryntum.com/products/scheduler/examples/configuration/

replication steps

1. change preset option from day and night to week
2. create an event on 1st date from 12:00 PM to 2:00PM
3. resize end part of event a bit
4. see it directly move it to 2nd date's end

## **Note** 
It is blocking issue for the client.

**Comment by mazzafabio** [comment]
After examining this ticket, it doesn't seem to be an issue.
The correct behavior is that when resizing, the code ensures that the duration of the event should be at least equal to the `resolutionIncrement` `resolutionUnits`. Then if an event starts at 12 pm on the 10th, if resizing a bit (just a few minutes), it should end at least at 12 pm on the 11th. After that, the code rounds up that date (`Math.Round` fn is used.. then hours greater or equal to 12pm are round up): 12 pm on the 11th ends up at 12 pm on the 12th.
I guess that to satisfy the request of the client, we should add a new config in the `EventResize` feature, that simply snaps the date to the next date without any other calculations.
