### ISSUE TITLE
Add configs to reapply store sorters on add/update

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#877]
https://www.bryntum.com/forum/viewtopic.php?p=73024#p73024

http://lh/bryntum-suite/grid/examples/basic/
```
grid.store.sort('city', 'asc')
// Barcelona at the top
grid.store.first.city = 'Kiev'
// This record shouldn't be the first anymore
grid.store.add({ city : 'Antalya' })
// This record should be the first
```

StoreSort should have similar configs to StoreFilter:
https://www.bryntum.com/docs/scheduler/#Core/data/mixin/StoreFilter#config-reapplyFilterOnAdd
https://www.bryntum.com/docs/scheduler/#Core/data/mixin/StoreFilter#config-reapplyFilterOnUpdate

**Comment by JockeLindberg** [comment]
We have configs for filter add/update and sort add. We're missing sort update

**Comment by ghulamghousdev** [comment]
Requested here: https://forum.bryntum.com/viewtopic.php?p=155972#p155972
