### ISSUE TITLE
Option to not allow to collapse Gantt timeline region

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8775]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28297&p=142239#p142239)

Hi everyone,

I have a requirement.

There should be an option to enable or disable the Gantt state provided from hiding the Gantt chart,

I am also attaching a video with complete functionality
https://www.loom.com/share/9306e5ed9d804001a71775be469e57af

**Comment by bb-xops** [comment]
whats the status of this ? i want my splitter button disabled.

**Comment by matsbryntse** [comment]
@bb-xops You mean you want none of the buttons? Try https://bryntum.com/products/scheduler/docs/api/Grid/feature/RegionResize#config-showSplitterButtons

**Comment by matsbryntse** [comment]
If you want to prevent collapsing timeline - you can now prevent a SubGrid from being fully expanded by providing a `maxWidth` to it in the `subGridConfigs`
