### ISSUE TITLE
Dropping a task inside a non-parent should be allowed

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8780]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28295&p=142267#p142267)

Client want  the functionality of dragging a task and droping it on another task which is not parent, should convert it to parent and make the dropped task its child
I have this when I am trying to drag inside another task which is not parent does not allow me.

I am also attaching a video with a demonstration thanks.
https://www.loom.com/share/7d929fd810614ab1940afbde45666fa6

**Comment by matsbryntse** [comment]
Already supported via `dropOnLeaf` setting on RowReorder. https://bryntum.com/products/grid/docs/api/Grid/feature/RowReorder#config-dropOnLeaf
