### ISSUE TITLE
[Windows OS] Dragging event editor in Scheduler is Jerky

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8781]
Steps to reproduce:
1. Go to https://bryntum.com/products/scheduler/examples/booking/
2. Open event editor
3. Try to move event editor to and fro and see the movement of event editor is jerky.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28285&p=142283#p142283)

See the clip:

https://github.com/bryntum/support/assets/52177956/3bc96294-0057-4182-b17c-6efa9ff08007

**Comment by ghulamghousdev** [comment]
Duplicate of https://github.com/bryntum/support/issues/4428

**Comment by hn1** [comment]
WOW. This was reported 2 years ago and is still unresolved?
Any idea if or when this issue will be dealt with as we cannot use the product in this state.
