### ISSUE TITLE
Occurrences should not be skipped for COUNT-based rules when changing `exceptionDates` at the data level

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#8783]
To reproduce:

1. navigate to https://bryntum.com/products/calendar/examples/basic/
2. go to today
3. create a recurring event: Repeats daily, ends after 2 repeats
4. in console: `bryntum.query('calendar').eventStore.last.excpetionDates = ['2024-MM-dd']; // first day`
5. in console: `bryntum.query('calendar').eventStore.last.excpetionDates = ['2024-MM-dd']; // second day`

The behavior is different: 
* If we set it to first day then the 1st event disappears and we only see one - on the 2nd day. 
* If we set it to 2nd day then the 2nd event jumps one day forward and we still see 2 events.

Is this an expected behavior?

Note: This issue has nothing to do with Angular.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=28287&p=142194#p142194)

Hello. Let's say we have this recurrence: RRULE:FREQ=DAILY;INTERVAL=1;COUNT=2 that start on 3/8/2024.

The displayed dates will be: 3/8/2024 and 3/9/2024.

If i add to ExceptionDates the first date, the displayed dates will be: 3/9/2024 wich is correct.

BUT if i add to ExceptionDates the last date, the displayed dates will be: 3/8/2024 AND 3/10/2024 wich is wrong.

**Comment by AlexandruIonutZarnescu** [comment]
Hello, any news about this bug?
One ETA of this?

**Comment by matsbryntse** [comment]
Checking it now, it might already be fixed

**Comment by matsbryntse** [comment]
@AlexandruIonutZarnescu Are you deleting the occurrence via UI? Or you are providing `exceptionDates` in your Event data?
