### ISSUE TITLE
Impossible to tab back to cell editing

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#879]
When editing cells in the locked section it is possible to tab to events in the normal section. But you cannot tab back to cells.
Steps to reproduce on basic demo https://bryntum.com/examples/scheduler/basic/ :
1. Docus cell `Don`, type arrow keys, see selection is moving
2. Press `TAB`, see focus moved to normal section and arrow keys now change event selection
3. When you try to `Shift + TAB`, focus won't move to cells. It will go to normal header -> locked header -> buttons in toolbar and then address bar.

**Comment by isglass** [comment]
When navigating from a grid cell to an event, either by right arrow or tab -> event in same row should get focused

**Comment by isglass** [comment]
With a11y changes, events are considered parts of the cells. Hitting ESC moves out of the event and into the cell, letting you navigate cells
