### ISSUE TITLE
Step does not work for startTimeField in event editor

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8792]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=1&t=28334&p=142400#p142400)

I got the config for a calendar in my file here

```
 
 let calendarConfig: Partial<CalendarFeaturesConfigType> = {
            eventEdit: {
                items: {
                    startTimeField:{
                        type   : 'time',
                        editor : {
                            step : '5min'
                        }
                    },
                    endTimeField:{
                        editable: true,
                        step: '5m'
                    },
                    allDay: null,
                    nameField: null,
                    resourceField: {
                        label: t("trackTypes"),
                        listeners: {
                            change(event: BryntumChangeEvent) {
                                const find = calendars.find(calendar =>  calendar.id === +event.value);
                                console.log(event.value)
                                console.log(find)
                                setEventEditStep(find && find.cronofyTimeSlot ? find.cronofyTimeSlot: 30)
                            },
                        },
                        type: "combo",
                        picker: {
                            allowGroupSelect: false
                        },
                        multiSelect: false,
                        editable: false,
                        weight: 0,
                        required: true
                    },
                    recurrenceCombo: null,
                    commentsField: {
                        label: t("comments"),
                        type: "textarea",
                        name: "comments",
                    },
                },
            }
        }

```

I tried multiple things that should work for step. But it's not changing.

-------------------------------------------
Use this code to repro
```javascript
        eventEdit : {
            items : {
                startTimeField : {
                    step : '5min'
                }
            }
        }
```
![msedge_vRLhTwoJRI](https://github.com/bryntum/support/assets/75997756/b9b80614-1f9c-4a8c-9ea4-9170d0e36eea)

**Comment by johnny090807** [comment]
Good morning taauntik!

I firstly wanted to say. Great job on the fast fix!

We would really like this issue to be released in the next update. It is really important for us, because we want to release the calendar to our customer. 

I want to thank you again on the great help!

Kind regards,

John

**Comment by taauntik** [comment]
Hi @johnny090807,

Thank you for your message and your kind words regarding the fast fix. I'm delighted to hear that it met your expectations!
I completely understand the urgency of getting this issue resolved, especially with your calendar release in mind. I've made sure that **the fix will be included in the next patch release**.

Your feedback is valuable to us, and we're dedicated to ensuring the smooth functionality of our product.

If you have any further questions or need assistance, feel free to reach out (to our support forum). We're here to help!

Thanks again for your understanding and patience.

Best regards,
Tasnim

**Comment by johnny090807** [comment]
Could you tell me when this will be released? And also just to be sure. The task states that the startTimeField doesn't update, but the endTimeField also doesn't update. I hope that also will be fixed with this update 😬

**Comment by matsbryntse** [comment]
Should be out in a few days, fix covers endTimeField too.
