### ISSUE TITLE
Timeranges feature not working when using thin modules

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8794]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=28335&p=142402#p142402)

"I am using gantt-thin package and when I try to set the timeRanges prop to Bryntum gantt I got error:

Feature 'timeRanges' not available, make sure you have imported it"

- Go to https://bryntum.com/products/gantt/examples/gantt-taskboard/
- Edit the Gantt to have the timeRanges feature - https://bryntum.com/products/gantt/docs/api/Scheduler/feature/TimeRanges
- Check the console, the error is triggered when the page is loaded.

**Comment by mazzafabio** [comment]
It was only required to import scheduler thin module. Just misunderstanding.
