### ISSUE TITLE
multiEventSelect and updating occurrences in a repeating series

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#8800]
Yes, it behaves as user describes. It seems that not all selected events are processed:

<img width="1471" alt="Screenshot 2024-03-13 at 10 00 24" src="https://github.com/bryntum/support/assets/204844/f625e3a5-4836-424d-ac62-1cae995cce78">

Note: The provided showcase needs Node 18 to work.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28344&p=142440#p142440)

Hello!

I'm seeing some unexpected behavior when selecting multiple (2) occurrences of a recurring event series and dragging them to change the start time.

When I select "All Future Events", the sync request payload looks as I expect, with 2 added events and 2 updated events. The updated events end the series via the recurrenceRule, and the updated events add 2 new recurring events that reflect the updated start time. This makes sense to me.

However, when I select "Only This Event", the sync request payload includes 1 added event with a null recurrenceRule, and another added event with a recurrence rule. I expected both added events to have a null recurrenceRule, since I am making exceptions to the series. However, it seems that my "Only This Event" choice is only applied to one of the selected events I am dragging to a new time. The other change in the sync request looks like it is applying "All Future Events" behavior.

I've reproduced this by modifying the scheduler pro + react + typescript + recurring events example project. (See attached.) I've included a few configs that we use in our own project: project instead of crudManager, multiEventSelect, taskEdit, and I've also updated the data.json to use assignments. (Autosyncing doesn't work, but I'm logging the request to inspect the payload.)

Do I have something configured incorrectly or am I misunderstanding what should happen in this scenario?

Thanks in advance for your help!

Kirsten

**Comment by kellywu** [comment]
@jsakalos is there an update on this and why it may be fixed? it's preventing the bulk edit feature from working

**Comment by jsakalos** [comment]
The issue has been fixed and will be released in the upcoming `5.6.12` version.

<img width="1297" alt="Screenshot 2024-06-11 at 14 56 54" src="https://github.com/bryntum/support/assets/204844/ba742d98-b541-4e97-ab4e-ba0636dfe6e9">
