### ISSUE TITLE
thin packages with trial npm access?

### ISSUE THREAD

**Issue by SaniMusic** [bryntum/support#8804]
Hey! Awesome products :)

My organisation is currently evaluating the product and we will wan't to load multiple views.

Our understanding is that the error " The Bryntum Grid bundle was loaded multiple times by the application." is solved by using thin packages [1]. However it seems like these are not available with the trial npm signin. 

Any suggestion how we can move forward?

[1] https://bryntum.com/products/grid/docs/guide/Grid/integration/react/multiple-products

Versions from yarn.lock file:
--------------
"@bryntum/calendar-trial-lib@1.0.0":
  version "1.0.0"
  resolved "https://npm.bryntum.com/@bryntum%2fcalendar-trial-lib/-/calendar-trial-lib-1.0.0.tgz#abc65ac2d390a902c42ca991ada21b59739e5aa1"
  integrity sha512-ksFBeKyU7BvIRo82K5Q0YlR44Ekf/HNCSxsgcsi6yUoVSS0QPob94KpTwkFQO5aUb7yqem2vmUTA6tLHR4aVWQ==

"@bryntum/calendar@npm:@bryntum/calendar-trial@latest":
  version "5.6.6"
  resolved "https://npm.bryntum.com/@bryntum%2fcalendar-trial/-/calendar-trial-5.6.6.tgz#1ae79b2bc3f7de8d580017785e9b41ddf0a359ce"
  integrity sha512-kzzxCygBoabd7KwK7hEm9vD+0nBH36olXZ8TfSDMIzEoi6uWYm+fmBQH+s9q87QwB+j9nuu0qqxHHPGSrdbThg==
  optionalDependencies:
    "@bryntum/calendar-trial-lib" "1.0.0"

"@bryntum/gantt-react@latest":
  version "5.6.6"
  resolved "https://npm.bryntum.com/@bryntum%2fgantt-react/-/gantt-react-5.6.6.tgz#17a121f1df71862815b53e4ebb1f5c1c14e8442d"
  integrity sha512-7yyNx0jlynuQ6uNRAn9V/t6s4FLRQtseyXfEv1PX3dmzR5OqdJD2losCQ4GdHym5J4bFX8LnUDcEzSKe1QfAHw==

"@bryntum/gantt-trial-lib@1.0.0":
  version "1.0.0"
  resolved "https://npm.bryntum.com/@bryntum%2fgantt-trial-lib/-/gantt-trial-lib-1.0.0.tgz#a706a41f01d14ec8f2e2f1c7b637c5810a644ce5"
  integrity sha512-RcmujANGGJ5KHiUbINqeQ5dtnDAKaQ+gSp/33mhTinMpdgWLgaKKZOnmmUSveglmapJKRSyfHQJVx00S+OJAHA==

"@bryntum/gantt@npm:@bryntum/gantt-trial@latest":
  version "5.6.6"
  resolved "https://npm.bryntum.com/@bryntum%2fgantt-trial/-/gantt-trial-5.6.6.tgz#3ff1d47edbdc1ab43509e173d305038ad8d08b6b"
  integrity sha512-J9Bnxl/Q59SMrixeT46OBbAScx/wUqTjdPvrZ6Xg5ulE6+M+QoXPMjKcHYb9+KDOCeR4qmnzzRbO+tO2JShQOw==
  optionalDependencies:
    "@bryntum/gantt-trial-lib" "1.0.0"

"@bryntum/grid-trial-lib@1.0.0":
  version "1.0.0"
  resolved "https://npm.bryntum.com/@bryntum%2fgrid-trial-lib/-/grid-trial-lib-1.0.0.tgz#891318a900ed868201171ed94eb5dc6da96d5fcc"
  integrity sha512-TE39mh31SW87EDmcoknpXm+E0lLi3qJ/PWvRttGETQym8ydyJNReHBivf9lN2ZOu/IuQWOstVMpBv3nAUPgAlQ==

"@bryntum/grid@npm:@bryntum/grid-trial@latest":
  version "5.6.6"
  resolved "https://npm.bryntum.com/@bryntum%2fgrid-trial/-/grid-trial-5.6.6.tgz#4d52d105c9f993af904e0bf782448b7d2d41a174"
  integrity sha512-YibYZ7sue3LDSKimNy6PE9/e1HIx5/RFUgTkwxrr5aYZEsyncaIrwEsW6Y5MA3jrdA2R9ydc5DCp2JrgxGZqxw==
  optionalDependencies:
    "@bryntum/grid-trial-lib" "1.0.0"

"@bryntum/scheduler-trial-lib@1.0.0":
  version "1.0.0"
  resolved "https://npm.bryntum.com/@bryntum%2fscheduler-trial-lib/-/scheduler-trial-lib-1.0.0.tgz#298d4d904b765c0b0cf4c5d6d1a2e667d9314308"
  integrity sha512-cOFtEq/KJUhGGh9wKNSmL5skrzpYpSj1EBML6NZVA+uYJ07dIMP/Ha7iSzlWyIFN1rTOGnAOa+WqXTS2SKNo2g==

"@bryntum/scheduler@npm:@bryntum/scheduler-trial@latest":
  version "5.6.6"
  resolved "https://npm.bryntum.com/@bryntum%2fscheduler-trial/-/scheduler-trial-5.6.6.tgz#849e76a8645dd4b7dd1c385b131c9d8ba5a0e57c"
  integrity sha512-MB1KjO6GcdWKD+ofDa3I9sHrowVcHPrdDTyCSnovwNjF2Atgml3rd06rVlOMkDmo59L3BBrG7OpAdaYK14DG7Q==
  optionalDependencies:
    "@bryntum/scheduler-trial-lib" "1.0.0"

"@bryntum/schedulerpro-trial-lib@1.0.0":
  version "1.0.0"
  resolved "https://npm.bryntum.com/@bryntum%2fschedulerpro-trial-lib/-/schedulerpro-trial-lib-1.0.0.tgz#30ca9e980833150b4c5198136572290b023e070c"
  integrity sha512-MY7P4ZSIriG1l4BvnSgyxW0DFaqKqidF3HscfPVmzhBRVwZFnBohcq66ZyXePl4IxgZA2zy3viVkRg13VxOA2w==

"@bryntum/schedulerpro@npm:@bryntum/schedulerpro-trial@latest":
  version "5.6.6"
  resolved "https://npm.bryntum.com/@bryntum%2fschedulerpro-trial/-/schedulerpro-trial-5.6.6.tgz#7a018341e9304a2eba51fc117c81371e4db70cf1"
  integrity sha512-fCJAEYRR7leJhjE9GmaWiUKXFwMR6hDxo0TiYrlvje74auY5DHcf7L6j0BQea9bJW6780p8Is4543GTAxeJxGg==
  optionalDependencies:
    "@bryntum/schedulerpro-trial-lib" "1.0.0"

"@bryntum/taskboard-react@latest":
  version "5.6.8"
  resolved "https://npm.bryntum.com/@bryntum%2ftaskboard-react/-/taskboard-react-5.6.8.tgz#316f440c7bc23f0bd5215cb9e3da25e89f37f30c"
  integrity sha512-R4616FDBQpvGQf2rmSXpcxxlHXGkxD0AC0TOW+x0dAs0FmFEP6oWBko8O7DV6aOhVWy/Kh/X/FZ4JsD2k5IOCQ==

"@bryntum/taskboard-trial-lib@1.0.0":
  version "1.0.0"
  resolved "https://npm.bryntum.com/@bryntum%2ftaskboard-trial-lib/-/taskboard-trial-lib-1.0.0.tgz#589ef749506da2e28464b90a4dbe973a77b4d3ab"
  integrity sha512-VNX1QP+NAdpQcetiBIw8yUPC8dX6xWepQ0GSLg3wjN/0P+38KcQ/E6P4b3gezpukd3fDUdJfQQXk8/TS/aWakQ==

"@bryntum/taskboard@npm:@bryntum/taskboard-trial@latest":
  version "5.6.6"
  resolved "https://npm.bryntum.com/@bryntum%2ftaskboard-trial/-/taskboard-trial-5.6.6.tgz#073936d418e40e4b8fcb3c487564f2a8e4c8313c"
  integrity sha512-CubG9iomdqcm2YOEj/CoxVVC/Vj66/ecq5DkGfS8pl08gVcGzgCJP34LMX8ujhWvyHA9dbSz8wACnHCgxme0xw==
  optionalDependencies:
    "@bryntum/taskboard-trial-lib" "1.0.0"

**Comment by ghulamghousdev** [comment]
Hi @SaniMusic,

Welcome to Bryntum and we are glad to hear that you have liked our products. About your query, please open a forum thread here https://forum.bryntum.com/ as opening support tickets is only for the bryntum team. Tracking the issues on forums is pretty easier and organized.

**Comment by SergeyMaltsev** [comment]
Hi, @SaniMusic 

We have no trial versions of thin npm packages for now.
