### ISSUE TITLE
Error: Effect resolved to promise in the synchronous context, check that you marked the asynchronous calculations accordingly

### ISSUE THREAD

**Issue by minderm** [bryntum/support#8864]
Guys, hello!

In our project, we encountered a serious bug with the Gantt scheduler when manual scheduling was enabled for dependent tasks.
 
We were able to reproduce the bug in the examples on the site.

To reproduce the bug, you need to go to the example [https://bryntum.com/products/gantt/examples/criticalpaths/](https://bryntum.com/products/gantt/examples/criticalpaths/)

Further:
1. Turn off the checkbox for highlighting critical paths
2. Open the Run tests task, enable its Manually Scheduled checkbox
3. For the Configure ports task, set the start date to 01/14/2019
4. We get an error in the developer console
     Uncaught (in promise) Error: Effect resolved to promise in the synchronous context, check that you marked the asynchronous calculations accordingly
     at EngineTransaction.calculateTransitionsStackSync (gantt.module.js?474872:63:1348298)

![image](https://github.com/bryntum/support/assets/4593213/8388bbeb-87a0-4d04-9d2e-e7381945712f)

https://github.com/bryntum/support/assets/4593213/5c8cbcf3-938c-472b-b3bc-acec7ab18fa4

**Comment by matsbryntse** [comment]
Thanks for reporting, we'll take a look!

**Comment by canonic-epicure** [comment]
Targets "master"

**Comment by minderm** [comment]
> Targets "master" (6.0.0 if I'm correct)

Guys, is it possible to make a patch for version 5? We do not plan to update to version 6 in the near future.

**Comment by canonic-epicure** [comment]
Probably it is possible, will duplicate some effort, because of 6.0.0 refactoring, but not much, @matsbryntse?

**Comment by isglass** [comment]
Hi @minderm,

The PR with the fix for this issue contains significant changes that are not suitable to include in a patch release. We would not usually port it to older patches, but if it is a blocker for you we are open to discussing doing it as part of our Professional Services (https://bryntum.com/services)
