### ISSUE TITLE
[React] setting date in useState causes component to freeze

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8866]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=28418&start=10)

I have debugged and tried to reduce the test case to a problem. Now the problem occurs only when setting a date in useState variable upon click of a next day button. Although this date is not used anywhere but it still causes the issue. So upon commenting out this date part and trying setting a simple string variable didn't caused any issues. 

Steps to repro:
1. download the test case
2. install packages and run it:
```
npm install --legacy-peer-deps
npm run dev
```
3. Create an event and save and Click on next day button in topbar
4. create an event and save
5. Click on next day button again.
6. Component will freeze

test case:
[test-repo-2.zip](https://github.com/bryntum/support/files/14722522/test-repo-2.zip)

See the clip:

https://github.com/bryntum/support/assets/52177956/08639e46-bb4a-468f-b8fc-62c497a4ebea

**Comment by SergeyMaltsev** [comment]
Demo should wrap any configs passed to Bryntum components with `useState` if they are inside react app function.
E.g.
```
const [config] = useState<BrynmtumGanttConfig>({ // config here });
```
