### ISSUE TITLE
Nested Relation Field Does Not Call Custom Setter For Field

### ISSUE THREAD

**Issue by ubaidkhan7** [bryntum/support#8877]
Consider the following relation:

```
Contact:
   id
   name
EntityContact
   id
   contactId
```

Notice in the following Contact Model I have a custom setter for `name` field and whenver I need to set value to this field I would expect it to be done through my custom `name` setter function.
```js
class Contact extends Model {
    static get fields() {
       return [
         { name: "name", dataSource: "name" },
       ];
    }

    set name(val) {
       // performing some custom logic
       this.set("name", val);
    }

    get name(val) {
       return this.get("name");
    }
}
```

I've following relation defined in EntityContact model class
```js
class EntityContact extends Model {
    static relations = {
        contactRecord: {
          foreignKey: "contactId",
          foreignStore: "contactStore",
          relatedCollectionName: "entityContacts",
        }
     }
   
   // ... other fields definition not mentioned
}
```

The problem lies here when I try to set the nested field using the setter function of model expecting it that I would call my custom `name` setter function but it doesn't.
```js
entityContactStore.first.set("contactRecord.name", "XYZ")
```

**Comment by matsbryntse** [comment]
@ubaidkhan7 Please post this in our support forums, we do not monitor this repo for external general questions. https://forum.bryntum.com/
