### ISSUE TITLE
`fixedRowHeight` does not work properly for Print

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8894]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=26717&p=143238#p143238)

Tested here 
https://bryntum.com/products/gantt/examples/print/
With this code 
[sampleCode.zip](https://github.com/bryntum/support/files/14771048/sampleCode.zip)

Copy paste code, see all looks good, click Print. See printed preview has wrong row heights and event bars positioned not correct.

**Comment by bmblb** [comment]
Not reproducible on 6.1.3
