### ISSUE TITLE
Feature Request: Mixed eventLayout types

### ISSUE THREAD

**Issue by einmalick** [bryntum/support#8901]
Based on the layoutFn within eventLayouts, we aim to utilize varying eventLayout types per event. Mixing of "none" (overlapping) and "stack" event types should be achievable.

[Forum Post](https://forum.bryntum.com/viewtopic.php?p=143370#p143370)

To create a custom layout using the layoutFn that mimics the behavior of "type: stack" (but with alterations like custom height), we would need to reimplement the calculation of the events' positions and sizes. However, this is not currently possible, as indicated in the documentation:

- applyLayout(events, resource)
- layoutEventsInBands(events)

> This method should not be used directly, it is called by the Scheduler during the row rendering process.

Executing these functions with the provided data of the layoutFn results in a crash.

To summarize, what we are seeking is a method to incorporate mixed eventLayout types: 

```
new SchedulerPro({
    eventLayout: {
        layoutFn(items) {
            items.forEach(item => {
                if (item.someCondition) {
                    // This Item should not stack and overlap with other elements
                    // simplified mixed eventLayout for this item: 
                    return { type: "none" }
                } else {
                    // This item should stack with other items. We would need to calculate the height and top (for vertical width and left) attributes and also need to react on the other elements in this events band. (Which both is currently not possible).
                    // simplified mixed eventLayout for this item: 
                    return { type: "stack" }
                }
            });

        return this.scheduler.rowHeight;
    }
}
});
```

**Comment by isglass** [comment]
Hi,

This sounds really complicated to implement and is not something we currently plan on supporting. The `layoutFn` lets you take full control over the layout, you would have to implement the logic yourself in there. I am going to close this ticket, if it is something that is really important for your app and you want help coding it, I recommend reaching out to our Professional Services (https://bryntum.com/services) regarding hiring help for implementing it.

Scheduler Pro supports laying events out in multiple bands per resource (https://bryntum.com/products/schedulerpro/examples/custom-layouts/). Although each band uses the same layout. If allowing layout per band instead would help you, I recommend posting about that on the forum.
