### ISSUE TITLE
Filtering bug in VUE Calendar inline-data demo when using project model

### ISSUE THREAD

**Issue by rubiconsid** [bryntum/support#8903]
`Filtering `is not working in `Inline-data` demo 

Feedback from Nige from initial investigation: 

"A new eventStore avctually gets created, and when the Calendar has its eventStore set, it's a different evenStore from that set into the filter widget. But they both have reference the same project, So some code is recreating the eventStore"

https://bryntum.com/products/calendar/examples/frameworks/vue-3/javascript/inline-data/dist/

**Comment by ExtAnimal** [comment]
The correct fix is in `Sidebar.js`. Paste this in and the IDE should show the diff:

```
    updateEventStore(eventStore) {
        const { resourceFilter, datePicker, eventFilter } = this.widgetMap;

        if (eventFilter) {
            eventFilter.store = eventStore;
        }
        if (resourceFilter) {
            resourceFilter.eventStore = eventStore;
        }
        if (datePicker) {
            datePicker.eventStore = eventStore;
        }
    }
```

**Comment by rubiconsid** [comment]
After updating `sidebar.js ` , tried by using `project model ` in the demo and tried the filtering
 1. in ` vue js ` it works directly.
 2. in` vue 3 vite `, it still needs to do the following to make it work

```
onMounted(() => {
    const calendar = calendarRef.value.instance.value;
    const project = projectRef.value.instance.value;
    const filterWidget = calendar.widgetMap['eventFilter'];
    filterWidget.store = project.eventStore;
});

```
I will have another investigation with saki regarding this.

**Comment by rubiconsid** [comment]
I had a discussion with Krona and found out this issue can be resolved by using `shallowRef ` instead of `ref` if we want to store deeply nested object and prevent the side effect of deep conversion. 

```
const
    calendarConfig     = reactive(useCalendarConfig({ beforeEventDropFinalize, beforeEventResizeFinalize })),
    calendarRef           = ref(null),
    events                    = shallowRef(null),
    resources              = shallowRef(null),
    assignments          = shallowRef(null),
    timeRanges           = shallowRef(null),
    resourceTimeRanges = shallowRef(null);
```

more reference info: https://vuejs.org/api/reactivity-core.html
