### ISSUE TITLE
ResourceTimeRanges should support being recurring

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#891]
`ResourceTimeRangesStore` must include these mixins:

```
export default class ResourceTimeRangeStore extends AjaxStore.mixin(RecurringEventsMixin, EventStoreMixin) {
```

And ResourceTimeRangeModel must include these mixins:

```
export default class ResourceTimeRangeModel extends TimeSpan.mixin(RecurringTimeSpan) {
```

To inherit the machinery they need.

And the `ResourceTimeRanges` feature needs to expose its timespans through the `getEvents` interface of its store which will now exist. That interpolates any occurrences into the returned data.

But its API is wrong. It just exposes `resourceTimeRanges` as a property on its client Scheduler as a block of records.

So that caller which asks for that data has to change. It cannot just ask for a blob of every `ResourceTimeRange` that exists. It must include the _date range it is interested in_. So the interface must be a _method_, not a property.

Forum: https://www.bryntum.com/forum/viewtopic.php?p=81072#p81072

**Comment by arcady-zherdev** [comment]
Also need to check `TimeRanges` feature to make sure both features support recurrence and look consistent.

**Comment by arcady-zherdev** [comment]
The issue is still not resolved.

To sum up:
1. need to apply recurrence mixins to the feature store/model classes out of the box
2. need to check how TimeRanges feature code looks in that aspect to make sure the API is consistent
