### ISSUE TITLE
CalendarPanel nonWorkingDays to be independent of weekendDays

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8914]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=28540&p=143511#p143511)

"Dear Bryntum Team
I noticed that setting the 'disableWeekends' on a DatePicker doesn't strictly disable weekends only. It works off of the "nonWorkingDays" value instead, which can be any number of weekdays.

![2024-03-28_19-23-23.png](https://forum.bryntum.com/download/file.php?id=27650)

I propose to change the name of this property to 'disableNonWorkingDays', or if this is an unneccessary breaking change, simply update the description in the docs."

**Comment by ExtAnimal** [comment]
We should **add** a `disableNonWorkingDays` config.

The two concepts, weekends and non working days may be separate. 

This also means no breaking API changes.
