### ISSUE TITLE
Postamble does not handle DST transitions

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8921]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28550&p=143553#p143553)

Steps to repro:
1. Change timezone to Munich local time (in your OS settings)
2. Open the demo: https://bryntum.com/products/schedulerpro/examples/travel-time/
3. Create an event and set start and end date and time according to screenshot
4. Set postamble to 1 d
5. See that it takes one less hour

It looks like postamble adds an extra hour whenever an event falls on DST period. Is it expected behavior or something missing in the config? My expectation was that event though it is a DST day I still want postamble to end at midnight and not add an extra hour. You can reproduce it in your travel time examples. 

Please advise on best way to handle this.

Thank you
![Issue.jpg](https://forum.bryntum.com/download/file.php?id=27664)

**Comment by chiefanov** [comment]
Do you have a timeline for when this bug will be fixed?

**Comment by JockeLindberg** [comment]
> Do you have a timeline for when this bug will be fixed?

It will most likely be a part of the next release (no fixed date for that yet, but shouldn't be long).

**Comment by chiefanov** [comment]
> > Do you have a timeline for when this bug will be fixed?
> 
> It will most likely be a part of the next release (no fixed date for that yet, but shouldn't be long).

Thank you!
