### ISSUE TITLE
CrudManager sync does not clear changes for updated recurring event

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8927]
https://forum.bryntum.com/viewtopic.php?f=54&t=28524&p=143646#p143646

Steps to reproduce:

1. Create a daily recurring event on Monday
2. Shift the second occurrence (Tuesday) by one hour and set it for all future events
3. Observe the network traffic
4. Click somewhere else to trigger another action, like double clicking on the canvas to create a new event
5. Another sync request is triggered from step (2)

You can use this test case: 
[test (1).zip](https://github.com/bryntum/support/files/14834221/test.1.zip)

**Comment by chegix** [comment]
Greetings.

Are there any news on this issue?

**Comment by matsbryntse** [comment]
Not yet I'm afraid, we should get to this soon!

**Comment by matsbryntse** [comment]
Test pushed to `8927-recurrence`
