### ISSUE TITLE
Scrolling scheduler while dragging event makes dragged event go away from cursor

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#893]
https://www.bryntum.com/forum/viewtopic.php?f=44&t=11856
https://www.bryntum.com/forum/viewtopic.php?f=44&t=14668&p=74646

http://lh/bryntum-suite/scheduler/examples/bigdataset/
Start drag and event
While dragging start scrolling the page by "down" arrow or using mouse scroll wheel
See proxy element goes away from cursor position
![Запись активности на экране 2019-07-29 в 11 09 35](https://user-images.githubusercontent.com/57486733/84016596-2d5cf500-a986-11ea-8262-4df70d3275cd.gif)

Closed: https://app.assembla.com/spaces/bryntum/tickets/8971

@isglass comment was: Currently ScrollManager triggers scroll when you drag close to the edge, but it does not listen for scroll that happens for other reasons. Not sure if it should belong in ScrollManager or DragHelper

**Comment by agwidarsito** [comment]
Looking forward to the resolution on this one! :)
