### ISSUE TITLE
Input value first char gets deleted in combo

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8930]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28574&p=143679#p143679)

Steps to reproduce:
1. Go to https://bryntum.com/products/gantt/examples/basic/
2. Add this code:
```
features : {
        taskEdit : {
            items : {
                generalTab : {
                    items : {
                        resourcesField : {
                            type                 : 'combo',
                            name                 : 'installer',
                            minChars             : 3,
                            multiSelect          : true,
                            items                : ['New Event', 'New 1 Event'],
                            clearTextOnSelection : true
                        }
                    }
                }
            }
        }
    },
```
3. Input `New` and select an item
4. Now try to input any char and it will be deleted

Note: This issue is reproducible with combination of `multiSelect` true, `clearTextOnSelection` and `minChars` value greater than 1.

Clip: 

https://github.com/bryntum/support/assets/52177956/97def1e5-e08f-45b4-91e4-1444c0c710c9

**Comment by ExtAnimal** [comment]
It's not `clearTextOnSelection`. It's `clearTextOnPickerHide` that causes it.

Typing a character when the input length is < minChars hides the picker.

![Screenshot 2024-04-02 at 15 23 24](https://github.com/bryntum/support/assets/200516/5bffe6dc-4fa5-4c8c-b4f3-ad49589f1937)
