### ISSUE TITLE
[REACT] "segments is not iterable" error when setting manuallyScheduled = false

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8940]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28590&p=143763#p143763)

Steps to repro:
1. Download demo and install packages with `npm install`
2. Start server with `npm start`
3. Click `Enforce dependencies` and see the error

[Segment error 2.zip](https://github.com/bryntum/support/files/14854775/Segment.error.2.zip)

https://github.com/bryntum/support/assets/52177956/1f58fc35-c20e-4e2b-ba15-abc9044d5441

**Comment by ghulamghousdev** [comment]
It probably something has to do with setting `duration: 0` for milestones. Issue was not reproducible when `duration: null`

**Comment by canonic-epicure** [comment]
@ghulamghousdev Please try to reproduce with 5.6.9? We've recently fixed something similar: https://github.com/bryntum/support/issues/8346

**Comment by ghulamghousdev** [comment]
@canonic-epicure I have checked and yes the issue has been fixed and not reproducible. I have let the customer know. I am closing this ticket.

**Comment by ghulamghousdev** [comment]
Issue has been fixed here https://github.com/bryntum/support/issues/8346
