### ISSUE TITLE
Allow to display multiple baselines in multiple columns at same time

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8941]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=28593&p=143750#p143750)

"Hi Team,
[...]

B. We have multiple baselines in our data, how can we show columns for each baseline under "add new Column list".
Example: Advanced Demosite
https://bryntum.com/products/gantt/examples/advanced/
Please observe for task 1.2.3 "Select & review final design" we have multiple baselines data.
And under addnew column list we can see "Baseline Start" and "Baseline End" that will show data of first baseline.

How to show other baseline data as another columns from add new columns list.

```
"baselines"      : [
                  {
                    "startDate" : "2019-01-28T00:00:00",
                    "endDate"   : "2019-01-30T00:00:00"
                  },
                  {
                    "startDate" : "2019-01-29T00:00:00",
                    "endDate"   : "2019-01-31T00:00:00"
                  },
                  {
                    "startDate" : "2019-01-30T00:00:00",
                    "endDate"   : "2019-02-01T00:00:00"
                  }
                ]
```

![baselineMultipleColumn.png](https://forum.bryntum.com/download/file.php?id=27714)
"

The user is looking for a way to display multiple baseline start dates in the columns at the same time. Example:

A task has 2 baselines - B1 and B2 - we already have a way to show the multiple baselines in the graphic part of Gantt, but he wants to display them in the grid, and wants to show a column "Baseline 1 Start Date" and "Baseline 2 Start date" at the same time, containing the values of B1 and B2. 

https://bryntum.com/products/gantt/docs/api/Gantt/column/BaselineDurationColumn
https://bryntum.com/products/gantt/docs/api/Gantt/column/BaselineDurationVarianceColumn
https://bryntum.com/products/gantt/docs/api/Gantt/column/BaselineEndDateColumn
https://bryntum.com/products/gantt/docs/api/Gantt/column/BaselineEndVarianceColumn
https://bryntum.com/products/gantt/docs/api/Gantt/column/BaselineStartDateColumn
https://bryntum.com/products/gantt/docs/api/Gantt/column/BaselineStartVarianceColumn

**Comment by arcady-zherdev** [comment]
Can be done like this:
```js
const gantt = new Gantt({

    columns : [
        {
            type : 'addnew',
            processComboStoreConfig({ config, column }) {
                // Add new custom columns to the combobox
                config.data.push({
                    text  : 'Baseline 1 Start',
                    // column config
                    value : {
                        type  : 'baselinestartdate',
                        text  : 'Baseline 1 Start',
                        field : 'baselines[0].startDate'
                    }
                }, {
                    text  : 'Baseline 2 Start',
                    // column config
                    value : {
                        type  : 'baselinestartdate',
                        text  : 'Baseline 2 Start',
                        field : 'baselines[1].startDate'
                    }
                }, {
                    text  : 'Baseline 3 Start',
                    // column config
                    value : {
                        type  : 'baselinestartdate',
                        text  : 'Baseline 3 Start',
                        field : 'baselines[2].startDate'
                    }
                });
            }
        }
        ...
```
