### ISSUE TITLE
TabPanel not focusing when adding items dynamically

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8944]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=28612&p=143846#p143846)

"Hi!

When a TabPanel is create without any tab, and the tabs are appended by a button event, for sample, the new tab don't get the focus. The focus only works when you add more than one tab and click in this tabs.

The sample code and some print bellow:

```
import * as Module from 'https://bryntum.com/products/grid/build/grid.module.js';
Object.assign(window, Module);
// The code above imports module bundle and places all Bryntum classes on window to simplify coding at CodePen

let Panel = new Module.TabPanel({
   appendTo: document.body,
   height: '25em'
});

let Button = new Module.Button({
   appendTo: document.body,
   text: 'Button',
   onClick: () => {
         Panel.add({
            title : 'Tab with basic HTML',
            items : {
                infoWidget : {
                    type  : 'widget',
                    style : 'padding:1em',
                    html  : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
                }
            }
        });
   }
});


```

First tab withou focus:
![Screenshot_15.png](https://forum.bryntum.com/download/file.php?id=27739)

Second tab without focus too:
![Screenshot_1.png](https://forum.bryntum.com/download/file.php?id=27740)

After clicking the the created tabs, the focus work:
![Screenshot_2.png](https://forum.bryntum.com/download/file.php?id=27741)"

Modifying the demo in the documentation - https://bryntum.com/products/grid/docs/api/Core/widget/TabPanel - to match the example provided by the user, makes the behavior appear.

**Comment by henriquewerlang** [comment]
Any news about this?

**Comment by matsbryntse** [comment]
This is too opinionated for the core code, we cannot assume where focus should go. Your app code should call focus on the Element/Widget you'd like to see focused after the user gesture.

**Comment by henriquewerlang** [comment]
Even setting the focus in the widget, doesn't work any way.
`import * as Module from 'https://bryntum.com/products/grid/build/grid.module.js';
Object.assign(window, Module);
// The code above imports module bundle and places all Bryntum classes on window to simplify coding at CodePen

let Panel = new Module.TabPanel({
   appendTo: document.body,
   height: '25em'
});

let Button = new Module.Button({
   appendTo: document.body,
   text: 'Button',
   onClick: () => {
         let MyTab = Panel.add({
            title : 'Tab with basic HTML',
            items : {
                infoWidget : {
                    type  : 'widget',
                    style : 'padding:1em',
                    html  : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
                }
            }
        });
     
       MyTab.focus();
   }
});

`
