### ISSUE TITLE
Two commits initially, leads to two refreshes

### ISSUE THREAD

**Issue by isglass** [bryntum/support#8958]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=143954#p143954)

Reproducible on the advanced demo, put a breakpoint in finalizeCommitAsync. 
It is hit twice, first one is the "real" commit, second hit is all `isShadow()` and leads to not record changes.

But since we redraw before writing back to records, it still leads to a redraw.

**Comment by canonic-epicure** [comment]
These 4 are not `isShadow()`:
```
['ProjectModel.$.dispatcher', 'ProjectModel.$.earlyEffectiveEndDateInterval', 'ProjectModel.$.earlyEffectiveStartDateInterval', 'ProjectModel.$.nonEqual']
```
`nonEqual` is supposed to, not sure about others, checking
