### ISSUE TITLE
Calling crudmanager `sync` method causes `hasChanges` listener to fire

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8960]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28633&p=143961#p143961)

Upon initial investigation, `hasChanges` listener is being fired when resuming change tracking after data is ready and before sending request to the backend. It does not seems intentional. Creating this ticket to further investigate this issue.

**Comment by ghulamghousdev** [comment]
Another report here: https://forum.bryntum.com/viewtopic.php?p=155964#p155964

**Comment by atremel** [comment]
We just tested with 6.1.3 - we still have this error. Please advise.

**Comment by ghulamghousdev** [comment]
@atremel 

We are not able to reproduce this issue. I have explained the steps here. Would like your help in reproducing this issue. https://forum.bryntum.com/viewtopic.php?p=158346#p158346

**Comment by atremel** [comment]
I will check and reply. Please allow for a couple days of processing / producing a minimum reproduction code.
