### ISSUE TITLE
Not possible to reach submenu of timeAxisHeaderMenu unless moving over the anchor icon

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8988]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28702&p=144390#p144390)

Hi,

there is a slight different behaviour between the task context menu and the time axis header menu:
The submenus of the time axis menu disappear "easier/faster" than in the context menu.
Therefore it's sometimes hard to enter for example a date in the submenu of the Date Range menu because the submenu looses the focus and is closed.

Is this different behaviour because the sub-menu items of the time axis header menu are of type 'popup'?
If yes, is it necessary that they are of this type and how can I change it without having to override the whole menu?

Thanks in advance for any hints.

https://github.com/bryntum/support/assets/75997756/5d223b47-b1f6-4af5-be43-4833fb2e4844

**Comment by ExtAnimal** [comment]
This is the issue which @matsbryntse was looking at recently. It's just the `mouseout` listener firing. @matsbryntse is your branch still active?

The submenu is "connected" to the parent menu through the anchor element and if the mouse is moved through that, it works. It's a bad UX.

It should be on a timer which is cancelled when the mouse enters the submenu.
