### ISSUE TITLE
STM does not track state changes when data loaded through `readUrl`

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8994]
https://forum.bryntum.com/viewtopic.php?p=144449#p144449

Steps to reproduce:

1. Go to advanced demo https://bryntum.com/products/gantt/examples/advanced/
2. Add this config to app.js
```
    project : {
        stm : {
            autoRecord : true
        },

        validateResponse : true,
        taskStore        : {
            autoLoad : true,
            readUrl  : `http://localhost:3030/events`
        }
    },
```

3. Run the backend attached below (if you face cors error, change the origin accordingly in corsOptions in index.js in backend)
```
const corsOptions = {
  origin: "http://lh"
};
```
4. Make changes and see they are not tracked

[backend copy.zip](https://github.com/bryntum/support/files/14976526/backend.copy.zip)

https://github.com/bryntum/support/assets/52177956/7fb2c23f-c9e2-4591-8b00-dbe47fd167d9

**Comment by ghulamghousdev** [comment]
[+1 here](https://forum.bryntum.com/viewtopic.php?p=144679#p144679)

**Comment by canonic-epicure** [comment]
Probably the same reason - the stm is not enabled. It seems people think `autoRecord : true` enables it, but it does not.

**Comment by ghulamghousdev** [comment]
> Probably the same reason - the stm is not enabled. It seems people think `autoRecord : true` enables it, but it does not.

Probably then we need to update docs. Because explicitly enabling stm in the load event results in stm working correctly. Can't we integrate it somewhere in our code so when autoRecord is set on project level and upon loading taskStore we should enable the stm based on project level config?

**Comment by canonic-epicure** [comment]
Docs already mentioned that: https://bryntum.com/products/gantt/docs/api/Core/data/stm/StateTrackingManager

> Tracks the state of every store registered via [addStore](https://bryntum.com/products/gantt/docs/api/Core/data/stm/StateTrackingManager#function-addStore). 
> It is [disabled](https://bryntum.com/products/gantt/docs/api/Core/data/stm/StateTrackingManager#config-disabled) by default so remember to call [enable](https://bryntum.com/products/gantt/docs/api/Core/data/stm/StateTrackingManager#function-enable) when your stores are registered and initial dataset is loaded.
> 

In main examples that utilize stm (advanced/undoredo examples), the config for stm contains only `autoRecord: true`: 
https://github.com/bryntum/bryntum-suite/blob/release/Gantt/examples/advanced/app.js#L48
https://github.com/bryntum/bryntum-suite/blob/release/Gantt/examples/undoredo/app.js#L20

Over time this made people think, that it is all that is needed, however the actual stm enable happens in the "undo redo widget": https://github.com/bryntum/bryntum-suite/blob/release/Scheduler/lib/Scheduler/widget/UndoRedo.js#L150

I don't think we need to merge the configs, based on the slight co-notation of the `autoRecord` config name. Auto recording is just a setting the defines the stm recording mode, auto or manual.

We probably should emphasis the need to enable stm in the docs, mention, that if you use `UndoRedo` widget it will be enabled automatically on the project's `load` event (not on the task store `load` event), and also add comments in the advanced/undoredo examples, that `autoRecord` is not about enabling stm.

**Comment by canonic-epicure** [comment]
This is docs-only ticket, w/o changelog, closing it after merge.
