### ISSUE TITLE
`STM` buggy when used with `NestedEvents` feature

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8997]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28668&p=144356#p144356)

https://bryntum.com/products/schedulerpro/examples/nested-events-configuration/

Enable STM using config for ProjectModel
```
stm : { autoRecord : true }
```

Drag and drop event, call in console 
```
schedulerPro.project.stm.undo()
```

See: nothing happened.

Try to create new event using dnd. See error in console

<img width="1109" alt="Screenshot 2024-04-15 at 15 37 11" src="https://github.com/bryntum/support/assets/7203098/88a52002-7f67-4ab6-8c33-4e20b8615adf">

**Comment by canonic-epicure** [comment]
Prioritized by Mats request

**Comment by canonic-epicure** [comment]
Need to also explicitly enable stm, to make it work, just having `autoRecord : true` is not enough (see https://github.com/bryntum/support/issues/8994). Also can not reproduce the exception after undoing drag create. Probably these 2 were fixed.

I'll be checking also the test cases from user.
