### ISSUE TITLE
Printing Gantt with more then 3000 records causing application to Crash

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8998]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=28603&p=144507#p144507)

Steps to repro:
1. Go to gantt print demo https://bryntum.com/products/gantt/examples/print/
2. Run this in console: `for(let i = 0; i<3000; i++){gantt.taskStore.add({name: 'sss', startDate: gantt.taskStore.first.startDate, endDate: gantt.taskStore.getById(11).endDate})}`
3. Now click on print button and click on print in dialog
4. It will wait for generating response and page will eventually crash

<img width="1273" alt="Screenshot 2024-04-15 at 6 37 28 PM" src="https://github.com/bryntum/support/assets/52177956/623c4453-ccc0-4fc6-9600-aca5e8257f5d">

**Comment by ghulamghousdev** [comment]
The issue is also reproducible in calendar with 100 odd events. Might be the underlying issue is same for both the products.

https://github.com/user-attachments/assets/122751c5-8f62-4345-b376-a7417f196a96

**Comment by bmblb** [comment]
When printing large amount of data, one should be aware that a huge amount of HTML is generated. For 3k tasks it would be about 80 pages. It is a lot of elements and therefore a lot of memory is required (first we generate in memory, then we render on the page). Page does not crash on 3k tasks for me, but it takes significant time
