### ISSUE TITLE
Group title should not render into RowNumber column

### ISSUE THREAD

**Issue by isglass** [bryntum/support#9]
Try it on columntypes demo
<img width="274" alt="Screenshot 2019-11-13 at 07 55 42" src="https://user-images.githubusercontent.com/5415653/68740356-2d149b00-05eb-11ea-9cfe-b0a24a7e30e0.png">

**Comment by ExtAnimal** [comment]
The problem is that the group header row is rendered with cells. Maybe it should not be.

But if we do, then the cell into which the group feature renders the title should be marked with a special class which gets a high specificity rule which makes it `justify-content : start`

**Comment by isglass** [comment]
It should be rendered with cells, to allow contents for all columns in a group title. Added recently on request by clients and used in grouping demo.

**Comment by ExtAnimal** [comment]
I have fixed `group.scss` to have this 

```
.b-group-row {
    background : $grid-group-header-background-color;

    // no border-right in group headers
    .b-grid-cell {
        border-right-color : transparent;
    }

    .b-group-title {
        // TODO: Remove usage of left and right for alignment.
        // Use start and end to be LTR/RTL neutral.
        &.b-grid-cell-align-right, &.b-grid-cell-align-end {
            justify-content : flex-end;
        }

        &.b-grid-cell-align-center {
            justify-content : start; //<====== This was changed from an invalid value
        }
    }
}
```

**Comment by ExtAnimal** [comment]
This will be needed if the cell that *happens* to be the recipient of the title is too narrow. But if it's wide, then maybe it should be aligned as the cell is configured to be. It's just not valid to use some random cell to chuck the title into.

This is a difficult problem.
