### ISSUE TITLE
Badge should not be shown for 0 string

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#90]
https://www.bryntum.com/examples/grid/transaction/

<img width="649" alt="Screenshot 2019-12-16 at 15 29 50" src="https://user-images.githubusercontent.com/218570/70914768-ed413900-2018-11ea-8a27-a5a4e1feda87.png">

**Comment by isglass** [comment]
Add `showZero` config to badge. Off by default, on in for example our search fields

**Comment by matsbryntse** [comment]
Not reproducible
