### ISSUE TITLE
HTML rendering in 5.6.9 stopped working

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9003]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28734&p=144562#p144562)

"Hello, I'm using scheduler pro 5.6.7 and I have a column config like this: 

 
```
columns: [
      {
        autoHeight: false,
        type: 'resourceInfo',
        field: 'name',
        showEventCount: false,
        width: 220,
        cellCls: my-class',
        editor: false,
        renderer: (props) => {
          const resource = props.record as SchedulerResourceModel
          return `<div class='my-class-name'>${getResourceNameHTML(resource)}<div/>`
        },
      },]
``` 

my getResourceNameHTML function also returns a html string.

That was working fine. After upgrading to 5.6.9 now I need to set htmlEncode to false to make this work, but I want this to be XSS safe. 

I tried to use StringHelper.xss / StringHelper.encodeHtml but it is always displayed as a string and not as HTML."

You can add a column similar to the user provided to the Scheduler pro demo and you'll have a result like the screenshot
```
{
        autoHeight: false,
        type: 'resourceInfo',
        field: 'name',
        showEventCount: false,
        width: 220,
        cellCls: 'my-class',
        editor: false,
        renderer: (props) => {
          const getResourceNameHTML = (resource) => {return `<div>${resource.name}</div>`};

          const resource = props.record;
          return StringHelper.xss(`<div class='my-class-name'>${getResourceNameHTML(resource)}<div/>`)
        },
      }
```

![Screenshot 2024-04-15 at 18 35 11](https://github.com/bryntum/support/assets/16693227/c34605cf-4bfd-45de-b93f-0bdd983ff4f5)

**Comment by isglass** [comment]
This was working "by luck" previously, the `renderer` is private on the ResourceInfoColumn - and thus not meant to be overridden. We will discuss in the team if we should take any action

**Comment by isglass** [comment]
Suggested another approach in the forum thread, closing this as it was not meant to work
