### ISSUE TITLE
Ability to hide/show row lines

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9008]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28740&p=144591#p144591)

Hi everyone,

We have a feature in bryntum gantt to show/hide column Line
![Screenshot 2024-04-16 at 2.51.17 PM.png](https://forum.bryntum.com/download/file.php?id=27948)

I want a feature to show/hide row lines.
![Screenshot 2024-04-16 at 2.51.17 PM.png](https://forum.bryntum.com/download/file.php?id=27948)

**Comment by matsbryntse** [comment]
Easy to implement in app code
