### ISSUE TITLE
Allow to use custom content when Gantt is empty

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9016]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=28750&p=144659#p144659)

"Hi Bryntum team,

How can we display some content (with custom react html) inside the Gantt / Scheduler body in those two situations:

loading (events / tasks loading)
no elements loaded: placeholder saying (this gantt is empty)
![Screenshot 2024-04-16 at 17.39.02.png](https://forum.bryntum.com/download/file.php?id=27968)
![Screenshot 2024-04-16 at 17.39.11.png](https://forum.bryntum.com/download/file.php?id=27967)"

**Comment by marciogurka** [comment]
[https://bryntum.com/products/gantt/docs/api/Grid/view/GridBase#config-emptyText](https://bryntum.com/products/gantt/docs/api/Grid/view/GridBase#config-emptyText) allows adding DOMConfig or HTML, which the user can add custom content

**Comment by Aarbel** [comment]
@marciogurka this is for grid and for bryntum, no ?
