### ISSUE TITLE
calendar.createEvent with empty date triggers an error

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9025]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=28770&p=144762#p144762)

"Hi guys, thank you for this amazing product.

I'm trying to do some programatic event creation when App.vue mounted, something like 

```
onMounted() {
	const calendarInstance = calendar.value.instance.value as Calendar;
	calendarInstance.createEvent();
}
```

But I'm getting 

```
Uncaught (in promise) TypeError: Cannot destructure property 'isRectangle' of 'element' as it is null.
```

Default view is month, after getting the error and moving to another view and doing window.calendar.createEvent() im not getting that error in that view, but when coming back to default (month) still getting the error.

You can even reproduce this error in https://bryntum.com/products/calendar/examples/print/. Open the browser inspector tools -> Console tab -> do window.calendar.createEvent()."

According to the [documentation](https://bryntum.com/products/calendar/docs/api/Calendar/view/Calendar#function-createEvent) it should be possible to create an event without providing a date.

**Comment by dennzimm** [comment]
Hi, I have the same problem, but with Angular. Unfortunately, I also get this error when I enter a date 🤔
