### ISSUE TITLE
Should not trigger a sync when ajaxStore is configured with a URL and `syncDataOnLoad: true`

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9030]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=144744#p144744)

Steps to repro:
1. Run the test case by running `./run.sh`
2. Choose default editor
3. Add an event
4. click on set date
5. click on load button
6. See in network tab that an api request is being triggered to sync the changes with backend

Note(Joakim):
`syncDataOnLoad` is built for `framework non-ajax stores`. I agree that changes made from the "syncing" process shouldn't create any record changes meta data, nor any server sync requests. But, I guess there is another way of looking at it, and that is that you modify your `"bound-by-framework"` data outside of our environment, but still somehow use our records/stores to keep track of what's changed. Maybe it would be able to activate `syncDataOnLoad`, but without creating any record changes meta and not triggering any sync request.

[syncDataOnLoad.zip](https://github.com/bryntum/support/files/15039593/syncDataOnLoad.zip)

**Comment by bmblb** [comment]
Bug has returned, here is an updated test case
[extra-put.zip](https://github.com/user-attachments/files/15929238/extra-put.zip)
