### ISSUE TITLE
Scroll over components in Firefox when using Material theme

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9047]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28807&p=144991#p144991)

When the browser has small heights, and the suite uses the Material theme, the scroll appears over the content of the task editor.

![Screenshot 2024-04-24 123810](https://github.com/bryntum/support/assets/16693227/a40b310f-a008-4daf-ac7a-c36d3d8da250)

https://github.com/bryntum/support/assets/16693227/d6300f62-cf51-4b33-ae4a-567e0d03885f

**Comment by isglass** [comment]
Does not look like a bug too me, it is how overlaid scrollbars work natively. When you are not scrolling, you can interact with whatever is below it. When you are scrolling, the scrollbar overlays the content and the content cant be reached until scrolling stops

**Comment by isglass** [comment]
Will close this as it is the expected behavior. If it is undesired in an app, you could add some padding to reserve space for the scrollbar when shown. We detect that content overflow and add the `.b-vertical-overflow` class, could base padding on presence of it
