### ISSUE TITLE
BryntumTimeline feature prop binding not working

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9056]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28824&p=145086#p145086)

"Hello,

we've noticed that right now it's not possible to use React feature prop binding with the BryntumTimeline component.

Code like this doesn't work as expected, the feature is not bound. 

```
		<BryntumTimeline
			eventTooltipFeature={{
				template: function (data) {
                                        ....
                                 }
                        }}
                 />
```

I checked gantt-react\lib\BryntumTimeline.js and it's missing the "featureNames".

Manually adding it in our own code before using the BryntumTimeline component like so works and the prop feature binding is now working as expected:

```
BryntumTimeline.featureNames = ['eventTooltipFeature'];
```
"

**Comment by SergeyMaltsev** [comment]
Not reproducible in Bryntum suite `6.1.0`
![image](https://github.com/user-attachments/assets/1a01a543-3f6e-41ea-9f32-8b5a1a3fe86c)

From wrapper source
```
   export type BryntumTimelineProps = {
...
 /**
     * Displays a tooltip when hovering events. The template used to render the tooltip can be customized, see [template](https://bryntum.com/products/gantt/docs/api/Scheduler/feature/EventTooltip#config-template).
     * Config options are also applied to the tooltip shown, see [Tooltip](https://bryntum.com/products/gantt/docs/api/Core/widget/Tooltip) for available options.
     * ...
     * [View online docs...](https://bryntum.com/products/gantt/docs/api/Scheduler/feature/EventTooltip)
     */
    eventTooltipFeature? : object|boolean|string|EventTooltip|EventTooltipConfig
```
