### ISSUE TITLE
eventLayout layoutFn in vertical mode is not calculating event positions correctly.

### ISSUE THREAD

**Issue by einmalick** [bryntum/support#9074]
[Forum Post](https://forum.bryntum.com/viewtopic.php?t=28861)

While it functions correctly in horizontal mode, transitioning to vertical mode introduces issues with event positioning and dragging behavior. 

I'd expect the layoutFn to work in vertical and horizontal mode:

For vertical mode:
Should set left and width for every provided data item (top and height are calculated according to the event start date and duration). The function should return the total column widthin pixels.

edit: 
Setting left should set the position inside the events resource column.

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/9078
