### ISSUE TITLE
Grouping AssignmentGrid doesn't work

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9088]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28881&p=145338#p145338)

Reproducible here in the demo https://bryntum.com/products/gantt/docs/api/Gantt/widget/AssignmentGrid
![image](https://github.com/bryntum/support/assets/75997756/b524584c-d627-4bf4-b4df-efc8ababfd48)

**Comment by matsbryntse** [comment]
Grouping is disabled in the grid, just enable with:
```

features : {
                group       : true,
                filterBar   : true,
                contextMenu : false
            },

```
