### ISSUE TITLE
Not possible to specify features in defaultConfig in Gantt

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#909]
Reproduced in Release and Master.
Works in Scheduler though.

http://lh/bryntum-suite/gantt/examples/basic/
```
class MyGantt extends Gantt {
    static get defaultConfig() {
        return {
            features : {
                taskEdit : false
            }
        };
    }
}
new MyGantt({
    // features : {
    //     taskEdit : false
    // },
```
Double click a task, see task editor is shown.
Uncomment the features config passing to the MyGantt constructor.
Double click a task, see nothing happens.

**Comment by matsbryntse** [comment]
Not reproducible
