### ISSUE TITLE
Grid Column ignores field's set value when field is localized

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#9091]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=28899)

The localization pulls in the `defaultValue` as the `localeKey`, so the value from the locale file is always used instead of the *configured* value.

**Comment by ExtAnimal** [comment]
This is the fix which allows it to work. `Localizable.js`:

<img width="1017" alt="Screenshot 2024-05-02 at 08 02 32" src="https://github.com/bryntum/support/assets/200516/d41f2ba8-46b0-4fb4-9742-a65ffb358521">

**Comment by ghulamghousdev** [comment]
+1 for this from a different client https://forum.bryntum.com/viewtopic.php?p=145908#p145908
