### ISSUE TITLE
Collapsible panels not working in Ext JS Modern demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#91]
Triggered by simply having our script on the page. Collapse a panel and notice Ext JS doesn't finalize the animation. 

`<script src="../../build/scheduler.umd.js"></script>`

Related to Tooltip, this fixes it:
`bryntum.get('bryntum-tooltip').destroy()`

Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=12600&p=66197#p66197

UPDATE:
as a solution need to turn off animation + remove ext-list class
<pre><code>
            // cls       : 'ext-list',
            collapsible: {
                direction: 'left',
                animation : false
            },
</code></pre>

examples/extjsmodern/App/view/Main.js
<pre><code>
    items  : [
        {
            xtype     : 'panel',
            title     : 'Ext JS Modern List',
            collapsible : 'left',
</code></pre>
http://lh/bryntum-suite/scheduler/examples/extjsmodern/

**Comment by dongryphon** [comment]
I am able to reproduce this. Looking into it.

**Comment by dongryphon** [comment]
The problem is caused by `Ext.dom.Element.prototype.eventMap`:

    {
        // ...
        transitionend: 'webkitTransitionEnd',
        animationstart: 'webkitAnimationStart',
        animationend: 'webkitAnimationEnd'
    }

In particular `transitionend`, but I suspect the others will fall into the same case. Rumor [had it](https://stackoverflow.com/questions/18106612/enabling-vendor-prefixes-in-css-transitions-make-callback-fires-twice) that both of these events would fire so you had to pick just one (not both). In Chrome 79 at least this is no longer true.

As mentioned, destroying the Tooltip singleton from Core allows Ext JS animations to complete properly. But this is enough to break them again:

    ote = e => { console.log('transitionend', e); };
    window.addEventListener('transitionend', ote);

**Comment by dongryphon** [comment]
I believe we could address this by removing those 3 items from the `eventMap` but I'm not sure the right place to do such things.

Fortunately, if we do this even reasonably early, it should be fine. The listener is not added until first requested. In the Scheduler demo that was delayed until the MessageBox was being closed.

**Comment by dongryphon** [comment]
In my PR (https://github.com/bryntum/bryntum-suite/pull/358) I added a Sencha package (`bryntum-extjs-compat`) to do the needful.

**Comment by dongryphon** [comment]
PR based on `release` branch https://github.com/bryntum/bryntum-suite/pull/375

Ignore https://github.com/bryntum/bryntum-suite/pull/358

**Comment by dongryphon** [comment]
This override fixes the problem (from https://github.com/bryntum/bryntum-suite/pull/529):
```
Ext.define('Bryntum.Compat', {
    override : 'Ext.dom.Element'
},
function(Element) {
    var eventMap = Element.prototype.eventMap;

    if (eventMap) {
        // Since 5.1.0, Ext JS has preferred webkit* vendor prefix for these. In the
        // past both webkitTransitionEnd and the standard transitionend event would be
        // fired, but in Chrome 79 (though the change was likely earlier), this is no
        // longer true. Since Bryntum Core requires the standard event, it is fair to
        // simply remove these from the mapping used by Ext JS (it will then use the
        // standard events as well):
        delete eventMap.transitionend;
        delete eventMap.animationstart;
        delete eventMap.animationend;
    }
});
```
