### ISSUE TITLE
Scheduler crashes sometimes when event is hovered

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9112]
1. Go to `/Scheduler/examples/infinite-scroll/` on FireFox (not demo-specific)
2. Drag an event
3. See below error in console

<img width="986" alt="Screenshot 2024-05-03 at 11 24 45 AM" src="https://github.com/bryntum/support/assets/52177956/deea7abf-336e-4c8e-82c9-c09dd1a8c5c0">

**Comment by JockeLindberg** [comment]
PdfExport is not supported. Making this a feature request instead.

Should probably add some page limiting capabilities to the export/print dialogs.
