### ISSUE TITLE
Infinite-scroll backend runs out of memory

### ISSUE THREAD

**Issue by isglass** [bryntum/support#9117]
http://localhost/bryntum-suite/SchedulerPro/examples/infinite-scroll-crudmanager/

Reproduced in Chrome & Safari, scroll horizontally until it happens

<img width="1274" alt="Screenshot 2024-05-03 at 09 34 29" src="https://github.com/bryntum/support/assets/5415653/9e7dc401-6a3c-4202-9ceb-e3dee948e933">

Looks like it runs out of memory, noticed this in the response:

```{"eventId":81128,"resourceId":100,"id":81128}]},"success":true,"requestId":171472172815219}<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 19337216 bytes) in <b>Unknown</b> on line <b>0</b><br />```

**Comment by JockeLindberg** [comment]
Also Scheduler (https://github.com/bryntum/support/issues/9114)
