### ISSUE TITLE
Rendering input in taskRenderer is not focusable

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9135]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28898&p=145558#p145558)

Reproducible https://bryntum.com/products/gantt/examples/basic/ 

With this code
```javascript
    taskRenderer({ taskRecord }) {
        if (taskRecord.isLeaf && !taskRecord.isMilestone) {
            return `<input type="text" />`;
        }
    }
```

And now when you click on the input field you'll see that the input is not getting into focus

**Comment by matsbryntse** [comment]
https://youtu.be/xm5k1EsmDcs
