### ISSUE TITLE
`startDate` is overridden upon editing other fields of an event in eventEdit

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9143]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=28959&p=145797#p145797)

Steps to repro:
1. Go to https://bryntum.com/products/calendar/examples/basic/
2. Disable startDateField and endDateField in eventEdit: `eventEdit : { items : { startDateField : null, endDateField : null}},`
3. Now edit a event `Team Scrum` and change its name and same.
4. Now edit an other event `Excursion` and save
5. See the startDate of event `Excursion` is overridden.

https://github.com/bryntum/support/assets/52177956/d73c6a7e-8e28-4354-9497-92bbcb2ce77d

**Comment by ExtAnimal** [comment]
This logic is at the Scheduler level, in the base `EventEdit` feature.
