### ISSUE TITLE
Column `autoHeight` doesn't work with Gantt

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9145]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28908&p=145839#p145839)

Reproducible here https://bryntum.com/products/gantt/examples/basic/
add `autoHeight:true` to the column
and now paste a long text to the name column's cell
![image](https://github.com/bryntum/support/assets/75997756/946f8edd-bde2-4f67-aca7-4fdc6bc26e8b)

It's working in 5.5.3
From User:

> If you mean, it never worked.
> 
> then, why it is showing on 5.5.3
> I tried again and you can see in the image that right side of timeline is also taking autoHeight.
> 
> ![Screenshot from 2024-05-08 12-13-25.png](https://forum.bryntum.com/download/file.php?id=28295)
> 
> If it was never intended to work, then why its showing properly here?

**Comment by matsbryntse** [comment]
autoHeight is not supported for the Gantt as it uses fixed row height
