### ISSUE TITLE
TabPanel should have Panel's functionality

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#915]
Since TabPanel has "Panel" in the name, I assume it has all the features a Panel has. But it's not, since it extends a Container.

Usecase is when you need to add a tbar or bbar to a TabPanel you have to additionally wrap it into a Panel.

Panel is deeply involved into theming. So additional work might be required to check how TabPanel looks in all our themes.

Or simply rename TabPanel to TabContainer

**Comment by isglass** [comment]
Closed as duplicate of #1837
