### ISSUE TITLE
[REACT] Bug with Recurring Events + Timezones

### ISSUE THREAD

**Issue by khattakdev** [bryntum/support#9150]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28972&p=145886#p145886)

Hi Bryntum team,

There's a serious bug with how recurring events + schedule time zones are behaving right now (version 5.6.10)

Steps to reproduce:

Set Bryntum calendar timezone to America/New_York

Go to March 9th, 2024 (EST - Before Daylight Savings in USA)
2b. Add an Event A for 6AM EST ("2024-03-09T11:00:00.000Z")that recurs daily
(DTSTART;TZID=America/New_York:20240310T060000;FREQ=DAILY;INTERVAL=1;WKST=MO)

Go to March 10th, 2024 (EDT - During Daylight Savings in USA)
3b. Add an Event B for 6AM EDT ("2024-03-10T10:00:00.000Z") that recurs daily
(DTSTART;TZID=America/New_York:20240310T060000;FREQ=DAILY;INTERVAL=1;WKST=MO)

Go to May 8th, 2024
CORRECT: Observe Event A (Expected 6 AM, Actual 6AM) 
CORRECT: Observe Event B (Expected 6AM, Actual 6AM)

Set Bryntum calendar timezone to Europe/London
CORRECT: Observe Event A (Expected 11 AM, Actual 11AM) 
WRONG: Observe Event B (Expected 11AM, Actual 10AM)

I think it's a pretty serious bug that the calendar is doing timezone conversion incorrectly. Two events on May 8th that show up at 11AM EDT is showing up as different times in BST, when it should be the same time.
https://www.worldtimebuddy.com/?qm=1&lid=5128581,2643743&h=5128581&date=2024-5-8&sln=6-7&hf=1

Please advise on workarounds to fix this issue.

---

**Note:** It's acting different in different timezones. For example, for Asia/Karachi_, Event A is 4PM, but it should be 3PM

**Comment by kellywu** [comment]
hey team, any update on when you all may tackle this?

**Comment by matsbryntse** [comment]
We'll try to address this in the 6.0.5 release

**Comment by JockeLindberg** [comment]
I've updated the forum thread with a request for confirmation

**Comment by kellywu** [comment]
thanks @matsbryntse , i see it's moved from 6.0.5 to 7. what would the ETA for that be?

incorrect timezone conversions is pretty critically impacting the usability of the calendar for us

i've tried patching it in getOccurrencesForDateRange but this causes performance issues for us

**Comment by matsbryntse** [comment]
Hi Kelly, we have a fix that's being reviewed - depends how the review / tests are looking. We'll try hard to get this out in the next few weeks.

**Comment by kellywu** [comment]
awesome, thank you for the update.

quick question, this issue also affects ResourceTimeRanges - will that also be fixed as part of this?

**Comment by JockeLindberg** [comment]
@kellywu Thanks for pointing this out. It should, but it does not work. We will fix this in another ticket: https://github.com/bryntum/support/issues/9737
