### ISSUE TITLE
New events disappear when changing date

### ISSUE THREAD

**Issue by khattakdev** [bryntum/support#9151]
- Add a recurring event
- Change the date
- Event is disappeared

Happening only in https://bryntum.com/products/calendar/examples/timezone/

https://github.com/bryntum/support/assets/37709578/e7cd0086-26b9-4940-913d-48fba9c83507

**Comment by JockeLindberg** [comment]
It is not as bad as it might appear. The demo reloads all data when requesting a new date range.
