### ISSUE TITLE
Filtering does not work correctly in the chained store

### ISSUE THREAD

**Issue by khattakdev** [bryntum/support#9171]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=146075#p146075)

https://github.com/bryntum/support/assets/37709578/28b2a63b-0550-4b9b-8e84-b374629c221b

**Comment by khattakdev** [comment]
Based on **Nige's**  explanation and `makeChained` functionality
```
            tree           : false,
            autoTree       : false,
```

The tree store becomes a non-tree when it is chained, hence the first issue is not an issue.

**Comment by isglass** [comment]
Will be fixed by using the new `chainTree` API
