### ISSUE TITLE
`contextMenuTriggerEvent: 'click'` does not work for calendar

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9185]
Set `contextMenuTriggerEvent: 'click'` on basic calendar example and right click on empty space in calendar.

https://github.com/bryntum/support/assets/52177956/571f0932-a3a6-4342-94b2-c4685e71f24f

**Comment by ExtAnimal** [comment]
Calendar's `SchedulerInterface.js` needs this:

```
eventNameSplitter = /(click|touch|mouse|pointer|key|context|dbl)(.*)/,
```

Then

```
features : {
    scheduleMenu : {
            triggerEvent : 'click'
    }
}
```

Will work. But the docs in `ContextMenuBase#config-triggerEvent` become invalid at the `Calendar` level. The docs for `triggerEvent` will have to be overridden in the Calendar's `ScheduleMenu.js` and `EventMenu.js` (Both of which have `ContextMenuBase` as their base class) to illustrate the above, that it's a config **on the feature itself**.
