### ISSUE TITLE
Exception thrown when syncing segmented events data and `useRawData` is enabled

### ISSUE THREAD

**Issue by canonic-epicure** [bryntum/support#9189]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=29039)

https://github.com/bryntum/support/assets/72431/aa55b33a-5830-41ee-942a-77a5db223c2f

Reproducible with:
[scheduler-bugs-4.zip](https://github.com/bryntum/support/files/15315999/scheduler-bugs-4.zip)

**Comment by isglass** [comment]
After initial set, syncDataOnLoad should ensure it does not come through that code path (setStoreData) - part of the issue seems to be that `syncDataOnLoad: true` gets lost somehow - separate ticket opened https://github.com/bryntum/support/issues/9203

**Comment by isglass** [comment]
With syncDataOnLoad set to `true` and other changes in 5.6.11 this is working for me. Will keep ticket open until it is relased a client has a chance to try

**Comment by isglass** [comment]
Client reports it seems to work now, will close ticket
