### ISSUE TITLE
Trial expired for Gantt Component in Salesforce showcase demo

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9220]
Go to this link https://bryntum-dev-ed.develop.lightning.force.com/lightning/n/BryntumGantt and check for Gantt Tab. No data is loaded and trial expired dialog is being shown.

![image](https://github.com/bryntum/support/assets/52177956/cf783f79-9eef-499f-a713-2fc072ae67d9)

**Comment by bmblb** [comment]
There is an internal ticket to solve this problem. Our public org correctly checks trial expiration now.
