### ISSUE TITLE
Evaluate editor height on every show

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9227]
[Forum Post](https://forum.bryntum.com/viewtopic.php?p=143768#p143768)

Words from @ExtAnimal:

> He’s hiding and showing components in there. So the potential height of the tabs changes.
So that max height that is needed to make it NOT change height as tabs are changed will need to be recalculated.

**Comment by ExtAnimal** [comment]
`TabPanel.js` needs

```
    onContentElMutation() {
        // When any content changes, then upon next show, applyAutoHeight must be called again 
        this.$measureHeight = true;
        super.onContentElMutation(...arguments);
    }
```
