### ISSUE TITLE
Time ranges are not correctly in `rtl` mode

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9249]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=29157&p=147058#p147058)

See attached image

Go to demo https://bryntum.com/products/scheduler/examples/timeranges/ and set rtl mode to true. Then zoom in and out and see the time ranges are not correctly displayed.

https://github.com/bryntum/support/assets/52177956/67edf148-be44-412d-b5b2-a0471ae294d9

![Screenshot 2024-05-24 123138.png](https://forum.bryntum.com/download/file.php?id=28590)

**Comment by matsbryntse** [comment]
Fixed in 6.0 branch already
