### ISSUE TITLE
Incorrect position of menu on clicking settings icon in agenda mode

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9255]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=29186&p=147168#p147168)

Clicking on the settings icon in agenda mode not showing the menu at the right place:

https://github.com/bryntum/support/assets/52177956/770418ae-8e15-4e31-92ea-8800b8297952

**Comment by JockeLindberg** [comment]
Reproducible in 5.68, but not in 5.6.11. Closing.
