### ISSUE TITLE
Angular: Scheduler pro non-umd import does not work.

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#927]
When the `module` (default) version of built SchedulerPro is imported then the app doesn't work.

Steps to reproduce:
1. unzip the attached file into `SchedulerPro/examples/frameworks/angular` (create the directory if it does not exist) 
[no-wrapper.zip](https://github.com/bryntum/bryntum-suite/files/4764615/no-wrapper.zip)

2. in `no-wrapper/src/app/app.component.ts` uncomment the non-umd (and comment the umd) import
3. run
```
npm i
npm start
```
4. navigate to `localhost:4200` and watch the browser console
<img width="1132" alt="Screen Shot 2020-06-11 at 14 00 57" src="https://user-images.githubusercontent.com/204844/84383260-3f3fd180-abec-11ea-86c0-205a2c8c101a.png">

**Comment by jsakalos** [comment]
Additional info:
The execution breaks (in the case of module) in `lib/Engine/calendar/CalendarCache.js`:
```
forEachAvailabilityInterval(options, func, scope) {
    var _a;

    scope = scope || this;
    const startDate = options.startDate;
    const endDate = options.endDate;
    const startDateN = startDate && startDate.getTime();
    const endDateN = endDate && endDate.getTime(); // <=== endDate is a Promise
```
because `endDate` is a `Promise` at the time of execution

**Comment by jsakalos** [comment]
I have re-tested it and it works with our wrapper but not without it (using the above no-wrapper.zip test case). However, it is not crucial for 4.0.0 release because our standard solution is to use the new bundle `schedulerpro.lite.umd.js`.

I suggest to change milestone to 4.1+ after we will implement `npm` solution.

**Comment by isglass** [comment]
We soon drop IE11, at which point we will try to drop umd completely
