### ISSUE TITLE
Changing duration of a task shouldn't end the task on non-working day

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9282]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=29027&p=147476#p147476)

Just to make you recollect, on this ticket, basically our goal is simple we don't want user to have weekends date(sat and sun) selected directly or indirectly.

I can see these cases are working fine in Advanced Demo app.
I am finding difficult to understand what we have missed in our app.

Hence I am sharing a sample app, to seek your assistance here, please.

Steps to reproduce:

1. Go to gantt basic demo and add this code: 
```
import '../_shared/shared.js'; // not required, our example styling etc.
import Gantt from '../../lib/Gantt/view/Gantt.js';
import StringHelper from '../../lib/Core/helper/StringHelper.js';
import StartDateColumn from '../../lib/Gantt/column/StartDateColumn.js'
import EndDateColumn from '../../lib/Gantt/column/EndDateColumn.js'

new Gantt({
    appendTo          : 'container',
    dependencyIdField : 'sequenceNumber',
    rowHeight         : 45,
    tickSize          : 45,
    barMargin         : 8,
    project           : {
        autoLoad  : true,
        transport : {
            load : {
                url : '../_datasets/launch-saas.json'
            }
        }
    },

    columns : [
        {
            type   : 'startdate',
            editor : {
                picker : {
                    disableWeekends : true
                }
            }
        },
        {
            type   : 'enddate',
            editor : {
                picker : {
                    disableWeekends : true
                }
            }
        }
    ],
});
```
2. Change of duration to Config Firewall to 5 days
3. See the end date of the task is on a non-working day

Expected Result:
Case1: After adding duration date should jump to before or after non-working day.

<img width="1374" alt="Screenshot 2024-06-03 at 11 19 41 AM" src="https://github.com/bryntum/support/assets/52177956/508e7a8d-2985-41c4-9257-a2d8c99da60c">

Thanks,
Shashank Yadav
Hatch Digital

**Comment by ghulamghousdev** [comment]
+1 here https://forum.bryntum.com/viewtopic.php?p=153570#p153570

**Comment by shivarajnaidu** [comment]
is there any plan or timeline to release fix for this in 5.x or in any other version of bryntum ?

**Comment by canonic-epicure** [comment]
This is misunderstanding, everything works as expected. 

Our end date is a point on the time axis, not a section of it. So the end date of Jan 19, 2019 (Saturday) actually means the midnight: Jan 19, 2019 00:00:00, so the task ends on midnight between the Friday and Saturday and it does not last during the weekend.

This is reflected on the timeaxis part of the gantt:
![image](https://github.com/user-attachments/assets/c552ce88-5b10-4ccb-8bdc-9133187a032f)


It seems the expectation is that specifying lets say 2024/01/06 in the field will set the end date to: 2024/01/06 24:00 === 2024/01/07. However this is not how it works currently. We had this behavior configurable in ExtJS version, however it lead to various incosistencies: https://www.bryntum.com/products/gantt-for-extjs/docs/#!/guide/gantt_disable_enddate_adjustment

So it was disabled by default in ExtJS Gantt 6.0.0 and removed completely in the current version.
