### ISSUE TITLE
Time selection demo broken

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9293]
Filtering out resources is not working

http://lh/bryntum-suite/scheduler/examples/time-selection/

**Comment by ExtAnimal** [comment]
I think the error was wrapping this arg list in `{}`.

The following fixes it:

![Screenshot 2024-06-04 at 15 14 23](https://github.com/bryntum/support/assets/200516/e7e4785d-334f-4f26-bb2a-72979e34a1da)
