### ISSUE TITLE
`tooltip` config on widget doesn't work in angular application

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#93]
To reproduce add `tooltip: 'foo'` config to any widget class in any angular application (spotted on advanced angular demo in Gantt), run the app, hover the widget - tooltip doesn't appear.

`tooltip` config is used by the global tooltip instance, which is created when tooltip class is imported:
```
Widget.tooltip = new Tooltip({
    id          : 'bryntum-tooltip',
    forElement  : window,
    forSelector : '[data-btip]',
    ...
})
```

Apparently it doesn't work with customElements, which angular uses. Thus probably issue would be reproducible with react and vue. Need to check

**Comment by isglass** [comment]
Tried adding the following:

```
<bryntum-button
    [text]="'Button'"
    [tooltip]="'Show'"
></bryntum-button>
```

And that works, tooltip shown.

Closing issue as no longer reproducible
