### ISSUE TITLE
Ella Patel lacks color

### ISSUE THREAD

**Issue by isglass** [bryntum/support#9305]
http://localhost/bryntum-suite/Grid/examples/drag-between-grids/

<img width="922" alt="Screenshot 2024-06-05 at 13 07 28" src="https://github.com/bryntum/support/assets/5415653/6e923d67-e347-4e29-9baf-e87b3e57d177">

**Comment by SergeyMaltsev** [comment]
Same here
http://localhost/bryntum-suite/Grid/examples/drag-between-trees/
