### ISSUE TITLE
Exported PDF corrupt after adding task

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#933]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14330&p=73391)

How to replicate:
Open the Export demo
Right click on the root task and add a task below
Hit the export button, download the PDF and open it

Result:
Some rows are missing at the top and the bottom

Expected:
All rows are present.

I made a report (to which I don't have access) using the feedback feature:
https://app.therootcause.io/d18e4328b7b5d16c17d813756a845cf5298e6639

Additional details:
In our application, when the new task is saved I can reload the entire app and the exportation includes the new row.
Still in our application, calling project.taskStore.crudManager.load() has some effect but does not fix the problem.
Not sure what other actions, if any, will also mess the exported PDF

**Comment by bmblb** [comment]
This is fixed along with this ticket: https://github.com/bryntum/support/issues/1092
