### ISSUE TITLE
Infinite scroll feature - scroll resets too close to the left edge of the new date range

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9356]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=29335&p=148103#p148103)

"Hi, When activating the infinite scroll feature with the below config, the scroll is stuck when scrolling backwards to past dates:

```
{
    infiniteScroll: true,
    bufferCoef: 1,
    bufferThreshold: 1,
}

```
I was able to reproduce it on your [live example](https://bryntum.com/products/scheduler/examples/infinite-scroll/):"
![infiniteScroll.gif](https://forum.bryntum.com/download/file.php?id=28949)

**Comment by ExtAnimal** [comment]
The fix is in `TimelineScroll.js`:

![Screenshot 2024-06-12 at 11 45 38](https://github.com/bryntum/support/assets/200516/38c64b80-19bf-436a-ac60-baab86ea329b)
