### ISSUE TITLE
Late end date position is incorrect

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9359]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=29337&p=148109#p148109)

Hi Bryntum,

it is still unclear how the indicators work. In this bug I can see that indicators are note showing correctly, but it is closed: #7963

Just check out the lateEnd value and the indictor line which appears to be a month late:

![Screenshot 2024-06-10 165151.png](https://forum.bryntum.com/download/file.php?id=28958&sid=e71830197a3238ca15fd93a9a955da6a)

You can find this in your own sample in the docs:

[**Gantt.feature.Indicators**](https://bryntum.com/products/gantt/docs/api/Gantt/feature/Indicators)

Please elaborate, thanks very much,

Best,
Andreas

**Comment by arcady-zherdev** [comment]
Related to https://github.com/bryntum/support/issues/7963
which has not resolved the problem completely
