### ISSUE TITLE
Calendar event edit button sometimes is hidden after creating a new event

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9361]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=29344&p=148134#p148134)

"Dear support,

We run into another issue on the Calendar event editor window. When it first loads the calendar, the edit window shows the Delete button. After create and save a new event, then the event editor window for any event does not show the Delete button unless the calendar is reloaded.

Here are the steps to reproduce it:

- When the first time the calendar is loaded, the event editor window shows the Delete button. Screenshot 1;
- Then add a new event. There is no Delete button at the editor window, which is correct. Screenshot 2;
- Click on Save to create the event. Then open any event, the Delete button is missing. Screenshot 3;
- Reload the calendar, the Delete button is back in the event editor;"

Follow the steps provide on https://bryntum.com/products/calendar/examples/basic/ 

![Screenshot_2.png](https://forum.bryntum.com/download/file.php?id=28968)
![Screenshot_3.png](https://forum.bryntum.com/download/file.php?id=28967)
![Screenshot_1.png](https://forum.bryntum.com/download/file.php?id=28965)

**Comment by ExtAnimal** [comment]
Regressed here: https://github.com/bryntum/bryntum-suite/pull/9115/files#diff-bc4c9a507a39cc2ce41c1b6f27562e31f827d9c049f6cb6ff57e172442fc831cR33
