### ISSUE TITLE
Merge cells rendering issues

### ISSUE THREAD

**Issue by egorkel-altexsoft** [bryntum/support#9379]
**Environment**: angular 18 + scheduler pro 5.6.11
**Demo repo**: https://github.com/egorkel-altexsoft/angular-bryntum-merge-cells-issue

### Bug 1
Merged cells layout breaks when removing overlapped events with custom row height.

1. Add a few overlapped events
2. Set a custom rowHeight to 96
3. Scroll to the bottom and press Remove events button

[merge-cells-bug1.webm](https://github.com/bryntum/support/assets/95917278/5f6c0d5a-be1e-42ec-8aff-f765f592a249)

### Bug 2
A custom class is not applied when collapsing/expanding resource groups

1. Collapse all groups
2. Expand the first and the second
3. Scroll to the bottom - one of the merged cell does not have a custom class
4. If you scroll to the top and back to the bottom the class is applied successfully. It looks like something with a virtual scroll.

[merge-cells-bug2.webm](https://github.com/bryntum/support/assets/95917278/98e1c5ca-eb60-4991-9ed2-4059bfc783bb)

**Comment by matsbryntse** [comment]
Thanks for reporting! Please report one bug per issue, + can you please share a small test case?

**Comment by egorkel-altexsoft** [comment]
@matsbryntse I added the link to the repo where you can see these issues. You can clone it and try. I described steps how you can reproduce them. What additional info can I provide?

**Comment by matsbryntse** [comment]
That should be enough info, which company / license are you working with?

**Comment by egorkel-altexsoft** [comment]
Company is Hastings Deering

**Comment by housewm** [comment]
@matsbryntse 
Hello Mat, is there any update on this?

**Comment by egorkel-altexsoft** [comment]
I've updated to v6.0.1 and nothing has changed. I can reproduce both issues in the same demo repo.

**Comment by mazzafabio** [comment]
Hello, I've just tested with v6.0.1, the event rendering issue seems solved but there still was class issue. That's because `rendering` callback is used to manipulate cell DOM. Instead, for merge cell `mergedRenderer` callback should be used.
Unfortunately, `mergedRenderer` was not documented, I'm sorry for that. In the next release, it should be consulted and used.
[screen-capture (10).webm](https://github.com/bryntum/support/assets/50654914/daf1f085-de86-4d1c-9fa6-ee25a774e695)

**Comment by egorkel-altexsoft** [comment]
Can you please describe how to use `mergedRenderer`, I try it.

**Comment by egorkel-altexsoft** [comment]
> Sure, but because it was not documented, currently is not a type of Column bryntum in typescript version. But if you want, you can try it in vanilla version for the moment. That's the code `mergedRenderer : ({ domConfig, value, record } : any) => { domConfig.className['crew-cell'] = value && !record.isGroupHeader; }`

Thanks! I'll try a little bit later

**Comment by mazzafabio** [comment]
Btw, you can follow the progress [here](https://github.com/bryntum/support/issues/9548) (it needs just to be reviewed)

**Comment by egorkel-altexsoft** [comment]
> Sure, but because it was not documented, currently is not a type of Column bryntum in typescript version. But if you want, you can try it in vanilla version for the moment. That's the code `mergedRenderer : ({ domConfig, value, record } : any) => { domConfig.className['crew-cell'] = value && !record.isGroupHeader; }`

I can confirm `mergedRenderer` works great! Thanks!
Waiting for the bug1 fix.

**Comment by housewm** [comment]
@mazzafabio  Hello, any updates about bug 1?

**Comment by mazzafabio** [comment]
Hello @housewm, I'm still fixing bug 1, hopefully for today PR is ready, I'll let you updated

**Comment by mazzafabio** [comment]
Hello, bug 1 fixed, PR merged. It will be available in the next release, including `mergedRenderer `
