### ISSUE TITLE
Duration Column Invalid Input Bug when using custom unit name

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9381]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=29389&p=148405#p148405)

"Hello Bryntum,

We are experiencing an issue with localized time units that contain upper-case characters.

It appears that all versions higher than v5.6.5 are affected, including the most recent v5.6.12.

Reproduction config:

```
unitNames : [
            { single : 'Millisekunde', plural : 'Millisekunden', abbrev : 'ms' },
            { single : 'Sekunde', plural : 'Sekunden', abbrev : 's' },
            { single : 'Minute', plural : 'Minuten', abbrev : 'min' },
            { single : 'Stunde', plural : 'Stunden', abbrev : 'h' },
            { single : 'Tag', plural : 'Tage', abbrev : 't' },   // NOTE the upper-case Ts here
            { single : 'Woche', plural : 'Wochen', abbrev : 'W' },
            { single : 'Monat', plural : 'Monate', abbrev : 'M' },
            { single : 'Quartal', plural : 'Quartal', abbrev : 'Q' },
            { single : 'Jahr', plural : 'Jahre', abbrev : 'J' },
            { single : 'Dekade', plural : 'Jahrzehnte', abbrev : 'dek' }
        ],

```

When the user starts editing a cell using the Duration Column's editor, an "invalid field" message is showing.

We traced down the issue to this code:

```
static parseTimeUnit(unitName) {
    const unitMatch = unitName == null ? null : DH.durationRegEx.exec(unitName.toLowerCase());
    if (!unitMatch) {
      return null;
    }
    for (let unitOrdinal = 0; unitOrdinal < canonicalUnitNames.length; unitOrdinal++) {
      if (unitMatch[unitOrdinal + 1]) {
        return canonicalUnitNames[unitOrdinal];
      }
    }
  }

```

DH.durationRegEx contains the non-lowered units, but the exec function's input is converted to lower case. Hence, the match will always fail."

- Go to https://bryntum.com/products/gantt/examples/advanced/
- Add the custom unit names like the user provided
- When trying to edit the duration, an error tooltip appears.

<img width="897" alt="Screenshot 2024-06-13 at 17 44 15" src="https://github.com/bryntum/support/assets/16693227/41e2f1ba-b866-4529-be37-a6e0a059e7d4">

**Comment by atremel** [comment]
Any update on this one - this blocks us from moving up from v5.6.5 with all the great fixes (printing especially, but a couple more)

**Comment by atremel** [comment]
Any update?

**Comment by matsbryntse** [comment]
Fix in place, just awaiting merge - will be part of 6.0
