### ISSUE TITLE
Tooltip title missing

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#939]
https://bryntum.com/examples/calendar/eventtooltip/

Also broken in scheduler master

**Comment by matsbryntse** [comment]
<img width="376" alt="Screenshot 2020-06-15 at 14 38 45" src="https://user-images.githubusercontent.com/218570/84658273-ee92e600-af15-11ea-8e27-3d4e726f8c0d.png">

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/1462
