### ISSUE TITLE
[VUE 3] Events disappear after ResourceStore.load() in 5.6.12

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#9403]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=29429&p=148782#p148782)

After call to ResourceStore.load() (and no change happening, the resources stay the same) the loaded events disappear from the Scheduler. This was not the case in v5.6.11
![store_load_fail.gif](https://forum.bryntum.com/download/file.php?id=29107)

Investigation:
Reloading resources on a SchedulerPro (not Scheduler) will not map the new resources to already loaded assignments and events.

To repro:
1. Use the Scheduler's php demo
2. Convert it to use SchedulerPro instead
3. In console, type schedulerPro.resourceStore.load()

Reason why it worked prior to 5.6.12 was that syncDataOnLoad was true per default

**Comment by ExtAnimal** [comment]
Creating a test case should be even simpler.

Just `schedulerPro.resourceStore.data = schedulerPro.resourceStore._data` will make the rendered events disappear.
