### ISSUE TITLE
Make default event duration configurable

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9431]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=29497&p=149062#p149062)

Hello all !

I'm using the Calendar lib, in react ts.

When I create a new event the default duration is 1 hour. 

Is it possible to change this duration ?

**Comment by matsbryntse** [comment]
The double click (and that gesture is configurable) event creation actions are fully customisable using this configuration option: [Calendar.view.Calendar#config-autoCreate](https://www.bryntum.com/products/calendar/docs/api/Calendar/view/Calendar#config-autoCreate)
