### ISSUE TITLE
Event Scheduling from 11:30 PM to 12 AM highlights entire day in IST timezone

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9450]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=29510&e=1&view=unread#unread)

To reproduce 
1. change your system timezone to IST timezone
![ApplicationFrameHost_hQ7INaoED0](https://github.com/bryntum/support/assets/75997756/30db0d13-134c-4eeb-b41f-19027a623ccd)
2. Open this demo https://bryntum.com/products/calendar/examples/basic/
3. Now try to create an event from 11:30 PM to 12 AM and you'll see that it highlights the whole day

https://github.com/bryntum/support/assets/75997756/43447362-b3de-4694-b0be-ec7b3013cc66

**Comment by bpreddy25** [comment]
Hi, Could you please let us know if any update on this issue?
