### ISSUE TITLE
showCurrentTimeline isn't working when setting name in Timeline widget

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9461]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=29546&p=149417#p149417)

Reproduction screenshot -->
![timeline_timeranges_issue_2024-06-28_11-28-23](https://github.com/bryntum/support/assets/75997756/b66898bc-a104-48e3-8391-6240a77a3f1f)

Reproducible demo link https://bryntum.com/products/gantt/examples/timeline/

**Comment by ghulamghousdev** [comment]
Duplicate of this: https://github.com/bryntum/support/issues/8970
