### ISSUE TITLE
Crash when selecting date in fullscreen docs fiddle

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9468]
Go full screen with the fiddle below, 
Open and select a date in the picker.
Then go full screen, 
Open picker - note it now shows wrong months (Sep-Oct)
select a date again => crash

https://bryntum.com/products/scheduler/docs/api/Core/widget/DateRangeField

```
scheduler.module.js?477655:12 Uncaught 
TypeError: Cannot read properties of null (reading 'getDay')
    at _SchedulerDatePicker.isDisabledDate (scheduler.module.js?477655:12:54564)
    at _SchedulerDatePicker.onUIDateSelect (scheduler.module.js?477655:22:19988)
    at _SchedulerDatePicker.onCellClick (scheduler.module.js?477655:22:19765)
    at u (scheduler.module.js?477655:10:703682)
    at HTMLDivElement.u (scheduler.module.js?477655:10:704815)
﻿

```
<img width="957" alt="Screenshot 2024-06-29 at 10 39 52" src="https://github.com/bryntum/support/assets/218570/830075c9-a837-48b5-89b9-69b8b2c398a8">

**Comment by dongryphon** [comment]
This may be not reproducible on Linux, but I did find an issue there. I could not get the picker to display when I went fullscreen on the fiddle due to `DomHelper.getVisibleViewport` not recognizing the `document.fullscreenElement`. Once I fixed that, the picker displayed and I got no errors on clicking dates.

**Comment by matsbryntse** [comment]
Date is corrupted 
<img width="1074" alt="Screenshot 2024-06-30 at 09 35 49" src="https://github.com/bryntum/support/assets/218570/9507fa20-0418-4fbf-b45a-5e30e600f058">
