### ISSUE TITLE
Aborting CrudManager requests leads to promise rejection message in console

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#947]
Add to crudmanager demo:

```
listeners : {
            beforesync : () => false
        }
```

<img width="752" alt="Screenshot 2020-06-16 at 10 21 57" src="https://user-images.githubusercontent.com/218570/84750151-37e94100-afbb-11ea-92ae-e624097b85f4.png">

**Comment by pmiklashevich** [comment]
Duplicated. Closed in favor of https://github.com/bryntum/support/issues/1412
