### ISSUE TITLE
CalendarEditor broken layout

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9475]
<img width="970" alt="Screenshot 2024-06-30 at 18 21 39" src="https://github.com/bryntum/support/assets/218570/f3bfcbde-9735-433e-850c-b417604c9d0b">

Run live demo at http://lh/bryntum-suite/gantt/docs/#SchedulerPro/widget/CalendarEditor

Click button to show editor, note right side of popup isn't laid out correctly

**Comment by canonic-epicure** [comment]
This ticket was css-only and does not have a changelog entry. Closing as completed after merge.
