### ISSUE TITLE
[REACT] Gantt crashes when manuallyScheduled set from task editor

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9476]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=29574&p=149513#p149513)

Hello,

We are encountering an error: TypeError: Cannot read properties of null (reading 'mergeUpdateModelActions'). This issue arises when we manually check the scheduled option inside the advanced tab of the task menu edit.

Attached are our runnable test and an image of the error for your reference.

Thank you for your assistance.
![Screenshot 2024-06-30 at 14.27.10.png](https://forum.bryntum.com/download/file.php?id=29357)

Reproducible with the project below
[runnable-test-manually-se.zip](https://github.com/user-attachments/files/16048468/runnable-test-manually-se.zip)

**Comment by canonic-epicure** [comment]
Closing as invalid.
