### ISSUE TITLE
Ticks should not be rendered when filter out all ticks from TimeAxis

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#948]
[TimeAxis](https://www.bryntum.com/docs/gantt/#Scheduler/data/TimeAxis) is a store, so it's possible to filter out all ticks.

`scheduler.timeAxis.filter(() => false);`
Scheduler
<img width="1124" alt="Снимок экрана 2020-06-16 в 15 53 36" src="https://user-images.githubusercontent.com/57486733/84776887-90cfce00-afe9-11ea-8d3d-4c8da3cf6fff.png">
SchedulerPro
<img width="1111" alt="Снимок экрана 2020-06-16 в 15 54 43" src="https://user-images.githubusercontent.com/57486733/84777044-c379c680-afe9-11ea-93a0-5969b6a94e08.png">

`gantt.timeAxis.filter(() => false);`
Gantt
<img width="1123" alt="Снимок экрана 2020-06-16 в 15 55 52" src="https://user-images.githubusercontent.com/57486733/84777135-e1472b80-afe9-11ea-8e70-0948d620ad23.png">

Note, all errors related to the all ticks filtered out are already solved in master

**Comment by matsbryntse** [comment]
invalid use case
