### ISSUE TITLE
Removing a specific group shows empty meta records

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#949]
http://lh/bryntum-suite/scheduler/examples/grouping/
`scheduler.resourceStore.removeGrouper('category');`
<img width="2048" alt="Снимок экрана 2020-06-16 в 18 05 15" src="https://user-images.githubusercontent.com/57486733/84791917-f2009d00-affb-11ea-9a7b-46a716828e3f.png">

We use removeGrouper internally in ColumnDragToolbar, to reproduce add to Scheduler/examples/grouping/app.js
```
import '../../lib/Grid/feature/ColumnDragToolbar.js';
....
    features : {
        columnDragToolbar : true,
```
Group by Employment column
Drag the column
See options are appeared on the screen
Drop on "STOP"
<img width="872" alt="Снимок экрана 2020-06-16 в 18 23 04" src="https://user-images.githubusercontent.com/57486733/84794271-b9ae8e00-affe-11ea-9076-6034cf741db5.png">

Also we use removeGrouper internally when we double click on column header holding shift and alt keys. To reproduce click on Employment column holding shift key, then click on Employment column holding shift + alt keys.
<img width="657" alt="Снимок экрана 2020-06-16 в 18 23 38" src="https://user-images.githubusercontent.com/57486733/84794431-e82c6900-affe-11ea-90ee-79253e53bf10.png">

1. removeGrouper should perform clearing storage from meta records similar to what `scheduler.resourceStore.clearGroupers();` does when it sets null value to groupers.
```
            me.groupRecords.forEach(r => {
                if (r.meta.collapsed) {
                    me.includeGroupRecords(r);
                }
            });
```

2. make removeGrouper public?

**Comment by matsbryntse** [comment]
not reproducible
