### ISSUE TITLE
Nested Events With parent dependencies and children out of limit

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9494]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=29598&p=149661#p149661)

"I am using Bryntum SchedulerPro 6 (latest), I am using scheduler nested events  with parent dependencies structure to fulfill my requirement.

I am facing issue that the children goes out of the parent when the height of parent is filled, in previous version (5.5) there was no issue.

I noticed a class "b-dependancies" that disturbs the style with overflow:visible.

same issue was noticed in example : https://bryntum.com/products/schedulerpro/examples/nested-events-dependencies/"

![Screenshot 2024-07-02 at 4.52.42 PM.png](https://forum.bryntum.com/download/file.php?id=29408)

- Go to the example that the user mentioned - https://bryntum.com/products/schedulerpro/examples/nested-events-dependencies/.
- Drag some nested events to only one parent until overflow.
- The behavior is displayed in the attached video

https://github.com/bryntum/support/assets/16693227/984c31ee-8f7f-405a-b718-72204988e755

**Comment by najam2012** [comment]
This issue fix will be a lot of help. @marciogurka  can you let me know some estimates on this fix as we are blocked due tho this. Thanks

**Comment by matsbryntse** [comment]
Update here: https://forum.bryntum.com/viewtopic.php?p=150574#p150574

**Comment by mazzafabio** [comment]
Thank you for the kind works :)
