### ISSUE TITLE
Task end date moves to the previous day when business calendar is used

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#95]
https://www.bryntum.com/forum/viewtopic.php?f=51&t=12908#p67464

When task's end day happens to be a non-working time, it shifts to the previous day. Task end date should be equal to the day which was selected in the editor.

http://lh/bryntum-suite/gantt/examples/advanced/
Gantt/examples/_datasets/launch-saas.json

```    "project" : {
        "calendar"  : "business",
```

Gantt/examples/advanced/app.js

```
    columns : [
        { type : 'startdate', format : 'll LT' },
        { type : 'enddate', format : 'll LT' },
```

Double click a task end date cell, for example Install Apache.
Change the date in the datepicker, for example 2019-01-18 - Friday.
Press Enter. See the end date is 2019-01-17 - Thursday now.

<img width="1464" alt="Снимок экрана 2019-12-17 в 17 31 07" src="https://user-images.githubusercontent.com/57486733/71005566-e556c700-20f4-11ea-9359-9838ac966f37.png">

**Comment by bensullivan** [comment]
Hi - any update on when this is going to get fixed?  Thanks

**Comment by matsbryntse** [comment]
We'll look at this one for the next 2-3 patch releases.

**Comment by bensullivan** [comment]
Hi - any update on turn around for this?  Seems odd that no one else is affected by this.  Entering a Friday and getting Thursday is kinda significant for a gantt component??  Or is this a timezone issue?  Would appreciate a workaround or a fix - we're going live on Monday...

**Comment by matsbryntse** [comment]
We'll try to fit this in during next week.

**Comment by bensullivan** [comment]
OK - much appreciated @matsbryntse - thanks
