### ISSUE TITLE
Assigning `project` to Scheduler Pro at runtime leads to errors

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#950]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=14331&p=73504#p73504)

The user provided a showcase where he assigns `project` to the Scheduler Pro instance after the instance is created. That leads to problems with tree which either does not expands nodes or throws on attempts to collapse.

Setting `project` as config in the scheduler config object resolves all problems.

We can either support change of `project` at runtime or we should implement a logic that would ignore it at runtime with a warning, but the scheduler must not wind up in a buggy state.

Steps to reproduce:
1. Unzip and run [scheduler-test.zip](https://github.com/bryntum/support/files/4788090/scheduler-test.zip) - the error will ensue.
2. Change `ngAfterViewInit()` to the following:
```
  ngAfterViewInit() {
    this.scheduler = new SchedulerPro({
      appendTo: this.schedulerRef.nativeElement,
      project: this.project,
      weekStartDay: 1,
      rowHeight: 40,
      barMargin: 3,
      columns: [
        {
          type: "tree",
          tree: true,
          text: "Locations",
          field: "name",
          width: 250,
          searchable: true,
        },
      ],
      features: {
        tree: true,
        timeRanges: {
          showCurrentTimeLine: true,
          showHeaderElements: false,
        },
      },
      workingTime: { fromDay: 1, toDay: 6 },
      maxZoomLevel: 10,
      minZoomLevel: 3,
      startDate: new Date("2020-05-01"),
      endDate: new Date("2020-10-01"),
      viewPreset: "dayAndWeek",
    });

    // this.scheduler.project = this.project;
    this.scheduler.expandAll();
    this.scheduler.zoomToLevel(9);
  }

```
and it will work.

Note: It is an Angular app but it should be reproducible also in vanilla

Note 2: https://www.bryntum.com/docs/scheduler-pro/#Scheduler/view/mixin/SchedulerStores#property-project

Project is missing docs

**Comment by matsbryntse** [comment]
It's documented as a property so should work

**Comment by jsakalos** [comment]
There's a PR on `project` documentation. It'll be merged soon.

**Comment by jsakalos** [comment]
Not reproducible with version 5.6.4

**Comment by jsakalos** [comment]
This issue is not reproducible with version `5.6.4`.
