### ISSUE TITLE
Resizing multiple events in drag selection mode

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#9509]
Reproducible on: https://bryntum.com/products/scheduler/examples/dragselection/

To reproduce select couple of events such as resizing one event would force another event end date out of the view. Then start resizing end date and see how events jumps around.

https://www.loom.com/share/db083b6f1655481fa1a0acb496abb6b4?sid=f145f4b4-7a05-4833-85e9-fe9c1f27ec36

**Comment by taauntik** [comment]
dupe https://github.com/bryntum/support/issues/9309
