### ISSUE TITLE
Event start date is one day before for zero-duration all-day events

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9513]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=29627&p=149810#p149810)

Dear Bryntum Team,

We encountered an error during testing. When we create an event with zero duration, meaning it starts at 00:00 and ends at 00:00, and then change the incident to daily, it appears interestingly in the Agenda menu item.

Please find attachment which represent the problem.

I really appreciate any comments.

Best Regards,
Adri

**Comment by ExtAnimal** [comment]
Can somebody please explain what the issue is?

It changes to be an all day event, so moves into the all day row. Then is displayed as a solid event bar which is what all day events do.

**Comment by ExtAnimal** [comment]
OK, I finally discovered what "interestingly" means. I think.

The fix, for calculating the time display text is in `EventList.js`:

<img width="1301" alt="Screenshot 2024-07-04 at 10 27 09" src="https://github.com/bryntum/support/assets/200516/f2947553-99b4-42fc-9472-a0f4aa3bb800">
