### ISSUE TITLE
Undo/redo not working in 6.0.0 (inline-data)

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9520]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=29648&p=149914#p149914)

"Hi,

We are running on v5.6.0 and in that version the undo/redo widget is working fine. However updating to v6.0.0 we get below exceptions and it is not working (see picture).

We did struggle to get undo/redo based on the inline-data example in the first place. You had to fix the below bug so adding that since it explains the setup

#3789

How to reproduce 
Below code works fine in inline example v5.3.4 but not adding the same in 6.0.0. In 6.0.0 this.gantComponent is undefined (we only added the undo/redo widget in the html file). I make the assumption that if you get the example working we can reuse that solution in our app.

```
<bryntum-project-model
    #project
    [calendar]     = "projectConfig.calendar!"
    [startDate]    = "projectConfig.startDate!"
    [hoursPerDay]  = "projectConfig.hoursPerDay!"
    [daysPerMonth] = "projectConfig.daysPerMonth!"
    [tasks]        = "tasks"
    [timeRanges]   = "timeRanges"
    [assignments]  = "assignments"
    [resources]    = "resources"
    [dependencies] = "dependencies"
    [calendars]    = "calendars"
</bryntum-project-model>

<bryntum-undo-redo  
    ref='undoRedo' 
    type='undoredo' 
    [project]="project">
</bryntum-undo-redo>

<bryntum-gantt
    #gantt
    [project]           = "project"
    [columnLines]       = "ganttConfig.columnLines!"
    [columns]           = "ganttConfig.columns!"
    [subGridConfigs]    = "ganttConfig.subGridConfigs!"
    [viewPreset]        = "ganttConfig.viewPreset!"
    [timeRangesFeature] = "ganttConfig.features!.timeRanges!"
    [dependenciesFeature]   = "ganttConfig.features!.dependencies!"
</bryntum-gantt>

ngAfterViewInit(): void {
     var gantt = this.ganttComponent.instance;
     gantt.project.stm.autoRecord = true;
     gantt.project.stm.enable();
}

```
![in v5.3.4 with above changes](https://forum.bryntum.com/download/file.php?id=29504)
![screenshot from our app](https://forum.bryntum.com/download/file.php?id=29503)
![screenshot from our app](https://forum.bryntum.com/download/file.php?id=29502)
"

Just update the inline data Angular demo with the snippet as user mentioned and the error will appear when compiling.

**Comment by matsbryntse** [comment]
Missing running test case

**Comment by canonic-epicure** [comment]
Split this ticket into 2 issues: #9537 and #9538, please track those for progress, closing this one.
