### ISSUE TITLE
Resource header disappears when restoring state

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#9524]
Reproducible on any vertical demo (vertical, vertical-dependencies) when you call `scheduler.state = scheduler.state`. Does not occur in vertical tests by default.

![image](https://github.com/bryntum/support/assets/45400762/d336570b-e28c-4ba1-aa11-65eacf9e0f54)

**Comment by matsbryntse** [comment]
Dupe https://github.com/bryntum/support/issues/9504
