### ISSUE TITLE
Default currency from locale not used

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9572]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=29729&p=150460#p150460)

Hi!

Go to [basic](https://bryntum.com/products/grid/examples/basic/) example and use the below code:

```
{
            text  : 'Age',
            field : 'age',
            width : 100,
            type  : 'number',
            format: {template: '$0,000.00', style: 'currency'}
        },
```

See the default currency from locale which is `USD` is not used.

**Comment by marciogurka** [comment]
[Another post](https://forum.bryntum.com/viewtopic.php?p=150753#p150753) related to this one.

**Comment by henriquewerlang** [comment]
This was fixed?

**Comment by matsbryntse** [comment]
Yep, should be in the next patch.

**Comment by henriquewerlang** [comment]
Please reopen because nothing is working as expected!
