### ISSUE TITLE
Event Drag is broken in RTL with `constrainDragToTimeline : false`

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9576]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=29740&p=150511#p150511)

Go to scheduler basic example and set the following config:

```
    rtl: true,
    features:{
        eventDrag : {
            constrainDragToTimeline : false
    },
```

And try to drag an event. Event is dragged in the opposite direction.

https://github.com/user-attachments/assets/f3e62894-daea-45ff-8a50-c019bc93ceeb

**Comment by yakeer** [comment]
@matsbryntse 
We would appreciate a quick fix here.
We're using RTL in most of our customers, and we would really want to upgrade to 6.x, since we're on a 5.6.1 because that would be the most stable RTL version, that we could actually work with.

Thanks.
Planit.

**Comment by matsbryntse** [comment]
@yakeer Sure. We'll get this fixed!
