### ISSUE TITLE
Column sorting causes record modifications

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#958]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14369&p=73548)

Steps to Reproduce

Go to the undo/redo example here: https://www.bryntum.com/examples/gantt/undoredo/
Sort by the name column. 
Note that the undo button remains disabled
In the browser console, run the following: 
```
gantt.project.taskStore.changes.modified.map(t => ({ name: t.name, changes: JSON.stringify(t.meta.modified)}))
```

Record's parentIndex is updated, should not be.

When sorting, parentIndex should not be updated. 

In Ext JS Gantt we do:
```
// Prevent a sort from triggering 'index' field to be persisted. It should only be persisted when reordering manually
            beforesort : function () {
                var indexField = this.getModel().getField('index');

                indexField.oldPersist = indexField.persist;
                indexField.persist = false;
            },

            sort : function () {
                var indexFld = this.getModel().getField('index');

                indexFld.persist = indexFld.oldPersist;
            },
```

**Comment by pmiklashevich** [comment]
Reproduced in both release and master
