### ISSUE TITLE
Calendar docs should not show Grid store related docs

### ISSUE THREAD

**Issue by khattakdev** [bryntum/support#9581]
![image](https://github.com/user-attachments/assets/54384c88-2d66-418b-be16-d8ed34c1b9a1)

Look for other places as well and make the docs Calendar centric

**Comment by ExtAnimal** [comment]
Why?

Grid is used By Calendar.

`EventList` is a Grid. People need to know how to use it.

**Comment by khattakdev** [comment]
@ExtAnimal Its only about Grid Store docs that is in the Calendar. For example:

https://bryntum.com/products/calendar/docs/guide/Calendar/data/displayingdata
