### ISSUE TITLE
Undoing created dependency leaves task in modified state

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#959]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14369&p=73548)

An additional somewhat related issue can be seen by creating a link/dependency and then undoing the change.

Go to the undo/redo example here: https://www.bryntum.com/examples/gantt/undoredo/
Create a link between the "Unit tests" task and the "UI unit tests / individual screens"
Undo
In the browser console, run the following
```
gantt.project.taskStore.changes.modified.map(t => ({ name: t.name, changes: JSON.stringify(t.meta.modified)}))
```

**Comment by pmiklashevich** [comment]
Not reproducible in both release and master. Must have been fixed in https://github.com/bryntum/support/issues/975
