### ISSUE TITLE
onEventPartialResize context object replacement in 6.0.1

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9624]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=29706&p=150705#p150705)

"Hi,

I'm working on a migration to Scheduler 6 (Pro) and came across the (undocumented?) changes to the event object passed to a handler for onEventPartialResize. It seems like the context subobject was removed. Based on the change mentioned in the third point in the upgrade guide ([Scheduler/Upgrades/6.0.0#the context and its nested params of beforeeventresizefinalize has been deprecated](https://www.bryntum.com/products/scheduler/docs/guide/Scheduler/upgrades/6.0.0#the-context-and-its-nested-params-of-beforeeventresizefinalize-has-been-deprecated)), I'm guessing in favor of resizeData.

We previously used the context object to store a validation message in the onEventPartialResize handler that is then shown in a tooltip. How can we achieve this in v6?

As a secondary question: where is the above change documented? I did not find any reference in the update announcement, changelog, migration guide or apidiff."

- Using a Scheduler Pro React demo as example, add the following configuration to the Scheduler config
```
eventResizeFeature: {
        tooltipTemplate: (data) => {
            return data.message
        }
    },
    onEventPartialResize: (ev) => {
        ev.context.message = 'test message'
    }
```

- If you use 5.6.13, it works just fine, but on 6.0.1, the context object is not available anymore, and that piece of code will trigger an error. How to achieve the same result in the new version?

**Comment by isglass** [comment]
Resolved by updating the upgrade guide + mentioning in changelog
