### ISSUE TITLE
Setting RTL on `document.documentElement` results in incorrect behaviour of Drag

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9635]
Currently setting RTL on `document.documentElement` results in incorrect behaviour of drag. Upon dragging an task, it moves the task in the opposite direction of the drag. Please see the attached clip to get better understanding of the issue. Steps to reproduce this issue:

1. Go to vanilla advanced examples: https://bryntum.com/products/gantt/examples/advanced/
2. Run this in console: `document.documentElement.setAttribute("dir", 'rtl');`
3. Now try to drag the parent task to left. You can see the mouse pointer is moved towards the right but the task bar moves towards the left.

https://github.com/user-attachments/assets/319340c2-92a8-4923-8dc8-dda79afb6a85

**Comment by matsbryntse** [comment]
Need to set `rtl` on Bryntum widgets too
