### ISSUE TITLE
index.module.html demos returning 404

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9639]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=29829&p=151010#p151010)

"No problem running this:
https://bryntum.com/products/schedulerpro/examples/drag-unplanned-tasks/index.html
or this
https://bryntum.com/products/schedulerpro/examples/drag-unplanned-tasks/index.umd.html
but get Page Not found for this:
https://bryntum.com/products/schedulerpro/examples/drag-unplanned-tasks/index.module.html
can you look at that example and see why there seems to be an issue running it?
see screen shot
![2024-07-22_10-05-37.png](https://forum.bryntum.com/download/file.php?id=29839)
"

All of the demos return 404 when trying to access the `index.module.html` demo

**Comment by khattakdev** [comment]
We don't have `index.module.html` links. 

I believe they have guessed the link and typed it manually but let's confirm it if we have some place linking to `index.module.html` that needs to be fixed.
