### ISSUE TITLE
Can't set resourceField default selected value to empty

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9640]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=29830&p=151021#p151021)

"When using the default resourceField described here Calendar/Customization/Eventedit#default fields it doesn't seem like it's possible to set this to not auto select the first resource.

```
    eventEditFeature: {
      items: {
        ...
        resourceField: {
          type: "combo",
          label: "Dispatch",
          multiSelect: true,
          value: [],
          weight: 700,
        },

```
"

Go to the basic demo and try to add the following configuration
```
features : {
        eventEdit : {
            // Our definition of its child items is merged over the provided one
            items : {
                resourceField: {
                  type: "combo",
                  label: "Dispatch",
                  multiSelect: true,
                  value: [],
                  weight: 700,
                },
            }
        },
    },
```

Is expected that the resourceField is loaded empty, but that's not the observed behavior.

**Comment by ExtAnimal** [comment]
The behaviour is correct. The Editor is loaded with data *before* being shown.

To *change* the values that were loaded needs a new event which comes later. That is requested here: https://github.com/bryntum/support/issues/9579
