### ISSUE TITLE
Fiddle code editor does not animate into view

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9670]
at https://bryntum.com/products/scheduler/docs/

**Comment by ExtAnimal** [comment]
This is the same issue as the broken examples. It's the CSS.

There has not been some massive code regression which needs to cause an exponential cascade of tickets for every consequence os the CSS issue. It is the same issue.

**Comment by SergeyMaltsev** [comment]
This works locally. But not on released onine version.
