### ISSUE TITLE
Timezone property not working

### ISSUE THREAD

**Issue by khattakdev** [bryntum/support#9682]
The `eventStore.toJSON()` prints the dates by converting them into local time.

For example, the Scheduler timezone is `UTC` and you add a new record:

```
scheduler.eventStore.add({
    startDate : '2024-04-01T02:00'
})
```

On `scheduler.eventStore.toJSON()`, the last record will show `2024-04-01T02:00`, if you're 5 hours ahead of UTC.

The [docs](https://bryntum.com/products/scheduler/docs/api/Scheduler/model/mixin/ProjectModelTimeZoneMixin#config-timeZone) says that:

> _If you want to create new records with dates that either should be interpreted as local system time zone or from any other time zone, specify the [timeZone](http://127.0.0.1:5500/Scheduler/docs/#Scheduler/model/mixin/TimeZonedDatesMixin#field-timeZone) field on the record._

If I add a new record while the Scheduler is in `UTC` timezone and I am +5 hours ahead of it:

```
scheduler.eventStore.add({
    timezone: "America/New_York",
    startDate : '2024-04-01T02:00'
})
```

It should add the record with `America/New_York` timezone, which when converted to UTC, it is: `2024-04-01T06:00` but since the `toJSON()` shows the time in local timezone, it is expected to show the record's date as: `2024-04-01T11:00`. However, it shows up as `2024-04-01T07:00`.

It looks like the `timezone` property doesn't work and the record is added with the scheduler's current timezone (`UTC`), which gives `2024-04-01T07:00`.

Here's another example:
![CleanShot 2024-07-29 at 14 28 36](https://github.com/user-attachments/assets/26d1712e-3362-4811-9a54-01fce605e662)

Both of the record shows the same time.

It can be tested in [Scheduler/basic](bryntum.com/products/scheduler/examples/basic) demo.

**Comment by JockeLindberg** [comment]
timeZone should be configured with a capital Z. Closing.
