### ISSUE TITLE
Bryntum Agenda Print Issue

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#9685]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=29913&p=151500#p151500)

Hi,

I was facing one issue when i used print functionality.
which was, on print agenda view the content was cotting off.
which seems to be resolved now, in
#9198

I updated version to 6.0.3
I dont think its perfectly working.
because when we add tasks which covers only one page, prints fine.
but if We add more tasks with 2,3 pages, the problem still exist.

please check and let me know if any issue from my side.

I am attaching images for view and print preview from example section I tried.
https://bryntum.com/products/calendar/examples/print/

See tasks at Date: 17 in view and print preview.

![Screenshot from 2024-07-29 18-02-43.png](https://forum.bryntum.com/download/file.php?id=29941)
![Screenshot from 2024-07-29 18-03-07.png](https://forum.bryntum.com/download/file.php?id=29940)
![Screenshot from 2024-07-29 18-02-43.png](https://forum.bryntum.com/download/file.php?id=29941)
![Screenshot from 2024-07-29 18-03-07.png](https://forum.bryntum.com/download/file.php?id=29940)

**Comment by recf25** [comment]
@matsbryntse do we have a timeline on when this will be resolved?

**Comment by bmblb** [comment]
@recf25 can you reproduce this issue in the online demo? I tried printing agenda with more events but I don't see a bug anymore.

**Comment by HarshalParadigm** [comment]
Yes it is reproducible.
I am sharing the vide9
[recording1.webm](https://github.com/user-attachments/assets/f669620a-b1b9-4677-89c6-b47c3f5b97a1)

**Comment by taauntik** [comment]
Please follow the steps shown in the video below to reproduce @bmblb 

[recording1.webm](https://github.com/user-attachments/assets/bd808548-12e1-4ebd-9408-f22d9692b7e7)

**Comment by aguhabldr** [comment]
refreshing this thread, Can you please tell us when its going to be done and released ?

**Comment by bmblb** [comment]
I will investigate this problem next week

**Comment by bmblb** [comment]
@aguhabldr I updated forum thread with important information. I couldn't reproduce issue, more info on the forum

**Comment by ghulamghousdev** [comment]
The issue is reproducible in the landscape layout with A4 page size set in advanced settings. Here's the clip:


https://github.com/user-attachments/assets/0d5fb9cf-8d6e-4997-a6f1-c36713e0ff27



[Bryntum Calendar - Print demo.pdf](https://github.com/user-attachments/files/16782377/Bryntum.Calendar.-.Print.demo.pdf)

**Comment by aguhabldr** [comment]
refreshing this thread, Can you please tell us when its going to be done and released ?
cc : @bmblb

**Comment by bmblb** [comment]
We cannot do much if you pick different paper size in Bryntum print dialog and browser print dialog. If you're talking about row height, you can try latest nightly build, we fixed #8998 ticket which contains some changes related to positioning content on the page.

**Comment by ghulamghousdev** [comment]
The issue is even reproducible in the portrait mode with A4 paper size:




https://github.com/user-attachments/assets/ae19c871-eb89-4d7d-96e8-24b5de33254a
