### ISSUE TITLE
LoadOnDemand feature with ResourceView causes infinite load loop

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#9690]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=29906)

Hi,

I encountered a load loop of the CrudManager, when using the weekResources view in the Calendar 6.0.2.

I attached an example showing the issue.

To reproduce the issue, select the resourceWeek view (preselected in the example) and go back two calendar weeks via the top left calendar week navigation arrows. In the developer network tab you will see a firework of load requests.

The key changes I did compared to the Angular Basic Example was activating the resourceWeek View and enabling the "load on demand" feature.

BR,
Alex
![Screenshot 2024-07-29 at 11.49.53.png](https://forum.bryntum.com/download/file.php?id=29931)
![Screenshot 2024-07-29 at 11.47.51.png](https://forum.bryntum.com/download/file.php?id=29930)

**Comment by helgetan** [comment]
Stops us from upgrading to 6.X

**Comment by matsbryntse** [comment]
Fix coming in next release!
