### ISSUE TITLE
[VUE-3] Preventable events don't work in Vue wrapper

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9718]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=29957&p=151774#p151774)

Using any Vue 3 demo, add the following event listener

```
<bryntum-calendar
        ref="calendar"
        v-bind="calendarConfig"
        @beforeEventEdit="openEventEditor"
    />

 // beforeEventEdit handler
        const openEventEditor = ({ eventRecord }) => {
            console.log('beforeEventEdit');
            return false;
        };
```

on 5.6.13 it works as expected, the popup is not displayed, but on 6.x the popup is displayed.

**Comment by ExtAnimal** [comment]
Returning `false` from a `beforeEventEdit` handler definitely does prevent editing. This needs to be investigated more before logging a bug like this.
