### ISSUE TITLE
Reassigning resource of one event within series triggers incorrect CrudManager operations

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9726]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=54&t=29933&p=151720#p151720)

Hi,

I encountered an issue with the reassignment of one event of a series to another resource when using the CrudManager in Calendar 6.0.2.

When changing the assigned resource of a recurring event and selecting the "only this event" option in the dialog, the CrudManager sends unexpected operations. Typically, when selecting "only this event" I expect an "update" operation which excludes the changed event date from the original series and an "add" event which creates a new event with the newly assigned resource. This also works as expected but only for the first event of a series. When changing the resource of the second event of the series, only one "update" Crud operation is being sent. 

This unexpected behavior only happens when changing an event within a series (not the first event) and only when changing ONLY the assigned resource via drag-and-drop. When changing the startDate along with the assigned resource, the Crud operations are generated as expected.

Attached you will find a working example. Please start the frontend and backend, reassign the event "Hackathon 2020" on the 21.10.2020 to another resource (keeping the same date/time) and select "only this event" and watch the network tab.

When doing the steps for the first event in the recurrent series:

https://github.com/user-attachments/assets/7682937a-6058-4752-9c8b-6cebd4172203

When changing the resource for the any other event then first in the recurrent series, no new event is added and incorrect update request:

https://github.com/user-attachments/assets/13a1a6f0-8cc1-43e0-9f8d-ff8e682283eb

Test Case: 
[calendar-angular-basic-crud-change-resource.zip](https://github.com/user-attachments/files/16460578/calendar-angular-basic-crud-change-resource.zip)

**Comment by helgetan** [comment]
Thank you, Blocking us from upgrading to 6.X

**Comment by matsbryntse** [comment]
Checking this now!

**Comment by canonic-epicure** [comment]
It seems moving the 2nd event in the series (and choosing "only this event") actually re-assigns the whole series.

**Comment by helgetan** [comment]
any updated on the release cycle?

**Comment by matsbryntse** [comment]
We release patch releases every 2-4 weeks typically, so expect this to roll out sometime next w.
