### ISSUE TITLE
Cannot double click to edit event

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#976]
Double "tap-but-not-press" on touchpad of laptop (somehow hard double press works)
Double click an overlapping event, it animates but no editor opened
<img width="310" alt="Screenshot 2020-06-22 at 10 19 42" src="https://user-images.githubusercontent.com/218570/85265014-e684fa00-b471-11ea-9fc2-daa3dcf54bca.png">

**Comment by ExtAnimal** [comment]
More info needed. In what example, exactly what interaction sequence? Because it works in all the examples I try.

**Comment by matsbryntse** [comment]
![editorbug](https://user-images.githubusercontent.com/218570/85313442-55854180-b4b8-11ea-9755-4117de08630f.gif)

**Comment by ExtAnimal** [comment]
https://github.com/bryntum/bryntum-suite/pull/1494
