### ISSUE TITLE
Expand Collapse on left pane grid disappears after re-render

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9768]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30041&p=152268#p152268)

"Hi Team,

Continuing with updating gantt chart, I have initialised the gantt component with column configuration having custom renderer. It worked fine on first render. However, after any re-render (the parent component updates) and there is no data update on the props sent to Gantt component, the expand collapse disappears. I'm not able to figure out why it does so. The data is same. I have attached the code with data and screen shots capturing the two states.

Any insights will be helpful."

Attached is a demo with a sample code, when clicking "Update State" the expand/collapse icons disappear.

[basic example.zip](https://github.com/user-attachments/files/16533364/basic.example.zip)

https://github.com/user-attachments/assets/b52d4cd9-5a53-48ac-84a1-655435845fce

**Comment by ghulamghousdev** [comment]
I got the chance to look at the bug reported above. This is not an issue on our end and instead it is the issue of how you have decalred configs in the component and using them. You have declared a variable for tasks and config and on each re-render, they are re-created and hence their reference changes and gantt component treats them as new configs and recreates each thing. And also you are passing the columns directly to the gantt component which is not supported. We have two adopted practices to handle static and dynamic configs. For static configs, we recommend moving them to static files and import them inside your component. And the configs which are going to be changed at runtime, should be wrapped by a `useState` or `useMemo`. 

https://bryntum.com/products/gantt/docs/guide/Gantt/integration/react/guide#best-practices-for-configuration-management
- For static configs: https://bryntum.com/products/gantt/docs/guide/Gantt/integration/react/guide#external-configuration-for-static-settings
- For Dynamic configs: https://bryntum.com/products/gantt/docs/guide/Gantt/integration/react/guide#state-managed-configuration-for-dynamic-settings
- Another thing in frameworks, we recommend to using `BryntumGanttProjectModel` for configuring project on your component.
Please follow these guides and implement your solution accordingly. 

I have updated the test case and providing you both version using BryntumGanttProjectModel and with management of static and dynamic configs. Here is the updated test case with the problem fixed:

[basic-example-using-useState.zip](https://github.com/user-attachments/files/16561405/basic-example-using-useState.zip)


https://github.com/user-attachments/assets/e345520f-bc80-4227-bdbc-53565cad93f4
