### ISSUE TITLE
Desynchronization in `realtime-updates` example in SchedulerPro after undoing event unassignment/deletion

### ISSUE THREAD

**Issue by canonic-epicure** [bryntum/support#9787]
Please refer to the video for the steps to reproduce:

https://github.com/user-attachments/assets/b4d13458-72c0-4a28-a49c-54aa3d6c4f10

The same issue applies for the "Delete" action.

**Comment by bmblb** [comment]
server issue, server did not handle number phantom ids. server updated: https://github.com/bryntum/gantt-websocket-server/commit/682bc893265f5a1c262c454bb8f3b09e718828d2
