### ISSUE TITLE
Grid freezes when row reordering in column using an array field

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9805]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=30099&p=152637#p152637)

"When I apply grouping on the Mutivalue column and attempt to reorder any row, the interface freezes, making it unresponsive.

Steps to Reproduce:
- Apply the provided code snippet to group the grid by the 'food' column.
- Attempt to reorder any row within the grid.

Code Snippet:

```
const grid = new Grid({
    appendTo : targetElement,

// makes grid as high as it needs to be to fit rows
autoHeight : true,

features : {
    rowReorder: { showGrip: true }
},

store : {
    fields : [
        'name',
        { name : 'foods', type : 'array' },
        'city'
    ]
},

data : [
    {
        id    : 1,
        name  : 'Bruce Wayne',
        foods : ['Pizza', 'Sushi', 'Burgers'],
        city  : 'Gotham'
    },
    {
        id    : 2,
        name  : 'Clark Kent',
        foods : ['Pizza', 'Burgers'],
        city  : 'Metropolis'
    },
    {
        id    : 3,
        name  : 'Barry Allen',
        foods : ['Pizza', 'Sushi'],
        city  : 'Central City'
    },
    {
        id    : 4,
        name  : 'Diana Prince',
        foods : ['Burgers', 'Sushi'],
        city  : 'Themyscira'
    }
],

columns : [
    { field : 'name', text : 'Name', flex : 1 },
    {
        field    : 'foods',
        text     : 'Favorite foods',
        flex     : 1,
        renderer : ({ record, value }) => {
            if (record.isGroupHeader) {
                return value;
            }
            return value.join(', ');
        }
    },
    { field : 'city', text : 'City', flex : 1 }
]
});

```
![download.png](https://forum.bryntum.com/download/file.php?id=30238)
"

Reproduced on https://bryntum.com/products/grid/examples/basic/

https://github.com/user-attachments/assets/a1183cfe-6385-454c-815a-bde200bf4fdc

**Comment by ubaidkhan7** [comment]
@marciogurka @matsbryntse 

This issue still has some issues and one of the issue I found is when you try to empty value in "FAVORITE FOODS" cell and drag the row into another group this is crashing.

The first image shows dragged row being stuck after crash.
The second image show that cryptic bug.

<img width="589" alt="image" src="https://github.com/user-attachments/assets/a73ad467-c7f1-4878-8eff-d7a836c3c09b">

<img width="239" alt="image" src="https://github.com/user-attachments/assets/a37a67a2-5c40-4eb0-8ef3-217f7ff41a6a">

**Comment by bmblb** [comment]
@ubaidkhan7 I opened a separate ticket for your issue
