### ISSUE TITLE
Font awesome tree arrows too big on touch screen

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9819]
Windows:

<img width="568" alt="Screenshot 2024-08-14 at 10 40 54" src="https://github.com/user-attachments/assets/c6ec2f49-64eb-4dd6-b05c-f4779864c227">

Mac OS
<img width="484" alt="Screenshot 2024-08-14 at 10 43 32" src="https://github.com/user-attachments/assets/294eaba3-525b-4895-a3f7-d9aa0217595b">

**Comment by bmblb** [comment]
This is a touchscreen style 
![image](https://github.com/user-attachments/assets/1db81ff6-690b-4ecb-a9e9-3d0ade085518)
