### ISSUE TITLE
Change ProjectModel's `calendar` don't trigger sync

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#9848]
enable autoSync, change gantt.projectModel.calendar value. See no calendar changes in sync request.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30132&p=152953#p152953)

Dear, 

when i select from dropdown of the calendar field as in file "projectGantttoolbar.js" attached without any customization to the calendar(without any update) , and click save which is in another file also attached called "GanttToolbar",  then the gantt.project.sync() not execute , and the new calendar selected not sent , why ?.

i have attached also the app.js file which is the entry point of the application .

waiting for your support please!

**Comment by matsbryntse** [comment]
Related? https://github.com/bryntum/support/issues/5138
