### ISSUE TITLE
Deleted tasks appear after reapplying filters

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#988]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14415&p=73739)

Steps to Reproduce

Go to the advanced demo here https://www.bryntum.com/examples/gantt/advanced/
Filter the start date column to show tasks starting after 1 January, 2019. It doesn't really matter what the filter is however, just that a filter exists.
Delete the "Setup web server" task
In the browser console, type 
```
gantt.taskStore.filter()
```

You'll notice that the "Setup web server" task reappears along with its children. These tasks are still technically deleted (gantt.taskStore.changes.removed.length === 6) but they appear in the UI. Attempting to interact with them in any way results in JS errors.

The same error can be seen by applying any sort of filter, not just reapplying the same filters.
```
gantt.taskStore.filter({ property: 'endDate', operator: '<', value: new Date() })
```

**Comment by chuckn0rris** [comment]
PR: https://github.com/bryntum/bryntum-suite/pull/1658
