### ISSUE TITLE
Updating column text does not get reflected in State

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9892]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30233&p=153429#p153429)

Hi. We are persisting our grid state into Local Storage using the StateProvider functionality. We have noticed from version 5.6.10 to 5.6.11, the implementation has now changed to also persist the column text. This causes us some problems:

If we want to change the text of one or more of our columns, this won't be picked up by customers unless they also clear their local storage

This is perhaps more of a niche problem, but we have some columns whose text is generated dynamically when we instantiate the grid (depending on the current date), and this no longer works due to text being persisted.

This can be reproduced easily using the online state demo - https://bryntum.com/products/grid/examples/state/ - simply amend one of the column widths to trigger the saving of state, then edit the text of one of the columns in the editor - it doesn't show the new value.

Was this change intentional, or is it a bug? Is there a reference to this in the changelog? It was my expectation that only things that the user can easily change themselves (e.g. column widths / sorting etc.) would be persisted.

Thanks.

https://github.com/user-attachments/assets/8895c880-58b7-45c5-a58a-da71a4868f3b

**Comment by chuckn0rris** [comment]
related to /issues/9823
