### ISSUE TITLE
Errors when opening gantt with infinite scroll and collapsed graph

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9895]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30240&p=153456#p153456)

Hi,
while testing the latest Gantt version (v6.0.4), I discovered that when the Gantt starts with the graph collapsed and with the infinite scroll feature enabled, it throws an error in the console:

[b]Steps to reproduce it[/b]:
- open the infinite scroll example: [url]https://bryntum.com/products/gantt/examples/infinite-scroll/[/url]
- open the code editor
- add [b]StateProvider[/b] to the imports and this two lines of code inside the gantt configuration:
```
	stateId: 'pippo',
	stateProvider: new StateProvider({ storage: 'local' })
```
- collapse the graph part
- let the system refresh (i did it by adding a new line to the code on the right)
- the error is thrown in the console

https://github.com/user-attachments/assets/2f5665e6-bbe5-4e45-b7bc-9f8909007cc7

**Comment by FlowIT-JIT** [comment]
I'm very interested in a fix for his too.

**Comment by ghulamghousdev** [comment]
@FlowIT-JIT The issue is fixed and will be part of the next patch release. Meanwhile if you wanna try the solution, you can pick tonight's nightly build and check it out.

**Comment by FlowIT-JIT** [comment]
Fantastic - thanks @ghulamghousdev
