### ISSUE TITLE
Scheduler and Scheduler Pro not working with Firefox Version 115.14.0esr

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9896]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30239&p=153451#p153451)

In the Scheduler and Scheduler Pro Component Resources are not shown anymore.
I found out that in all of your Examples from the Scheduler and Scheduler Pro this Problem exists too.

Just go to https://bryntum.com/products/schedulerpro/examples/ and open any Example. No Data is shown with Firefox Version 115.14.0esr in every Example you provide. With any other Browser it is working fine.

Even in your Documentation Page from the Scheduler Pro the Live Demo is not shown (See attached Picture).

![bryntum_doc.png](https://forum.bryntum.com/download/file.php?id=30461)
![image](https://github.com/user-attachments/assets/aca6a683-3f73-47de-a3da-b86bc2fa8fcc)

Can you please take a closer look at the Problem ? We really need a Solution for this Problem.

Best regards
Bastian

**Comment by ghulamghousdev** [comment]
+1 for client asking for updates: https://forum.bryntum.com/viewtopic.php?p=153755#p153755

**Comment by willydee** [comment]
Also affects Grid.
