### ISSUE TITLE
Moving an infinitely weekly repeating event by drag&drop fails

### ISSUE THREAD

**Issue by jonek** [bryntum/support#9909]
When dragging an infinitely weekly repeating event from one weekday to another, the first event vanishes and the rest of the series is not moved.

This issue does not occur for recurring events with limited repeats.

Forum post: https://forum.bryntum.com/viewtopic.php?t=30259

Steps to reproduce in [Recurring events example](https://bryntum.com/products/calendar/examples/recurrence/):
- create an event on Monday and make it repeat infinitely on Mondays
- drag the first event of the series to Tuesday and confirm the change for all events of the series
- bug occurs: the first event vanishes and all other events stay on Monday
Example screen recording:

https://github.com/user-attachments/assets/ba128f03-1fdb-4a3c-84bc-e05191b4ee97

Example screen recording that shows the expected behavior when the event is limited to three recurrences:

https://github.com/user-attachments/assets/79b7e3ff-8552-43b8-b856-d8e4cceb279a

**Comment by ExtAnimal** [comment]
It worked in 5.6.13, and fails in 6.0.0, so some commit between those tags broke it...

**Comment by jonek** [comment]
Thanks for taking care about this so quickly.
