### ISSUE TITLE
animateTreeNodeToggle with locked columns places rows incorrectly

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9914]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=30269&p=153610#p153610)

Go to the following example and collapse, then expand the `Planning node` and see the issue. https://bryntum.com/products/grid/examples/lockedcolumnstree/.

https://github.com/user-attachments/assets/0459c7ff-d8e2-42e8-ba60-1d8a84e8e051

**Comment by ExtAnimal** [comment]
In `DataGenerator.generateData(5, true, (i+1)*100);`

The `true` parameter means generate random `rowHeight` fields in the records. That is a field used to control the row heights and so there are random row heights in the UI.

**Comment by hexasense** [comment]
Hi,
Why the 6.0.6 milestone has been removed? It would be urgent to get the fix.

**Comment by koszegil** [comment]
When can we expect this bugfix?

**Comment by ghulamghousdev** [comment]
@koszegil It will be part of the next patch release. PR only needs merging.

**Comment by koszegil** [comment]
Thank you!
