### ISSUE TITLE
Predecessor/successor lists miss tasks

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#9923]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30256&p=153577#p153577)

Steps to reproduce:
1. open advanced demo
2. replace tasks with:
```js
gantt.taskStore.data = [
    {
        "startDate": "2019-01-14",
        "endDate": "2019-01-15",
        "name: : "task 1",
        "duration": 1
    },
    {
        "startDate": "2019-01-14",
        "endDate": "2019-01-15",
        "name: : "task 2",
        "duration": 1
    },
    {
        "startDate": "2019-01-14",
        "endDate": "2019-01-15",
        "duration": 1,
        "name: : "task 3",
        "expanded": true,
        "children": [
            {
                "startDate": "2019-01-14",
                "endDate": "2019-01-15",
                "name: : "task 3-1",
                "duration": 1
            }
        ]
    }
]
```
3. start cell editing "task 1"

Result:  "Predecessors" column editor dropdown list has no "task 3-1" entry

**Comment by ghulamghousdev** [comment]
This issue is a duplicate and has been resolved here https://github.com/bryntum/support/issues/10291

Current release branch behaviour: 


https://github.com/user-attachments/assets/716f9fd4-ea76-46e7-a4f5-4ada8e1c53de
