### ISSUE TITLE
Top toolbar shrinks if window is not tall enough

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#994]
https://www.bryntum.com/examples/calendar/filtering/

<img width="1159" alt="Screenshot 2020-06-23 at 10 28 34" src="https://user-images.githubusercontent.com/218570/85379690-56f84d80-b53c-11ea-8e94-9cf24073b32f.png">

**Comment by ExtAnimal** [comment]
WHat's a proposed solution?

**Comment by matsbryntse** [comment]
Toolbar should never decrease in height

**Comment by matsbryntse** [comment]
<img width="973" alt="Screenshot 2020-07-01 at 14 21 44" src="https://user-images.githubusercontent.com/218570/86243177-35374000-bba6-11ea-84b7-d3bd229578e9.png">

Still see this in master
