### ISSUE TITLE
Aggregation demo total column shows only $0

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#9955]
![image](https://github.com/user-attachments/assets/4fec9586-51c9-4968-a228-fb3e1294b932)

**Comment by SergeyMaltsev** [comment]
Category column  should be wider
![image](https://github.com/user-attachments/assets/5678a6ac-d4d8-4321-afe9-170f1ed3b123)

**Comment by SergeyMaltsev** [comment]
```
static get fields() {
```

May be just `static fields = ...`

**Comment by khattakdev** [comment]
Duplicating an existing group adds `undefined-2` under `items` column
https://github.com/user-attachments/assets/b8e7ad77-a3fb-4879-a255-de8cbcdb8841
