### ISSUE TITLE
Date filters "today", "yesterday", "tomorrow" are not working properly

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9973]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30330&p=153962#p153962)

Hello,

We noticed that when filtering on a date field with the field option "today", "yesterday" or "tomorrow", the filtering is not correct. More specifically, lines with a date that is 1 day after the requested date are also displayed.

You can reproduce it in the Grid Filtering demo: https://bryntum.com/products/grid/examples/filtering/
I recorded this issue on 09/05/2024. So I updated the dates of 4 records as follows:
![Screenshot_1_noFilters.png](https://forum.bryntum.com/download/file.php?id=30631)
When I select the filter "yesterday", I get this result: the correct record for 09/04/2024, but the record for 09/05/2024 (today, not yesterday) as well:
![Screenshot_2_yesterday.png](https://forum.bryntum.com/download/file.php?id=30632)
When I select the filter "today", I get this result: the correct record for 09/05/2024, but the record for 09/06/2024 (tomorrow, not today) as well:
![Screenshot_3_today.png](https://forum.bryntum.com/download/file.php?id=30633)

I noticed the same issue for filters:
tomorrow: date 09/07/2024 is not filtered
this week: date 09/08/2024 is not filtered
this month: date 10/01/2024 is not filtered
So I guess the issue is present in all filters of that kind.

I looked for a config in the "filter" feature of the Grid that would solve this but could not find any.

Could you please have a look?

Thanks.
Best regards,

**Comment by isglass** [comment]
Duplicated of https://github.com/bryntum/support/issues/9767
