### ISSUE TITLE
Editor does not open on single click for assigned resources column with `triggerEvent : 'cellclick'`

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9981]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=30338&p=154010#p154010)

Hello,
We configured the Gantt to be single click edit, this was working fine in v5 of the Gantt but since moving to V6, single click worked in other cells but not the Assigned Resource field. With the code added to use cell click edit, the Assigned Resource cell was not clickable at all. This has been repro'd on your demos adding in the following code:

```
cellEdit : {
triggerEvent : 'cellclick'
},
```

https://github.com/user-attachments/assets/a1f1c259-2a5c-4056-889a-7744857819d0

Is this a known issue?
Paul

**Comment by pwmather** [comment]
Thanks @ghulamghousdev  - we'll take a look at that

**Comment by pwmather** [comment]
Was this an undocumented change in v6 @ghulamghousdev  as it worked fine before when we were on v5.

**Comment by ghulamghousdev** [comment]
@pwmather this is a regression and not something intentional that is why no docs exist for it. We will fix it soon. Hopefully it will be part of the next patch release.
