### ISSUE TITLE
Not clear docs in part of adding new event in `resourceId` notation used

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#9992]
If an event added with `resouceId` notation, crudManager expects to have assignmentStore update in response. It's not mentioned in docs now.

[Forum post](https://forum.bryntum.com/viewtopic.php?t=30351&start=10)

**Comment by chuckn0rris** [comment]
It was not required to have assignments in response until v5.6. marked as regression

**Comment by knobel-dk** [comment]
@matsbryntse Any news on this one? Hoping it can make the next release 😄
